### ISSUE TITLE
【問題】表單框線設定 若沒有隱藏進階設定 會與下方按鈕框線設定連動

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#1000]
表單元件的框線設定 如果沒有把進階設定收合的話
下面按鈕的框線設定就會與表單元件的框線設定連動
如果把表單元件的 進階設定 收合的話 一切就沒問題
這邊附上動圖說明
如果還有不清楚的地方
歡迎來問我~~

![20190129_142356](https://user-images.githubusercontent.com/34263719/51888793-6cfaf080-23d2-11e9-881e-c0f57a59670a.gif)

**Comment by AnitaRyzo** [comment]
『表單元件』的「頁面設定」之框線與陰影，已不會與「按鈕設定」之框線與陰影，互相影響
![image](https://user-images.githubusercontent.com/41721950/52778378-dd676a00-3080-11e9-83cc-9cacf1e81f8a.png)
◎◎ 20190214確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『表單元件』的「頁面設定」之框線與陰影，已不會與「按鈕設定」之框線與陰影，互相影響
![image](https://user-images.githubusercontent.com/41721950/55711629-a4fc6080-5a1f-11e9-942f-92d7143726f4.png)
◎◎ 20190408確認以上正式環境內容 ◎◎
