### ISSUE TITLE
【建議】收縮區塊的箭頭方向

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#1001]
介面上收縮區塊展開與收合的方向
與一般使用習慣不太一樣

目前
關閉狀態-箭頭向下
<img width="1280" alt="2019-01-29 2 38 15" src="https://user-images.githubusercontent.com/34293268/51889386-6e2d1d00-23d4-11e9-9aac-83f6deb6f270.png">

展開狀態-箭頭向右
<img width="1280" alt="2019-01-29 2 38 24" src="https://user-images.githubusercontent.com/34293268/51889391-71c0a400-23d4-11e9-9cf9-6a194c527b1e.png">

建議可以修改成像下圖這樣
關閉狀態-箭頭向右
展開狀態-箭頭向下
<img width="717" alt="2019-01-29 12 19 12" src="https://user-images.githubusercontent.com/34293268/51889436-9452bd00-23d4-11e9-918d-d6dbfb6330b4.png">

**Comment by AnitaRyzo** [comment]
箭頭方向已依照指示修改
![image](https://user-images.githubusercontent.com/41721950/54891907-329d6380-4eea-11e9-8e74-22a0c2e4cd2a.png)
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55772839-a7fb5d80-5ac0-11e9-94e2-2db829bb2015.png)
◎◎ 20190409確認以上正式環境內容 ◎◎
