### ISSUE TITLE
【建議】數據多個專案時下方的點點並排

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#1002]
當現在的專案數較多時
在數據後台的專案列表中
下方的點點並排有點近 建議調整距離
<img width="1194" alt="2019-01-30 10 35 29" src="https://user-images.githubusercontent.com/34560641/51954410-11d10880-247b-11e9-80e4-900d9c052f3a.png">

**Comment by AnitaRyzo** [comment]
已加高雙層點點的距離
![image](https://user-images.githubusercontent.com/41721950/55045557-1c71dd80-5079-11e9-9ba9-ba48a771cf7e.png)
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已加高雙層點點的距離
![image](https://user-images.githubusercontent.com/41721950/55773149-f0674b00-5ac1-11e9-9ba0-f28dcbb72db7.png)
◎◎ 20190409確認以上正式環境內容 ◎◎
