### ISSUE TITLE
【建議】希望WEBA內的輸入欄位可以清空

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1003]
像是獎品數量、XY軸、尺寸，這些欄位都希望可以先完全刪掉再開始輸入

而不是規定一定要有一個數值在輸入框內

**Comment by ai015606220** [comment]
請問理由是?

**Comment by weilyn** [comment]
如圖，
使用者習慣為點選鍵盤的delete鍵或backspace來將數值刪除以後再輸入新的數值
但是目前的WEBA最多只能將數值清空至1，無法完全清空
如果要修改數值變成要用滑鼠圈選起再做修改會比較不方便

<img width="328" alt="2019-01-30 4 43 11" src="https://user-images.githubusercontent.com/34327325/51969295-04ce0c80-24af-11e9-8955-4a0284face87.png">

**Comment by ai015606220** [comment]
會這樣的原因是這些輸入數值的輸入框都會即時的去改動畫布上的內容
這樣如果是空值就會出錯
如果要按照你的需求讓他能全部刪除   
就需要仔細考慮各種情境的防呆

**Comment by weilyn** [comment]
輸入線停留在框內的時候，數值不會即時送出去，直到我鍵入enter，或是點取其他地方的時候，才會將數值套用到元件上。
當我鍵入enter或是點選其他地方時，欄位若是空白的，則提示請輸入正確數值，並跳回原先的數值

**Comment by weilyn** [comment]
@Samasianspock @ryzojudy

**Comment by ai015606220** [comment]
我傾向空白時讓它等於0
我認為如果改掉現在這種即時改變的機制  之後又會被要求加上去
至於第二點  我依然是傾向  它沒有輸入就補上0

**Comment by Gabe-Liu** [comment]
如果是點擊輸入框時，自動選起裡面的內容，這樣是否就可以了?

**Comment by weilyn** [comment]
聽起來可以

**Comment by AnitaRyzo** [comment]
輸入的數值從「輸入點」變成「選取」
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
點擊欄位不是出現「輸入點」，而是如下的「選取」
![image](https://user-images.githubusercontent.com/41721950/55791719-b6ae3880-5af1-11e9-89fa-6cb828fdc0a1.png)
◎◎ 20190409確認以上正式環境內容 ◎◎
