### ISSUE TITLE
【建議】資料綁定中部份文字變動

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#1009]
修改一：
(Weilyn建議)
名單擋案處的欄位定義「數字」建議改為「數值」
位置：
![image](https://user-images.githubusercontent.com/34263719/51973182-0223e500-24b8-11e9-8a3d-0cc857c1bab0.png)

修改二：
(Wilma建議)
初次進入分類設定的「稍後設定」按鈕文字可以改成「跳過」
位置：
![image](https://user-images.githubusercontent.com/34263719/51973400-824a4a80-24b8-11e9-8cb5-22b9ccd73193.png)

修改三：
(Wilma建議)
分類設定中的「分類排序」改成「定義分類」
位置：
![image](https://user-images.githubusercontent.com/34263719/51973519-c9384000-24b8-11e9-83c4-0894dea40745.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55390014-ea74e580-5568-11e9-80f5-0d2fbf08f61e.png)
![image](https://user-images.githubusercontent.com/41721950/55390135-26a84600-5569-11e9-8236-14646aed2c85.png)
![image](https://user-images.githubusercontent.com/41721950/55390112-185a2a00-5569-11e9-8892-a88e5675c5e7.png)
◎◎ 20190402確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已如上綠框修正
◎◎ 20190403確認以上正式環境內容 ◎◎
