### ISSUE TITLE
顏色設定-色碼後面都會多兩個ff

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#102]
如圖～～～

<img width="181" alt="2018-05-11 9 40 47" src="https://user-images.githubusercontent.com/34293268/39902193-6964148a-54ff-11e8-96de-d8a6b238198d.png">
<img width="182" alt="2018-05-11 9 40 08" src="https://user-images.githubusercontent.com/34293268/39902194-6a3b1d54-54ff-11e8-9a4a-348a6956af4f.png">

**Comment by ryuichl** [comment]
那是透明度吧

**Comment by eatinggg** [comment]
好喔收到
現在貼上色碼例如 feda55 
要自己再加上# 顏色才會改變
希望之後可以做成貼上 feda55 確定以後就直接改變顏色

**Comment by ai015606220** [comment]
目前這個套件的規則就是這樣，所以目前先不考慮做這項優化

**Comment by eatinggg** [comment]
那就當作對未來的期許吧！！！！
