### ISSUE TITLE
【建議】數據的預設時間是不是可以改為近30日

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#1024]
(Roy建議)
目前數據的預設時間是「近7日」
但通常都會沒有數據
是不是可以改為「近30日」或是改成發佈日期往後30日

**Comment by AnitaRyzo** [comment]
發佈日期往後30日
![image](https://user-images.githubusercontent.com/41721950/54519866-77814180-49a2-11e9-85de-554380721c13.png)
◎◎ 20190318確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55773206-2278ad00-5ac2-11e9-8aab-5e348723103f.png)
◎◎ 20190409確認以上正式環境內容 ◎◎
