### ISSUE TITLE
【測試環境】無法切換電子申請書的回覆

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1028]
電子申請書只顯示第一筆表單的回覆，切換不會改成其他的申請書回覆
![image](https://user-images.githubusercontent.com/41721950/52603656-c2d79a00-2ea2-11e9-8c28-1ae567a4209c.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
請問你的篩選時間是有打開的嗎??

**Comment by AnitaRyzo** [comment]
我沒有找到「篩選時間」的功能耶
![image](https://user-images.githubusercontent.com/41721950/52605026-126c9480-2ea8-11e9-95c3-652dffe702a3.png)

**Comment by AnitaRyzo** [comment]
可切換不同表單的內容
![image](https://user-images.githubusercontent.com/41721950/52696728-ab83d400-2faa-11e9-94ec-cb33b29779a6.png)
◎◎ 20190213確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55457596-fd48f200-561c-11e9-89cf-14b043a10063.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
