### ISSUE TITLE
頁面管理命名

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#103]
希望左側頁面管理命名後
可以跟選單架構設定的 項目-自動 裡的名稱做連動

就是～希望我在左側命名完以後
畫布上可以直接得到我所命名的頁面名稱(可以嗎)

<img width="916" alt="2018-05-11 9 53 03" src="https://user-images.githubusercontent.com/34293268/39902551-25f043de-5501-11e8-9c71-3bb4222802e9.png">

**Comment by Gabe-Liu** [comment]
選單架構的頁面名稱是可以自訂的，因此不會跟左側的頁面名稱作連動
