### ISSUE TITLE
【測試環境】跨帳號查看電子申請書，只顯示回覆日期

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1036]
跨帳號查看『電子申請書』
問題：除了『專案名稱』與『回覆日期』，未顯示表單預覽，也未有題目與答覆
![image](https://user-images.githubusercontent.com/41721950/52702374-f99ed480-2fb6-11e9-8940-3f7f0b94c020.png)

在個人帳號「表單管理」後台看到的狀況如下，只用『日期』區分，較難找出所需資料是哪一筆...
建議：黃框內的ID顯示可否更顯而易懂?
![image](https://user-images.githubusercontent.com/41721950/52702290-d116da80-2fb6-11e9-847c-9efa0711c6cd.png)
以上問題與建議請協助處理，感恩~

**Comment by ai015606220** [comment]
關於第二點  我們並沒有適合顯示的資訊

**Comment by AnitaRyzo** [comment]
跨帳號查看電子申請書的內容如下所示
![image](https://user-images.githubusercontent.com/41721950/52834314-3f28e200-311c-11e9-8a18-025c0abeae18.png)
◎◎ 20190215確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55460749-54eb5b80-5625-11e9-9784-44fcf262d26f.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
