### ISSUE TITLE
【問題】臉書工具內嵌型 的群組圖層順序問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1038]
圖1是編輯區的樣式，及圖層列表，可以看到臉書工具在最上層，其中中綠色色塊跟圖片元件是一個群組
<img width="960" alt="2019-02-14 9 28 53" src="https://user-images.githubusercontent.com/34327325/52756145-6196fe80-303b-11e9-84a2-b769e40368b6.png">

接著我想把全部物件群組，圖層的順序就出現變化了，臉書工具被壓在後面
<img width="982" alt="2019-02-14 9 29 08" src="https://user-images.githubusercontent.com/34327325/52756160-6d82c080-303b-11e9-9233-0a928bfc640c.png">

**Comment by AnitaRyzo** [comment]
群組前
![image](https://user-images.githubusercontent.com/41721950/54574232-8b708600-4a2a-11e9-8b10-80512b80c3ac.png)
群組後
![image](https://user-images.githubusercontent.com/41721950/54574310-d38fa880-4a2a-11e9-91d8-9f3a77f03d29.png)
◎◎ 20190319確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55844889-151afb80-5b72-11e9-9a9b-e7fc6fe11799.png)
![image](https://user-images.githubusercontent.com/41721950/55844875-0a606680-5b72-11e9-8d49-edc9a7ef5811.png)
◎◎ 20190410確認以上正式環境內容 ◎◎
