### ISSUE TITLE
選單的高度bar

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#104]
高度bar 他不能手動輸入  只能用拖拉的QQ

<img width="278" alt="2018-05-11 10 25 07" src="https://user-images.githubusercontent.com/34293268/39903460-e402f764-5505-11e8-8d54-4324b003c314.png">

**Comment by Gabe-Liu** [comment]
此欄位的值限制為 50~90 因此當你清空時，會回復到最小值50，妳必須要選取5後修正即可
