### ISSUE TITLE
【測試環境】互動元件的樣式與測試失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1040]
1.所有互動元件的樣式選擇畫面全黑
![image](https://user-images.githubusercontent.com/41721950/52759557-44682d00-3047-11e9-9e01-2db0f57e7ac5.png)

2.所有互動元件的測試結果失效
![image](https://user-images.githubusercontent.com/41721950/52759381-9d839100-3046-11e9-990e-7ff4b1b7abab.png)

3.戳戳樂的「格數設定」不會即時更新
![image](https://user-images.githubusercontent.com/41721950/52758340-d457a800-3042-11e9-99fa-df2ac9aeec01.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
測試抽獎的部分已修正

**Comment by AnitaRyzo** [comment]
1.所有互動元件的樣式選擇皆有顯示
2.所有互動元件的測試結果皆可執行
3.戳戳樂的「格數設定」會即時更新
![image](https://user-images.githubusercontent.com/41721950/52842329-b6b93a00-3139-11e9-9fab-d6bfd2837cf3.png)
◎◎ 20190215確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
1.所有互動元件的樣式選擇皆有顯示
2.所有互動元件的測試結果皆可執行
3.戳戳樂的「格數設定」會即時更新
◎◎ 20190409確認以上正式環境內容 ◎◎
