### ISSUE TITLE
【測試環境】互動元件的狀態頁未依照設定

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1041]
左邊編輯區依照設定，但右邊執行後卻與設定不同
狀態(提示)頁的「未中獎」
![image](https://user-images.githubusercontent.com/41721950/52758847-c4d95e80-3044-11e9-9f20-b3426607b847.png)
狀態(提示)頁的「恭喜中獎」
![image](https://user-images.githubusercontent.com/41721950/52758987-46c98780-3045-11e9-8e5c-e32f3bb7c148.png)
狀態(提示)頁的「中獎紀錄」
![image](https://user-images.githubusercontent.com/41721950/52759299-47165280-3046-11e9-80d2-1ea861a6360b.png)
當「獎項已抽完」出現的是以下的提示訊息，非設定
![image](https://user-images.githubusercontent.com/41721950/52761364-133f2b00-304e-11e9-8a3e-831712a4bc5c.png)

以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
抽完的部分已修正

**Comment by AnitaRyzo** [comment]
互動元件的狀態頁已依照設定變更
◎◎ 20190218確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
X 狀態(提示)頁的「中獎紀錄」未依照設定
![image](https://user-images.githubusercontent.com/41721950/55786430-c96f4000-5ae6-11e9-9eb2-05302f967c1b.png)
狀態(提示)頁的「未中獎」&狀態(提示)頁的「恭喜中獎」&當「獎項已抽完」已可正確執行
◎◎ 20190409確認以上正式環境內容 ◎◎
