### ISSUE TITLE
【測試環境】內嵌與圖示元件消失於編輯畫布中

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1042]
編輯器畫面可從圖層看到元件是存在的
![image](https://user-images.githubusercontent.com/41721950/52768558-d0d71780-3068-11e9-8d2c-98dc4f11eb73.png)
瀏覽器執行可以看到元件
![image](https://user-images.githubusercontent.com/41721950/52768647-07149700-3069-11e9-903d-ab322570d61a.png)

錯誤訊息如下紅字
![image](https://user-images.githubusercontent.com/41721950/52768627-f9f7a800-3068-11e9-8fdd-c196092e6dfd.png)
以上情況請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
內嵌元件沒問題，是圖示元件錯誤導致的

**Comment by AnitaRyzo** [comment]
內嵌元件在儲存時會閃現，是因為執行快取畫面
圖示元件與內嵌元件已可同時存在
![image](https://user-images.githubusercontent.com/41721950/52843534-617f2780-313d-11e9-8284-d23c25660354.png)
◎◎ 20190215確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
內嵌網頁與內嵌程式碼在儲存時會閃現，是因為執行快取畫面
執行完成儲存後，圖示元件與內嵌元件已可同時存在
![image](https://user-images.githubusercontent.com/41721950/55845892-3da4f480-5b76-11e9-8072-eef688a75d65.png)
◎◎ 20190410確認以上正式環境內容 ◎◎
