### ISSUE TITLE
【測試環境】題目過長造成PDF未完整顯示題目

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1048]
電子表單題型如下
1英文標題+2數字標題+3中文標題+4英文標題+5數字標題
![image](https://user-images.githubusercontent.com/41721950/52984192-5ec84f00-3429-11e9-9534-6e92cd2afcf3.png)
![image](https://user-images.githubusercontent.com/41721950/52984197-638d0300-3429-11e9-9dcf-e8841e49909b.png)

PDF顯示的畫面如下，
1. 只有1英文標題+3中文標題+5數字標題的題目與答覆，且題目被卡斷
2. 缺少2數字標題+4英文標題的題目與答覆
![image](https://user-images.githubusercontent.com/41721950/52984341-fb8aec80-3429-11e9-8a2a-9c412ad25141.png)
請協助處理此問題，感恩~

**Comment by Gabe-Liu** [comment]
由於此PDF套件無法針對一行過長的英文、數字自動換行，因此手動加入判定，如果字元數超過26個，則在之後接一個空白字元。

**Comment by AnitaRyzo** [comment]
英文、數字會跟著空白或逗點斷行，但是中文的斷點就過長了...
![image](https://user-images.githubusercontent.com/41721950/53234522-a91c2b00-36ca-11e9-97fe-6c99bcdb6a48.png)
◎◎ 20190222確認以上測試環境內容 ◎◎

**Comment by Gabe-Liu** [comment]
請 @AnitaRyzo 大大 在幫忙測試確認一下

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/54894489-d4767d80-4ef5-11e9-863f-20df4f423e01.png)
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55456873-c07bfb80-561a-11e9-8696-60bd7745991a.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
