### ISSUE TITLE
【建議】審核後台預設以送出審核的時間為依據排列

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1049]
無論是
「專案審核」、「專案發佈」、「套版審核」

審核人可能會累積很多專案才進行審核，並且進入後台以後應該是想看到剛送出審核的專案
因為專案創建日期並不能表示活動上線的急迫性，但是送出審核的時間相顯就比較有依據，
但是如果最新申請審核的就擺在最前面，可能造成有些比較早申請的被往後推，而被擱置

所以應該要依**「送出審核的時間」**為主要依據，越早送出審核的就會排在越前面，
並且以此作為**「預設的排序方式」**
「專案審核」、「專案發佈」、「套版審核」這三項都應該比照類似的方式的方式調整

提供給UI / UX 討論看看
<img width="1375" alt="2019-02-19 11 48 57" src="https://user-images.githubusercontent.com/34327325/53004058-4ed15f00-346b-11e9-8d12-e8b78d15d856.png">

**Comment by ryzojudy** [comment]
專案審核：
	下方專案區：各個待審核的專案，越舊的專案出現在越前面
	針對專案區可執行動作：排序(依申請審核時間)、搜尋關鍵字

專案發佈：
	下方專案區：各審核通過的專案，越舊的專案出現在越前面
	針對專案區可執行動作：排序(依通過審核時間)、搜尋關鍵字

套版審核：
	下方專案區：各待審核套版，越舊的出現在越前面
	針對專案區可執行動作： 排序(依申請審核時間)、搜尋關鍵字

**Comment by leonlin6** [comment]
已與 @ryzojudy  確認新增的排序下拉選單內容文字為「案送審時間排序」
已與 @eatinggg  確認新增的排序下拉選單內容「案送審時間排序」使用icon為「時鐘圖案」

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58395107-2f089300-8079-11e9-959f-656a91e4c467.png)

![image](https://user-images.githubusercontent.com/41721950/58395111-36c83780-8079-11e9-83f0-799a4447f7fd.png)
◎◎ 20190527確認以上測試環境內容 ◎◎

**Comment by ryzojudy** [comment]
根據業務反應和EDM的文字統一
需要變更文字內容

創建時間正序  ->  創建時間新到舊
創建時間倒序  ->  創建時間舊到新

以上麻煩了~
感謝!!

**Comment by leonlin6** [comment]
@ryzojudy  已修改。

![001](https://user-images.githubusercontent.com/29088297/59479017-01e81d00-8e8e-11e9-96b9-5a87b200a1ab.jpg)

Leon_20190614

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60556127-69e5a100-9d72-11e9-9e4e-65b471ea2ae0.png)
![image](https://user-images.githubusercontent.com/41721950/60556830-8b945780-9d75-11e9-9380-942e000a0f1b.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
