### ISSUE TITLE
【圖層群組】目前為無法直接解散群組狀態

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#105]
希望“群組按鈕”在選取到群組的項目時能變成：解散群組鍵“（Gabe知道）
兩種情境：
選取到母層時：為解散全部物件
![2018-05-11 12 14 09](https://user-images.githubusercontent.com/37163894/39906582-1cfafdfe-5516-11e8-9a13-30365432e33b.png)
選取到子層時：為單獨解散該物件
![2018-05-11 12 14 25](https://user-images.githubusercontent.com/37163894/39906588-29962976-5516-11e8-85f8-544f747f3a5c.png)
希望有快捷鍵（Alt+G）

**Comment by Gabe-Liu** [comment]
群組的快捷鍵為 (Ctrl + G)
目前已做到群組解鎖  ~

單獨解散再考慮
