### ISSUE TITLE
【測試環境】抽獎禮盒素材掉圖

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1059]
正式、測試環境都有這個問題

![image](https://user-images.githubusercontent.com/11918396/53142457-e8fde800-35ce-11e9-9376-badec29267c5.png)

![image](https://user-images.githubusercontent.com/11918396/53142796-28790400-35d0-11e9-8ebf-4479a34360f8.png)

如圖所示

**Comment by AnitaRyzo** [comment]
目前已無找不到圖片的錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/53218230-53c62680-3696-11e9-8321-8b5a9b2bc314.png)
◎◎ 20190222確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
目前已無找不到圖片的錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/55855390-f3356f00-5b99-11e9-8ce3-eb98a1be7d2a.png)
![image](https://user-images.githubusercontent.com/41721950/55855506-4d363480-5b9a-11e9-8719-304bd788523b.png)
◎◎ 20190410確認以上正式環境內容 ◎◎
