### ISSUE TITLE
【問題】表格工具的設定表格內容視窗

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1064]
設定表格內容視窗在不特別去關閉的情況下
直接去點選其他元件，會出現空白的視窗內容

<img width="959" alt="2019-02-23 10 44 11" src="https://user-images.githubusercontent.com/34327325/53280695-36f22780-3758-11e9-9407-d8de69cfae3f.png">
<img width="904" alt="2019-02-23 10 44 05" src="https://user-images.githubusercontent.com/34327325/53280697-39ed1800-3758-11e9-9bad-32b36637183b.png">

**Comment by AnitaRyzo** [comment]
點選其他元件，表格內容編輯視窗會自動關閉
◎◎ 20190225確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
點選其他元件，表格內容編輯視窗會自動關閉
◎◎ 20190410確認以上正式環境內容 ◎◎
