### ISSUE TITLE
【問題】動畫的旋轉方向

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1065]
將元件設定旋轉淡入以及旋轉淡出，
發現在編輯區及30分鐘預覽裡，方向不一致
再麻煩查看
並且，當我連續使用這兩個動畫的時候，元件會有閃動的情況
<img width="323" alt="2019-02-23 11 10 28" src="https://user-images.githubusercontent.com/34327325/53280960-ec72aa00-375b-11e9-861b-70af0f5325ba.png">
<img width="392" alt="2019-02-23 11 12 44" src="https://user-images.githubusercontent.com/34327325/53280963-fa282f80-375b-11e9-9775-20362df10990.png">

**Comment by AnitaRyzo** [comment]
※編輯區及30分鐘預覽裡，方向不一致
正確的是向左旋轉淡入，向右旋轉淡出
在iOS系統的瀏覽器(Chrome、Firefox、Safari)中，向左旋轉淡入，向左旋轉淡出
以上補充，感恩~

**Comment by AnitaRyzo** [comment]
手機iOS系統的瀏覽器(Chrome、Firefox、Safari)中，也是向左旋轉淡入，向右旋轉淡出
即使開啟元件的「動畫循環」已不會閃一下再動
◎◎ 20190226確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
手機iOS系統的瀏覽器(Chrome、Firefox、Safari)
1.向左旋轉淡入，向右旋轉淡出
2.即使開啟元件的「動畫循環」已不會閃一下再動
小問題：Firefox若多個元件同時設定旋轉，速度會不一樣
◎◎ 20190410確認以上正式環境內容 ◎◎
