### ISSUE TITLE
【建議】QR code的圖片填充先給預設圖片

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1068]
QR code的圖片填充類型
可否像刮刮卡一樣先給預設的圖片，不要呈現完全空白
![image](https://user-images.githubusercontent.com/41721950/53463518-0ffe6300-3a82-11e9-833f-72d1cb535683.png)

![image](https://user-images.githubusercontent.com/41721950/53464059-f2ca9400-3a83-11e9-9b78-a64dc35d9039.png)
以上建議請參考，感恩~

**Comment by eatinggg** [comment]
修改後如下圖
建議可以在預設狀態放上圖片，右側預設呈現長相
使用者直接上傳自己的圖片或刪除預設圖
再請 @liucwlewis 上傳到zeplin～感謝～

<img width="737" alt="螢幕快照 2019-03-15 上午10 50 48" src="https://user-images.githubusercontent.com/34293268/54405233-e34c7b80-4710-11e9-8cb5-b25325e5e86f.png">

**Comment by AnitaRyzo** [comment]
填充圖已如下所示，而商標圖為方便日後客戶放置客戶商標圖，故不預設為WEBA商標
![image](https://user-images.githubusercontent.com/41721950/54575389-e4dab400-4a2e-11e9-9432-9e210f2a170f.png)
◎◎ 20190319確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55856523-2af1e600-5b9d-11e9-81cd-e836be9669ac.png)
◎◎ 20190410確認以上正式環境內容 ◎◎
