### ISSUE TITLE
【問題】電腦版的表單按鈕轉跳抓不到提示項目

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1070]
從手機版複製了表單，這個表單在手機版已經製作好送出按鈕轉跳提示頁面A

發佈後發現在電腦版填寫完以後，不會跳出提示A
檢查了設定值，發現提示仍然連結著手機版的提示頁面A，只是沒反應

接著在電腦版裡建立了提示頁面B
發現電腦版裡的表單完全無法看到該項目B的選項

請問按鈕轉跳可以連結提示嗎？不行的話可能要關閉這個選項
除此之外也無法抓到在電腦版頁面設置的錨點

<img width="322" alt="2019-03-05 12 16 22" src="https://user-images.githubusercontent.com/34327325/53781074-328cf200-3f42-11e9-9e70-be47887c8d5b.png">
<img width="547" alt="2019-03-05 12 16 33" src="https://user-images.githubusercontent.com/34327325/53781077-33258880-3f42-11e9-9e71-b60e9b897596.png">

**Comment by AnitaRyzo** [comment]
圖片、圖示、按鈕三個元件，若從手機版複製到電腦版
『連結設定』的『選擇提示』下拉選單是「電腦版」的提示頁
但表單元件不管是否從手機版複製到電腦版，或是直接在電腦版新增
『連結設定』的『選擇提示』下拉選單都是「手機版」的提示頁
以上補充提供參考，感恩~

**Comment by AnitaRyzo** [comment]
若從手機版複製到電腦版
在電腦版『連結設定』的『選擇提示』下拉選單是「電腦版」的提示頁
![image](https://user-images.githubusercontent.com/41721950/54580316-81f31800-4a42-11e9-8880-aafc6b045824.png)
在手機版『連結設定』的『選擇提示』下拉選單是「手機版」的提示頁
![image](https://user-images.githubusercontent.com/41721950/54580342-a5b65e00-4a42-11e9-8644-6e9df7698ab0.png)
◎◎ 20190319確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
電腦版『連結設定』的『選擇提示』下拉選單是「電腦版」的提示頁
![image](https://user-images.githubusercontent.com/41721950/55715256-f4925a80-5a26-11e9-8244-19144bfc489b.png)
手機版『連結設定』的『選擇提示』下拉選單是「手機版」的提示頁
![image](https://user-images.githubusercontent.com/41721950/55715384-34594200-5a27-11e9-9cab-d8acc5386ca5.png)
◎◎ 20190408確認以上正式環境內容 ◎◎
