### ISSUE TITLE
【建議】希望畫布外的內容也能呈現在實際手機上

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#1071]
實際的畫布是坐滿版的畫面，但實際上會因為裝置的比例不同，可能會跑出白邊
<img width="319" alt="2019-03-05 3 10 49" src="https://user-images.githubusercontent.com/37163894/53793498-fde06100-3f68-11e9-8299-bfac3a5f878f.png">
（畫布的畫面）

![img_8d5b7c7868f7-1](https://user-images.githubusercontent.com/37163894/53793696-5c0d4400-3f69-11e9-87fb-c8e866bdd112.jpeg)
（實際的畫面）

希望能在比例不同時，把畫布外的畫面也呈現出來，有點像印刷出血的感覺～

**Comment by ryuichl** [comment]
@Gabe-Liu  @ai015606220

**Comment by weilyn** [comment]
<img width="382" alt="螢幕快照 2019-03-22 下午5 57 49" src="https://user-images.githubusercontent.com/34327325/54815142-3d7aad00-4ccc-11e9-8f4a-24ecc9959880.png">

目前這個做法要小心考慮到有製作上下框架的使用情境

**Comment by Gabe-Liu** [comment]
現在添加一個開關，看是否要顯示畫布外的內容，預設是關閉

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55206782-af924b00-5212-11e9-8dec-1fe3ff4fd87a.png)
◎◎ 20190329確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55860909-d56f0680-5ba7-11e9-9b45-dccb60001a0f.png)
◎◎ 20190410確認以上正式環境內容 ◎◎
