### ISSUE TITLE
【問題】設立域名的專案應歸類於已發佈專案，故刪除專案的權限有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1076]
帳號權限設定如下
![image](https://user-images.githubusercontent.com/41721950/53867846-a8bb5280-402f-11e9-9227-ea04af93d470.png)
AAB專案設立『域名』後已通過審核並發佈→被認定無刪除權限；
而AAD專案設立『域名』後儲存→定義上**此專案已發佈，故無刪除權限**。
但現在歸類於「未發佈專案」，所以可以執行刪除，但是頁面重新整理後又會重新出現此專案...
![image](https://user-images.githubusercontent.com/41721950/53867672-4bbf9c80-402f-11e9-8d6f-e8a84aa0e24f.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
@ryuichl 請問是不是有設定域名後都會被後台判斷成是已發佈的專案??

**Comment by ryuichl** [comment]
目前是這樣沒錯
我看一下要不要調整權限的判定
@ai015606220

**Comment by AnitaRyzo** [comment]
完全沒有刪除權限時
![image](https://user-images.githubusercontent.com/41721950/54587007-c4741f00-4a59-11e9-97ba-afd324e7ac8e.png)

僅開啟『刪除未發布專案』的權限
![image](https://user-images.githubusercontent.com/41721950/54587163-35b3d200-4a5a-11e9-913a-dcb34444dc31.png)
AAM-無域名、AAL-有域名、AAK-有域名且通過審核→皆有刪除權限如下
![image](https://user-images.githubusercontent.com/41721950/54587058-eb325580-4a59-11e9-9618-48da34adbdd1.png)
刪除三個專案後重整頁面，僅AAM-無域名的專案真的消失...
![image](https://user-images.githubusercontent.com/41721950/54587036-d6ee5880-4a59-11e9-9bc7-902db0f13730.png)
請協助再次確認權限，感恩~

**Comment by ai015606220** [comment]
@ryuichl 目前還有一種情況會發生問題，是專案從未發佈過 + 已設定域名，會被判斷成已發佈的專案，可能是因為專案預設的online屬性是true

前端的判斷是:
已發佈 project.structure_prod !== '[]' && project.online
未發佈 project.structure_prod === '[]' || !project.online

**Comment by AnitaRyzo** [comment]
已可刪除AAM-無域名、AAL-有域名、AAK-有域名且通過審核
◎◎ 20190319確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已可刪除BBA-無域名、BBB-有域名、BBC-有域名且通過審核
![image](https://user-images.githubusercontent.com/41721950/55865266-93968e00-5bb0-11e9-9e35-ab9f723e99ce.png)
◎◎ 20190410確認以上正式環境內容 ◎◎
