### ISSUE TITLE
【建議】表單題目編輯頁的教學提示有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1081]
點擊右側『題目類型』新增表單題目，而「拖曳」只作用在題目排序
![image](https://user-images.githubusercontent.com/41721950/53939524-44ab9380-40ee-11e9-9f55-f980270a9f97.png)
請協助修改文字敘述，感恩~

**Comment by ai015606220** [comment]
拖曳也可以新增表單題目

**Comment by AnitaRyzo** [comment]
是我誤會了，感謝解謎
