### ISSUE TITLE
【問題】無查看數據權限，「數據後台」的錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1082]
當「帳號管理」權限如下所示
![image](https://user-images.githubusercontent.com/41721950/53944425-4ed38f00-40fa-11e9-9997-b1068993d891.png)
在「專案管理」的專案已確實關閉查看數據的路徑
![image](https://user-images.githubusercontent.com/41721950/53945226-1df45980-40fc-11e9-8a27-54ad4e62ae80.png)
問題一：點選「數據後台」未顯示數據，錯誤訊息如右
![image](https://user-images.githubusercontent.com/41721950/53945415-8ba08580-40fc-11e9-8f50-03fb61baaab4.png)
問題二：是否還需要關閉「專案管理」的數據路徑??
以上狀況請協助處理，感恩~

**Comment by ai015606220** [comment]
Duplicate of #1074
