### ISSUE TITLE
【問題】社群註冊登入後修改密碼無須輸入舊密碼

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1085]
情境：利用google註冊start201808@gmail.com
若直接在電子信箱輸入此帳號與密碼，無法登入
內部提示訊息為『用戶密碼尚未設置』
![image](https://user-images.githubusercontent.com/41721950/54094768-3905e880-43de-11e9-9da4-6c7a66d5de47.png)
登入後至「帳號管理」頁想利用「修改密碼」配置此帳號的密碼
※※**『舊密碼』只要隨意輸入「八個以上且英數混合的字元」**※※
![image](https://user-images.githubusercontent.com/41721950/54095407-2d1c2580-43e2-11e9-8a0d-eda5ce6aab4c.png)
即會出現「密碼設定成功」的提示訊息。
![image](https://user-images.githubusercontent.com/41721950/54095429-491fc700-43e2-11e9-89ab-dc4890bac554.png)
但正確修改密碼途徑應是「登入頁-忘記密碼?」且舊密碼不該隨意輸入而未驗證
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
目前修改密碼的api會看密碼是否為空
才會去確認舊密碼
前端流程希望改成當用戶沒有密碼時
就不用輸入舊密碼
@Gabe-Liu  @ai015606220

**Comment by AnitaRyzo** [comment]
當用戶沒有密碼時，就不用輸入舊密碼
![image](https://user-images.githubusercontent.com/41721950/54897478-8c5e5780-4f03-11e9-908d-06aef50ab1eb.png)
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55459440-23bd5c00-5622-11e9-8b06-c74170ad918d.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
