### ISSUE TITLE
【問題】互動元件裡的表單 表單顏色是否失效

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1086]
如圖，黃色區域的表單顏色是否失效了
更換顏色沒有反應

<img width="1020" alt="螢幕快照 2019-03-11 下午2 29 36" src="https://user-images.githubusercontent.com/34327325/54104299-4fc23480-440a-11e9-84f0-ce1f58475a8b.png">

**Comment by ai015606220** [comment]
這問題只有正式站上有，日後更新後就能解決

**Comment by AnitaRyzo** [comment]
表單顏色可即時更新為選取的顏色
◎◎ 20190319確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
表單顏色可即時更新為選取的顏色
◎◎ 20190408確認以上正式環境內容 ◎◎
