### ISSUE TITLE
【建議】元件複製與貼上

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#1092]
目前的元件複製與貼上方式，是在選取目標元件後以 (Ctrl+C)複製，必須保持選取狀態，再以 (Ctrl+V)原位置貼上，因此一旦複製後取消原目標元件的選取，使用(Ctrl+V)就無法貼上原本複製的元件。

建議在任何狀態(1)選取(2)未選取，都可以貼上複製好的元件，貼上的位置會是在畫布的正中央，如同元件加入畫布時的初始位置，如此一來不管使用者有沒有選取或是滑動至畫布其他位置，複製的元件都能貼上。

以上建議，感謝！

**Comment by AnitaRyzo** [comment]
(Ctrl+C)複製元件後，隨時(Ctrl+V)都可貼上被複製的元件
而貼上的元件會重疊在被複製的元件上。
◎◎ 20190319確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
(Ctrl+C)複製元件後，隨時(Ctrl+V)都可貼上被複製的元件
而貼上的元件會重疊在被複製的元件上。
◎◎ 20190410確認以上正式環境內容 ◎◎
