### ISSUE TITLE
【測試環境】分類管理之選單架構的圖片剪裁失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1093]
『分類管理-選單架構設定-自訂-圖片上傳-圖片剪裁』
![image](https://user-images.githubusercontent.com/41721950/54260952-5c2ec480-45a5-11e9-94e6-4e96a2a81789.png)
點選『圖片剪裁』之後如下沒有預覽的圖示，點選比例尺與完成鈕也沒有反應
![image](https://user-images.githubusercontent.com/41721950/54261005-926c4400-45a5-11e9-9254-98c659b820f5.png)
錯誤訊息如下所示
![image](https://user-images.githubusercontent.com/41721950/54261202-1cb4a800-45a6-11e9-9636-b72fc51c951d.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
目前圖片剪裁的分應該有用到 canvas
因為我把圖片改傳到雲端空間
會有跨域存取的問題
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
提供這篇文章做參考
應該加一個屬性在圖片上就可以
crossOrigin = "Anonymous"

@Gabe-Liu  @ai015606220

**Comment by AnitaRyzo** [comment]
已可剪裁圖片
![image](https://user-images.githubusercontent.com/41721950/54653973-9a713a00-4af7-11e9-9c9c-aa7225658b65.png)
◎◎ 20190320確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已順利剪裁且預覽與瀏覽器皆可看到剪裁後的圖片
![image](https://user-images.githubusercontent.com/41721950/55924119-21b75680-5c3b-11e9-99be-17de7407e040.png)
◎◎ 20190411確認以上正式環境內容 ◎◎
