### ISSUE TITLE
【測試環境】跨帳號無法查看電子申請單的回覆

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1094]
『跨帳號-表單管理-查看回覆-電子申請單』
如下無法查看電子申請單的回覆
![image](https://user-images.githubusercontent.com/41721950/54336551-54375900-4667-11e9-8d9e-c11b80efbe0f.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/54336811-12f37900-4668-11e9-8e95-0adc62688baa.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
跨帳號和取自己的api不一樣
再麻煩確認一下
@Gabe-Liu  @ai015606220

**Comment by AnitaRyzo** [comment]
跨帳號已可看到回覆的PDF列表
![image](https://user-images.githubusercontent.com/41721950/54653437-acea7400-4af5-11e9-8419-9936177c4a71.png)
◎◎ 20190320確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55459493-4c455600-5622-11e9-89c2-cb864f887210.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
