### ISSUE TITLE
mac螢幕顯示100%的時候  圖層下不去

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#110]
mac螢幕顯示100%的時候
圖層下不去 不能刪除元件QQ

要縮到大概67%的時候才能看到全部介面

<img width="1280" alt="2018-05-11 3 32 04" src="https://user-images.githubusercontent.com/34293268/39912193-7ad7d360-5530-11e8-8b5d-35451ab65fc9.png">

**Comment by Gabe-Liu** [comment]
記得之前有修正，等下次更新看使否有改善
