### ISSUE TITLE
【問題】套版管理的開啟與結束時間設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1103]
狀況1: 設定好日期以後，設定時間時如果直接點選“下”，設定成23點，點選完成再重新進入套版管理，會發現日期往前了一天（但是在剛設定完時間時，顯示的還是原本設定好的日期）

狀況2: 發現日期錯誤後，重新進入套版管理設定，只將日期欄位修改後，完成動作。再次進入時，發現時間不是原本預設好的時間，會變成預設的0:00

以上兩個狀況都是另一個欄位的值沒有同步即時更新，
或是乾脆把他們各自切開，直接單獨設定不要連動數值

<img width="688" alt="螢幕快照 2019-03-19 上午9 27 05" src="https://user-images.githubusercontent.com/34327325/54574176-4c423500-4a2a-11e9-8afb-a5152e5de41b.png">

**Comment by AnitaRyzo** [comment]
套版管理的開啟與結束時間
點選『日期』，時間不會變動；『時間』跨越23，日期不會+1
目前「專案類型」仍有此問題，請協助處理。感恩~

**Comment by AnitaRyzo** [comment]
『專案類型』『套版類型』的開啟與結束時間
『時間』應為24小時計，但設定超過12點儲存後再次開啟，時間會回到早上的時間
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『專案類型』『套版類型』的開啟與結束時間已正確
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『專案類型』『套版類型』的開啟與結束時間已正確
◎◎ 20190411確認以上正式環境內容 ◎◎
