### ISSUE TITLE
【問題】專案在IE與Safari的執行畫面不流暢

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1105]
與Chrome、Firefox、Opera執行的畫面相比，專案在IE與Safari的執行畫面不流暢
![image](https://user-images.githubusercontent.com/41721950/54584088-43188e80-4a51-11e9-938d-1db94d36be56.png)
以上問題請協助解決，感恩~

**Comment by ai015606220** [comment]
請問是指在蘋果電腦上的Safari還是windows的?

**Comment by AnitaRyzo** [comment]
蘋果電腦跟「windows之蘋果電腦模擬器」的Safari都不流暢

**Comment by Gabe-Liu** [comment]
修正後，對於裝飾使用框架的元件需要多一個設定 "使用穿透"，如此在用滑鼠或手指滾動時，並不會因為在框架元件上卡住，導致無法上下滑動

**Comment by weilyn** [comment]
好奇詢問，那什麼情況下不需要設定 “使用穿透”
如果設定成框架都需要的話，可以直接變成開啟框架時，直接預設選項開啟嗎

**Comment by ryuichl** [comment]
如果使用穿透的話
元件會無法點擊
也就是按鈕之類的元件還是會需要相關設定
無法全部都設穿透

**Comment by Gabe-Liu** [comment]
IE 應該是要放棄治療了！

**Comment by AnitaRyzo** [comment]
在Safari瀏覽器執行.com與.io的速度，.com較.io更為流暢
◎◎ 20190329確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『開啟穿透』：元件會無法點擊，連結設定失效
◎◎ 20190419確認以上正式環境內容 ◎◎
