### ISSUE TITLE
【測試環境】跨帳號查看PDF的錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1108]
跨帳號權限已全數開啟；但點選『查看pdf』之後，會出現error
![image](https://user-images.githubusercontent.com/41721950/54654129-21bead80-4af8-11e9-93af-8706e091cd73.png)
另開新網頁的顯示如下
![image](https://user-images.githubusercontent.com/41721950/54654193-53377900-4af8-11e9-9dd1-f8174582529b.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
@ai015606220 
剛補上文件
你再看一下

**Comment by AnitaRyzo** [comment]
已可跨帳號查看電子表單的PDF
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已可跨帳號查看電子表單的PDF
![image](https://user-images.githubusercontent.com/41721950/55458868-bceb7300-5620-11e9-9c7f-8032e597da67.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
