### ISSUE TITLE
【問題】『內容待更新上線』的專案在審核後台的提示訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1112]
如下設定個人權限，已完全開啟『審核後台』權限
![image](https://user-images.githubusercontent.com/41721950/54665983-893e2280-4b23-11e9-85fd-b201c1c5b3d2.png)
在『審核發佈管理』可以執行『專案審核』
『專案發佈』可以執行將專案從『待發佈』轉到『發佈中』
但若專案在『發佈中』，顯示『內容待更新上線』的燈號
![image](https://user-images.githubusercontent.com/41721950/54665943-71669e80-4b23-11e9-93d9-2c3236e8dcbf.png)
請修改以下的提示訊息描述
![image](https://user-images.githubusercontent.com/41721950/54665903-5431d000-4b23-11e9-9aab-73537b4863e0.png)
請協助處理，感恩~

**Comment by ryzojudy** [comment]
無跨帳號查看專案之權限，無法查看更新畫面。並不影響發佈權限，可照常更新專案，若欲查看更新畫面請連絡相關人員為你開啟

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/54901532-ac951300-4f11-11e9-857c-f491482d8b99.png)
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55926637-ace91a00-5c44-11e9-81f4-53587a2f1ce5.png)
◎◎ 20190411確認以上正式環境內容 ◎◎
