### ISSUE TITLE
【建議】套版審核跳窗中下方按鈕文字修改

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#1115]
在套版審核處
希望可以將跳窗中下方的按鈕文字改為「下一步」(紅框處)
感謝~~
![image](https://user-images.githubusercontent.com/34263719/54730309-1d12fb80-4bc3-11e9-86b2-3ba0ee0fa539.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/54902351-1dd5c580-4f14-11e9-99a3-17b405cf5a4f.png)
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55926694-e0c43f80-5c44-11e9-8aea-2ee648344b38.png)
◎◎ 20190411確認以上正式環境內容 ◎◎
