### ISSUE TITLE
【建議】編輯區 圖片元件的濾鏡設定 重設按鈕樣式

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#1121]
目前圖片元件的濾鏡設定裡「重設」按鈕位於濾鏡設定的底部，建議位置修改至圖片濾鏡標題的右側，並將樣式更改為小型圓角按鈕。
＊目前寬版的矩形按鈕是設定成開啟其他設定視窗的功能，小型的圓角按鈕則是針對該設定區域執行相關動作(例如：輪播圖的「新增」、內嵌程式碼的「儲存」等等) 
故提出以上變更建議，感謝。

![螢幕快照 2019-03-22 下午3 52 02](https://user-images.githubusercontent.com/37531593/54810268-a3f9ce00-4cc0-11e9-9c81-af0dc5d6c6d3.jpg)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55394669-64f63300-5572-11e9-8a5b-2d162b90ad85.png)
◎◎ 20190402確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55855610-95eded80-5b9a-11e9-90ed-0084ba2cbd4b.png)
◎◎ 20190410確認以上正式環境內容 ◎◎
