### ISSUE TITLE
【測試環境】裝飾區塊調整大小時的顯示位置偏移

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1127]
在畫面下方調整裝飾區塊大小，
但狀態卻顯示在工作區域中間

無傷大雅，提供參考

![ezgif-2-0e6f9b825fcf](https://user-images.githubusercontent.com/34327325/54890641-4a261d80-4ee5-11e9-9218-94c929f6a259.gif)

**Comment by AnitaRyzo** [comment]
裝飾區塊調整大小時未偏移
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55927091-5bda2580-5c46-11e9-90eb-00654a06a27c.png)
裝飾區塊調整大小時未偏移
◎◎ 20190411確認以上正式環境內容 ◎◎
