### ISSUE TITLE
【測試環境】電子申請書的下載無資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1130]
電子申請書會以壓縮檔的方式下載
下載後解壓縮會有以下提示訊息
![image](https://user-images.githubusercontent.com/41721950/54910767-f983e400-4f27-11e9-8a10-be5a8f5d8dcf.png)
請協助處理此問題，感恩~

**Comment by ai015606220** [comment]
請問是沒有勾選回覆的情況嗎??

**Comment by AnitaRyzo** [comment]
是的，我沒有勾選任何一筆回覆
但是『表單』不用勾選也可以下載所有回覆耶...

**Comment by ai015606220** [comment]
因為表單只能一次下載全部的回覆，不能分筆

但電子申請書目前設計是只有把全部勾選才會下載全部，這點可以看看需不需要優化
我會先讓下載按鈕在沒有勾選時不能按

**Comment by AnitaRyzo** [comment]
下載按鈕在沒有勾選時不能按
→ 可否加入提示訊息，請操作者『選取要下載的回覆』

**Comment by ai015606220** [comment]
我是傾向  有勾選才出現這個按鈕拉

**Comment by AnitaRyzo** [comment]
上次『資料綁定-匯出資料』在專案未發佈前是消失的狀態，會造成使用者若未受到教學就不知道此處發佈後會出現『匯出資料』的按鈕。
故建議『下載』按鈕不要消失，而是「不能有功能的灰字按鈕」，滑鼠靠近出現提示訊息『選取要下載的回覆』。
以上建議請參考，感恩~

**Comment by ai015606220** [comment]
因為以gmail為例，也是有勾選才會顯示出這種控制的按鈕
我覺得這能保持介面的簡潔

**Comment by AnitaRyzo** [comment]
蠻有道理的

**Comment by ai015606220** [comment]
那麻煩請 @ryzojudy @Samasianspock @liucwlewis 決斷一下

**Comment by ryzojudy** [comment]
這邊也覺得有勾選時再出現會比較好~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55048540-7ecfdb80-5083-11e9-97b0-42a5c91930f3.png)
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55455725-4ac26080-5617-11e9-8ae3-1d599a51f80a.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
