### ISSUE TITLE
【問題】收縮區塊“關閉”狀態影響下層物件點選

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1133]
想請問一下，收縮區塊如果在收縮的情況下，仍然會影響下層的物件點選情況
是否表示在收縮區塊的範圍內不能放置任何需要點擊觸發的按鈕、或是其他收縮區塊

註：以前“可能”曾經可以正常點選該範圍下的其他內容物件

<img width="262" alt="螢幕快照 2019-03-26 下午12 00 48" src="https://user-images.githubusercontent.com/34327325/54970860-d0faf900-4fbe-11e9-89fe-9fba61468901.png">

**Comment by AnitaRyzo** [comment]
收縮區塊“關閉”狀態不影響下層物件點選
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55927803-ede32d80-5c48-11e9-996b-12d200771bfc.png)
收縮區塊“關閉”狀態不影響下層物件點選
◎◎ 20190411確認以上正式環境內容 ◎◎
