### ISSUE TITLE
【測試環境】專案域名後置的個人URL

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1135]
『資料綁定-匯出資料-URL』
![image](https://user-images.githubusercontent.com/41721950/54974647-a8c7c600-4fcf-11e9-8a9a-f735bedfd364.png)
此URL無法正確執行
![image](https://user-images.githubusercontent.com/41721950/54974638-a1a0b800-4fcf-11e9-8c1f-038298c696dd.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
『資料綁定-審核發佈-匯出資料-URL』
個人URL已可在瀏覽器上執行
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
『資料綁定-審核發佈-匯出資料-URL』
個人URL已可在瀏覽器上執行
◎◎ 20190625確認以上正式環境內容 ◎◎

**Comment by cocosu123** [comment]
『資料綁定-審核發佈-匯出資料-URL』
個人URL已可在瀏覽器上執行
![1135](https://user-images.githubusercontent.com/49626114/60633586-f315da00-9e3d-11e9-8578-0e83df41a760.png)
◎◎ 20190704確認以上正式環境內容 ◎◎
