### ISSUE TITLE
【測試環境】專案域名後置的專案下載無法在本機開啟

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1136]
下載專案
![image](https://user-images.githubusercontent.com/41721950/54979917-6312f980-4fdf-11e9-8856-ba6182fc0fc7.png)
無法在本機開啟
![image](https://user-images.githubusercontent.com/41721950/54979822-21824e80-4fdf-11e9-878a-39347a2e5e38.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
已可開啟
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
專案下載後可開啟
◎◎ 20190703確認以上正式環境內容 ◎◎
