### ISSUE TITLE
【問題】gif的圖片剪裁後就不動了

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1144]
.gif的檔案格式可以上傳
但若進行『圖片剪裁』，圖片就不再是動圖了
![image](https://user-images.githubusercontent.com/41721950/55303326-0fd5f680-5478-11e9-8347-25fbc3bd9357.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
gif確實是不可以裁切
看是要擋住還怎樣
@Gabe-Liu  @ai015606220

**Comment by AnitaRyzo** [comment]
.gif的檔案格式沒有『圖片剪裁』功能
![image](https://user-images.githubusercontent.com/41721950/56007245-a3c28080-5d0a-11e9-81ba-115e2309edd2.png)
◎◎ 20190412確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56260972-dbb33480-610b-11e9-9bc2-75c0956d57b3.png)
◎◎ 20190417確認以上正式環境內容 ◎◎
