### ISSUE TITLE
【測試環境】複製的專案中，有MGM元件的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1145]
左側為原有專案，右側為複製專案
互動元件不管是「複製專案」或在同一專案複製貼上，都是出現『啟用/選擇』二選一
但「複製專案」後的MGM卻直接共用後台資料
![image](https://user-images.githubusercontent.com/41721950/55307853-5bde6680-548b-11e9-94d6-87cb4f9e70d8.png)
同一專案複製貼上時，MGM與其他互動元件的狀況如下
![image](https://user-images.githubusercontent.com/41721950/55308073-1a01f000-548c-11e9-9bcc-42dfed7321f6.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
@Gabe-Liu  @ai015606220  同一專案複製的再麻煩改一下

**Comment by AnitaRyzo** [comment]
複製專案
![image](https://user-images.githubusercontent.com/41721950/55390495-edbca100-5569-11e9-9870-1e3c887ccefd.png)
◎◎ 20190402確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55450514-f82a7980-5601-11e9-80ca-dc6c6b6ed735.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
