### ISSUE TITLE
【測試環境】電子申請書上傳png檔案有錯誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1153]
.png圖檔顯示表單回覆錯誤，未出現pdf下載，後台點選眼睛出現錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/55383768-8a2b7700-555b-11e9-9450-a97b5237ca9a.png)
但如下同為.png圖檔的表單可以順利上傳、pdf下載、後台開啟
![image](https://user-images.githubusercontent.com/41721950/55383958-032ace80-555c-11e9-9218-dde41e2cdc5b.png)
請協助處理此問題，感恩~

**Comment by ryuichl** [comment]
pdfmake在處理png時會某些格式不吃
改成上傳圖片會先經過jimp處理

**Comment by AnitaRyzo** [comment]
F3.png已可順利上傳
◎◎ 20190402確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
F3.png圖檔表單正常回覆，但pdf無法下載
![image](https://user-images.githubusercontent.com/41721950/55460220-fbcef800-5623-11e9-8d08-2b8c6c79192b.png)
後台點選眼睛可出現pdf的文件
![image](https://user-images.githubusercontent.com/41721950/55460241-0c7f6e00-5624-11e9-9cb5-a6ee621d9a4f.png)
◎◎ 20190403確認以上正式環境內容 ◎◎

**Comment by ryuichl** [comment]
後端的部分我有解決
但是前端還有問題
pdfmake在處理png時用的套件不支援png某些格式導致錯誤
https://github.com/foliojs/pdfkit/issues/414
以上連結供參考
大坑
@Gabe-Liu  @ai015606220

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56117819-7fc99e00-5f9b-11e9-9cc5-cd1fcfd93d5a.png)
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56265369-ed9cd380-611b-11e9-9345-9ea7f217b6a3.png)
◎◎ 20190417確認以上正式環境內容 ◎◎
