### ISSUE TITLE
【問題】英文版 表單按鈕文字錯誤

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#1157]
應該是next卻出現系統語言？

<img width="423" alt="螢幕快照 2019-04-03 上午8 48 29" src="https://user-images.githubusercontent.com/34560641/55445385-ad9f0200-55ed-11e9-84bc-a202c89a5816.png">

**Comment by AnitaRyzo** [comment]
請幫我清cookie再試試看，感恩~
![image](https://user-images.githubusercontent.com/41721950/55445845-c7d9df80-55ef-11e9-9d1f-a75ae7e84a5b.png)

**Comment by AnitaRyzo** [comment]
已向Wilma確定無誤可執行
