### ISSUE TITLE
【問題】表單動畫呈現樣式可能異常

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1162]
如題，選擇滑動效果中的第一組向下滑動
兩題題目有交疊的情形，與其他同類型樣式略有差異
請協助確認是否執行有誤

![1554262179965](https://user-images.githubusercontent.com/34327325/55451155-59ebe300-5604-11e9-9204-8ddf407bb327.gif)

**Comment by AnitaRyzo** [comment]
滑動效果的向下滑動系列無疊題問題
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
滑動效果的向下滑動系列無疊題問題
翻轉效果受效果影響略有小疊題
◎◎ 20190418確認以上正式環境內容 ◎◎
