### ISSUE TITLE
【問題】表單中含標題說明，若其他題型為必填的錯誤狀況

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1166]
在表單的標題說明的題型後，如果有設置必填的題型，就會造成表單無法送出

詳情可以參閱issue #848 

是某一位客戶目前碰到的情形，再麻煩協助優先處理，謝謝

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56028946-e48eb980-5d4b-11e9-8e19-1e39b40f6068.png)
◎◎ 20190412確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56342315-3cb13a00-61ea-11e9-9ba1-a89dc166e2b9.png)
◎◎ 20190418確認以上正式環境內容 ◎◎
