### ISSUE TITLE
【問題】表單題目過長時，蘋果手機直接卡掉問卷

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1170]
蘋果手機：iPhone 7、iPhone 8、iPhone X、iPhone XR、iPhone XS系列
只顯示問卷一開始Loading的題目，後續題目未帶入
![image](https://user-images.githubusercontent.com/41721950/55710872-205d1280-5a1e-11e9-8b74-4e0f9dd7f118.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
有案例能夠提供嗎?

**Comment by AnitaRyzo** [comment]
蘋果手機系列已帶入後續題目
![image](https://user-images.githubusercontent.com/41721950/56106817-8ba26980-5f75-11e9-9127-9a388a51a176.png)
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
蘋果手機iPhone6以上系列已帶入後續題目
![image](https://user-images.githubusercontent.com/41721950/56340490-a1699600-61e4-11e9-99a4-d0c2215cf233.png)
◎◎ 20190418確認以上正式環境內容 ◎◎
