### ISSUE TITLE
【問題】表單的題目刪除再建立，表單就失效了

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1172]
創建表單後，對表單題目刪除再建立，並讓使用者填寫表單
![image](https://user-images.githubusercontent.com/41721950/55771015-f7d62680-5ab8-11e9-9d1e-b98c373c9d94.png)
差不多在重建第二次第三次後就會如下狀況不斷LOADING
所有題型亂排都出現一樣的錯誤
![image](https://user-images.githubusercontent.com/41721950/55772036-1e965c00-5abd-11e9-8707-78170c61ddae.png)
#956 為相關聯的表單問題
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
這個跟 956 並沒有關聯

**Comment by AnitaRyzo** [comment]
表單的題目可以不斷刪除再建立
![image](https://user-images.githubusercontent.com/41721950/56113560-cd8cd900-5f90-11e9-9ca8-60c7c46e175c.png)
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
表單的題目可以不斷刪除再建立
![image](https://user-images.githubusercontent.com/41721950/56351653-2e6e1880-6200-11e9-8ac3-5d2ed222b3a3.png)
◎◎ 20190418確認以上正式環境內容 ◎◎
