### ISSUE TITLE
【問題】表單題號的.跑位

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1174]
如圖
2底下的點跑位了

![S__7667731](https://user-images.githubusercontent.com/34327325/55784233-b6f30780-5ae2-11e9-887d-d6b57b9a8c45.jpg)

**Comment by ai015606220** [comment]
請提供你的專案，還有執行的環境

**Comment by weilyn** [comment]
https://sdjfkjxdioc.ryzoweba.io
這個專案 在手機版上填寫表單會出現以上情形

**Comment by AnitaRyzo** [comment]
iOS系列的表單題號的. 無跑位
![image](https://user-images.githubusercontent.com/41721950/56106030-d02c0600-5f71-11e9-915a-a14cd70caa75.png)
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56333448-d0710f00-61c6-11e9-9d9c-61da97190c73.png)
◎◎ 20190418確認以上正式環境內容 ◎◎
