### ISSUE TITLE
【問題】發佈的專案運行緩慢，請協助查看

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1176]
目前專案經過發佈後，在瀏覽器中查看，發現有嚴重延遲的情況
這個專案同時有製作手機及電腦版，都有延遲情況，但以電腦版為重
再麻煩協助排解

https://sdjfkjxdioc.ryzoweba.io/

**Comment by AnitaRyzo** [comment]
發佈的專案運行無嚴重延遲
◎◎ 20190415確認以上測試環境內容 ◎◎
