### ISSUE TITLE
【問題】表單填題字體大小

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1177]
表單填題的字體大小只有從16px開始
WEBA其他地方的文字設定為最小12

<img width="927" alt="螢幕快照 2019-04-09 下午3 44 20" src="https://user-images.githubusercontent.com/34327325/55845960-88bf0780-5b76-11e9-9fda-cd9c57725497.png">

**Comment by ai015606220** [comment]
#1031
