### ISSUE TITLE
【問題】發布站點抓不到語系檔

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1178]
如題
在語系為英文的環境下, 應該要套用 i18n/v3Publish/en-US.json 字句
但依然顯示中文的提示字句

Console 有無法抓取 ./assets/i18n/v3Publish/en-US.json 的警示
![image](https://user-images.githubusercontent.com/11918396/55850231-2110b880-5b86-11e9-8306-55ef4d08bd92.png)

Network 無相關的 404 錯誤
![image](https://user-images.githubusercontent.com/11918396/55850625-a8aaf700-5b87-11e9-8d7d-60e4b0358ced.png)

![image](https://user-images.githubusercontent.com/11918396/55850722-23741200-5b88-11e9-975e-fd8c245e9a07.png)

![image](https://user-images.githubusercontent.com/11918396/55850745-3ab2ff80-5b88-11e9-984b-e94f9744a6b9.png)

**Comment by leonlin6** [comment]
已詢問 @Kyle30 ，此Issue Bug已被修復，故關閉Issue
