### ISSUE TITLE
【審核後台】審核預覽沒東西

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#118]
如圖 點進去畫面出不來
![image](https://user-images.githubusercontent.com/34263719/39975471-52b75454-5761-11e8-997b-e1655f13b134.png)

**Comment by Gabe-Liu** [comment]
請再檢查看看線上的還是無法嗎?

**Comment by ryzojudy** [comment]
自己送出的專案審核沒問題
但看別人的一樣會沒有內容
![image](https://user-images.githubusercontent.com/34263719/40031569-e3ebba8e-5822-11e8-9d54-7f49b6f25a01.png)
