### ISSUE TITLE
【建議】分享換優惠元件中的說明文字

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#1183]
分享換元件優惠中的角色(橘框處)
有『推薦人 』、『分享者』、『被分享者』、『接收者』

建議文字部分統一
才不會造成使用者的混亂～

(圖一有錯字順便框起來)
<img width="387" alt="螢幕快照 2019-04-08 下午12 22 01" src="https://user-images.githubusercontent.com/34293268/55924201-7064f080-5c3b-11e9-883a-68f1390d7126.png">

<img width="956" alt="螢幕快照 2019-04-11 上午9 24 27" src="https://user-images.githubusercontent.com/34293268/55924270-be79f400-5c3b-11e9-8b67-b610a4ac6653.png">

<img width="207" alt="螢幕快照 2019-04-11 上午9 16 53" src="https://user-images.githubusercontent.com/34293268/55924274-c33ea800-5c3b-11e9-9d89-e5491eba9dbc.png">

<img width="315" alt="螢幕快照 2019-04-11 上午9 18 43" src="https://user-images.githubusercontent.com/34293268/55924276-c76ac580-5c3b-11e9-9807-afb51094940d.png">

<img width="310" alt="螢幕快照 2019-04-11 上午9 18 54" src="https://user-images.githubusercontent.com/34293268/55924281-cb96e300-5c3b-11e9-84aa-ae21df9a8c1f.png">

後台
![螢幕快照 2019-04-11 上午9 29 03](https://user-images.githubusercontent.com/34293268/55924415-642d6300-5c3c-11e9-8a9d-218c5711fb79.png)

**Comment by ai015606220** [comment]
@ryzojudy 請問哪兩個用字才是正確的??

**Comment by ryzojudy** [comment]
正確是
分享者
接收者

**Comment by ryzojudy** [comment]
推薦人 -> 分享者
被分享者 -> 接收者

感謝~~~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56114678-24e07880-5f94-11e9-89c6-3180fb14c24a.png)
![image](https://user-images.githubusercontent.com/41721950/56114753-522d2680-5f94-11e9-95d3-f007d423547d.png)
![image](https://user-images.githubusercontent.com/41721950/56114787-6ec95e80-5f94-11e9-8874-c60cd13c8cc9.png)
![image](https://user-images.githubusercontent.com/41721950/56115123-44c46c00-5f95-11e9-9cd0-b8fe2d04bd76.png)
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已確認此文字描述
推薦人 -> 分享者
被分享者 -> 接收者
![image](https://user-images.githubusercontent.com/41721950/56401424-4b036280-628b-11e9-9dfc-e4e7300fd6aa.png)
◎◎ 20190419確認以上正式環境內容 ◎◎
