### ISSUE TITLE
【問題】上傳圖片題型是否有檔案大小限制

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#1186]
電子申請書的上傳圖片題型
用兩張不同大小的圖片實驗
<img width="220" alt="螢幕快照 2019-04-11 上午10 21 52" src="https://user-images.githubusercontent.com/34293268/55926474-0d2b8c00-5c44-11e9-967d-a8db1f5575ac.png">

上傳較大的檔案“圖1”
等了一陣子都沒反應
<img width="400" alt="螢幕快照 2019-04-11 上午10 24 06" src="https://user-images.githubusercontent.com/34293268/55926483-11f04000-5c44-11e9-98a4-fb5c2d26cecd.png">

放棄以後接著上傳較小的“圖2”
上傳成功
<img width="428" alt="螢幕快照 2019-04-11 上午10 21 33" src="https://user-images.githubusercontent.com/34293268/55926529-482dbf80-5c44-11e9-80d3-60c4e1d84b0c.png">

不確定是否有檔案大小的限制
如果有的話建議可以以提示的方式提醒使用者未上傳成功之類的
可能像下面這種
或可以再討論看看有沒有更好的回饋方式～
<img width="410" alt="螢幕快照 2019-04-11 上午10 28 52" src="https://user-images.githubusercontent.com/34293268/55926635-aa86c000-5c44-11e9-974a-fa8da77d4a7a.png">

**Comment by ryuichl** [comment]
印象中我會回傳錯誤?
再加個錯誤處理吧

**Comment by AnitaRyzo** [comment]
19.7MB的圖片等再久也未上傳，未有提示
![image](https://user-images.githubusercontent.com/41721950/55938694-7cb67100-5c6e-11e9-85ed-e943a8766549.png)
系統內圖片上傳提示訊息為大小不超過10MB
故嘗試上傳9.96MB的圖片，但等再久也未上傳，未有提示
![image](https://user-images.githubusercontent.com/41721950/55939195-be93e700-5c6f-11e9-9a7d-5789909f8ca7.png)
在9.96MB之後上傳2.80MB，2.80MB已顯示
資料確認頁面與下載的PDF也只顯示2.80MB的圖示
![image](https://user-images.githubusercontent.com/41721950/55939512-8214bb00-5c70-11e9-8e8c-a9c9f2357927.png)
以上補充，感恩~

**Comment by ai015606220** [comment]
發現是我當初設定錯誤，本來設成10Mb(megabit)，已修正成10MB(megabyte)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56117943-d46d1900-5f9b-11e9-9c56-d082c4a81635.png)
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56265711-d6121a80-611c-11e9-923b-2e13ee8d7d59.png)
◎◎ 20190417確認以上正式環境內容 ◎◎
