### ISSUE TITLE
【問題】分享換優惠的按鈕顏色

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#1191]
原本的設定是
登入前-**紅色按鈕**    文字：**登入參加活動**
登入後-**紫色按鈕**    文字：**分享吧！！！**
如下圖
<img width="1280" alt="螢幕快照 2019-04-11 下午2 18 49" src="https://user-images.githubusercontent.com/34293268/55935218-a5863880-5c65-11e9-8848-ea06c2b4a2ee.png">
<img width="1280" alt="螢幕快照 2019-04-11 下午2 19 11" src="https://user-images.githubusercontent.com/34293268/55935220-a6b76580-5c65-11e9-87de-a7ec7ac2c296.png">

發佈後使用瀏覽器開啟
因為已經登入過了
所以會顯示文字“分享吧！！！”
但按鈕會先顯示登入前的顏色  點擊的瞬間再變成登入後的顏色
電腦預覽跟手機都有這個問題～
<img width="387" alt="螢幕快照 2019-04-11 下午2 15 55" src="https://user-images.githubusercontent.com/34293268/55935526-6d332a00-5c66-11e9-97fe-5085f702717e.png">
<img width="386" alt="螢幕快照 2019-04-11 下午2 16 35" src="https://user-images.githubusercontent.com/34293268/55935529-6efced80-5c66-11e9-9420-ba90978bd44c.png">

好難解釋因此在附上一張動圖QQ
![1554964076538](https://user-images.githubusercontent.com/34293268/55935369-0a419300-5c66-11e9-8bf0-f1227dca17ca.gif)

**Comment by AnitaRyzo** [comment]
瀏覽器已有社群登入紀錄，按鈕顏色會顯示登入後指定顏色
![image](https://user-images.githubusercontent.com/41721950/56116386-3d529200-5f98-11e9-92b3-bcbeec66ba3b.png)
◎◎ 20190415確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56401335-dd573680-628a-11e9-8fd1-3be3c79b2856.png)
◎◎ 20190419確認以上正式環境內容 ◎◎
