### ISSUE TITLE
【問題】MGM按下切換帳號會進入黑畫面無法再次登入

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1204]
![image](https://user-images.githubusercontent.com/41721950/56177834-a686e380-6032-11e9-87e3-4c04e0523877.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
https://cm.ryzoweba.com/google
此專案一進去就是全黑的
chrome的分頁一切換又正常
可能是同個問題

**Comment by AnitaRyzo** [comment]
已可順利登入
◎◎ 20190416確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已可順利登入
◎◎ 20190419確認以上正式環境內容 ◎◎
