### ISSUE TITLE
【問題】數據抓取分頁名稱出現錯誤編碼顯示？

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1205]
專案中只有一個分頁，如下圖，
<img width="185" alt="螢幕快照 2019-04-16 下午1 55 17" src="https://user-images.githubusercontent.com/34327325/56185314-bfea5880-604f-11e9-9a13-676835eebb2f.png">

在數據中，分頁數據中的跳出率及離開率的頁面名稱顯示有誤
<img width="1364" alt="螢幕快照 2019-04-16 下午1 57 24" src="https://user-images.githubusercontent.com/34327325/56185343-c7116680-604f-11e9-9fd9-cc7848a69236.png">

在UTM中，也是一個正常，一個不正常
<img width="410" alt="螢幕快照 2019-04-16 下午1 58 14" src="https://user-images.githubusercontent.com/34327325/56185365-cd074780-604f-11e9-8855-79a944215588.png">

**Comment by ryuichl** [comment]
請問這個專案的網址是什麼?

**Comment by weilyn** [comment]
https://springrs.ryzoweba.io

**Comment by ryuichl** [comment]
![image](https://user-images.githubusercontent.com/10150807/56190776-8f112000-605d-11e9-9e9f-8e470e1a1cba.png)
後台撈出來確實就是這樣

**Comment by weilyn** [comment]
XD 好吧 GA的錯
