### ISSUE TITLE
畫布上選取元件後 圖層沒反應

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#121]
在畫布上選取元件後 圖層區沒顯示是哪個元件被選取(沒反應)
或是對元件按了移至最上層的圖示  但畫布上的元件還是留在原地

<img width="817" alt="2018-05-14 10 32 09" src="https://user-images.githubusercontent.com/34293268/39975589-1a8e22aa-5762-11e8-9d86-0930340b94a6.png">

**Comment by Gabe-Liu** [comment]
待確認

**Comment by Gabe-Liu** [comment]
推測是上下步問題
