### ISSUE TITLE
【不知是甚麼問題】多出一個專案

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#122]
原本是兩個專案：新專案(空白)、新專案(有表單在內)
後來用空白的那個專案仿做其他的頁面
該專案儲存後 在某次文字元件造成的閃退
回到dashboard時 發現出現了一個新的空白專案
(或也許是仿做的專案另存新檔?總之多了一個專案)
![image](https://user-images.githubusercontent.com/34263719/39975810-4efd3b60-5763-11e8-8ab4-34d9f1750e07.png)

**Comment by ryuichl** [comment]
先關掉
有一樣問題發生再提
