### ISSUE TITLE
【建議】表單類型元件的「下一頁」優化

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1221]
目前在表單裡，如果題目較多，例如兩頁分別都有10題，
當我從第一頁的第10題填寫完以後，會直接跳到第二頁第10題的位置
但其實第二頁的題目完全還沒填寫過

除此之外資料確認頁也有類似的情況

**Comment by ai015606220** [comment]
請問有出錯的範例能提供嗎?

**Comment by weilyn** [comment]
這邊 
https://ctbcreport2.ryzoweba.io
這是長頁型裡資料確認頁的情況

另外有需要也可以提供短頁的範例

**Comment by ai015606220** [comment]
需要短頁的

長頁的沒有辦法，對表單來說它已經到頂了，表單的滾動和頁面的滾動是不同的

**Comment by weilyn** [comment]
短頁的今天再試一次發現會回到表單最上方了，因此短頁的issue暫時無法重現

好奇一問，點擊上下一頁的對齊位置是以目前編輯區可視範圍的頂端為依據嗎 (不是以表單元件的頂端)
因為短頁式的目前無論滑動到哪，都可以無意外的回到表單頁面的最上方

如果這個真的無解的話也沒關係，我先知道一下規則即可
