### ISSUE TITLE
【問題】圖片與輪播圖元件之上傳圖片的檔案大小

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1223]
元件：圖片與輪播圖，以下情境使用圖片元件表示
問題一：上傳的檔案為1.81MB，但利用『下載專案』功能，會發現此圖片的檔案為4.14MB，檔案大了兩倍以上
![image](https://user-images.githubusercontent.com/41721950/56412420-a1d26180-62b6-11e9-9d12-780c043ebf9a.png)
問題二：上傳的檔案為9.96MB，故未出現超過10MB不給上傳的提示
![image](https://user-images.githubusercontent.com/41721950/56412583-52406580-62b7-11e9-854a-0638be271207.png)
但元件不斷LOADING，等待五分鐘也未出現圖片；
『Network-img』顯示「undefined」，利用『下載專案』功能發現無此圖
![image](https://user-images.githubusercontent.com/41721950/56412444-bf073000-62b6-11e9-8d41-ec737cda59cb.png)
請協助處理此問題，感恩~

**Comment by ryuichl** [comment]
圖片變大的問題我會處理
第二個的話應該是沒處理回傳的錯誤吧?
@ai015606220  @Gabe-Liu

**Comment by AnitaRyzo** [comment]
解題一：上傳的檔案為8.31MB，利用『下載專案』功能，此圖片的檔案為1.99MB
![image](https://user-images.githubusercontent.com/41721950/56787418-12392f80-682f-11e9-972a-1b3634fea294.png)
解題二：上傳的檔案為9.96MB，出現超過10MB不給上傳的提示
![image](https://user-images.githubusercontent.com/41721950/56787769-229dda00-6830-11e9-9d3f-9af52912294d.png)
◎◎ 20190426確認以上測試環境內容 ◎◎

**Comment by ryuichl** [comment]
提醒一下
第一題
你上傳的尺寸跟本來提的不太一樣喔

**Comment by AnitaRyzo** [comment]
sorry, 我剛剛想說直接放大尺寸下載
原圖片尺寸1.81MB，下載後為2.20MB；而8.31MB的圖片，下載後為1.99MB
![image](https://user-images.githubusercontent.com/41721950/56788771-ecae2500-6832-11e9-8d88-7fc322019936.png)
結論：圖片尺寸越大下載後的檔案尺寸反而小

**Comment by AnitaRyzo** [comment]
題一：上傳的圖檔與下載專案的圖檔尺寸如下
![image](https://user-images.githubusercontent.com/41721950/57212696-1e837080-7017-11e9-8e0c-eaf4caf49216.png)
題二：上傳的檔案為9.96MB，出現超過10MB不給上傳的提示
![image](https://user-images.githubusercontent.com/41721950/57212134-483b9800-7015-11e9-89b1-409d9d6374ca.png)
◎◎ 20190506確認以上正式環境內容 ◎◎
