### ISSUE TITLE
【建議】表單改版後，主題樣式包樣式沒有跟著做調整

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1224]
如圖
樣式1的色塊與題目距離過近
原因應該是因為新加入了頁面名稱的緣故
請UI再評估如何調整

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56487325-5ebdfb80-650d-11e9-8d66-936103c24ed9.png)
以上補充，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57829591-10390f80-77e2-11e9-8e59-65172ccf6336.png)
◎◎ 20190516確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57993913-880e7f00-7aed-11e9-8477-1fe0aaf78910.png)
◎◎ 20190520確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1224](https://user-images.githubusercontent.com/49626114/60574249-d9c44d80-9dab-11e9-9bde-1c38d9d13503.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
