### ISSUE TITLE
【問題】MGM表單編輯時，右側的離開編輯模式按鈕

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1226]
請確認在MGM中，編輯 “需要填寫表單才算達成任務”的表單，右側的按鈕文字是否正確

<img width="959" alt="螢幕快照 2019-04-22 下午1 55 07" src="https://user-images.githubusercontent.com/34327325/56485406-75ad1f80-6506-11e9-82e7-3a9512b1c1a8.png">

其他互動元件在次狀態下顯示的是以下
<img width="458" alt="螢幕快照 2019-04-22 下午1 54 46" src="https://user-images.githubusercontent.com/34327325/56485429-8493d200-6506-11e9-8e03-65d5535c4403.png">

**Comment by AnitaRyzo** [comment]
須修改的位置如紅框所示
![image](https://user-images.githubusercontent.com/41721950/56485637-5fec2a00-6507-11e9-8644-5987732e3469.png)
以上補充，感恩~

**Comment by AnitaRyzo** [comment]
『表單資料設定』開啟後皆會出現『離開表單編輯頁』
◎◎ 20190426確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『表單資料設定』開啟後皆會出現『離開表單編輯頁』
◎◎ 20190506確認以上正式環境內容 ◎◎
