### ISSUE TITLE
【問題】MGM專屬網址不會抓取專案ogt內容

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1228]
如圖，專案的分享設定圖片及文字皆不會被抓取

但是實際在使用MGM的時候，必須要具備以上項目，才能增加點擊率

<img width="313" alt="螢幕快照 2019-04-22 下午2 42 31" src="https://user-images.githubusercontent.com/34327325/56487378-93ca4e00-650d-11e9-8116-6b3798438319.png">

<img width="285" alt="螢幕快照 2019-04-22 下午2 42 44" src="https://user-images.githubusercontent.com/34327325/56487384-97f66b80-650d-11e9-99e6-2343c6ddf750.png">

**Comment by ryuichl** [comment]
已證實無此問題

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56549593-bd3eb480-65b5-11e9-8358-585a8d5eabce.png)

**Comment by AnitaRyzo** [comment]
更新文字與圖片，經過三小時後社群更新狀況如下
![image](https://user-images.githubusercontent.com/41721950/56558151-4c58c600-65d0-11e9-8205-6f1ccf5b9ac9.png)
