### ISSUE TITLE
【問題】表單管理下方文字超出畫面

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1229]
<img width="1440" alt="螢幕快照 2019-04-22 下午3 05 49" src="https://user-images.githubusercontent.com/34327325/56488195-49969c00-6510-11e9-8d88-dfdb3e939b99.png">

超出畫面，且沒有捲軸

**Comment by AnitaRyzo** [comment]
請參考互動後台的最後一行
![image](https://user-images.githubusercontent.com/41721950/56488992-cdea1e80-6512-11e9-91d2-51d16d3776c6.png)
以上補充，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/56799002-9220c300-684a-11e9-8152-2066643ac6ab.png)
◎◎ 20190426確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57214373-622ca900-701c-11e9-9429-7c8c1854d5f9.png)
◎◎ 20190506確認以上正式環境內容 ◎◎
