### ISSUE TITLE
【問題】序號機在專案重新送審發佈後出現的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1230]
STEP1.編輯者創建序號機並創建表單，專案發佈上線
STEP2.第一位A使用者登入社群，回填表單後得到QR code
STEP3.編輯者更換表單題目，重新送審後再次更新上線專案
STEP4.使用者F5重新整理專案網頁
![image](https://user-images.githubusercontent.com/41721950/56544271-8ca34e80-65a6-11e9-9765-525bfa0d5621.png)

利用不同瀏覽器或裝置登入社群帳號B使用者
出現錯誤一：五分鐘內重新整理專案網頁
登入後，不斷要求使用者填寫表單，但不會跳出QR code
![image](https://user-images.githubusercontent.com/41721950/56544605-9c6f6280-65a7-11e9-964c-4b62caedbf7b.png)

出現錯誤二：五分鐘後重新整理專案網頁
登入後，不用填寫表單直接顯示第一位A使用者的QR code
![image](https://user-images.githubusercontent.com/41721950/56544828-320af200-65a8-11e9-95ec-19316733c2c7.png)

『互動後台管理』只有A使用者的紀錄，其他帳號未寫入
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
server快取的問題
我會處理
@Gabe-Liu

**Comment by ryuichl** [comment]
稍微解釋一個這個issue
這個重現不用重新審核
之前後台快取時沒有考慮到序號這部分會因為不同人有不同結果

第一個問題是因為第一次進入專案
序號的狀態被紀錄下來
當使用者填完表單後取得序號
這時候他如果重整 理論上他可以直接看到序號
但是因為快取的關係他沒有序號
即使重填表單 後台也會回傳錯誤因為已經填過

第二個問題是因為當後台快取的狀態是任一使用者拿過序號後的狀態
其他人拿序號時就會直接看到第一個人的序號

目前已經改完上到測試環境
測試環境已經有開快取
@AnitaRyzo  有看不懂的再問我

**Comment by AnitaRyzo** [comment]
已依照原有步驟執行
◎◎ 20190423確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57216409-60fe7a80-7022-11e9-8738-e24b4bba92dd.png)
第一題：表單A-單選題

第二題是『相同表單A，更改題目』後再發佈
第二題a→「表單A-單行文字」填寫後得到正確序號
將「表單A-單行文字」改為「表單A-線性評分」儲存後發佈，五分鐘快取時間內重新整理頁面
第二題b→ 出現「表單A-單行文字」的舊題型，但仍可以填寫回覆表單送出，得到正確序號

第三題是『更改為其他表單B-線性評分』後再發佈
→ 如下出現錯誤訊息，待五分鐘快取結束之後仍可填寫表單B並取得正確序號
![image](https://user-images.githubusercontent.com/41721950/57216898-bab37480-7023-11e9-8eb4-64e74b30e205.png)
◎◎ 20190506確認以上正式環境內容 ◎◎
