### ISSUE TITLE
【測試環境】專案域名後置的兌獎頁面錯誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1233]
設立中獎後顯示QR code
![image](https://user-images.githubusercontent.com/41721950/56566475-546f3080-65e5-11e9-8289-76f4ad924dfe.png)
QR code顯示後連結至『cm.ryzoweba.com』而非兌獎頁面
![image](https://user-images.githubusercontent.com/41721950/56565973-2e955c00-65e4-11e9-81cd-cfec77928162.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
掃描QR code可到兌獎頁面，兌獎紀錄也會寫進後台
◎◎ 20190423確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
QR code可掃描到兌獎頁面，兌獎紀錄也會寫進後台。
◎◎ 20190703確認以上正式環境內容 ◎◎
