### ISSUE TITLE
【問題】當表單後台沒有表單，儲存『備註』會有錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1234]
『表單管理』的『表單-備註』
由以下畫面可知尚未建立任何表單，但『備註』卻可以輸入
![image](https://user-images.githubusercontent.com/41721950/56635009-91473000-6696-11e9-8048-ebc3020c2831.png)
錯誤訊息如下所示
![image](https://user-images.githubusercontent.com/41721950/56635245-8e007400-6697-11e9-9f24-2a6a79bd3629.png)
故無表單時，請協助隱藏『儲存備註』的按鈕
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
有表單才會出現『儲存備註』按鈕
![image](https://user-images.githubusercontent.com/41721950/59316897-3ecbdc80-8cf3-11e9-8abd-017658cf0e51.png)
◎◎ 20190612確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
後台有表單才會有"儲存備註"的按鈕
![1234](https://user-images.githubusercontent.com/49626114/60571388-1f7e1780-9da6-11e9-92b4-443f903f02ca.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
