### ISSUE TITLE
[問題]下載PDF後回到頁面固定框架的元件會跟著頁面移動

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1238]
iPone7(實體)/iPone XR(遠端)
step1.長頁面放輪播區塊，輪播區塊裡放電子申請書，下載pdf後。
step2.回到原頁面滑動時，固定框架的元件(裝飾圖案、圖示、圖片)會跟著頁面移動。
左圖的紅框是固定框架的正確位置，右圖的紅框是固定框架跑掉的樣子。
![image](https://user-images.githubusercontent.com/49626114/56705340-1daf2c80-6743-11e9-9548-855cb17d7667.png) ![image](https://user-images.githubusercontent.com/49626114/56705375-3586b080-6743-11e9-89e2-4c5e28522f91.png)

https://cm.ryzoweba.com/a0424-2

**Comment by AnitaRyzo** [comment]
實體：iPhone7/iPhone8，
遠端：iPhone XR/iPhone XS
固定框架的元件不會跟著頁面移動
◎◎ 20190429確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
實體：iPhone8，遠端：iPhone XR/iPhone XS/iPhone X/iPhone 6s
下載PDF後回到頁面，固定框架的元件不會跟著頁面移動
◎◎ 20190509確認以上正式環境內容 ◎◎
