### ISSUE TITLE
【文字連結】文字連結失效

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#124]
文字連結失效
https://judytest.ryzoweba.io/%E9%A0%81%E9%9D%A2?slideIndex=0

  裡面的兩段
信託銀行または信託会社と類似する会社名（商号）を用いる金融業者等にご注意ください
都有帶不同連結

第一個是帶外部連結
https://www.shintaku-kyokai.or.jp/news/other/caution/171019.html
第二個是帶內部得第二個幻燈片
https://judytest.ryzoweba.io/%E9%A0%81%E9%9D%A2?slideIndex=1

**Comment by ryuichl** [comment]
#48
