### ISSUE TITLE
【問題】手機版的時間題型無法帶入

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1241]
日期+時間的題型→先點『請選擇日期』會帶入00:00的時間，先點『請選擇時間』時間不會帶入
時間題型→點『請選擇時間』並按完成，時間不會帶入
![image](https://user-images.githubusercontent.com/41721950/56719898-33891580-6774-11e9-9227-af7873077593.png)
PS: 不管是在LINE或是一般瀏覽器都有問題
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
ios 6s 10.3.1
chrome可以  line和safari不行

**Comment by ai015606220** [comment]
@AnitaRyzo 請問是第一次操作都無法選擇時間嗎?  還是有按清除?

**Comment by AnitaRyzo** [comment]
第一次操作就無法選擇時間

**Comment by AnitaRyzo** [comment]
實體手機：iPhone6s/iPhone7/iPhone8/iPhoneXR點選時間皆會正確出現
遠端網路手機(browserstack)仍然無法選擇時間
◎◎ 20190429確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
實體手機：iPhone6s/iPhone7/iPhone8/iPhoneXR點選時間皆會正確出現
備註：遠端網路手機(browserstack)無法選擇時間
◎◎ 20190508確認以上正式環境內容 ◎◎
