### ISSUE TITLE
【問題】資料綁定選單樣式文字換行失效

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1243]
<img width="1308" alt="螢幕快照 2019-04-26 上午9 22 36" src="https://user-images.githubusercontent.com/34327325/56777596-059fe180-6805-11e9-92ac-ca4d86dbb612.png">

**Comment by leonlin6** [comment]
與Sam和Judy討論後，更改input為textarea

**Comment by leonlin6** [comment]
與Sam和Judy討論後，修正當 切換自動換行/手動換行 radio button時，改變「文字內容」欄位 textarea的style:white-space，若為手動換行，則textarea內容不自動換行，要使用者自己輸入enter，如下圖

![001](https://user-images.githubusercontent.com/29088297/62858202-437d3300-bd2c-11e9-97da-5e68a36f367e.jpg)
手動換行

![002](https://user-images.githubusercontent.com/29088297/62858300-80492a00-bd2c-11e9-86d1-9a655c426e6a.jpg)
自動換行

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/63010235-9683f100-beb8-11e9-8293-af2a3a54aecb.png)
◎◎ 20190814確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/63560839-25b09900-c58a-11e9-859c-d05f767177cc.png)
![image](https://user-images.githubusercontent.com/41721950/63560905-8049f500-c58a-11e9-874d-cacb95bc4c5d.png)
◎◎ 20190823確認以上正式環境內容 ◎◎
