### ISSUE TITLE
[問題]手機版輪播區塊放特定元件會lag

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1244]
iPhone 7(實體/遠端)  iPhone 6s(遠端)  iPhone 6(遠端)  iPad 6th(遠端) Google Nexus 7(遠端)會出現lag問題
iPhone 8以上都沒問題
同一個頁面放兩個輪播區塊，輪播區塊a放影片/內嵌網頁/內嵌程式碼，輪播區塊b放電子申請表時，會出現lag情況。
上圖是連結打開來的樣子，下圖是隔幾秒後出現全部元件。
![IMG_7429-1](https://user-images.githubusercontent.com/49626114/56786488-bc16bd00-682b-11e9-9664-e6fa8f195ead.png)
![IMG_7430-1](https://user-images.githubusercontent.com/49626114/56786489-bc16bd00-682b-11e9-9e08-8a6ec663ac1a.png)

檔案連結
1.影片+電子申請書
https://cm.ryzoweba.com/aaa0426-1
2.內嵌網頁+電子申請書
https://cm.ryzoweba.com/aaa0426-2
3.內嵌程式碼+電子申請書
https://cm.ryzoweba.com/aaa0426-3
4.正常不會lag的專案
https://cm.ryzoweba.com/aaa0426test

**Comment by ryuichl** [comment]
@cocosu123 
你這是指說裡面的元件
比較慢跑出來?

**Comment by cocosu123** [comment]
是整個輪播區塊跟輪播區塊裡的元件會比較慢出現

**Comment by ryuichl** [comment]
我覺得這應該只是單純效能問題

**Comment by cocosu123** [comment]
但是放其他元件在輪播區塊內就不會有這個問題

**Comment by ryuichl** [comment]
幫忙嘗試一下
在你的專案中
以影片為例子
如果是把影片放在輪播區塊內和放在外面
是否出現時間會有差別?

**Comment by cocosu123** [comment]
將元件分別放在輪播區塊內和外測試後，沒有時間差。
輪播區塊/輪播圖/影片/內嵌網頁/內嵌程式碼這五個元件的loading速度比其他元件慢，若放置更多其他元件也會導致上述元件loading更慢。
在遠端手機上測試也會因為不同的手機效能影響上述元件的loading速度。
