### ISSUE TITLE
【測試環境】元件設定開啟連結，連結失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1246]
元件：圖片、圖示、按鈕
『連結設定』的連結、電話、電子郵件
![image](https://user-images.githubusercontent.com/41721950/56939282-1bc9dc80-6b3a-11e9-90b9-d99378fb9785.png)
在預覽、UAT環境、發佈後環境會顯示以下訊息
![image](https://user-images.githubusercontent.com/41721950/56939173-7ca4e500-6b39-11e9-9100-cb74f2505195.png)
PS: 文字元件的『連結設定』執行是正確的
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
是不是因為改了fortify的issue影響到了?
@Gabe-Liu  @ai015606220

**Comment by AnitaRyzo** [comment]
預覽、UAT環境、發佈後環境皆可正確連結連結、電話、電子郵件、頁面、提示
![image](https://user-images.githubusercontent.com/41721950/57054955-76923e00-6cca-11e9-9be1-fc51e6035e15.png)
◎◎ 20190502確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
預覽、UAT環境、發佈後環境皆可正確連結連結、電話、電子郵件、頁面、提示
![image](https://user-images.githubusercontent.com/41721950/57422665-90400200-7243-11e9-8763-e12ea8b70682.png)
◎◎ 20190509確認以上正式環境內容 ◎◎
