### ISSUE TITLE
【問題】部分icon需要修改

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#1248]
1.圖片元件右側的“濾鏡設定”
旁邊說明文字的icon應該和其他地方統一
改成問號的樣子～
<img width="322" alt="螢幕快照 2019-04-15 下午5 13 31" src="https://user-images.githubusercontent.com/34293268/57053308-b1db3f80-6cbf-11e9-9669-81eda2f753cc.png">

附上fontawesome連結
https://fontawesome.com/icons/question-circle?style=regular

-----

2.表單選擇主題樣式包的魔術棒
改為互動元件選擇樣式時的魔術棒icon
<img width="1021" alt="螢幕快照 2019-04-16 下午12 24 10" src="https://user-images.githubusercontent.com/34293268/57053512-1fd43680-6cc1-11e9-820c-9e4f0cf907a9.png">
<img width="863" alt="螢幕快照 2019-05-02 上午9 56 46" src="https://user-images.githubusercontent.com/34293268/57053513-2367bd80-6cc1-11e9-99be-47a9d066ebcf.png">

附上連結
https://fontawesome.com/icons/magic?style=solid

---

3.圖示元件中
左右切換選擇樣式的方向鍵
應改為和裝飾圖案元件相同的icon

<img width="283" alt="螢幕快照 2019-04-16 上午10 01 08" src="https://user-images.githubusercontent.com/34293268/57053659-16979980-6cc2-11e9-96ac-c516b1d16882.png">
<img width="316" alt="螢幕快照 2019-04-16 上午10 01 17" src="https://user-images.githubusercontent.com/34293268/57053660-18615d00-6cc2-11e9-8bd0-6012ea89a824.png">

附上連結
https://fontawesome.com/icons/play?style=solid

---

4.表格元件右下角出現不知名小方塊(瀏覽器100%)
<img width="461" alt="螢幕快照 2019-04-16 上午10 26 05" src="https://user-images.githubusercontent.com/34293268/57053280-907a5380-6cbf-11e9-89da-adcdd25a5142.png">

瀏覽器調整成90%時 小方塊消失
<img width="417" alt="螢幕快照 2019-05-02 上午9 49 37" src="https://user-images.githubusercontent.com/34293268/57053293-9f610600-6cbf-11e9-91df-8cf3136bb3fa.png">

---
5.電子申請書在畫布上的icon是表單的
應該改成和左側元件相同長相
<img width="1280" alt="表單類型icon-4" src="https://user-images.githubusercontent.com/34293268/57054309-4d6fae80-6cc6-11e9-961d-fd2bf5759666.png">

以上協助修改～
感恩的心～～

**Comment by AnitaRyzo** [comment]
1.圖片元件右側的“濾鏡設定”，改成問號
![image](https://user-images.githubusercontent.com/41721950/59240634-4928a080-8c37-11e9-8272-9110a13383da.png)
2.表單選擇主題樣式包的魔術棒，改為互動元件選擇樣式時的魔術棒icon
![image](https://user-images.githubusercontent.com/41721950/59240486-29917800-8c37-11e9-84ae-c8da40e72bfe.png)
3.圖示元件左右切換選擇樣式的方向鍵，改為和裝飾圖案元件相同的icon
![image](https://user-images.githubusercontent.com/41721950/59240724-9442b380-8c37-11e9-8ed6-8dcd077e74f5.png)
4.表格元件右下角無小方塊(瀏覽器150%)
![image](https://user-images.githubusercontent.com/41721950/59240811-e4217a80-8c37-11e9-9f9c-4da41f005601.png)
5.電子申請書改成和左側元件相同長相
![image](https://user-images.githubusercontent.com/41721950/59241042-a6712180-8c38-11e9-8016-a0b36726bbf0.png)
◎◎ 20190611確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
1.圖片濾鏡的文字說明icon
![1248圖片濾鏡](https://user-images.githubusercontent.com/49626114/60474946-73ee9d80-9ca7-11e9-989e-7dc75bbe3ce7.PNG)
2.表單選擇主題樣式包的魔術棒
![1248表單主題樣式魔法棒](https://user-images.githubusercontent.com/49626114/60474964-8963c780-9ca7-11e9-8562-c1a954037ce1.PNG)
3.圖示元件的切換箭頭
![1248圖示元件箭頭](https://user-images.githubusercontent.com/49626114/60475018-c203a100-9ca7-11e9-86c6-2a8607d70334.png)
4.表格元件的右下角已沒有小方塊(瀏覽器100%)
![1248表格](https://user-images.githubusercontent.com/49626114/60475060-0000c500-9ca8-11e9-81f6-75ffe64f1a3b.png)
5.電子申請書的圖示
![1248電子申請書](https://user-images.githubusercontent.com/49626114/60475081-1ad33980-9ca8-11e9-8755-47ee2ec1bbf3.png)
◎◎ 20190701確認以上正式環境內容 ◎◎
