### ISSUE TITLE
【測試環境】序號與抽獎類型表單，下載後的EXCEL內容缺少

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1252]
在.io環境中
序號表單不論是否已兌獎都有顯示『TRUE』『FALSE』
![image](https://user-images.githubusercontent.com/41721950/57117021-9fc6d300-6d8b-11e9-9ab5-74d39bc020b7.png)
抽獎表單皆顯示『獎項』名稱與『已兌獎』的狀態
![image](https://user-images.githubusercontent.com/41721950/57117408-65ab0080-6d8e-11e9-9345-715d09fcc317.png)

但是在.com環境中
序號表單僅顯示已兌獎為『TRUE』的內容
![image](https://user-images.githubusercontent.com/41721950/57116991-52e2fc80-6d8b-11e9-8301-1681ff858d98.png)
抽獎表單未顯示『獎項』名稱與『已兌獎』的狀態
![image](https://user-images.githubusercontent.com/41721950/57117096-35faf900-6d8c-11e9-8f04-e82dc67f5744.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
抽獎表單
![image](https://user-images.githubusercontent.com/41721950/57590383-f5566900-755d-11e9-92a8-7c4dc01f6cf4.png)
序號表單
![image](https://user-images.githubusercontent.com/41721950/57590475-904f4300-755e-11e9-971b-9f7a774adc84.png)
◎◎ 20190513確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1252](https://user-images.githubusercontent.com/49626114/60567651-3409e200-9d9d-11e9-9bc3-0f1d98c0c5de.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
