### ISSUE TITLE
【測試環境】Banner的圖示元件在編輯區與下載後不同

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1253]
Banner的圖示元件在編輯區如下設定
![image](https://user-images.githubusercontent.com/41721950/57269559-82ab4080-70ba-11e9-8f4b-08a075ce9093.png)
不管利用哪個管道『下載』
![image](https://user-images.githubusercontent.com/41721950/57269675-eafa2200-70ba-11e9-8892-a3f7b57797cc.png)
「圖示顏色」與「框線設定」皆與編輯區不同
![image](https://user-images.githubusercontent.com/41721950/57269741-23016500-70bb-11e9-9213-d6798c148830.png)
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
截圖功能的框線只支援實心線，請 @ryzojudy 討論一下，是否有需要保留框線功能，或者只留下實心線。

**Comment by ryzojudy** [comment]
框線部分只保留實心線好了

**Comment by AnitaRyzo** [comment]
編輯區僅『實心線』框線，編輯區與下載後的內容是相同的
![image](https://user-images.githubusercontent.com/41721950/57424117-232f6b00-7249-11e9-8763-d7833b8447f2.png)
◎◎ 20190509確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
Banner的圖示元件編輯區僅『實心線』框線，編輯區與下載後的內容是相同的
![image](https://user-images.githubusercontent.com/41721950/59991450-05dc2200-967a-11e9-9b10-630fb62199f4.png)
