### ISSUE TITLE
【測試環境】一般表單與電子申請書的+題目選項無法輸入英文與數字

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1260]
一般表單與電子申請書的題目選項無法輸入英文與數字
![image](https://user-images.githubusercontent.com/41721950/57282592-f3188880-70df-11e9-8a53-4ecc36ad5111.png)
PS: 序號產生器與抽獎類型的表單可以
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
我們是用Chrome編輯，沒有跳出任何錯誤訊息
PS: 其實很多地方都不能輸入英文數字，目前還在整理中

**Comment by AnitaRyzo** [comment]
目前已可正常輸入
![image](https://user-images.githubusercontent.com/41721950/58236038-a508b380-7d74-11e9-8bed-327737e99440.png)
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1260](https://user-images.githubusercontent.com/49626114/60566178-b2b05080-9d98-11e9-9741-8a85f095494f.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
