### ISSUE TITLE
【測試環境】未開啟電腦版，電腦模式與手機模式顯示相同

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1261]
前提：未開啟電腦版
測試環境中，電腦模式與手機模式顯示相同
![image](https://user-images.githubusercontent.com/41721950/57287432-11838180-70ea-11e9-9179-21455b6a8f2f.png)

正式環境中，電腦模式會多留白的空間
![image](https://user-images.githubusercontent.com/41721950/57287011-26134a00-70e9-11e9-9539-13735d14c0b4.png)
不知道是否有更改設計?? 請協助確認。感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57427241-a3f46400-7255-11e9-939a-a666c891152b.png)
![image](https://user-images.githubusercontent.com/41721950/57427272-cb4b3100-7255-11e9-8434-a97542b2355d.png)
◎◎ 20190509確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1261](https://user-images.githubusercontent.com/49626114/60563078-d1a8e580-9d8c-11e9-9a6b-84b195b1f6a8.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
