### ISSUE TITLE
【測試環境】選單架構未顯示在編輯區

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1262]
開啟『漢堡選單』，且選擇『展開』選單
正式環境的編輯區會如下『展開』
![image](https://user-images.githubusercontent.com/41721950/57343141-b64aa100-7174-11e9-9dea-2d1290b27776.png)
但測試環境的編輯區未顯示
![image](https://user-images.githubusercontent.com/41721950/57343279-3ffa6e80-7175-11e9-969f-9bc41c9f7877.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57430919-bb3a4e00-7263-11e9-95af-67be59512d77.png)
◎◎ 20190509確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1262](https://user-images.githubusercontent.com/49626114/60562989-665f1380-9d8c-11e9-849d-95d3a07bc73e.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
