### ISSUE TITLE
【測試環境】收縮區塊的編輯模式，增加元件卻未能帶入其中

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1264]
step1.設立收縮區塊，並在『編輯模式』隨意放入一個元件
![image](https://user-images.githubusercontent.com/41721950/57346125-f6fbe780-717f-11e9-9ca7-6641d6c32c9e.png)
step2.點選收縮區塊的框架
![image](https://user-images.githubusercontent.com/41721950/57346348-bea8d900-7180-11e9-99bf-bbab436157c9.png)
step3.點選元件，卻發現元件未在『編輯模式』中
![image](https://user-images.githubusercontent.com/41721950/57346113-ef3c4300-717f-11e9-907f-e89a3b63c97c.png)
依照此步驟，正式環境會將元件帶入『編輯模式』中
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
現在已無法執行『step2.點選收縮區塊的框架』
增加的元件也會計算在編輯模式中
![image](https://user-images.githubusercontent.com/41721950/57430040-eec7a900-7260-11e9-9ea7-a973dfd63bf1.png)
◎◎ 20190509確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
現在已無法執行『step2.點選收縮區塊的框架』
增加的元件會直接計算在編輯模式中
![1264](https://user-images.githubusercontent.com/49626114/60562501-737b0300-9d8a-11e9-806f-b2f599d89844.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
