### ISSUE TITLE
【問題】樞紐設定的分頁資料未能顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1267]
『數據後台』的『分頁數據』有資料
![image](https://user-images.githubusercontent.com/41721950/57598304-4b8ad280-7585-11e9-8e9f-208d54649bd5.png)
但在『樞紐設定』若有點選『分頁』，訊息會停留在「在所選條件下，暫無數據」
![image](https://user-images.githubusercontent.com/41721950/57598477-f602f580-7585-11e9-9648-a9d1d6fa063a.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
樞紐設定的資料皆能正常呈現
![1267](https://user-images.githubusercontent.com/49626114/60562057-8a205a80-9d88-11e9-91a6-291f89e6e854.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
