### ISSUE TITLE
【疑問】跨帳號查看數據可以多次增加同一個專案的資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1270]
跨帳號查看數據
只要用梅花座的形式，就可以不斷將「同一個人的同一個專案」不斷放入，如下所示
![image](https://user-images.githubusercontent.com/41721950/57663870-63676280-7628-11e9-8ecb-e3bf6d14bada.png)
右下角顯示圖表處，雖然有用『專案名稱#1』將專案隔開(如紅框)，但與第一排的專案名稱與圖表名稱不符，使用者是無法直觀了解，每個顏色到底是屬於哪個專案的數據。
請協助修改此畫面顯示，感恩~

**Comment by AnitaRyzo** [comment]
曾被選取的專案，會一直抱持被選取的狀態；故無法再多次增加同一個專案
![image](https://user-images.githubusercontent.com/41721950/58522003-1b803800-81f1-11e9-9931-6f9c7c4ed129.png)
◎◎ 20190529確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
已被選取的專案會一直顯示被選取的狀態(有藍色框線框住)，所以無法再多次增加同一個專案。
![1270](https://user-images.githubusercontent.com/49626114/60561370-dfa73800-9d85-11e9-8b59-f72181e754e3.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
