### ISSUE TITLE
【問題】MGM後台的階層抬頭不會自動關閉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1271]
在互動後台管理，每一個MGM都可以切換『社群列表』
社群列表每一個帳號都可利用『觸及人數』了解此帳號有多少下線
![image](https://user-images.githubusercontent.com/41721950/57669117-58b6c880-763c-11e9-93b4-aac0f58fe3f0.png)
點擊『觸及人數』即可開啟階層關係列表
![image](https://user-images.githubusercontent.com/41721950/57669308-fd390a80-763c-11e9-88d1-972c43f26e76.png)
若未按『返回』回到上一層，直接切換至其他MGM
紅框處的資料將會一直保留，而這樣顯示容易造成使用者誤解
![image](https://user-images.githubusercontent.com/41721950/57669370-45582d00-763d-11e9-8616-3f798ae70007.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
MGM後台的階層抬頭會自動關閉
![image](https://user-images.githubusercontent.com/41721950/58463214-014d4800-8166-11e9-8ba9-fa12116650aa.png)
◎◎ 20190528確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
mgm後台的階層抬頭已會自動關閉。
![1271](https://user-images.githubusercontent.com/49626114/60425183-8a074a00-9c24-11e9-882b-7ab78d26a53c.png)
◎◎ 20190701確認以上正式環境內容 ◎◎
