### ISSUE TITLE
【問題】帳號的第一個專案連到數據後台頁，顯示其他專案的數據資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1272]
從『專案管理』的專案點選『數據』
![image](https://user-images.githubusercontent.com/41721950/57684480-7568f580-7668-11e9-9aa4-b6d4378d3320.png)
會開啟『數據後台』頁面，且會顯示「點選的專案數據資料」
![image](https://user-images.githubusercontent.com/41721950/57684878-41da9b00-7669-11e9-8935-4298bc5db369.png)
但每個帳號的第一個專案，從『專案管理』的專案點選『數據』，開啟『數據後台』顯示的是「創建日期最近的專案」。
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
帳號的第一個專案已可正確連到數據後台頁的專案
![image](https://user-images.githubusercontent.com/41721950/58140717-eb75e980-7c72-11e9-87ee-336b6153c07c.png)
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
第一個專案已可正確連到數據後台頁的專案
![1272](https://user-images.githubusercontent.com/49626114/60561242-77f0ed00-9d85-11e9-94ae-1215bca6ef92.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
