### ISSUE TITLE
【問題】從抽獎紀錄可預測獎項且可重複回填表單

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1273]
互動元件按下『開始』按鈕之後，獎項就已決定。而元件有兩組呈現獎項的方式
A組互動元件的動畫會直接執行，無法點選改變；
B組互動元件上有遮罩，需要再次點選互動元件才有動畫；B組名單如下。
![image](https://user-images.githubusercontent.com/41721950/57754401-e9ff6b00-7720-11e9-98a0-0c4130227897.png)

若對B組名單執行以下步驟，後台會重複收集表單回覆
STEP1.按下『開始』按鈕(黃框)
STEP2.點選『抽獎紀錄圖示』(紅框)
![image](https://user-images.githubusercontent.com/41721950/57754166-62196100-7720-11e9-9179-f03517db8e64.png)
STEP3.跳出『中獎紀錄』的獎項，此時『填寫資料』回覆表單；再關閉表單。
![image](https://user-images.githubusercontent.com/41721950/57754939-3008fe80-7722-11e9-95fb-17430e3d2792.png)
STEP4.點選互動元件產生動畫後會跳出獎項，此時可以再一次『填寫資料』回覆表單
![image](https://user-images.githubusercontent.com/41721950/57755280-13b99180-7723-11e9-953f-68451f9671a0.png)
後台：寫入兩次表單回覆
![image](https://user-images.githubusercontent.com/41721950/57755326-3d72b880-7723-11e9-9f66-abc9851a0ac4.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
請問怎麼預測獎項?

**Comment by AnitaRyzo** [comment]
按照原始設計流程，『中獎紀錄』是要執行互動元件的動畫才會得知是哪個獎項。
但B組元件可以從第三步驟-先開啟『中獎紀錄』，就提前得知獎項。

**Comment by ryuichl** [comment]
重覆回填的部分
我後端會增加驗證 一個獎項只能填一次表
前端也麻煩檔一下重複回填 @Gabe-Liu  @ai015606220 

至於提前得知獎品我是覺得還好

**Comment by Gabe-Liu** [comment]
現在改成點開始遊戲後，必須要完成遊戲，點擊查看紀錄才可觀看紀錄。

**Comment by AnitaRyzo** [comment]
已確認點『開始』按鈕後，必須要完成遊戲，點擊查看紀錄才可觀看紀錄。
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
點選"開始"按鈕後，直接點擊中獎紀錄圖示無反應，必須先完成遊戲才能夠查看中獎紀錄。
◎◎ 2019701確認以上正式環境內容 ◎◎
