### ISSUE TITLE
[問題]首頁跑完先顯示，其他頁面再慢慢讀取

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1274]
目前狀況 : 
開啟專案就會一次讀取完整個專案，進度條呈現的樣子是整個專案讀取的進度。
專案第一個頁面沒有圖片但也需要等其他頁面的內容都讀取完畫面才會顯示。
![網頁進度條](https://user-images.githubusercontent.com/49626114/57764507-2f7a6300-7736-11e9-963d-d086b2370322.jpg)

討論後決定修改狀況 : 
進度條呈現的樣子是專案第一個頁面讀取的進度。
專案第一個畫面跑完後要先顯示出來，其他頁面的內容再慢慢讀取。
附註 : 切換頁面時，其他頁面的內容若未讀取完成就需要等待內容讀取完成。

**Comment by AnitaRyzo** [comment]
由Network可知，會先讀取首頁的Img，再讀取其他頁面
![image](https://user-images.githubusercontent.com/41721950/58143796-a657b480-7c7e-11e9-8877-e647155c08e1.png)
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
1.專案第一個頁面沒有圖片但不需要等其他頁面的內容都讀取完畫面才會顯示。只要第一個頁面的可視範圍內容讀取完就會直接顯示。
![1274-1](https://user-images.githubusercontent.com/49626114/60560779-d2894980-9d83-11e9-94fd-d852c1a325bc.png)
2.由Network可知，會先讀取可視範圍的Img(黃框&橘框)，只要可視範圍內的圖片讀取完就會先顯示畫面，其他剩下的Img(綠框)會再慢慢讀取。
![1274-2](https://user-images.githubusercontent.com/49626114/60560885-3449b380-9d84-11e9-824e-4ce4e953e7d2.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
