### ISSUE TITLE
【問題】電子表單的PDF版面配置有圖片，手機就無法下載

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1275]
實體手機：iPhone 7/iPhone 8/Samsung A7
@Gabe-Liu 告知 IOS只能用safari，Andriod只知道chrome
以此為基礎，發現在『PDF版面配置』若『+頁面』是有放圖片的
![image](https://user-images.githubusercontent.com/41721950/57824419-8ed78200-77cd-11e9-9c89-babc60c197e4.png)
電子表單填表完成後，點選『檔案寄出頁』沒有反應；
後台『表單管理』出現「404頁面」
![image](https://user-images.githubusercontent.com/41721950/57824754-b3802980-77ce-11e9-8e48-ef1f66c0c975.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
實體手機：iPhone 7/iPhone 8/Samsung A7
電子表單的PDF版面配置有圖片，手機可以下載檔案
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
實體手機：iPhone 7/Samsung A7
電子表單的PDF版面配置有圖片，手機可以下載檔案
◎◎ 20190703確認以上正式環境內容 ◎◎
