### ISSUE TITLE
【問題】資料綁定的分類切換之圖片設定，未即時呈現在預覽區

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1276]
資料綁定的『分類切換設定』其中一個樣式有預設圖片
而圖片設定的『圓角、不透明度、圖片剪裁』都未即時呈現在右手邊的預覽區
]![image](https://user-images.githubusercontent.com/41721950/57836207-cc023b00-77f2-11e9-984c-d5e87463c284.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58400365-608b5980-808d-11e9-8ab6-5409574ec712.png)
◎◎ 20190527確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1276](https://user-images.githubusercontent.com/49626114/60076566-79556080-975a-11e9-8f7a-e71f0cf7529e.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
