### ISSUE TITLE
【ml環境】重新設定密碼 按鈕 顯示異常

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1277]
如題
透過忘記密碼的功能 重設密碼送出後
按鈕的顯示異常 ( 但功能不影響 )

![image](https://user-images.githubusercontent.com/11918396/57843497-f4913180-7800-11e9-96ac-15fb3f857fdd.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58140232-e57f0900-7c70-11e9-9506-31273936b974.png)
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1277](https://user-images.githubusercontent.com/49626114/60558801-1036a400-9d7d-11e9-8140-cc037b87d26f.PNG)
◎◎ 20190703確認以上正式環境內容 ◎◎
