### ISSUE TITLE
【ml環境】UAT 網址 導向錯誤

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1278]
![image](https://user-images.githubusercontent.com/11918396/57897353-f3a2e300-7886-11e9-88ce-a46ae9c9f321.png)

如圖所示
原本應該是 https://pubb.ml/weba/uat-k0516
會被導向至 https://pubb.ml/weba/uat-uat-k0516

**Comment by AnitaRyzo** [comment]
已確認問題已解決
◎◎ 20190614確認以上測試環境內容 ◎◎
