### ISSUE TITLE
【希望】收縮區塊加圖示、框線、背景色

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#128]
希望收縮區塊的標題可以加圖示
整個元件可以加框線
收縮內容的區塊可以設定背景顏色

希望在切換【一般狀態】和【展開狀態】時
畫布中的元件也可以跟著一起變動
現在是標即呈現一般狀態 但整體卻是展開的樣子

希望收縮區塊市展開時才把元件往下排
目前的話 會有一個神奇的空白區域
![image](https://user-images.githubusercontent.com/34263719/39981009-220cd836-5781-11e8-860b-d54c90eeaaf6.png)

**Comment by wilmaftliu** [comment]
建議收縮區塊的「背景」可以叫「標題背景」因為目前收縮區塊內是不能設定背景色的 避免混淆
<img width="326" alt="2018-06-07 12 15 39" src="https://user-images.githubusercontent.com/34560641/41078028-c9d8943c-6a4c-11e8-9db7-f54319494d83.png">

**Comment by Samasianspock** [comment]
@Gabe-Liu 輪播區塊與頁籤希望也一併新增「背景色」的設定。
加框線的效果是包覆整個元件，參考下列示意圖。
<img width="313" alt="2018-07-25 2 58 45" src="https://user-images.githubusercontent.com/37531593/43185353-4447d3ee-901e-11e8-8646-4aa143387e49.png">
