### ISSUE TITLE
【ml環境】小積木 圖片路徑錯誤

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1280]
as title 
請參考下圖所示
![image](https://user-images.githubusercontent.com/11918396/57900017-d6274680-7891-11e9-9c27-f1b84afd70cb.png)

**Comment by AnitaRyzo** [comment]
積木已可正確顯示
![image](https://user-images.githubusercontent.com/41721950/58158266-abcbf380-7cac-11e9-9829-289b663b66fe.png)
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
積木皆正確顯示
![1280](https://user-images.githubusercontent.com/49626114/60558518-1710e700-9d7c-11e9-91e8-c2dd0c273ca5.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
