### ISSUE TITLE
【測試+ml】框架設定只在最後一個設定的元件正確執行

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1281]
在測試環境與ml環境下，對元件執行『框架設定』
開啟『將元件固定』，並選擇『固定至所有分頁』或『固定至所有幻燈片』其一
只有最後一個「被設定的元件」會正確執行
![image](https://user-images.githubusercontent.com/41721950/57902507-070c7900-789c-11e9-9615-f5a8d17bd8dc.png)
PS: 在正式環境是正確執行的。
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
框架設定的元件已可正確執行
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
所有元件的框架設定皆可正確執行
◎◎ 20190703確認以上正式環境內容 ◎◎
