### ISSUE TITLE
【測試+ml】審核發佈管理頁面之篩選的圖示掉圖

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1282]
篩選排序『按送審時間排序』的圖示掉圖
![image](https://user-images.githubusercontent.com/41721950/57906252-eba96a00-78ab-11e9-92b7-d366fa74db06.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58142466-c9339a00-7c79-11e9-90cc-be78b022e830.png)
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
圖示皆正常呈現
![1282](https://user-images.githubusercontent.com/49626114/60558229-0613a600-9d7b-11e9-9592-d04cd070f4b3.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
