### ISSUE TITLE
【測試環境】固定答案題型的題目設定

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1283]
固定答案的題型只能讓編輯者看到，填表者不會知道有這題
![image](https://user-images.githubusercontent.com/41721950/57917608-a135e680-78c7-11e9-8690-5e4e4290ebdc.png)
問題一：若設計為一題一頁時，進度條百分比不能達到100%
建議：是否能參考『標題說明』不影響進度條，或是直接計算為完成的題型?
![image](https://user-images.githubusercontent.com/41721950/57917821-173a4d80-78c8-11e9-98db-c57e583488df.png)
問題二：是否需要有『必選題』的選項
問題三：是否需要被設定為『跳題』的對象
以上問題請協助設計，感恩~

**Comment by ryzojudy** [comment]
同意直接改為「標題說明」不影響進度條的部分
另外也拿掉「必選」和「跳題」的兩個設定
感謝~~~~
@liucwlewis 再麻煩路易斯協助出圖 感謝~

**Comment by liucwlewis** [comment]
已上傳～～～囉～

**Comment by AnitaRyzo** [comment]
答一：『固定答案』未計算為百分比的分母
![image](https://user-images.githubusercontent.com/41721950/58391971-6de31c80-806a-11e9-81d4-bae779f9828b.png)
答二三：無「必選」和「跳題」
![image](https://user-images.githubusercontent.com/41721950/58390855-de3b6f00-8065-11e9-9102-86acefebf8ad.png)

**Comment by cocosu123** [comment]
1.固定答案題型不會影響進度條的計算
![1283-1](https://user-images.githubusercontent.com/49626114/60557650-eb403200-9d78-11e9-90ff-22bd399f4ae3.png)
2.固定答案題型無"必選"和"跳題"
![1283-2](https://user-images.githubusercontent.com/49626114/60557676-0743d380-9d79-11e9-9a72-2ccb5f4ec852.PNG)
◎◎ 20190703確認以上正式環境內容 ◎◎
