### ISSUE TITLE
【測試+ml】新增或複製元件突然卡住不能移動

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1284]
新增或複製元件時，元件會突然卡住不能移動
console的錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/57919975-844fe200-78cc-11e9-96cd-a768d62b4e94.png)
重新整理網頁後就可以再次移動元件
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
目前複製元件不會出現此錯誤訊息
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
目前新增或複製元件都正常，不會出現錯誤訊息。
◎◎ 20190703確認以上正式環境內容 ◎◎
