### ISSUE TITLE
[測試環境] 序號兌換網址錯誤

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1287]
兌換的網址後面似乎是/client寫死的
再討論一下要怎麼改
@Gabe-Liu

**Comment by AnitaRyzo** [comment]
序號可兌換
![image](https://user-images.githubusercontent.com/41721950/58147188-e5403700-7c8b-11e9-8fc1-1f4e3a5cdf95.png)
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
序號可以兌換
![1287](https://user-images.githubusercontent.com/49626114/60556971-458bc380-9d76-11e9-8465-42ee45e339bb.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
