### ISSUE TITLE
[測試環境] 管理者後台沒畫面

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1289]
superuser的後台沒畫面
![image](https://user-images.githubusercontent.com/10150807/57999372-bc8f3480-7b07-11e9-9577-5b022fef8cae.png)
![image](https://user-images.githubusercontent.com/10150807/57999382-cca71400-7b07-11e9-858f-df42c56c2a31.png)
api的部分沒有統一吃配置更動網址

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58067449-e7d55a80-7bbf-11e9-8655-13959af6c9ad.png)
◎◎ 20190521確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1289](https://user-images.githubusercontent.com/49626114/60556838-9a7b0a00-9d75-11e9-8ef1-9af2c07f94bb.PNG)
◎◎ 20190703確認以上正式環境內容 ◎◎
