### ISSUE TITLE
【測試環境】序號後台未帶入社群資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1290]
獎項列表可知已被領取序號
但『登入人數』與『社群列表』都沒有資料
![image](https://user-images.githubusercontent.com/41721950/57999378-c749c980-7b07-11e9-8d48-a0674be9f065.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58146703-d22c6780-7c89-11e9-98f8-7d1afd41db93.png)
◎◎ 20190522確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1290](https://user-images.githubusercontent.com/49626114/60556755-46702580-9d75-11e9-8425-cf87862faa62.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
