### ISSUE TITLE
[問題]陰影設定未正常呈現在預覽頁及發佈頁

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1291]
1.文字及時間倒數設定陰影若超出編輯框線，在預覽頁面及發佈頁面會切掉超出編輯框線的內容。
2.按鈕及表單設定陰影，在預覽頁面及發佈頁面未呈現陰影的樣子。

![#](https://user-images.githubusercontent.com/49626114/58001188-59a09c00-7b0d-11e9-8a26-6a545922b0a3.PNG)

**Comment by AnitaRyzo** [comment]
無論何處都如下顯示
![image](https://user-images.githubusercontent.com/41721950/58233754-7b00c280-7d6f-11e9-9d9e-e37daa512f49.png)
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1291](https://user-images.githubusercontent.com/49626114/60555638-651fed80-9d70-11e9-828d-c0bcdd1f7c66.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
