### ISSUE TITLE
【問題】圓形的裝飾區塊在蘋果手機被切邊

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1292]
圓形的裝飾區塊在蘋果手機被切邊，如下紅框
![image](https://user-images.githubusercontent.com/41721950/58001658-b6e91d00-7b0e-11e9-9c6d-92013db5bf22.png)
以上問題請協助處理，感恩~
補充：當裝飾區塊的尺寸小於100*100後，尺寸越小切邊的狀況會越來越明顯

**Comment by AnitaRyzo** [comment]
已無切邊情況
![image](https://user-images.githubusercontent.com/41721950/59242594-b0961e80-8c3e-11e9-884a-06ee5a4d6225.png)
◎◎ 20190611確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
在蘋果手機&安卓手機皆無切邊情況。
![1292](https://user-images.githubusercontent.com/49626114/60556081-34d94e80-9d72-11e9-8070-9c6daf055cde.jpg)
◎◎ 20190703確認以上正式環境內容 ◎◎
