### ISSUE TITLE
【測試環境】使用Query登入後，會自動執行互動元件

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1293]
身份驗證方式-Query String
依照『定義KEY』在頁面後增加指定的字元
此情境範例的『定義KEY』為id
![image](https://user-images.githubusercontent.com/41721950/58012236-9f1d9300-7b26-11e9-8d20-655e2cc65b67.png)
網址中的頁面後增加?id=bbb
按下『登入』按鈕後，換顯示『開始』按鈕；使用者必須重複按兩次按鈕
![image](https://user-images.githubusercontent.com/41721950/58012212-8c0ac300-7b26-11e9-92f0-73f4b7584127.png)
請修改此操作流程，按下『登入』後跳『開始』，會自動開始執行互動元件。
以上建議請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
使用Query網址進入網站，按下『登入』按鈕會自動執行互動元件
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
使用Query String進入網站，按『登入』按鈕後會自動執行互動元件。
◎◎ 20190701確認以上正式環境內容 ◎◎
