### ISSUE TITLE
【測試環境】互動元件的設定獎項之匯入序號

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1294]
設定獎項新增『匯入序號』功能，抓第A欄的資料
疑問：匯入EXCEL的資料表，是否跟資料綁定一樣限定只能.xlsx的表單?
![image](https://user-images.githubusercontent.com/41721950/58063746-12201b80-7bb2-11e9-82e3-51034eae113d.png)
問題：點擊匯入的表單，會跳出如右的空白內容
![image](https://user-images.githubusercontent.com/41721950/58063916-bdc96b80-7bb2-11e9-8d3c-01555e5eacbb.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
設定獎項的匯入內容已可顯示
![image](https://user-images.githubusercontent.com/41721950/58065373-0e8f9300-7bb8-11e9-8d66-beb36969ac75.png)
◎◎ 20190521確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
匯入序號後的內容已正常顯示。
![1294](https://user-images.githubusercontent.com/49626114/60423634-347d6e00-9c21-11e9-8c1c-10f64a252586.png)
