### ISSUE TITLE
【測試環境】互動元件抽獎並填表後 打開抽獎紀錄會報錯

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1295]
不管選擇哪項『獎項序號樣式』都有以下問題
![image](https://user-images.githubusercontent.com/41721950/58064116-7c858b80-7bb3-11e9-8b1f-0910f82e9973.png)

step1. 登入社群後得到互動資格，按下『開始』按鈕後抽獎
step2.回填表單
step3.點選『抽獎紀錄圖示』會出現空白的紀錄
![image](https://user-images.githubusercontent.com/41721950/58064380-5f9d8800-7bb4-11e9-991a-04e59b917594.png)
錯誤記錄如下所示
![image](https://user-images.githubusercontent.com/41721950/58063674-c8cfcc00-7bb1-11e9-946b-b3923a1d3758.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
與 #1299 第二點是一樣的錯誤

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58221125-08c6b880-7d44-11e9-8084-585dac745757.png)
![image](https://user-images.githubusercontent.com/41721950/58221132-0e240300-7d44-11e9-8212-4b7776bd38ba.png)
延伸問題已開#1301 
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
中獎紀錄已正常呈現。
![1295](https://user-images.githubusercontent.com/49626114/60423311-81ad1000-9c20-11e9-84f0-56a35f9eeb62.png)
◎◎ 20190701確認以上正式環境內容 ◎◎
