### ISSUE TITLE
【測試環境】互動元件的設定獎項之匯入序號呈現

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1296]
互動元件的設定獎項之匯入序號
點選excel表單進入後，可以看到每一列的內容用表格方式顯示
![image](https://user-images.githubusercontent.com/41721950/58065169-5cf06200-7bb7-11e9-8e54-9ed1aa22ba8e.png)
當資料為英數時，會超出表格框線延伸顯示
![image](https://user-images.githubusercontent.com/41721950/58065135-40542a00-7bb7-11e9-9114-575e6ff01648.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58221506-57288700-7d45-11e9-905b-b964678e6ad9.png)
請幫忙再研究一下，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58297694-2f9bf200-7e0b-11e9-9725-21cdb9002652.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
若內容太長時，如圖A所顯示，不會超出表格框線。
若內容包含特殊字元，如圖B所顯示，會跳出提示訊息。
![1296](https://user-images.githubusercontent.com/49626114/60422767-4a8a2f00-9c1f-11e9-8bf4-9dc0a883f383.png)
◎◎ 20190701確認以上正式環境內容 ◎◎
