### ISSUE TITLE
【測試環境】互動元件被遺漏的圖示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1297]
互動元件被遺漏的圖示列表如下
![image](https://user-images.githubusercontent.com/41721950/58065679-1f8cd400-7bb9-11e9-8039-4427d4bb378a.png)
![image](https://user-images.githubusercontent.com/41721950/58065688-2582b500-7bb9-11e9-8142-0e66ed1d8875.png)
請幫忙帶入，感恩~

**Comment by AnitaRyzo** [comment]
已確認所有互動元件的圖示皆有顯示
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
互動元件的所有圖示已正常呈現。
◎◎ 20190701確認以上正式環境內容 ◎◎
