### ISSUE TITLE
【測試環境】互動元件的自動傳送表單失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1299]
『表單設定』勾選『自動傳送表單』
![image](https://user-images.githubusercontent.com/41721950/58068410-d9893d80-7bc3-11e9-8eda-9376883f6489.png)
問題一：表單後台未有資料寫入
![image](https://user-images.githubusercontent.com/41721950/58071226-85378b00-7bce-11e9-827b-dc9a27373b64.png)
問題二：『狀態(提示)頁』開啟兌獎『QR Code』，但實際在瀏覽器開啟『抽獎紀錄圖示』未出現
![image](https://user-images.githubusercontent.com/41721950/58071150-3a1d7800-7bce-11e9-824a-1d08cbc17f5d.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
互動元件已會自動傳送表單
延伸問題已開新issue
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
互動元件的自動傳送表單已正常執行。
◎◎ 20190701確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60576175-7e945a00-9daf-11e9-94cc-ebc2324ab9dc.png)
◎◎ 20190703確認以上正式環境內容 ◎◎
