### ISSUE TITLE
【測試環境】互動元件的設立獎項是匯入資料時，啟動元件失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1300]
step1.原始的互動元件設立獎項時，獎項設計使用『匯入序號』
![image](https://user-images.githubusercontent.com/41721950/58077267-bd46ca00-7bde-11e9-94a5-93e6a452642e.png)
在複製互動元件後，可以連接『啟用元件』或是『選擇元件』
step2.在編輯區選擇連接『啟用元件』
![image](https://user-images.githubusercontent.com/41721950/58077172-896ba480-7bde-11e9-9ff7-88b3d79165de.png)
step3.已確認『互動後台管理』有建立(獎項都是40)
![image](https://user-images.githubusercontent.com/41721950/58077084-604b1400-7bde-11e9-8573-f2a0c3f66642.png)
但在瀏覽器執行時，『啟用元件』的全部變成『獎項已抽完』，且出現#1294 的相同問題
![image](https://user-images.githubusercontent.com/41721950/58077567-67265680-7bdf-11e9-8945-edd2dbb14ff2.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
『啟用元件』的獎項數量雖亂跳，但後台有新增此元件紀錄，也可執行
![image](https://user-images.githubusercontent.com/41721950/58222482-c489e700-7d48-11e9-8aaf-01449a69ee80.png)
◎◎ 20190523確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
互動元件使用匯入序號時，已可正常執行，獎項數量也正確呈現。
![1300](https://user-images.githubusercontent.com/49626114/60421879-4eb54d00-9c1d-11e9-9d47-811d292e1e40.png)
◎◎ 20190701確認以上正式環境內容 ◎◎
