### ISSUE TITLE
【測試環境】編輯區設定的中獎紀錄與實際執行有差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1301]
設立獎項新增『匯入序號』功能，有三種序號樣式可選擇
![image](https://user-images.githubusercontent.com/41721950/58220439-76bdb080-7d41-11e9-9758-cf77d0bc23d7.png)
在『狀態(提示)頁-中獎紀錄-填表前』寫道，僅顯示『獎項圖片、獎項名稱』
![image](https://user-images.githubusercontent.com/41721950/58220066-ee8adb80-7d3f-11e9-9fd0-bf38f4c4fc0d.png)
但實際在瀏覽器顯示的畫面如下，依序是Barcode、QR code、文字序號
問題一：全部都增加顯示『兌換時間』與『序號說明』，是原本就設計要顯示的嗎??
問題二：QR code與文字序號都有出現錯誤訊息，QR code等再久都不會出現，而文字序號等五秒到十秒才會出現內容。
![image](https://user-images.githubusercontent.com/41721950/58220377-352d0580-7d41-11e9-86ff-34d9f05b5a28.png)
以上問題出現在所有的互動元件當中，請協助確認後修改。感恩~
可用範例 https://cm.ryzoweba.com/weba/aae/

**Comment by AnitaRyzo** [comment]
修改後實際在瀏覽器顯示的畫面如下，依序是Barcode、QR code、文字序號
答一：未顯示『兌換時間』與『序號說明』
答二：Barcode直接顯示，QR code與文字序號錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/58394431-c53aba00-8075-11e9-8007-9919b55d74fc.png)
◎◎ 20190527確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
狀態(提示)頁-恭喜中獎-填表前
![image](https://user-images.githubusercontent.com/41721950/59479534-f990e180-8e8f-11e9-8863-7c02a13794a4.png)
狀態(提示)頁-恭喜中獎-填表後
![image](https://user-images.githubusercontent.com/41721950/59479592-2f35ca80-8e90-11e9-91f9-4eaeef31cdce.png)
狀態(提示)頁-中獎紀錄-序號選項
![image](https://user-images.githubusercontent.com/41721950/59479677-72903900-8e90-11e9-8407-0349a55d3eb4.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1301](https://user-images.githubusercontent.com/49626114/60421372-4872a100-9c1c-11e9-97b5-d7b50954c653.png)
◎◎ 20190701確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
狀態(提示)頁與實際執行的畫面相同
◎◎ 20190702確認以上正式環境內容 ◎◎
