### ISSUE TITLE
[問題]互動元件陰影未正常顯示

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1302]
1.序號設定陰影在編輯頁、預覽頁和發佈頁皆會被編輯框線卡掉。
![#](https://user-images.githubusercontent.com/49626114/58221253-74a92100-7d44-11e9-8154-71fbefab15c9.png)

2.在io環境設定陰影，搖獎機和轉蛋機在編輯頁會正常顯示，但發佈後陰影會被編輯框卡掉。
![互動元件陰影](https://user-images.githubusercontent.com/49626114/58221678-09604e80-7d46-11e9-865f-b76cfbef7cfa.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58308298-c9779500-7e33-11e9-99a7-61c1745f2d94.png)
![image](https://user-images.githubusercontent.com/41721950/58308212-874e5380-7e33-11e9-9eb8-c01c943c7c69.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
互動元件陰影已正常呈現
![1302](https://user-images.githubusercontent.com/49626114/60418834-81a81280-9c16-11e9-8b00-479cc9ef8419.png)
◎◎ 20190701確認以上測試環境內容 ◎◎
