### ISSUE TITLE
【測試環境】互動元件匯入序號的數量與後台的總數量不符合

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1303]
從『測試結果』可知，『匯入序號』的數量為5
![image](https://user-images.githubusercontent.com/41721950/58222117-97890480-7d47-11e9-918b-ea2b5688834b.png)
但後台卻顯示數量為10
![image](https://user-images.githubusercontent.com/41721950/58222028-4da01e80-7d47-11e9-9c84-848d9335d430.png)
當複製後連接『啟動互動元件』；雖然『匯入序號』要重新帶入，但一開始顯示的數量會亂跳。
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
看了一下數量應該是從number直接取的吧
@Gabe-Liu  再看一下

**Comment by AnitaRyzo** [comment]
補充：
step1.互動元件A是直接設定數量，發佈後在瀏覽器執行幾次抽獎，再回來編輯區『匯入序號』
step2.複製『互動元件A』再『啟動互動元件』此時數量就會如下為非10的數值了
![image](https://user-images.githubusercontent.com/41721950/58300600-d08faa80-7e15-11e9-9753-ff5d5483f230.png)
請再協助處理，感恩~

**Comment by AnitaRyzo** [comment]
複製『互動元件A』再『啟動互動元件』，獎項數量為10的數值
◎◎ 20190703確認以上測試環境內容 ◎◎
