### ISSUE TITLE
[問題]互動元件的動畫和框線設定未正常顯示

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1304]
1.編輯區動畫設定的位置應該在登入後(黃框處)。
![動畫](https://user-images.githubusercontent.com/49626114/58223571-cc4b8a80-7d4c-11e9-97e2-ae3e972c9286.png)

2.互動元件的框線設定應該顯示在按鈕上，但目前在編輯頁、預覽頁和發佈頁的框線都是呈現在互動元件的編輯框線。
![框線](https://user-images.githubusercontent.com/49626114/58223734-79260780-7d4d-11e9-8287-9737ca58cfad.png)

  已經跟@ryzojudy 確認過動畫是在登入後才執行，框線是設定給按鈕的。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58308808-232c8f00-7e35-11e9-8da2-c45bc2b6c166.png)

![image](https://user-images.githubusercontent.com/41721950/58309193-19eff200-7e36-11e9-9bdd-798e0d60fd88.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
互動元件的動畫和框線已可正常顯示
![1304](https://user-images.githubusercontent.com/49626114/60143596-65a90900-97f1-11e9-8ece-3ef5554e4453.PNG)
◎◎ 20190626確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
互動元件的動畫和框線已可正常顯示
◎◎ 20190701確認以上正式環境內容 ◎◎
