### ISSUE TITLE
【測試環境】互動元件用Query String身分驗證+自動傳送表單，會連「銘謝惠顧」都回傳至表單後台

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1305]
step1. 設定Query String為身分驗證
![image](https://user-images.githubusercontent.com/41721950/58230779-e181e280-7d67-11e9-888f-4720451deb23.png)
step2.表單選擇『自動傳送表單』
![image](https://user-images.githubusercontent.com/41721950/58230866-2148ca00-7d68-11e9-84d8-39a6d55e1da7.png)
在瀏覽器執行互動後，發現連「銘謝惠顧」都寫至表單後台了
![image](https://user-images.githubusercontent.com/41721950/58230602-60c2e680-7d67-11e9-98b5-18aa77c2f184.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
關閉『兌獎』已不會回傳資料至表單後台
![image](https://user-images.githubusercontent.com/41721950/58306136-1146ee00-7e2d-11e9-8822-2cc9c8eacb7b.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
"銘謝惠顧"已不會回傳至表單後台。
![1305](https://user-images.githubusercontent.com/49626114/60084701-985bee80-976a-11e9-8ced-fc732f2c2c35.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
