### ISSUE TITLE
【測試環境】互動元件用Query String+自動傳送表單，轉蛋機回傳空白值到表單

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1306]
step1. 設定Query String為身分驗證
![image](https://user-images.githubusercontent.com/41721950/58230779-e181e280-7d67-11e9-888f-4720451deb23.png)
step2.表單選擇『自動傳送表單』
![image](https://user-images.githubusercontent.com/41721950/58230866-2148ca00-7d68-11e9-84d8-39a6d55e1da7.png)
在瀏覽器執行轉蛋機，發現回傳至表單後台是空白的
![image](https://user-images.githubusercontent.com/41721950/58231669-1db64280-7d6a-11e9-841b-f87b8fcf333d.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
已正確顯示
![image](https://user-images.githubusercontent.com/41721950/58306213-68e55980-7e2d-11e9-8785-de97ffac9e1d.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
轉蛋機有回傳正確值到表單
![1306](https://user-images.githubusercontent.com/49626114/60084096-7c0b8200-9769-11e9-95b2-f052572cd193.png)
◎◎ 20190625確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
互動元件用Query String+自動傳送表單，皆有正確回傳值。
![image](https://user-images.githubusercontent.com/41721950/60405774-e480b600-9be4-11e9-8474-f9198865ff5b.png)
◎◎ 20190701確認以上正式環境內容 ◎◎
