### ISSUE TITLE
【測試環境】互動元件設自動傳送表單，中獎紀錄仍要求要填寫資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1307]
表單選擇『自動傳送表單』
![image](https://user-images.githubusercontent.com/41721950/58230866-2148ca00-7d68-11e9-84d8-39a6d55e1da7.png)
在瀏覽器執行互動元件後，左邊恭喜中獎的提示頁是正確的，但右邊中獎記錄的提示頁又可以回要求再填寫一次表單
![image](https://user-images.githubusercontent.com/41721950/58232209-8f42c080-7d6b-11e9-8f9f-29a9561c5e89.png)
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
記錄：uat問題

**Comment by AnitaRyzo** [comment]
目前狀況：
自動填表的回傳還沒存到後台，若馬上開啟紀錄仍會出現『填寫資料』，等個幾秒再開啟就沒問題。
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
開啟中獎紀錄後，不會出現"填寫資料"。
![1307](https://user-images.githubusercontent.com/49626114/60083255-f6d39d80-9767-11e9-806e-523449a190f7.png)
◎◎ 20190625確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
執行互動元件後，立即開啟中獎紀錄已無出現"填寫資料"。
