### ISSUE TITLE
【測試環境】表單自動寄送的內容有很多空值

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1309]
一般表單的『固定答案-串接資料』題型的內容不會顯示
![image](https://user-images.githubusercontent.com/41721950/58241459-9ecc0480-7d7f-11e9-9616-2e8a8360f5ec.png)
序號表單與抽獎表單有很多欄位都是空白的
![image](https://user-images.githubusercontent.com/41721950/58241927-7395e500-7d80-11e9-9042-6cb2b52a3434.png)
以上問題請協助處理，感恩

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58300291-8bb74400-7e14-11e9-9bce-50a08e183c13.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
抽獎表單的『串接資料』有出現，但一般表單的『串接資料』卻沒出現唷
![image](https://user-images.githubusercontent.com/41721950/58301234-38df8b80-7e18-11e9-8fbc-de9e74d42d08.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『串接資料』是網址須要出現的key，寫入後台的會是『=』後面的值
![image](https://user-images.githubusercontent.com/41721950/58302157-29624180-7e1c-11e9-9d4d-d721e40a8af4.png)
◎◎ 20190524確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
一般表單
![1309一般表單](https://user-images.githubusercontent.com/49626114/60500171-70c9d080-9cec-11e9-9d1e-99030505991d.png)
抽獎表單
![1309抽獎表單](https://user-images.githubusercontent.com/49626114/60500182-76bfb180-9cec-11e9-8883-7cdf9e8fe0b4.png)
序號表單
![1309序號表單](https://user-images.githubusercontent.com/49626114/60500205-7e7f5600-9cec-11e9-8196-e0c7fc55e9ee.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
