### ISSUE TITLE
[測試環境]裝飾圖案沒有跟著編輯框縮放

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1310]
縮放編輯框時，裝飾圖案只會跟著編輯框上下左右移動但不會跟著縮放。
![裝飾圖案](https://user-images.githubusercontent.com/49626114/58297297-d54e6180-7e09-11e9-8f6f-284c3556644c.PNG)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58394512-34b0a980-8076-11e9-80cd-7f92e564cda9.png)
◎◎ 20190527確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
裝飾圖案已會跟著編輯框縮放
![1310](https://user-images.githubusercontent.com/49626114/60495513-84bd0480-9ce3-11e9-9d7a-9d7dee41ffee.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
