### ISSUE TITLE
【測試環境】設定獎項的匯入序號，Barcode未出現

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1312]
『匯入序號』的excel資料內容如下
![image](https://user-images.githubusercontent.com/41721950/58312005-f3818500-7e3c-11e9-8db2-5762c10eb00f.png)
選擇的序號樣式為『Barcode』
![image](https://user-images.githubusercontent.com/41721950/58311941-c7fe9a80-7e3c-11e9-9457-8f735c0ff435.png)
『恭喜中獎』與『中獎紀錄』頁面未顯示『Barcode』
![image](https://user-images.githubusercontent.com/41721950/58313197-91764f00-7e3f-11e9-8bc1-7a76eebec495.png)

而『QRcode』與『文字序號』有正確顯示
![image](https://user-images.githubusercontent.com/41721950/58313053-42c8b500-7e3f-11e9-80d0-0d92bfc2e99f.png)
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
獎項序號將會禁止中文以及不常用的特殊符號上傳
可以使用的符號 **~!@#$%^&*()_+-=`{}[]:;"'<>?/.,**

**Comment by AnitaRyzo** [comment]
若A欄含有中文、純空格、或不常用的特殊符號，皆會出現以下提示訊息
![image](https://user-images.githubusercontent.com/41721950/58390000-7be06f80-8061-11e9-8a9c-97e107cf0848.png)
◎◎ 20190527確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
若序號A欄含有中文、純空格、或不常用的特殊符號，則會出現提示訊息。
![1312-1](https://user-images.githubusercontent.com/49626114/60492974-97810a80-9cde-11e9-9f7b-7416251e3f80.PNG)
若序號符合規則，序號樣式Barcode會正常出現。
![1312-2](https://user-images.githubusercontent.com/49626114/60493073-bda6aa80-9cde-11e9-94ae-e4fa3a0c7f8c.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
