### ISSUE TITLE
【問題】手勢評分顯示錯誤

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1313]
使用手勢評分 
如果填答後又切換上下頁
文字內容會錯誤

專案中，正確的是最左邊是非常不滿意  ，最右邊是非常滿意
<img width="374" alt="螢幕快照 2019-05-24 下午6 08 12" src="https://user-images.githubusercontent.com/34327325/58320810-216fc500-7e4f-11e9-8cff-0d3c8e1999e5.png">

<img width="332" alt="螢幕快照 2019-05-24 下午6 08 02" src="https://user-images.githubusercontent.com/34327325/58320841-2d5b8700-7e4f-11e9-975d-4bb3d8365569.png">

**Comment by AnitaRyzo** [comment]
填答後又切換上下頁，文字內容是正確的
◎◎ 20190527確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
切換頁面後再回到手勢評分頁面內容呈現正確
![1313](https://user-images.githubusercontent.com/49626114/60491583-b0d48780-9cdb-11e9-99c4-32bea1c44251.png)
◎◎ 2019702確認以上正式環境內容 ◎◎
