### ISSUE TITLE
【測試環境】互動元件的匯入序號，當A欄無值的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1314]
#1312為前提，若A欄含有中文、純空格、或不常用的特殊符號，皆會出現提示訊息且無法上傳檔案
但若A欄是完全未輸入的，匯入的資料會如紅框顯示
![image](https://user-images.githubusercontent.com/41721950/58392302-ea2a2f80-806b-11e9-801d-908a19d18ebe.png)
請協助確認是否在A欄無值時，直接不上傳不顯示資料內容? 感恩~

**Comment by AnitaRyzo** [comment]
當A欄無值，直接當作不存在
![image](https://user-images.githubusercontent.com/41721950/58847707-8086d280-86b6-11e9-97d5-92e7c9d05f3d.png)
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
若欄位無值時，則當作不存在。
![1314](https://user-images.githubusercontent.com/49626114/60082632-ba537200-9766-11e9-90c4-bc2559d16a80.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
