### ISSUE TITLE
【測試環境】資料綁定後，頁面管理的增加頁面未出現在選單架構

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1315]
step1.設立『頁面』，先設立三頁
![image](https://user-images.githubusercontent.com/41721950/58402447-ed84e180-8092-11e9-89d1-a6a7ec0eb29f.png)
step2.『資料綁定』的名單檔案匯入，並按『儲存變更』
![image](https://user-images.githubusercontent.com/41721950/58402550-3177e680-8093-11e9-9a1a-9a2bbbaf0586.png)
step3.『+頁面』有增加，但有錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/58402234-63d51400-8092-11e9-9cf3-f7277c38edfa.png)
問題：頁面管理的頁面有增加，但『選單架構』未出現頁面
![image](https://user-images.githubusercontent.com/41721950/58402793-b7942d00-8093-11e9-88cc-5d6bef574b9b.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
資料綁定後，頁面管理的增加頁面會出現在選單架構
![image](https://user-images.githubusercontent.com/41721950/59477979-3bb72480-8e8a-11e9-85c1-681bec39ceb4.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
資料綁定後，頁面管理的增加頁面會出現在選單架構
![1315](https://user-images.githubusercontent.com/49626114/60076262-b0774200-9759-11e9-9cd5-53f7ed6a65c8.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
