### ISSUE TITLE
[問題]PDF版面配置樣式排版有誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1316]
1. 在"選擇圖文配置"裡樣式13的排版是上方兩段文字+下方兩張圖，但實際呈現方式(如右圖)是上方兩張圖+下方一段文字和一張圖。
![樣式13](https://user-images.githubusercontent.com/49626114/58444948-fde99a80-812c-11e9-9439-a385cca30fff.png)

2.在"選擇圖文配置"裡樣式14的排版是上方兩張圖+下方兩段文字，但實際呈現方式(如右圖)是上方兩段文字+下方兩張圖。
![pdf版面配置](https://user-images.githubusercontent.com/49626114/58445004-5456d900-812d-11e9-8d27-1c1312ef886c.PNG)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58674892-78602780-8384-11e9-8225-295511c8ca10.png)
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1316](https://user-images.githubusercontent.com/49626114/60491078-7d452d80-9cda-11e9-9141-a38279f0b320.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
