### ISSUE TITLE
[測試環境] 管理者後台沒團隊時錯誤

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1317]
![image](https://user-images.githubusercontent.com/10150807/58446523-98e57300-8133-11e9-9541-a786f9804d54.png)

有團隊時正常
沒團隊時設定畫面顯示不出來

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59243335-07e9be00-8c42-11e9-9267-e80ad54339fb.png)
◎◎ 20190611確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1317](https://user-images.githubusercontent.com/49626114/60490689-a2856c00-9cd9-11e9-844e-e11877c0873e.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
