### ISSUE TITLE
【測試環境】Banner套版的原專案被刪除，圖片素材遺失

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1319]
『套版總覽』的原專案被刪除，圖片素材的位置會一直LOADING
![image](https://user-images.githubusercontent.com/41721950/58449586-7a38a980-813e-11e9-8180-329b08c03fd3.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/58450129-3181f000-8140-11e9-8dd0-35fa49d51814.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
我試了一次流程
沒有這樣的問題
可以幫我從頭試一次看看嗎
感恩

**Comment by AnitaRyzo** [comment]
step1.加入圖片元件
![image](https://user-images.githubusercontent.com/41721950/58454810-32bc1880-8152-11e9-9bbc-3c4788b37cae.png)
step2.申請套版，第一次『套版審核未通過』；再次送審後『套版審核通過』
![image](https://user-images.githubusercontent.com/41721950/58454928-8e86a180-8152-11e9-9d87-b79e5ce698fd.png)
就會出現以上敘述的問題囉! 請知悉~

**Comment by AnitaRyzo** [comment]
目前圖片素材未遺失
![image](https://user-images.githubusercontent.com/41721950/58680854-4955b000-839c-11e9-9f80-3daa359c0b9b.png)
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『Banner廣告管理』刪除專案，再從『套版總覽』點選『點擊進入查看』或『使用此套版』，圖片皆存在
![image](https://user-images.githubusercontent.com/41721950/60064421-f1a82b80-9732-11e9-81a2-55979f642ab9.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
