### ISSUE TITLE
[問題]核取方塊&上傳圖片進度條會自動計算成完成題數

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1321]
表單及電子申請書放核取方塊和上傳圖片題型，在未選填答案的情況下，進度條會自動計算成完成題數。
![題數問題](https://user-images.githubusercontent.com/49626114/58450726-ab1add80-8142-11e9-9b88-1dcf1fc077e9.PNG)

備註 : 下拉式題型在未選填答案的情況下會預設為第一個選項，因此也會自動計算成完成題數。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58849635-a663a580-86bd-11e9-93e5-c675d91c8649.png)
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
完成題數已正常呈現
![1321](https://user-images.githubusercontent.com/49626114/60490249-c2686000-9cd8-11e9-8c1b-179da1c7a034.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
