### ISSUE TITLE
[測試環境]從其他頁面返回日期題型頁面時會自動帶入日期

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1322]
在測試環境中，表單及電子申請書的日期題型在未選填答案的情況下，從其他頁面返回到日期題型的頁面時會自動帶入系統當下的日期時間，而進度條會將此題歸於完成題數。

在正式環境中日期題型並未有此狀況發生，請協助確認日期題型是否需要自動帶入系統當下的日期時間?
![日期自動帶入](https://user-images.githubusercontent.com/49626114/58454698-d3f69f00-8151-11e9-8f57-8f9aacce9cc8.png)

**Comment by AnitaRyzo** [comment]
已從『下一頁』返回，目前已不會自動帶入日期時間
![image](https://user-images.githubusercontent.com/41721950/58850524-6dc5cb00-86c1-11e9-8992-36ea954abd40.png)
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
從下一頁返回後不會自動帶入日期時間
![1322](https://user-images.githubusercontent.com/49626114/60488709-43bdf380-9cd5-11e9-82e5-12bd90162649.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
