### ISSUE TITLE
[問題]手勢選答題型在進度條的完成題數計算有誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1324]
1.手勢選答未選填答案的情況下直接跳下一頁時，進度條的完成題數會+1。
![手勢選答未選填](https://user-images.githubusercontent.com/49626114/58455928-749a8e00-8155-11e9-9334-530474e9b2a1.png)

2.在正式環境中，手勢選答選填答案後，進度條完成題數會+2。
在測試環境中，手勢選答選填答案後，會先跳空白頁面(黃框處)進度條的完成題數會+1，隔幾秒後才跳至下一頁且進度條的完成題數變+2。
![手勢選答選填後](https://user-images.githubusercontent.com/49626114/58456372-99dbcc00-8156-11e9-86a3-1daf4a869046.png)

**Comment by ai015606220** [comment]
#1321

**Comment by AnitaRyzo** [comment]
已切換到下一頁再回頭，完成題數未自己加總
![image](https://user-images.githubusercontent.com/41721950/58850046-58e83800-86bf-11e9-911a-f613984ad5da.png)
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
手勢選答未填寫(如黃框)，手勢選答有填寫(如綠框)，題數計算皆為正確值。
![1324](https://user-images.githubusercontent.com/49626114/60485017-20dc1100-9cce-11e9-9fab-985e317724a5.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
