### ISSUE TITLE
後台左上角logo

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1325]
希望滑鼠的cursor可以設定一下顯示手出來
因為他可以點擊
感恩

**Comment by AnitaRyzo** [comment]
左上角Logo已會出現👆鼠標
![image](https://user-images.githubusercontent.com/41721950/58674733-b7da4400-8383-11e9-9bf0-3f046dfc1882.png)
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
滑鼠游標移到左上角的logo上時已會出現手指圖示。
![1325](https://user-images.githubusercontent.com/49626114/60482229-37309f80-9cc3-11e9-9b69-0869d32c278e.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
