### ISSUE TITLE
[測試環境] 電子申請書資料確認

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1326]
![image](https://user-images.githubusercontent.com/10150807/58457658-ccd38f00-8159-11e9-9844-9b0bb58ff2bf.png)

資料確認頁缺少確認資料的顯示
https://cm.ryzoweba.com/weba/roy-form3

**Comment by AnitaRyzo** [comment]
即使完全未填資料且資料確認頁無題目，皆會顯示題目
![image](https://user-images.githubusercontent.com/41721950/58850180-e6c42300-86bf-11e9-8da3-bf8bf18493b9.png)
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
資料確認頁會完整呈現題目頁面管理內的題目
![1326](https://user-images.githubusercontent.com/49626114/60482057-9fcb4c80-9cc2-11e9-96ed-f0c507f9132e.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
