### ISSUE TITLE
【測試環境】MGM的社群列表中，社群名稱顯示錯誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1329]
MGM的社群列表中社群名稱顯示錯誤，如紅框所示
![image](https://user-images.githubusercontent.com/41721950/58463401-58531d00-8166-11e9-8f06-db34522a98c2.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58850689-40c5e800-86c2-11e9-8f5b-ce69020a47ce.png)
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1329](https://user-images.githubusercontent.com/49626114/60481595-95a84e80-9cc0-11e9-99cf-dc09f457d65d.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
