### ISSUE TITLE
【測試環境】跨帳號開關專案的功能，專案通過審核前無法預覽

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1330]
跨帳號專案的發佈/關閉功能，專案通過審核前，預覽圖無法顯示
![image](https://user-images.githubusercontent.com/41721950/58522997-4cfb0280-81f5-11e9-88db-788b69c4b973.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/58523088-b11dc680-81f5-11e9-8188-4eccfbf4caf7.png)
以上問題請協助處理，感恩~

備註：若『點擊進入查看』會出現預覽圖
![image](https://user-images.githubusercontent.com/41721950/58523167-078b0500-81f6-11e9-8aad-f2b4d12a7485.png)

**Comment by AnitaRyzo** [comment]
僅『發佈後』的專案有「開關專案」的按鈕
![image](https://user-images.githubusercontent.com/41721950/58851107-f80f2e80-86c3-11e9-8a0d-96a60adcd194.png)
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
只有發佈後的專案會有"發佈專案"和"關閉專案"的按鈕，不管有沒有發佈專案都能夠預覽。
![1332](https://user-images.githubusercontent.com/49626114/60481459-fdaa6500-9cbf-11e9-8931-c6983a389e16.png)
