### ISSUE TITLE
【測試環境】跨帳號開關專案的功能，未發佈的專案不能點選『關閉專案』的按鈕

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1331]
跨帳號專案的發佈/關閉功能，未發佈的專案若顯示『關閉專案』按鈕
![image](https://user-images.githubusercontent.com/41721950/58522997-4cfb0280-81f5-11e9-88db-788b69c4b973.png)
會如以下編輯畫面，『更新專案』按鈕一直讀取，但等很久都沒有到下一步
![image](https://user-images.githubusercontent.com/41721950/58523299-86803d80-81f6-11e9-81ba-d06f0c6bd2d0.png)
查看後台可知是因為此專案『審核未通過』
![image](https://user-images.githubusercontent.com/41721950/58527853-f991b000-8206-11e9-99e6-7e75bde513b4.png)
建議未發佈的專案一開始就不能點選『關閉專案』按鈕
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58685393-259b6580-83ae-11e9-9c0e-c6c80062f3d6.png)
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58685413-3b108f80-83ae-11e9-8d9a-f1e1ce33bd98.png)
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
只有已發佈的專案才會有"關閉專案"的按鈕
![1332](https://user-images.githubusercontent.com/49626114/60481173-e6b74300-9cbe-11e9-9798-53a9187b309a.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
