### ISSUE TITLE
【測試環境】跨帳號開關專案的功能，未發佈的專案不能顯示『發佈專案』按鈕

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1332]
跨帳號專案的發佈/關閉功能，未發佈的專案不能顯示『發佈專案』按鈕
![image](https://user-images.githubusercontent.com/41721950/58523621-b845d400-81f7-11e9-9934-f361ec7f6cc4.png)
否則會如以下編輯畫面，『發佈專案』按鈕會一直讀取，但等很久都沒有到下一步；專案也無法開啟
![image](https://user-images.githubusercontent.com/41721950/58523732-24283c80-81f8-11e9-9e18-96f21d128d8c.png)
因為structure_prod(送審完成)是空值
![image](https://user-images.githubusercontent.com/41721950/58527513-820f5100-8205-11e9-84aa-07b81ebf671c.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58685426-495eab80-83ae-11e9-8c8f-08d271672c15.png)
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
只有已發佈的專案才會有"發佈專案"按鈕
![1332](https://user-images.githubusercontent.com/49626114/60480823-a1464600-9cbd-11e9-95af-a5810269fd92.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
