### ISSUE TITLE
[測試環境]裝飾圖案未跟著頁面比例縮放

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1336]
step 1. 當頁面比例為100%時，在頁面中放入裝飾圖案。
step 2. 把頁面比例放大到150%時，編輯框跟著比例變大但是裝飾圖案沒有變動。
反之，把頁面比例縮小時，編輯框會縮小但是裝飾圖案沒有縮小。
![裝飾圖案縮放](https://user-images.githubusercontent.com/49626114/58618379-1a383380-82f5-11e9-978a-044c72d48db7.png)

**Comment by AnitaRyzo** [comment]
裝飾圖案與其他元件皆跟著頁面比例縮放
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
所有元件都會跟著頁面比例縮放
◎◎ 20190702確認以上正式環境內容 ◎◎
