### ISSUE TITLE
【問題】電腦版的裝飾圖案，未依循「隱藏畫布外內容』的指示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1337]
『背景效果設定』已設定『隱藏』畫布外內容
![image](https://user-images.githubusercontent.com/41721950/58623321-502ee500-8300-11e9-92a8-3c5e0bf1df81.png)
在「30分鐘預覽」與發佈後的裝飾圖案，未依循「隱藏畫布外內容』的指示
![image](https://user-images.githubusercontent.com/41721950/58623620-f7ac1780-8300-11e9-99c4-a37e3e95cb9d.png)
請協助處理此問題，感恩~

**Comment by Gabe-Liu** [comment]
看起來.com的環境是好的 請 @AnitaRyzo  幫我試試

**Comment by AnitaRyzo** [comment]
當『元件固定』後，裝飾圖會就會飛出去了。請知悉~
![image](https://user-images.githubusercontent.com/41721950/59480221-5ee5d200-8e92-11e9-8819-0f4ab3955409.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59489185-0fb09900-8eb4-11e9-930e-c1d0063dd251.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
將元件固定後，已不會出現在畫布外。
![image](https://user-images.githubusercontent.com/49626114/60479113-3a259300-9cb7-11e9-9d9b-329aef05cc30.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
