### ISSUE TITLE
【專案審核】專案審核失敗沒出現紅點

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#134]
![image](https://user-images.githubusercontent.com/34263719/39984109-a87fc8b4-578c-11e8-82ca-dcf79676867d.png)

**Comment by ai015606220** [comment]
@ryzojudy 麻煩再試一下現在還有沒有問題

**Comment by ryzojudy** [comment]
這個沒問題了

**Comment by Isabella-RYZO** [comment]
未上線的專案審核失敗會有紅點點無誤
