### ISSUE TITLE
【建議】管理者後台的「權限管理」項目移動位置

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#1342]
根據weilyn的回饋
在管理者後台的權限設定表中
原本的「帳號相關」文字容易讓人產生誤解
因此想把原本在帳號相關中的「權限管理」移動至「團隊相關」中
(如下圖表示)
已跟sam確認過沒問題
再麻煩協助了~~~
感謝!!
![image](https://user-images.githubusercontent.com/34263719/58866359-0755a280-86eb-11e9-9ca2-0eddeb9fbb36.png)

**Comment by ryzojudy** [comment]
因為 權限管理 其實也是跟團隊有相關(一樣需要在團隊中才可以設定其他人的權限)
所以就移動至 團隊相關 這個分類中了

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59316708-62daee00-8cf2-11e9-8942-568960b1ebfb.png)
◎◎ 20190612確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1342](https://user-images.githubusercontent.com/49626114/60477603-40fdd700-9cb2-11e9-85d2-4672818ad460.PNG)
◎◎ 20190702確認以上正式環境內容 ◎◎
