### ISSUE TITLE
【測試環境】用未設定郵件的line登入，帳號名稱的氣泡窗

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1343]
line未設定電子郵件，直接用QR code掃描註冊weba帳號
![image](https://user-images.githubusercontent.com/41721950/58926454-ee4a0180-877d-11e9-9dd0-1b4587ee28f1.png)
帳號名稱的氣泡窗顯示如下
![image](https://user-images.githubusercontent.com/41721950/58926621-6a444980-877e-11e9-9e1d-01848d398e86.png)
請協助處理此問題，感恩~

**Comment by ryuichl** [comment]
同1344 先關掉
因為沒信箱 所以氣泡窗空的
