### ISSUE TITLE
[專案發佈]第一次審核失敗第二次成功專案

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#135]
第一次審核失敗的專案
在第二次成功後
不會出現在「待發布」的分頁中
而是出現在「發佈中」
不知道是不是因爲已經有網址存在的原因？
（失敗後 在專案管理的地方會出現設定的URL 點進去無效）

**Comment by ai015606220** [comment]
這個專案是正在發佈中還是從未發佈過??

**Comment by ryzojudy** [comment]
未發佈過的

**Comment by ai015606220** [comment]
OK 那我有調整過了，下次下線就會解決這個問題

**Comment by Isabella-RYZO** [comment]
👌
