### ISSUE TITLE
[測試環境]電子申請書的資料確認頁不需要顯示固定答案題型

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1350]
1. 已跟@ryzojudy 確認過在電子申請書的資料確認頁面不需要顯示固定答案題型。
![固定答案資料確認頁](https://user-images.githubusercontent.com/49626114/58943593-a1345280-87b2-11e9-8c96-b3a994ac310d.PNG)

2.電子申請書下載後的pdf檔也會顯示固定答案題型，再麻煩 @ryzojudy 確認是否需要顯示，感謝~
![固定答案pdf檔](https://user-images.githubusercontent.com/49626114/58944264-06d50e80-87b4-11e9-914e-a573b7b096aa.PNG)

**Comment by ryzojudy** [comment]
理論上也不會出現在PDF頁面中
後續討論結果是電子申請書元件不會有固定題型
再麻煩了~
感謝!!

**Comment by AnitaRyzo** [comment]
電子申請書的資料確認頁已移除固定答案題型
![image](https://user-images.githubusercontent.com/41721950/59317640-653f4700-8cf6-11e9-86f1-def6a8b2992c.png)
◎◎ 20190612確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
電子申請書的題目已移除固定答案題型
![1350](https://user-images.githubusercontent.com/49626114/60477345-85d53e00-9cb1-11e9-8b26-50bcd648b761.PNG)
◎◎ 20190701確認以上正式環境內容 ◎◎
