### ISSUE TITLE
【測試環境】資料綁定產生的專屬連結，在名單列表與匯出資料顯示不一致

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1351]
『資料綁定-名單檔案-名單列表』的專屬連結(紅框)
『資料綁定-名單檔案-匯出資料』的專屬連結(黃底)
兩個顯示的網址不一致，而黃底可以正確開啟網頁，紅框在瀏覽器顯示有誤
![image](https://user-images.githubusercontent.com/41721950/58946289-1f472800-87b8-11e9-9065-b5547317e6ea.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
網址顯示一致且可以正確開啟網頁
![image](https://user-images.githubusercontent.com/41721950/59421378-10d4be00-8e01-11e9-94f3-ffd9066581e1.png)
◎◎ 20190613確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1351](https://user-images.githubusercontent.com/49626114/60075736-91c47b80-9758-11e9-9bba-c66b7f4ed49a.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
