### ISSUE TITLE
[測試環境]先設定活動名稱後原本獎項設定的匯入序號會消失

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1353]
step 1.建立互動元件並設定好獎項內容使用匯入序號。
![設定獎項](https://user-images.githubusercontent.com/49626114/59006695-e3fb3680-8855-11e9-8574-a1976c4071db.PNG)

step 2.未先執行表單設計動作而是先設定活動名稱(紅框處)。
![活動名稱](https://user-images.githubusercontent.com/49626114/59006779-4a805480-8856-11e9-93af-0a0777c46dee.PNG)

step 3.再回到設定獎項查看，獎項內容的匯入序號消失。
![設定獎項(空)](https://user-images.githubusercontent.com/49626114/59006834-7e5b7a00-8856-11e9-85b8-bc9658ccc486.PNG)

**Comment by AnitaRyzo** [comment]
匯入序號後，先設定『活動名稱』並儲存，獎項設定的匯入序號仍會留存。
◎◎ 20190613確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
先設定活動名稱後儲存，獎項設定的匯入序號仍然存在。
◎◎ 20190625確認以上正式環境內容 ◎◎
