### ISSUE TITLE
【測試環境】資料綁定利用名單列表刪明細的錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1354]
『名單檔案-名單列表-選取名單-刪除名單』
![image](https://user-images.githubusercontent.com/41721950/59010054-8faa8380-8862-11e9-843f-d7901d7cb854.png)
顯示『No Rows To Show』
![image](https://user-images.githubusercontent.com/41721950/59010068-9b964580-8862-11e9-849f-a3b2351aba4a.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/59010120-c97b8a00-8862-11e9-8abb-d6dcd77f1362.png)

但定義欄位的欄位資料依然顯示前三筆，資料綁定編輯與預覽仍有資料
![image](https://user-images.githubusercontent.com/41721950/59010093-b36dc980-8862-11e9-856a-04f0e7e336e7.png)
切換左邊功能列表後，才會出現與『刪除檔案』相同的畫面，錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/59010224-1e1f0500-8863-11e9-90c2-b24ed9f8a4e8.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
資料綁定利用名單列表刪名單資料，會跳回『刪除檔案』的畫面
![image](https://user-images.githubusercontent.com/41721950/59239029-d0274a00-8c32-11e9-8665-ec615e6ba537.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
![1354](https://user-images.githubusercontent.com/49626114/60075484-00550980-9758-11e9-9022-c87f0967a770.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
