### ISSUE TITLE
[測試環境]幸運餅乾的匯入序號按鈕變形且部分被遮蓋

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1355]
幸運餅乾的獎項設定在匯入序號之後按鈕會變形且被"數量"的字樣遮蓋到一小部分。
PS: 與螢幕大小有關
![餅乾獎項設定](https://user-images.githubusercontent.com/49626114/59012119-49a4ee00-8869-11e9-8a71-07399065e069.PNG)

**Comment by AnitaRyzo** [comment]
小畫面時，『匯入序號』按鈕也不會變形
![image](https://user-images.githubusercontent.com/41721950/59022930-49b0e800-8881-11e9-8533-f8e32213a79a.png)
◎◎ 20190606確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
"匯入序號"按鈕已呈現正常，不會變形也不會遮蓋到其他內容。
![1355](https://user-images.githubusercontent.com/49626114/60476998-4528f500-9cb0-11e9-9261-eed86a2d9dd3.png)
◎◎ 20190701確認以上正式環境內容 ◎◎
