### ISSUE TITLE
【測試環境】資料綁定的名單檔案上傳直接跳至『分類管理』

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1357]
資料綁定的名單檔案上傳後，會出現『檔案預覽』
按下『使用檔案』後，會直接跳『分類管理』頁
未給使用者定義『欄位名稱』
![image](https://user-images.githubusercontent.com/41721950/59024099-b62ce680-8883-11e9-9d6a-80681d083646.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
資料綁定的名單檔案上傳後，會給使用者定義『欄位名稱』
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
資料綁定的名單檔案上傳後，會給使用者定義『欄位名稱』
◎◎ 20190625確認以上正式環境內容 ◎◎
