### ISSUE TITLE
【測試環境】資料綁定的名單檔案若未編輯，URL會是黑畫面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1358]
資料綁定的名單檔案會預先設定第一個欄位為『數據後台顯示的資料』
![image](https://user-images.githubusercontent.com/41721950/59024230-0d32bb80-8884-11e9-83e0-e4f2a6c366e8.png)
若編輯者未在此頁做任何編輯，『匯出資料』的URL會是黑畫面
錯誤訊息如右所示
![image](https://user-images.githubusercontent.com/41721950/59024299-3ce1c380-8884-11e9-99a5-b94b285cbf66.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
依然黑畫面，請協助處理，感恩~
![image](https://user-images.githubusercontent.com/41721950/59421025-7d02f200-8e00-11e9-9319-fc6fea44e5f6.png)

**Comment by AnitaRyzo** [comment]
抱歉!! 是我在『內容待更新上線』就查看資料綁定URL，才會有此錯誤!!
![image](https://user-images.githubusercontent.com/41721950/59421922-0e269880-8e02-11e9-8ceb-c65896a2ca0a.png)
已確認可以不編輯名單，也可以正常使用URL
◎◎ 20190613確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
已確認可以不編輯資料綁定的名單，也可以正常使用URL
◎◎ 20190625確認以上正式環境內容 ◎◎
