### ISSUE TITLE
[問題]gif的圖片需要擋住剪裁功能

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1359]
在輪播圖、選單架構、資料綁定的圖片庫、banner的圖片庫上傳gif檔都有剪裁的功能，但是根據issue #1144應該是要擋住gif檔的剪裁功能，再麻煩協助處理，謝謝~
![banner剪裁](https://user-images.githubusercontent.com/49626114/59170490-70b53580-8b71-11e9-85ff-d7bdee8fe0b2.PNG)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59476411-1bd03280-8e83-11e9-978c-1cfba92f8242.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1359](https://user-images.githubusercontent.com/49626114/60073353-c33a4880-9752-11e9-9b94-d7b0757c63ba.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
