### ISSUE TITLE
[測試環境]幸運轉盤上傳獎項圖片後不會正常呈現在互動元件上

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1360]
正常情況上傳獎項圖片後，獎項圖片應該呈現在左側幸運轉盤上(上圖綠色圓圈處)。
![正常獎項圖片上傳](https://user-images.githubusercontent.com/49626114/59178557-e4ffd100-8b91-11e9-9795-5286fb7263ca.PNG)
![成功確定後呈現樣子](https://user-images.githubusercontent.com/49626114/59179055-6dcb3c80-8b93-11e9-9009-42dc81101812.PNG)

在測試環境中上傳獎項圖片後，獎項圖片未正常呈現(下圖紅色圓圈處)。
![失敗獎項圖片上傳](https://user-images.githubusercontent.com/49626114/59179011-470d0600-8b93-11e9-8a3b-0437d8e1bd51.PNG)
![失敗確定後呈現樣子](https://user-images.githubusercontent.com/49626114/59179068-7754a480-8b93-11e9-81c5-61e7a186cbae.PNG)

**Comment by AnitaRyzo** [comment]
幸運轉盤上傳的獎項圖片，會正確呈現
◎◎ 20190613確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
幸運轉盤上傳的獎項圖片，會正確呈現
![1360](https://user-images.githubusercontent.com/49626114/60081591-ad358380-9764-11e9-86cc-126c66557070.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
