### ISSUE TITLE
【測試環境】資料綁定的分類管理按鈕文字

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1361]
資料綁定的分類管理，教學頁的描述與按鈕文字不一致
請將『稍後設定』(紅框處)改為『跳過』
![image](https://user-images.githubusercontent.com/41721950/59238549-272c1f80-8c31-11e9-9e65-3baaa6bd88df.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
抱歉!! 正確是兩處都顯示『稍後設定』才對!!
請協助修改，感恩!!

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59487429-40420400-8eaf-11e9-96a4-1d549926fa90.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1361](https://user-images.githubusercontent.com/49626114/60072198-4a85bd00-974f-11e9-8ef0-164a1a8d6a3c.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
