### ISSUE TITLE
【測試環境】資料綁定的圖片庫分類後裁切，分類會暫時失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1362]
資料綁定的圖片庫可將圖片分類
情境：以下兩張圖片已分類至『公主與萌寵』，分類後再將圖片進行裁切(黃框)
![image](https://user-images.githubusercontent.com/41721950/59238692-91dd5b00-8c31-11e9-85ad-5b3095c73ce7.png)
圖片裁切完成後，被裁切的圖片就會從分類中消失
![image](https://user-images.githubusercontent.com/41721950/59238772-d49f3300-8c31-11e9-873d-20cc27408ffc.png)
必須切換其他功能列(藍框)再切回圖片庫後，被裁切的圖片才會再次出現(黃框)
![image](https://user-images.githubusercontent.com/41721950/59238834-0fa16680-8c32-11e9-9ce4-db4e90fe077d.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
圖片分類剪裁後，會一直存在於分類中
![image](https://user-images.githubusercontent.com/41721950/59422831-935e7d00-8e03-11e9-9237-aee68c518c0f.png)
◎◎ 20190613確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1362](https://user-images.githubusercontent.com/49626114/60072541-62aa0c00-9750-11e9-8926-55419db64b19.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
