### ISSUE TITLE
【測試環境】電子表單的檔案寄出頁在編輯區與瀏覽器顯示不同

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1363]
電子表單的檔案寄出頁，可設定是否要出現『上方文字』or『下方文字』
編輯區將兩個勾選都取消時，顯示完全無內容(紅框)
但在瀏覽器執行時，會出現下載檔案的圖示(綠框)
![image](https://user-images.githubusercontent.com/41721950/59243620-77ac7880-8c43-11e9-9135-5e021d7ea812.png)
請協助讓畫面內容一致，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59587892-eb092b00-9118-11e9-9e88-414d9efe6857.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
電子申請書編輯頁
![1363編輯頁](https://user-images.githubusercontent.com/49626114/60476551-9fc15180-9cae-11e9-9290-2eef6c4cb0ce.PNG)
電子申請書發佈頁
![1363發佈頁](https://user-images.githubusercontent.com/49626114/60476568-a9e35000-9cae-11e9-85dd-e9e2c6cc55ec.PNG)
編輯區跟發布後瀏覽器的呈現已相同
◎◎ 20190701確認以上正式環境內容 ◎◎
