### ISSUE TITLE
【測試環境】套版的互動元件專屬設定變成undefined

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1364]
從『套版總覽』選擇喜歡的套版，並按下『選擇此套版』
若套版內有『互動元件』，可選擇的狀況如下：啟用元件 or 選擇元件
![image](https://user-images.githubusercontent.com/41721950/59253754-79853480-8c61-11e9-9117-5bad341dfcec.png)
按下『啟用元件』後，發現專屬設定變成undefined(如下紅框)
![image](https://user-images.githubusercontent.com/41721950/59253545-0e3b6280-8c61-11e9-9409-700f18cab324.png)
『設定獎項』的數量也是undefined(如下紅框)
![image](https://user-images.githubusercontent.com/41721950/59262086-26b37900-8c71-11e9-87d9-857adc46824d.png)
補充：獎項數量不論怎麼設定，都只會出現『獎項已領取完』
![image](https://user-images.githubusercontent.com/41721950/59322325-3631d100-8d08-11e9-9e46-35dded4c1b76.png)

若按下『選擇元件』，則會帶入正常的數字資料
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59576271-c2ba0600-90f1-11e9-9bfa-9df5db930434.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1364](https://user-images.githubusercontent.com/49626114/60081079-b70ab700-9763-11e9-888f-f568a9a79eb7.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
