### ISSUE TITLE
【問題】十周年感恩慶套版

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1366]
由於很早期的圖片檔名允許特殊字元, 於是在上傳圖片後, 圖片檔名仍然存在該字元.

這導致這個套版的圖片檔名, 在匯入其他環境時 ( 過程中檔案會經過壓縮與解壓縮 ), 檔名中該字元會出現被重新編碼的狀況, 最終檔名對應不到的問題.

![messageImage_1560305107869](https://user-images.githubusercontent.com/11918396/59320281-61182700-8d00-11e9-81a4-0791f2134172.jpg)

![image](https://user-images.githubusercontent.com/11918396/59320806-3b8c1d00-8d02-11e9-8570-de38b489e281.png)

![未命名2](https://user-images.githubusercontent.com/11918396/59320825-4b0b6600-8d02-11e9-99e6-1955e285dd32.png)

不確定套版這塊由誰來維護, 請協助更新一下這個套版.

**Comment by ryuichl** [comment]
@Kyle30  你跟weilyn 協調一下
看是要直接下架這個套板還是怎樣

**Comment by weilyn** [comment]
已經更新圖片

**Comment by Kyle30** [comment]
P.S.
這個套版後來還是有些問題, 已從 io 上刪除.
