### ISSUE TITLE
[測試環境] banner連動素材更換

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1368]
![image](https://user-images.githubusercontent.com/10150807/59335280-d7cc1900-8d2e-11e9-9a06-2848753441ec.png)

設計中有連動素材統一更換的設計
目前在測試環境好像沒有看到這部分的實作

**Comment by ai015606220** [comment]
請問這個功能有對應的API可以使用嗎?
還是只能依靠相同的檔名? 但這樣使用者就會受到限制，必須上傳相同檔案格式的圖

**Comment by weilyn** [comment]
想請問文字的顏色是否有連動的可能，
或是圖片跟文字可以事後調整（尺寸、顏色）以後，快速套用到全部尺寸的版面

**Comment by ai015606220** [comment]
無法

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59489038-c06a6880-8eb3-11e9-84a7-643a617046e4.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60076661-b7528480-975a-11e9-97a5-e63e38b57a18.png)
![image](https://user-images.githubusercontent.com/41721950/60076640-a7d33b80-975a-11e9-8547-2e7d33d253b3.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
