### ISSUE TITLE
【專案發佈】專案發佈成功卻沒內容

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#137]
專案成功發佈
點進去卻沒內容
![image](https://user-images.githubusercontent.com/34263719/39991471-3acd564a-57a2-11e8-883a-4593762842f4.png)

**Comment by ryzojudy** [comment]
https://judytest0514.ryzoweba.io

**Comment by Gabe-Liu** [comment]
暫時好了，可能更新後OK了

**Comment by Isabella-RYZO** [comment]
👌
