### ISSUE TITLE
【測試環境】互動的抽獎中獎紀錄無QR code可掃描至兌獎頁

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1370]
設定『數量』的獎項，填表後會利用QR code進入兌換獎項頁面
![image](https://user-images.githubusercontent.com/41721950/59401076-21b70c80-8dcc-11e9-83ac-7d57d5cb25ff.png)
狀態(提示)頁之中獎紀錄有開啟兌換頁的『QR code』
![image](https://user-images.githubusercontent.com/41721950/59401037-f92f1280-8dcb-11e9-8cd9-576026e1f1d5.png)
但是在瀏覽器上執行時，點選『抽獎紀錄圖示』的獎項列表，無QR code可以掃描至兌獎頁
![image](https://user-images.githubusercontent.com/41721950/59401219-92f6bf80-8dcc-11e9-8164-40dc628b43b1.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59572773-eaa16d80-90e1-11e9-8291-530bd5bd53ca.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1370](https://user-images.githubusercontent.com/49626114/60080514-a6a60c80-9762-11e9-93cf-0fdd72233a7f.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
