### ISSUE TITLE
[測試環境]自動傳送表單影響中獎紀錄設定

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1371]
互動元件的獎項設定使用匯入序號，並在表單資訊設定勾選"自動傳送表單"。
![勾選表單自動傳送](https://user-images.githubusercontent.com/49626114/59402848-c89ea700-8dd2-11e9-9c18-83724d16ed9a.png)

中獎紀錄的畫面呈現錯誤，且右邊序號獎項的設定也是錯誤的。(紅框處)
![錯誤中獎紀錄](https://user-images.githubusercontent.com/49626114/59402967-46fb4900-8dd3-11e9-8afa-f587f8c3219e.png)

但是實際發布後中獎紀錄的呈現樣子卻是正確的。(綠框處)
![實際執行畫面](https://user-images.githubusercontent.com/49626114/59403062-b83afc00-8dd3-11e9-934c-641ab22c6ede.png)

若取消勾選"自動傳送表單"，在中獎紀錄中的畫面跟設定則會呈現正確的樣子。(綠框處)
![正確中獎紀錄](https://user-images.githubusercontent.com/49626114/59403015-7ca03200-8dd3-11e9-8c09-dffce12ca74c.png)

**Comment by AnitaRyzo** [comment]
互動元件的獎項設定使用匯入序號，並在表單資訊設定勾選"自動傳送表單"
狀態(提示)頁的畫面已正確
![image](https://user-images.githubusercontent.com/41721950/59499751-9bcdbb00-8eca-11e9-8809-a0c4936e9f81.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1371](https://user-images.githubusercontent.com/49626114/60080237-123baa00-9762-11e9-854f-e29b0c57888b.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
