### ISSUE TITLE
【測試環境】幸運轉盤的設定獎項中，設定比例掉圖

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1372]
幸運轉盤設立後，在『設立獎項』可以修改獎項內容
![image](https://user-images.githubusercontent.com/41721950/59418651-fb10ca00-8dfb-11e9-8e6d-d2332b1b3880.png)
『設立獎項』的『設定比例』未帶入圖片
![image](https://user-images.githubusercontent.com/41721950/59418598-dd436500-8dfb-11e9-9550-95c8064eb1a9.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
圖片已帶入
![image](https://user-images.githubusercontent.com/41721950/59494987-ef3b0b80-8ec0-11e9-8e51-4acd2de1bc8a.png)
◎◎ 20190614確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
幸運轉盤的設定比例圖片已帶入
![1372](https://user-images.githubusercontent.com/49626114/60476270-8f5ca700-9cad-11e9-8073-3fdc03a5b960.PNG)
◎◎ 20190701確認以上正式環境內容 ◎◎
