### ISSUE TITLE
【問題】資料綁定在框架物件上失效

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1373]
如圖，藍色字是資料綁定的文字
其中上方的溯源號碼是使用框架方式，呈現在每個分頁之中
在資料綁定後，只有第一頁有成功被替換到，其他頁都維持未綁定的數值
<img width="527" alt="螢幕快照 2019-06-14 上午8 19 11" src="https://user-images.githubusercontent.com/34327325/59475300-651d8380-8e7d-11e9-80a1-7442772bc594.png">

專案網址：https://weba0001.ryzoweba.io/?did=7ExBxvVd86

**Comment by weilyn** [comment]
此專案(及另一個) 為客戶6/19號 食品展活動上所需，
再麻煩工程部同仁協助在活動開始以前完成修復並上線，謝謝。

**Comment by AnitaRyzo** [comment]
https://cm.ryzoweba.com/ddc/?did=26K9SUyMF8
首要條件：從資料綁定的URL開啟網頁後，先到資料綁定的幻燈片，才會顯示正確的資料綁定
![image](https://user-images.githubusercontent.com/41721950/59586468-9adc9980-9115-11e9-898d-8cd0d469e7ca.png)
資料綁定在框架物件上已生效
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
資料綁定在框架物件上已生效
![1373](https://user-images.githubusercontent.com/49626114/60078324-5036cf00-975e-11e9-9bfd-2ea6eff85859.png)
◎◎ 20190625確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
正式環境下，框架物件+資料綁定依然失效
![image](https://user-images.githubusercontent.com/41721950/60086847-6cdb0300-976e-11e9-9706-ca1cf3c3ae15.png)
◎◎ 20190625確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『資料綁定編輯』設定在2-1頁
![image](https://user-images.githubusercontent.com/41721950/60497278-19753180-9ce7-11e9-8499-4c9265d9da60.png)
無須到設定『資料綁定編輯』的頁面，就會直接跳出專屬的內容
![image](https://user-images.githubusercontent.com/41721950/60497485-85579a00-9ce7-11e9-82c2-1193e52e2478.png)
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『資料綁定編輯』設定在3-2頁
![image](https://user-images.githubusercontent.com/41721950/60781288-5ff9de80-a174-11e9-9d33-f025bc531fff.png)
無須到設定『資料綁定編輯』的頁面，就會直接跳出專屬的內容
![image](https://user-images.githubusercontent.com/41721950/60781263-3d67c580-a174-11e9-95fd-afeaec069428.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
