### ISSUE TITLE
【測試環境】序號表單設定影響序號發放

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1374]
當『序號表單』在一開始就設定『填表人數限制』與『回覆寄至指定信箱』
![image](https://user-images.githubusercontent.com/41721950/59477040-0a3c5a00-8e86-11e9-94b3-caf3f6c4d8dd.png)
表單回覆時的提示訊息是『表單回覆發生錯誤』，錯誤訊息如右
![image](https://user-images.githubusercontent.com/41721950/59477138-728b3b80-8e86-11e9-8e16-2a1033f1f573.png)
從『表單管理』與『互動後台管理』可知序號未被提供給使用者
![image](https://user-images.githubusercontent.com/41721950/59477195-b120f600-8e86-11e9-9183-2b09c8a17748.png)
![image](https://user-images.githubusercontent.com/41721950/59477232-dc0b4a00-8e86-11e9-9a1f-ddbbbb0eacb7.png)
PS: 正式環境仍可正確發送序號
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
已可正確帶入序號
![image](https://user-images.githubusercontent.com/41721950/59576738-54764300-90f3-11e9-8fd2-33f22166e033.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![1374](https://user-images.githubusercontent.com/49626114/60079880-61350f80-9761-11e9-8c52-4cc3d0025ced.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
