### ISSUE TITLE
[問題]刪除跳題題目後，表單無法繼續編輯

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1375]
設定Q1的A選項跳題至Q2。
![設定跳題](https://user-images.githubusercontent.com/49626114/59479284-095bf600-8e8f-11e9-9c07-958da5a1fc26.PNG)

不小心將Q2刪除後，左邊的題目頁面管理還會顯示Q2題目。
![刪除題目後](https://user-images.githubusercontent.com/49626114/59479357-4b853780-8e8f-11e9-9ce4-3c11fd005230.png)

無法繼續選擇或編輯其他題目，開啟檢查會出現右邊的錯誤碼。
![錯誤碼](https://user-images.githubusercontent.com/49626114/59479442-9c952b80-8e8f-11e9-8543-042236e28980.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59594798-24e12e00-9127-11e9-9a5b-012be0b52e07.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
刪除跳題題目後，左邊頁面管理正常呈現，且依舊可以繼續編輯表單。
![1375-1](https://user-images.githubusercontent.com/49626114/60485769-a8c31a80-9cd0-11e9-8a96-1b27176cc9b7.png)
![1375-2](https://user-images.githubusercontent.com/49626114/60485770-a95bb100-9cd0-11e9-93f6-36693d7b9a40.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
