### ISSUE TITLE
[測試環境]相同檔名的banner畫布下載後只會有其中一個檔

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1376]
設定兩個不同尺寸但是相同檔名的banner畫布(紅框處)。
![BANNER相同檔名](https://user-images.githubusercontent.com/49626114/59497794-b2721300-8ec6-11e9-8ea4-6e6dc52cf00d.png)

輸出檔案勾"全選"。
![全選下載](https://user-images.githubusercontent.com/49626114/59497871-db92a380-8ec6-11e9-8f9c-aee475f15691.png)

輸出後只有出現A跟C畫布，沒有B畫布。
![BANNER下載後](https://user-images.githubusercontent.com/49626114/59497889-e5b4a200-8ec6-11e9-9048-933cce51bccc.png)

如果使用相同尺寸畫布且未修改預設檔名(預設檔名皆為畫布尺寸)
![BANNER相同尺寸](https://user-images.githubusercontent.com/49626114/59498299-ba7e8280-8ec7-11e9-9aa7-e9c3596a6c2a.png)

輸出後只有出現A跟B畫布，沒有C畫布。
![BANNER相同檔名下載後](https://user-images.githubusercontent.com/49626114/59498375-e568d680-8ec7-11e9-80db-2a2a6b1557d4.PNG)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59577528-af5d6980-90f6-11e9-93d9-20f3d8b24d3c.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60077488-9f7c0000-975c-11e9-981e-ca8e87b9c912.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
