### ISSUE TITLE
[測試環境]banner輸出檔案後文字跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1377]
在banner放入裝飾圖案、文字、圖片、圖示，在編輯區這四種元件都是在畫布區內。
![BANNER文字](https://user-images.githubusercontent.com/49626114/59495898-e9dec080-8ec2-11e9-9dbf-fbfccd74e0e3.PNG)

輸出檔案後，文字元件跑版。(紅框處)
![BANNER文字跑版](https://user-images.githubusercontent.com/49626114/59496022-2c080200-8ec3-11e9-8cf5-fd86a8800581.png)

**Comment by AnitaRyzo** [comment]
跑版變小了
![image](https://user-images.githubusercontent.com/41721950/59577931-5989c100-90f8-11e9-8379-747284406b21.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by Gabe-Liu** [comment]
看起來是有些google font的字體會走掉，請 @AnitaRyzo 幫忙測看那些字體會跑版

**Comment by AnitaRyzo** [comment]
黃色是略為跑版，紅色是較大的跑版
![image](https://user-images.githubusercontent.com/41721950/59584377-6d412180-9110-11e9-908f-7883fce3a0b1.png)
![image](https://user-images.githubusercontent.com/41721950/59584122-cf4d5700-910f-11e9-9afd-6a5a2c8551be.png)
已上資料請參考，感恩~

**Comment by AnitaRyzo** [comment]
Banner可用字型如下列表
![image](https://user-images.githubusercontent.com/41721950/59595970-6a065f80-9129-11e9-92ca-24589fc6fc99.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
Allen字型在『粗體斜體』的狀況下跑版嚴重
![image](https://user-images.githubusercontent.com/41721950/60079671-f97ec480-9760-11e9-91f0-1d7f6cc788c3.png)
![image](https://user-images.githubusercontent.com/41721950/60079719-12877580-9761-11e9-8de0-6876e518a6b4.png)
![image](https://user-images.githubusercontent.com/41721950/60079791-3b0f6f80-9761-11e9-87bf-3231b3feddef.png)
![image](https://user-images.githubusercontent.com/41721950/60079845-4a8eb880-9761-11e9-981a-358236d1ef79.png)
◎◎ 20190625確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
字型剩下29種
![image](https://user-images.githubusercontent.com/41721950/60485510-d5c2fd80-9ccf-11e9-8a5c-d2ba03ece574.png)
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
文字保留29種跑版較小的字型，粗斜體與顏色陰影皆可正常操作
![image](https://user-images.githubusercontent.com/41721950/60787780-7eb89f00-a18d-11e9-8705-d8586688abec.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
