### ISSUE TITLE
【測試環境】套版內的互動元件，獎項圖片遺失

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1378]
帶入有互動元件的舊有套版
![image](https://user-images.githubusercontent.com/41721950/59578340-542d7600-90fa-11e9-9848-4b3e321f722d.png)
『啟用互動元件』後
![image](https://user-images.githubusercontent.com/41721950/59578373-77f0bc00-90fa-11e9-8e7b-6c0b74369cb0.png)
發現『設定獎項』未將獎項圖片帶入
![image](https://user-images.githubusercontent.com/41721950/59578400-a1a9e300-90fa-11e9-9305-bb281233e37e.png)
而在專案列表的預覽圖與專案下載後都可以看到獎項圖片
![image](https://user-images.githubusercontent.com/41721950/59578556-5512d780-90fb-11e9-98b2-2f28ef39940b.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
套板內的互動元件獎項圖片已正常呈現。
![1378](https://user-images.githubusercontent.com/49626114/60417697-a058da00-9c13-11e9-8dd9-d10c92eee75b.png)
◎◎ 20190701確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『套版總覽』按下查看套版時，獎項未出現
![image](https://user-images.githubusercontent.com/41721950/60475539-6555b580-9caa-11e9-9000-3b2ea0021159.png)
@Gabe-Liu 請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
『套版總覽』與啟用互動元件的『設定獎項』，皆有出現獎項圖片
![image](https://user-images.githubusercontent.com/41721950/60580708-2150d680-9db8-11e9-8f94-fb1fee123971.png)
◎◎ 20190703確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『套版總覽』與啟用互動元件的『設定獎項』，皆有出現獎項圖片
![image](https://user-images.githubusercontent.com/41721950/60789467-c04b4900-a191-11e9-8d85-ba3b7c010338.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
