### ISSUE TITLE
【問題】資料綁定中，點選儲存或發佈的回饋

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1383]
1.如果我的專案網址不符合規則，並且忽略他直接在綁定的畫面中編輯，點選儲存，儲存按鈕可以點擊，但是不會跳出成功或失敗的提示。

2.如果專案的網址從未設定過網址，並且都有正常儲存，在資料綁定裡進行儲存可以成功儲存，但是接著點選申請審核，不會跳出送審成功或失敗的提示，讓使用者以為他已經送去審核了，其實因為沒有設定網址，所以根本就沒有成功送審。

<img width="781" alt="螢幕快照 2019-06-19 上午9 18 10" src="https://user-images.githubusercontent.com/34327325/59729979-2f104300-9273-11e9-8ad2-52bd55553d39.png">

**Comment by leonlin6** [comment]
已與Sam和Judy討論後並調整v3-editor存檔時publish_name的防呆與提醒視窗機制
現今防呆與提醒規則為：
1. 若publish_name為輸入格式錯誤，點選存檔時，跳出紅色外框popup訊息，並跳回發布設定頁面
2. 若publish_name為空時，視為格式錯誤，點選存檔時，跳出紅色外框popup訊息，並跳回發布設定頁面
3. 已存檔成功，若更改publish_name為錯誤輸入格式，點選申請審核時，跳出「氣泡確認視窗」，並鎖定確認按鈕，不能送出申請，並跳回發布設定頁面

此issue與 「#927【測試環境】在資料綁定中點選申請審核，不會跳轉。」 一同修改完內容。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60777544-8c5a2e80-a165-11e9-85f8-6d1fc9248127.png)
以上補充，感恩~

**Comment by leonlin6** [comment]
已修正為Anita所提供之操作流程
若publish_name尚未輸入過，點選存檔時，跳出進行儲存中popup訊息，並正常儲存。

此issue與 「#927【測試環境】在資料綁定中點選申請審核，不會跳轉。」 一同修改完內容。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60853046-073a4c80-a22d-11e9-8f44-9fd2e98920b7.png)
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
無域名的『申請審核』確認鈕尚未隱藏
![image](https://user-images.githubusercontent.com/41721950/60933858-b7c05300-a2f6-11e9-9b6b-9b1a039b7483.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60934268-2651e080-a2f8-11e9-8e11-ced0364a9d4e.png)
◎◎ 20190710確認以上正式環境內容 ◎◎
