### ISSUE TITLE
【問題】在編輯區無法看到全部的提示

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#1387]
專案中使用的建立的提示超過原本的編輯區的可視範圍後，沒有辦法看到其他的提示
<img width="599" alt="螢幕快照 2019-06-21 上午9 54 13" src="https://user-images.githubusercontent.com/36216073/59892211-bcd26680-940a-11e9-9712-c85cefa1d8dc.png">

<img width="397" alt="螢幕快照 2019-06-21 上午9 54 53" src="https://user-images.githubusercontent.com/36216073/59892225-c9ef5580-940a-11e9-97b8-82d08be2206f.png">
上圖為專案中全部的提示

再麻煩協助處理，謝謝～

**Comment by AnitaRyzo** [comment]
提示頁多了滾軸
![image](https://user-images.githubusercontent.com/41721950/60493570-a87e4b80-9cdf-11e9-934c-0708ebf98898.png)
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
提示頁多了滾軸
![image](https://user-images.githubusercontent.com/41721950/60789803-8cbcee80-a192-11e9-9ac8-0ecd10f35830.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
