### ISSUE TITLE
【問題】MGM的社群分享內容在手機版分享時不顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1388]
分享換優惠的『狀態提示頁』可以設定『社群分享內容』
![image](https://user-images.githubusercontent.com/41721950/59897539-ae427a00-941f-11e9-9619-f1e3916d20f9.png)
使用『電腦版』按下社群類別的按鈕，就會帶入『社群分享內容』，若按『複製連結』則無
![image](https://user-images.githubusercontent.com/41721950/59897485-73d8dd00-941f-11e9-9281-5b4232898f31.png)
『手機版』不論按『社群類別』或『複製連結』，都不會顯示『社群分享內容』
![image](https://user-images.githubusercontent.com/41721950/59900189-e2bb3380-9429-11e9-86fe-ab64b59a6e87.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
line在電腦版和手機版時行為我試過不太一致
可能要偵測手機和電腦展示不同分享連結
例如
電腦版
https://social-plugins.line.me/lineit/share?url=https%3A%2F%2Fryzo.io&text=哈哈
手機版
https://social-plugins.line.me/lineit/share?url=https%3A%2F%2Fryzo.io%0D%0A哈哈

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60499204-98b83480-9cea-11e9-90ee-6f5e721aad00.png)
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60790994-4d43d180-a195-11e9-990b-d428d29c4666.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
