### ISSUE TITLE
【問題】套版MGM重新啟用元件，部分獎項設定遺失

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1389]
於從MGM的套版，或是複製專案後，重新啟用該MGM元件，
發送者的獎項設定全數被保留，
唯獨接收者優惠會被取消(即便原專案是開啟並設定妥當的情況)。

<img width="956" alt="螢幕快照 2019-06-21 下午3 45 22" src="https://user-images.githubusercontent.com/34327325/59906562-9c6ed000-943b-11e9-84e7-16b221c157f3.png">

套版網址 https://template-weba080.ryzoweba.io

**Comment by AnitaRyzo** [comment]
獎項設定都有留存
![image](https://user-images.githubusercontent.com/41721950/60559295-969fb580-9d7e-11e9-9f2a-022dcc7e927d.png)
◎◎ 20190703確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60791727-d576a680-a196-11e9-8435-8d24bc4afccb.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
