### ISSUE TITLE
【問題】BANNER產生器在MAC環境下，替換圖片沒反應

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1391]
從套版新增BANNER廣告以後，

替換圖片無反應
<img width="1280" alt="螢幕快照 2019-06-24 上午9 54 17" src="https://user-images.githubusercontent.com/34327325/59985793-21d5c880-9666-11e9-8ffe-028fe89bb3e1.png">

**Comment by AnitaRyzo** [comment]
此使用者未執行api，但我們其他使用者有執行此請求
![image](https://user-images.githubusercontent.com/41721950/59988474-be4f9900-966d-11e9-81c0-eb38ea41d5aa.png)
請工程大大協助處理，感恩~

**Comment by AnitaRyzo** [comment]
已確認兩台MAC可以替換圖片
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已確認MAC可以替換圖片
◎◎ 20190710確認以上正式環境內容 ◎◎
