### ISSUE TITLE
[問題]資料綁定編輯頁圖片呈現與發佈後不同

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1392]
設定圖片元件圓角100% (圖片元件並無上傳任何圖片)
![資料綁定圖片設定](https://user-images.githubusercontent.com/49626114/60062808-48126b80-972d-11e9-994d-41cfb40da710.png)

在圖片庫上傳正方形圖片
![圖片原檔](https://user-images.githubusercontent.com/49626114/60062984-ddadfb00-972d-11e9-9138-21bc815ed556.png)

在資料綁定頁呈現圖片會是圓形(如紅框處)
![資料綁定呈現](https://user-images.githubusercontent.com/49626114/60062865-798b3700-972d-11e9-8b26-31832d7d856a.png)

發佈後圖片呈現卻是方形圓角，跟編輯頁的呈現結果不同
![資料綁定發布後](https://user-images.githubusercontent.com/49626114/60063039-059d5e80-972e-11e9-88b3-5dd0fdd54082.png)

**Comment by AnitaRyzo** [comment]
資料綁定頁與瀏覽器發佈後的圖片是相同的
![image](https://user-images.githubusercontent.com/41721950/60500920-b935be00-9ced-11e9-8d4b-e8a119c19d48.png)
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
長方形圖片與正方形圖片對照圖如下，系統已依照指示提供圓角
![image](https://user-images.githubusercontent.com/41721950/60782121-e7951c80-a177-11e9-9ae1-913b35a27949.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
