### ISSUE TITLE
【問題】Banner圖片庫的圖片剪裁，編輯區的圖片未同步

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1393]
step1. 從素材庫帶入圖片
![image](https://user-images.githubusercontent.com/41721950/60068364-fa076300-9740-11e9-8267-eab1361e1684.png)
step2. 從『管理素材』進行『圖片剪裁』
![image](https://user-images.githubusercontent.com/41721950/60068448-54a0bf00-9741-11e9-8f61-5afbb7a042ce.png)
step3. 『管理素材』可知圖片已剪裁，但編輯區的圖片未有任何變化
![image](https://user-images.githubusercontent.com/41721950/60068317-c1678980-9740-11e9-8e84-d6960bb6302d.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
請問編輯區的圖片是不是有調整過圖片顯示位置?

**Comment by AnitaRyzo** [comment]
沒有調整『圖片顯示位置』唷

**Comment by ai015606220** [comment]
我的狀況是
如果有調整過圖片顯示位置，圖片不會更新
但除此況外的圖片素材裁切後的更新是正常的

**Comment by AnitaRyzo** [comment]
但我未調整過『圖片顯示位置』也不會更新圖片耶
![image](https://user-images.githubusercontent.com/41721950/60160353-c6ebcf00-9827-11e9-9039-9930a1b854c4.png)

**Comment by ai015606220** [comment]
你有什麼額外的操作嗎?
因為我這邊測不出來更新失敗的例子

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60325344-ab183280-99b9-11e9-855f-1a62971dd9b5.png)
◎◎ 20190628確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
補充：此問題當開啟『檢查』的時候不存在
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
圖片庫的圖片剪裁，編輯區的圖片已同步
◎◎ 20190708確認以上正式環境內容 ◎◎
