### ISSUE TITLE
【問題】互動表單的『送出後執行動作』遺失

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1395]
原先設計：互動的表單「送出成功」後會停留在原表單頁面
但現在更新為互動的表單「送出成功」後，會直接跳出獎項的『中獎頁面』...
問題：『送出後執行動作』設定之後也無法出現
![image](https://user-images.githubusercontent.com/41721950/60323170-e7e12b00-99b3-11e9-9107-efe2e64cf3b6.png)
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
目前如果是手動填表，有開啟『送出後執行動作』的話，則不會自動回到中獎頁面。
但開啟自動填表，則會忽略『送出後執行動作』。

**Comment by AnitaRyzo** [comment]
手動填表：開啟『送出後執行動作』會依照指示執行
![image](https://user-images.githubusercontent.com/41721950/60580345-86f09300-9db7-11e9-930a-33ca237a3ceb.png)
自動填表：忽略『送出後執行動作』
![image](https://user-images.githubusercontent.com/41721950/60580389-9c65bd00-9db7-11e9-8b6f-c24226c6f8b5.png)
◎◎ 20190703確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
手動填表：開啟『送出後執行動作』會依照指示執行
自動填表：忽略『送出後執行動作』
◎◎ 20190708確認以上正式環境內容 ◎◎
