### ISSUE TITLE
[測試環境]資料綁定的多分類內容"內容輪播"發布後頁面跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1397]
在資料綁定中的多分類內容若選擇"內容輪播"，發布後的頁面會跑版，全部元件會跑到左上角(紅框處)。
![資料綁定跑版](https://user-images.githubusercontent.com/49626114/60406984-39bfc600-9beb-11e9-8e9d-1cc6b25d35ce.png)

**Comment by AnitaRyzo** [comment]
"內容輪播"-發布後的頁面已不會跑版
◎◎ 20190702確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
"內容輪播"發布後的頁面已正確顯示
![image](https://user-images.githubusercontent.com/41721950/60782727-68551800-a17a-11e9-91a5-39d49b5b4e60.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
