### ISSUE TITLE
[測試環境]EDM網頁擷取的選擇專案畫面跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1409]
EDM圖片元件網頁擷取功能的選擇專案畫面跑版。內容跑出灰底部分(下圖紅框處)
![EDM網頁擷取](https://user-images.githubusercontent.com/49626114/60645495-6550e380-9e6b-11e9-83c1-f27b0b629114.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60709527-39089600-9f43-11e9-8372-cde9ad194238.png)
◎◎ 20190705確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60796044-53d74680-a19f-11e9-8269-aa314f72b012.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
