### ISSUE TITLE
最上面切換團隊還有登出那條資訊

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#141]
那條現在都點不到
滑鼠移過去沒反應
只有在表單管理才可以點

![image](https://user-images.githubusercontent.com/10150807/40030078-0fa70636-581b-11e8-8474-73c472a515f6.png)

**Comment by ai015606220** [comment]
#139

**Comment by ai015606220** [comment]
這是z-index的問題，已修改，下次上線就能解決

**Comment by Isabella-RYZO** [comment]
👌
