### ISSUE TITLE
【問題】互動元件未連接就儲存離開，再次進入連接元件就出現undefined

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1415]
step1.建立互動元件
step2.專案儲存離開後再進入專案
step3.建立新互動元件
![image](https://user-images.githubusercontent.com/41721950/60696460-7c014400-9f18-11e9-95a9-7bbf86c30eb8.png)
問題：密碼出現undefined
![image](https://user-images.githubusercontent.com/41721950/60701291-deb10a80-9f2d-11e9-8f6f-140156d5a1e1.png)
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
暫時玩不出選擇互動的BUG

**Comment by AnitaRyzo** [comment]
依照以上步驟，密碼未出現undefined
◎◎ 20190705確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
依照以上步驟，密碼未出現undefined
◎◎ 20190708確認以上正式環境內容 ◎◎
