### ISSUE TITLE
專案儲存問題

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1418]
開了新專案
目前沒打域名就無法儲存
會報錯
如果沒打理論上應該要略過

**Comment by AnitaRyzo** [comment]
無域名可儲存專案
![image](https://user-images.githubusercontent.com/41721950/60852827-f50bde80-a22b-11e9-8015-6a52c1b6876e.png)
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
無域名的『申請審核』確認鈕尚未隱藏
![image](https://user-images.githubusercontent.com/41721950/60933858-b7c05300-a2f6-11e9-9b6b-9b1a039b7483.png)
◎◎ 20190710確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/61102081-f7c23a00-a49e-11e9-923b-85f1003fa089.png)
◎◎ 20190712確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
無域名可儲存專案
![image](https://user-images.githubusercontent.com/41721950/63659743-b2a35e80-c7e5-11e9-9899-d8dca5847baa.png)
無域名的『申請審核』不會出現確認窗或是隱藏確認鈕
![image](https://user-images.githubusercontent.com/41721950/63659801-0e6de780-c7e6-11e9-86c2-d42a5ead7266.png)
◎◎ 20190823確認以上正式環境內容 ◎◎
