### ISSUE TITLE
[問題]EDM積木新增元件時icon跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1419]
問題1. 套用積木後將元件使用『移動』新增至積木的網格後左邊的元件icon跑版(紅框處)
![edm元件icon跑版](https://user-images.githubusercontent.com/49626114/60778748-b3ffc580-a16a-11e9-8982-d50ebcc2f073.png)
問題2. 套用積木後在下方新增雙網格或三網格，將元件新增至雙網格或三網格內之後左邊的元件icon跑版(紅框處)
![edm元件icon跑版-2](https://user-images.githubusercontent.com/49626114/60778893-5750da80-a16b-11e9-8159-e3ce5df9fe73.png)

**Comment by AnitaRyzo** [comment]
目前使用上述方式操作，icon未跑版
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
目前按照上述的方式操作icon不會跑版。
◎◎ 20190710確認以上正式環境內容 ◎◎
