### ISSUE TITLE
【問題】EDM最後一個被刪除網格的元件，移動後會消失

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1420]
EDM最後一個被刪除網格的元件，移動後會消失
step1. 選擇其中一個元件，拉至其他網格中
情境：將「文字」元件，拉至三網格的最左邊
![image](https://user-images.githubusercontent.com/41721950/60779789-95033280-a16e-11e9-920a-4a62f4c9d685.png)
step2. 刪除元件原本的網格
情境：將「文字」元件的原先網格刪除
![image](https://user-images.githubusercontent.com/41721950/60779810-aa785c80-a16e-11e9-9275-9cf5de4fed3b.png)
step3.移動未有網格的元件，元件會消失
情境：「文字」元件由三網格的最左邊移動至中間，「文字」元件消失
![image](https://user-images.githubusercontent.com/41721950/60779915-0a6f0300-a16f-11e9-93a6-ee52b32ad6ea.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
目前使用上述方式操作，元件會留存
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
目前照著上述的方式操作元件不會消失。
◎◎ 20190710確認以上正式環境內容 ◎◎
