### ISSUE TITLE
[問題]banner替換圖片可以上傳gif檔

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1421]
依照上傳圖片的提示文字說明支援格式僅有JPG和PNG。
![banner圖片提示文字](https://user-images.githubusercontent.com/49626114/60780665-fb3d8480-a171-11e9-800e-8ee1f7dc4040.png)

但是如果使用替換圖片功能選擇GIF格式的圖片檔
![banner替換圖片](https://user-images.githubusercontent.com/49626114/60780735-36d84e80-a172-11e9-885b-f6c90aed90b5.png)
![banner選擇gif檔](https://user-images.githubusercontent.com/49626114/60780751-48b9f180-a172-11e9-9df1-c0892164ba66.png)

GIF格式圖片檔會成功替換並顯示在頁面上。
![banner成功替換gif檔](https://user-images.githubusercontent.com/49626114/60780795-6be4a100-a172-11e9-8447-82ce64a1bb7a.png)

**Comment by AnitaRyzo** [comment]
Banner『替換圖片』會阻擋gif檔的圖片
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
Banner『替換圖片』會阻擋gif檔的圖片
◎◎ 20190710確認以上正式環境內容 ◎◎
