### ISSUE TITLE
【問題】序號產生器表單位置跑版 

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#1423]
專案中的序號產生器在電腦中觀看，
表單跑到畫面的最左側
為不正常顯示

<img width="1438" alt="螢幕快照 2019-07-08 下午4 35 01" src="https://user-images.githubusercontent.com/34327325/60795606-892f6480-a19e-11e9-8e0e-5c80cf46f692.png">

**Comment by Gabe-Liu** [comment]
互動表單的預設對齊點是左上方，記得要拖拉一下位置

**Comment by weilyn** [comment]
但我製作的是純手機版網頁
所以不應該出現這個狀況

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60935371-3bc90980-a2fc-11e9-8138-ffedf5780755.png)
◎◎ 20190710確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60944115-8194ca80-a31a-11e9-8774-7443d9ee3f2b.png)
◎◎ 20190710確認以上正式環境內容 ◎◎
