### ISSUE TITLE
[問題]EDM網頁擷取時，若非選擇第一張輪播圖則輪播圖呈現空白

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1425]
如果專案中有輪播圖元件時，在EDM的網頁擷取功能的步驟2"選擇幻燈片"可以滑動輪播圖選擇要顯示的圖片(如紅框處A可以滑動到B)
![EDM網頁擷取](https://user-images.githubusercontent.com/49626114/60854351-7c5c5080-a232-11e9-96bd-4790d032a242.png)
但是如果選擇的圖片不是輪播圖的第一張圖，則輪播圖呈現空白沒有圖片。
![EDM輪播圖空白](https://user-images.githubusercontent.com/49626114/60854866-49b35780-a234-11e9-8e54-874b11ac4537.png)

**Comment by Gabe-Liu** [comment]
在EDM截圖時，改成無法滑動輪播圖，確保在第一張圖片上。

**Comment by AnitaRyzo** [comment]
無法滑動輪播圖與輪播區塊，確保畫面停留在第一個。
![image](https://user-images.githubusercontent.com/41721950/60935838-c9592900-a2fd-11e9-8d4e-5541959743a5.png)
◎◎ 20190710確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
在網頁擷取功能中無法滑動輪播圖與輪播區塊，確保停留在第一個畫面。
![1425](https://user-images.githubusercontent.com/49626114/60938837-0fb38580-a308-11e9-8b44-aedb378a3352.png)
◎◎ 20190710確認以上正式環境內容 ◎◎
