### ISSUE TITLE
[問題]專案的文字樣式在EDM的網頁擷取功能中跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1427]
專案的"英文"文字樣式在EDM的網頁擷取功能中跑版。
在步驟2"選擇幻燈片"還是呈現正常樣子，但是到步驟3"擷取畫面"樣式就會跑版。
![網也擷取畫面不一致](https://user-images.githubusercontent.com/49626114/60861804-2a292880-a24e-11e9-9db2-2eb6412f48e1.png)

以下是所有文字樣式的比對圖(紅框是EDM擷取畫面後的樣子，黃框是專案發佈後正常呈現樣子)
中文樣式皆正常，僅有英文樣是會跑版。
![比對圖1](https://user-images.githubusercontent.com/49626114/60861982-d408b500-a24e-11e9-9516-804e6684b288.PNG)
![比對圖2](https://user-images.githubusercontent.com/49626114/60861985-d703a580-a24e-11e9-80a1-d910221ae8bb.PNG)
![比對圖3](https://user-images.githubusercontent.com/49626114/60861987-dbc85980-a24e-11e9-9f1d-2fb2cdab2f0e.PNG)

**Comment by Gabe-Liu** [comment]
字形會修正回來，但是文字的位移問題，是無法解決掉的，除非像是Banner那樣把位移的字形給移除。

**Comment by AnitaRyzo** [comment]
@ryzojudy 請協助是否增加提示文字，告訴客戶：有些字型會有位移的狀況。
PS: Banner移除位移文字後，可用字型變成只有29個唷!

**Comment by ryzojudy** [comment]
請問關於位移的部分
是只有在截圖時會產生是嗎?
(意指在一般專案發佈瀏覽的狀況下沒有問題)

**Comment by cocosu123** [comment]
在一般專案發佈瀏覽都是沒問題的，只有在EDM的網頁擷取功能才會出現此問題。

**Comment by ryzojudy** [comment]
好的 了解

**Comment by AnitaRyzo** [comment]
@ryzojudy 專案中**文字設定的『底線跟刪除線』在網頁擷取是無法看到的**
![image](https://user-images.githubusercontent.com/41721950/60939399-13480c00-a30a-11e9-82ee-395719c3da8f.png)
![image](https://user-images.githubusercontent.com/41721950/60939406-1e02a100-a30a-11e9-9879-7590b01feacc.png)
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by ryzojudy** [comment]
增加小字說明：
部份字型會有位移狀況發生!

再麻煩 @Samasianspock 協助圖片的部分

**Comment by AnitaRyzo** [comment]
後續設計已增加#1431 ，正式環境的文字樣式也確定有正確顯示；故先關閉此issue。
