### ISSUE TITLE
【問題】專案預覽表單時，單頁面內的跳題功能失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1428]
專案內預覽表單元件
![image](https://user-images.githubusercontent.com/41721950/60863853-8131fc00-a254-11e9-902c-5ecf2f266bfd.png)
在預覽時，單頁面內的跳題功能失效
![image](https://user-images.githubusercontent.com/41721950/60863969-d8d06780-a254-11e9-9f2c-c6718c39e5cf.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
#1429

**Comment by AnitaRyzo** [comment]
題目設定如下
![image](https://user-images.githubusercontent.com/41721950/60873320-c6f8bf80-a268-11e9-8007-028c90c24c61.png)
『預覽』已跳至指定題目
![image](https://user-images.githubusercontent.com/41721950/60873584-379fdc00-a269-11e9-893b-b2787b1aa223.png)
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
在預覽狀態時，表單已可正常執行跳題。
![1428](https://user-images.githubusercontent.com/49626114/60939331-cfed9d80-a309-11e9-9e68-d85c1fdbde8c.png)
◎◎ 20190710確認以上正式環境內容 ◎◎
