### ISSUE TITLE
【問題】專案預覽的表單有設定跳題時，編輯區跑版

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1429]
專案內預覽表單元件
![image](https://user-images.githubusercontent.com/41721950/60863853-8131fc00-a254-11e9-902c-5ecf2f266bfd.png)
操作有『設定跳題的表單』後
![image](https://user-images.githubusercontent.com/41721950/60864466-47fa8b80-a256-11e9-82b9-42d96a2c298c.png)
整個編輯區就跑版，無法拉回原位
![image](https://user-images.githubusercontent.com/41721950/60864534-6fe9ef00-a256-11e9-966a-4d9f23ae90ae.png)
暫解：離開此專案，再次進入
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
表單有設定跳題，編輯區仍會在原地
◎◎ 20190709確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
在預覽狀態操作跳題表單，回到編輯區表單仍在原處。
◎◎ 20190710確認以上正式環境內容 ◎◎
