### ISSUE TITLE
【問題】互動的表單有必填卻可以按下『送出表單』，表單就會關閉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1433]
互動元件的表單題目中，設立『必填題』
![image](https://user-images.githubusercontent.com/41721950/61100337-6e0f6e00-a498-11e9-867d-41e6c3aa1621.png)
抽到獎項後，未填表單的『必填題』就按下『送出表單』，『提示字元』在頂端，但表單已關閉
![image](https://user-images.githubusercontent.com/41721950/61100482-f4c44b00-a498-11e9-92b1-27926e8c0a4a.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/61100581-453ba880-a499-11e9-86db-ebc5f1acbae6.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
互動的表單有必填按下『送出表單』不會關閉表單
![image](https://user-images.githubusercontent.com/41721950/63415961-21bd3380-c431-11e9-94d7-2b3112222f93.png)
◎◎ 20190821確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
互動元件的表單未填寫「必填」題就按下『送出表單』不會關閉表單，會跳出提示訊息，必須填寫完才能夠送出表單。
![image](https://user-images.githubusercontent.com/49626114/63670752-3c682180-c810-11e9-8ee6-56793d912dec.png)
