### ISSUE TITLE
【ml環境】幸運轉盤的預覽圖掉圖

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1438]
『幸運轉盤』不管是新設立或是套版的啟用，都會掉圖
![image](https://user-images.githubusercontent.com/41721950/61278965-c66fa400-a7e7-11e9-9aae-68bb0675e219.png)
以上問題請協助處理，感恩~

**Comment by Kyle30** [comment]
此環境模擬 國泰 正式環境
由於國泰的正式環境使用一個 Apache 搭配兩個 AP Server 來做負載平衡
且兩台 AP Server 的本地檔案並不會同步
故需要將獎項圖片改為存取線上的檔案 ( 如 CDN )

**Comment by AnitaRyzo** [comment]
目前在模擬環境看到的幸運轉盤未有此問題
![image](https://user-images.githubusercontent.com/41721950/63414445-7612e400-c42e-11e9-9e26-cc98e7b89b3d.png)
◎◎ 20190821確認以上測試環境內容in weba.ga◎◎
