### ISSUE TITLE
[問題]臉書工具的網址顯示undefined

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1439]
step 1. 新增臉書工具元件
step 2. 點擊網址欄位(綠框處)但是未輸入內容
step 3.再點擊臉書工具的編輯框後，網址欄位會顯示undefined(紅框處)
![臉書工具](https://user-images.githubusercontent.com/49626114/61340039-295a4d00-a873-11e9-9cd0-c9b9bf8a2165.png)

p.s. 動作型&內嵌型皆有上述情況發生

**Comment by AnitaRyzo** [comment]
臉書工具的動作型&內嵌型依照上述步驟，網址欄位已不會顯示undefined
◎◎ 20190723確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
臉書工具的動作型&內嵌型依照上述步驟，網址欄位已不會顯示undefined
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
臉書工具的動作型&內嵌型依照上述步驟，網址欄位已不會顯示undefined
◎◎ 20190826確認以上正式環境內容 ◎◎
