### ISSUE TITLE
【權限】擁有刪除的權限 但不能刪除專案

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#144]
我的帳號judy@ryzo.io
有除了管理團隊以外的所有權限
但系統告知我無法刪除專案

我的權限
![image](https://user-images.githubusercontent.com/34263719/40031396-16df105e-5822-11e8-9599-d2465fe704a3.png)

![image](https://user-images.githubusercontent.com/34263719/40031399-1accb180-5822-11e8-89d2-9c32414a3ea3.png)

**Comment by ai015606220** [comment]
這裡我有調整好了，下次上線能夠解決

**Comment by Isabella-RYZO** [comment]
👌
