### ISSUE TITLE
[問題]請協助刪除臉書工具(動作型)的預設留言

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1440]
請協助刪除臉書工具(動作型)的預設留言(紅框處)
![臉書工具預設留言](https://user-images.githubusercontent.com/49626114/61340273-3592da00-a874-11e9-9706-1afdf882586d.png)

**Comment by AnitaRyzo** [comment]
預設留言已為0則
![image](https://user-images.githubusercontent.com/41721950/61691016-325c8a00-ad5d-11e9-990e-da0d368b50ca.png)
◎◎ 20190723確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
預設留言已為0則
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
預設留言已為0則
![image](https://user-images.githubusercontent.com/41721950/63661064-c8b41d80-c7eb-11e9-8d2f-6125f1952b7a.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
