### ISSUE TITLE
【問題】EDM的編輯區尺寸縮放，新增元件會影響畫布顯示位置

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1441]
當編輯區尺寸為100%，增加元件時，畫布位置會慢慢往上推移
![image](https://user-images.githubusercontent.com/41721950/61345824-37b36380-a889-11e9-98fa-6d4312852a4b.png)
當編輯區尺寸非100%(不論大或小)，增加元件時，畫布會跳離編輯區的中央(如下圖)
![image](https://user-images.githubusercontent.com/41721950/61345935-9f69ae80-a889-11e9-9f3f-6bb913e8764a.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
MAC與Windows系統當使用者新增元件時，會到畫布中間
◎◎ 20190723確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
此功能再次失效，請協助處理。感恩
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
當編輯區尺寸為100%，增加元件時，情況如下圖
![image](https://user-images.githubusercontent.com/49626114/67058501-ae614500-f187-11e9-9946-d44d941f7e4c.png)
當編輯區尺寸為50%，增加元件時，情況如下圖
![image](https://user-images.githubusercontent.com/49626114/67058683-80303500-f188-11e9-8e00-07103127560d.png)
當編輯區尺寸為150%，增加元件時，情況如下圖
![image](https://user-images.githubusercontent.com/49626114/67058715-9ccc6d00-f188-11e9-919b-a694ed50cf22.png)
◎◎ 20191018確認以上正式環境內容◎◎
