### ISSUE TITLE
【問題】序號表單的『送出後執行動作』遺失

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1442]
#1395 的延續問題
序號機的『表單資訊設定』可設定表單的「送出後執行動作」
![image](https://user-images.githubusercontent.com/41721950/61433380-ba115580-a965-11e9-9df9-bae3fae40ba8.png)
但目前就算有設定，瀏覽器執行「表單送出」會直接跳出「QR code」
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
序號機沒有送出後執行動作的設定，會把它給移除

**Comment by AnitaRyzo** [comment]
序號機已移除『送出後執行動作』
![image](https://user-images.githubusercontent.com/41721950/61690903-f9241a00-ad5c-11e9-83ff-e3eee5e69e68.png)
◎◎ 20190723確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
序號機已移除『送出後執行動作』，目前僅有一般表單&互動元件的抽獎表單有『送出後執行動作』的功能。
![image](https://user-images.githubusercontent.com/49626114/63670118-6ae4fd00-c80e-11e9-8d4b-9a3ae34644d8.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
