### ISSUE TITLE
【問題】EDM的信件寄不到outlook的信箱中

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1448]
在EDM的試寄名單中輸入outlook的信箱
![image](https://user-images.githubusercontent.com/41721950/61601538-7b7ee200-ac68-11e9-8bd9-41e4380b0df9.png)
但信箱遲遲收不到信件
![image](https://user-images.githubusercontent.com/41721950/61601523-630ec780-ac68-11e9-8d75-71b646f3af5f.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
正常
目前用的這個ip寄outlook會被擋信

**Comment by AnitaRyzo** [comment]
在edm設計的支援列表有提到outlook的支援狀況
但https://ryzoweba.io/ 目前的ip寄outlook會被擋信，所以暫時無法確認功能狀況，請知悉~
![image](https://user-images.githubusercontent.com/41721950/61608824-c0197600-ac86-11e9-9a21-ae92a7f4ad36.png)
