### ISSUE TITLE
【專案發佈】發佈中的專案關閉發佈

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#145]
發佈中的專案關閉發佈後
目前是會再回到待發佈的分頁
希望他可以重新走一次審核流程才會出現在發佈後台中

關閉發佈 -> (不會出現在專案審核/發佈) -> 重新申請審核 -> (出現在專案審核)審核通過 ->(出現在專案發佈的待發佈分頁) 專案發佈

**Comment by ai015606220** [comment]
但這種方式我覺得不是很合理，因為這個專案的內容已經通過了審核，為何同樣的內容要再經過審核一次??

**Comment by ryzojudy** [comment]
因為可以專案發佈的人可以是一個以上
所以如果因為一些不知道的原因下架
在還沒有解決問題點時 就被不清楚狀況的人發佈上線也是有可能的
所以我是覺得在重新走一次審核流程是最保險的 雖然可能比較麻煩

**Comment by ryuichl** [comment]
現在新的流程中
專案關不關閉 PM完全是可以自己決定
已經跟審核流程無關了

甚至他在編輯頁就可以開啟專案
