### ISSUE TITLE
[問題]mgm連結產出的條件進度顯示資訊錯誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1451]
在mgm編輯頁連結產出的顯示資訊可以看到當進度已達成會顯示紅框處的內容，未達成則顯示黃框處的內容。
![mgm編輯頁](https://user-images.githubusercontent.com/49626114/61687729-b0b52e00-ad55-11e9-8150-cfbcbfe821f6.png)

以下狀況僅會在帳號第一次登入的時候發生。
登入後點擊mgm按鈕"點我分享"，在尚未分享連結給任何人的情況下會直接出現「進度已達成」的描述(紅框處)
![mgm產出連結後](https://user-images.githubusercontent.com/49626114/61688273-2a99e700-ad57-11e9-8133-a1f8209a13f9.png)
點選『活動紀錄』或是畫面重整後，描述會回到「進度未達成」的描述。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/62269970-442de380-b467-11e9-89c1-7e90800f6f4e.png)
◎◎ 20190730確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
實測失敗
![image](https://user-images.githubusercontent.com/41721950/62281464-63853a80-b480-11e9-8798-975e8f95c70b.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/64663882-d28e7f80-d47f-11e9-98c0-5d279d397086.png)
◎◎ 20190911確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
mgm連結產出的條件進度顯示資訊在電腦版或手機版都是正確的
◎◎ 20191002確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
mgm連結產出的條件進度顯示資訊在電腦版或手機版都是正確的
![1451](https://user-images.githubusercontent.com/49626114/67057740-655bc180-f184-11e9-9fa0-4fafbbf4a64a.png)
◎◎ 20191018確認以上正式環境內容◎◎
