### ISSUE TITLE
[測試環境] 新建專案後未填域名申請審核

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1454]
新建專案後未填域名申請審核後會打開設域名的地方
但是確認申請審核的跳窗沒有關掉
![image](https://user-images.githubusercontent.com/10150807/61762285-1829b700-ae04-11e9-9ba5-ef0b1f2a9f40.png)

**Comment by leonlin6** [comment]
於20190731 與Gabe和Sam討論後，調整成

當domain_name錯誤時，點選申請審核，跳頁回到「發佈頁面」，域名欄位顯示紅色警告提示，「申請審核跳窗」不出現
當domain_name正確時，點選申請審核，「申請審核跳窗」出現

**Comment by leonlin6** [comment]
之前的調整可參考#1383、#927

**Comment by AnitaRyzo** [comment]
新建專案後未填域名申請審核，不會跳出選取視窗
![image](https://user-images.githubusercontent.com/41721950/62276850-7cd5b900-b477-11e9-986d-1e2360330365.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
新建專案後未填域名申請審核，不會跳出選取視窗
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
無域名可儲存專案
![image](https://user-images.githubusercontent.com/41721950/63659743-b2a35e80-c7e5-11e9-9899-d8dca5847baa.png)
無域名的『申請審核』不會出現確認窗或是隱藏確認鈕
![image](https://user-images.githubusercontent.com/41721950/63659801-0e6de780-c7e6-11e9-86c2-d42a5ead7266.png)
◎◎ 20190823確認以上正式環境內容 ◎◎
