### ISSUE TITLE
【問題】小螢幕編輯Banner需要滾輪

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#1456]
目前在進行Banner編輯時，若是複製了一個小尺寸的畫布沒有辦法往下移動去選擇元件

原尺寸
<img width="1375" alt="螢幕快照 2019-07-25 下午2 08 51" src="https://user-images.githubusercontent.com/36216073/61850107-ff91cd80-aee5-11e9-99e2-495572914162.png">

小尺寸
<img width="1373" alt="螢幕快照 2019-07-25 下午2 08 39" src="https://user-images.githubusercontent.com/36216073/61850142-1506f780-aee6-11e9-8347-0c314edd19e2.png">

再麻煩協助處理，謝謝！

**Comment by AnitaRyzo** [comment]
小畫面+圖片有捲軸
![image](https://user-images.githubusercontent.com/41721950/62261955-8ea06780-b449-11e9-9f2e-84d624ab502e.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
小畫面+大圖片有捲軸
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
小畫面+大圖片有捲軸
![1456](https://user-images.githubusercontent.com/49626114/63661497-6bb96700-c7ed-11e9-852d-b599b98f46b3.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
