### ISSUE TITLE
[測試環境]序號機在互動後台的表單回覆內容未加密

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1457]
序號表單有設定題型加密，在表單管理後台有正常呈現(紅框處)，但是在互動後台的表單回覆內容沒有加密(黃框處)。
![互動後台未加密](https://user-images.githubusercontent.com/49626114/61851986-e8a1aa00-aeea-11e9-922c-86e8995c8c88.png)

**Comment by AnitaRyzo** [comment]
序號機在互動後台的表單回覆內容已加密
![image](https://user-images.githubusercontent.com/41721950/62271359-003cdd80-b46b-11e9-8981-36cc75e8145a.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
序號機在互動後台的表單回覆內容已加密
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
序號機在互動後台的表單回覆內容已加密
![image](https://user-images.githubusercontent.com/49626114/63669963-06c23900-c80e-11e9-8ff6-103f051c0b20.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
