### ISSUE TITLE
【問題】跨帳號查看數據的權限，不該攸關左側數據後台圖示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1458]
當『跨帳號功能-查看數據』的權限開啟時，才有「數據後台」的圖示
![image](https://user-images.githubusercontent.com/41721950/61855473-b6944600-aef2-11e9-9664-3d3d1967f7b7.png)
當『跨帳號功能-查看數據』的權限關閉時，則無「數據後台」的圖示
![image](https://user-images.githubusercontent.com/41721950/61855530-cca20680-aef2-11e9-8f68-8ecec16fdad2.png)
但左側「數據後台」圖示的功能非跨帳號才會執行，請協助修改此設計。感恩~

**Comment by AnitaRyzo** [comment]
僅「專案管理(個人帳號)-專案數據v查看』才能開啟左側數據後台圖示
![image](https://user-images.githubusercontent.com/41721950/62263619-864b2b00-b44f-11e9-8779-d796323d827b.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
僅「專案管理(個人帳號)-專案數據v查看』才能開啟左側數據後台圖示
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
僅「專案管理(個人帳號)-專案數據v查看』才能開啟左側數據後台圖示(黃框)。
「跨帳號功能-查看數據」的權限(綠框)已不會影響左側數據後台圖示。
![1458](https://user-images.githubusercontent.com/49626114/63668762-95cd5200-c80a-11e9-9dac-4c4beb3fa557.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
