### ISSUE TITLE
【問題】使用套版的Banner，操作後未有暫存提示窗

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1459]
當Banner使用套版
![image](https://user-images.githubusercontent.com/41721950/61924297-bd29c880-af99-11e9-9822-8e40de08b30e.png)
執行任何操作後若未按『儲存』，不會出現如下的「暫存提示窗」
![image](https://user-images.githubusercontent.com/41721950/61924329-df234b00-af99-11e9-8af1-fa2b740863e2.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
即使未執行任何操作，也會出現如下的「暫存提示窗」
![image](https://user-images.githubusercontent.com/41721950/62263916-6cf6ae80-b450-11e9-91db-09102174f17c.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
使用套版的Banner，即使未執行任何操作，也會出現如下的「暫存提示窗」
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
使用套版的Banner，即使未執行任何操作，也會出現如下黃框的「暫存提示窗」。
![1459](https://user-images.githubusercontent.com/49626114/63661244-4aa44680-c7ec-11e9-8e79-e105f92b5b5c.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
