### ISSUE TITLE
【測試環境】套版管理的套版設定呈現黑底沒有內容

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1460]
『審核發佈管理』的套版管理按下套版設定(紅框)會呈現黑畫面沒有內容。
![image](https://user-images.githubusercontent.com/41721950/61925792-6673bd00-afa0-11e9-8dbf-048b37b3cc21.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/62264500-bf38cf00-b452-11e9-82fe-8698bf4c0bcb.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
套版設定已有內容
◎◎ 20190805確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![1460](https://user-images.githubusercontent.com/49626114/63668197-ffe4f780-c808-11e9-893d-ec24127acc62.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
