### ISSUE TITLE
[問題]Banner審核中的套版"廣告畫布"沒有滾輪造成畫面跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1463]
Banner在"套版申請"跟審核發佈管理"套版審核"的審核中，套版"廣告畫布"區塊沒有滾輪，所以有多個畫布的情況下，會造成畫面跑版(紅框處)，而無法執行下一步驟。
![banner審核中跑版](https://user-images.githubusercontent.com/49626114/62016816-ceb3e000-b1e6-11e9-8588-b25351f213ff.png)

**Comment by AnitaRyzo** [comment]
審核中的套版"廣告畫布"已增加滾輪
![image](https://user-images.githubusercontent.com/41721950/62264322-03779f80-b452-11e9-8e2c-0eee70d6df20.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
審核中的套版"廣告畫布"已增加滾輪
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
Banner在「套版申請」跟「套版審核」審核中的廣告畫布區域皆已增加滾輪。
![1463](https://user-images.githubusercontent.com/49626114/63660962-4f1c2f80-c7eb-11e9-9049-54313b02d07e.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
