### ISSUE TITLE
【測試環境】數據的樞紐設定顯示資料時，格線消失了

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1465]
無論是左側功能列的『數據後台』或是『跨帳號-查看數據』的樞紐設定
在IO正式環境顯示資料時可以看得見格線(黃框)，但在com測試環境卻沒有格線(紅框)
![image](https://user-images.githubusercontent.com/41721950/62017328-cb215880-b1e8-11e9-8858-64334a281e07.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
數據的樞紐設定顯示資料時已有格線
![image](https://user-images.githubusercontent.com/41721950/62281937-3dac6580-b481-11e9-8638-66c72fed6a6f.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
數據的樞紐設定顯示資料時已有格線
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
數據的樞紐設定顯示資料時已有格線。
![image](https://user-images.githubusercontent.com/49626114/63661668-29445a00-c7ee-11e9-9371-8aa11df90a6e.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
