### ISSUE TITLE
【問題】MGM重複計算+填寫表單，在瀏覽器不該出現『不存在的邀請碼』

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1467]
step1. MGM設立『分享機制：重複計算+填寫表單』
![image](https://user-images.githubusercontent.com/41721950/62027782-29fac800-b211-11e9-80f7-436f9529d14b.png)
step2. 瀏覽器Chrome→Opera→Firefox，再從Firefox的專屬連結→Opera，就會出現『不存在的邀請碼』(可隨意掉換瀏覽器順序)
![image](https://user-images.githubusercontent.com/41721950/62028062-f4a2aa00-b211-11e9-8b8e-19adfaea16fc.png)
step3. 出現『不存在的邀請碼』的瀏覽器，將『表單』關閉後，會回到『點我分享』按鈕，點擊『點我分享』又要求填寫表單；不斷重複填寫表單直到重整頁面，才能拿到專屬連結。
![image](https://user-images.githubusercontent.com/41721950/62032023-3e43c280-b21b-11e9-83d5-2112c3d80fda.png)
![image](https://user-images.githubusercontent.com/41721950/62030682-320a3600-b218-11e9-92ba-9e1aec10b9e1.png)
已測的瀏覽器：Chrome、Opera、Firefox、Edge
以上問題請協助處理，感恩

**Comment by AnitaRyzo** [comment]
瀏覽器Chrome→Opera→Firefox，再從Firefox的專屬連結→Opera
依照上述步驟未出現『不存在的邀請碼』
![image](https://user-images.githubusercontent.com/41721950/62270321-54928e00-b468-11e9-8f43-fd8dd1ccfa34.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
瀏覽器Chrome→Opera→Firefox，再從Firefox的專屬連結→Opera
依照上述步驟未出現『不存在的邀請碼』
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述步驟操作未出現「不存在的邀請碼」。
◎◎ 20190826確認以上正式環境內容◎◎
