### ISSUE TITLE
【測試環境】利用資料綁定網址開啟單頁的幻燈片，在數據後台的資料綁定無資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1468]
專案設計的是單頁的幻燈片
![image](https://user-images.githubusercontent.com/41721950/62100363-0a70a780-b2c4-11e9-9abd-2952c8a923ff.png)
專案僅用專屬URL開啟，故只要有數據就是資料綁定的數據
![image](https://user-images.githubusercontent.com/41721950/62094234-fb332f00-b2ae-11e9-800e-5e2ed4a63b8a.png)
但點選『資料綁定』按鈕(黃框)，卻出現暫無數據的提示訊息
![image](https://user-images.githubusercontent.com/41721950/62094269-1867fd80-b2af-11e9-8900-d3c341b73ac9.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
我用GA的測試工具
看起來是有送資料出去
不確定為什麼沒有資料
可能要再看看是為甚麼

**Comment by ryuichl** [comment]
大概知道原因了
能找到這個issue真是太猛了

**Comment by AnitaRyzo** [comment]
單頁的幻燈片，在數據後台的資料綁定已有資料
![image](https://user-images.githubusercontent.com/41721950/62279607-03d96000-b47d-11e9-89dd-696ae40f0a2a.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
單頁的幻燈片，在數據後台的資料綁定已有資料
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
單頁的幻燈片，在數據後台的資料綁定已有資料
![image](https://user-images.githubusercontent.com/41721950/63571061-a5059300-c5b1-11e9-89c1-58f2d53bc76e.png)
◎◎ 20190823確認以上正式環境內容 ◎◎
