### ISSUE TITLE
【測試環境】EDM的試寄系統失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1470]
在EDM的試寄系統輸入信箱後，遲遲等不到郵件
![image](https://user-images.githubusercontent.com/41721950/62095751-f3c25480-b2b3-11e9-8673-59e1ecf358a4.png)
錯誤訊息如下，請參考
![image](https://user-images.githubusercontent.com/41721950/62095748-f0c76400-b2b3-11e9-9b71-7f35f770efb0.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
已可以收到試寄的信件
![image](https://user-images.githubusercontent.com/41721950/62104170-5f66ea80-b2d1-11e9-96fa-ec9163aa74ea.png)
◎◎ 20190730確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/62504338-9b96cf80-b82a-11e9-9bb4-0e2304efaba7.png)
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
已可收到EDM試寄信件。
![image](https://user-images.githubusercontent.com/49626114/63660077-6bb66880-c7e7-11e9-9fcb-296407c444a4.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
