### ISSUE TITLE
【測試環境】Banner的預覽未顯示目前被選取的畫布

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1471]
Banner在正式環境時，點選『預覽』會顯示目前被選取的畫布
但在測試環境第一時間是黑畫面，要切換畫布才會顯示
若今天只有一頁畫布，那就永遠無法預覽了...
![image](https://user-images.githubusercontent.com/41721950/62097302-f5424b80-b2b8-11e9-848a-cb5a4cfd2460.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/62263784-08d3ea80-b450-11e9-9cca-b2565ef75e29.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
預覽會顯示目前被選取的畫布
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
Banner點選預覽會顯示目前被選取的畫布。
![image](https://user-images.githubusercontent.com/49626114/63659837-407f4980-c7e6-11e9-8b61-f293f68ef082.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
