### ISSUE TITLE
【測試環境】套版審核的備註欄位大於等於三欄，審核無效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1472]
『審核發佈管理-套版審核、Banner套版審核、EDM套版審核』皆有此問題
![image](https://user-images.githubusercontent.com/41721950/62098257-2ec88600-b2bc-11e9-8ea4-3d8b7d52302e.png)
當『備註欄位』大於等於三欄且多行字，審核送出無效
![image](https://user-images.githubusercontent.com/41721950/62098415-cf1eaa80-b2bc-11e9-9d4a-d527ba5994ef.png)
錯誤訊息如下，請參考~
![image](https://user-images.githubusercontent.com/41721950/62098539-5c61ff00-b2bd-11e9-9101-67dfdd10ee67.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
備註在後台有限制字數
太多字確實會出錯
可能要想一下怎麼改

**Comment by AnitaRyzo** [comment]
當『備註欄位』大於等於三欄且多行字，已可完成審核
![image](https://user-images.githubusercontent.com/41721950/64219285-75cb1c00-cef7-11e9-9e06-26f41b66dfc2.png)
![image](https://user-images.githubusercontent.com/41721950/64219288-79f73980-cef7-11e9-85fc-e049818bf66f.png)
◎◎ 20190904確認以上正式環境內容 ◎◎
