### ISSUE TITLE
【問題】團隊管理的成員在隱藏勾選的狀態下被刪除

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1473]
step1.『帳號管理-團隊管理』點選其中一個成員
![image](https://user-images.githubusercontent.com/41721950/62106778-adcbb780-b2d8-11e9-92e7-8d07229b9805.png)
step2. 切換至『團隊權限總覽』
![image](https://user-images.githubusercontent.com/41721950/62106883-fa16f780-b2d8-11e9-9ad3-32e6df71cbc8.png)
step3.切換回『團隊成員』後，發現**名單未有被選取的成員**，但『刪除選取的團員』與『批次修改權限』(紅框)卻是可以點選的
![image](https://user-images.githubusercontent.com/41721950/62107024-4d894580-b2d9-11e9-9b1f-a4f1eab1ef60.png)
問題：正式環境在此時若按下『刪除選取的團員』，第一步驟點選的團員就會被刪除
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
切換『團隊成員』與『團隊權限總覽』，不會有隱藏勾選的狀態
![image](https://user-images.githubusercontent.com/41721950/62273076-3bd9a680-b46f-11e9-95db-d7d66f59c456.png)
但是意外發現若『帳號編輯』也可以在隱藏勾選的狀態刪除成員
![image](https://user-images.githubusercontent.com/41721950/62273350-e94cba00-b46f-11e9-8093-b7438174adfc.png)
◎◎ 20190801確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
切換『團隊成員』『團隊權限總覽』或是『帳號編輯』都不會有隱藏勾選的狀態
◎◎ 20190802確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
切換『團隊成員』『團隊權限總覽』或是『帳號編輯』都不會有隱藏勾選的狀態
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述步驟切換『團隊成員』『團隊權限總覽』或是『帳號編輯』都不會有隱藏勾選的狀態。
◎◎ 20190826確認以上正式環境內容 ◎◎
