### ISSUE TITLE
【問題】互動元件的自動傳送表單內有複選題或矩陣題，表單無法下載

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1475]
當互動元件的表單設定為『自動傳送表單(隱藏此表單)』，而表單題目有『複選題』或『矩陣式題』
![image](https://user-images.githubusercontent.com/41721950/62198000-754cdc00-b3b3-11e9-8059-c7a94f3f67d1.png)
在瀏覽器都可以正確執行互動元件，但在「表單管理」按下「下載」時
![image](https://user-images.githubusercontent.com/41721950/62196828-4afa1f00-b3b1-11e9-8bdc-1d6c5f292658.png)
『複選題』開啟錯誤訊息頁如下
![image](https://user-images.githubusercontent.com/41721950/62196935-85fc5280-b3b1-11e9-9920-5da60f42305c.png)
『矩陣式題』開啟錯誤訊息頁如下
![image](https://user-images.githubusercontent.com/41721950/62197827-230bbb00-b3b3-11e9-9293-c4e7ced66987.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
『自動傳送表單(隱藏此表單)』，而表單題目有『複選題』或『矩陣式題』都可以下載檔案
![image](https://user-images.githubusercontent.com/41721950/62268409-640ed880-b462-11e9-8be2-d5abe05fbaa7.png)
◎◎ 20190730確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『自動傳送表單(隱藏此表單)』的表單題目有『複選題』或『矩陣式題』都可以下載檔案
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
『自動傳送表單(隱藏此表單)』的表單題目有『複選題』或『矩陣式題』都可以下載檔案。
![1475](https://user-images.githubusercontent.com/49626114/63659620-ec279a00-c7e4-11e9-9100-355185b75891.png)
◎◎ 20190826確認以上正式環境內容 ◎◎
