### ISSUE TITLE
【測試環境】設置「管理後台-帳號管理」出現的錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1476]
「最高權限者」在設置「管理後台-帳號管理」時，對「全域權限」任一功能開關後，按下『完成』鈕，畫面會不斷loading
![image](https://user-images.githubusercontent.com/41721950/62261292-5435cb00-b447-11e9-9d22-5a24b5d15224.png)
錯誤訊息如下所示
![image](https://user-images.githubusercontent.com/41721950/62261403-c4445100-b447-11e9-8e19-bad44334fc7f.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
對「全域權限」任一功能開關後，已可順利按下『完成』鈕
◎◎ 20190802確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
對「全域權限」任一功能開關後，已可順利按下『完成』鈕
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
對「全域權限」任一功能開關後，已可順利按下『完成』鈕。
◎◎ 20190826確認以上正式環境內容 ◎◎
