### ISSUE TITLE
[測試環境]刮刮樂的中獎畫面未出現

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1477]
開始刮刮樂之前會先閃黑畫面，刮到完全乾淨卻沒有跳出中獎畫面，會一直停在下圖的狀態。
![image](https://user-images.githubusercontent.com/49626114/62276174-097f7780-b476-11e9-97f3-64d5cd4a3fc3.png)
正常刮刮樂刮完應該出現的畫面如下圖。
![image](https://user-images.githubusercontent.com/49626114/62276394-84489280-b476-11e9-9115-dce16cb45f05.png)

p.s.正式環境無此狀況發生。

**Comment by AnitaRyzo** [comment]
刮刮樂的中獎畫面會正常出現
◎◎ 20190802確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
刮刮樂的中獎畫面會正常出現
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
刮刮樂的中獎畫面會正常出現
◎◎ 20190826確認以上正式環境內容 ◎◎
