### ISSUE TITLE
[問題]套版管理的排序下拉選單跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1478]
所有"套版管理"(黃框)的排序下拉選單跑版(紅框處)，文字內容跟三角形圖示重疊。
![套版管理的排序下拉選單跑版](https://user-images.githubusercontent.com/49626114/62281194-e78af280-b47f-11e9-996b-8ee0f9d02787.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/62504943-3a243000-b82d-11e9-8a15-db67e6648507.png)
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![1478](https://user-images.githubusercontent.com/49626114/63579704-d0927880-c5c5-11e9-942c-bffdb4cdaed6.png)
◎◎ 20190823確認以上正式環境內容◎◎
