### ISSUE TITLE
[問題]表單的下拉式題目過長時，選單箭頭消失

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1479]
當下拉式題型的題目過長時(如第一題)，選單箭頭(紅框處)會消失。
![下拉式題目](https://user-images.githubusercontent.com/49626114/62343867-561e8d80-b51e-11e9-93e2-b520346276ba.png)

**Comment by AnitaRyzo** [comment]
當下拉式題型的題目過長時，會變成...
![image](https://user-images.githubusercontent.com/41721950/62511350-c3dff780-b845-11e9-8a33-c219e4cb446f.png)
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
下拉試題目過長時，呈現方式如下圖。
![1479](https://user-images.githubusercontent.com/49626114/63572428-75588a00-c5b5-11e9-9fd4-2e68c945e212.png)
◎◎ 20190823確認以上正式環境內容◎◎
