### ISSUE TITLE
【問題】MGM複製元件但未啟用，瀏覽無法開啟頁面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1480]
在編輯區將MGM複製，但未啟用或選擇
![image](https://user-images.githubusercontent.com/41721950/62344470-bf070500-b520-11e9-98b7-f54bb749ea67.png)
發佈後此專案在瀏覽頁面無法開啟，錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/62349149-786dd680-b531-11e9-84ce-ed713e5cbea7.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
MGM複製元件但未啟用，瀏覽器已可正確開啟頁面
![image](https://user-images.githubusercontent.com/41721950/62508789-73fc3300-b83b-11e9-99ec-b434eb051937.png)
◎◎ 20190806確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
MGM元件複製後未啟用，瀏覽器可開啟頁面。
![image](https://user-images.githubusercontent.com/49626114/63572006-645b4900-c5b4-11e9-96b5-fc6b56d78d8c.png)
◎◎ 20190823確認以上正式環境內容◎◎
