### ISSUE TITLE
[測試環境]一般表單元件沒有"送出後執行動作"的功能

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1481]
一般表單元件目前在測試環境中沒有"送出後執行動作"的功能(如紅框)，但是在正式環境中有此功能(如黃框)。
![一般表單跳轉](https://user-images.githubusercontent.com/49626114/62445865-e4e81000-b793-11e9-8ccf-e3ef340d265e.png)

@Gabe-Liu 請再麻煩修改此問題，感謝~

**Comment by Gabe-Liu** [comment]
剛跟Judy確認，序號與電子申請書不會有跳轉，其他都可以設定

**Comment by AnitaRyzo** [comment]
MGM是使用『一般表單』，即使可以設定「送出後執行動作」
但是在「分享者的表單」會直接跳轉「專屬連結分享」的頁面
![image](https://user-images.githubusercontent.com/41721950/62447628-604bc080-b798-11e9-9562-d94e739d04d7.png)
以上問題請協助一併處理，感恩~

**Comment by AnitaRyzo** [comment]
表單：序號產生器使用序號表單、MGM使用一般表單；與電子申請書
目前都無『送出後執行動作』的功能
![image](https://user-images.githubusercontent.com/41721950/62602086-7e92f700-b925-11e9-90aa-dfa35f9b5a47.png)
◎◎ 20190807確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
目前僅有一般表單&抽獎表單有"送出後執行動作"的功能。(如綠框)
電子申請書、序號表單、MGM的一般表單皆無"送出後執行動作"的功能。(如黃框)
![1481](https://user-images.githubusercontent.com/49626114/63571706-8ef8d200-c5b3-11e9-9d21-319560454a73.png)
◎◎ 20190823確認以上正式環境內容◎◎
