### ISSUE TITLE
[問題]切換幻燈片時，動畫會重複再執行一次

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1483]
操作步驟如下 : 
1.在同一個頁面有兩個幻燈片
2.第一個幻燈片內的某元件設定動畫，動畫次數僅設定1次(如黃框)
3.利用連結設定(按鈕/圖片/圖示)跳轉到下個幻燈片
![動畫重複](https://user-images.githubusercontent.com/49626114/62520280-d830ee00-b85f-11e9-874b-8e4e241ee031.png)

專案開啟後等待動畫執行1次，動畫結束後再切換幻燈片時，動畫會重複再執行一次。

專案連結 : https://a0806.ryzoweba.com

**Comment by AnitaRyzo** [comment]
依照上述步驟，動畫已不會重複再執行一次。
◎◎ 20190807確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述步驟，動畫僅會執行一次。
◎◎ 20190823確認以上正式環境內容◎◎
