### ISSUE TITLE
[測試環境]mgm設定跳轉會重複出現接收者表單

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1484]
分享機制重複或不重複都一樣會有此問題。
編輯頁設定步驟如下 : 
1.在頁面1設定mgm填寫表單(接收者表單)
![填寫表單](https://user-images.githubusercontent.com/49626114/62590641-9b1c3880-b8ff-11e9-93ec-b01f38ab82d2.png)
2.表單送出後執行動作設定跳轉頁面2
![image](https://user-images.githubusercontent.com/49626114/62590678-b6874380-b8ff-11e9-8389-a136aa86c61e.png)
3.在跳轉的頁面2放圖片/圖示/按鈕(有連結設定的元件)，設定連結頁面跳轉回頁面1
![image](https://user-images.githubusercontent.com/49626114/62590787-1bdb3480-b900-11e9-9fda-dfae971158f3.png)

發布後操作步驟如下 : 
1.從瀏覽器1複製優惠連結給瀏覽器2
2.瀏覽器2填寫完接收者表單後，會根據"連結跳轉設定"直接跳轉至頁面2
3.按下頁面2的可連結設定的元件後，會開啟頁面1
4.頁面1會第二次出現接收者表單，再次填寫完畢後跳轉至頁面2
(表單後台會有兩筆資料)
![image](https://user-images.githubusercontent.com/49626114/62591220-7d4fd300-b901-11e9-9114-040929b5c07c.png)
5.出現"不存在的邀請碼"的提示訊息
![image](https://user-images.githubusercontent.com/49626114/62591285-b4be7f80-b901-11e9-8e2f-bd30bc9a32a2.png)

**Comment by ryuichl** [comment]
@Gabe-Liu  @ai015606220 
是否先把一般表單還有抽獎表單
以外的跳轉都關掉

**Comment by AnitaRyzo** [comment]
請參考#1481 ，故先關閉此issue
