### ISSUE TITLE
【建議】EDM的背景圖片請增加刪除功能

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1485]
EDM的背景圖片可以設定開關，但是有時可能覺得不適合想刪除上傳的圖片
![image](https://user-images.githubusercontent.com/41721950/62599036-bbf38680-b91d-11e9-89d5-2c66568e3e61.png)
以上建議請參考，感恩~

**Comment by vianchang** [comment]
再麻煩工程加入刪除功能

**Comment by AnitaRyzo** [comment]
背景圖片有圖片的會出現『刪除』按鈕
![image](https://user-images.githubusercontent.com/41721950/63011420-d8ae3200-beba-11e9-80cf-3368226331d3.png)
◎◎ 20190814確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
背景圖片在有圖片的情況下會出現"刪除"按鈕。
![1485](https://user-images.githubusercontent.com/49626114/63566478-ee4ce700-c59f-11e9-8360-38c805a7f113.png)
◎◎ 20190823確認以上正式環境內容◎◎
