### ISSUE TITLE
【測試環境】Banner新增元件，元件不在畫布正中間

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1486]
Banner新增元件，元件不在畫布正中間
![image](https://user-images.githubusercontent.com/41721950/62608947-6e821400-b933-11e9-98da-c7eb15416daf.png)
PS: 正式環境新增元件，元件會在正中間
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
Banner新增元件會出現在畫布正中間
◎◎ 20190815確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
Banner不管新增任何元件都會出現在"編輯區"正中間。
◎◎ 20190823確認以上正式環境內容◎◎
