### ISSUE TITLE
【問題】修改畫布尺寸若未切換畫布，新增元件會超出畫布

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1487]
step1.『+新增畫布』尺寸先設定2000x2000，新增的元件會在「860x920的位置」
step2.修改『畫布設定的尺寸』為200x200，新增的元件仍然出現在「860x920的位置」
![image](https://user-images.githubusercontent.com/41721950/62609386-3fb86d80-b934-11e9-8748-06ff9a20f421.png)
暫解：若切換左手邊的畫布管理列表，新增的元件就會出現在畫布的位置
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
修改畫布尺寸後，新增元件會出現在畫布範圍中
◎◎ 20190821確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
不論如何調整畫布尺寸，新增元件皆會出現在"編輯區"的正中間。
◎◎ 20190823確認以上正式環境內容◎◎
