### ISSUE TITLE
[測試環境]mgm專屬連結沒有縮網址

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1488]
mgm的專屬連結在編輯頁預設是縮網址狀態。
![image](https://user-images.githubusercontent.com/49626114/62668329-0fb5ac80-b9be-11e9-982f-a37790ffd675.png)
但是發佈後的專屬連結沒有縮網址。(如紅框)
![專屬連結沒有縮網址](https://user-images.githubusercontent.com/49626114/62668445-74710700-b9be-11e9-833a-eff4650ec322.png)

**Comment by AnitaRyzo** [comment]
勾選『專屬連結縮網址』，但網址仍然未縮短
![image](https://user-images.githubusercontent.com/41721950/63075137-2a11fc00-bf63-11e9-870f-3be36d88afce.png)
◎◎ 20190815確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
勾選『專屬連結縮網址』，網址已縮短
![image](https://user-images.githubusercontent.com/41721950/63077341-8b899900-bf6a-11e9-983a-055b16e2f346.png)
◎◎ 20190815確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![1488](https://user-images.githubusercontent.com/49626114/63564868-5f3cd080-c599-11e9-8dcf-bb9759dc9bb3.png)
◎◎ 20190823確認以上正式環境內容◎◎
