### ISSUE TITLE
[問題]互動元件的匯入序號內文格式錯誤也可以上傳

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1489]
設定表格如下圖 : 
1.表格1的第一欄有中文字。(黃框)
2.表格2的最後一欄有中文字。(紅框)
![匯入序號表格](https://user-images.githubusercontent.com/49626114/62851123-b203c600-bd17-11e9-934b-002632217358.png)
操作步驟如下 : 
1.第一次匯入表格1的檔案時會跳出提示訊息。(如下圖)
2.第二次改成匯入表格2的檔案，此時也會跳出提示訊息。(如下圖)
![1312-1](https://user-images.githubusercontent.com/49626114/62851981-99e17600-bd1a-11e9-9e2e-73dc4de806de.PNG)
3.第三次再匯入表格1的檔案，卻能夠成功匯入。
![匯入表格1](https://user-images.githubusercontent.com/49626114/62851833-0b6cf480-bd1a-11e9-89e1-60efe571857c.png)

**Comment by AnitaRyzo** [comment]
依照上述方法操作第一二步驟，目前未出現錯誤狀況
◎◎ 20190815確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述方法操作，不符合格式的檔案皆會跳出提示訊息，目前未再出現錯誤狀況。
◎◎ 20190823確認以上正式環境內容◎◎
