### ISSUE TITLE
【測試環境】信件通知移除帳號若未選取，會出現錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1490]
『信件通知名單』若未選取名單，直接按下「移除帳號」
![image](https://user-images.githubusercontent.com/41721950/62910187-268b4300-bdb2-11e9-9b37-7cecd5f1bfa4.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/62910195-2d19ba80-bdb2-11e9-9994-1d3de8a201f9.png)
請問可否未選取名單，就先鎖住『確認』按鈕??
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
未選取名單，就先鎖住『移除帳號』按鈕
![image](https://user-images.githubusercontent.com/41721950/63069743-c085f380-bf4a-11e9-97d4-3f2c80e619aa.png)
◎◎ 20190815確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
未選取名單時，會鎖住"移除帳號"按鈕。(如黃框)
![1490](https://user-images.githubusercontent.com/49626114/63563510-ef781700-c593-11e9-9868-96f63ef96a08.png)
◎◎ 20190823確認以上正式環境內容◎◎
