### ISSUE TITLE
【測試環境】電子申請書的電子簽名失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1491]
電子申請書的電子簽名無法開啟手寫視窗
![image](https://user-images.githubusercontent.com/41721950/62911064-859e8700-bdb5-11e9-834b-58cd6761901d.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/62911077-8e8f5880-bdb5-11e9-8b3f-045e8d6f74aa.png)
PS:正式環境無此問題
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
電子申請書的電子簽名可以使用
![image](https://user-images.githubusercontent.com/41721950/63070741-02189d80-bf4f-11e9-9278-025f8496d8cf.png)
◎◎ 20190815確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
電子簽名已可正常使用。
![image](https://user-images.githubusercontent.com/49626114/63561570-0109f080-c58d-11e9-8d09-30199be7fc41.png)
◎◎ 20190823確認以上正式環境內容◎◎
