### ISSUE TITLE
表單多行文字

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1492]
多行文字
我填了兩行的文字
在後台結果只有第一行
![image](https://user-images.githubusercontent.com/10150807/62912923-a74f3c80-bdbc-11e9-8d61-efc8ab0bd038.png)
![image](https://user-images.githubusercontent.com/10150807/62912927-b0400e00-bdbc-11e9-8710-b494d6c6c5b5.png)
![image](https://user-images.githubusercontent.com/10150807/62912944-b9c97600-bdbc-11e9-9314-b12934df25df.png)

**Comment by AnitaRyzo** [comment]
後台有顯示多行文字
![image](https://user-images.githubusercontent.com/41721950/63071376-a3a0ee80-bf51-11e9-98ef-fe2dfd751aa2.png)
◎◎ 20190815確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
表單後台&下載檔案皆會顯示多行文字內容
![image](https://user-images.githubusercontent.com/49626114/63561379-542f7380-c58c-11e9-85d2-fe66301f7935.png)
◎◎ 20190823確認以上正式環境內容◎◎
