### ISSUE TITLE
【問題】移動後複製的提示頁會被自動刪除

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1494]
step1.原始設定五個提示頁
![image](https://user-images.githubusercontent.com/41721950/63007572-7998ef00-beb3-11e9-804e-d2e37fb68d37.png)
step2.移動提示頁(e5)的順序並複製移動的提示頁(e52)
![image](https://user-images.githubusercontent.com/41721950/63007527-60903e00-beb3-11e9-92cd-bf7c6836af38.png)
問題1：『連結設定』的提示頁順序未依照編輯區
問題2：移動後複製的提示頁未顯示，且「提示頁區」關閉開啟後，移動後複製的提示頁會消失
![image](https://user-images.githubusercontent.com/41721950/63007670-afd66e80-beb3-11e9-9cd7-3139e2f0e275.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
問題1解決：『連結設定』的提示頁順序已依照編輯區
問題2解決：移動後複製的提示頁會留存
![image](https://user-images.githubusercontent.com/41721950/63412274-000c7e00-c42a-11e9-9862-869391c1d186.png)
◎◎ 20190821確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![1494](https://user-images.githubusercontent.com/49626114/63561004-e46cb900-c58a-11e9-8f31-c877f5c93be5.png)
◎◎ 20190823確認以上正式環境內容◎◎
