### ISSUE TITLE
【問題】按鈕的連結功能無法完全關閉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1495]
當『連結設定』開啟時，有連結功能的元件才會出現👆指標
![image](https://user-images.githubusercontent.com/41721950/63072219-31320d80-bf55-11e9-9350-00b50871204c.png)
但按鈕元件不論是否開啟『連結設定』，都會出現👆指標
「頁面與提示」的功能在關閉『連結設定』時，仍然會生效
![image](https://user-images.githubusercontent.com/41721950/63072198-12337b80-bf55-11e9-9770-f26800403d57.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
按鈕元件不論是否開啟『連結設定』，都會出現👆指標，關閉『連結設定』也不會在連結。
◎◎ 20190821確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
按鈕元件關閉連結設定後，不會再執行連結動作。
不論是否開啟連結設定，按鈕元件都會出現手指圖案的滑鼠游標。
◎◎ 20190823確認以上正式環境內容◎◎
