### ISSUE TITLE
【測試環境】EDM的背景圖片被刪但未點選背景顏色，背景應顯示的畫面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1496]
勾選『背景圖片』時，會像橘框處出現預設的「灰底圖片」
![image](https://user-images.githubusercontent.com/41721950/63234797-65654100-c269-11e9-8a54-2e40027685d5.png)
未設定「當列的背景顏色」且對已存在的『背景圖片』點選『刪除』
![image](https://user-images.githubusercontent.com/41721950/63234579-6b0e5700-c268-11e9-93ae-417ec3b0d7b5.png)
第一時間會出現「當列的背景顏色」
![image](https://user-images.githubusercontent.com/41721950/63234541-3ac6b880-c268-11e9-93b1-2a5a60c9039b.png)
若此時「試寄」郵件或「輸出檔案」，都會顯示「當列的背景顏色」
![image](https://user-images.githubusercontent.com/41721950/63234626-af99f280-c268-11e9-8502-3ad7b73e5713.png)
但若對其中的元件執行刪除，或是跳出此專案，會回復到原始預設的勾選『背景圖片』就出現「灰底圖片」的狀態。「試寄」郵件或「輸出檔案」也會顯示此畫面。
![image](https://user-images.githubusercontent.com/41721950/63234690-01427d00-c269-11e9-9248-abdcc67fc970.png)
問題：是否應該顯示一致的畫面?
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
「當列的背景顏色」設定如下
![image](https://user-images.githubusercontent.com/41721950/63408841-7c9b5e80-c422-11e9-8168-5065b05afac9.png)
刪除圖片，就會出現「當列的背景顏色」
![image](https://user-images.githubusercontent.com/41721950/63408794-68eff800-c422-11e9-9484-40e4ac4810e0.png)
◎◎ 20190821確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
刪除背景圖片後，就會依照設定的當列背景顏色來呈現。
![1496](https://user-images.githubusercontent.com/49626114/63559462-4a097700-c584-11e9-83d0-9aa6de7637e0.png)
◎◎ 20190823確認以上正式環境內容◎◎
