### ISSUE TITLE
[問題]套版中表單&互動元件的連結跳轉無預設文字，造成按鈕消失。

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1497]
套版中一般表單&互動元件的連結跳轉設定原本預設的文字消失，若沒有輸入跳轉連結文字則發佈後不會有跳轉的按鈕。
(紅框是沒有預設文字的情況，黃框是有預設文字的情況)
![跳轉連結預設消失](https://user-images.githubusercontent.com/49626114/63310995-59dc4d80-c32f-11e9-9732-9edbaff50585.png)
![跳轉按鈕](https://user-images.githubusercontent.com/49626114/63311711-8e510900-c331-11e9-93bd-9d258dd5bc3d.png)

**Comment by AnitaRyzo** [comment]
『連結、頁面、提示』若設定跳轉，按鈕會呈現『完成』，且會在表單完成寄送後兩秒左右自動跳轉；若『連結-開啟新分頁』，則需要編輯連結跳轉設定的文字。
![image](https://user-images.githubusercontent.com/41721950/64577177-452f2a80-d3ae-11e9-8431-9f26ba767eb7.png)
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
『連結、頁面、提示』若設定跳轉，按鈕會呈現『完成』，且會在表單完成寄送後兩秒左右自動跳轉；而『連結-開啟新分頁』，則需要編輯連結跳轉設定的文字，若完全無文字也會有按鈕框如下。
![image](https://user-images.githubusercontent.com/41721950/66034446-d6239c80-e53b-11e9-8ca4-5b8aec6243c6.png)
◎◎ 20191002確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
『連結、頁面、提示』若設定跳轉，按鈕會呈現『完成』，且會在表單完成寄送後兩秒左右自動跳轉；而『連結-開啟新分頁』，則需要編輯連結跳轉設定的文字，若完全無文字也會有按鈕框如下。
![1497](https://user-images.githubusercontent.com/49626114/67057387-e1eda080-f182-11e9-8be0-f91347db524d.png)
◎◎ 20191018確認以上正式環境內容◎◎
