### ISSUE TITLE
【問題】移除複製元件可以跨專案貼上的功能

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1498]
從A專案點選並複製(ctrl+c)元件後
![image](https://user-images.githubusercontent.com/41721950/63566457-dc6b4400-c59f-11e9-8811-181142867961.png)
開啟了B專案
![image](https://user-images.githubusercontent.com/41721950/63566480-f2790480-c59f-11e9-96ee-b218bd8beab6.png)
若執行貼上(ctrl+v)，此元件就會出現在B專案
![image](https://user-images.githubusercontent.com/41721950/63566542-25bb9380-c5a0-11e9-8c37-8de2be39e989.png)
請協助移除此功能，感恩~

**Comment by AnitaRyzo** [comment]
目前已無此特殊能力
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
目前已無此特殊能力
◎◎ 20191017確認以上正式環境內容◎◎
