### ISSUE TITLE
【問題】長頁面外設定元件，跳題表單後的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1501]
設定「長頁面」且畫布外內容是「隱藏」
![image](https://user-images.githubusercontent.com/41721950/63582319-74caee00-c5cb-11e9-9c8f-f3cd5befc268.png)
而畫布內容是『跳題表單』及設定元件在「畫布外內容」(如黃框)
![image](https://user-images.githubusercontent.com/41721950/63582224-451be600-c5cb-11e9-8cb1-e42233c63c09.png)
執行時，一開始不會跑出畫布外內容；但是在表單按了跳題的題目之後...
問題一：畫布外內容就會顯示。
![image](https://user-images.githubusercontent.com/41721950/63583305-55cd5b80-c5cd-11e9-8661-9ccd7554ffd0.png)
問題二：進度條的區域無法顯示
![image](https://user-images.githubusercontent.com/41721950/63583469-a8a71300-c5cd-11e9-83e8-18bffbb59ede.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
跳題後，表單會整個往左移
![image](https://user-images.githubusercontent.com/41721950/64513441-216ed480-d31b-11e9-9f10-4736b2f2a5da.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
畫布外內容不會顯示，進度條會顯示；但跳題後整個表單往左移動
![image](https://user-images.githubusercontent.com/41721950/64513705-b8d42780-d31b-11e9-99df-f511b24ad4b7.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
https://ac1.ryzoweba.com
此問題再次出現了...
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
此問題已被解決，但是會影響到 #1640 。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
無論是表單(一般/序號機/互動)與電子申請書，在跳題後畫布外內容不會顯示，進度條會顯示；但跳題後的題目會顯示在中間，而非置頂。
![image](https://user-images.githubusercontent.com/41721950/69529036-69aca300-0faa-11ea-86fd-482f7e555bf9.png)
◎◎ 20191125確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
表單(一般/序號機/互動)，在跳題後畫布外內容不會顯示，進度條會顯示；而電子申請書在跳題後畫布會小位移。
跳題後的題目會顯示在中間，而非置頂。
◎◎ 20200107確認以上測試環境內容MS SQL◎◎
