### ISSUE TITLE
[問題]在編輯頁中電子申請書受到表單編輯權限連動

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1502]
依照#1464 描述的內容設定權限。
![image](https://user-images.githubusercontent.com/49626114/63664310-9b21a100-c7f8-11e9-9d3f-aa18e55a8d6f.png)
在專案編輯頁裡建立電子申請書元件後，編輯功能依舊受到表單權限的連動會被開啟(如紅框)，在表單管理後台建立電子申請書則沒有編輯權限(如黃框)。
![1464](https://user-images.githubusercontent.com/49626114/63664083-b0e29680-c7f7-11e9-9818-7c332cf43811.png)

**Comment by AnitaRyzo** [comment]
電子申請書的設定在「表單管理後台」與「專案編輯頁」中，皆會依照「帳號編輯權限」。
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
電子申請書的設定在「表單管理後台」與「專案編輯頁」中，皆會依照「帳號編輯權限」。
◎◎ 20191002確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
電子申請書的設定在「表單管理後台」與「專案編輯頁」中，皆會依照「帳號編輯權限」。
◎◎ 20191017確認以上正式環境內容◎◎
