### ISSUE TITLE
【問題】「其他」選項填寫的內容在電子申請書未顯示

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1505]
在電子申請書的「其他」選項填寫內容，但是在資料確認頁&下載PDF檔卻沒有顯示填寫的內容。(如紅框處)
![電子申請書的其他題型未顯示內容](https://user-images.githubusercontent.com/49626114/63903017-8cc4c680-ca3e-11e9-9b63-d346686813c6.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/64502110-e6f34080-d2f6-11e9-8714-be70ff1bebb8.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
「其他」選項填寫的內容在電子申請書會顯示
◎◎ 20191002確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
「其他」選項填寫的內容在電子申請書會顯示。
![1505](https://user-images.githubusercontent.com/49626114/66989905-d1dcaf00-f0f7-11e9-83d8-3ff835c8f6b4.png)
◎◎ 20191017確認以上正式環境內容◎◎
