### ISSUE TITLE
【問題】表單的「其他」選項在複選題刪除未能即時顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1508]
表單的「其他」選項在一開始設定了選項描述(如橘框)
但在按下『X』刪除選項後，「單選題」會立刻出現(如黃框)
但「複選題」要將所有選項刪除後，才會出現「其他」的題型
![image](https://user-images.githubusercontent.com/41721950/63928482-2feaff80-ca82-11e9-8578-2c63955d9597.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
「其他」選項在複選題刪除已可即時顯示
![image](https://user-images.githubusercontent.com/41721950/64500675-bf00de80-d2f0-11e9-91cf-0e4da75ed3d9.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
「其他」選項在複選題刪除已可即時顯示
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
「其他」選項在複選題刪除已可即時顯示
![1508](https://user-images.githubusercontent.com/49626114/66987267-0863fb00-f0f3-11e9-963c-9900f5f25e95.png)
◎◎ 20191017確認以上正式環境內容◎◎
