### ISSUE TITLE
【問題】刪除專案時，「已發布專案」跟「待審核專案」的數字不會即時變動

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1509]
刪除專案時，紅框裡面的數字不會即時變動，需要重整或切換頁面，但是黃框的會即時變動。
![專案數字](https://user-images.githubusercontent.com/49626114/63987376-8865df80-cb0a-11e9-830b-86c8ca565dc0.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/64498061-33358500-d2e5-11e9-996e-f1f3eba83a83.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
刪除專案時，「已發布專案」跟「待審核專案」的數字會即時變動；
但在『專案發佈管理』頁面時，數字未能即時變動。#1542 已設立新issue
◎◎ 20191003確認以上測試環境內容MS SQL◎◎
