### ISSUE TITLE
【問題】同時未勾選「顯示頁面名稱」跟「進度條樣式」，表單顏色應該隱藏

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1511]
當選擇主題樣式包"theme-1"(紅框處)時，
![主題樣式包2](https://user-images.githubusercontent.com/49626114/64005171-6720e580-cb42-11e9-837f-41db9386d534.png)
同時未勾選「顯示頁面名稱」跟「進度條樣式」(黃框處)，表單顏色(紅框處)應該隱藏。
![表單顏色顯示問題](https://user-images.githubusercontent.com/49626114/64000228-dba25700-cb37-11e9-9f74-e7d55effb4ea.png)
已跟 @ryzojudy 確認過。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/64503425-9af7ca00-d2fd-11e9-82ad-55163f91d18a.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
同時未勾選「顯示頁面名稱」跟「進度條樣式」，表單顏色已隱藏
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
同時未勾選「顯示頁面名稱」跟「進度條樣式」，表單顏色已隱藏
![1511](https://user-images.githubusercontent.com/49626114/66986475-963ee680-f0f1-11e9-8867-e7bd07921891.png)
◎◎ 20191017確認以上正式環境內容◎◎
