### ISSUE TITLE
【問題】因修改畫布尺寸而造成的問題

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1512]
1.如下圖所示，修改後的畫布尺寸應為320*472(px)。
![image](https://user-images.githubusercontent.com/49626114/64095735-3df69400-cd92-11e9-9536-e46336aeb8c6.png)

但是專案原本預設的第一個頁面的第一個幻燈片的畫布尺寸是320*480(px)，且開啟長頁面後會有小部分灰色區塊(如紅框處)。其他新增的幻燈片則無此狀況發生，畫布尺寸仍是預設的大小(如黃框處)。
![畫布尺寸](https://user-images.githubusercontent.com/49626114/64096506-739c7c80-cd94-11e9-9eeb-fd8aaccc466e.png)

2.因修改了畫布尺寸，導致資料綁定的「分類切換設定」圖片超出畫布區域。(如紅框處)
![分類切換設定](https://user-images.githubusercontent.com/49626114/64097079-d7737500-cd95-11e9-88c8-3265bc56dcb2.png)

**Comment by AnitaRyzo** [comment]
1.修改後的畫布尺寸應為320*472(px)，但首頁的幻燈片高度尺寸為473(px)
![image](https://user-images.githubusercontent.com/41721950/64506855-a2be6b00-d30b-11e9-8ae5-f947ecba5c8a.png)
2.資料綁定的「分類切換設定」圖片在畫布區域邊界
![image](https://user-images.githubusercontent.com/41721950/64507072-4576e980-d30c-11e9-9feb-fa7121a57912.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/66105088-0c6d2480-e5ed-11e9-8282-65dc1de54e72.png)
![image](https://user-images.githubusercontent.com/41721950/66105247-961cf200-e5ed-11e9-80c5-d161f0a945fe.png)
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
1.修改後的畫布尺寸高為472(px)。
2.資料綁定的「分類切換設定」圖片在畫布區域邊界。
![1512](https://user-images.githubusercontent.com/49626114/66986036-a0acb080-f0f0-11e9-98a9-74380cb6b275.png)
◎◎ 20191017確認以上正式環境內容◎◎
