### ISSUE TITLE
【問題】資料綁定的「分類顯示圖設定」問題

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1514]
問題1. 若圖片的檔名包含空格(如黃框處)，在右邊預覽區域有顯示圖片，但是左邊「分類顯示圖設定」的圖片顯示不出來(紅框處)。
![檔名空格](https://user-images.githubusercontent.com/49626114/64138675-97150500-ce30-11e9-9c7d-f9fb21d855cb.png)
問題2. 當圖片點選刪除後(紅框處)，右邊的預覽區域圖片已移除(如綠框處)，但是左邊的「分類顯示圖設定」圖片依舊存在(如黃框處)，需切換至別的頁面後圖片才會消失。
![圖片刪除後未消失](https://user-images.githubusercontent.com/49626114/64138973-e445a680-ce31-11e9-9a99-02aa38fd6454.png)

**Comment by AnitaRyzo** [comment]
補充：Banner的圖案庫會因圖片的檔名包含空格而未有顯示圖
![image](https://user-images.githubusercontent.com/41721950/64148874-06055480-ce57-11e9-8cf6-796ffb89af09.png)

**Comment by AnitaRyzo** [comment]
1.圖片的檔名包含空格，在資料綁定的「分類顯示圖設定」與Banner的圖片庫已可正確執行
![image](https://user-images.githubusercontent.com/41721950/64583132-77e31e00-d3c2-11e9-87f7-8427f56d6e6b.png)
![image](https://user-images.githubusercontent.com/41721950/64583270-f93ab080-d3c2-11e9-8ae4-881e4323af2d.png)
2.當圖片點選刪除後，右邊的預覽區域圖片與左邊的「分類顯示圖設定」圖片皆會消失
![image](https://user-images.githubusercontent.com/41721950/64583408-57679380-d3c3-11e9-8717-575384daf0b3.png)
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
1.圖片的檔名包含空格，在資料綁定的「分類顯示圖設定」與Banner的圖片庫已可正確執行
2.當圖片點選刪除後，右邊的預覽區域圖片與左邊的「分類顯示圖設定」圖片皆會消失
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
1.圖片的檔名包含空格，在資料綁定的「分類顯示圖設定」與Banner的圖片庫已可正確執行
![1514](https://user-images.githubusercontent.com/49626114/66984489-61309500-f0ed-11e9-9607-726df536a9e0.png)
2.當圖片點選刪除後，右邊的預覽區域圖片與左邊的「分類顯示圖設定」圖片皆會消失
![1514-2](https://user-images.githubusercontent.com/49626114/66984500-68f03980-f0ed-11e9-8d7a-1941624661b7.png)
◎◎ 20191017確認以上正式環境內容◎◎
