### ISSUE TITLE
【問題】抽獎表單內有複選題且設定自動傳送表單，後台的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1515]
若「抽獎類型表單」的表單題型有『複選題』且設定『自動傳送表單』
![image](https://user-images.githubusercontent.com/41721950/64140977-0262d500-ce39-11e9-9501-08a242fa37f1.png)
在「表單管理」點選『表單』後，會不斷LOADING
![image](https://user-images.githubusercontent.com/41721950/64141312-1d821480-ce3a-11e9-8780-082ae13de2f6.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/64141344-43a7b480-ce3a-11e9-94e8-e9716f1ff7a0.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
抽獎表單內有複選題且設定自動傳送表單，已可以正確回傳與下載
![image](https://user-images.githubusercontent.com/41721950/64579049-0ac88c00-d3b4-11e9-8a18-a5d997e07121.png)
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
抽獎表單內有複選題且設定自動傳送表單，已可以正確回傳與下載
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
抽獎表單內有複選題且設定自動傳送表單，已可以正確回傳與下載
![1515](https://user-images.githubusercontent.com/49626114/66982758-7277a280-f0e9-11e9-9336-efa23b956837.png)
◎◎ 20191017確認以上正式環境內容◎◎
