### ISSUE TITLE
【問題】刮刮樂與禮盒在預覽畫面未能正確執行

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1516]
不論是在專案管理的『專案預覽』、專案編輯的『預覽』、審核發佈管理的『預覽』都有相同狀況
![image](https://user-images.githubusercontent.com/41721950/64149487-95f7ce00-ce58-11e9-9cdf-79873170384b.png)
禮盒：中獎未跳出慶祝熊；刮刮樂：未進行刮的動作
![image](https://user-images.githubusercontent.com/41721950/64150412-c3457b80-ce5a-11e9-83cd-f537da284edc.png)
刮刮樂錯誤訊息如下，請參考
![image](https://user-images.githubusercontent.com/41721950/64150623-2fc07a80-ce5b-11e9-8a13-4a6393fc3d7b.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
解決：刮刮樂在瀏覽器更改以下設定之後已可使用
![image](https://user-images.githubusercontent.com/41721950/64154902-50410280-ce64-11e9-9981-d671998b66ef.png)

**Comment by ai015606220** [comment]
[webGL支援度解法](https://zhuanlan.zhihu.com/p/24794967)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/64498811-e358bd00-d2e8-11e9-8901-8a2478157d09.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
所有互動遊戲在預覽畫面皆能正確執行
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
所有互動遊戲在預覽畫面皆能正確執行。
◎◎ 20191017確認以上正式環境內容◎◎
