### ISSUE TITLE
【問題】MGM在Pinterest顯示的錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1517]
『社群分享』可以分享至Pinterest，雖然不清楚分享至Pinterest(只會抓圖社群)的意義
![image](https://user-images.githubusercontent.com/41721950/64161203-d6167b00-ce6f-11e9-98a1-78446fcd2fa9.png)
但在電腦跟手機按分享都會失敗
![image](https://user-images.githubusercontent.com/41721950/64161786-ccd9de00-ce70-11e9-9f42-d974b261eef2.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
看是不是把Pinterest統一移除

**Comment by ryzojudy** [comment]
根據討論過後決定統一拿掉Pinterest
(因為目前分享到pnterest不會顯示畫面的截圖 且目前TA也不是for設計師)

**Comment by Gabe-Liu** [comment]
是要社群分享元件、社群追蹤元件裡的pinterest都移除嗎

**Comment by AnitaRyzo** [comment]
社群分享元件、社群追蹤元件的舊元件會保留，但新元件已無pinterst選項
mgm中的社群分享元件已跟著修改
![image](https://user-images.githubusercontent.com/41721950/65414918-3d986880-de27-11e9-9c18-fe47a8148f29.png)
小註解：舊元件的電腦跟手機按分享仍是失敗，建議使用新元件。
![image](https://user-images.githubusercontent.com/41721950/65415106-a67fe080-de27-11e9-9271-cb4cea9851b3.png)
◎◎ 20190923確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
MGM、社群分享元件、社群追蹤元件的新元件已無pinterst選項
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
社群分享元件(包含MGM的社群分享)、社群追蹤元件的新元件已無pinterst選項。
![1517](https://user-images.githubusercontent.com/49626114/66977728-a77bf900-f0d9-11e9-90b3-1014e57427ce.png)
◎◎ 20191017確認以上正式環境內容◎◎
