### ISSUE TITLE
【問題】EDM文字元件刪除預設內容後出現undefined

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1518]
EDM文字元件在右側編輯框刪除預設內容後出現undefined(如紅框處)
![edm文字出現undefine](https://user-images.githubusercontent.com/49626114/64218875-f12bce00-cef5-11e9-8403-d9e773bca0aa.png)

**Comment by AnitaRyzo** [comment]
文字元件刪除預設內容後是空白的
![image](https://user-images.githubusercontent.com/41721950/64581128-8a0d8e00-d3bb-11e9-8fdb-42a8d2359eb8.png)
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
文字元件刪除預設內容後是空白的
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
文字元件刪除預設內容後是空白的。
![image](https://user-images.githubusercontent.com/49626114/66977460-a1d1e380-f0d8-11e9-8b38-cf0a6c9dc871.png)
◎◎ 20191017確認以上正式環境內容◎◎
