### ISSUE TITLE
【問題】EDM圖片的網頁擷取，無專案截圖的畫面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1519]
EDM圖片的網頁擷取，專案列表未呈現截圖的畫面
![image](https://user-images.githubusercontent.com/41721950/64219822-a90eaa80-cef9-11e9-8cc4-4e687c18efb7.png)
![image](https://user-images.githubusercontent.com/41721950/64219832-b9268a00-cef9-11e9-9841-37b3b37e7c05.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
EDM圖片的網頁擷取，有專案截圖
![image](https://user-images.githubusercontent.com/41721950/64505891-1fe7e100-d308-11e9-9505-3b9ffb79bda2.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
EDM圖片的網頁擷取，有專案截圖
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
EDM圖片的網頁擷取，有專案截圖。
![image](https://user-images.githubusercontent.com/49626114/66977395-56b7d080-f0d8-11e9-8f3b-2fed861b3ac6.png)
◎◎ 20191017確認以上正式環境內容◎◎
