### ISSUE TITLE
【新增按鈕】Dashboard上的新增icon改為一致

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#152]
目前這兩處的新增要換icon
<img width="1680" alt="2018-05-15 1 56 16" src="https://user-images.githubusercontent.com/37163894/40039256-44a2c60e-5848-11e8-9947-aeb5f2d2ccee.png">
<img width="1678" alt="2018-05-15 1 56 27" src="https://user-images.githubusercontent.com/37163894/40039257-451edf50-5848-11e8-8240-89087c964d6d.png">

改為橘框icon的狀態
![1526364108954](https://user-images.githubusercontent.com/37163894/40039371-b9242310-5848-11e8-98c2-072edf7030e8.jpg)

**Comment by Isabella-RYZO** [comment]
待上線
