### ISSUE TITLE
【問題】EDM增刪文字元件，元件內是特定符號出現的問題

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1520]
波浪符號「 ~ 」在刪除網格或是以"拖拉方式"新增元件時，每操作一次就會多出一段\x7e的內容(紅框處)。
![EDM符號被改變](https://user-images.githubusercontent.com/49626114/64221154-6ac7ba00-cefe-11e9-8769-173876324b2c.png)
P.S.已測試的符號有~!@#$%^&*()_+{}|:"<>?-=[]\;',./，。

**Comment by AnitaRyzo** [comment]
目前已無此問題
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
目前已無此問題
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
目前已無此問題
◎◎ 20191017確認以上正式環境內容◎◎
