### ISSUE TITLE
【問題】MGM不重複的填表模式，提示文字有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1521]
mgm設定「分享機制-不重複計算」與「分享模式-填寫表單」
![image](https://user-images.githubusercontent.com/41721950/64225136-b7b28d00-cf0c-11e9-9332-4d2862947921.png)
正確：應該出現『你已幫助過其他朋友』
現在的問題：出現『不存在的邀請碼』
![image](https://user-images.githubusercontent.com/41721950/64225685-052ff980-cf0f-11e9-8b59-5cc688c2ece7.png)
![image](https://user-images.githubusercontent.com/41721950/64230055-3ebc3100-cf1e-11e9-8eae-5424ea735073.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/64662544-69a50880-d47b-11e9-9af0-b7b493481e58.png)
◎◎ 20190911確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
出現『已幫助其他人』的正確訊息
◎◎ 20191004確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
出現『已幫助其他人』的正確訊息
![image](https://user-images.githubusercontent.com/49626114/66977152-5965f600-f0d7-11e9-95e1-9b65c76f5018.png)
◎◎ 20191017確認以上正式環境內容◎◎
