### ISSUE TITLE
【問題】從電腦模式直接預覽，出現黑畫面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1523]
電腦模式直接預覽
![image](https://user-images.githubusercontent.com/41721950/64395100-a3e16500-d08b-11e9-9d95-882b2ffe0dda.png)
等再久都是黑畫面
![image](https://user-images.githubusercontent.com/41721950/64395117-b8256200-d08b-11e9-9436-d0d35078e305.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/64395143-cb383200-d08b-11e9-872e-13d4a38488c9.png)
以上問題請協助處理，感恩

**Comment by AnitaRyzo** [comment]
電腦模式直接預覽，已可正常執行
![image](https://user-images.githubusercontent.com/41721950/64498646-00d95700-d2e8-11e9-86ab-1262e26c6576.png)
◎◎ 20190909確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
電腦模式直接預覽，已可正常執行
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
電腦模式直接預覽，已可正常執行
![image](https://user-images.githubusercontent.com/49626114/66976900-3ab32f80-f0d6-11e9-9371-bba324ea1649.png)
◎◎ 20191017確認以上正式環境內容◎◎
