### ISSUE TITLE
【問題】元件框架設定下有多群組重疊時，有群組會跑位

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1524]
STEP1.『將元件固定』開啟
STEP2. 多個群組重疊
![image](https://user-images.githubusercontent.com/41721950/64400562-68509600-d09f-11e9-8e30-ea47234b8d43.png)
問題：預覽與瀏覽器查看專案時，會有群組跑位
![image](https://user-images.githubusercontent.com/41721950/64400716-080e2400-d0a0-11e9-83ad-949434611ddb.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
元件框架設定下有多群組重疊時，『預覽』或『發布後』群組仍在固定位置
![image](https://user-images.githubusercontent.com/41721950/64583718-9a763680-d3c4-11e9-92d8-af9ae45c2534.png)
![image](https://user-images.githubusercontent.com/41721950/64583696-803c5880-d3c4-11e9-9ca3-ac7d046c61ba.png)
◎◎ 20190910確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
元件框架設定下有多群組重疊時，『預覽』或『發布後』群組仍在固定位置
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
元件框架設定下有多群組重疊時，『預覽』或『發布後』群組仍在固定位置
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
元件框架設定下有多群組重疊時，『預覽』或『發布後』群組仍在固定位置
![image](https://user-images.githubusercontent.com/49626114/66976550-dfcd0880-f0d4-11e9-9dcf-ad186c6ad8df.png)
![image](https://user-images.githubusercontent.com/49626114/66976577-fecb9a80-f0d4-11e9-900b-ef2969e03975.png)
◎◎ 20191017確認以上正式環境內容◎◎
