### ISSUE TITLE
【問題】MGM的網站內嵌，網址識別碼的錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1525]
MGM的網站內嵌APP網址，複製後開啟瀏覽器
![image](https://user-images.githubusercontent.com/41721950/64519863-88928600-d327-11e9-90db-6b241400d239.png)
被分享者可從紀錄中得知自己的『識別碼』，在網頁中輸入識別碼後
![image](https://user-images.githubusercontent.com/41721950/64519922-ab249f00-d327-11e9-8c94-29d1c63d6249.png)
錯誤訊息紅字如下
![image](https://user-images.githubusercontent.com/41721950/64519936-b081e980-d327-11e9-8712-543174b3d4f6.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
測試環境已修正
麻煩創建新活動來測試
舊的沒有辦法

**Comment by AnitaRyzo** [comment]
網站內嵌的「網址識別碼」已正確執行＿
![image](https://user-images.githubusercontent.com/41721950/65669802-c527e680-e076-11e9-906e-6bae2d77cdea.png)
◎◎ 20190926確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
網站內嵌的「網址識別碼」可正確執行
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
網站內嵌的「網址識別碼」可正確執行
![image](https://user-images.githubusercontent.com/49626114/66976173-7dbfd380-f0d3-11e9-98bd-ad22d93cbc17.png)
◎◎ 20191017確認以上正式環境內容◎◎
