### ISSUE TITLE
【問題】自訂選單架構的柵欄式選單失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1526]
自訂選單架構如左圖，無論主選單選甚麼，子選單選了「柵欄式選單」
![image](https://user-images.githubusercontent.com/41721950/64582332-dce94480-d3bf-11e9-9c13-6e32bfda0ce8.png)
在「預覽」或是發布後在瀏覽器，皆未呈現「柵欄式選單」
![image](https://user-images.githubusercontent.com/41721950/64582488-3b162780-d3c0-11e9-9e11-3b16d0573a88.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
.com 好像是正常的??

**Comment by AnitaRyzo** [comment]
柵欄式選單已修復
![image](https://user-images.githubusercontent.com/41721950/65415693-d1b6ff80-de28-11e9-896c-3a9dec28f351.png)
◎◎ 20190923確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
柵欄式選單已正常執行
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
柵欄式選單已正常執行
![1526](https://user-images.githubusercontent.com/49626114/66975732-f6be2b80-f0d1-11e9-8c93-f1f03934e25d.png)
◎◎ 20191017確認以上正式環境內容◎◎
