### ISSUE TITLE
【問題】其他選項在表單後台跟下載後的內容不符

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1527]
在填寫表單時，選擇其他選項並填寫了內容，在表單後台可以看到填寫的內容(紅框處)，但是下載表單後卻只有顯示"其他"，與表單後台呈現的內容不符。
![其他選項問題](https://user-images.githubusercontent.com/49626114/64582377-04401180-d3c0-11e9-8f4e-24f36522c61e.PNG)
p.s. 客戶希望後台看到內容能夠跟下載的檔案呈現內容一致。

**Comment by AnitaRyzo** [comment]
其他選項在表單後台跟下載後的內容相符
![image](https://user-images.githubusercontent.com/41721950/66196532-4e6c9800-e6cb-11e9-819e-d1925356847d.png)
◎◎ 20191004確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
其他選項在表單後台跟下載後的內容相符
![image](https://user-images.githubusercontent.com/49626114/66975195-574c6900-f0d0-11e9-9544-ba6e96dfdd7b.png)
◎◎ 20191017確認以上正式環境內容◎◎
