### ISSUE TITLE
【專案複製的Bug】專案複製後有些文字會跑版

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#153]
專案複製後文字會跑版

複製後打開的畫面
<img width="1678" alt="2018-05-15 2 08 27" src="https://user-images.githubusercontent.com/37163894/40039581-7e24c2f0-5849-11e8-9919-3580b918ff8a.png">

Eating製作時的畫面
<img width="259" alt="2018-05-15 2 08 52" src="https://user-images.githubusercontent.com/37163894/40039609-9b604e7a-5849-11e8-93cb-f7c97542b395.png">

**Comment by ai015606220** [comment]
這個問題是因為文字框的大小拉得剛剛好，然後因作業系統、瀏覽器對字型大小的定義各有差異，因此讓整串文字的長度不同造成斷行

**Comment by Gabe-Liu** [comment]
待確認

**Comment by Gabe-Liu** [comment]
暫時關閉
