### ISSUE TITLE
【問題】編輯模式同時存在兩個，新增元件未能出現在提示頁

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1533]
有編輯模式的元件：輪播區塊、收縮區塊、頁籤皆有此問題
步驟一：進入編輯模式
![image](https://user-images.githubusercontent.com/41721950/65303321-4a5f5700-dbb0-11e9-9338-1d59a212fba2.png)
步驟二：『新增提示』但不編輯橘框的提示名稱
![image](https://user-images.githubusercontent.com/41721950/65303486-c5c10880-dbb0-11e9-9d6d-5ec949430041.png)
問題：同時存在兩個編輯模式，若新增元件，元件會坐落在「非提示頁」中
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
按下『+新增提示』後，會立刻關閉原先的『編輯模式』，進入『提示編輯模式』
◎◎ 20191004確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
按下『+新增提示』後，會立刻關閉原先的『編輯模式』，進入『提示編輯模式』
◎◎ 20191017確認以上正式環境內容◎◎
