### ISSUE TITLE
【問題】跨帳號查看專案數據後，團隊點的數量錯誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1534]
根據以下步驟會發生此狀況：
1.當帳號有多個團隊時，在團隊管理裡面可以看到紅框處的捲軸有數個點點，在滑動選擇團隊時透過點點數量可以清楚知道團隊的大概數量。
![點點數量多](https://user-images.githubusercontent.com/49626114/65310847-c57d3900-dbc1-11e9-9396-e4f09ac20ebd.png)
2.點選「跨帳號專案管理」查看專案。
![跨帳號查看專案](https://user-images.githubusercontent.com/49626114/65311086-36245580-dbc2-11e9-8f82-4817489253e3.png)
3.此時的團隊捲軸依舊有多個點點(黃框處)，再點選查看數據。
![查看數據](https://user-images.githubusercontent.com/49626114/65311524-180b2500-dbc3-11e9-834f-808cad926b19.png)
4.接著按左上角的返回鍵(黃框處)。
![專案畫面的點點](https://user-images.githubusercontent.com/49626114/65311894-fe1e1200-dbc3-11e9-95ca-24961a79ea4e.png)
5.返回到上一頁的專案畫面後，此時的團隊捲軸只剩下一個點點(紅框處)。
![返回後點點只剩一個](https://user-images.githubusercontent.com/49626114/65311271-9915ec80-dbc2-11e9-89a5-20e7ad423007.png)

**Comment by AnitaRyzo** [comment]
團隊捲軸會保持點點數量
◎◎ 20191004確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
團隊捲軸會保持點點數量
◎◎ 20191017確認以上正式環境內容◎◎
