### ISSUE TITLE
【問題】最高權限者的團隊相關權限設定有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1535]
帳號管理-團隊管理-帳號編輯
![image](https://user-images.githubusercontent.com/41721950/65401517-2fccee00-ddfb-11e9-9b1f-3b2d7d11d0f8.png)
若開啟『管理者後台』的『團隊管理』，
![image](https://user-images.githubusercontent.com/41721950/65401607-fb0d6680-ddfb-11e9-9230-d9d3351cebb1.png)
按下『帳號編輯』時，如下畫面只可編輯『階層』
![image](https://user-images.githubusercontent.com/41721950/65401617-08c2ec00-ddfc-11e9-8743-3209bc3a816e.png)
若增加開啟『管理者後台』的『最高權限者』
![image](https://user-images.githubusercontent.com/41721950/65401634-2abc6e80-ddfc-11e9-9d8c-b18c1c2b8c15.png)
如下畫面除了『階層』之外，還增加開啟『權限管理』的項目
![image](https://user-images.githubusercontent.com/41721950/65401779-e1205380-ddfc-11e9-9150-9ef6c783e6b6.png)
但若編輯了『權限管理』的項目，再按下『完成』；設定的權限未被寫入，後台資料如下
![image](https://user-images.githubusercontent.com/41721950/65401731-943c7d00-ddfc-11e9-9db1-16a575fb180e.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
開啟『管理者後台』的『最高權限者』已不會連動影響『團隊相關』的權限
◎◎ 20191005確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
開啟『管理者後台』的『最高權限者』已不會連動影響『團隊相關』的權限
◎◎ 20191016確認以上正式環境內容◎◎
