### ISSUE TITLE
【問題】套版管理主題的標籤是否至少一個?

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1537]
『套版管理』在設立主題時
![image](https://user-images.githubusercontent.com/41721950/65741600-2acfad80-e11f-11e9-8bb9-91281b96898c.png)
有一個小防呆是必須選擇至少一個『標籤』，才能按下『完成』；
問題：但若重複點選『標籤』，標籤就會被取消，但『完成』仍可操作。
![image](https://user-images.githubusercontent.com/41721950/65741544-f52ac480-e11e-11e9-8422-56b0d34bc90a.png)

疑問：為何沒有『標籤』的主題，篩選出來是全部的專案? 
依照標籤篩選模式，未選應該是完全沒有專案(吧?)
![image](https://user-images.githubusercontent.com/41721950/65741802-0e804080-e120-11e9-8fa9-0a6fa87c6763.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
套版管理主題的標籤無須選擇任何一個
![image](https://user-images.githubusercontent.com/41721950/66195710-c0dc7880-e6c9-11e9-9e8b-5d3a2d5f7492.png)
◎◎ 20191004確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
套版管理主題的標籤無須選擇任何一個。
![image](https://user-images.githubusercontent.com/49626114/66902032-84e2d500-f032-11e9-92d7-af013f38d4a2.png)
![1537](https://user-images.githubusercontent.com/49626114/66902169-c07d9f00-f032-11e9-9d0d-2899c9a4ab2c.png)
◎◎ 20191016確認以上正式環境內容◎◎
