### ISSUE TITLE
【問題】輸入註冊過的信箱，註冊按鈕不斷laoding

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1538]
輸入已使用過的信箱再按下註冊按鈕，註冊按鈕會一直呈現laoding的狀態(如下圖紅框處)。
此時再改成輸入未使用過的信箱註冊按鈕仍然不會變回正常狀態，依舊呈現laoding狀態。
![image](https://user-images.githubusercontent.com/49626114/65928898-447c3800-e432-11e9-98e9-35f8f1228e52.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/66197444-fdf63a00-e6cc-11e9-834f-5cafe4aa7802.png)
◎◎ 20191004確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
依照上述步驟，已註冊過會直接跳紅字提示訊息，按鈕會正常呈現。
![image](https://user-images.githubusercontent.com/49626114/66900264-12bcc100-f02f-11e9-8294-786f2ccc730b.png)
且仍可進行新帳號的註冊。
![image](https://user-images.githubusercontent.com/49626114/66900405-53b4d580-f02f-11e9-95a2-95b5929d3800.png)
◎◎ 20191016確認以上正式環境內容◎◎
