### ISSUE TITLE
【問題】社群登入影響QueryString，後台寫入的登入訊息有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1539]
設定『身分驗證』方式時，「社群登入」強制要求至少設定一個；
情境：在「社群登入」勾選『Google』，但最後選擇了『QueryString』時的錯誤狀況
![image](https://user-images.githubusercontent.com/41721950/66024913-b7b3a600-e527-11e9-90bb-c05f16dd768f.png)

step1. 左邊限定Google登入，右邊限定Query String=id登入
![image](https://user-images.githubusercontent.com/41721950/66023920-1deaf980-e525-11e9-9642-8cdfe6f40cf9.png)
step2. 登入Google之後，執行互動遊戲；『互動後台管理』會寫入google社群登入資料
![image](https://user-images.githubusercontent.com/41721950/66024118-9487f700-e525-11e9-8f4e-666981c6656e.png)
step3. 此時若修改網址，讓網址符合「Query String=id登入」
![image](https://user-images.githubusercontent.com/41721950/66027162-e97b3b80-e52c-11e9-9d84-908f9a3b8ec9.png)
問題：可以操作Query String的互動，但寫入後台的是社群的登入資料
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
依照上述步驟，非QueryString的互動，即使按鈕是『開始』也會進入選擇「社群登入」的頁面
![image](https://user-images.githubusercontent.com/41721950/66103613-ea71a300-e5e8-11e9-9422-075eefc1023b.png)
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
依照上述步驟，QueryString『互動後台管理』資料顯示的是正確的。
![image](https://user-images.githubusercontent.com/49626114/66899802-274c8980-f02e-11e9-93be-bd61470a71e4.png)
◎◎ 20191016確認以上正式環境內容◎◎
