### ISSUE TITLE
【提示】預覽時無法滾動

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#154]
> 編輯時例圖

![default](https://user-images.githubusercontent.com/20262208/40040282-39d57f92-584c-11e8-80a5-4a85b146e266.png)

> 預覽時例圖(無法滾動提示)

![default](https://user-images.githubusercontent.com/20262208/40040307-54cad536-584c-11e8-9e83-1b289e8e0850.png)

**Comment by Isabella-Zheng** [comment]
背景設定 開啟 長頁面功能。 已解決

**Comment by Isabella-RYZO** [comment]
👌
