### ISSUE TITLE
【問題】審核發佈區的「已發布專案」跟「待審核專案」的數字不會即時變動

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1542]
#1509 延伸問題
審核發佈區的『專案審核』與『專案發佈』，數字需要重整或切換頁面才能即時變動。
![image](https://user-images.githubusercontent.com/41721950/66102736-f3ad4080-e5e5-11e9-9c0c-b2af129fcced.png)
已上問題請協助修改，感恩~

**Comment by AnitaRyzo** [comment]
審核發佈區的『專案審核』與『專案發佈』，數字已會即時更新
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
審核發佈區的『專案審核』與『專案發佈』，數字已會即時更新。
◎◎ 20191016確認以上正式環境內容◎◎
