### ISSUE TITLE
【問題】mgm網站內嵌的計數方式有誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1543]
目前的執行狀況是分享後獲得驗證識別碼(紅框處)互動後台就會寫入條件已達成；
正確步驟是要進入「輸入識別碼」的頁面之後(黃框處)才能夠算條件已達成。
![image](https://user-images.githubusercontent.com/49626114/66108658-a6d16600-e5f5-11e9-9493-763fe4f596d2.png)
被分享者要到如下頁面輸入識別碼，才能算是『條件達成』
![image](https://user-images.githubusercontent.com/49626114/66109480-53f8ae00-e5f7-11e9-8f52-9615c25e68f1.png)
互動後台管理的觸及人數不正確
![image](https://user-images.githubusercontent.com/41721950/66112444-7261a800-e5fd-11e9-93f4-94892f8683bd.png)
以上事項已與 @ryzojudy 確認過，請協助修改，感謝~

**Comment by AnitaRyzo** [comment]
互動後台管理的觸及人數已正確
![image](https://user-images.githubusercontent.com/41721950/66112490-90c7a380-e5fd-11e9-82a9-8af63f7cc74c.png)
◎◎ 20191003確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
互動後台管理的觸及人數已正確，要進入「輸入識別碼」的頁面才能夠算條件已達成。
![image](https://user-images.githubusercontent.com/49626114/66898321-92489100-f02b-11e9-9b59-b6a684c1f8ac.png)
◎◎ 20191016確認以上正式環境內容◎◎
