### ISSUE TITLE
【測試環境】Banner的元件群組後，多處發生錯誤的狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1545]
當Banner內的『元件群組』時，
問題一：按下『下載』整個畫面會空白
![image](https://user-images.githubusercontent.com/41721950/66187766-1445cb00-e6b8-11e9-8e27-f105f3b425e6.png)
正確版的Banner畫部管理頁狀態
![image](https://user-images.githubusercontent.com/41721950/66187259-fc217c00-e6b6-11e9-9ef2-791fe2cd0507.png)
問題二：畫布管理頁顯示錯誤如下
![image](https://user-images.githubusercontent.com/41721950/66187376-3ab73680-e6b7-11e9-8355-4397a6d36f16.png)
問題三：『預覽』頁面全部的畫布都是空白
![image](https://user-images.githubusercontent.com/41721950/66185756-f7f35f80-e6b2-11e9-9df0-d727136fd664.png)
問題四：在套版管理編輯標籤時顯示空白頁面
![image](https://user-images.githubusercontent.com/41721950/66191915-f8dfbd80-e6c1-11e9-8f34-d9fa73ea2b27.png)

以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
Banner的元件群組後，已可正確執行
1+2：畫布管理頁可正常呈現，也可下載Banner檔案
![image](https://user-images.githubusercontent.com/41721950/66367455-cafebf80-e9c6-11e9-9cdc-5e90b8481e61.png)
3.『預覽』頁面正確顯示
![image](https://user-images.githubusercontent.com/41721950/66367511-1618d280-e9c7-11e9-8afd-3c6b8510f06c.png)
4.『套版管理頁』正確顯示
![image](https://user-images.githubusercontent.com/41721950/66367610-7dcf1d80-e9c7-11e9-92a2-beed3660645c.png)
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
Banner的元件群組後，已可正確執行以上畫面
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
Banner的元件群組後，已可正確執行
1+2：畫布管理頁可正常呈現，也可下載Banner檔案
![image](https://user-images.githubusercontent.com/49626114/66891742-7be70900-f01c-11e9-8f89-735c67645f73.png)
3.『預覽』頁面正確顯示
![image](https://user-images.githubusercontent.com/49626114/66891850-adf86b00-f01c-11e9-8ecb-f5465d92b397.png)
4.『套版管理頁』正確顯示
![image](https://user-images.githubusercontent.com/49626114/66891991-0cbde480-f01d-11e9-9034-1fb4e0891756.png)
◎◎ 20191016確認以上正式環境內容◎◎
