### ISSUE TITLE
【測試環境】Banner與EDM的套版管理未顯示標籤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1546]
Banner的套版管理
![image](https://user-images.githubusercontent.com/41721950/66192483-2842fa00-e6c3-11e9-9f44-eec046e63f9b.png)
EDM的套版管理
![image](https://user-images.githubusercontent.com/41721950/66192462-1a8d7480-e6c3-11e9-8677-159ebb28d96d.png)

正確的套版管理頁面
![image](https://user-images.githubusercontent.com/41721950/66192620-748e3a00-e6c3-11e9-84c4-da6491f3185b.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/66363177-edd5a780-e9b7-11e9-83ca-6e4dfadc8a15.png)
◎◎ 20191008確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
Banner與EDM的套版管理正確顯示標籤

**Comment by cocosu123** [comment]
Banner與EDM的套版管理正確顯示標籤
![1546](https://user-images.githubusercontent.com/49626114/66888297-869ba100-f010-11e9-8326-577fe3545ca0.png)
◎◎ 20191016確認以上正式環境內容◎◎
