### ISSUE TITLE
【問題】EDM的社群分享之twitter開啟的頁面有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1548]
twitter在EDM開啟的頁面是發布列表
![image](https://user-images.githubusercontent.com/41721950/66248806-d13e3300-e75d-11e9-91d4-3714cc6b937d.png)
其他社群分享會開啟撰寫分享的頁面
![image](https://user-images.githubusercontent.com/41721950/66248827-034f9500-e75e-11e9-98f4-689fe0b61c68.png)
專案的社群分享開啟的是撰寫分享的頁面(正確版)
![image](https://user-images.githubusercontent.com/41721950/66248854-490c5d80-e75e-11e9-8509-20e9ce6ef7b8.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
EDM的社群分享之twitter開啟的頁面已正確
![image](https://user-images.githubusercontent.com/41721950/66364348-ea441f80-e9bb-11e9-8488-45b05a3ddec4.png)
◎◎ 20191008確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
EDM的社群分享之twitter開啟的頁面，在「試寄」與「輸出檔案」已正確
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
EDM的社群分享之twitter開啟的頁面，在「試寄」與「輸出檔案」已正確
![image](https://user-images.githubusercontent.com/49626114/66884337-74ffcc80-f003-11e9-979b-604ba1a0fb68.png)
◎◎ 20191016確認以上正式環境內容◎◎
