### ISSUE TITLE
【問題】元件超出收縮區塊畫布區時，編輯框線的錯誤情況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1549]
收縮區塊正常情況：未進入編輯模式時才會有編輯框線(左圖黃框)，進入編輯模式時無法點擊編輯框線(右圖紅框)。
![收縮區塊正常情況](https://user-images.githubusercontent.com/49626114/66248918-4827fb80-e75f-11e9-9a4a-c98bb0f5025a.png)

問題發生情況：
多個元件都有此狀況，情境以圖片元件描述
在編輯模式新增圖片元件，將元件放大超出畫布區時，編輯框線會變成收縮區塊的。
![元件超出收縮區塊(圖層)](https://user-images.githubusercontent.com/49626114/66248609-71468d00-e75b-11e9-8cfe-ba317fa61cf1.png)
若此時新增元件，新增的元件並未會出現在編輯模式的圖層內，而是出現在尚未進入編輯模式的圖層內(紅框處)。
![新增元件(圖層)](https://user-images.githubusercontent.com/49626114/66248924-4fe7a000-e75f-11e9-9061-92e0010c3201.png)

**Comment by AnitaRyzo** [comment]
元件超出收縮區塊畫布區時，不會自動點選至「收縮區塊」
◎◎ 20191008確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
元件超出收縮區塊畫布區時，不會自動點選至「收縮區塊」
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
元件超出收縮區塊畫布區時，不會自動點選至「收縮區塊」
◎◎ 20191016確認以上正式環境內容◎◎
