### ISSUE TITLE
【測試環境】專案的套版管理按完成按鈕沒有反應

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1550]
專案的套版管理按完成按鈕沒有反應
![image](https://user-images.githubusercontent.com/41721950/66250560-f7bc9800-e776-11e9-9982-5c3f8e03d7ca.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
專案的套版管理按完成按鈕已可正確執行
延伸問題已開issue #1555 
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
專案的套版管理按完成按鈕已可正確執行開啟關閉套版
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
專案的套版管理按完成按鈕已可正確執行開啟關閉套版
◎◎ 20191016確認以上正式環境內容◎◎
