### ISSUE TITLE
【問題】mgm「網頁內嵌」模式「不重複多層分享」機制在後台觸及人數計算錯誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1551]
mgm設定「網頁內嵌」模式「不重複多層分享」機制的情況下，在後台的觸及人數計算錯誤(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/66251889-fd6ea980-e787-11e9-86f0-5a2d1dbf64d4.png)
![mgm後台](https://user-images.githubusercontent.com/49626114/66251991-0613af80-e789-11e9-8a02-8abf9cc9191e.png)

**Comment by AnitaRyzo** [comment]
後台計算人數已正確
![image](https://user-images.githubusercontent.com/41721950/66293472-4ace5080-e919-11e9-92d3-dbd6dc47ee6b.png)
但是!!!!
填第一次出現『識別碼重複驗證』
![image](https://user-images.githubusercontent.com/41721950/66293624-a8fb3380-e919-11e9-8f5a-06e60850a1e2.png)
填第二次開始，不管填幾次都出現『成功使用識別碼』
![image](https://user-images.githubusercontent.com/41721950/66293523-66395b80-e919-11e9-83b5-16a7fcb6e7b7.png)
請協助修改，感恩~

**Comment by ryuichl** [comment]
用好了
再麻煩幫忙測試
感恩

**Comment by AnitaRyzo** [comment]
「識別碼的回覆」已顯示正確的訊息
◎◎ 20191007確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
後台計算人數已正確，「識別碼的回覆」也已顯示正確的訊息。
![image](https://user-images.githubusercontent.com/49626114/66883478-b04ccc00-f000-11e9-9dcf-fe3faf405278.png)
◎◎ 20191016確認以上正式環境內容◎◎
