### ISSUE TITLE
【問題】按鈕的空格在編輯區跟預覽發佈頁呈現不同

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1552]
設定內容：
按鈕文字最右邊加上空格+對齊方式選擇靠右對齊
![按鈕空格問題](https://user-images.githubusercontent.com/49626114/66252247-a1a61f80-e78b-11e9-8f5b-7946cf190163.png)
在手機預覽跟發佈頁空格會消失(如紅框)
![按鈕空格手機呈現](https://user-images.githubusercontent.com/49626114/66252404-d9ae6200-e78d-11e9-9b7e-73a5b91889f9.png)
在電腦預覽跟發佈頁皆正常呈現(如下圖)
![按鈕30分鐘預覽](https://user-images.githubusercontent.com/49626114/66252373-64429180-e78d-11e9-8307-e2f60cb22a88.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/66375875-01e1cf00-e9e1-11e9-9dfa-b26077b432b4.png)
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
按鈕的空格在編輯區跟預覽發佈頁呈現相同的空格
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
按鈕的空格在編輯區跟預覽發佈頁呈現相同的空格
![1552](https://user-images.githubusercontent.com/49626114/66882912-b80b7100-effe-11e9-8d02-16fcf8dd1a91.png)
![1552-2](https://user-images.githubusercontent.com/49626114/66882913-b8a40780-effe-11e9-9945-c130d1308181.png)
◎◎ 20191016確認以上正式環境內容◎◎
