### ISSUE TITLE
【問題】獎項名稱在不同手機尺寸顯示時會被卡掉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1553]
當獎項圖片較高時，『獎項名稱』較容易被卡掉，就算有捲軸也不會出現『獎項名稱』
![image](https://user-images.githubusercontent.com/41721950/66288316-4864fa00-e90b-11e9-9547-f1e057856f2d.png)
就算是抽到相同獎項，不同手機螢幕尺寸也會影響顯示內容出現的完整度
![image](https://user-images.githubusercontent.com/41721950/66287276-a859a180-e907-11e9-99d7-7424c30d9952.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
已增加卷軸觀看完整內容
![image](https://user-images.githubusercontent.com/41721950/66375289-a06d3080-e9df-11e9-808a-2f850ebd4054.png)
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
獎項名稱在不同手機尺寸皆會增加卷軸顯示完整獎項名稱
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
獎項名稱在不同手機尺寸皆會增加卷軸顯示完整獎項名稱
![1553](https://user-images.githubusercontent.com/49626114/66882104-abd1e480-effb-11e9-9eca-49d57561150c.png)
![1553-2](https://user-images.githubusercontent.com/49626114/66882545-70381a00-effd-11e9-8a33-69f04f29c603.png)
◎◎ 20191016確認以上正式環境內容◎◎
