### ISSUE TITLE
【測試環境】電子申請書的日期題型未顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1554]
無論是在30分鐘、uat或是發佈後的環境，
「日期題型」做了選擇設定後，先到「下一頁」再回到有「日期題型」這頁
就會發現「日期題型-不論是否有勾選時間」回到『請選擇』
![image](https://user-images.githubusercontent.com/41721950/66366034-abb16380-e9c1-11e9-804c-f5c54dc6b368.png)
雖然在『資料確認頁』寫入的資料是正確的
![image](https://user-images.githubusercontent.com/41721950/66366162-237f8e00-e9c2-11e9-9430-e630bd023121.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
「日期題型-不論是否有勾選時間」皆可完整顯示時間
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
「日期題型-不論是否有勾選時間」皆可完整顯示時間
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
「日期題型-不論是否有勾選時間」皆可完整顯示時間
◎◎ 20191016確認以上正式環境內容◎◎
