### ISSUE TITLE
【測試環境】套版管理的標籤未能完整顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1555]
設立了14個套版管理的標籤
![image](https://user-images.githubusercontent.com/41721950/66370863-369b5980-e9d4-11e9-9ec1-745f24ed4361.png)
但在「套版管理」設定時，卻僅顯示11個
![image](https://user-images.githubusercontent.com/41721950/66370842-26837a00-e9d4-11e9-9518-854b012c28da.png)
正式環境的正確畫面會有捲軸
![image](https://user-images.githubusercontent.com/41721950/66370978-88dc7a80-e9d4-11e9-8a5b-cdd4732ee80e.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
套版管理的標籤已完整顯示
![image](https://user-images.githubusercontent.com/41721950/66380905-e11e7700-e9ea-11e9-8446-0a2cf17edb05.png)
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
套版管理的標籤已完整顯示
◎◎ 20191009確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
套版管理的標籤已完整顯示。
![1555](https://user-images.githubusercontent.com/49626114/66879847-c3589f80-eff2-11e9-916c-c81ad1fde077.png)
◎◎ 20191016確認以上正式環境內容◎◎
