### ISSUE TITLE
【問題】Android手機未能顯示QR code

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1558]
受災實體手機：Samsung S10、HTC U12+
互動遊戲在實體機的『恭喜中獎頁』與『中獎紀錄頁』未能顯示QR code，遠端手機未有此問題
![image](https://user-images.githubusercontent.com/41721950/66886748-07579e80-f00b-11e9-9b67-830066aa0ecd.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
android版本?

**Comment by AnitaRyzo** [comment]
Samsung S10的版本如左，HTC U12+的版本如右
而Samsung A7與Samsung S10同版本，但沒有此問題
![image](https://user-images.githubusercontent.com/41721950/66887551-ecd2f480-f00d-11e9-9466-493ab2550a74.png)

**Comment by ai015606220** [comment]
目前還找不到出錯的原因，但有David的幫忙得到了console.log
![image](https://user-images.githubusercontent.com/10190722/66907422-e6f40800-f03b-11e9-9941-cce0a9c0fcda.png)
![image (1)](https://user-images.githubusercontent.com/10190722/66907437-ea878f00-f03b-11e9-9295-66ec6f6c56a6.png)

會再研究看看，如果真的都無解的話就會考慮換一個qrcode轉換的套件

**Comment by ai015606220** [comment]
![141757](https://user-images.githubusercontent.com/10190722/66990440-c5a52180-f0f8-11e9-9bd5-7ba748ecf1f2.jpg)
來自David的HTC手機截圖

**Comment by AnitaRyzo** [comment]
Android手機-HTC U12+已可完整顯示獎項圖片、獎項名稱、QR code
![image](https://user-images.githubusercontent.com/41721950/66992821-1454ba80-f0fd-11e9-8cd5-873e5a52f517.png)
◎◎ 20191017確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
Android手機-HTC U12+已可完整顯示獎項圖片、獎項名稱、QR code。
![image](https://user-images.githubusercontent.com/49626114/67059207-bcfd2b80-f18a-11e9-9c77-aabc464c4b5f.png)
◎◎ 20191018確認以上正式環境內容◎◎
