### ISSUE TITLE
【問題】iPhone新款手機的轉蛋機超出設計範圍

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1559]
受災手機：iPhone XR與iPhone11
![image](https://user-images.githubusercontent.com/41721950/66887038-315d9080-f00c-11e9-9606-b98a53969f76.png)
在瀏覽器開啟時，偶而會出現轉蛋機的蛋超出設計範圍
![image](https://user-images.githubusercontent.com/41721950/66887099-6964d380-f00c-11e9-90c6-13d8f3f68cc5.png)
一般手機是掉一顆蛋
![image](https://user-images.githubusercontent.com/41721950/66887182-a9c45180-f00c-11e9-88db-a3177ff60100.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
iPhone XR與iPhone11的轉蛋機皆會在規定範圍內運作
◎◎ 20191017確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
iPhone XR與iPhone11的轉蛋機皆會在規定範圍內運作
◎◎ 20191018確認以上正式環境內容◎◎
