### ISSUE TITLE
【專案呈現修正版】套版管理/套版審核/專案審核/專案發佈需加上作者名稱

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#156]
套版管理/套版審核/專案審核/專案發佈需加上作者名稱
請看橘框標記
位址：https://zpl.io/Vxkz79m

**Comment by ai015606220** [comment]
@ryuichl 目前專案的那包資料裡面只有owner id，有建議的方法取得使用者的nickname嗎?

**Comment by ryuichl** [comment]
幫你改了一下
可以在owner 欄位裡面取得
@ai015606220
