### ISSUE TITLE
【問題】表單題目編輯頁的感應區與電子申請書不同

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1565]
此情況發生在一般表單、序號表單、抽獎表單，有多個頁面存在的時候。
以此專案為例：從第一頁要切換到第二頁時，點選題型(紅框)時，整個第二頁會亮起藍綠色邊框(代表點選)；但是右邊的頁面，無論是標題或是題目列表皆未改變(橘框處)，必須要點選黃框的非題型位置，才能夠成功的切換頁面。
![表單編輯頁感應區](https://user-images.githubusercontent.com/49626114/66993090-947b2000-f0fd-11e9-967d-f7063d501d09.png)
而在電子申請書的部分，點選題型會切換整個頁面。

**Comment by AnitaRyzo** [comment]
表單目前感應區已放大，點題型也可成功切換頁面
![image](https://user-images.githubusercontent.com/41721950/68267901-073d4280-008f-11ea-8744-62b265cf17ae.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
表單與電子表單點『題型』可成功切換頁面
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
表單與電子表單點擊『題型』可成功切換頁面
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
表單與電子表單點擊『題型』可成功切換頁面
◎◎ 20191125確認以上正式環境內容 ◎◎
