### ISSUE TITLE
【問題】EDM的社群元件未設定專案或網址的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1571]
當『社群分享』『社群追蹤』未選擇/輸入指定連結時
![image](https://user-images.githubusercontent.com/41721950/67192256-d8379780-f425-11e9-8259-f2fbab183e4d.png)
問題一：『社群分享』依照其他社群設定，預設會開啟登入分享頁；但Linkedin出現錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/67192459-382e3e00-f426-11e9-841a-948b506f7496.png)
問題二：『社群追蹤』無論哪個社群都開啟以下頁面
![image](https://user-images.githubusercontent.com/41721950/67191230-dc62b580-f423-11e9-9899-a220fa435923.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
那是否要讓他沒有設定網址的時候，點擊就是沒反應??

**Comment by AnitaRyzo** [comment]
目前專案的社群追蹤是「重複開啟專案的同一分頁」，但很久以前是開啟「WEBA首頁」

**Comment by ai015606220** [comment]
我是覺得如果空白的話，就是一個空連結(點了不會有反應)比較合理
可能需要請 @ryzojudy 定義一下

**Comment by ryzojudy** [comment]
同意大德的說法~
「社群分享」和「社群追蹤」如果沒有設定任何連結，點擊的話則會沒有反應
麻煩協助變更了 感謝!

**Comment by AnitaRyzo** [comment]
「社群分享」和「社群追蹤」若未設定會直接不能點選
◎◎ 20191101確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
「社群分享」和「社群追蹤」若未設定會直接不能點選，可設定的方式如下
![image](https://user-images.githubusercontent.com/41721950/68558000-a3da5880-0472-11ea-8ee8-50cc59a9bea9.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
「社群分享」和「社群追蹤」若未設定會直接不能點選；
若設定「社群分享」設定的『專案連結』之專案未發佈，Linkedin仍會出現錯誤訊息。
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
「社群分享」和「社群追蹤」若未設定會直接不能點選；
若設定「社群分享」設定的『專案連結』之專案**通過審核但未發佈**，Linkedin仍會出現錯誤訊息。
![image](https://user-images.githubusercontent.com/41721950/69519511-314e9a00-0f95-11ea-8b7f-801d3fb57af2.png)
◎◎ 20191125確認以上正式環境內容 ◎◎
