### ISSUE TITLE
【問題】專案與表單的時間設定修改後的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1574]
日期是直接點選的，而時間的設定如下圖「有輸入點且可以點選往上往下』
![image](https://user-images.githubusercontent.com/41721950/67266688-5f971080-f4e3-11e9-951e-036ffd39e94b.png)
問題一：用電腦輸入數字後，數字不會被寫入
問題二：用電腦輸入數字後，點按『往上往下』會跳回原本的時間當基準點
問題三：字元數量似乎未限制(嘗試輸入200個字元還能繼續輸入)
問題出現在專案所有日期時間中，表單輸入也有此問題
以上問題請協助處理，感恩~

**Comment by qq076qq076** [comment]
將鍵盤編輯功能拿掉 長按箭頭會快速增加或減少數字

**Comment by cocosu123** [comment]
已無法用鍵盤輸入數字，長按箭頭會快速增加或減少數字
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
長按箭頭會快速增加或減少數字
![image](https://user-images.githubusercontent.com/41721950/68454044-61c2d400-0232-11ea-859e-8612c879bbc0.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
專案與表單的時間設定，都是長按箭頭會快速增加或減少數字
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
專案與表單的時間設定，都是長按箭頭會快速增加或減少數字
◎◎ 20191126確認以上正式環境內容 ◎◎
