### ISSUE TITLE
【問題】分類切換設定的圖示顏色未立即變更

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1576]
在資料綁定的分類切換設定中，改變圖示顏色後在右側預覽的地方並未即時變更(紅框)，需要先切換至別的頁面再返回此頁面才會變更(綠框)。
![資料綁定圖示顏色](https://user-images.githubusercontent.com/49626114/67355022-befb2c00-f588-11e9-8665-8bc87f1645dd.png)

**Comment by cocosu123** [comment]
分類切換設定的圖示顏色已立即變更。 
![image](https://user-images.githubusercontent.com/49626114/68558426-3cbda380-0474-11ea-8c24-4efbb947277a.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
分類切換設定的圖示顏色會立即變更
![image](https://user-images.githubusercontent.com/41721950/68566996-deec8400-0492-11ea-8ed7-d4bd8e975a98.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
分類切換設定的圖示顏色會立即變更
![image](https://user-images.githubusercontent.com/41721950/69519995-5ee81300-0f96-11ea-9b60-69ce05a05179.png)
◎◎ 20191125確認以上正式環境內容 ◎◎
