### ISSUE TITLE
【問題】電子申請書的未依照權限開關刪除按鈕

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1578]
電子申請書回覆的刪除權限被關閉時
![image](https://user-images.githubusercontent.com/41721950/67356907-629b0b00-f58e-11e9-8f91-b6d19ffe84e8.png)
仍會出現『刪除』按鈕
![image](https://user-images.githubusercontent.com/41721950/67356380-8eb58c80-f58c-11e9-8e09-4df8841c4185.png)
選取資料按下『刪除』按鈕，資料不會被刪除；而Network顯示「權限不足」
![image](https://user-images.githubusercontent.com/41721950/67356621-4fd40680-f58d-11e9-8447-4335b4d8d466.png)

當電子申請書回覆的刪除被開啟時，未顯示『刪除』按鈕
![image](https://user-images.githubusercontent.com/41721950/67356797-01733780-f58e-11e9-9354-c7ae33d2f71d.png)
結論：電子申請書編輯的刪除權限被連動了，而電子申請書回覆的刪除沒有作用
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
根據上述操作，電子申請書回覆的刪除權限被關閉時，不會再出現『刪除』按鈕(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68558194-61654b80-0473-11ea-82b9-a8975ecdd85c.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
根據上述操作，電子申請書回覆的刪除權限被關閉時，未出現『刪除』按鈕(黃框處)。
![image](https://user-images.githubusercontent.com/41721950/68647964-2853d680-055a-11ea-92fd-9c16fe6f8f71.png)
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
即使將「表單刪除」開啟，「電子申請書」仍會保持關閉「刪除」功能
![image](https://user-images.githubusercontent.com/41721950/69523355-ae324180-0f9e-11ea-8c35-a73fa1d77bed.png)
![image](https://user-images.githubusercontent.com/41721950/69523321-99ee4480-0f9e-11ea-8fc6-aeab11596c61.png)
◎◎ 20191125確認以上正式環境內容 ◎◎
