### ISSUE TITLE
【問題】跨帳號權限的電子申請書依賴表單才會出現列表

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1579]
電子申請書相關權限開啟，但表單管理未開啟
![image](https://user-images.githubusercontent.com/41721950/67362147-04295900-f59d-11e9-8d76-cb9d8d35f52d.png)
→「跨帳號表單管理」未出現
![image](https://user-images.githubusercontent.com/41721950/67361950-92510f80-f59c-11e9-835b-6c5abb369867.png)

當表單管理任一權限開啟(黃框)
![image](https://user-images.githubusercontent.com/41721950/67362007-b6145580-f59c-11e9-8a4c-043a03431b70.png)
→「跨帳號表單管理」才會出現
![image](https://user-images.githubusercontent.com/41721950/67362068-d93f0500-f59c-11e9-8f27-9d5584b20de0.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
根據上述操作，「跨帳號表單管理」已正常出現(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68557798-e3547500-0471-11ea-92c1-41df0175eee5.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
當「申請書相關」開啟任一權限開啟(橘框)，就會出現『跨帳號表單管理』的圖示按鈕
![image](https://user-images.githubusercontent.com/41721950/68645405-eb381600-0552-11ea-82f6-a0982c2fa974.png)
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
當「申請書相關」開啟任一權限開啟(如上圖)，就會出現『跨帳號表單管理』的圖示按鈕。
點選『跨帳號表單管理』後，無論是否有功能會出現「表單+電子申請書」的所有表單列表；電子申請書是橘框，其餘都是表單。
![image](https://user-images.githubusercontent.com/41721950/69523827-c8b8ea80-0f9f-11ea-85e4-00ef07bbf291.png)
◎◎ 20191125確認以上正式環境內容 ◎◎
