### ISSUE TITLE
【問題】序號機在互動後台的表單回覆內容未呈現「其他」選項的答題內容

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1580]
序號機在互動後台的表單回覆內容未呈現「其他」選項的答題內容(紅框處)，但是序號表單在表單管理後台有呈現答題內容(綠框處)。
![序號機其他選項](https://user-images.githubusercontent.com/49626114/67363010-02609500-f59f-11e9-8a62-d529465a7b18.png)

**Comment by AnitaRyzo** [comment]
其他的回覆已顯示
![image](https://user-images.githubusercontent.com/41721950/68281503-c35c3480-00b2-11ea-970c-c5f8c06e051f.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68463622-08669f00-024a-11ea-9867-3b5f1779b952.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/68576417-051d1e80-04a9-11ea-9570-893efee4135b.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/69593708-fa2fc580-1034-11ea-9ecc-bb0211874240.png)
◎◎ 20191126確認以上正式環境內容◎◎
