### ISSUE TITLE
【問題】互動元件若使用「選擇連接元件」，活動設定區跑版

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1581]
互動元件設定時，若有設定「活動名稱」內的任一欄位
![image](https://user-images.githubusercontent.com/41721950/67537007-3907ee00-f70c-11e9-986f-0eeaec921b46.png)
無論是新增或是複製元件，『選擇連接專案內元件』後，設定處完全跑版...
![image](https://user-images.githubusercontent.com/41721950/67537065-6ce31380-f70c-11e9-84c2-660405a76f2b.png)
錯誤訊息如下請參考
![image](https://user-images.githubusercontent.com/41721950/67537163-c6e3d900-f70c-11e9-87c3-f0bc86b507fe.png)
以上問題請協助處理，感恩~
PS: 不是每次都出現，若要查看請先告知；測試環境未有此問題。

**Comment by AnitaRyzo** [comment]
目前可以正常執行「選擇連接元件」
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
目前可以正常執行「選擇連接元件」與「啟用連接元件」
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
目前可以正常執行「選擇連接元件」與「啟用連接元件」
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
目前可以正常執行「選擇連接元件」與「啟用連接元件」。
◎◎ 20191126確認以上正式環境內容◎◎
