### ISSUE TITLE
【問題】未中獎的狀態提示頁設定未能依照指示獎項圖片

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1584]
狀態提示頁的『未中獎』頁面，設定開啟『獎項圖片』
無論是編輯區或實際在瀏覽器執行都未顯示圖片
![image](https://user-images.githubusercontent.com/41721950/67648523-e4b17800-f970-11e9-9d25-3898b7fb1887.png)
確定「設定獎項」中，有關閉『中獎』的獎項
![image](https://user-images.githubusercontent.com/41721950/67648624-36f29900-f971-11e9-88e9-1fb90bc4f1be.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
設定區有出現獎項圖片
![image](https://user-images.githubusercontent.com/41721950/68285772-d96df300-00ba-11ea-97f2-51580a7a8e7a.png)
但實際執行時未有圖片出現
![image](https://user-images.githubusercontent.com/41721950/68285864-028e8380-00bb-11ea-8a5e-4d894132b557.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
編輯區、預覽、電腦版、手機版(iPhone、Samsung7)皆有出現未中獎的獎項圖片
![image](https://user-images.githubusercontent.com/41721950/68355295-c6eeca80-0149-11ea-9458-cf77d9154bb4.png)
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
專案列表與編輯區的預覽、電腦版、手機版(iPhone、Samsung7)皆有出現未中獎的獎項圖片
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
專案列表與編輯區的預覽、電腦版、手機版(iPhone、Samsung7)皆有出現未中獎的獎項圖片
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
專案列表與編輯區的預覽、電腦版、手機版(iPhone、Samsung7)皆有出現未中獎的獎項圖片
![image](https://user-images.githubusercontent.com/49626114/69592999-c5227380-1032-11ea-8128-cc41cdf1a669.png)
◎◎ 20191126確認以上正式環境內容◎◎
