### ISSUE TITLE
【MS SQL】表單在編輯區及管理後台出現的錯誤狀況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1587]
問題1.在專案編輯區按下「建立新表單」(橘框)或是在已有表單的專案中按下「表單管理」(黃框)，都未正常出現『表單設定視窗』，只會跳出一條綠色細線(紅框處)。
![建立新表單錯誤碼](https://user-images.githubusercontent.com/49626114/67664516-c4021600-f9a2-11e9-9b09-ff3ff0f36e6a.png)
![表單管理錯誤碼](https://user-images.githubusercontent.com/49626114/67664539-cd8b7e00-f9a2-11e9-8cb4-061fd55697a1.png)
錯誤訊息如下
![新建表單錯誤碼](https://user-images.githubusercontent.com/49626114/67664622-eeec6a00-f9a2-11e9-91c3-77da868d31e7.PNG)
問題2. 在表單管理後台編輯表單，若表單存在多個專案中(如黃框)，則會顯示「權限不足」無法編輯表單。
![表單權限不足](https://user-images.githubusercontent.com/49626114/67664065-db8ccf00-f9a1-11e9-819e-48d7545228a0.png)

**Comment by cocosu123** [comment]
問題1. 在專案中按下「建立新表單」、「選擇其他表單」、「表單管理」，畫面都已正常呈現。
![1587](https://user-images.githubusercontent.com/49626114/68285542-695f6d00-00ba-11ea-97e8-3e05c3b4af4d.png)
問題2. 在表單管理後台編輯表單，已可正常編輯表單。
![image](https://user-images.githubusercontent.com/49626114/68285640-9d3a9280-00ba-11ea-8cc1-cb7e6869e11c.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
問題1. 在專案中按下「建立新表單」、「選擇其他表單」、「表單管理」，畫面都已正常呈現。
問題2. 在表單管理後台編輯表單，已可正常編輯。
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
問題1. 在專案中按下「建立新表單」、「選擇其他表單」、「表單管理」，畫面都已正常呈現。
問題2. 在表單管理後台編輯表單，已可正常編輯。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1. 在專案中按下「建立新表單」、「選擇其他表單」、「表單管理」，畫面都已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/69591094-9903f400-102c-11ea-8e99-9963bd489484.png)
2. 在表單管理後台編輯表單，已可正常編輯。
![image](https://user-images.githubusercontent.com/49626114/69591125-b0db7800-102c-11ea-8a19-156b0cf28ee6.png)
◎◎ 20191126確認以上正式環境內容◎◎
