### ISSUE TITLE
【建議】選單架構設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#159]
hi
左側的頁面管理，以及右側自動模式下的選單架構設定連動問題

*頁面管理新增或刪減時，選單架構會跟著連動
*選單架構新增修改時，頁面管理不會跟著連動

我個人是覺得既然是自動了，應該都會自動連動
自訂的部分沒有意見

或是這部分尤其他的設計思維，願聞其詳

**Comment by ryuichl** [comment]
我是覺得可以改成選單架構選自動的話
他就不能在那邊新增

**Comment by weilyn** [comment]
我記得之前UX規劃是新增的話，會自動切換為自訂。
但直接限制也不失為個好辦法

**Comment by Samasianspock** [comment]
之前的預想狀態是，只要使用者在”自動模式“新增或刪除任何頁面就會切換到"自訂模式"。
如果在自動模式限制使用者不能新增或刪除的話也許是個好方法，能突顯自訂模式的特色，但有可能會使人困惑，除非他主動切換到自訂模式否則使用者可能會覺得架構設定故障了，再加上目前切換到“自訂模式”時，架構是空白的，因此建議在第一次進入選單架構時，可以在“自訂模式”顯示已經存在的頁面，完全空白會讓人不知所措。
我想維持原先預想的操作方式。

**Comment by Samasianspock** [comment]
經過一番思考後，以下是目前決定的規劃：
選單架構自動：
限制不能新增刪除。頁面的名稱在預設時跟頁面管理相同，可以讓使用者更改名稱。
不可刪除、不可複製任何頁面，沒有新增按鈕。
選單架構自訂：切換到自訂時一樣會有預設的頁面，可以使用新增按鈕新增、複製和刪除頁面以及新增和刪除子層。
（自動與自訂）
![default](https://user-images.githubusercontent.com/37531593/42269843-e51f047c-7fb1-11e8-85b6-002acc43dc53.jpg)
（自動的預設名稱與頁面相同 但仍可以更改）
<img width="492" alt="default" src="https://user-images.githubusercontent.com/37531593/42269873-f6061a28-7fb1-11e8-8e9e-15d34aee22ed.png">

必須清楚地讓使用者了解，選單架構是選單的呈現樣式，並不能新增或刪除專案的頁面，若需設定頁面請前往頁面管理。

有個題外話，由於選單架構也是與選單相關，因此點選選單元件時，選單架構設定或許可以一起出現？
使用者還是可以在未選擇選單是去單獨開啟選單架構。因為目前是需要使用自行去點開。 以上，感激！
![default](https://user-images.githubusercontent.com/37531593/42269988-528a19b6-7fb2-11e8-9677-eafb4a83bec4.jpg)
