### ISSUE TITLE
【MS SQL】資料綁定中分類切換設定的畫面呈現問題

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1592]
問題1.
分類切換設定的樣式選擇按鈕文字是英文(紅框處)。
![樣式選擇按鈕](https://user-images.githubusercontent.com/49626114/67820805-ac877200-faf5-11e9-8fba-9a01304d8610.png)
問題2.
在正式環境操作，分類切換的圖示應該要呈現在右邊預覽畫面(如綠框)。
分類切換的圖示未呈現在右邊預覽畫面中(紅框處)。
![分類切換圖未呈現](https://user-images.githubusercontent.com/49626114/67821388-c2963200-faf7-11e9-987c-f0559c05693f.png)
問題3.
上圖是在正式環境操作的正常畫面。
分類切換設定的選單狀態選擇『展開』，此處的畫面內容跑掉(下圖)。
![分類切換設定畫面](https://user-images.githubusercontent.com/49626114/67821827-5a485000-faf9-11e9-9760-d44846d7a56a.png)

**Comment by cocosu123** [comment]
問題1. 分類切換設定的樣式選擇按鈕已恢復正常。
![image](https://user-images.githubusercontent.com/49626114/68284022-9fe7b880-00b7-11ea-950a-7365cbfee7bf.png)
問題2. 分類切換的圖示已正常呈現在右邊預覽畫面中(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/68284120-d8879200-00b7-11ea-91a9-649830bac20a.png)
問題3. 分類切換設定的選單狀態選擇『展開』，此處的畫面已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/68284296-2dc3a380-00b8-11ea-9a56-8aa940251871.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
問題1. 分類切換設定的樣式選擇按鈕
![image](https://user-images.githubusercontent.com/41721950/68456603-2e377800-0239-11ea-8afc-4f7a82e4b627.png)
問題2. 分類切換的圖示已正常呈現在右下角的預覽畫面中(橘框)。
問題3. 分類切換設定的選單狀態選擇『展開』(黃框)，此處的畫面已正常呈現。
![image](https://user-images.githubusercontent.com/41721950/68458012-ace1e480-023c-11ea-8c0a-141a49729fef.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
問題1. 分類切換設定的樣式選擇按鈕
問題2. 分類切換的圖示已正常呈現在右下角的預覽畫面中(橘框)。
問題3. 分類切換設定的選單狀態選擇『展開』(黃框)，此處的畫面已正常呈現。
![image](https://user-images.githubusercontent.com/41721950/68567975-47d4fb80-0495-11ea-8ed6-9eea24e71e15.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/69520869-a53e7180-0f98-11ea-83c4-4113fc7f1441.png)
◎◎ 20191125確認以上正式環境內容 ◎◎
