### ISSUE TITLE
【MS SQL】元件複製後開啟框架固定，元件會消失

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1595]
被複製或複製而來的元件，會因為『框架設定』勾選而消失
![image](https://user-images.githubusercontent.com/41721950/67910735-d3f64180-fbbe-11e9-8a57-56d74ac0743a.png)
以下範例以裝飾圖案為例
三角形為最原始的元件，正方形與圓形是複製貼上的
![image](https://user-images.githubusercontent.com/41721950/67911118-4fa4be00-fbc0-11e9-84f7-7dbd3cf149ed.png)
針對「三角形裝飾圖案」開啟『框架設定』並勾選「固定到所有分頁」or「固定到所有幻燈片」
![image](https://user-images.githubusercontent.com/41721950/67911175-95fa1d00-fbc0-11e9-8a26-032da70bcf8f.png)
切換至其他幻燈片再切回後，會發現只剩下設定框架的元件
![image](https://user-images.githubusercontent.com/41721950/67911283-f1c4a600-fbc0-11e9-8170-b9059db2d36c.png)
而從『圖層設定』會發現這些元件全部被連動了
![image](https://user-images.githubusercontent.com/41721950/67911326-20db1780-fbc1-11e9-8c28-1ca64b410640.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
被複製或複製而來的元件，已不會因為『框架設定』勾選而消失
『圖層設定』也不會將元件全部連動
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
被複製或複製而來的元件，已不會因為『框架設定』勾選而消失
『圖層設定』也不會將元件全部連動
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
被複製或複製而來的元件，已不會因為『框架設定』勾選而消失。
『圖層設定』也不會將元件全部連動。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
被複製或複製而來的元件，已不會因為『框架設定』勾選而消失。
『圖層設定』也不會將元件全部連動。
◎◎ 20191125確認以上正式環境內容◎◎
