### ISSUE TITLE
【MS SQL】互動元件內的表單未正常呈現

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1596]
在序號機、互動遊戲、MGM裡的表單未正常呈現，只有關閉表單的圖示，卻沒有表單內容。(如下圖紅框處)
![互動元件表單消失](https://user-images.githubusercontent.com/49626114/67918449-4d019300-fbd7-11e9-8600-86210f8337b6.png)

**Comment by AnitaRyzo** [comment]
序號機、互動遊戲、MGM裡的表單已正確顯示表單
![image](https://user-images.githubusercontent.com/41721950/68278842-26e36380-00ad-11ea-82d1-d47b2055972c.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
序號機、互動遊戲、MGM裡的表單已正確顯示表單
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
序號機、互動遊戲、MGM裡的表單已正確顯示表單
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
序號機、互動遊戲、MGM裡的表單已正確顯示表單。
◎◎ 20191125確認以上正式環境內容◎◎
