### ISSUE TITLE
【MS SQL】Banner的預覽圖在多處無畫面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1597]
Banner廣告管理的列表預覽與下載檔案、套版總覽的點擊查看、套版申請的申請套版審核
![image](https://user-images.githubusercontent.com/41721950/67925023-1171c380-fbed-11e9-8267-ba30c568e6d8.png)
Banner編輯區的預覽
![image](https://user-images.githubusercontent.com/41721950/67925387-28fd7c00-fbee-11e9-9f97-d3be57809ca8.png)
Banner套版審核與套版管理的預覽
![image](https://user-images.githubusercontent.com/41721950/67925404-3adf1f00-fbee-11e9-8b38-61cdd58e17cd.png)
目前找到以上位置皆未出現預覽畫面
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
目前除了已新增的issue『套版審核與套版管理的預覽』之外，其他畫面已顯示
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
Banner廣告管理的列表預覽與下載檔案、套版總覽的點擊查看、套版申請的申請套版審核皆已正常顯示畫面。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
Banner廣告管理的列表預覽與下載檔案、套版總覽的點擊查看、套版申請的申請套版審核皆已正常顯示畫面。
![image](https://user-images.githubusercontent.com/49626114/69520641-2ba68380-0f98-11ea-8d45-6b1226397e39.png)
◎◎ 20191125確認以上正式環境內容◎◎
