### ISSUE TITLE
【MS SQL】驗證識別碼與兌換獎品的畫面呈現問題

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1598]
問題1.
MGM的驗證識別碼畫面內容變成英文，且驗證會出現錯誤碼。
![image](https://user-images.githubusercontent.com/49626114/67925436-54806680-fbee-11e9-9081-e0ab69858108.png)
![image](https://user-images.githubusercontent.com/49626114/67925444-5cd8a180-fbee-11e9-8c25-b1c7cc2dfddd.png)
問題2.
互動遊戲的兌換獎品畫面內容變成英文。
![image](https://user-images.githubusercontent.com/49626114/67925513-93aeb780-fbee-11e9-91b9-6a560ce46941.png)

**Comment by cocosu123** [comment]
問題1.
MGM的驗證識別碼畫面內容已恢復正常，驗證也會正常執行。
![image](https://user-images.githubusercontent.com/49626114/68283085-dfada080-00b5-11ea-94b9-476420d654e6.png)
![image](https://user-images.githubusercontent.com/49626114/68283300-45019180-00b6-11ea-8309-caa19b41aa04.png)
問題2.
互動遊戲的兌換獎品畫面內容已恢復正常。
![image](https://user-images.githubusercontent.com/49626114/68283806-3071c900-00b7-11ea-9f00-ec0e8b660ee2.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
問題1.MGM的「驗證識別碼」頁面與驗證皆正常執行。
![image](https://user-images.githubusercontent.com/41721950/68465963-71501600-024e-11ea-883e-a7b8d5bd1e45.png)
問題2.互動遊戲的「兌換獎品」頁已正常執行。
![image](https://user-images.githubusercontent.com/41721950/68466146-c8ee8180-024e-11ea-95bc-aff690c404d6.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
1. MGM的「驗證識別碼」頁面與驗證皆正常執行。
2. 互動遊戲的「兌換獎品」頁已正常執行。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1. MGM的「驗證識別碼」頁面與驗證皆正常執行。
2. 互動遊戲的「兌換獎品」頁已正常執行。
![image](https://user-images.githubusercontent.com/49626114/69519757-bcc82b00-0f95-11ea-99ca-953e55853701.png)
◎◎ 20191125確認以上正式環境內容◎◎
