### ISSUE TITLE
【MS SQL】圖片剪裁的步驟被忽視

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1599]
上傳圖片後，進行畫布剪裁
![image](https://user-images.githubusercontent.com/41721950/67927303-3832f880-fbf3-11e9-8bbb-b77b149d1c84.png)
從畫布區可知此圖片已完成圖片剪裁
此時按下『上一步』應該回到「未剪裁的圖片」
![image](https://user-images.githubusercontent.com/41721950/67927444-9233be00-fbf3-11e9-96c3-f1655cc35331.png)
但現在卻直接跳未上傳圖片的畫面
![image](https://user-images.githubusercontent.com/41721950/67927576-e474df00-fbf3-11e9-8bc6-7cedf71ef755.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
按『上一步』已回到「未剪裁的圖片」，『下一步』則回到「剪裁的圖片」
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
按『上一步』已回到「未剪裁的圖片」，『下一步』則回到「剪裁的圖片」
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
按『上一步』已回到「未剪裁的圖片」，『下一步』則回到「剪裁的圖片」。
◎◎ 20191125確認以上正式環境內容◎◎
