### ISSUE TITLE
【MS SQL】社群分享與SEO設定的內容被忽視

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1600]
操作步驟如下：
先新增一個元件(以文字元件為範例)，再至社群分享與SEO設定(綠框處)進行操作(以上傳圖片為範例)，接著再按『上一步』，com環境的圖片依然存在，但文字元件消失(紅框處)；io環境則是圖片消失(黃框處)，但文字元件存在。
![發佈設定](https://user-images.githubusercontent.com/49626114/67931131-3ae61b80-fbfc-11e9-85a8-6924578236db.png)

在com環境社群分享與SEO設定的內容不受『上一步』與『下一步』影響，只對畫布區有影響。

**Comment by AnitaRyzo** [comment]
社群分享與SEO設定的內容與『上一步』與『下一步』有互相影響
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
社群分享與SEO設定的內容受『上一步』與『下一步』影響
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
社群分享與SEO設定的內容受『上一步』與『下一步』影響。
◎◎ 20191125確認以上正式環境內容◎◎
