### ISSUE TITLE
【MS SQL】內嵌網頁與程式碼設定值的步驟被忽視

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1602]
內嵌網頁 & 內嵌程式碼的設定值內容步驟皆被忽視，原始設定如下
![image](https://user-images.githubusercontent.com/41721950/67928858-fdcb5a80-fbf6-11e9-93a0-6eb696c29e65.png)
點選『上一步』，會回到元件的上一動作(建立或移動位置)，系統直接刪除元件內的設定值
![image](https://user-images.githubusercontent.com/41721950/67929064-631f4b80-fbf7-11e9-9d14-392767c3d81e.png)
即使點選『下一步』回到應該要有設定值的步驟，依然顯示空白
![image](https://user-images.githubusercontent.com/41721950/67930514-e55d3f00-fbfa-11e9-8ea2-c740e100c36f.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
內嵌網頁 & 內嵌程式碼的設定值內容，不會因『上下一步』就消失
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
內嵌網頁 & 內嵌程式碼的設定值內容，不會因『上下一步』就消失
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
內嵌網頁 & 內嵌程式碼的設定值內容，不會因『上下一步』就消失。
◎◎ 20191125確認以上正式環境內容◎◎
