### ISSUE TITLE
【MS SQL】時間倒數元件沒有預設值

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1603]
時間倒數元件沒有預設值(紅框處)，需先點擊『日期/時間』、『顯示進階設定』或是離開編輯框再點擊一次元件才會出現預設值。
![時間倒數沒有預設](https://user-images.githubusercontent.com/49626114/67930632-22293600-fbfb-11e9-97db-d065114a66a8.png)

**Comment by cocosu123** [comment]
時間倒數元件已有預設值。
![image](https://user-images.githubusercontent.com/49626114/68280701-074e3a00-00b1-11ea-9d06-e29eb3de8b46.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
時間倒數元件已有預設值
![image](https://user-images.githubusercontent.com/41721950/68554080-ed21ac80-0460-11ea-8f9d-dfb5ddecd09f.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
時間倒數元件已有預設值
![image](https://user-images.githubusercontent.com/49626114/68642063-b96d8200-0547-11ea-94d5-25725f86d3d4.png)
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
時間倒數元件已有預設值
![image](https://user-images.githubusercontent.com/49626114/69516589-0bbd9280-0f8d-11ea-98c1-d5ec7373803b.png)
◎◎ 20191125確認以上正式環境內容◎◎
