### ISSUE TITLE
【MS SQL】互動系列元件的設定步驟被忽視

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1604]
互動系列受影響的元件：分享換優惠、序號機、互動的九個遊戲、表單、電子申請書
如下情境以分享換優惠為範例
step1.新增分享換優惠的元件至編輯區
![image](https://user-images.githubusercontent.com/41721950/67931023-03776f00-fbfc-11e9-95b5-e8fcf512798f.png)
step2.選擇分享機制與模式
![image](https://user-images.githubusercontent.com/41721950/67931219-623ce880-fbfc-11e9-8d33-69a22c0373b3.png)
step3.基礎設定後按下『上一步』
![image](https://user-images.githubusercontent.com/41721950/67931300-7ed92080-fbfc-11e9-9ae0-d0aead11a9f1.png)
io環境會回到與『複製元件』相同的初始設定選項
![image](https://user-images.githubusercontent.com/41721950/67931402-b778fa00-fbfc-11e9-8b30-51158eee9fff.png)
但com環境換直接刪除元件
![image](https://user-images.githubusercontent.com/41721950/67931494-e98a5c00-fbfc-11e9-8b05-3713c757aba4.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
互動系列元件的『上一步』不會直接刪除元件
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
互動系列元件的『上一步』不會直接刪除元件
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
互動系列元件的『上一步』不會直接刪除元件。
◎◎ 20191126確認以上正式環境內容◎◎
