### ISSUE TITLE
【MS SQL】獎項匯入序號的提示訊息不會自動關閉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1605]
獎項匯入序號的提示訊息不會自動關閉，必須重新整理頁面才會消失
![image](https://user-images.githubusercontent.com/41721950/67931747-7df4be80-fbfd-11e9-9f3f-34cd055ae25e.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
獎項匯入序號的提示訊息會停留大約2-3秒後就自動關閉。
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
獎項匯入序號的提示訊息會停留大約2-3秒後就自動關閉。
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
獎項匯入序號的提示訊息會停留大約2-3秒後就自動關閉。
◎◎ 20191125確認以上正式環境內容◎◎
