### ISSUE TITLE
【MS SQL】同時複製多個元件後，無法拖移

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1606]
以按鈕元件為例，如下圖同時選取三個按鈕元件
![image](https://user-images.githubusercontent.com/49626114/67932201-67029c00-fbfe-11e9-8ca3-bad2b854ff52.png)
複製貼上後，將元件拖移，由下圖可見只有編輯框線被移動，元件本身並未被移動。
![image](https://user-images.githubusercontent.com/49626114/67932340-b1841880-fbfe-11e9-9273-c7e3add34611.png)
備註：所有元件皆有此狀況發生。

**Comment by cocosu123** [comment]
同時複製多個元件後，已經可以正常將元件拖移。
![image](https://user-images.githubusercontent.com/49626114/68279594-b8070a00-00ae-11ea-8d41-efd18e5d5f16.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
同時複製多個元件後，已經可以正常將元件拖移。
![image](https://user-images.githubusercontent.com/41721950/68553996-7b496300-0460-11ea-9295-9136c15fe817.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
同時複製多個元件後，已經可以正常將元件拖移。
![image](https://user-images.githubusercontent.com/49626114/68640956-3f87c980-0544-11ea-9a81-78c47ecd8096.png)
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
同時複製多個元件後，已經可以正常將元件拖移。
![image](https://user-images.githubusercontent.com/49626114/69516106-a4531300-0f8b-11ea-943c-35ab21d229d2.png)
◎◎ 20191125確認以上正式環境內容◎◎
