### ISSUE TITLE
【MS SQL】專案的『套版管理』之『套版設定』完成按鈕失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1607]
專案的『套版管理』之『套版設定』
![image](https://user-images.githubusercontent.com/41721950/67932271-84376a80-fbfe-11e9-8ff0-5ffb2b9a69dd.png)
輸入域名後的提示訊息為『可以使用』，但怎麼按『完成』按鈕都沒有反應
無論是否為已上傳之套版，所有設定值都無法設定
![image](https://user-images.githubusercontent.com/41721950/67932654-3d964000-fbff-11e9-972f-75e17a2c6e68.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
套版設定已經可以正常執行
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
套版設定已經可以正常執行
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
套版設定已經可以正常執行
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
套版設定已經可以正常執行。
◎◎ 20191125確認以上正式環境內容◎◎
