### ISSUE TITLE
【MS SQL】動畫效果未能隨著選擇即時更改文字

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1608]
動畫效果未能隨著選擇即時更改文字，如下圖黃框處選擇翹翹板，但是紅框處卻顯示彈跳。
需要進行別的觸發動作紅框處才會變更為正確內容。
![image](https://user-images.githubusercontent.com/49626114/67933320-85699700-fc00-11e9-92c6-25cecde9302f.png)

**Comment by cocosu123** [comment]
動畫效果已經能隨著選擇即時更改文字。
![1608](https://user-images.githubusercontent.com/49626114/68275145-cf8dc500-00a5-11ea-979b-2a38cc94fa1b.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
動畫效果已經能隨著選擇即時更改文字
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
動畫效果已經能隨著選擇即時更改文字
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
動畫效果已經能隨著選擇即時更改文字。
◎◎ 20191125確認以上正式環境內容◎◎
