### ISSUE TITLE
【MS SQL】套版的互動元件不能啟用或選擇

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1609]
從『套版總覽』選擇一個含有互動的套版
![image](https://user-images.githubusercontent.com/41721950/67937067-d761eb00-fc07-11e9-9de0-b232a05d0f91.png)
按下『啟用互動元件』後，元件設定會一直Loading
![image](https://user-images.githubusercontent.com/41721950/67936442-c2388c80-fc06-11e9-8edd-5b1ca4250347.png)
點選其他元件再回點此互動元件，可知元件設定已跑版
![image](https://user-images.githubusercontent.com/41721950/67936504-e1cfb500-fc06-11e9-9426-d6b19cc5aadb.png)
在此專案中新建元件並選擇『選擇元件』，可以看到編輯區的元件已跑版
![image](https://user-images.githubusercontent.com/41721950/67936695-32dfa900-fc07-11e9-971f-bcbcadc87530.png)
錯誤訊息如下，請參考
![image](https://user-images.githubusercontent.com/41721950/67936950-a681b600-fc07-11e9-8861-caeb26e6994a.png)

**Comment by AnitaRyzo** [comment]
套版的互動元件可以連接「啟用或選擇」
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
套版的互動元件可以連接「啟用或選擇」
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
套版的互動元件可以連接「啟用或選擇」
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
套版的互動元件可以連接「啟用或選擇」。
◎◎ 20191125確認以上正式環境內容◎◎
