### ISSUE TITLE
【MS SQL】『進入XX編輯模式』的元件，離開編輯後未留在元件上

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1610]
在輪播區塊、收縮區塊、頁籤、電子申請書、互動遊戲、MGM、序號機皆有以下狀況發生，下面以互動遊戲為範例：
在COM環境互動元件的表單資訊設定中按下『離開表單編輯頁』(如下圖橘框處)
![image](https://user-images.githubusercontent.com/49626114/67997617-cceb3400-fc8f-11e9-82dc-35d8489fdd70.png)
就會直接離開互動元件的編輯框，右邊跳離設定畫面(紅框處)
![com環境](https://user-images.githubusercontent.com/49626114/67996943-c5765b80-fc8c-11e9-9f98-c088d01f4e6d.png)
但是相同步驟在io環境操作，仍然會停留在編輯設定狀態(黃框處)
![io環境](https://user-images.githubusercontent.com/49626114/67997075-5b11eb00-fc8d-11e9-8bc7-e3c218e66e6e.png)

**Comment by cocosu123** [comment]
『進入XX編輯模式』的元件，離開編輯後，仍然會停留在編輯設定狀態。
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
『進入XX編輯模式』的元件，離開編輯後，仍然會停留在編輯設定狀態。
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
『進入XX編輯模式』的元件，離開編輯後，仍然會停留在編輯設定狀態。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
『進入XX編輯模式』的元件，離開編輯後，仍然會停留在編輯設定狀態。
◎◎ 20191125確認以上正式環境內容◎◎
