### ISSUE TITLE
【MS SQL】EDM與Banner的圖片剪裁或顯示位置，在選擇比例後出現黑畫面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1611]
無論是EDM的「圖片剪裁」
![image](https://user-images.githubusercontent.com/41721950/68000331-9ff04e80-fc9a-11e9-9f5e-7a9e3c7ff59f.png)
或是Banner的「圖片/圖片庫之圖片剪裁」與「圖片顯示位置」
![image](https://user-images.githubusercontent.com/41721950/68000221-29535100-fc9a-11e9-9239-4c45d6cee880.png)
選擇下方的剪裁比例(紅框處)後，原本的圖片會呈現黑畫面(右圖紅框處)。
![image](https://user-images.githubusercontent.com/41721950/68000265-5e5fa380-fc9a-11e9-9a33-3a292d2dd255.png)
比例剪裁全數失效
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
Duplicate of #1589

**Comment by AnitaRyzo** [comment]
EDM的「圖片剪裁」可正常執行
但Banner的「圖片/圖片庫之圖片剪裁」與「圖片顯示位置」可按下『確認』關閉視窗，但功能依然失效。
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
EDM與Banner的圖片剪裁或顯示位置，在選擇比例後已無黑畫面的情況發生。
◎◎ 20191113確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
EDM與Banner的圖片剪裁或顯示位置，在選擇比例後已無黑畫面的情況發生，且都可正常執行。
◎◎ 20191125確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
EDM與Banner的圖片剪裁或顯示位置，在選擇比例後已無黑畫面的情況發生，且都可正常執行。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
