### ISSUE TITLE
【MS SQL】EDM的網頁擷取若放大比例尺，畫面會留白

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1612]
圖片的『網頁擷取』時
![image](https://user-images.githubusercontent.com/41721950/68002341-63752080-fca3-11e9-9564-084ddd5120e9.png)
若按放大比例尺，圖片未能完整顯示於框內 (會空出紅線)
![image](https://user-images.githubusercontent.com/41721950/68004630-3168bc00-fcad-11e9-9913-5b672cf1038a.png)
但正式環境可以填滿
![image](https://user-images.githubusercontent.com/41721950/68002321-450f2500-fca3-11e9-987c-5d813e05bee5.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68556398-11838600-046d-11ea-8f0d-2dcd39302a8b.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68574837-c76ac680-04a5-11ea-9588-b435e07bd017.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/69511995-46b7ca00-0f7d-11ea-938d-2bb585a8b570.png)
◎◎ 20191125確認以上正式環境內容◎◎
