### ISSUE TITLE
【MS SQL】修改團隊名稱打勾後呈現loading狀態

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1613]
在團隊管理修改團隊名稱，完成後按打勾符號(橘框處)
![勾勾](https://user-images.githubusercontent.com/49626114/68014921-ce3a5200-fccb-11e9-86c8-1c8d3e8bb184.png)
打勾符號會變成齒輪符號(紅框處)一直轉圈呈現LOADING狀態，
![image](https://user-images.githubusercontent.com/49626114/68015140-6f290d00-fccc-11e9-8ab8-e730c615dd6b.png)
而從Network顯示"團隊修改成功"(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/68015153-7e0fbf80-fccc-11e9-9730-792a95192908.png)
若要解決此狀況，必須點叉叉(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68015292-cd55f000-fccc-11e9-9051-5fb8b0c43336.png)

**Comment by cocosu123** [comment]
在團隊管理修改團隊名稱，完成後按打勾符號已可正常執行。
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
在團隊管理修改團隊名稱，無論是按『enter』或是按『打勾符號』皆可正常儲存。
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
在團隊管理修改團隊名稱，無論是按『enter』或是按『打勾符號』皆可正常儲存。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在團隊管理修改團隊名稱，無論是按『enter』或是按『打勾符號』皆可正常儲存。
◎◎ 20191125確認以上正式環境內容◎◎
