### ISSUE TITLE
【MS SQL】管理者後台的權限管理開關影響權限項目查看的呈現畫面

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1614]
情況發生在管理者後台的權限管理關閉(黃框處)時，
![image](https://user-images.githubusercontent.com/49626114/68098800-cc55d600-fef9-11e9-90f3-b18e4b17cd93.png)
情況1.
團隊管理中的團隊管理&權限管理皆關閉，在權限項目查看的畫面沒有顯示團隊管理&權限管理的內容(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68098765-a03a5500-fef9-11e9-9590-9261884b7335.png)
情況2.
團隊管理中的團隊管理開啟、權限管理關閉，在權限項目查看的畫面團隊管理顯示不完全，權限管理的內容則未顯示(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68098785-ba743300-fef9-11e9-8e20-96b5a3651ef8.png)

**Comment by cocosu123** [comment]
在管理者後台的團隊相關權限關閉(黃框處)時，
![image](https://user-images.githubusercontent.com/49626114/68277941-411c4200-00ab-11ea-8485-21b8de1f5a72.png)
情況1.
若團隊管理中的團隊管理&權限管理皆關閉，在權限項目查看的畫面就不會顯示團隊管理&權限管理的內容。
![image](https://user-images.githubusercontent.com/49626114/68278549-85f4a880-00ac-11ea-99ab-06e48553e6cc.png)
情況2.
若團隊管理中的團隊管理開啟、權限管理關閉時，內容已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/68278431-429a3a00-00ac-11ea-91e1-f69bb9ec0adc.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
根據上述操作，
情況1.在權限項目查看的畫面就不會顯示團隊管理&權限管理的內容。
![image](https://user-images.githubusercontent.com/49626114/68555287-f3675700-0467-11ea-9cb6-5192b55e2628.png)
情況2.內容已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/68555303-fe21ec00-0467-11ea-983a-86c3295a7b32.png)
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
1. 團隊管理中的團隊管理&權限管理皆關閉，在權限項目查看的畫面就不會顯示團隊管理&權限管理的內容。
2. 團隊管理中的團隊管理開啟、權限管理關閉，在權限項目查看的畫面已正常呈現。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
管理者後台的權限管理關閉(黃框處)時，
a.團隊管理中的「團隊管理&權限管理」皆關閉時，在「權限項目查看」的明細不會顯示「團隊管理&權限管理」的內容。
![image](https://user-images.githubusercontent.com/41721950/69507608-1caadb80-0f6e-11ea-98c0-6f39e287d4f6.png)
b.團隊管理中的團隊管理開啟、權限管理關閉，在權限項目查看的畫面已正常呈現。
![image](https://user-images.githubusercontent.com/41721950/69507598-0e5cbf80-0f6e-11ea-8fbd-d29c3b0a6ee5.png)
◎◎ 20191125確認以上正式環境內容 ◎◎
