### ISSUE TITLE
【MS SQL】輪播區塊與頁籤在『編輯模式列表』，功能未完整顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1615]
輪播區塊與頁籤在『編輯模式中』，區塊排序列表的排序、複製與刪除功能未顯示，且不能雙擊修改名稱
輪播區塊示意圖
![image](https://user-images.githubusercontent.com/41721950/68099428-771bc380-fefd-11e9-9ba6-3b57748d1260.png)
頁籤示意圖
![image](https://user-images.githubusercontent.com/41721950/68099437-8569df80-fefd-11e9-8a27-45555eee3bad.png)
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
進入編輯模式時，預設不給編輯，讓使用者當下專注在編輯內部的元件

**Comment by ryuichl** [comment]
不是bug 先關掉
