### ISSUE TITLE
【MS SQL】表單與電子申請書的顏色設定呈現有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1617]
無論是頁面、題目、按鈕設定的顏色設定值，皆未能依照設定立即呈現在編輯區中
最明顯有問題的是『表單背景顏色』，「主題樣式區」與「編輯區」顯示的背景顏色範圍不同
![image](https://user-images.githubusercontent.com/41721950/68105729-63cb2100-ff1a-11e9-99d0-62e5e5640eba.png)
![image](https://user-images.githubusercontent.com/41721950/68105809-a260db80-ff1a-11e9-952e-3a0b5accd0a8.png)
而電子申請書所有的顏色設定，必須通過切換『幻燈片』才能呈現設定...
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
上述問題仍存在，且現在點選顏色不會第一時間顯示在編輯區預覽
![image](https://user-images.githubusercontent.com/41721950/68271781-b2082d80-009c-11ea-8495-9363b8d1391e.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
表單顏色設定目前沒有此問題
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
表單與電子申請書的顏色設定呈現正確
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
表單與電子申請書的顏色設定呈現正確
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
表單與電子申請書的顏色設定呈現正確。
◎◎ 20191125確認以上正式環境內容◎◎
