### ISSUE TITLE
【MS SQL】資料綁定的分類管理未顯示選單架構設定與預覽圖

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1618]
在資料綁定的分類管理頁未正常顯示選單架構設定與預覽圖(紅框處)，需要切換至別的頁面再回來才會正常顯示。
![image](https://user-images.githubusercontent.com/49626114/68108549-01c2e980-ff23-11e9-824b-bb185eb76b79.png)

**Comment by cocosu123** [comment]
資料綁定的分類管理畫面已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/68355712-0f5ab800-014b-11ea-9956-4304ae59a9df.png)
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
資料綁定的「分類管理」已正常呈現。
![image](https://user-images.githubusercontent.com/41721950/68456492-dac52a00-0238-11ea-8803-d4373cf626a4.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
資料綁定的「分類管理」已正常呈現。
![image](https://user-images.githubusercontent.com/41721950/68571032-f6306f00-049c-11ea-80f6-b3f85e1b7556.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
資料綁定的「分類管理」已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/69511696-34895c00-0f7c-11ea-9576-c19aaf9049e8.png)
◎◎ 20191125確認以上正式環境內容◎◎
