### ISSUE TITLE
【MS SQL】選擇表單類型與專案個別設定的問題

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1619]
問題1.
一般表單元件和MGM的表單點選『建立新表單』後，選擇表單類型多了其他兩種表單的選項，如下圖。
![image](https://user-images.githubusercontent.com/49626114/68174754-08e90680-ffba-11e9-8ee1-34a5c035d043.png)
在序號機&互動元件點選『建立新表單』後，選擇表單類型則無任何選項，畫面如下圖。
![image](https://user-images.githubusercontent.com/49626114/68174939-8ca2f300-ffba-11e9-9dd6-f24cc73a2368.png)

問題2.
表單元件點選『表單管理』後，在表單設定裡的專案個別設定內容呈現不完全(紅框處)，在正式環境的呈現如黃框處。
![表單專案個別設定](https://user-images.githubusercontent.com/49626114/68174389-eb676d00-ffb8-11e9-9105-70c40c3cabe7.png)
此問題發生在表單、電子申請書、MGM、序號機、互動元件。

**Comment by AnitaRyzo** [comment]
一般表單元件(MGM)、互動元件與序號機皆有出現正確的表單類型選項
![image](https://user-images.githubusercontent.com/41721950/68278364-18e11300-00ac-11ea-8d43-93ad4fa6c175.png)
一般表單元件(MGM)、互動元件與序號機皆有出現正確的專案個別設定內容(黃框)
![image](https://user-images.githubusercontent.com/41721950/68278583-960c8800-00ac-11ea-8d2c-7ecbc49bc938.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
一般表單元件(MGM)、互動元件和序號機皆有出現正確的表單類型選項，也皆有出現正確的專案個別設定內容。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
一般表單元件(MGM)、互動元件和序號機皆有出現正確的表單類型選項，
![image](https://user-images.githubusercontent.com/49626114/69511524-6bab3d80-0f7b-11ea-9e18-1d8886dbc796.png)
也皆有出現正確的專案個別設定內容。
![image](https://user-images.githubusercontent.com/49626114/69511584-add47f00-0f7b-11ea-8683-ba7eb328c718.png)
◎◎ 20191125確認以上正式環境內容◎◎
