### ISSUE TITLE
【建議】內嵌程式碼

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#162]
使用內嵌程式碼新增程式碼
使用“放大”功能之後， 點擊完成沒有實質的回饋，需要另外點擊縮小才會將區塊縮回去

問題1:請問這個完成僅只是用來預視程式碼樣式的用途嗎？並不是真的完成整個內嵌網頁的動作
問題2:點擊完成以後，如果我將程式碼刪除，再點擊完成，畫面會維持我原本嵌入程式碼的樣式，並不會被清除

**Comment by Isabella-Zheng** [comment]
已解決

**Comment by Isabella-RYZO** [comment]
👌
