### ISSUE TITLE
【MS SQL】資料綁定的名單檔案頁掉圖

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1620]
在資料綁定的名單檔案頁掉圖(紅框處)
![image](https://user-images.githubusercontent.com/49626114/68177351-fb844a00-ffc2-11e9-8644-3bee10a93965.png)
從network查看得到404錯誤碼
![image (1)](https://user-images.githubusercontent.com/49626114/68177428-44d49980-ffc3-11e9-8738-d59485e0dbf6.png)

**Comment by cocosu123** [comment]
資料綁定的名單檔案頁圖片已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/68275641-33fd5400-00a7-11ea-8eec-0e280cd441a1.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68454968-2ece0f80-0235-11ea-8ff3-0d596fcb460b.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68570780-625ea300-049c-11ea-8528-ca8a02d1e24c.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/69511255-774a3480-0f7a-11ea-8744-024091d8d51a.png)
◎◎ 20191125確認以上正式環境內容◎◎
