### ISSUE TITLE
【MS SQL】表單題型造成編輯區的表單顯示毀損

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1621]
有問題的題型：單選題、複選題、線性評分、矩陣式、核取方塊
無論是一般、MGM、序號、互動表單，當表單有放到任何一個上面所述的題型，表單第一次匯入後
![image](https://user-images.githubusercontent.com/41721950/68178277-5c615180-ffc6-11e9-8747-91079c86932d.png)
編輯區的顯示會多出一塊(紅框處)
![image](https://user-images.githubusercontent.com/41721950/68178444-03de8400-ffc7-11e9-8566-69446c8c89c0.png)
若按下『表單設定』的任一按鈕
![image](https://user-images.githubusercontent.com/41721950/68178647-c5959480-ffc7-11e9-9c96-ec6215944514.png)
錯誤訊息碼如下
![image](https://user-images.githubusercontent.com/41721950/68178679-e3fb9000-ffc7-11e9-8247-f4fac2e55e93.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
一般、MGM、序號、互動表單，即使有單選題、複選題、線性評分、矩陣式、核取方塊的題型，仍可正常執行。
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
全題型在表單或電子申請書皆可正常執行。
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
全題型在表單或電子申請書皆可正常執行。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
全題型在表單或電子申請書皆可正常執行。
◎◎ 20191125確認以上正式環境內容◎◎
