### ISSUE TITLE
【MS SQL】MGM與互動的獎項圖片載入方式有誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1622]
從network得知圖片未取到site id(如下圖，紅框處的undefined)，導致在ml測試環境圖片無法正常顯示，雖然在com環境會顯示圖片，但也有未取到site id的問題發生。
![image](https://user-images.githubusercontent.com/49626114/68184917-4ad67480-ffdb-11e9-9908-b6d6ea9a10ed.png)

**Comment by AnitaRyzo** [comment]
互動遊戲也有相同問題，後續要一併確認，若有錯誤要提出
![image](https://user-images.githubusercontent.com/41721950/68260949-7c9e1880-0079-11ea-84d6-d595001306a3.png)

**Comment by cocosu123** [comment]
圖片使用「原檔上傳」時，依舊有上述問題發生。
![image](https://user-images.githubusercontent.com/49626114/68274641-a02a8880-00a4-11ea-8461-e20a88de18d8.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
從network得知「一般上傳」及「原檔上傳」取得圖片路徑都已修正(綠框處)，在ml測試環境MGM與互動的圖片已正常呈現。
![1622](https://user-images.githubusercontent.com/49626114/68354770-3a8fd800-0148-11ea-9060-4e60ef9c5b12.png)
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
從network得知「一般上傳」及「原檔上傳」取得圖片路徑都已修正(綠框處)，MGM與互動的圖片皆正常呈現。
![image](https://user-images.githubusercontent.com/49626114/68460295-714a1900-0242-11ea-802c-5e34e5ac1e41.png)

**Comment by cocosu123** [comment]
從network得知取得圖片路徑都已修正(綠框處)，圖片皆正常呈現。
![image](https://user-images.githubusercontent.com/49626114/68573312-71e0ea80-04a2-11ea-9dca-87b3a142a504.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
從network得知取得圖片路徑都已修正，圖片皆正常呈現。
![image](https://user-images.githubusercontent.com/49626114/69510744-0d7d5b00-0f79-11ea-9c6d-7ddc754987c5.png)
◎◎ 20191125確認以上正式環境內容◎◎
