### ISSUE TITLE
【問題】MGM已有社群列表資料才加分享前表單

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1623]
若MGM一開始未設定連動『表單』(左圖橘框)，但若在社群已有資料後才增加『表單設計』將表單帶入(右圖黃框)
![image](https://user-images.githubusercontent.com/41721950/68200358-aa904800-fffa-11e9-82c9-aa8c075665fd.png)
在連動表單前，『互動管理後台-社群列表-下載』可以正確執行
![image](https://user-images.githubusercontent.com/41721950/68199859-c21b0100-fff9-11e9-9eea-50465ffbfb12.png)
連動表單後，若按『下載』，會出現以下錯誤狀況
![image](https://user-images.githubusercontent.com/41721950/68200518-0955c180-fffb-11e9-9676-cf102a6d5bee.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
連動表單後，『互動管理後台-社群列表-下載』可以正確執行。
![1623](https://user-images.githubusercontent.com/49626114/68272097-a9fcbd80-009d-11ea-9a36-31c4a298d0c2.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
連動表單後，『互動管理後台-社群列表-下載』可以正確執行。
![image](https://user-images.githubusercontent.com/49626114/68459897-85414b00-0241-11ea-8d4e-d9370c2406e4.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
連動表單後，『互動管理後台-社群列表-下載』可以正確執行。
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
連動表單後，『互動管理後台-社群列表-下載』可以正確執行。
◎◎ 20191125確認以上正式環境內容◎◎
