### ISSUE TITLE
【一銀環境】mgm的分享模式與機制會被強制切換

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1624]
原專案中mgm的分享機制只要是「不重複計算+多層分享」，在複製專案後，啟用分享換優惠再選擇任何分享機制&分享模式都會被強制變成「分享」模式+「不重複計算」機制，且優惠及條件設定不會連動。
如下圖範例所示：
綠色框為原專案mgm的設定，複製專案後啟用專案中的mgm，選擇「可重複計算」機制+「網站內嵌」模式(黃框處)，按下確認後會被強制切換成「分享」模式+「不重複計算」機制(如紅框處)
![image](https://user-images.githubusercontent.com/49626114/68201434-bb41bd80-fffc-11e9-8f18-b7473f2770f5.png)
優惠及條件設定不會連動，會亮起綠框要重新設定(如下圖)
![image](https://user-images.githubusercontent.com/49626114/68259200-29759700-0074-11ea-905a-1606c0da5969.png)

**Comment by Kyle30** [comment]
原先環境內使用的測試資料庫缺少了特定欄位
已更換了一個新的測試資料庫, 並套用到最新的 migration
此問題已解

**Comment by AnitaRyzo** [comment]
「不重複計算+多層分享」在複製專案後，再「啟用分享換優惠」，設定值不會跳離且「設定優惠及條件」的內容也會一併帶入。
◎◎ 20191106確認以上一銀模擬環境內容◎◎
