### ISSUE TITLE
【一銀環境】單一獎項下載的內容與後台描述有差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1625]
問題1.紅框處內容呈現不一
在後台顯示『年月日時分秒』，但下載後只剩『年月日』
問題2.橘框顯示的內容未出現在『表單後台』，且下載後的『回覆日期』是+8時區的時間
![image](https://user-images.githubusercontent.com/41721950/68202085-f690bc00-fffd-11e9-8ba0-464b98a04591.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
已修正
@Kyle30 再幫忙更新到測試的一銀環境

**Comment by cocosu123** [comment]
問題1.紅框處內容依舊呈現不一
在後台顯示『年月日時分秒』，但下載後只剩『年月日』
問題2.綠框處的時區時間已恢復正常。
![image](https://user-images.githubusercontent.com/49626114/68286800-ab89ae00-00bc-11ea-9442-7f38e41639de.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
問題1.紅框處內容依舊呈現不一
在後台顯示『年月日時分秒』，但下載後只剩『年月日』。
問題2.綠框處的時區時間已恢復正常。
![image](https://user-images.githubusercontent.com/49626114/68459521-99387d00-0240-11ea-9ae0-fd4b9b6bfe19.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
紅框處內容依舊呈現不同，在後台顯示『年月日時分秒』，但下載後只剩『年月日』。
綠框處的時區時間已恢復正常。
![image](https://user-images.githubusercontent.com/49626114/68572776-3d206380-04a1-11ea-9163-d49d0626251b.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
紅框處內容依舊呈現不同，在後台顯示『年月日時分秒』，但下載後只剩『年月日』。
綠框處的時區時間已恢復正常。
![image](https://user-images.githubusercontent.com/49626114/69508788-ab6d2780-0f71-11ea-89b7-5e6f00cc3e5b.png)
◎◎ 20191125確認以上正式環境內容◎◎
