### ISSUE TITLE
【MS SQL】新增團隊的按鈕失效

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1627]
新增團隊的按鈕(紅框處)失效。
![image](https://user-images.githubusercontent.com/49626114/68261016-bc650000-0079-11ea-835c-6eb8f728452a.png)

**Comment by cocosu123** [comment]
新增團隊的按鈕已經可以正常執行。
![image](https://user-images.githubusercontent.com/49626114/68275512-db2dbb80-00a6-11ea-8e45-a31744527785.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
新增團隊的兩個地方(黃框)皆可正常執行
![image](https://user-images.githubusercontent.com/41721950/68465176-e91d4100-024c-11ea-94df-23e116ea0f20.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
新增團隊的兩個按鈕皆可正常執行
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
新增團隊的兩個按鈕(黃框處)皆可正常執行。
![image](https://user-images.githubusercontent.com/49626114/69507845-00f40500-0f6f-11ea-9deb-21ea61510e81.png)
◎◎ 20191125確認以上正式環境內容◎◎
