### ISSUE TITLE
【MS SQL】顏色設定的跳出視窗未能在最上層

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1628]
顏色設定的跳出視窗未能在最上層，會讓一些設定被覆蓋住
![image](https://user-images.githubusercontent.com/41721950/68261656-c7209480-007b-11ea-9886-58a49c6163f5.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
顏色設定的跳出視窗已位移，不會被擋住
![image](https://user-images.githubusercontent.com/41721950/68282251-4e89fa00-00b4-11ea-9e90-ee82187bb8cd.png)
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
顏色設定的彈跳視窗已位移，不會被擋住
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
顏色設定的彈跳視窗已位移，不會被擋住。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
顏色設定的彈跳視窗已位移，不會被擋住。
![image](https://user-images.githubusercontent.com/49626114/69507572-f71dd200-0f6d-11ea-93db-216701d4aa94.png)
◎◎ 20191125確認以上正式環境內容◎◎
