### ISSUE TITLE
【問題】元件刪除的問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#163]
Hi，
目前因為快速編輯區還沒完成，所以刪除仰賴鍵盤的Delete

1.Mac預設的Delete對應的其實是Backspace，導致在Mac系統要刪除元件必須點擊Fn+Delete，不知有什麼解決方法

2.新增元件以後，如果我在元件內做任何編輯，再點Delete，無法直接刪除元件。必須要點擊空白處再重新選擇該元件才能正常Delete (我新增一個圖片元件，並上傳圖片，然後我立刻點擊Delete，會沒有反應)

**Comment by ryuichl** [comment]
目前還有圖層區右下角可以刪除元件
其餘部分待優化

**Comment by wilmaftliu** [comment]
目前快捷鍵有支援刪除的是delete鍵
還是說可以把這個刪除快捷鍵改成backspace？
