### ISSUE TITLE
【一銀環境】互動的表單顯示比例錯誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1630]
編輯時的表單尺寸有完整覆蓋『互動元件』，發佈後互動表單變成迷你尺寸
![image](https://user-images.githubusercontent.com/41721950/68266566-6f3d5a00-008a-11ea-8786-0a617b451596.png)
但在其他環境是有按照螢幕比例放大
![image](https://user-images.githubusercontent.com/41721950/68266596-811efd00-008a-11ea-93ce-62bf948bd4cc.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
是說我剛.com也有看到小的表單
但現在就正常
是因為已經改過了嗎?
@ai015606220

**Comment by ai015606220** [comment]
是的 有改過

**Comment by ryuichl** [comment]
等 @Kyle30 更新

**Comment by Kyle30** [comment]
已更新至 Dev:4269

**Comment by AnitaRyzo** [comment]
互動的表單尺寸已顯示與編輯區設定的尺寸類似
◎◎ 20191106確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
互動的表單尺寸已顯示與編輯區設定的尺寸類似
![image](https://user-images.githubusercontent.com/49626114/68456583-22e44c80-0239-11ea-97ea-a25a4cfe4d26.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
互動的表單尺寸已顯示與編輯區設定的尺寸類似
![image](https://user-images.githubusercontent.com/49626114/68569789-fd09b280-0499-11ea-8919-8952a78a6941.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
互動的表單尺寸已顯示與編輯區設定的尺寸類似。
![image](https://user-images.githubusercontent.com/49626114/69507117-68f51c00-0f6c-11ea-8274-27b907edc31e.png)
◎◎ 20191125確認以上正式環境內容◎◎
