### ISSUE TITLE
【MS SQL】表單管理後台新增的表單類型要有三種

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1631]
表單管理後台新增表單時，原本可以從三種『表單類型』擇一
![image](https://user-images.githubusercontent.com/41721950/68268217-5041c680-0090-11ea-9a8d-922552f992f0.png)
但目前只剩下『一般表單』
![image](https://user-images.githubusercontent.com/41721950/68268203-4029e700-0090-11ea-9302-901e9c76e05c.png)
以上問題請協助修改，感恩~

**Comment by cocosu123** [comment]
在表單管理後台新增表單時，已恢復成有三種『表單類型』
![image](https://user-images.githubusercontent.com/49626114/68358660-25b94180-0154-11ea-9a9a-a513eae6628b.png)
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
在表單管理後台新增表單時，有三種『表單類型』可選擇
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在表單管理後台新增表單時，有三種『表單類型』可選擇。
![image](https://user-images.githubusercontent.com/49626114/69506839-4e6e7300-0f6b-11ea-94c9-2e109fa47863.png)
◎◎ 20191125確認以上正式環境內容◎◎
