### ISSUE TITLE
【 MS SQL】互動表單編輯頁切換幻燈片時，未關閉表單編輯頁

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1632]
互動元件設置在「頁面-幻燈片」，設置『表單資料設定』
![image](https://user-images.githubusercontent.com/41721950/68272311-3f984d00-009e-11ea-818a-cad1f95b56ef.png)
開啟『表單編輯頁』時，若切換左邊頁面管理的幻燈片，仍保持開啟著『表單編輯頁』
![image](https://user-images.githubusercontent.com/41721950/68272488-cf3dfb80-009e-11ea-8911-242dffb080c0.png)
在正式環境若切換頁面管理的幻燈片，就會自動關閉『表單編輯頁』
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
互動元件設置『表單資料設定』時，若切換左邊頁面管理的幻燈片，會關閉『表單編輯頁』
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
互動元件設置『表單資料設定』時，若切換左邊頁面管理的幻燈片，會關閉『表單編輯頁』。
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
互動元件設置『表單資料設定』時，若切換左邊頁面管理的幻燈片，會關閉『表單編輯頁』。
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
互動元件設置『表單資料設定』時，若切換左邊頁面管理的幻燈片，會關閉『表單編輯頁』。
◎◎ 20191125確認以上正式環境內容◎◎
