### ISSUE TITLE
【MS SQL】互動元件的「測試結果」按鈕失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1633]
互動元件的「測試結果」按鈕沒有反應
![image](https://user-images.githubusercontent.com/41721950/68285395-2bfadf80-00ba-11ea-8c5a-2b3b6090c475.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
所有互動元件的「測試結果」按鈕已可正確執行
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
所有互動元件的「測試結果」按鈕已可正確執行。
![image](https://user-images.githubusercontent.com/49626114/68456399-9a65ac00-0238-11ea-811f-6a6996ff2dc7.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
所有互動元件的「測試結果」按鈕已可正確執行，九宮格的延伸問題在 #1652 。
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
所有互動元件的「測試結果」按鈕已可正確執行。
◎◎ 20191125確認以上正式環境內容◎◎
