### ISSUE TITLE
【MS SQL】文字陰影的顏色選取器不會自動關閉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1634]
文字陰影預設是關閉，開啟後可以利用「顏色選取器」選陰影顏色
![image](https://user-images.githubusercontent.com/41721950/68353911-ed126b80-0145-11ea-8f64-e8a91bdc4e99.png)
當從「有陰影的文字」改選「無文字陰影的元件」，顏色選取器變成了半透明...
![image](https://user-images.githubusercontent.com/41721950/68353983-1fbc6400-0146-11ea-90e4-0cf14d240d23.png)
在正式環境是會自動關閉顏色選取器的
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
從「有陰影的文字」改選「無文字陰影的元件」，顏色選取器會自動關閉
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
從「有陰影的文字」改選「無文字陰影的元件」，顏色選取器會自動關閉
◎◎ 20191111確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
從「有陰影的文字」改選「無文字陰影的元件」，顏色選取器會自動關閉。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
從「有陰影的文字」改選「無文字陰影的元件」，顏色選取器會自動關閉。
◎◎ 20191125確認以上正式環境內容◎◎
