### ISSUE TITLE
【MS SQL】幸運轉盤的獎項圖片在設定時未正常顯示

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1635]
幸運轉盤上傳獎項圖片後，都會正常顯示。
![image](https://user-images.githubusercontent.com/49626114/68356585-a3c61a00-014d-11ea-8983-ed3b01b9d479.png)
但是切換到「設定比例」頁面，左邊預覽圖未正常顯示獎項圖片(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68356294-db809200-014c-11ea-84d1-f9b86a3b9f43.png)
調整比例(紅框處)後，左邊預覽圖(橘框處)圖片就會正常顯示。
![image](https://user-images.githubusercontent.com/49626114/68356363-171b5c00-014d-11ea-9230-f940b7ffecf7.png)
若再切換回「設定獎項」頁面(橘框處)，左邊的預覽圖(紅框處)圖片就會消失。
![image](https://user-images.githubusercontent.com/49626114/68356438-534ebc80-014d-11ea-845b-a4f34b209af7.png)

**Comment by AnitaRyzo** [comment]
幸運轉盤的獎項圖片皆會完整顯示
![image](https://user-images.githubusercontent.com/41721950/68448801-b27d0180-021f-11ea-938d-a145c6135c5d.png)
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
幸運轉盤的獎項圖片皆會完整顯示
![image](https://user-images.githubusercontent.com/49626114/68456247-4ce93f00-0238-11ea-9146-38f857b3c9a2.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
幸運轉盤的獎項圖片皆會完整顯示
![image](https://user-images.githubusercontent.com/49626114/68566617-d0ea3380-0491-11ea-9bb4-45c8158bd22a.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
幸運轉盤的獎項圖片皆會完整顯示。
![image](https://user-images.githubusercontent.com/49626114/69506163-57117a00-0f68-11ea-85bb-8bbbeaf5da08.png)
◎◎ 20191125確認以上正式環境內容◎◎
