### ISSUE TITLE
【MS SQL】互動元件的專案截圖跑版

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1636]
已測試所有互動元件，僅有搖獎機、轉蛋機、紅包的專案截圖跑版，截圖畫面與專案內呈現的畫面不同。
![image](https://user-images.githubusercontent.com/49626114/68357676-0d93f300-0151-11ea-893e-bd10c342f579.png)
![image](https://user-images.githubusercontent.com/49626114/68357702-21d7f000-0151-11ea-983c-cef6652b2e8a.png)
![image](https://user-images.githubusercontent.com/49626114/68357720-2e5c4880-0151-11ea-9fcc-d31cf46f7157.png)
備註：紅包全部樣式皆有此問題發生。

**Comment by AnitaRyzo** [comment]
互動元件的專案截圖已正常顯示
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
互動元件的專案截圖已正常顯示
![image](https://user-images.githubusercontent.com/49626114/68456094-dcdab900-0237-11ea-9c62-88013ab96ac7.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
互動元件的專案截圖已正常顯示
![image](https://user-images.githubusercontent.com/49626114/68565950-fece7880-048f-11ea-96a4-39ae6677d4e1.png)
◎◎ 20191111確認以上測試環境內容MongoDB◎◎

**Comment by cocosu123** [comment]
互動元件的專案截圖已正常顯示。
◎◎ 20191125確認以上正式環境內容◎◎
