### ISSUE TITLE
【MS SQL】資料綁定的圖片庫分類視窗未自動關閉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1637]
資料綁定的圖片庫，選取數張圖片後按下『分類』按鈕，擇一類別後按下『完成』，會一直停留在這頁
![image](https://user-images.githubusercontent.com/41721950/68360053-6a93a700-0159-11ea-9d3a-a89992fe678b.png)
但按下X關閉此視窗後，圖片確實已被分類
錯誤訊息如下請參考
![image](https://user-images.githubusercontent.com/41721950/68360098-9d3d9f80-0159-11ea-95ab-6439bb888651.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
資料綁定的圖片庫，選取數張圖片後按下『分類』按鈕，擇一類別後按下『完成』，已可正常執行。
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
資料綁定的圖片庫，選取數張圖片後按左上角的『分類』按鈕，擇一類別後按下『完成』，已可正常執行。
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
資料綁定的圖片庫，選取數張圖片後按左上角的『分類』按鈕，擇一類別按下『完成』，已可正常執行。
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
資料綁定的圖片庫，選取數張圖片後按左上角的『分類』按鈕，擇一類別按下『完成』，已可正常執行。
◎◎ 20191125確認以上正式環境內容◎◎
