### ISSUE TITLE
【MS SQL】資料綁定的分類顯示圖設定未及時顯示圖片

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1638]
在資料綁定的「分類顯示圖設定」上傳圖片後，圖片未即時顯示(紅框處)，右邊的預覽處有及時顯示圖片(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68364984-6fad2200-016a-11ea-81b4-760357f8c8e3.png)
備註：紅框處的圖片需先切換到別的分頁再回來才會顯示圖片。

**Comment by cocosu123** [comment]
「分類顯示圖設定」上傳圖片後，圖片已有即時顯示(綠框處)
![image](https://user-images.githubusercontent.com/49626114/68449678-1654f980-0223-11ea-89b5-1af2c8bbc8e5.png)
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
「分類顯示圖設定」上傳圖片後，圖片已有即時顯示(黃框)
![image](https://user-images.githubusercontent.com/41721950/68457785-0ac1fc80-023c-11ea-8fd5-79ba958673ec.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
「分類顯示圖設定」上傳圖片後，圖片已有即時顯示(綠框)
![image](https://user-images.githubusercontent.com/41721950/68571197-7060f380-049d-11ea-866d-f2595b68af87.png)
◎◎ 20191111確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
「分類顯示圖設定」上傳圖片後，圖片已有即時顯示。
![image](https://user-images.githubusercontent.com/49626114/69505573-938fa680-0f65-11ea-9650-ce4f34d6e7b2.png)
◎◎ 20191125確認以上正式環境內容◎◎
