### ISSUE TITLE
【MS SQL】分類切換的提示圖示顏色未即時變更

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1639]
在資料綁定的分類切換設定中，變更提示設定的圖示顏色，但右邊預覽處並未及時變更(紅框處)，需離開顏色設定區塊(黃框處)後，右邊預覽處的圖示顏色才會變更。
![image](https://user-images.githubusercontent.com/49626114/68366960-7db17180-016f-11ea-8151-1b65ab26fa21.png)

**Comment by ai015606220** [comment]
Duplicate of #1576

**Comment by ryuichl** [comment]
重複先關掉
