### ISSUE TITLE
【問題】表單題目設定跳題，但未讓指定題目在表單頂端

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1640]
單選題、線性評分、下拉式、手勢選答、手勢評分的題型，每個選項皆可設定跳題
![image](https://user-images.githubusercontent.com/41721950/68367080-c5d09400-016f-11ea-98e6-8dfdb8bc7e31.png)
但是指定跳題題目後，題目未在表單頂端
如下情境是點選『線性評分』，但是跳至『線性評分』的前一題在表單頂端
![image](https://user-images.githubusercontent.com/41721950/68367213-22cc4a00-0170-11ea-9ebb-da4e412aac66.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
表單題目設定跳題，已讓被跳的指定題目在表單頂端
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
此問題解決之後，連動#1501 問題重現了

**Comment by cocosu123** [comment]
為了解決 #1501 的問題，因此現在表單跳題的指定題目會顯示在表單正中間(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68636987-427cbd00-0538-11ea-93f7-7dec3eecc1f0.png)
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
表單題目設定跳題後，跳題的指定題目會顯示在表單正中間。
![image](https://user-images.githubusercontent.com/49626114/69505295-2af3fa00-0f64-11ea-803f-c71d55ae6790.png)
◎◎ 20191125確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
跳題的指定題目會顯示在表單較為中間的位置，若是長頁面整個表單會上移(橘框)
![image](https://user-images.githubusercontent.com/41721950/69529428-3cacc000-0fab-11ea-9348-71c262e18449.png)
◎◎ 20191125確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
跳題的指定題目會顯示在表單較為中間的位置，若是長頁面整個表單會上移(橘框) https://aa1.ryzoweba.com/
![image](https://user-images.githubusercontent.com/41721950/71876855-bca97680-3162-11ea-90e1-51765e73d636.png)

◎◎ 20200107確認以上測試環境內容MS SQL◎◎
