### ISSUE TITLE
【MS SQL】表單定量寄至信箱與原先設計不同

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1641]
正式環境會跟著回覆筆數，定量寄送郵件及excel
![image](https://user-images.githubusercontent.com/41721950/68368973-2661d000-0174-11ea-8488-783fafdc7912.png)
但測試環境超過『定量筆數』就每筆寄送郵件且無excel
![image](https://user-images.githubusercontent.com/41721950/68368904-f9adb880-0173-11ea-88c1-fb608ac3ca89.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
筆數的部分我會看
沒有EXCEL正常
這跟環境有關
有個資限制的不會寄發EXCEL

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68378733-90d03b80-0187-11ea-94b7-6a3829c43e44.png)
◎◎ 20191107確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68464313-63e55c80-024b-11ea-86c1-b50c32c30d14.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/68633765-07758c00-052e-11ea-8233-ea8fc0c9b180.png)
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/69410610-5e593d80-0d46-11ea-85f9-ce19ade78a6d.png)
◎◎ 20191122確認以上正式環境內容◎◎
