### ISSUE TITLE
【MS SQL】互動遊戲的登入按鈕設定顏色後的錯誤狀況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1642]
步驟1. 在互動遊戲變更登入前&登入後的按鈕顏色(圖A紅框處)
步驟2. 在顏色設定(圖B橘框處)點擊無反應，而且也關閉不了此視窗
步驟3. 離開互動遊戲編輯框後再回來就會變成圖C紅框處的樣子，且只要出現圖C的畫面此專案就無法恢復原貌。
![image](https://user-images.githubusercontent.com/49626114/68369247-c7e92180-0174-11ea-8ae6-d4b6a3c10511.png)

**Comment by AnitaRyzo** [comment]
目前已無此問題
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by cocosu123** [comment]
互動遊戲的登入按鈕設定顏色後已可正常呈現(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68455746-119a4080-0237-11ea-9706-1528747b3ce0.png)
◎◎ 20191108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
互動遊戲的登入按鈕設定顏色後已可正常呈現(橘框處)。
![image](https://user-images.githubusercontent.com/49626114/68565519-bebac600-048e-11ea-80b6-f4128414f664.png)
◎◎ 20191111確認以上測試環境內容MongoDB◎◎

**Comment by cocosu123** [comment]
互動遊戲的登入按鈕設定顏色後已可正常呈現。
![image](https://user-images.githubusercontent.com/49626114/69409899-d161b480-0d44-11ea-8a22-0e33612e1342.png)
◎◎ 20191122確認以上正式環境內容◎◎
