### ISSUE TITLE
【MS SQL】專案與套版管理開啟時間，時分會回到設定值

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1643]
無論是『專案發佈』或是『套版管理』的時間設定
設定值如下圖的綠框，再按下『更新專案』
![image](https://user-images.githubusercontent.com/41721950/68370406-637b9180-0177-11ea-8124-99eebf86ab14.png)
儲存後再次開啟，發現只有『年月日』被儲存，但是『時分』會跳回原始設定值
![image](https://user-images.githubusercontent.com/41721950/68370245-0384eb00-0177-11ea-8d63-25ca756ce45a.png)
以上問題請協助處理，感恩~

**Comment by qq076qq076** [comment]
問題描述  時間套件更換但是這裡沒有對應調整 導致於沒有辦法更新時間

**Comment by AnitaRyzo** [comment]
套版管理的時分仍會回到初始設定值，尚須修改
◎◎ 20191108確認以上一銀模擬環境內容◎◎

**Comment by AnitaRyzo** [comment]
『專案發佈』或是『套版管理』的時間設定皆可依照設定值
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
『專案發佈』或是『套版管理』的時間設定皆可依照設定值。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
『專案發佈』或是『套版管理』的時間設定皆可依照設定值。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
