### ISSUE TITLE
【MS SQL】資料綁定的分類顯示圖只能擇一

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1646]
資料綁定的分類顯示圖按下『選擇』會開啟『圖片庫』
![image](https://user-images.githubusercontent.com/41721950/68457043-48be2100-023a-11ea-928c-1e76f81ba7fc.png)
正式環境只能擇一，選了B就會自動取消A；但現在可以全選...
![image](https://user-images.githubusercontent.com/41721950/68457425-3a243980-023b-11ea-80f6-6df468b3f062.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
資料綁定的分類顯示圖只能擇一
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
資料綁定的分類顯示圖只能擇一，選了B就會自動取消A。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
資料綁定的分類顯示圖只能擇一，選了B就會自動取消A。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
