### ISSUE TITLE
【MS SQL】Banner刪除元件後，元件設定未關閉

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1648]
在Banner將畫面中的元件刪除後(從圖層設定可得知沒有元件存在畫面中)，右側的元件設定未被關閉(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68556055-a38a8f00-046b-11ea-8e41-16ee65e66b5d.png)
備註：Banner所有元件皆有此狀況發生。

**Comment by AnitaRyzo** [comment]
元件設定會在元件刪除時立刻被關閉
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
元件設定會在元件刪除時立刻被關閉。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
元件設定會在元件刪除時立刻被關閉。
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
