### ISSUE TITLE
【建議】各種文字輸入完成的確認鍵

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#165]
因為測試了新增提示的區塊，然後發現一個微妙的差異

新增提示，設定提示名稱時，當我輸入完點擊ENTER視同輸入完成

在地圖元件裡輸入完地址或地標時，點擊ENTER是換行，並且沒有確認的按鈕可以點選
必須點擊任意空白處，設定才會套用到編輯區塊裡

可能要統一下，不然輸入完地址的草民可能會很無助

**Comment by ryzojudy** [comment]
希望可以在地圖輸入地址的輸入框右下角新增一個完成按鈕
地址輸入完後，點擊完成紐內容才算確認
同時畫布中的地圖內容更新
麻煩 @liucwlewis 出畫面
感謝~~~~

**Comment by liucwlewis** [comment]
連結：https://zpl.io/aRYKvpN
<img width="242" alt="2018-07-25 11 40 23" src="https://user-images.githubusercontent.com/37163894/43178348-89625c8e-8fff-11e8-952c-314bbea42909.png">
