### ISSUE TITLE
【MS SQL】EDM網頁擷取的彈跳視窗不能按『上一步』

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1650]
EDM網頁擷取按鈕可開啟彈跳視窗
![image](https://user-images.githubusercontent.com/41721950/68556599-e0578580-046d-11ea-921c-62317320123b.png)
在此視窗中，點擊『上一步』不會發生任何事件
![image](https://user-images.githubusercontent.com/41721950/68556828-c36f8200-046e-11ea-9e25-3a699fc8b4a6.png)
目前解法：點選最上層的步驟數字
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
EDM網頁擷取的「上一步」已可正常執行。
◎◎ 20191113確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
EDM網頁擷取的「上一步」已可正常執行。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
EDM網頁擷取的「上一步」已可正常執行。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
