### ISSUE TITLE
【Mongo DB】幸運轉盤「測試結果」點擊測試按鈕前，預覽畫面未顯示獎項圖片

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1651]
幸運轉盤在點擊測試按鈕前左邊預覽畫面未顯示獎項圖片(紅框處)，點擊測試按鈕後獎項圖片才會顯示(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68567432-f2e4b580-0493-11ea-9b56-42a5b99ca054.png)

**Comment by cocosu123** [comment]
幸運轉盤在點擊測試按鈕前左邊預覽畫面已正常顯示獎項圖片。
![image](https://user-images.githubusercontent.com/49626114/68652404-563e1880-0564-11ea-9cec-74d0d85ec550.png)
◎◎ 20191008確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
幸運轉盤在點擊測試按鈕前左邊預覽畫面已正常顯示獎項圖片。
![image](https://user-images.githubusercontent.com/49626114/69407589-ca847300-0d3f-11ea-9e9a-94922a704931.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
獎項無論是jpg/png/gif檔，都不影響『測試結果』的測試按鈕按下前，預覽畫面皆正常顯示獎項圖片。
![image](https://user-images.githubusercontent.com/41721950/72048376-9c5ef080-32f7-11ea-96c8-15a52b63d508.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
