### ISSUE TITLE
【測試環境】九宮格的測試中獎的內容很久才回傳

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1652]
『測試結果』是提供給「設定獎項」的機率參考用
![image](https://user-images.githubusercontent.com/41721950/68569934-5a9dff00-049a-11ea-8cad-9d50bdf98356.png)
而『測試結果』只有「九宮格」跟「幸運轉盤」有預覽圖片
問題一：九宮格的動畫未完整執行(綠框)
問題二：執行時間超過八秒才會出現測試中獎的內容(橘框)
![image](https://user-images.githubusercontent.com/41721950/68569801-05fa8400-049a-11ea-8059-041250f3696e.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
九宮格的動畫已有完整執行，動畫執行結束後，測試中獎的內容也會即時顯示。
◎◎ 20191112確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
九宮格的動畫已有完整執行，動畫執行結束後，測試中獎的內容也會即時顯示。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
九宮格的動畫已有完整執行，動畫執行結束後，測試中獎的內容也會即時顯示。
![image](https://user-images.githubusercontent.com/41721950/72048716-62421e80-32f8-11ea-914b-ca85ad1c5ee3.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
