### ISSUE TITLE
【測試環境】表單元件在編輯區未能即時切換內容

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1653]
表單內的頁面與題目排序如下
![image](https://user-images.githubusercontent.com/41721950/68635837-b7e68e80-0534-11ea-8e45-83ce72a49def.png)
點選黃框切換頁面，但編輯區內容未有任何改變
必須要點擊「表單元件」外(=表單元件未被選取)，編輯區內容才會跳至「指定頁面」(橘框)
![image](https://user-images.githubusercontent.com/41721950/68635232-d8154e00-0532-11ea-97f4-b81a01f672ab.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
表單元件在編輯區切換頁面時，表單已會即時切換內容。
◎◎ 20191113確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
表單元件在編輯區切換頁面時，表單已會即時切換內容。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
一般表單與電子申請書在編輯區切換頁面時，點選右上角可即時切換表單內容。
![image](https://user-images.githubusercontent.com/41721950/71877373-e4e5a500-3163-11ea-8002-8065bcd29b3e.png)
◎◎ 20200107確認以上測試環境內容MS SQL◎◎
