### ISSUE TITLE
【測試環境】登出未能回到初始登入頁

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1654]
按下右上角的『登出』後，未自動開啟「初始登入頁」
無論是用何種方式登入，或是Network是否已回覆「登出成功」，都有此狀況
![image](https://user-images.githubusercontent.com/41721950/68639502-b9698400-053f-11ea-8598-4215463a63e6.png)
![image](https://user-images.githubusercontent.com/41721950/68639566-e61d9b80-053f-11ea-964f-55b551aab71e.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
不論是使用社群登入還是直接登入，登出後Network皆有回覆「登出成功」，且皆有正常回到初始登入頁。
![image](https://user-images.githubusercontent.com/49626114/68739123-0e31fb00-0623-11ea-8e95-ff1471af3095.png)
◎◎ 20191113確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
不論是使用社群登入還是直接登入，登出後Network皆有回覆「登出成功」，且皆有正常回到初始登入頁。
![image](https://user-images.githubusercontent.com/49626114/69406210-85127680-0d3c-11ea-82e7-da472ca1eaae.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
不論是使用社群登入還是直接登入，登出後Network皆有回覆「登出成功」，且皆有正常回到初始登入頁。
![image](https://user-images.githubusercontent.com/41721950/72047466-87815d80-32f5-11ea-80a3-cac894304f4b.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
