### ISSUE TITLE
【測試環境】電子申請書單開「跨帳號-下載」的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1655]
若「個人帳號之表單管理」未開啟「申請書回覆-下載」
![image](https://user-images.githubusercontent.com/41721950/68649927-c8136380-055e-11ea-83e9-86341c1b7d9b.png)
「跨帳號-下載申請書回覆」選擇回覆後(紅框)
![image](https://user-images.githubusercontent.com/41721950/68642128-ffc2e100-0547-11ea-9b3c-dce4d69327f4.png)
會出現以下提示訊息
![image](https://user-images.githubusercontent.com/41721950/68642169-2b45cb80-0548-11ea-8df7-16d6f4838b3f.png)

如下開啟權限，才可順利下載
![image](https://user-images.githubusercontent.com/41721950/68649895-ba5dde00-055e-11ea-888a-c24c563b2bdc.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
其實點那個眼睛就算是下載了
已經有下載PDF
查看的話就是可以看到回覆的列表

**Comment by AnitaRyzo** [comment]
點那個眼睛就算是下載→我了解。
但現在是『個人帳號之申請書管理-下載』影響『跨帳號之申請書管理-下載申請書回覆』了~

**Comment by cocosu123** [comment]
在『個人帳號之申請書管理-下載』的權限設定已不會影響『跨帳號之申請書管理-下載申請書回覆』。
◎◎ 20191113確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在『個人帳號之申請書管理-下載』的權限設定已不會影響『跨帳號之申請書管理-下載申請書回覆』。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
在『個人帳號之申請書管理-下載』的權限設定已不會影響『跨帳號之申請書管理-下載申請書回覆』。
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎
