### ISSUE TITLE
【測試環境】新增電子申請書的頁面與題目列表錯誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1656]
『新建』電子申請書時，在『題目編輯』頁面是『一般表單』的題型，而非『電子申請書』的；也缺少了『資料確認頁面』。
![image](https://user-images.githubusercontent.com/41721950/68646492-48819680-0556-11ea-95cd-84f3343501a6.png)
『編輯』電子申請書，才會出現正確的電子申請書『題型』與『料確認頁面』
![image](https://user-images.githubusercontent.com/41721950/68646655-ce9ddd00-0556-11ea-9f91-716a30f9fff8.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
新增電子申請書的頁面已增加『資料確認頁面』，題目列表也已刪除固定答案並增加『上傳圖片題型』&『電子簽名』。
![image](https://user-images.githubusercontent.com/49626114/68741344-54d62400-0628-11ea-91c1-dd3d2fe01040.png)
◎◎ 20191113確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
新增電子申請書的頁面已增加『資料確認頁面』，題目列表也已刪除固定答案並增加『上傳圖片題型』&『電子簽名』。
![image](https://user-images.githubusercontent.com/49626114/69404872-4a5b0f00-0d39-11ea-9ac2-5fcf96f397b2.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
無論是「新建或管理」電子申請書都是出現相同的「題目類型列表」
![image](https://user-images.githubusercontent.com/41721950/71879170-66d7cd00-3168-11ea-9193-94c983c3c54a.png)
◎◎ 20200107確認以上測試環境內容MS SQL◎◎
