### ISSUE TITLE
【測試環境】電子申請書的電子簽名與送出表單失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1657]
電子申請書的簽名題型，無論是「一般頁面」或「資料確認頁面」皆未出現『電子簽名按鈕』(紅框vs綠框)；在「資料確認頁面」正確應該出現『送出表單』(藍框)，但卻出現『下一頁』(橘框)，造成電子申請書無法進行到最後一步。
![image](https://user-images.githubusercontent.com/41721950/68647681-71575b00-0559-11ea-84bf-83bb3adce81a.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
電子申請書的電子簽名與送出表單按鈕皆有正常出現。
![image](https://user-images.githubusercontent.com/49626114/68746762-3a09ac80-0634-11ea-8e3d-47fe37bf83da.png)
◎◎ 20191113確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
電子申請書的電子簽名與送出表單按鈕皆有正常出現。
![image](https://user-images.githubusercontent.com/49626114/69404723-e7697800-0d38-11ea-951c-5c18a52e637a.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
電子申請書的電子簽名與送出表單按鈕皆有正常出現與運作。
![image](https://user-images.githubusercontent.com/41721950/71878877-b4076f00-3167-11ea-9347-be4a057e10dc.png)
◎◎ 20200107確認以上測試環境內容MS SQL◎◎
