### ISSUE TITLE
【問題】MGM獎項內容未隨活動不同而切換

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1660]
『互動後台管理』擇一有『條件達成人數』的mgm
![image](https://user-images.githubusercontent.com/41721950/68731370-c43d1b00-060a-11ea-9f97-7d46a7f13a6d.png)
從『條件達成人數』的「有底線的綠色數字」，可以開啟以下畫面
![image](https://user-images.githubusercontent.com/41721950/68731197-319c7c00-060a-11ea-98d5-2fab49fe2a87.png)
切換不同的活動(藍框)，可知『條件達成人數=0人』，但畫面依然保持在原先的達成人數與內文(紅框)
![image](https://user-images.githubusercontent.com/41721950/68731624-b6d46080-060b-11ea-9a7c-e8b0e90e84eb.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
從『條件達成人數』直接點選其他活動，會自動切換回『優惠及條件』那層。
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
從『條件達成人數』直接點選其他活動，會自動切換回『優惠及條件』那層。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
從『條件達成人數』的分頁，直接點選其他活動
![image](https://user-images.githubusercontent.com/41721950/72050583-738d2a00-32fc-11ea-884c-5e320f2eb0bf.png)
會自動切換回『中獎名單』那層。
![image](https://user-images.githubusercontent.com/41721950/72050574-6d974900-32fc-11ea-913b-0829ea2fdef5.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
