### ISSUE TITLE
【測試環境】收縮區塊的背景顏色點擊無反應

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1661]
收縮區塊的背景顏色(紅框處)點擊後無反應
![image](https://user-images.githubusercontent.com/49626114/68733353-5811e580-0611-11ea-8e42-3612f9387b33.png)
且會出現錯誤碼(如下圖)
![image](https://user-images.githubusercontent.com/49626114/68736283-26058100-061b-11ea-995c-3717a6982aff.png)

**Comment by AnitaRyzo** [comment]
收縮區塊的背景顏色可以設定
![image](https://user-images.githubusercontent.com/41721950/68921789-cf33af00-07b4-11ea-97f8-4ea1cc17fdd2.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
收縮區塊的背景顏色可以設定。
![image](https://user-images.githubusercontent.com/49626114/69403701-35c94780-0d36-11ea-8115-7993deb20d9f.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
收縮區塊的背景顏色與陰影可以設定並即時在畫布區顯示。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
