### ISSUE TITLE
【測試環境】MGM的分享前表單開回覆開關與顯示有差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1662]
互動後台管理的MGM，設定『分享前表單設計』會寫入後台(橘框)，同時出現『顯示表單回覆』的開關，預設是關閉(黃框)
![image](https://user-images.githubusercontent.com/41721950/68739415-ba73e180-0623-11ea-808d-7ce0d10ceb22.png)
當單擊點選後，會變成開啟『顯示表單回覆』；就會在原始社群資料後面加入『表單內容』。
若點選『觸及人數』(橘框)，會進入『階層關係』展開明細
![image](https://user-images.githubusercontent.com/41721950/68739594-29e9d100-0624-11ea-9eba-6338dee43f2e.png)
從『階層關係』展開明細點選離開(橘框)
![image](https://user-images.githubusercontent.com/41721950/68739676-56055200-0624-11ea-9c1d-cedb9a91aa78.png)
回到『社群列表』可以看到『顯示表單回覆』已關閉(藍框)，但卻顯示『表單內容』(紅框)；
此時再次點選會呈現『顯示表單回覆』已開啟，但『表單內容』卻消失的相反狀況。
![image](https://user-images.githubusercontent.com/41721950/68739786-a381bf00-0624-11ea-8065-5561fa2218cb.png)
![image](https://user-images.githubusercontent.com/41721950/68740143-5fdb8500-0625-11ea-8e42-c0af24ad560a.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
點選『觸及人數』前開啟『顯示表單回覆』，從『觸及人數』離開時，『顯示表單回覆』仍是開啟；反之則已。
![image](https://user-images.githubusercontent.com/41721950/68921503-f50c8400-07b3-11ea-82e6-e2b01f91972d.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
點選『觸及人數』前開啟『顯示表單回覆』，從『觸及人數』離開時，『顯示表單回覆』仍是開啟；反之則已。
![image](https://user-images.githubusercontent.com/49626114/69403508-b89dd280-0d35-11ea-94b7-f78bbb03fdba.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
點選『觸及人數』前開啟『顯示表單回覆』，從『觸及人數』離開時，『顯示表單回覆』仍是開啟；反之則已。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
