### ISSUE TITLE
【測試環境】互動元件的時間設定，時分會回到設定值

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1663]
受影響的元件：MGM、序號機、九種互動遊戲
MGM的『時效設定』，時間從「2019/11/13 12:01」修改為「2019/11/30 18:01」；Network回傳『mgm修改成功』，也按了『確認』與『專案儲存』。
![image](https://user-images.githubusercontent.com/41721950/68741174-eabd7f00-0627-11ea-80e5-bae33d8051b9.png)
離開專案再次進入後，發現『年月日』有寫入，但『時間』仍保持在「12:01」...
![image](https://user-images.githubusercontent.com/41721950/68741318-4425ae00-0628-11ea-96f3-4e4e0bf5e674.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
互動元件的時間設定，時分已依照指示
![image](https://user-images.githubusercontent.com/41721950/68922522-ce038180-07b6-11ea-90e6-433d957070f1.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
互動元件的時間設定，時分已依照指示呈現。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
互動元件的時間設定，時分已依照指示呈現。
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
