### ISSUE TITLE
【測試環境】電子申請書「檔案寄出頁」的文字顏色顯示有誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1664]
在電子申請書的「檔案寄出頁」
問題1. 調整下方文字的文字樣式顏色(綠框處)，會連動上方文字的文字樣式顏色，且在左邊畫布區只有上方文字的顏色會變動，下方文字不會跟著設定變動(紅框處)。
問題2. 上方文字陰影的顏色會連動下方文字，調整下方文字的陰影顏色畫布區無反應(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68744297-450e0e00-062f-11ea-8518-edff3ef2b5b9.png)

**Comment by cocosu123** [comment]
在電子申請書的「檔案寄出頁」的文字顏色皆有正確顯示。
![image](https://user-images.githubusercontent.com/49626114/69402337-7cb53e00-0d32-11ea-9a1a-9fb8074a840e.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
在電子申請書的「檔案寄出頁」的文字顏色皆有正確顯示。
![image](https://user-images.githubusercontent.com/41721950/72044713-7df4f700-32ef-11ea-8c9e-6f8e3b62e8b8.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
