### ISSUE TITLE
【問題】MGM專屬連結縮網址不該影響顯示連結產出頁

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1665]
MGM無論是否開啟『專屬連結縮網址』都應開啟『連結產出』頁，因『連結產出』頁提供的資料是關於「條件進度」，而且從設計也無從得知不會出現『連結產出』頁。
![image](https://user-images.githubusercontent.com/41721950/68745335-7687d900-0631-11ea-9db7-f71b84df52f2.png)
但目前若是「非縮網址」，就不會開啟『連結產出』頁
![image](https://user-images.githubusercontent.com/41721950/68745113-fcefeb00-0630-11ea-951d-7cf0467a0ab2.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/68925714-9b5d8700-07be-11ea-83fd-d6a355b49646.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
「非縮網址」(綠框處)會開啟『連結產出』頁(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/69402740-b8043c80-0d33-11ea-97fc-199972eea48c.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/72049146-50ad4680-32f9-11ea-91d8-e55fba275d32.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
