### ISSUE TITLE
【測試環境】電子申請書pdf頁面管理設定文字顏色後，表單無法送出

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1666]
電子申請書送出表單後，一直停留在資料確認頁，且後台也沒有表單資料回傳的紀錄。
![image](https://user-images.githubusercontent.com/49626114/68745764-370dbc80-0632-11ea-8260-443deace4fe1.png)
補充：在pdf設定文字顏色後，表單無法送出。

**Comment by ai015606220** [comment]
能提供這個專案給我嗎，我無法重現這個問題

**Comment by ai015606220** [comment]
顏色選擇器的輸出色碼格式必須為rgb

**Comment by AnitaRyzo** [comment]
顏色選擇器色碼格式已是rgb，電子申請書表單已可順利送出
![image](https://user-images.githubusercontent.com/41721950/68929100-90a6f000-07c6-11ea-9655-5332aa9eabdd.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
顏色選擇器色碼格式已是rgb，電子申請書表單已可順利送出
![image](https://user-images.githubusercontent.com/49626114/69401870-25fb3480-0d31-11ea-9d40-21a8683f51ee.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
顏色選擇器色碼格式已是rgb(或顯示hex)，電子申請書表單已可順利回傳與下載
![image](https://user-images.githubusercontent.com/41721950/71946571-3134f180-3205-11ea-8f38-fa9cd6c1d58e.png)
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎
