### ISSUE TITLE
【測試環境】序號狀態頁的陰影失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1667]
序號-狀態(提示)頁的「未索取」與「已索取」之所有頁籤(橘框)，
開啟『顯示進階設定』可以勾選「陰影」，但是將「陰影」開啟，卻無法設定陰影的細項
![image](https://user-images.githubusercontent.com/41721950/68818964-a979ad80-06c1-11ea-8358-a08d8baeaad6.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
序號-狀態(提示)頁的「未索取」與「已索取」之所有文字皆可設定陰影
![image](https://user-images.githubusercontent.com/41721950/68925107-4a995e80-07bd-11ea-9245-ae35007edbd6.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
序號-狀態(提示)頁的「未索取」與「已索取」之所有文字皆可設定陰影。
![image](https://user-images.githubusercontent.com/49626114/69401564-61e1ca00-0d30-11ea-9d1b-9b4123ac1aa9.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
序號-狀態(提示)頁的「未索取」與「已索取」之所有文字皆可設定陰影。
![image](https://user-images.githubusercontent.com/49626114/72120455-f234a680-3392-11ea-8f62-8a37ed40580a.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
