### ISSUE TITLE
【問題】QR Code商標圖設定無法連續上傳同一張圖片

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1668]
在QR Code產生器的「填充類型-圖片」和「商標圖設定」上傳A圖片後刪除(左圖黃框處)，再次上傳一樣的A圖片時，「填充類型」和「商標圖設定」完全沒反應(右圖紅框處)
![image](https://user-images.githubusercontent.com/49626114/68820443-34f53d80-06c6-11ea-83c6-afb9cba3b7e8.png)
暫解：刪除A圖片後改上傳B圖片，再次上傳A圖片，A圖片就會帶入。

**Comment by AnitaRyzo** [comment]
QR Code商標圖設定可以連續上傳同一張圖片
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
QR Code商標圖設定可以連續上傳同一張。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
QR Code商標圖設定可以連續上傳刪除同一張圖片
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
