### ISSUE TITLE
【測試環境】QR Code產生器設定顏色無反應

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1669]
問題1. 先設定「填充類型-顏色」的填充顏色時，右邊QR Code會變成一片空白(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68821119-64a54500-06c8-11ea-8258-f6964199d495.png)
問題2. 再設定「填充類型-顏色」的背景顏色時，右邊QR Code會出現，但是並未改變顏色(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/68821133-6ec74380-06c8-11ea-8857-7099a7dc4798.png)
問題3. 切換到「填充類型-圖片」時，改變背景顏色後，右邊QR Code也無反應(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68821152-7ab30580-06c8-11ea-9640-4828a204a83f.png)

**Comment by AnitaRyzo** [comment]
答1. 設定「填充類型-顏色」的填充顏色時，右邊QR Code會即時變色
![image](https://user-images.githubusercontent.com/41721950/68924081-e5dd0480-07ba-11ea-9eee-fda65a0d2cf4.png)
答2. 再設定「填充類型-顏色」的背景顏色時，右邊QR Code會即時變色
![image](https://user-images.githubusercontent.com/41721950/68924040-ca71f980-07ba-11ea-8c0e-05ba43bfec15.png)
答3. 切換到「填充類型-圖片」時，改變背景顏色後，右邊QR Code會即時變色
![image](https://user-images.githubusercontent.com/41721950/68924177-20df3800-07bb-11ea-85eb-20d242e459bc.png)
備註：『背景顏色』在顏色與圖片之間是共用的
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
設定顏色時，右邊QR Code皆會即時變色。
![image](https://user-images.githubusercontent.com/49626114/69401093-1549bf00-0d2f-11ea-8630-c01ba591e8d3.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
設定顏色時，右邊QR Code皆會即時變色。
而「背景顏色」是填充類型共用的
![image](https://user-images.githubusercontent.com/41721950/72041880-b09af180-32e7-11ea-90ad-d31717a8c5d9.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
