### ISSUE TITLE
【測試環境】圖片剪裁點選水平翻轉後，圖片未即時顯示

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1670]
在專案、Banner、EDM中的圖片剪裁選擇比例後，在點選水平翻轉鈕(紅框處)，會呈現黑畫面(黃框處)，需等一段時間圖片才會顯示。
![image](https://user-images.githubusercontent.com/49626114/68825097-ec448100-06d3-11ea-8733-4eb54d2a5164.png)

**Comment by cocosu123** [comment]
圖片剪裁點選水平翻轉已可正常執行。
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
圖片剪裁點選水平翻轉已可正常執行。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
圖片剪裁點選水平翻轉已可正常出現圖片
![image](https://user-images.githubusercontent.com/41721950/71965670-1aa98d00-323b-11ea-8c27-f6e8997469de.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
