### ISSUE TITLE
【測試環境】Banner圖片庫的圖片剪裁與圖片替換失效

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1671]
問題1. 在Banner圖片庫剪裁圖片(黃框處)後，回到畫布區查看圖片並未被剪裁(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68826074-5ad70e00-06d7-11ea-975d-20c369ed7711.png)
問題2. Banner圖片庫替換圖片(黃框處)後，回到畫布區查看圖片並未被替換(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68826134-8eb23380-06d7-11ea-966c-60e3338fe182.png)

**Comment by cocosu123** [comment]
Banner圖片庫的圖片剪裁與圖片替換皆可正常執行。
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
Banner圖片庫的圖片剪裁與圖片替換皆可正常執行。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
Banner圖片庫的「圖片剪裁」與「圖片替換」皆可正常執行
「圖片替換」即使是相同檔名也會正確出現圖片。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
