### ISSUE TITLE
【測試環境】Banner輸出檔案只會輸出一個畫布

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1673]
從畫布管理可得知有3個畫布，輸出畫布時選擇「全選」，
![image](https://user-images.githubusercontent.com/49626114/68826732-18630080-06da-11ea-8b83-98db47e3e6da.png)
輸出檔案後卻只有一個畫布。
![image](https://user-images.githubusercontent.com/49626114/68826764-2f095780-06da-11ea-9570-87366085e3e6.png)

**Comment by cocosu123** [comment]
Banner輸出檔案可輸出多個畫布。
![image](https://user-images.githubusercontent.com/49626114/68927822-9d761480-07c3-11ea-959a-24ee69e42675.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
Banner輸出檔案可輸出多個畫布。
![image](https://user-images.githubusercontent.com/49626114/69397184-36ef7a00-0d20-11ea-82b8-6273414f3a71.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
Banner可以同時輸出多個畫布。
![image](https://user-images.githubusercontent.com/41721950/71964548-c1d8f500-3238-11ea-8770-2fad1da48b9a.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
