### ISSUE TITLE
【測試環境】Banner內容生成不能只有純背景

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1674]
若畫布只設定背景顏色，選擇內容生成後，生成複製的畫布會是空白的(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68830641-253a2100-06e7-11ea-8e53-658a93908422.png)
若畫布內有元件，選擇內容生成後，生成複製的畫布才會跟原畫布相同(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68830666-37b45a80-06e7-11ea-80b5-be6e082750a6.png)

**Comment by cocosu123** [comment]
畫布只設定背景顏色已可以選擇內容生成複製畫布。
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
畫布只設定背景顏色已可以選擇內容生成複製畫布(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/69397066-9731ec00-0d1f-11ea-914a-a31fbaf2cd33.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
畫布只設定背景顏色，可以選擇「內容生成」複製畫布
![image](https://user-images.githubusercontent.com/41721950/71964310-48d99d80-3238-11ea-8ad5-ca1bcc326e97.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
