### ISSUE TITLE
【測試環境】Banner素材庫選擇其它圖片後，未留在元件編輯區

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1675]
圖片庫的蘋果從「素材選擇設定」切換成香蕉後，會跳離編輯框未留在元件上(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68832674-84e6fb00-06ec-11ea-9c47-884a229de345.png)
同樣的操作在io環境，佩佩豬從「素材選擇設定」切換成辛普森後，依然會停留在編輯框(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68832761-c4ade280-06ec-11ea-88ac-0e984c99171e.png)

**Comment by ai015606220** [comment]
可以再詳述一下操作行為嗎? 我這邊不會出現這個情況

**Comment by AnitaRyzo** [comment]
補充：兩個以上的畫布或是畫布中有群組的物件時，都會發生此狀況
![image](https://user-images.githubusercontent.com/41721950/68838783-422c1f80-06fa-11ea-96e4-e70894d37cc0.png)

**Comment by cocosu123** [comment]
「兩個以上的畫布」或是「畫布中有群組的物件」時，將圖片庫的圖片從「素材選擇設定」切換成其他圖片後，依然會停留在編輯框。
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
「兩個以上的畫布」或是「畫布中有群組的物件」時，將圖片庫的圖片從「素材選擇設定」切換成其他圖片後，依然會停留在編輯框。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
「兩個以上的畫布」或是「畫布中有群組的物件」時，
![image](https://user-images.githubusercontent.com/41721950/72034357-bc7ab980-32cf-11ea-88ac-83e8e4fc45be.png)
將圖片庫的圖片從「素材選擇設定」切換成其他圖片後，依然會停留在編輯框。
![image](https://user-images.githubusercontent.com/41721950/72034391-d3b9a700-32cf-11ea-9c5b-350d3e3568eb.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
