### ISSUE TITLE
【測試環境】Banner素材文案庫編輯區跟畫布不同步

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1676]
問題1.
x文案從「素材選擇設定」切換成o文案，會跳離編輯框未留在元件上(紅框處)。
點擊元件查看時，「素材選擇設定」區已變更成o文案(綠框處)，但是畫布上的x文案未變更成o文案(藍框處)。
![image](https://user-images.githubusercontent.com/49626114/68834990-04c39400-06f2-11ea-8948-adc51f7c1750.png)
同樣的操作在io環境，a文案從「素材選擇設定」切換成b文案，會停留在編輯框且畫布上的文案有即時變更(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68833059-82d16c00-06ed-11ea-9e84-aff1638b5b6a.png)
問題2.
在「素材選擇設定」編輯文案後，按儲存會跳離編輯框未留在元件上(紅框處)。
點擊元件查看時，編輯內容是有寫入的(綠框處)，但是畫布上的文案內容未變更(籃框處)。
![image](https://user-images.githubusercontent.com/49626114/68834583-19ebf300-06f1-11ea-9e55-0ef9ddf8643f.png)
同樣的操作在io環境，編輯文案後按儲存，會停留在編輯框且畫布上的文案內容有即時變更(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68834320-726ec080-06f0-11ea-8815-08d738325267.png)

**Comment by cocosu123** [comment]
1.a文案從「素材選擇設定」切換成b文案，會停留在編輯框且畫布上的文案有即時變更。
2.編輯文案後按儲存，會停留在編輯框且畫布上的文案內容有即時變更。
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1. 文案切換會停留在編輯框且畫布上的文案有及時變更。
2. 編輯文案後按儲存，會停留在編輯框且內容有即時變更。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
一：文案切換會停留在編輯框且畫布上的文案有及時變更。
![image](https://user-images.githubusercontent.com/41721950/72033992-cb14a100-32ce-11ea-9a12-19e654c8f47d.png)
二、編輯文案後按儲存，會停留在編輯框且內容有即時變更。
![image](https://user-images.githubusercontent.com/41721950/72034106-162eb400-32cf-11ea-988a-b6257b7d39b9.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
