### ISSUE TITLE
【測試環境】EDM的積木在繁體世界顯示簡體

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1677]
EDM的積木下拉式類型文字在『繁體語系』卻顯示簡體
![image](https://user-images.githubusercontent.com/41721950/68840609-072beb00-06fe-11ea-9d72-7066a627247f.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/68921509-fa69ce80-07b3-11ea-90e0-03d9bb249f8b.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/69396546-8ed8b180-0d1d-11ea-8287-68f8411b5a6f.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
EDM的積木在繁體世界顯示繁體中文
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
