### ISSUE TITLE
【測試環境】EDM影片的框線失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1678]
EDM影片的框線選取後，無法做任何設定
![image](https://user-images.githubusercontent.com/41721950/68844241-6f7dcb00-0704-11ea-97f1-e778d35df6d6.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/68844315-90462080-0704-11ea-8fdf-8d807455e885.png)
備註：寄至郵件發現影片沒有擷圖
![image](https://user-images.githubusercontent.com/41721950/68844791-5590b800-0705-11ea-9ec6-ef91b9851bbe.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
EDM影片的框線已正常呈現
![image](https://user-images.githubusercontent.com/49626114/68921426-ac54cb00-07b3-11ea-97bf-c47c53efd1b9.png)
寄至郵件影片已有擷圖。
![image](https://user-images.githubusercontent.com/49626114/68921445-bd054100-07b3-11ea-849f-1c6bdddf3184.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/69396104-2937f580-0d1c-11ea-8687-6ac36243ba12.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
EDM影片的框線已正常呈現
![image](https://user-images.githubusercontent.com/41721950/72037852-6bbc8e00-32da-11ea-8765-88ec2e45eff4.png)
試寄、預覽、輸出檔案皆可看到影片有框線
![image](https://user-images.githubusercontent.com/41721950/72037987-e2f22200-32da-11ea-8b91-48da635648db.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
