### ISSUE TITLE
【測試環境】發佈中的專案再次送審，發佈設定的提示訊息未出現

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1680]
發佈中的專案再次送審，專案會再次出現在『專案審核』區
![image](https://user-images.githubusercontent.com/41721950/68910591-50774b80-078d-11ea-9e08-a3ac8c3562e5.png)
若此時直接在『專案發佈』區按下『更新專案』按鈕，就會不斷旋轉(紅框)然後靜止
![image](https://user-images.githubusercontent.com/41721950/68910666-92a08d00-078d-11ea-8f43-48649ffc9d65.png)
正式環境應該要出現提示訊息
![image](https://user-images.githubusercontent.com/41721950/68910789-fa56d800-078d-11ea-8f79-96e18b10b7e2.png)
錯誤訊息如下，請參考
![image](https://user-images.githubusercontent.com/41721950/68910693-9f24e580-078d-11ea-9d7f-554a63a4867f.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
發佈中的專案再次送審，發佈設定的提示訊息已會正常跳出。
![image](https://user-images.githubusercontent.com/49626114/68920665-ec667e80-07b0-11ea-93bb-c1d44f67b2ed.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
發佈中的專案再次送審，會跳出發佈設定的提示訊息。
![image](https://user-images.githubusercontent.com/49626114/69395848-618b0400-0d1b-11ea-8402-aa4a309f3bc9.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72120983-a08d1b80-3394-11ea-868d-39268088e754.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
