### ISSUE TITLE
【測試環境】UTM繁體中文語系出現英文描述

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1681]
![image](https://user-images.githubusercontent.com/41721950/68911493-2410fe80-0790-11ea-82f0-8de503554c2a.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/68920480-4ca8f080-07b0-11ea-963c-f5f6e4685144.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/69395546-51265980-0d1a-11ea-871e-757338b10e9c.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72120687-b9e19800-3393-11ea-9e8d-98043ce81311.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
