### ISSUE TITLE
【問題】曾創建團隊後又被移除團隊管理權限，不應有刪除團隊按鈕

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1682]
「管理者後台-團隊相關」權限關閉，「團隊管理-團隊管理」權限也關閉(黃框處)
![image](https://user-images.githubusercontent.com/49626114/68914828-cafa9800-079a-11ea-9837-0c55d2b15d7a.png)
在自己創建的團隊裡有「刪除此團隊」的按鈕(橘框處)
![image](https://user-images.githubusercontent.com/49626114/68914874-f8dfdc80-079a-11ea-9fe7-9564c7a914d6.png)
但是按了之後network顯示「權限不足」(紅框處)，團隊不會被刪除。
![image](https://user-images.githubusercontent.com/49626114/68914911-19a83200-079b-11ea-8868-63ae9070958d.png)

**Comment by cocosu123** [comment]
「管理者後台-團隊相關」權限關閉，「團隊管理-團隊管理」權限也關閉的情況下，在自己創建的團隊裡已無「刪除此團隊」的按鈕(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/68920396-0a7faf00-07b0-11ea-85c5-59bc4e8a8981.png)
◎◎ 20191115確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
「管理者後台-團隊相關」權限關閉，「團隊管理-團隊管理」權限也關閉的情況下，在自己創建的團隊裡已無「刪除此團隊」的按鈕。
![image](https://user-images.githubusercontent.com/49626114/69395415-d8270200-0d19-11ea-9ab0-1668d7c6f537.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
「管理者後台-團隊相關」與「團隊管理-團隊管理」權限皆關閉的情況下，在自己創建的團隊裡已無「刪除此團隊」的按鈕。
![image](https://user-images.githubusercontent.com/41721950/72118003-a978ef80-338a-11ea-9522-7789926350af.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
