### ISSUE TITLE
【測試環境】Banner文案庫群組後，編輯區跟畫布不同步

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1683]
#1676 的延續問題
將文案庫的文案群組後，在右邊的「素材選擇設定」做編輯或是切換其他文案庫，在畫布區無反應(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/68923635-ba0d4f00-07b9-11ea-8779-684564225435.png)

**Comment by cocosu123** [comment]
將文案群組後，在「素材選擇設定」編輯或是切換其他文案庫，畫布區已即時變更。
◎◎ 20191118確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
將文案群組後，在「素材選擇設定」編輯或是切換其他文案庫，畫布區已即時變更。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
將文案群組後，在「素材選擇設定」編輯或是切換文案庫中其他文案，畫布區都會即時變更。
![image](https://user-images.githubusercontent.com/41721950/72033643-dfa46980-32cd-11ea-923b-525f398095dd.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
