### ISSUE TITLE
【測試環境】專案確認已儲存，但點選主選單仍跳暫存的提示訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1684]
專案編輯後，已跳出『進行儲存中』的提示訊息
![image](https://user-images.githubusercontent.com/41721950/68926227-fcd22580-07bf-11ea-8e1f-8d3a8205739a.png)
但點選左上角的主選單後，仍出現暫存的提示訊息
![image](https://user-images.githubusercontent.com/41721950/68926298-25f2b600-07c0-11ea-93aa-4155dff249b4.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
專案確認已儲存，就不會跳出『暫存的提示訊息』
◎◎ 20191118確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
專案確認已儲存，就不會跳出『暫存的提示訊息』。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
專案確認已儲存，就不會跳出『暫存的提示訊息』。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
