### ISSUE TITLE
【測試環境】電子申請書之PDF頁面管理的文字設定差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1686]
電子申請書之PDF頁面管理的文字設定，多出的粗體與斜體，點按之後沒有反應
![image](https://user-images.githubusercontent.com/41721950/68928170-69e7ba00-07c4-11ea-912b-c37d8a91115a.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
電子申請書之PDF頁面管理的文字設定，只剩下底線與刪除線的設計
◎◎ 20191118確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
電子申請書之PDF頁面管理的文字設定，只剩下底線與刪除線的設計。
![image](https://user-images.githubusercontent.com/49626114/69394014-bf1c5200-0d15-11ea-8bc5-d4eac614d706.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
電子申請書之PDF頁面管理的文字設定，只剩下底線與刪除線的設計。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
