### ISSUE TITLE
【問題】曾創建團隊後又被移除團隊管理權限，不可再度修改團隊名稱

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1687]
#1682 延伸問題
「管理者後台-團隊相關」與「團隊管理-團隊管理」權限皆關閉
在自己創建的團隊裡有『修改團隊名稱』的圖示，但實際執行後是失敗的
![image](https://user-images.githubusercontent.com/41721950/68930912-5ccdc980-07ca-11ea-8ce6-9ba863f70668.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/68930985-8555c380-07ca-11ea-9b82-a34abf398e64.png)
請協助修改此問題，感恩~

**Comment by AnitaRyzo** [comment]
即使是創建團隊者，在「管理者後台-團隊相關」與「團隊管理-團隊管理」權限皆關閉時，就不能編輯團隊名稱與系列動作。
![image](https://user-images.githubusercontent.com/41721950/69030972-f3d99200-0a13-11ea-8a93-0ad082b35e15.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
即使是創建團隊者，在「管理者後台-團隊相關」與「團隊管理-團隊管理」權限皆關閉時，就不能編輯團隊名稱與系列動作。
![image](https://user-images.githubusercontent.com/49626114/69393914-6fd62180-0d15-11ea-92ba-f4763542fb43.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
即使是創建團隊者，在「管理者後台-團隊相關」與「團隊管理-團隊管理」權限皆關閉時，就不能編輯團隊名稱。
![image](https://user-images.githubusercontent.com/41721950/72118138-2efc9f80-338b-11ea-8cab-730411df130f.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
