### ISSUE TITLE
【測試環境】幻燈片的名稱未輸入會被自動刪除

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1688]
複製幻燈片後，雙點擊『幻燈片』可以修改幻燈片名稱
![image](https://user-images.githubusercontent.com/41721950/69028045-c12b9b80-0a0b-11ea-9452-895cb7dd1de0.png)
在測試環境，雙點擊『幻燈片』名稱後，點選編輯區的元件，名稱就會變成空白「undefined」
![image](https://user-images.githubusercontent.com/41721950/69028078-d6082f00-0a0b-11ea-9487-4efd3e2a16bd.png)
而在正式環境，雙點擊『幻燈片』名稱後，點選編輯區的元件，名稱會保持在「幻燈片」
![image](https://user-images.githubusercontent.com/41721950/69028175-1f587e80-0a0c-11ea-8b8e-e6f719ee550b.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
測試環境雙點擊『幻燈片』名稱後，點選編輯區的元件，名稱會保持在「幻燈片」
◎◎ 20191118確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
測試環境雙點擊『幻燈片』名稱後，點選編輯區的元件，名稱會保持在「幻燈片」。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
雙點擊『幻燈片』名稱後，點選編輯區的元件，名稱會保持在「幻燈片」。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
