### ISSUE TITLE
【問題】EDM未跳出暫存恢復的提示訊息

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1689]
操作步驟如下：
1.在EDM進行操作，未儲存專案直接按左上角的dashboard離開專案(下圖橘框處)。
2.離開專案前會先跳出提示訊息(下圖綠框處)，選擇確定暫存。
![image](https://user-images.githubusercontent.com/49626114/69111019-47e98280-0ab7-11ea-8a41-c235d7c6eaf4.png)
3.再次回到此專案時，應該要跳出下圖的提示訊息，但是在EDM並未跳出暫存恢復的提示訊息，內容是離開前的設計狀態。
![image](https://user-images.githubusercontent.com/49626114/69111122-87b06a00-0ab7-11ea-9384-3db3bab9f531.png)
備註：在專案&Banner中，依照上述相同的步驟操作皆會跳出「上次離開時尚未儲存，是否要恢復?」的提示訊息。

**Comment by cocosu123** [comment]
依照上述操作，再次回到EDM專案時，會跳出暫存恢復的提示訊息。
◎◎ 20191121確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述操作，再次回到EDM專案時，會跳出暫存恢復的提示訊息。
![image](https://user-images.githubusercontent.com/49626114/69390997-51b7f380-0d0c-11ea-964a-09021d4a794d.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
EDM的暫存與恢復的訊息
![image](https://user-images.githubusercontent.com/41721950/72035330-8854c800-32d2-11ea-9934-7fffe802dbb3.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
