### ISSUE TITLE
【建議】幸運轉盤右側設定欄位

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#169]
哈囉，剛剛使用了幸運轉盤的功能

發現轉盤右側設定裡，當滑動到獎項設定的時候，會出現內外兩層捲軸，造成滑動跟點擊的不便利

建議可以讓獎項的區塊直接展開，變成只有一個捲軸
(依轉盤的樣式來看，應該也無法新增太多獎品，右側本來就已經很長了，再增加一點也無妨)

目前的雙捲軸設定如果獎品數量多，佔滿整個區域的時候，一定會發生二版的網格滑不動的情形，必須要用滑鼠去點擊外層捲軸進行捲動

**Comment by ryzojudy** [comment]
更改為預設顯示四個獎項
當有第五個獎項需設定時 一律需進入放大狀態
會有小字提示
再麻煩路意思出圖 @liucwlewis

**Comment by ryzojudy** [comment]
好
那就直接整塊拿掉 換成一個按鈕
一樣麻煩lewis出圖
@liucwlewis

**Comment by ryuichl** [comment]
建議
裡面是不是可以剛開始全部收起來
然後可以再收起來狀態改數量和機率

打開時可以設定圖片和顏色
這樣畫面感覺比較乾淨

![image](https://user-images.githubusercontent.com/10150807/40819464-ca110484-658d-11e8-863a-eeb6db7732d6.png)

**Comment by liucwlewis** [comment]
右側控制欄修改後，如圖：
左側為原始狀態，右側為修正後版本。將獎項挪出深色區域，獨立成為按鈕，須透過提示框才可設定獎項
<img width="975" alt="2018-06-01 2 53 56" src="https://user-images.githubusercontent.com/37163894/40825919-b06deda8-65ab-11e8-8359-4c4958346b00.png">
----------------------------------------------------------
提示框修正後，如圖:
第一排為收合狀態，
可直接設定數量及機率。開啟狀態維持原樣
<img width="1017" alt="2018-06-01 3 35 32" src="https://user-images.githubusercontent.com/37163894/40827842-7989bf5a-65b1-11e8-9ecf-de9e51d18add.png">
