### ISSUE TITLE
【測試環境】Banner暫存後無法回到專案中

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1690]
操作步驟如下：
1.在Banner進行操作，未儲存專案直接按左上角的dashboard離開專案(下圖橘框處)。
2.離開專案前會先跳出提示訊息(下圖綠框處)，選擇確定暫存。
![image](https://user-images.githubusercontent.com/49626114/69111630-183b7a00-0ab9-11ea-9bab-4b6f36e48245.png)
3.再次回到Banner專案時，會跳出下圖的提示訊息
![image](https://user-images.githubusercontent.com/49626114/69111701-520c8080-0ab9-11ea-9922-788ce5a0db80.png)
4.不管選擇「取消」或「確認」，畫面會一直呈現如下圖的狀態，完全無法回到Banner專案，且此專案就壞了無法再使用。
![image](https://user-images.githubusercontent.com/49626114/69111774-8a13c380-0ab9-11ea-861c-e492bea11b5f.png)

**Comment by ai015606220** [comment]
發現這是在開發階段會被避開的bug

**Comment by cocosu123** [comment]
依照上述操作，再次回到Banner專案選擇完暫存恢復的提示訊息後，就能夠直接進入編輯Banner專案。
◎◎ 20191121確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述操作，再次回到Banner專案選擇完暫存恢復的提示訊息後，就能夠直接進入編輯Banner專案。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
依照上述操作，再次回到Banner專案選擇完暫存恢復的提示訊息後，就能夠直接進入編輯Banner專案。
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
