### ISSUE TITLE
【問題】電子申請書未填寫完成卻可跳至檔案寄出頁

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1692]
電子申請書未填寫完成(橘框處)就送出表單時，依然會跳至「檔案寄出頁」，且會跳出提示訊息(黃框處)，若點擊下載PDF則會出現綠框處的錯誤碼。
![image](https://user-images.githubusercontent.com/49626114/69124738-5f3c6600-0adf-11ea-9ab0-bcae37fcea0a.png)

**Comment by cocosu123** [comment]
電子申請書未填寫完成就送出表單時，會跳出提示訊息停留在未完成的地方，直到表單填寫完成才會跳至「檔案寄出頁」。
![image](https://user-images.githubusercontent.com/49626114/69324386-508eb400-0c83-11ea-99dd-74be66a72670.png)
◎◎ 20191121確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
電子申請書未填寫完成就送出時，會跳出提示訊息停留在未完成的地方，直到表單填寫完成送出後才會跳至「檔案寄出頁」。
![image](https://user-images.githubusercontent.com/49626114/69390774-6a73d980-0d0b-11ea-9cbc-5b34caccf7e7.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
電子申請書未填寫完成按下「送出」按鈕，會跳出提示訊息停留在未完成且是必填的題目，直到表單填寫完整，再按「送出」按鈕才會跳至「檔案寄出頁」。
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎
