### ISSUE TITLE
【問題】電子申請書編輯時，PDF的檔案寄出頁圖層錯誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1693]
『單幻燈片』的元件大於10個後，編輯電子申請書設定的『檔案寄出頁』
![image](https://user-images.githubusercontent.com/41721950/69125519-f0600c80-0ae0-11ea-9594-e3b8e57edbfa.png)
圖層顯示有誤
![image](https://user-images.githubusercontent.com/41721950/69125081-f0abd800-0adf-11ea-9ccd-7c282a1e5c37.png)
正確顯示應該要如下
![image](https://user-images.githubusercontent.com/41721950/69115025-24780500-0ac2-11ea-95f8-8e74523ac080.png)
發佈後雖然沒有問題，但編輯時會讓編輯者產生疑惑
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
『單幻燈片』的元件大於10個(黃框處)，編輯電子申請書設定的『檔案寄出頁』圖層以正常呈現(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/69324959-5cc74100-0c84-11ea-85ac-8147508a61fd.png)
◎◎ 20191121確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
『單幻燈片』的元件大於10個(綠框處)，『檔案寄出頁』圖層已正常呈現(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/69390324-d48b7f00-0d09-11ea-89cc-da5aab6cd72f.png)
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
『單幻燈片』的元件大於10個(右圖)，『檔案寄出頁』圖層已正常呈現(左圖)
![image](https://user-images.githubusercontent.com/41721950/72043570-7da72c80-32ec-11ea-8ce1-772a61c56056.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
