### ISSUE TITLE
【問題】表單與申請書的下拉式題型的選項一出現的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1694]
無論是在表單或是電子申請書都有此狀況
問題一：下拉式題型保持在『選項一』，按了『完成』沒寫入
問題二：選了『選項二』卻突然顯示『選項一』的答案
![8y4ca-i2foe](https://user-images.githubusercontent.com/41721950/69200601-96118b00-0b76-11ea-979b-d391edf41018.gif)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
表單或是電子申請書的下拉選項改停留在選項內容，而非第一個選項。
![下拉](https://user-images.githubusercontent.com/41721950/70697630-d3de7b00-1d00-11ea-998b-bf5f544e17d7.gif)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
表單與電子申請書的下拉選項改停留在「選項內容」，而非第一個選項。
◎◎ 20200107確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
表單與電子申請書的下拉選項改停留在「選項內容」，而非第一個選項。
◎◎ 20200109確認以上正式環境內容◎◎
