### ISSUE TITLE
【疑問】手機顯示網頁白名單以外，顯示提示訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1695]
曾經制訂過可以開啟WEBA網頁的『手機白名單』如下，除了『白名單』之外的一律顯示『請用內建瀏覽器』的訊息。
inappArr = ['facebook', 'line', 'messenger', 'instagram'];
inBrowser =[ Safari、Chrome、Firefox、Edge]
在iPhone與Android上雖然大部分的網頁會開啟『預設瀏覽器』，但現在出現『QR 掃描器』的軟體會直接開啟網頁，請協助確認是否要顯示『請用內建瀏覽器』的訊息。
![image](https://user-images.githubusercontent.com/41721950/69208130-6c179300-0b8d-11ea-9dc4-667a653ae6ea.png)
以上疑問請協助處理，感恩~

**Comment by ryuichl** [comment]
因為富邦的案子他們IT來不急修改對應設定
所以目前是全開放的

**Comment by ryuichl** [comment]
非bug
先關掉了
