### ISSUE TITLE
【測試環境】元件設定區超線選取後，能否保持選取著元件?

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1696]
點選元件後會自動開啟「元件設定區」，若在此處複製「可編輯的字元」，而滑鼠指標超過橘色線才放開左鍵時，元件會立刻取消選取...
![image](https://user-images.githubusercontent.com/41721950/69214892-24036b00-0ba3-11ea-99ed-4964a3348e30.png)
但在正式環境即使滑鼠指標超過橘色線，必須再次點選空白處才會取消選取元件
現在測試環境很容易就跳離「元件設定區」，有點不方便
以上疑問請協助處理，感恩~

**Comment by ai015606220** [comment]
我看不懂...

**Comment by AnitaRyzo** [comment]
超過橘色線才放開左鍵時，元件仍會保持選取
◎◎ 20191121確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
超過橘色線才放開左鍵時，元件仍會保持選取。
◎◎ 20191122確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
超過橘色線才放開左鍵時，元件仍會保持選取。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
