### ISSUE TITLE
【問題】設定表格內容視窗內按倒退鍵，會刪除元件或無法再編輯

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1697]
表格設定視窗內，若打字游標未在「輸入格」內，按Backspace鍵或是Delete鍵，會刪除表格元件
![image](https://user-images.githubusercontent.com/41721950/69225446-646de380-0bb9-11ea-96c5-95ca047d3ca6.png)
在正式環境雖然不會因此而刪除表格元件，但也無法再編輯
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/69225846-19a09b80-0bba-11ea-93b4-bf0829ea24ad.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
但游標不在輸入框之內時，按Backspace鍵或是Delete會刪掉元件應該是很合理吧?

**Comment by AnitaRyzo** [comment]
表格與內嵌程式碼元件的彈跳視窗僅為放大之用，若打字游標未在「輸入格」內，按Backspace鍵或是Delete鍵，就會刪除元件。
待正式環境更新後，確認不會再出現錯誤訊息即可結案。

**Comment by cocosu123** [comment]
表格與內嵌程式碼元件的彈跳視窗僅為放大之用，若打字游標未在「輸入格」內，按Backspace鍵或是Delete鍵，就會刪除元件，且不會再出現錯誤訊息。
◎◎ 20191122確認以上正式環境內容◎◎
