### ISSUE TITLE
【疑問】收縮區塊與頁籤的標題高度能否使用鍵入數值的方式

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1698]
收縮區塊與頁籤的「標題高度」拉Bar條可以調整「1px」，右側也像是可以輸入(紅框)
![image](https://user-images.githubusercontent.com/41721950/69293231-37fea980-0c43-11ea-86cf-24c96b1689a2.png)
但輸入第一個「鍵」會出現「20px」，輸入第二個「鍵」會出現「100px」
![image](https://user-images.githubusercontent.com/41721950/69292643-9460c980-0c41-11ea-8252-ce2d85501174.png)
請確認是否能使用「鍵入數值」並進行調整，感恩~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/70763528-50b83600-1d8f-11ea-8b82-37d0b131c5fb.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
已可鍵入數值
![image](https://user-images.githubusercontent.com/49626114/71963296-48400780-3236-11ea-918f-7d6aacfa519e.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
收縮區塊與頁籤的標題高度已可鍵入數值
![image](https://user-images.githubusercontent.com/41721950/72117415-8f3e1200-3388-11ea-8634-53b7c671ed99.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
