### ISSUE TITLE
【問題】EDM按鈕的空格未依照設定呈現

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1699]
在編輯區設定按鈕文字最左 / 右邊加上空格(黃框處)+對齊方式選擇靠左 / 右對齊(橘框處)，但是實際上並未依照設定的方式去呈現(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/69293933-51a0f080-0c45-11ea-92d1-8617cbb6a045.png)
備註：在EDM編輯區、預覽、試寄、輸出檔案皆未依照設定呈現。

**Comment by AnitaRyzo** [comment]
在EDM編輯區、預覽、試寄、輸出檔案皆依照設定呈現。
![image](https://user-images.githubusercontent.com/41721950/70764663-2c5e5880-1d93-11ea-838a-a6a97f80e4ef.png)
![image](https://user-images.githubusercontent.com/41721950/70764571-e7d2bd00-1d92-11ea-9767-ff2b71863fd2.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在EDM編輯區、預覽、試寄、輸出檔案皆依照設定呈現。
![image](https://user-images.githubusercontent.com/49626114/71961289-fd23f580-3231-11ea-94b3-d622c2b0ee6b.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
在EDM編輯區、預覽、試寄、輸出檔案皆依照設定呈現。
![image](https://user-images.githubusercontent.com/41721950/72037289-93125b80-32d8-11ea-9891-0cdc0bacfc25.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
