### ISSUE TITLE
【測試環境】表單與申請書在編輯區的預覽切換失敗

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1700]
表單與電子申請書在編輯區可以做「題目頁面」的切換
但是按下「頁面切換往右」後(橘框)，整個「頁面切換」消失且頁面也沒有切換
![image](https://user-images.githubusercontent.com/41721950/69300088-3cc85b00-0c4d-11ea-80ae-2cfd13164ea1.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
一般表單與電子申請書在編輯區可以正確執行「題目頁面」的預覽切換
![image](https://user-images.githubusercontent.com/41721950/70690799-69264300-1cf2-11ea-9bb7-a0b5a0042db2.png)
而抽獎表單與序號表單沒有此功能
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
一般表單與電子申請書在編輯區可以正確執行「題目頁面」的預覽切換
![image](https://user-images.githubusercontent.com/41721950/71879598-67249800-3169-11ea-8e11-9e72f8e57077.png)
◎◎ 20200107確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
一般表單與電子申請書在編輯區可以正確執行「題目頁面」的預覽切換。
![image](https://user-images.githubusercontent.com/49626114/72031715-30b15f00-32c8-11ea-8827-7427850ab222.png)
◎◎ 20200109確認以上正式環境內容◎◎
