### ISSUE TITLE
【測試環境】表單與申請書的按鈕設定，陰影功能未能正確執行

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1702]
表單與電子書的按鈕，可以設定「陰影」(橘框)
問題一：設定「陰影」但編輯區的按鈕未顯示
![image](https://user-images.githubusercontent.com/41721950/69303087-a4cf6f00-0c56-11ea-9b87-199261a96048.png)
開啟『預覽』發現設定的值有帶入
![image](https://user-images.githubusercontent.com/41721950/69303172-ecee9180-0c56-11ea-90c2-a8e4fe31af4b.png)
問題二：不能取消勾選「陰影」
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
解決問題一：設定「陰影」後，編輯區的按鈕會立即顯示
未解決問題二：不能取消勾選「陰影」
◎◎ 20191121確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
解決一：設定「陰影」後，編輯區的按鈕會立即顯示
解決二：可以取消勾選「陰影」的元件(文字、表格、倒數、按鈕、表單、電子申請書、互動遊戲)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
解決一：設定「陰影」後，編輯區的按鈕會立即顯示
解決二：可以取消勾選「陰影」的元件(文字、表格、倒數、按鈕、表單、電子申請書、互動遊戲)
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1. 設定「陰影」後，編輯區的按鈕會立即顯示。
2. 可以取消勾選「陰影」的元件(文字、表格、倒數、按鈕、表單、電子申請書、互動遊戲)。
◎◎ 20200109確認以上正式環境內容◎◎
