### ISSUE TITLE
【問題】複製有表單/電子申請書的專案後，新增表單/電子申請書的錯誤狀況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1703]
此情況發生在一般表單、序號表單、互動表單、電子申請書，以下用電子申請書做範例：
原專案(綠框處)存在電子申請書
![image](https://user-images.githubusercontent.com/49626114/69392890-8038cd00-0d12-11ea-9812-5af19e3757c4.png)
複製專案後再建立新電子申請書，從network查看api是建立成功的(黃框處)，但是編輯區是「尚未建立電子申請書」的畫面(橘框處)
![image](https://user-images.githubusercontent.com/49626114/69392897-89c23500-0d12-11ea-8b2e-4b5004e14ba0.png)
從network查看取得的舊專案api顯示「無此表單」(紅框處)
![image](https://user-images.githubusercontent.com/49626114/69392936-ac544e00-0d12-11ea-832b-e696508068b6.png)
從後台表單管理查看新建立的電子申請書是存在的。

**Comment by AnitaRyzo** [comment]
複製有表單與電子申請書的專案，已可正確顯示
![image](https://user-images.githubusercontent.com/41721950/70700164-3b96c500-1d05-11ea-9994-7ff23e8814a5.png)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
複製有表單與電子申請書的專案，已可正確顯示於畫布中
![image](https://user-images.githubusercontent.com/41721950/71947100-ad7c0480-3206-11ea-8645-6fd4f18f34ee.png)
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
複製有一般表單、序號表單、互動表單、電子申請書的專案，皆已可正確顯示於畫布中。
◎◎ 20200108確認以上正式環境內容◎◎
