### ISSUE TITLE
【問題】表單與電子申請書設定的必選與選答上限未正常執行

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1704]
無論是表單(一般/互動/序號)與電子申請書都有此問題
問題一：當『複選題』勾選「選答上限」的設定，此題目就無法點選
![image](https://user-images.githubusercontent.com/41721950/69395859-6d76c600-0d1b-11ea-898a-80dc720f021f.png)
問題二：『日期』與『時間』題型勾選「必選題」的設定，但未填寫不會提示，表單仍會正常送出
![image](https://user-images.githubusercontent.com/41721950/69396076-158c8f00-0d1c-11ea-8936-ad745bd575e5.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
解答一：當『複選題』勾選「選答上限」的設定，此題目可點選且會依照設定的選答上限執行
解答二：『日期』與『時間』題型勾選「必選題」的設定，未填寫會有提示
備註：僅下拉式題型即使設定必選，未選擇仍會以第一個選項當答案
![image](https://user-images.githubusercontent.com/41721950/70762674-6a0bb300-1d8c-11ea-8b02-2981d13cc00a.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
解答一：當『複選題』勾選「選答上限」的設定，此題目可點選且會依照設定的選答上限執行
解答二：『日期』與『時間』題型勾選「必選題」的設定，未填寫會有提示
![image](https://user-images.githubusercontent.com/41721950/71885161-c045f900-3174-11ea-953d-c4cae89ce56b.png)
◎◎ 20200107確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
1. 當『複選題』勾選「選答上限」的設定，此題目可點選且會依照設定的選答上限執行。
2. 『日期』與『時間』題型勾選「必選題」的設定，若未填寫會有提示。
![image](https://user-images.githubusercontent.com/49626114/72030642-aa474e00-32c4-11ea-97cc-07305340d2e0.png)
◎◎ 20200109確認以上正式環境內容◎◎
