### ISSUE TITLE
【問題】電子申請書的上傳圖片之警告文字，顏色未跟著設定

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1705]
電子申請書的上傳圖片之警告文字，顏色未跟著設定
正確為橘框文字，但上傳圖片之警告文字明顯不同(紅框)
![image](https://user-images.githubusercontent.com/41721950/69401650-95bcef80-0d30-11ea-9103-20023056d3ed.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
上傳圖片之警告文字，顏色會跟著設定
![image](https://user-images.githubusercontent.com/41721950/70765792-ce337480-1d96-11ea-9112-9fe9ce4201ba.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72029543-3b1c2a80-32c1-11ea-854d-abf80c7faa55.png)
◎◎ 20200109確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
上傳圖片之警告文字，顏色會跟著設定值顯示
![image](https://user-images.githubusercontent.com/41721950/72044187-17230e00-32ee-11ea-8aed-0f68c23086c5.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
