### ISSUE TITLE
【問題】表單的時間題型卻跳日期的選項

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1706]
此問題非每次出現，但不是個案
當題目中同時有『日期』與『時間』題型時，填好『日期』再填『時間』時，出現了可點選的下拉式日期選項(紅框)，但這個日期選項也不一定與前一題的日期答案相符(橘框)。
![image](https://user-images.githubusercontent.com/41721950/69404680-d02a8a80-0d38-11ea-8a10-030cdfe00e1d.png)
備註：在時間題點了下拉式日期選項，是不會寫入後台的
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
已嘗試多次都不會在「時間」題型出現「日期」
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
目前在「時間」題型填答時，皆未出現「日期」
◎◎ 20200107確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
目前在「時間」題型填答時，皆未出現「日期」。
◎◎ 20200108確認以上正式環境內容◎◎
