### ISSUE TITLE
【問題】EDM確認已儲存，但點選主選單仍跳暫存的提示訊息

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1707]
#1684 的延伸問題。
EDM編輯後，已跳出『進行儲存中』的提示訊息
![image](https://user-images.githubusercontent.com/49626114/69408339-94e08980-0d41-11ea-91b5-f5dbc05725d3.png)
但點選左上角的主選單後，仍出現暫存的提示訊息
![image](https://user-images.githubusercontent.com/49626114/69408361-a1fd7880-0d41-11ea-985e-d8eee6ae4914.png)

**Comment by cocosu123** [comment]
EDM編輯後儲存，跳出『進行儲存中』的提示訊息再點選左上角的主選單已不會出現暫存的提示訊息。
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
EDM編輯後儲存，跳出『進行儲存中』的提示訊息再點選左上角的主選單已不會出現暫存的提示訊息。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
EDM編輯後儲存，跳出『進行儲存中』的提示訊息再點選左上角的主選單已不會出現暫存的提示訊息。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
