### ISSUE TITLE
【問題】必填複選題的非其他選項，造成表單無法送出的情況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1708]
單選題與複選題有「其他」的選項可以自由輸入，若未輸入任何字元，必填題的機制會強制要求。
step1. 選擇「其他」的選項，但未輸入任何字元就按「第一次送出」，會出現右圖的紅字提示「請填入答案」訊息。
![image](https://user-images.githubusercontent.com/41721950/69414367-88fac480-0d4d-11ea-9b6b-70bae5ccf135.png)
step2. 選擇「非其他」的選項，「第二次送出」如右圖出現提示「請確認您的填寫」
![image](https://user-images.githubusercontent.com/41721950/69414776-5ac9b480-0d4e-11ea-95cc-c7929104011f.png)
step3. 不變動任何答案，「第三次送出」就成功了
![image](https://user-images.githubusercontent.com/41721950/69415071-e4798200-0d4e-11ea-9afe-8e99d722a3a3.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
必填複選題的非其他選項，表單已可順利送出
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
依照以上步驟，必填複選題的非其他選項，表單第一次就順利送出
◎◎ 20200107確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
依照以上步驟，必填複選題的非其他選項，表單第一次就順利送出。
◎◎ 20200109確認以上正式環境內容◎◎
