### ISSUE TITLE
【問題】互動元件的滴管吸顏色時，右上角的關閉按鈕怪怪的

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1709]
互動元件的滴管吸顏色時，右上角的關閉按鈕如下紅框
![image](https://user-images.githubusercontent.com/41721950/69415714-16d7af00-0d50-11ea-8106-84fe18e90f38.png)
請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
右上角的關閉按鈕已正常顯示
![image](https://user-images.githubusercontent.com/41721950/70766078-9e38a100-1d97-11ea-8a2c-3be81736a1ff.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
右上角的關閉按鈕已正常顯示
![image](https://user-images.githubusercontent.com/41721950/71955059-35233c80-3222-11ea-8108-56176c77305f.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
右上角的關閉按鈕已正常顯示
![image](https://user-images.githubusercontent.com/49626114/71960826-ee890e80-3230-11ea-9a34-6dcc96406cf0.png)
◎◎ 20200108確認以上正式環境內容◎◎
