### ISSUE TITLE
【問題】元件連結錨點的功能在預覽時失效，只能開啟頁面

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1710]
受影響的元件：圖片、圖示、按鈕之有錨點的連結設定者
如下情境是將『連結頁面』設定在「錨點3-2」，依照遊戲規則會將此長頁面的「錨點3-2」拉至頂端
![image](https://user-images.githubusercontent.com/41721950/69512204-16bcf680-0f7e-11ea-834f-8b0d2ea216e1.png)
但在預覽區(無論是編擊區、專案列表、專案審核發佈區)未依照規則將「錨點3-2」的位置置頂
![image](https://user-images.githubusercontent.com/41721950/69512328-9945b600-0f7e-11ea-9e3e-633dec968aa3.png)
而在uat環境與正式發佈上線後，都有正確執行
![image](https://user-images.githubusercontent.com/41721950/69512426-f5103f00-0f7e-11ea-85db-395f94ad7e2b.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
備註：此問題也會發生在30分鐘預覽頁面。
關閉issue時要一併確認。

**Comment by AnitaRyzo** [comment]
編輯區設定如下
![image](https://user-images.githubusercontent.com/41721950/70767422-3c2e6a80-1d9c-11ea-9547-20b55bec9f65.png)
預覽、30分鐘預覽、專案列表、專案審核發佈區、uat環境與正式發佈上線都有正確執行
![image](https://user-images.githubusercontent.com/41721950/70767467-6da73600-1d9c-11ea-80c6-95d4f5267c85.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
錨點目前在預覽、30分鐘預覽、專案列表、專案審核發佈區、uat環境與正式發佈上線都有正確執行。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
錨點目前在預覽、30分鐘預覽、專案列表、專案審核發佈區、uat環境與正式發佈上線都有正確執行。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎

**Comment by AnitaRyzo** [comment]
https://redmine.ryzoweba.com/redmine/issues/172
