### ISSUE TITLE
【問題】資料綁定上傳的資料檔案限制

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1711]
MongoDB限制單次上傳10MB以下的檔案
![image](https://user-images.githubusercontent.com/41721950/69516367-660a2380-0f8c-11ea-9bfa-1957fb08ce39.png)
但上傳20萬筆的資料在後台會暴增至13MB
即使將檔案分成多筆上傳，也因為資料庫限制而無法正常上傳
目前嘗試5萬筆、10萬筆、15萬筆分多次「新增名單資料」上傳，最多只能上傳到「25萬筆」資料，再上傳資料，「名單列表」就無法顯示所有資料，也無法『儲存定義』。
![image](https://user-images.githubusercontent.com/41721950/69516615-209a2600-0f8d-11ea-8f4a-62d331e665f9.png)
資料參考：https://github.com/SheetJS/sheetjs/issues/1138
待com環境切換資料庫至MSSQL後，會再次嘗試上傳
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
MSSQL測試的結果跟MongoDB一樣無法上傳大於10萬筆資料的檔案。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
