### ISSUE TITLE
【問題】mgm內嵌APP網址在chrome的無痕網頁未顯示「輸入識別碼」文字

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1712]
在chrome的無痕網頁打開沒有「輸入識別碼」文字(紅框處)，但是之前是有的。
![image](https://user-images.githubusercontent.com/49626114/69520233-0cf3bd00-0f97-11ea-9a6e-dd07eaeb7298.png)

**Comment by ai015606220** [comment]
@ryuichl 這裡發現是因為call /api/weba/v3/mgm/ 時在無痕網頁會403，請問是這個頁面本來就設計無法在無痕網頁中使用嗎?

**Comment by ryuichl** [comment]
前後台共用API
邏輯沒寫好造成的錯誤
已修正

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/69769638-9a662580-11c0-11ea-8d51-f58f7141671e.png)
◎◎ 20191128確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71960461-11ff8980-3230-11ea-8e4c-00a6d30da0c1.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/72056068-d8e61880-3306-11ea-902a-e39335fc72eb.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
