### ISSUE TITLE
【問題】在專案間共用彼此的編輯步驟造成的錯誤狀況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1714]
操作步驟如下：
STEP 1. 在專案1新增文字元件儲存後，再創建新的專案2
STEP 2. 在專案2新增裝飾圖案元件，再創建新的專案3
STEP 3. 在專案3新增任何元件，一直按『上一步』雖然畫布區無反應，但是在右側設定區域則會出現專案1&2的元件設定內容(紅框處)
![image](https://user-images.githubusercontent.com/49626114/69527214-cefe9500-0fa6-11ea-9188-0cc17f54831a.png)
STEP 4. 出現專案1的元件設定內容後，再按『下一步』畫布區&圖層設定就會顯示專案2的元件(橘框處)
![image](https://user-images.githubusercontent.com/49626114/69526483-36b3e080-0fa5-11ea-928a-5dddb1c07101.png)
若將前面專案(專案1&2)刪除後，按『上一步』『下一步』編輯區依舊可以出現上述內容，不過會有錯誤碼出現。
![image](https://user-images.githubusercontent.com/49626114/69526630-97dbb400-0fa5-11ea-8e58-5040005d9d3b.png)
備註：上述操作步驟不局限任何元件也不設限專案數量皆會發生此問題。

**Comment by AnitaRyzo** [comment]
每新開一個專案都不會有上一步
![image](https://user-images.githubusercontent.com/41721950/70768166-f0c98b80-1d9e-11ea-8b0d-bdcebcaf5d4f.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述操作，已不會有專案間共用彼此編輯步驟的情況發生。
◎◎ 20200109確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
依照上述操作，已不會有專案間共用彼此編輯步驟的情況發生。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
