### ISSUE TITLE
【問題】刮刮樂達到抽獎上限後，無法查看中獎紀錄

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1715]
設定「互動遊戲」的「抽獎上限」
![image](https://user-images.githubusercontent.com/41721950/69593985-e173df80-1035-11ea-85f5-8c2aed369beb.png)
刮刮樂在抽獎次數達到上限時，跳出提示頁後就無法再點按「中獎紀錄圖示」
![image](https://user-images.githubusercontent.com/41721950/69593914-ad98ba00-1035-11ea-8742-9db27fe39708.png)
但在其他互動遊戲中，跳出提示頁後仍可再點按「中獎紀錄圖示」，出現中獎紀錄
![image](https://user-images.githubusercontent.com/41721950/69593891-99ed5380-1035-11ea-8147-caad9f77c4c2.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
刮刮樂在抽獎次數達到上限時，點按「中獎紀錄圖示」已會出現中獎紀錄。
![image](https://user-images.githubusercontent.com/49626114/70768776-a8f83380-1da1-11ea-99cc-ca614e81c905.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
刮刮樂在抽獎次數達到上限時，點按「中獎紀錄圖示」無論是否已按「開始」都會出現中獎紀錄。
![image](https://user-images.githubusercontent.com/41721950/71955696-fb533580-3223-11ea-8348-6120f5335eb1.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
刮刮樂在抽獎次數達到上限時，點按「中獎紀錄圖示」無論是否已按「開始」都會出現中獎紀錄。
![image](https://user-images.githubusercontent.com/49626114/71964420-81797700-3238-11ea-9b3a-04c2951334bd.png)
◎◎ 20200108確認以上正式環境內容◎◎
