### ISSUE TITLE
【問題】積木在切換分類時產生錯誤提示

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1717]
![image](https://user-images.githubusercontent.com/11918396/69597859-5cdb8e00-1042-11ea-9f9e-ea394c61dbb6.png)

如上圖所示 , 在切換到這兩個分類時會觸發錯誤

io環境 以及 dev:4655 皆有這個問題

**Comment by AnitaRyzo** [comment]
積木在切換分類時未產生錯誤提示
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
積木在切換分類時未產生錯誤提示。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
積木在切換分類時未產生錯誤提示。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
