### ISSUE TITLE
【問題】互動-抽獎設置輸入異常

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#1719]
![image](https://user-images.githubusercontent.com/11918396/69599197-2ce2b980-1047-11ea-841e-f33e90e33cfc.png)

如上圖所示

抽獎設置中的三個欄位, 當以較快的速度來輸入數值並跳出該欄位後, 會顯示為 NaN

此時若儲存該設置並跳出該配置畫面，而後再重新切換回該配置畫面

![image](https://user-images.githubusercontent.com/11918396/69599349-ad091f00-1047-11ea-88dd-60fa5dd891ef.png)

如上圖所示

其抽獎配置欄位都會歸零

**Comment by cocosu123** [comment]
目前測試以較快的速度來輸入數值並跳出該欄位後, 抽獎設置的數值皆會正常呈現。
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
目前測試以較快的速度來輸入數值並跳出該欄位後, 抽獎設置的數值皆會正常呈現。
◎◎ 20200108確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
目前測試以較快的速度來輸入數值並跳出該欄位後, 抽獎設置的數值皆會正常呈現。
◎◎ 20200108確認以上正式環境內容◎◎
