### ISSUE TITLE
【團隊合作的成員筆數】是否能將顯示筆數提高至十個

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#172]
橘框部分顯示的筆數是否能將預設提到至十個，目前僅顯示四個好像太少了
![1526438664747](https://user-images.githubusercontent.com/37163894/40093748-2233cf6a-58f6-11e8-8e26-bdc6e789a24e.jpg)

**Comment by ai015606220** [comment]
是10沒錯，只是若你在當初尚未更改前就使用過，瀏覽器就會記錄你是設定4
