### ISSUE TITLE
【問題】表單專案個別設定的填表人數限制造成的錯誤情況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1720]
在專案1跟專案2放入相同的表單，從「專案個別設定」可得知在專案2的填表人數限制是2人(橘框處)，專案1沒有填表人數限制(黃框處)
![image](https://user-images.githubusercontent.com/49626114/69616201-2a955500-1071-11ea-9c11-477919e085ac.png)
從表單管理後台查看可得知此表單有2筆回覆是來自專案1(綠框處)
![image](https://user-images.githubusercontent.com/49626114/69616312-5d3f4d80-1071-11ea-87ad-c2222c299374.png)
但是進入專案2未填寫過表單卻顯示「此專案表單筆數已達上限」
![image](https://user-images.githubusercontent.com/49626114/69616568-cde66a00-1071-11ea-8a94-c81c4c3fc38e.png)

**Comment by AnitaRyzo** [comment]
依據上述步驟進行測試，專案2的填表人數限制是2人，專案1沒有填表人數限制；在專案1填寫人數達兩人時，專案2依然可以進行表單填寫送出，直到達成填表人數限制。
![image](https://user-images.githubusercontent.com/41721950/69769262-0778bb80-11bf-11ea-9521-a67ad020ffbd.png)
◎◎ 20191128確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
依據上述步驟進行測試，A1專案時效已到，A1專案-2與-3各設定只能填寫一個。
在各專案已依照設定的時效與填表人數執行
![image](https://user-images.githubusercontent.com/41721950/71954099-28e9b000-321f-11ea-85c9-b8b0d7454ec7.png)
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述操作，表單「專案個別設定」的填表人數限制已不會互相影響，已依照各專案設定的時效與填表人數執行。
◎◎ 20200109確認以上正式環境內容◎◎
