### ISSUE TITLE
【MSSQL】互動遊戲匯入序號若資料不完整，資料顯示有差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1723]
當匯入的資料有空白欄位(黃框)，在互動遊戲的「匯入序號」將此份資料匯入指定獎項
![image](https://user-images.githubusercontent.com/41721950/69689017-b905e700-1102-11ea-94f4-5dedeb657a97.png)
若在第一次『儲存』「設定獎項」前，未開啟過(橘框)，之後開啟資料只會顯示欄位一
![image](https://user-images.githubusercontent.com/41721950/69689239-5bbe6580-1103-11ea-98b1-cb4c179f889e.png)
若在第一次『儲存』「設定獎項」前，就開啟過(橘框)，資料會完整顯示
![image](https://user-images.githubusercontent.com/41721950/69689164-29146d00-1103-11ea-9465-a25a8971614b.png)
在io環境無論怎麼操作，都會顯示前三欄的欄位資料
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
A欄欄位必須要有資料，否則BC欄會往前移動
其他資料格式都有正常顯示
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
A欄欄位必須要有資料，否則資料不會被寫入。
如下圖原本有10筆資料其中3筆(橘框處)A欄為空值，
![image](https://user-images.githubusercontent.com/49626114/71958920-728cc780-322c-11ea-8b5c-8c5e24b260c1.png)
匯入後只有7筆資料寫入。
![image](https://user-images.githubusercontent.com/49626114/71958855-41ac9280-322c-11ea-9e24-8193927e85d3.png)
其他資料格式都有正常顯示，若BC欄未有空值也會正常寫入資料。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
A欄欄位必須要有資料，否則資料不會被寫入。
如下圖原本有10筆資料其中3筆(紅框處)A欄為空值，但是匯入後只有7筆資料寫入(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/72125597-1a78d100-33a4-11ea-92ca-bda8471947f9.png)
其他資料格式都有正常顯示，若BC欄未有空值也會正常寫入資料。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
