### ISSUE TITLE
【問題】團隊相關權限設定必須重新整理頁面才會更新

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1724]
無論是「管理者後台」或「團隊管理」的團隊相關權限
![image](https://user-images.githubusercontent.com/41721950/69692411-ed7ea080-110c-11ea-8e59-fb4e9e3b5c06.png)
若只是頁面內切換，設定不會照著變動；必須重新整理頁面才會更新
但以前只要頁面內切換就會更新，請協助確認。感恩~

**Comment by AnitaRyzo** [comment]
備註：主要是「管理者後台」影響到設定

**Comment by cocosu123** [comment]
「管理者後台」或「團隊管理」的團隊相關權限重新設定後只要頁面內切換就會更新。
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
「管理者後台」或「團隊管理」的團隊相關權限重新設定後只要頁面內切換就會更新。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
「管理者後台」或「團隊管理」的團隊相關權限重新設定後只要頁面內切換就會更新。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
