### ISSUE TITLE
【問題】PDF版面配置在簡體中文和英文語系增加頁面無反應

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1726]
語系設定選擇簡體中文和英文語系時，
![image](https://user-images.githubusercontent.com/49626114/69775415-9ee80980-11d3-11ea-9496-f0f357380b54.png)
在電子申請書的PDF版面配置增加頁面(紅框處)無反應，
![image](https://user-images.githubusercontent.com/49626114/69775520-eec6d080-11d3-11ea-91a8-e697ad08e479.png)
且會出現錯誤訊息。
![image](https://user-images.githubusercontent.com/49626114/69775497-dc4c9700-11d3-11ea-8bc7-67b9f31d78ca.png)

**Comment by cocosu123** [comment]
PDF版面配置在簡體中文和英文語系已經可以正常執行增加頁面。
![image](https://user-images.githubusercontent.com/49626114/70762938-6167ac80-1d8d-11ea-9aa8-15c51a28c8d8.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
PDF版面配置在簡體中文和英文語系已經可以正常執行增加頁面。
![image](https://user-images.githubusercontent.com/49626114/71956837-225f3680-3227-11ea-9adb-d3e25150c80d.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
PDF版面配置在簡體中文和英文語系已經可以正常執行增加頁面。
![image](https://user-images.githubusercontent.com/41721950/72042662-1ee0b380-32ea-11ea-937c-954aacf988da.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
