### ISSUE TITLE
【問題】字型在編輯區與瀏覽器顯示有差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1727]
字型「Exo 2」在編輯區與瀏覽器顯示有差異
![image](https://user-images.githubusercontent.com/41721950/69775968-7b25c300-11d5-11ea-8294-dab3535333d0.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
字型「Exo 2」在編輯區與瀏覽器顯示已相同。
![image](https://user-images.githubusercontent.com/49626114/70762677-6aa44980-1d8c-11ea-8994-60a6fd53b5d2.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71957540-ff358680-3228-11ea-8ea6-bcbf9643ed3e.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
字型「Exo 2」在編輯區與瀏覽器顯示已相同。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
