### ISSUE TITLE
【問題】QR code設定商標圖的垂直位置之錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1728]
QR code商標圖會在上傳圖片後，啟用圖片設定
但是在垂直位置設定處(紅框)拉動時，預覽圖變成白色區塊且不會依照拉動Bar條而移動
![image](https://user-images.githubusercontent.com/41721950/69776788-947c3e80-11d8-11ea-9429-5261e894095e.png)
雖然操作此步驟在console未有錯誤訊息，但在開啟「QR code設定」視窗時，有以下錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/69777003-60554d80-11d9-11ea-8341-60ee87686da3.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
QR code商標圖在垂直位置設定處拉動bar條時，預覽圖已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/70695662-2cac1480-1cfd-11ea-80df-7b071c57c392.png)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
QR code商標圖在垂直位置設定處拉動bar條時，預覽圖已正常呈現。
![image](https://user-images.githubusercontent.com/49626114/71956488-4bcb9280-3226-11ea-84e4-887ddb0a028f.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
QR code商標圖在垂直位置設定處拉動bar條時，預覽圖正常呈現且下載後也是相同畫面。
![image](https://user-images.githubusercontent.com/41721950/72038209-978c4380-32db-11ea-96a1-087e322dc76e.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
