### ISSUE TITLE
【問題】動畫的循環播放

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#173]
目前動畫沒有找到循環播放的設定處
不知道以後會不會新增？（還是只是我一時沒找到？ＸＤ）

**Comment by ryuichl** [comment]
![image](https://user-images.githubusercontent.com/10150807/40095677-e09b3d18-58ff-11e8-9e29-e9ee993229fe.png)

**Comment by wilmaftliu** [comment]
<img width="318" alt="2018-05-17 10 31 05" src="https://user-images.githubusercontent.com/34560641/40153668-6e2fe95e-59bd-11e8-8477-52106be895e0.png">
當動畫新增一個以上時 循環播放的選項就消失了
所以如果要做兩個以上循環播放的動畫是不可行的
希望可以開放讓一個以上的動畫還是可以個別設定播放的次數

**Comment by wilmaftliu** [comment]
<img width="315" alt="2018-05-17 10 32 48" src="https://user-images.githubusercontent.com/34560641/40153721-aba01426-59bd-11e8-8171-e70172663372.png">
（一個動畫是可以設定循環的）
