### ISSUE TITLE
【問題】資料綁定再次上傳不同欄位的檔案，「覆蓋資料」未出現提示訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1730]
前提：資料綁定上傳遞一份資料後，若要『新增名單資料』或是『覆蓋名單資料』時，系統會優先以「欄位數量」判斷是否可以上傳。
但『覆蓋名單資料』未有提示訊息，只會一直Loading
![image](https://user-images.githubusercontent.com/41721950/69847050-f314eb80-12b0-11ea-8cdc-39a3adfcf9e9.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/69847085-0d4ec980-12b1-11ea-90a2-3cf44d469a2c.png)
以上問題請協助處理，感恩~

備註：『新增名單資料』的欄位資料錯誤時的提示訊息如下
![image](https://user-images.githubusercontent.com/41721950/69846960-a7624200-12b0-11ea-8b9b-3b5fa3d8837a.png)

**Comment by cocosu123** [comment]
『覆蓋名單資料』已會正常跳出提示訊息。
![image](https://user-images.githubusercontent.com/49626114/70690970-e356c780-1cf2-11ea-9b71-d3d2a142c400.png)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
『覆蓋名單資料』已會正常跳出提示訊息。
![image](https://user-images.githubusercontent.com/49626114/71956076-1f634680-3225-11ea-8fa3-7bc798b237cf.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
『覆蓋名單資料』已會正常跳出提示訊息。
![image](https://user-images.githubusercontent.com/49626114/72117177-b3e5ba00-3387-11ea-8200-87b715b15d10.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
