### ISSUE TITLE
【問題】新增團隊後，團隊列表未切換至新團隊

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1733]
所在「ABC」團隊的狀況下(橘框處)，點擊黃色框建立新團隊
![image](https://user-images.githubusercontent.com/49626114/69855898-7e00e080-12c7-11ea-98ac-741ae64c6dc6.png)
建立新團隊名為「測試團隊」
![image](https://user-images.githubusercontent.com/49626114/69856026-a5f04400-12c7-11ea-8865-d04385627e49.png)
確認後，所在團隊顯示為「測試團隊」(綠框處)，但是團隊管理列表處卻顯示在「ABC」團隊內(紅框處)
![image](https://user-images.githubusercontent.com/49626114/69856093-c91af380-12c7-11ea-9c52-f8bc01cb94d8.png)
備註：以前新增團隊後會自動切換到新團隊內。

**Comment by AnitaRyzo** [comment]
新增：在表單新增也有此問題，請一併處理。感恩~

**Comment by cocosu123** [comment]
點擊紅框處建立新團隊依然會有上述問題發生，但是點擊綠框處建立新團隊已正確切換團隊。
![image](https://user-images.githubusercontent.com/49626114/70687903-68d67980-1ceb-11ea-9251-a4bd53912d56.png)
在表單管理後台新增表單也已有正確切換表單。
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
無論是綠框哪個方法新增團隊後，團隊列表會自動切換至新團隊
![image](https://user-images.githubusercontent.com/41721950/71401905-46871900-2666-11ea-943c-a753ea26bd00.png)
表單新增後，會停留在最新表單
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
無論是綠框哪個方法新增團隊後，團隊列表會自動切換至新團隊
![image](https://user-images.githubusercontent.com/41721950/71887611-701d6580-3179-11ea-8368-58a937435c2b.png)
表單與電子申請書新增後，會停留在最新表單
![image](https://user-images.githubusercontent.com/41721950/71887721-a3f88b00-3179-11ea-940f-73be4ab0a098.png)
◎◎ 20200107確認以上測試環境內容MS SQL◎◎

**Comment by cocosu123** [comment]
新增團隊後，團隊列表會自動切換至新團隊。
新增表單/電子申請書也都會停留在最新表單。
◎◎ 20200108確認以上正式環境內容◎◎
