### ISSUE TITLE
發佈域名要檔掉保留字

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1735]
![image](https://user-images.githubusercontent.com/10150807/69947563-dbe03300-1528-11ea-8a58-f09014266df9.png)

這邊取域名的時候
前面不可以有uat或template
有的話要顯示已使用
不然會跟測試功能衝突

**Comment by cocosu123** [comment]
域名有uat或template未被擋掉，依然可以使用。
![image](https://user-images.githubusercontent.com/49626114/70687356-de414a80-1ce9-11ea-8e7b-f7948c4adfd2.png)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
域名是uat或template為首的域名會被擋掉，無法使用
![image](https://user-images.githubusercontent.com/41721950/71402538-150f4d00-2668-11ea-9c7c-19a678f19f9a.png)
![image](https://user-images.githubusercontent.com/41721950/71402565-31ab8500-2668-11ea-9948-9da5a4bb768c.png)
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71955573-9992cb80-3223-11ea-9083-0ea52df6388e.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72117114-74b76900-3387-11ea-8758-9ab4191a933f.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
