### ISSUE TITLE
【新功能】表單特定項目即時回覆的編輯與信件差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1736]
表單特定項目即時回覆的適用題型：單選題、複選題、下拉式、矩陣式(直行欄位)、線性評分、手勢選答、手勢評分。
「及時回覆項目通知」有差異處
1.設計稿是無須勾選『寄至指定信箱』，現在要勾選才寄信跟此項目不太合理
2.設計稿有提到要有「問號說明」，但實際操作區未出現
![image](https://user-images.githubusercontent.com/41721950/70023768-5d8c9b00-15d3-11ea-81da-82df558c8d9b.png)

「信件寄送」
→被指定的特定項目文字粗體不太明顯，而設計稿還多了『表單參數：表單網址』*(目前無此機制)
![image](https://user-images.githubusercontent.com/41721950/70023853-9af12880-15d3-11ea-9a11-9bc7845ce280.png)
目前在一般表單、抽獎表單、序號表單皆有正確執行
以上資訊請參考，感恩~

**Comment by tkwang0530** [comment]
關於 第一點: 是否要勾選『寄至指定信箱』後來跟產品溝通過了。產品要我們加上去的 (Tommy)

**Comment by ryzojudy** [comment]
不好意思 上次tommy詢問時因為沒有考慮清楚
所以就請他幫忙補上了
後與測試討論過後
同意將前面的勾選拿掉

原因：
【即時回覆】此項功能因已經在問題處選擇開啟這項設定
所以在前面的地方不需要在決定是否開啟
而是直接填寫信箱即可
(當後面題目有答案被標示需要即時回覆時，就可以直接寄信，不需要再回頭道前面這邊打勾)

**Comment by AnitaRyzo** [comment]
「問號說明」與『寄至指定信箱』無勾選
![image](https://user-images.githubusercontent.com/41721950/71403253-22c5d200-266a-11ea-9ff0-bee31d6fc48c.png)
目前在一般表單與抽獎表單皆有正確執行，但序號表單目前尚有問題處理中。
『表單參數：表單網址』已更新且回信的題目變成紅字粗體更明顯
![image](https://user-images.githubusercontent.com/41721950/71404195-e182f180-266c-11ea-864b-4eaf2fba8da0.png)
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1. 已有問號說明(黃框處)，且已無需勾選是否要『寄至指定信箱』。
![image](https://user-images.githubusercontent.com/49626114/71954773-533c6d00-3221-11ea-9a16-a2af118fbff0.png)
2. 目前在一般表單、抽獎表單、序號表單皆有正確執行，『表單參數：表單網址』已更新且回信的題目變成紅字粗體更明顯。
![image](https://user-images.githubusercontent.com/49626114/71954953-d493ff80-3221-11ea-82ac-45562549bf2f.png)
◎◎ 20200108確認以上正式環境內容◎◎
