### ISSUE TITLE
【問題】資料綁定的使用者ID未顯示被選取者

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1737]
在資料綁定中，系統預設『欄位1』為使用者ID
![image](https://user-images.githubusercontent.com/41721950/70027855-13f57d80-15de-11ea-9aba-d76569b7e0e1.png)
若今日選擇了其他欄位，按了「非儲存定義」的其他項目
![image](https://user-images.githubusercontent.com/41721950/70027945-5323ce80-15de-11ea-84bf-e9d0277b748d.png)
再次回到『名單檔案』時，沒有一個欄位被選擇為使用者ID
![image](https://user-images.githubusercontent.com/41721950/70028047-8cf4d500-15de-11ea-970c-d8d0ab4dc383.png)
備註：即使是上述狀況，在數據後台預設『欄位1』為顯示的資料，故資料不會有問題
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
依照上述操作，再次回到『名單檔案』仍會變成預設的『欄位1』為使用者ID。
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述操作，再次回到『名單檔案』仍會變成預設的『欄位1』為使用者ID。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
依照上述操作，再次回到『名單檔案』仍會變成預設的『欄位1』為使用者ID。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
