### ISSUE TITLE
【問題】資料綁定圖片的連結網址未能帶入圖片

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1738]
資料綁定可以編輯「圖片的連結網址」與「輪播圖的自行輸入網址」
![image](https://user-images.githubusercontent.com/41721950/70036429-c08c2b00-15ef-11ea-84bf-d5a87240811a.png)
**已確認連結網址的圖片是存在的**，且無論是甚麼圖片格式(jpeg、jpg、png、gif)
當在「資料綁定編輯」編輯時，或是在「瀏覽器上查看」時，圖片都**可能無法顯示**。
![image](https://user-images.githubusercontent.com/41721950/70038217-dfd88780-15f2-11ea-9510-7ab145148e7f.png)
專案範例：[公主圖片集.xlsx](https://github.com/ryuichl/v3-report/files/3915681/default.xlsx)
若是有「連結網址」的限制，請告訴我們；以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
第一次編輯的「公主圖片集』的內容全部跑到左上角，已無法查看
故新增[公主1212.xlsx](https://github.com/ryuichl/v3-report/files/3953637/1212.xlsx)，但圖片依然殘缺無法顯示耶...
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by ai015606220** [comment]
這是CORS問題，要再研究

**Comment by AnitaRyzo** [comment]
目前已可正常顯示圖片
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
目前資料綁定圖片的連結網址已可正常顯示圖片。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
目前資料綁定圖片的連結網址已可正常顯示圖片。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
