### ISSUE TITLE
【問題】套用有表單/電子申請書的套版後，建立與選擇的錯誤狀況

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1739]
#1703 延伸問題
使用有一般表單/電子申請書的套版，進行『表單設定』
![image](https://user-images.githubusercontent.com/41721950/70123062-d7dd1e00-16ac-11ea-955c-16b6f24c0ff0.png)
無論是『建立新表單』或是『選擇表單』，Network 都會出現『無此表單』
![image](https://user-images.githubusercontent.com/41721950/70123002-afedba80-16ac-11ea-9e65-37cc713e7b2d.png)
編輯畫面會一直停留在『尚未建立任何表單』
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
套用有表單/電子申請書的套版後，建立與選擇都可以正常執行。
![image](https://user-images.githubusercontent.com/49626114/70762028-244deb00-1d8a-11ea-8ed8-a8533244318b.png)
◎◎ 20191213確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
備註：IO環境時要測試非常舊且含有表單的專案

**Comment by AnitaRyzo** [comment]
套用有表單/電子申請書的套版後，建立與選擇都可以正常執行。
![image](https://user-images.githubusercontent.com/41721950/71947868-267c5b80-3209-11ea-9b44-3b9680542937.png)
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
套用舊有表單套版後，建立與選擇都可以正常執行。
電子申請書因無舊套版，所以是套用新的套版，建立與選擇也都可以正常執行。
◎◎ 20200108確認以上正式環境內容◎◎
