### ISSUE TITLE
【問題】序號產生器跑版

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#174]
產生序號以後,點擊查看序號
發現序號跑版了!!

**Comment by weilyn** [comment]
![default](https://user-images.githubusercontent.com/34327325/40094676-f83bb7cc-58fa-11e8-83d6-3dbf6d544874.PNG)

**Comment by Isabella-Zheng** [comment]
暫無發生

**Comment by Isabella-RYZO** [comment]
👌
