### ISSUE TITLE
【問題】電腦版設定兩個以上的群組框架固定產生跑版

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1740]
電腦版編輯區將當多個元件組成群組後，再『框架設定』
無論是否有勾選『固定至所有分頁』or『固定至所有幻燈片』
![image](https://user-images.githubusercontent.com/41721950/70130065-dca8ce80-16ba-11ea-97d3-33d1351d0789.png)
第一次進入專案時，被框架的群組皆可正常顯示
![image](https://user-images.githubusercontent.com/41721950/70129804-61471d00-16ba-11ea-8d93-3cadac1e0e8f.png)
重新整理頁面後，被框架的群組就會跑版了
![image](https://user-images.githubusercontent.com/41721950/70129918-8c317100-16ba-11ea-96a8-b793d8a14030.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
依照上述步驟操作在預覽、uat、發佈頁面都還是會產生跑版。
![image (1)](https://user-images.githubusercontent.com/49626114/70676751-26e80c00-1cc8-11ea-8116-e74045263395.png)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
依照上述步驟操作在預覽、uat、發佈頁面都可以正常顯示
◎◎ 20200102確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述步驟操作在預覽、uat、發佈頁面都可以正常顯示。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
依照上述步驟操作在預覽、uat、發佈頁面都可以正常顯示。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
