### ISSUE TITLE
【問題】文字元件的編輯框線未跟著元件尺寸變動

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1742]
在專案跟Banner中，文字元件重現issue #1067 的問題，編輯框線皆未跟著元件尺寸變動。
左圖是16px 調成 30px，右圖是30px 調成 16px。
![image](https://user-images.githubusercontent.com/49626114/70410854-6d9cf280-1a8b-11ea-820a-d034420c6dc6.png)

**Comment by cocosu123** [comment]
在專案跟Banner中，編輯框線已會跟著元件尺寸變動。
![image](https://user-images.githubusercontent.com/49626114/70603497-a5de3580-1c31-11ea-8473-6a0f03b0d5fb.png)
◎◎ 20191211確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在專案跟Banner中，編輯框線已會跟著元件尺寸變動。
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
在專案跟Banner中，編輯框線已會跟著元件尺寸變動。
![image](https://user-images.githubusercontent.com/41721950/72032720-378da100-32cb-11ea-9cef-ace55a9232a3.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
