### ISSUE TITLE
【問題】互動元件的獎項序號內容呈現時有時無

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1743]
在互動元件的獎項匯入序號時看到的內容(如下圖左邊)，先離開設定獎項頁面進行其他設定，再次進入設定獎項頁面查看序號卻與原本的內容呈現不一(如下圖右邊紅框處)。
![image](https://user-images.githubusercontent.com/49626114/70423776-21f94180-1aa9-11ea-8f61-d257d76b9807.png)
備註：內容呈現的狀況沒有先後順序，以上情境描述其中一種。

**Comment by cocosu123** [comment]
再次進入設定獎項頁面查看序號內容(如下圖右邊橘框處)與原本的(如下圖左邊綠框處)已呈現相同，不管內容是否有空值皆會完整呈現序號一、二、三欄位的內容。
![image](https://user-images.githubusercontent.com/49626114/70675644-b68bbb80-1cc4-11ea-941c-71d3cbe05492.png)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
再次進入設定獎項頁面查看序號內容(如下圖右邊橘框處)與原本的(如下圖左邊黃框處)呈現相同，不管內容是否有空值皆會完整呈現序號一、二、三欄位的內容。
![image](https://user-images.githubusercontent.com/49626114/71945646-5a07b780-3202-11ea-9198-60964ef0a95d.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
原本的(如左圖)匯入序號與再次進入「設定獎項」頁面查看序號內容(如右圖)呈現的資料相同。
![image](https://user-images.githubusercontent.com/41721950/72122451-e9df6a00-3398-11ea-9d45-1c89563c06e2.png)
![image](https://user-images.githubusercontent.com/41721950/72125274-f1a40c00-33a2-11ea-9665-2cb7ae3623c3.png)
![image](https://user-images.githubusercontent.com/41721950/72123092-214f1600-339b-11ea-99ff-214d5fc9c7d6.png)
![image](https://user-images.githubusercontent.com/41721950/72122618-74c06480-3399-11ea-8f3b-094926cd4b19.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
