### ISSUE TITLE
【問題】互動元件匯入獎項後，若C欄不存在則B欄也不顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1744]
互動元件的匯入獎項，現在可以匯入有ABC三欄的資料
但當匯入的資料C欄不存在時...
![image](https://user-images.githubusercontent.com/41721950/70424352-32f68280-1aaa-11ea-86ec-da49ae5ef776.png)
資料預覽的畫面中也不會有B欄
![image](https://user-images.githubusercontent.com/41721950/70424170-df843480-1aa9-11ea-90c2-d75d0b201454.png)
以上問題請協助處理，感恩~
#1743 延續問題

**Comment by cocosu123** [comment]
若互動元件匯入序號的資料C欄不存在時(橘框處)，資料預覽的畫面中A跟B欄依然會正常呈現(黃框處)，不受C欄位影響。
![image](https://user-images.githubusercontent.com/49626114/70606792-361f7900-1c38-11ea-832d-2f0f1a56cdb1.png)
◎◎ 20191211確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
若互動元件匯入序號的資料C欄不存在時(橘框處)，資料預覽的畫面中A跟B欄依然會正常呈現(綠框處)，不受C欄位影響。
![image](https://user-images.githubusercontent.com/49626114/71944380-89b4c080-31fe-11ea-9079-623468badb32.png)
◎◎20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
若互動元件匯入序號的資料C欄不存在時(橘框處)，資料預覽的畫面中A跟B欄依然會正常呈現(黃框處)，不受C欄位影響。
![image](https://user-images.githubusercontent.com/49626114/72124681-9a9d3780-33a0-11ea-9f5f-63f36ce62045.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
