### ISSUE TITLE
【建議】電腦版表單其他選項設定跳題時，輸入完成後的下一步不明確

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1745]
電腦版表單「其他」選項輸入完成後必須要點擊空白處才會跳題。
在輸入狀態時會亮起藍綠色的底線(紅框處)，跳題方式是輸入完內容後，點擊表單的任何一處「空白」，系統才會判定離開輸入狀態底線，底線變回預設灰色(橘框處)才會跳至指定題目。
![image](https://user-images.githubusercontent.com/49626114/70491249-b90ed980-1b3b-11ea-9776-db448aaf9812.png)
但是正常狀態下使用者輸入完成後，不一定會去點擊表單空白處，甚至更可能直接滑動表單填寫其他題目，因此會造成無法依照編輯者預期的跳至指定題目。
在手機版無此問題，手機版輸入完成後一定要先離開輸入鍵盤(離開輸入狀態)才能夠填寫其他題目，因此可以順利跳至指定題目。

**Comment by ai015606220** [comment]
除了失去游標的這個事件外，我沒有其他辦法能夠判斷他已經「完成作答」

**Comment by AnitaRyzo** [comment]
好的，我們會寫入『使用WEBA的注意事項』
→ 當「單選題」的「其他」選項遇到「跳題」設定時，電腦版需先點空白處才會正確執行跳題。
