### ISSUE TITLE
【問題】暫存提示後未回到專案列表，而是停留在專案中

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1746]
此問題僅出現在io正式環境
當執行到一半點選『左上角的logo』會跳出「暫存提示」後回到「專案列表」
![image](https://user-images.githubusercontent.com/41721950/70504159-1ae13a80-1b60-11ea-9d36-e8695700bf17.png)
但現在回覆「暫存提示」後，仍然是黑畫面，不會回到「專案列表」；而網址依然保留在專案
![image](https://user-images.githubusercontent.com/41721950/70507402-3e5bb380-1b67-11ea-9e48-9e90bf6481bc.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
「暫存提示」點選確定後已會回到「專案列表」。
◎◎ 20200108確認以上正式環境內容◎◎
