### ISSUE TITLE
【問題】專案背景延伸的相關問題

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1747]
問題1.
在幻燈片A進行背景設定後直接點擊新增頁面或幻燈片，新增的幻燈片B「背景顏色(溢版)」(紅框處)卻自動帶入了幻燈片A的設定(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/70515087-b201be80-1b6f-11ea-9a4e-6e2112cd0de6.png)
問題2.
在幻燈片A進行背景設定後再點選「套用至此頁面中的幻燈片」，但是幻燈片B的背景延伸(紅框處)卻未套用幻燈片A的背景延伸(黃框處)設定，僅有綠框處的內容有套用。
![image](https://user-images.githubusercontent.com/49626114/70513610-f17adb80-1b6c-11ea-8daa-bbd949088937.png)

**Comment by ai015606220** [comment]
因為背景顏色(溢版)是整個專案只有一個設定，不是各頁面或幻燈片有自己的設定
問題2已修正

**Comment by cocosu123** [comment]
在幻燈片A點選「套用至此頁面中的幻燈片」後，幻燈片B(綠框處)會套用幻燈片A(黃框處)的背景設定。
![image](https://user-images.githubusercontent.com/49626114/70598156-22b6e280-1c25-11ea-85af-65c307bd8ce4.png)
◎◎ 20191211確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在幻燈片A點選「套用至此頁面中的幻燈片」後，幻燈片B(綠框處)會套用幻燈片A(黃框處)的背景設定。
![image](https://user-images.githubusercontent.com/49626114/71944007-7523f880-31fd-11ea-8c6f-bced313c6555.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
在幻燈片A點選「套用至此頁面中的幻燈片」後，幻燈片B會套用幻燈片A的背景設定。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
