### ISSUE TITLE
【問題】互動遊戲匯入多欄獎項時，若有空欄資料庫未完整寫入

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1749]
當資料量完整時，network會帶入「code、description、value」
![image](https://user-images.githubusercontent.com/41721950/70585855-7cf17c80-1c00-11ea-841c-56dab88a1f5f.png)
當只有BC欄有時，network只寫入「value」
![image](https://user-images.githubusercontent.com/41721950/70586657-aa3f2a00-1c02-11ea-84e9-bcad6ae7e558.png)
當只有AC欄有資料時，network只寫入「description、value」
![image](https://user-images.githubusercontent.com/41721950/70586638-9f849500-1c02-11ea-9245-b4a22fb106af.png)
當只有AB欄有資料時，network只寫入「value」
![image](https://user-images.githubusercontent.com/41721950/70586939-89c39f80-1c03-11ea-9a0b-adfc85cc14ea.png)
以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
互動遊戲匯入多欄位序號時，若有空的欄位(橘框處)，network依然會帶入「code、description、value」的值(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/70606091-c066dd80-1c36-11ea-8266-9be5536ef3ab.png)
◎◎ 20191211確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
互動遊戲匯入多欄位序號時，若有空的欄位(黃框處)，network依然會帶入「code、description、value」的值(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/71943614-2e81ce80-31fc-11ea-96db-8b8a9525004c.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
互動遊戲匯入多欄位序號時，若有空的欄位，network依然會帶入「code、description、value」的值(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/72124151-a851bd80-339e-11ea-833d-cf9ecb5ea75d.png)
