### ISSUE TITLE
【MongoDB】多個互動抽獎共用表單，限定專案填表人數會失效

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1750]
多個互動抽獎共用同一個表單，
當設定「專案個別設定」並使用「自動回覆表單」
![image](https://user-images.githubusercontent.com/41721950/70677606-9eb73600-1cca-11ea-9238-ade214d602a4.png)
「自動回覆表單」的限定「填表人數限制」失效，『上限』的提示訊息只會出現在手動回覆
![image](https://user-images.githubusercontent.com/41721950/70677498-4da74200-1cca-11ea-886b-9099e86ec752.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
![image](https://user-images.githubusercontent.com/10150807/70679313-b218d000-1ccf-11ea-9d91-b4a193f6f587.png)
上面是自動回傳
下面是手動發送

因為回傳後我會把site_id存到回覆中
後續再透過site_id去算說這個專案有幾個回覆

所以麻煩 @ai015606220  把自動回傳的部分 publish_name 改成 site_id
這功能就正常了

**Comment by AnitaRyzo** [comment]
若是「自動傳送表單」且「表單人數限制已滿」，前臺會看到左邊的畫面；直到後台編輯者將「自動傳送表單」關閉，未回填的表單才會再次出現如右圖。
![image](https://user-images.githubusercontent.com/41721950/71429555-1db46180-2702-11ea-9027-6987549e7a83.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在「自動傳送表單」且「表單人數限制已滿」的情況下會看到黃框處的畫面，但是表單後台不會再回傳表單資料。
若編輯者將「自動傳送表單」關閉則會看到橘框處的畫面，點選填寫資料後則會顯示綠框處畫面。
![image](https://user-images.githubusercontent.com/49626114/71942424-2031b380-31f8-11ea-89fd-cd1cfcaebdfc.png)
◎◎ 20200108確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
當「表單人數限制」已滿，左圖手動填表，右圖自動填表
![image](https://user-images.githubusercontent.com/41721950/71956570-79184080-3226-11ea-9b2e-5b46c5c891c6.png)
「自動傳送表單」的互動遊戲，表單後台也不會收到任何表單資料。
![image](https://user-images.githubusercontent.com/41721950/71956596-833a3f00-3226-11ea-8365-cf7ef007c135.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
