### ISSUE TITLE
【MongoDB】新創專案申請審核未亮橘色燈號

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1751]
專案申請審核後，從Network判定專案已是『申請審核中』(apply : true, verify:false)
![image](https://user-images.githubusercontent.com/41721950/70681990-5868d380-1cd8-11ea-8bfc-562ad2b74e74.png)
但是在「專案管理列表」未有燈號(左圖)，「審核發佈管理」有確實出現專案須審核(右圖)
![image](https://user-images.githubusercontent.com/41721950/70682217-01173300-1cd9-11ea-84b4-cf2bc4f0120e.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
這邊還有個判斷邏輯是apply_at > verify_at
之前為了讓專案在建立時兩個值完全一樣
邏輯沒寫好造成的bug
等一下會修正上去

**Comment by AnitaRyzo** [comment]
燈號已正確亮起
![image](https://user-images.githubusercontent.com/41721950/70688340-87894000-1cec-11ea-93f8-5a4e75516fa3.png)
◎◎ 20191212確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71883301-20d33700-3171-11ea-94f6-2d249243e81d.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
燈號已正確亮起。
![image](https://user-images.githubusercontent.com/49626114/72053860-d5509280-3302-11ea-8c29-08c9b1786abb.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
