### ISSUE TITLE
後台設定的SEO和分享資訊失效

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1752]
![image](https://user-images.githubusercontent.com/10150807/70688115-ea2e0c00-1ceb-11ea-9a49-3f9cdd97ca46.png)
我在後台設定了SEO和分享的資訊
![image](https://user-images.githubusercontent.com/10150807/70688159-ffa33600-1ceb-11ea-822a-c65967c377e3.png)
在最終發佈的網頁只有seo的title跑出來
其他都沒有

**Comment by AnitaRyzo** [comment]
補充：貼上已發佈的網址到「[臉書除錯](https://developers.facebook.com/tools/debug/sharing?locale=zh_TW)」頁面，會出現如下黃框的文字
![image](https://user-images.githubusercontent.com/41721950/70777927-f7b2c700-1dbb-11ea-8e39-058acc224c20.png)
黃框的文字必須出現在網頁的Elements中
![image](https://user-images.githubusercontent.com/41721950/70778019-3c3e6280-1dbc-11ea-8b27-cc5aac505c21.png)

**Comment by AnitaRyzo** [comment]
設定後台的SEO和分享資訊如下
![image](https://user-images.githubusercontent.com/41721950/71405235-c9f93800-266f-11ea-9c07-13a07fdf68e6.png)
實際執行也正確如下
![image](https://user-images.githubusercontent.com/41721950/71405279-ec8b5100-266f-11ea-928b-9c97e2c9d9c7.png)
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71882418-668f0000-316f-11ea-99d8-efcebaeda76e.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72053442-0086b200-3302-11ea-8f5c-19ee7197412c.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
