### ISSUE TITLE
審核後台更新專案後關掉頁面會跳提示

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#1753]
![image](https://user-images.githubusercontent.com/10150807/70691002-f6699780-1cf2-11ea-8f2c-9ac819af8670.png)

**Comment by AnitaRyzo** [comment]
補充路徑如下
![image](https://user-images.githubusercontent.com/41721950/70777541-0482eb00-1dbb-11ea-8cb1-32c1dbfa72db.png)

**Comment by AnitaRyzo** [comment]
審核後台更新專案後，關掉彈出頁面不會跳提示
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
審核後台更新專案後，關掉彈出頁面不會跳提示。
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
審核後台更新專案後，關掉彈出頁面不會跳提示。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
