### ISSUE TITLE
【問題】PDF版面配置圖片支援格式的提示訊息內容有誤

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1754]
PDF版面配置圖片支援格式的提示訊息紅框處與黃框處內容不同，正確支援格式為黃框處的內容。
![image](https://user-images.githubusercontent.com/49626114/70697801-2455d880-1d01-11ea-8074-35a586a3ad77.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/71431365-55c0a200-270c-11ea-99b6-0c66e045cb4f.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71880910-3f82ff00-316c-11ea-8a69-50f7539ff416.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72038254-c30f2e00-32db-11ea-8d42-0a003a4b8463.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
