### ISSUE TITLE
【問題】EDM的文字設定被隱藏

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1755]
EDM的文字設定被隱藏(紅框處)
![image](https://user-images.githubusercontent.com/49626114/70774070-2462e080-1db4-11ea-8e90-e524982d92cc.png)
點擊「...」符號展開也看不到全部的設定細項
![image](https://user-images.githubusercontent.com/49626114/70774220-8cb1c200-1db4-11ea-8b68-7732e9584f8c.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/71713971-eb63dc00-2e46-11ea-8db0-7e0953a8fccf.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
EDM的文字設定已正常顯示。
![image](https://user-images.githubusercontent.com/49626114/71880574-9b00bd00-316b-11ea-8795-327efffb7c36.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
EDM的文字設定已正常顯示與執行
![image](https://user-images.githubusercontent.com/41721950/72035606-52641380-32d3-11ea-903c-bea6d4b4ea18.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
