### ISSUE TITLE
【問題】EDM圖片的重設按鈕帶出舊紀錄

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1756]
step1. 新增「圖片」元件利用「一般上傳/原檔上傳」上傳圖片
![image](https://user-images.githubusercontent.com/41721950/70787713-42d3d680-1dca-11ea-892d-8735d143658e.png)
step2. 在同一個元件改圖片為「網頁截取」，並開啟「圖片剪裁」
![image](https://user-images.githubusercontent.com/41721950/70787949-c68dc300-1dca-11ea-8ebc-c708c3820746.png)
step3.「圖片剪裁」的跳出視窗中，按『重設』按鈕
![image](https://user-images.githubusercontent.com/41721950/70788025-f0df8080-1dca-11ea-897f-d92a942cb6b9.png)
錯誤狀況：跳出「一般上傳/原檔上傳」上傳的圖片，而非「網頁截取」的圖
![image](https://user-images.githubusercontent.com/41721950/70788115-24220f80-1dcb-11ea-8995-9abbd97729dd.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
圖片剪裁會一直保持在同一張圖片
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
根據上述操作，圖片剪裁會一直保持在同一張圖片。
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
跟著上述操作，圖片剪裁會一直保持在同一張圖片。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
