### ISSUE TITLE
【問題】EDM圖片的網頁擷取的百分比會影響輪播圖的尺寸

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1757]
EDM圖片元件的網頁擷取
![image](https://user-images.githubusercontent.com/41721950/70789555-32255f80-1dce-11ea-9d89-51f3ab55270b.png)
「選擇幻燈片」時若是100%，顯示的輪播圖是正常尺寸
![image](https://user-images.githubusercontent.com/41721950/70789356-d4911300-1dcd-11ea-97b4-8c46eb969fdc.png)
若設定至200%，顯示的輪播圖會縮小
![image](https://user-images.githubusercontent.com/41721950/70789465-0e621980-1dce-11ea-8c3c-76d715c80057.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
網頁擷取的百分比不會影響輪播圖的尺寸
![image](https://user-images.githubusercontent.com/41721950/71406397-fc586480-2672-11ea-8d93-714b149d1a6d.png)
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
網頁擷取的百分比不會影響輪播圖的尺寸
![image](https://user-images.githubusercontent.com/49626114/71880365-19a92a80-316b-11ea-99c0-587d2c5ae8bf.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
網頁擷取的百分比不會影響「輪播圖」的尺寸比例
![image](https://user-images.githubusercontent.com/41721950/72036088-c226ce00-32d4-11ea-859c-35935c8e92ff.png)
備註：但尺寸比例會影響畫面品質
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
