### ISSUE TITLE
【問題】電子申請書進入編輯模式後，按Delete卻刪除畫布區的元件

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1758]
1.進入「檔案寄出頁」可以看到背後的電子申請書元件(黃框處)，在編輯模式按Delete按鈕畫面無任何反應及改變，依然停留在檔案寄出頁的編輯模式，但背後的電子申請書元件被刪除(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/70874604-d76a4e80-1fed-11ea-883b-579c19e685a2.png)
2.在「PDF版面配置頁」增加任一頁面，點選頁面上的文字或圖片元件按Delete按鈕編輯畫面無任何反應及改變，但離開PDF版面配置頁後，電子申請書元件被刪除(紅框處)，右側元件設定區域還停留在離開PDF版面配置(橘框處)。
![image](https://user-images.githubusercontent.com/49626114/70874006-295da500-1feb-11ea-9dbc-ebd6bf3b9ecf.png)

**Comment by AnitaRyzo** [comment]
1.「檔案寄出頁」按Delete按鈕，不會有任何元件被刪除
2.「PDF版面配置頁」按Delete按鈕，電子申請書元件仍在
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1.「檔案寄出頁」按Delete按鈕，不會有任何元件被刪除。
2.「PDF版面配置頁」按Delete按鈕，電子申請書元件仍在。
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
1.「檔案寄出頁」按Delete按鈕，畫布不會有任何元件被刪除
2.「PDF版面配置頁」按Delete按鈕，電子申請書元件仍在
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
