### ISSUE TITLE
【問題】按了LOGO未回到首頁

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1759]
無論是在專案、EDM或Banner的編輯環境，按了左上角的LOGO未回到首頁
![image](https://user-images.githubusercontent.com/41721950/70875371-b7885a00-1ff0-11ea-803c-1f3f5c62fd03.png)
在Windows或Mac皆有發生，但不是人人有此狀況
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
無論是在專案、EDM或Banner的編輯環境，按了左上角的LOGO皆可回到首頁
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在專案、EDM或Banner的編輯環境，按了左上角的LOGO皆可回到首頁。
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
在專案、EDM或Banner的編輯環境，按了左上角的LOGO皆可回到首頁。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
