### ISSUE TITLE
【問題】文字元件在電腦版瀏覽器佔用更多的空間

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1761]
在客戶的操作中，文字元件設定的大小為「text-wrap.small」
但預點選圖片的超連結時，卻只有綠框的大小是感應範圍
![image](https://user-images.githubusercontent.com/41721950/70885515-02679900-2014-11ea-9bea-6ed730be409e.png)
從單行文字可知，「inner-box」的尺寸大約等於兩倍的「text-wrap.small」
![image](https://user-images.githubusercontent.com/41721950/70887212-478dca00-2018-11ea-9962-63d9b585df83.png)
當時的暫解是請客戶將圖片移到圖層的最上層，但請協助解決文字元件佔用空間的問題。感恩~

**Comment by AnitaRyzo** [comment]
文字元件設定的大小為「text-wrap.handle-size」，此範圍之外的可以點擊圖片連結
![image](https://user-images.githubusercontent.com/41721950/71401515-11c69200-2665-11ea-94ee-ecdf8cca4ab7.png)
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
文字元件設定的大小為「text-wrap.handle-size」，此範圍之外的可以點擊圖片連結。
![image](https://user-images.githubusercontent.com/49626114/71878323-558dc100-3166-11ea-9b82-bc4ca95ef537.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
文字元件設定的大小為「text-wrap.handle-size」，此範圍之外的可以點擊圖片連結。
![image](https://user-images.githubusercontent.com/49626114/72052791-c537b380-3300-11ea-96ea-196c791878fc.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
