### ISSUE TITLE
【問題】在互動後台切換不同互動遊戲時，「中獎名單」的資料未即時切換。

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1762]
問題1.
從互動A(橘框處)切換到互動C-1(綠框處)時，登入人數及抽獎次數顯示為1(黃框處)，但中獎名單卻有兩筆資料且是互動A的資料(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/70888023-49f12380-201a-11ea-8fbd-396da90020f3.png)
互動C-1正確的中獎名單資料應顯示如下圖綠框處
![image](https://user-images.githubusercontent.com/49626114/70887276-77d56880-2018-11ea-8651-1e5f4bb0a7d1.png)
問題2.
從獎項列表或社群列表(橘框處)切換到中獎名單(黃框處)時，顯示無資料(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/70890578-5ed0b580-2020-11ea-80c5-6ef3278ddafa.png)

**Comment by AnitaRyzo** [comment]
解答一：已正確顯示的中獎名單資料
解答二：從獎項列表或社群列表切換到中獎名單再到「中獎名單」時，會正確顯示
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1. 切換不同互動遊戲時，「中獎名單」的資料已及時切換且正確顯示。
2. 從獎項列表或社群列表切換到中獎名單再到「中獎名單」時，會正確顯示。
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
答一：已正確顯示的中獎名單資料
答二：從獎項列表或社群列表切換到中獎名單再到「中獎名單」時，會正確顯示
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
