### ISSUE TITLE
【問題】資料綁定的數據後台資料，跨月份後就顯示暫無數據

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1767]
曾經依照資料綁定的數據後台資料編寫資料
![image](https://user-images.githubusercontent.com/41721950/70969997-43c17c80-20d8-11ea-9018-d76990f9a001.png)
但從「數據後台-資料綁定」進入後
![image](https://user-images.githubusercontent.com/41721950/70970261-d7934880-20d8-11ea-863b-23466385e8a2.png)
顯示『暫無數據』
![image](https://user-images.githubusercontent.com/41721950/70970637-cf87d880-20d9-11ea-80b1-82b2c0e533e3.png)
疑問：開啟『資料綁定』的數據時，預設是七日內還是跟著外層的「篩選時間」(紅框)險示資料??
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
資料綁定的預設是三十天，超過可以自行調整日期
![image](https://user-images.githubusercontent.com/41721950/71431268-a388da80-270b-11ea-84fe-a3671a3eafc6.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
從「數據後台-資料綁定」進入後，原預設篩選時間為三十天，若數據資料超過30天內則可調整自訂時間(綠框處)
![image](https://user-images.githubusercontent.com/49626114/71872666-16587380-3158-11ea-952f-320d8778ec61.png)
即可看到資料綁定專案的數據
![image](https://user-images.githubusercontent.com/49626114/71872581-d3969b80-3157-11ea-83c8-16a48cf25609.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
從「數據後台-資料綁定」進入後，原預設篩選時間為三十天，若數據資料超過30天內則可調整自訂時間(黃框處)。
![image](https://user-images.githubusercontent.com/49626114/72122774-13e55c00-339a-11ea-8899-34e094cebb68.png)
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
