### ISSUE TITLE
【MongoDB】恭喜中獎頁未顯示匯入獎項的序號樣式

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1768]
互動遊戲匯入序號不管選擇哪一種樣式(黃框處)
![image](https://user-images.githubusercontent.com/49626114/70974506-dd8e2700-20e2-11ea-8b8a-3cf5ad669634.png)
在各狀態提示頁和發佈頁的「恭喜中獎」頁皆不會顯示序號(欄位一)的內容(紅框處)
![image](https://user-images.githubusercontent.com/49626114/70975555-234bef00-20e5-11ea-85e8-8772afa2fb50.png)
已確認規格書的內容描述如下
![image](https://user-images.githubusercontent.com/49626114/70975821-a8370880-20e5-11ea-8fdf-c847f7cc295b.png)

**Comment by ai015606220** [comment]
請問你上傳的序號，第一欄都長什麼樣子? 有錯誤訊息嗎?

**Comment by AnitaRyzo** [comment]
序號的樣子如下
![image](https://user-images.githubusercontent.com/41721950/70976740-7626a600-20e7-11ea-8d0a-a9faa9dcb2e9.png)
應該沒有看到錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/70976997-f3521b00-20e7-11ea-92be-b22ed4a2fab4.png)

**Comment by ai015606220** [comment]
能請你把檔案給我嗎? 還有錯誤訊息是指console那邊的

**Comment by AnitaRyzo** [comment]
請收檔案 [檔案四.xlsx](https://github.com/ryuichl/v3-report/files/3972103/default.xlsx)
console沒有錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/70977361-b8041c00-20e8-11ea-86ab-06a656927375.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/71439576-22ded400-2735-11ea-9db4-a52505a13085.png)
![image](https://user-images.githubusercontent.com/41721950/71439588-2d996900-2735-11ea-8d36-9fcaee6d526e.png)
![image](https://user-images.githubusercontent.com/41721950/71439613-430e9300-2735-11ea-9a0b-45c10a9a6966.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71872294-ed83ae80-3156-11ea-8c36-3748ab656f2a.png)
◎◎ 20200107確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72049187-6589da00-32f9-11ea-876c-0b5f3320599c.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
