### ISSUE TITLE
【問題】表單跳題在預覽時會整個畫面往上移

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1769]
表單有跳題的題型時，跳題後會把最上層的功能列覆蓋
![image](https://user-images.githubusercontent.com/41721950/71070685-42ff1800-21b6-11ea-8b8a-efb86d115435.png)
覆蓋的狀態如下
![image](https://user-images.githubusercontent.com/41721950/71070876-940f0c00-21b6-11ea-8ec2-980fc3557a64.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
表單跳題在預覽已不會整個畫面往上移
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
表單跳題在預覽已不會整個畫面往上移。
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
表單跳題在預覽已不會整個畫面往上移。
◎◎ 20200107確認以上測試環境內容MS SQL◎◎
