### ISSUE TITLE
【建議】對齊工具定位點

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#177]
HI
一點小建議,但不知合不合適,或適能不能製作得出來,供參考

目前幻燈片裡製作長頁面,會有個遮罩顯示目前編輯的區塊

但是當我的元件選擇向上對齊時,他還是會對齊到幻燈片得最上或最下

不知能否針對目前編輯區域作對齊

**Comment by ryuichl** [comment]
太久先關掉
有一樣問題再提出
