### ISSUE TITLE
【問題】跳出視窗的狀態中，背景仍可被操作

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1770]
跳出視窗的『選擇一般/序號/抽獎表單』『互動遊戲-設定獎項』『資料綁定-匯入-檔案預覽』...等，
在windows可以按「上一頁」與MAC電腦觸控版的滑動，都會產生此狀況。
![image](https://user-images.githubusercontent.com/41721950/71139128-4511b700-2248-11ea-8e02-a6f2f1f3762c.png)
甚至是在跳出視窗的狀態，按下「Backspace」或「Delete」按鈕，都會刪除畫布中的元件。
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
跳出視窗的「上一頁」未解決，而「Backspace」或「Delete」按鈕，不會刪除畫布中的元件。
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
跳出視窗的『選擇一般/序號/抽獎表單』『互動遊戲-設定獎項』『資料綁定-匯入-檔案預覽』...等，皆未出現此問題；且「Backspace」或「Delete」按鈕，不會刪除畫布中的元件。
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
跳出視窗的『選擇一般/序號/抽獎表單』『互動遊戲-設定獎項』『資料綁定-匯入-檔案預覽』...等，皆未出現此問題；且「Backspace」或「Delete」按鈕，不會刪除畫布中的元件。
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
跳出視窗的『選擇一般/序號/抽獎表單』『互動遊戲-設定獎項』『資料綁定-匯入-檔案預覽』...等，皆未出現此問題；且「Backspace」或「Delete」按鈕，不會刪除畫布中的元件。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
