### ISSUE TITLE
【問題】兩個以上元件設定框架後再群組，執行後會跑版

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1771]
將兩個以上的元件設定「框架固定元件」
![image](https://user-images.githubusercontent.com/41721950/71145097-4b5d5e80-225b-11ea-89ef-2affc874b6c7.png)
將兩個以上元件組成「群組」後，問題一：最上面的元件會被複製(紅框)
![image](https://user-images.githubusercontent.com/41721950/71145167-88295580-225b-11ea-85b5-0e3d8b567354.png)
問題二：在預覽、表單列表、專案審核、瀏覽器...等看到的專案都是跑版的
![image](https://user-images.githubusercontent.com/41721950/71145282-00901680-225c-11ea-8050-71dabb0e698f.png)
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
問題一暫時玩不出來

**Comment by AnitaRyzo** [comment]
問題一：最上面的元件會被複製(紅框)
已解二：在預覽、表單列表、專案審核、瀏覽器...等看到的專案都可正常顯示
![image](https://user-images.githubusercontent.com/41721950/71430732-8999c880-2708-11ea-84fb-43e83276e681.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
問題1：最上面的元件會被複製已無法重現
已解2：元件設定框架(黃框處)及群組(橘框處)，在預覽、表單列表、專案審核、瀏覽器...等看到的專案都可正常顯示。
![image](https://user-images.githubusercontent.com/49626114/71791577-74aa2700-3070-11ea-84b2-6c613a771b7d.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
問題1：最上面的元件會被複製已無法重現
已解2：元件設定框架後再群組，目前在預覽、表單列表、專案審核、瀏覽器...等看到的專案都可正常顯示。
