### ISSUE TITLE
【問題】新增互動元件使用「選擇」時，未連動表單及各狀態提示頁的設定內容

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1772]
原專案已有互動遊戲的狀態下，再「新增」互動元件並點選「選擇」互動。(黃框處)
![image](https://user-images.githubusercontent.com/49626114/71144992-e7d33100-225a-11ea-8adb-5156f0a580de.png)
「選擇」後的專案(紅框處)並未連動原專案(綠框處)的表單設定內容及各狀態提示頁的設定內容
![image](https://user-images.githubusercontent.com/49626114/71147590-2c16ff00-2264-11ea-88f2-7b56f9099aee.png)
(此處僅以恭喜中獎頁作為範例)
![image](https://user-images.githubusercontent.com/49626114/71147701-8adc7880-2264-11ea-8553-90c9e379597f.png)

**Comment by Gabe-Liu** [comment]
使用選擇時，只會取得 您所選取的互動元件在後台的資料內容，提示頁並不包含在裡頭

**Comment by AnitaRyzo** [comment]
已記錄，謝謝回覆
