### ISSUE TITLE
【問題】複製互動元件，原序號獎項變成一般獎項，在中獎紀錄頁顯示序號說明

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1773]
原專案已有互動遊戲的狀態下，「複製」互動元件並點選「啟用」互動。(黃框處)
![image](https://user-images.githubusercontent.com/49626114/71148405-9e88de80-2266-11ea-931a-a5b973c99376.png)
原本的互動獎項1是序號獎項(黃框處)，啟用的互動獎項1是一般獎項(橘框處)
![image](https://user-images.githubusercontent.com/49626114/71148642-2242cb00-2267-11ea-9333-4ce329324b99.png)
啟用的一般獎項1在各狀態提示頁的中獎紀錄頁卻連動到原本序號獎項1的內容(黃框處)，出現了序號說明的文字(紅框處)
![image](https://user-images.githubusercontent.com/49626114/71149065-6da9a900-2268-11ea-860d-109bf8b7e551.png)

**Comment by Gabe-Liu** [comment]
序號獎項在複製後，並不會把序號也複製過去，會變成一般獎項，至於第二點問題會再做修正

**Comment by AnitaRyzo** [comment]
啟用的互動獎項是一般獎項，中獎紀錄顯示的是一般獎項
![image](https://user-images.githubusercontent.com/41721950/71606619-5a260880-2bad-11ea-8c78-e79acac19b7f.png)
◎◎ 20191231確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
啟用的互動獎項是一般獎項，中獎紀錄顯示的是一般獎項。
![image](https://user-images.githubusercontent.com/49626114/71804852-aa1a3900-309f-11ea-85ac-c10c0f6bd7a6.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
目前複製互動元件後啟用的互動獎項是一般獎項，中獎紀錄顯示的也是一般獎項。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
