### ISSUE TITLE
【問題】連續點選互動元件時，系統核銷顯示有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1774]
第一個互動元件設定「按鈕核銷」，第二個互動元件設定「QR code核銷」
![image](https://user-images.githubusercontent.com/41721950/71150609-ddba2e00-226c-11ea-8139-27c448647e87.png)
此時若連續點擊互動元件，系統核銷顯示有誤
![image](https://user-images.githubusercontent.com/41721950/71150704-1954f800-226d-11ea-880a-adf9f180d072.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
連續點選互動元件時，系統核銷顯示正確
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
連續點選互動元件時，系統核銷顯示正確。
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
連續點選互動元件時，系統核銷顯示正確。
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
