### ISSUE TITLE
【MongoDB】序號機兌換密碼的錯誤情況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1775]
序號機無輸入兌換密碼的欄位，僅有「兌換」的按鈕(紅框處)。
按「兌換」按鈕畫面無反應，network顯示「密碼錯誤」(橘框處)。
![image](https://user-images.githubusercontent.com/49626114/71153431-0f82c300-2274-11ea-94c2-9f0d4d533bdc.png)

**Comment by ai015606220** [comment]
@Gabe-Liu 再幫我確認一下app-cpt-serial: 175的this.serialData.serial_number的格式問題

**Comment by AnitaRyzo** [comment]
序號機的密碼已可正確兌換
![image](https://user-images.githubusercontent.com/41721950/71453319-a47e4280-27c5-11ea-8bf4-8611971c9af6.png)
![image](https://user-images.githubusercontent.com/41721950/71453326-aea04100-27c5-11ea-9af2-f2b475e28ae3.png)
◎◎ 20191226確認以上測試環境內容in MongoDB◎◎

**Comment by Gabe-Liu** [comment]
20191226 確認serialData.serial_number在mongo與msql都是number型態

**Comment by cocosu123** [comment]
序號機的密碼已可正確兌換。
![image](https://user-images.githubusercontent.com/49626114/71804176-adacc080-309d-11ea-98ec-b675e0d69879.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
序號機的密碼已可正確兌換。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
