### ISSUE TITLE
【MongoDB】設定QR Code核銷時，狀態提示頁未立即顯示QR Code

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1776]
互動元件一開始的核銷方式設定為QR Code核銷時(黃框處)
![image](https://user-images.githubusercontent.com/49626114/71154813-5de59100-2277-11ea-903c-9b70a52b45cc.png)
在恭喜中獎頁和中獎紀錄頁都不會顯示QR Code(如紅框處，不管是編輯區、預覽頁、發佈頁皆有此問題)
![image](https://user-images.githubusercontent.com/49626114/71155039-da786f80-2277-11ea-86df-79bcbac76263.png)
必須要先將核銷方式改為「按鈕核銷」(橘框處)，再改回「QR Code核銷」
![image](https://user-images.githubusercontent.com/49626114/71155434-a81b4200-2278-11ea-9094-99c03ab129ca.png)
此時恭喜中獎頁和中獎紀錄頁的QR Code才會正常顯示(綠框處)
![image](https://user-images.githubusercontent.com/49626114/71155537-e3b60c00-2278-11ea-96d1-64d809388538.png)

**Comment by AnitaRyzo** [comment]
設定QR Code核銷時，恭喜中獎頁和中獎紀錄頁都會顯示QR Code
![image](https://user-images.githubusercontent.com/41721950/71438377-8581a100-2730-11ea-9a83-f5c1bd864356.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
設定QR Code核銷時，恭喜中獎頁和中獎紀錄頁都會顯示QR Code。
![image](https://user-images.githubusercontent.com/49626114/71802906-3c1f4300-309a-11ea-9ffd-b734dd714b3c.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
設定QR Code核銷時，恭喜中獎頁和中獎紀錄頁都會顯示QR Code。
![image](https://user-images.githubusercontent.com/49626114/72047398-6587db00-32f5-11ea-8bd3-0cea911f7e94.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
