### ISSUE TITLE
【問題】複製元件「全選」卻未勾選全部元件

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1778]
複製元件選擇「全選」(黃框處)時，在元件選取的地方卻未勾選全部元件(如紅框處元件未被勾選)。
![image](https://user-images.githubusercontent.com/49626114/71224807-6b4f5980-2311-11ea-83c0-b8e52e992a44.png)

**Comment by AnitaRyzo** [comment]
按下「複製至其他位置」按鈕後點「全選」，所有元件都會被勾選
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
按下「複製至其他位置」按鈕後點「全選」，所有元件都會被勾選。
![image](https://user-images.githubusercontent.com/49626114/71802629-3b39e180-3099-11ea-97d5-279dd756c3c3.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
按下「複製至其他位置」按鈕後點「全選」，所有元件都會被勾選。
![image](https://user-images.githubusercontent.com/49626114/72036580-34e47900-32d6-11ea-8327-812e422bd688.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
