### ISSUE TITLE
【問題】離開提示編輯模式後，元件設定未關閉

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1779]
在元件被選取(黃框處)的狀況下，點擊離開提示編輯模式(橘框處)
![image](https://user-images.githubusercontent.com/49626114/71227094-0dbf0b00-2319-11ea-9e5b-0c1c264af35d.png)
已離開提示編輯模式後，右側的元件設定卻未關閉(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/71227105-1d3e5400-2319-11ea-871e-e122da3bd629.png)

**Comment by AnitaRyzo** [comment]
元件被選取的狀況下，點擊離開提示編輯模式，不會留下右邊的元件設定
![image](https://user-images.githubusercontent.com/41721950/71398761-76c9ba00-265c-11ea-95fa-b908207343cf.png)
◎◎ 20191224確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
元件被選取的狀況下，點擊離開提示編輯模式，不會留下右邊的元件設定(橘框處)。
![image](https://user-images.githubusercontent.com/49626114/71802502-cebee280-3098-11ea-9913-2b811c6a552a.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
依照上述操作，在元件被選取的狀況下點擊離開提示編輯模式，已不會留下右邊的元件設定。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
