### ISSUE TITLE
【建議】帳號管理icon

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#178]
hi, 一個渺小的心願

目前帳號管理的icon可能比較難跟"帳號"做關聯

我覺得帳號的常見icon可能還是以人頭為主  可能是單人或多人的icon
 附上圖例

![123](https://user-images.githubusercontent.com/34327325/40099019-c477f20a-5910-11e8-8856-d6d9565a1fb4.PNG)
![default](https://user-images.githubusercontent.com/34327325/40099020-c4a09336-5910-11e8-8748-87ca1d86c563.PNG)

**Comment by Samasianspock** [comment]
已請eating修改
