### ISSUE TITLE
【MongoDB】圖片元件的連結網址無法顯示圖片

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1782]
圖片元件的「選擇圖片」設定，可以「圖片上傳」也可以「連結網址」
![image](https://user-images.githubusercontent.com/41721950/71389413-40c60f00-2637-11ea-8c67-6df4c6a8dbfe.png)
問題一：在編輯區放入網址後，從未出現圖片；但預覽區出現了
![image](https://user-images.githubusercontent.com/41721950/71389605-03ae4c80-2638-11ea-915e-f2683f4f6c36.png)
問題二：發佈至瀏覽器後也無法顯示圖片
![image](https://user-images.githubusercontent.com/41721950/71390429-4d4c6680-263b-11ea-9805-a5b585bf9e19.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
目前圖片元件的連結網址都有正常顯示
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
目前圖片元件的連結網址都有正常顯示。
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
目前圖片元件的連結網址都有正常顯示。
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
