### ISSUE TITLE
【MongoDB】修改表單名稱後，表單名稱未立即變更

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1783]
在表單管理後台點擊編輯按鈕(黃框處)修改表單名稱，將原本的新表單名稱(橘框處)改為手勢評分(紅框處)
![image](https://user-images.githubusercontent.com/49626114/71390464-7a007e00-263b-11ea-92b3-589ef0a059a6.png)
確認儲存後，表單名稱未立即變更(紅框處)，但是從network查看表單名稱已被變更(綠框處)
![image](https://user-images.githubusercontent.com/49626114/71390508-9f8d8780-263b-11ea-9f07-8f8a9a4daecb.png)

**Comment by AnitaRyzo** [comment]
修改表單名稱後，表單名稱已立即變更
![image](https://user-images.githubusercontent.com/41721950/71714093-63320680-2e47-11ea-9247-aa7af77967a3.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
修改表單名稱後，表單名稱已立即變更。
![image](https://user-images.githubusercontent.com/49626114/71789431-08c2c100-3066-11ea-87d3-7c86083c1046.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
在表單管理修改表單名稱後，表單名稱已會即時更新。
![image](https://user-images.githubusercontent.com/41721950/71877716-d51a9080-3164-11ea-8046-8a48f30e9466.png)
![image](https://user-images.githubusercontent.com/41721950/71877799-04c99880-3165-11ea-93c6-1c2f68795eb7.png)
◎◎ 20200107確認以上測試環境內容MS SQL◎◎
