### ISSUE TITLE
【問題】數據後台的下載按鈕，未隨切換專案而改變下載的資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1784]
數據後台的專案中，可以點選其中一個專案的「查看細節」，進入細節頁
![image](https://user-images.githubusercontent.com/41721950/71396867-b5f50c80-2656-11ea-852a-827b92e335f8.png)
細節頁的資料切換下方處有「下載數據-下載按鈕」
點選中間的專案時，會看到資料的變動(綠框)；但按下「下載」後，卻只會下載到進入細節頁的「專案數據資料」
![image](https://user-images.githubusercontent.com/41721950/71396822-8a722200-2656-11ea-8bfc-16dbcd0005b0.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
細節頁的資料切換下方處之「下載數據-下載按鈕」可以正確下載所點選的專案數據
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
細節頁的資料切換下方處之「下載數據-下載按鈕」切換專案後，已可以正確下載所點選的專案數據。
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
細節頁的資料切換下方處之「下載數據-下載按鈕」切換專案後，已可以正確下載所點選的專案數據。
◎◎ 20200110確認以上測試環境內容MS SQL◎◎
