### ISSUE TITLE
【正式環境】序號機使用「選擇」時，出現的錯誤情況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1785]
將A和B兩個序號機放在同個頁面(B序號機是使用「選擇」A序號機，如黃框處)
![image](https://user-images.githubusercontent.com/49626114/71396896-d45b0800-2656-11ea-9fef-246a3939d4d8.png)
發佈後先點擊A序號機並填寫表單領取序號，再點擊B序號機並填寫表單，填寫完成後會跳出黃框處訊息，接著再跳出橘框處的訊息
![image](https://user-images.githubusercontent.com/49626114/71397014-22700b80-2657-11ea-93a1-f1f63f4bc44d.png)
回到表單管理後台查看時，也確實有兩筆資料，但是第二筆資料不完整(紅框處)
![image](https://user-images.githubusercontent.com/49626114/71397096-767af000-2657-11ea-8ab4-9c1d1fa41056.png)
在此狀況下點擊下載表單則會出現錯誤訊息
![image](https://user-images.githubusercontent.com/49626114/71397129-97dbdc00-2657-11ea-9160-322827a05c88.png)
必須刪除第二筆表單資料才能正常下載表單回覆的EXCEL檔。

**Comment by AnitaRyzo** [comment]
依照上述步驟，第一個領取序號呈現左邊的正確訊息；非第一次領取序號呈現右邊的錯誤訊息。
![image](https://user-images.githubusercontent.com/41721950/71575873-80a26000-2b29-11ea-9759-ceefaeba8179.png)
但後台卻仍將空白資料回傳(紅框)，但是下載是只有正確回覆的訊息。
![image](https://user-images.githubusercontent.com/41721950/71575937-bba49380-2b29-11ea-8188-38d560f8eaff.png)
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
依照上述步驟操作，若重複領取會跳出提示訊息(綠框處)，但後台仍會將空白資料回傳(紅框處)，但是下載是只有正確回覆的訊息(橘框處)。
![image](https://user-images.githubusercontent.com/49626114/71801418-d4ff8f80-3095-11ea-87f0-d034aca05d2e.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
依照上述步驟操作，若重複領取會跳出提示訊息，但後台仍會將空白資料回傳(黃框處)，但是下載是只有正確回覆的訊息。
![image](https://user-images.githubusercontent.com/49626114/72050696-ba7b1f80-32fc-11ea-9d68-ddc4395b3464.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
