### ISSUE TITLE
【疑問】動態網址的按鈕資料未寫入數據後台的連結分析

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1786]
按鈕加了「動態網址」
![image](https://user-images.githubusercontent.com/41721950/71397148-a3c79e00-2657-11ea-861f-ba575e10750f.png)
並利用此按鈕連結網頁
![image](https://user-images.githubusercontent.com/41721950/71397311-251f3080-2658-11ea-9e92-61ee2665b7a4.png)
但在『數據後台-連結分析』卻未顯示動態連結數據
![image](https://user-images.githubusercontent.com/41721950/71397646-1dac5700-2659-11ea-9e42-97c388e38948.png)

請協助確認此資料是否可以寫入，感恩~

**Comment by ryuichl** [comment]
這個專案網址可以提供嗎?
感恩

**Comment by AnitaRyzo** [comment]
https://but2.ryzoweba.com
請查收

**Comment by ryuichl** [comment]
之前忘了甚麼原因這邊會自動把qurystring去掉
目前我把他加回來
再看會有甚麼影響
重新操作一次就會有數據了

**Comment by AnitaRyzo** [comment]
qurystring已加入連結中
![image](https://user-images.githubusercontent.com/41721950/71430177-4f7af780-2705-11ea-97fa-54951f539bc0.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71801008-97e6cd80-3094-11ea-995a-899bdc607b34.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72043514-5d776d80-32ec-11ea-922b-59878f9c1dd3.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
