### ISSUE TITLE
【MangoDB】MGM的活動紀錄設定內容消失

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1787]
MGM的活動紀錄圖示(黃框處)依然存在，但是MGM的活動紀錄設定(紅框處)內容卻消失了。
![image](https://user-images.githubusercontent.com/49626114/71431071-65d78200-270a-11ea-92ca-880a62d4d745.png)
疑問備註：
分享機制本來是左右排列，但是現在變成上下排列(橘框處)，是否不小心變動到分享機制的排列方式呢?
![image](https://user-images.githubusercontent.com/49626114/71431115-bd75ed80-270a-11ea-96f6-317fd8b4ebd2.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/71606763-cce3b380-2bae-11ea-8b1a-18ce5d460b9c.png)
◎◎ 20191231確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71798960-ceb9e500-308e-11ea-8660-c581737a01b0.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72036013-7ffd8c80-32d4-11ea-9d1d-47097fba3900.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
