### ISSUE TITLE
【MongoDB】MGM複製專屬連結的錯誤狀況

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1788]
在MGM的專屬連結分享提示頁中設定社群分享內容(黃框處)
![image](https://user-images.githubusercontent.com/49626114/71438004-df816700-272e-11ea-8a25-5298d05611f0.png)
發佈後，複製專屬連結(點擊紅框處)打開網頁
![image](https://user-images.githubusercontent.com/49626114/71438369-7a2e7580-2730-11ea-8cc0-6db1108f2c7e.png)
會有以下兩種情況：
1. 專屬連結是縮網址(橘框處)，則網頁會呈現如右圖的錯誤狀況。
![image](https://user-images.githubusercontent.com/49626114/71438071-30915b00-272f-11ea-9714-00b8c5c95614.png)
2. 專屬網址不是縮網址(橘框處)，則MGM會呈現「尚未建立分享換優惠」(如紅框處)。
![image](https://user-images.githubusercontent.com/49626114/71438184-a09fe100-272f-11ea-92f1-cb916e8b119f.png)

**Comment by ryuichl** [comment]
第一個情境是故意做那樣的
因為是要給他貼給別人看
不是直接貼到瀏覽器看

**Comment by ryuichl** [comment]
感覺第二個情境也是因為這個原因
我們會把分享的字接到連結後面
造成這個結果

**Comment by cocosu123** [comment]
上述相同的做法在手機上操作MGM會正常呈現且可以正常執行。

**Comment by cocosu123** [comment]
MGM專屬連結的設計情境是要讓使用者從社群分享給其他人，而不是直接貼在瀏覽器上。
因此在電腦版會將空格自動編碼(如紅框處)再加上「社群分享內容」造成上述的結果。
![image](https://user-images.githubusercontent.com/49626114/71453165-d9d66080-27c4-11ea-9132-04ff7f1c8414.png)
而在手機版上則會自動將「專屬連結」和「社群分享內容」分開。
2019/12/26補充說明
