### ISSUE TITLE
【MongoDB】無數據的提示視窗未出現文字

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1789]
無數據的提示視窗未出現文字
![image](https://user-images.githubusercontent.com/41721950/71432122-34fb4b00-2712-11ea-9aeb-17297f7c909f.png)
◎◎ 20191225確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/71572083-72981380-2b18-11ea-9273-708bc525d7e6.png)
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/71798280-708c0280-308c-11ea-9750-bff60f47e68b.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
![image](https://user-images.githubusercontent.com/49626114/72034089-03b47a80-32cf-11ea-950a-89fac3e90ea3.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
