### ISSUE TITLE
【MongoDB】文字編輯器的提示視窗內容是英文

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1790]
文字編輯器的提示視窗內容是英文(如紅框處)，黃框處的提示視窗皆顯示為英文內容。
![image](https://user-images.githubusercontent.com/49626114/71461093-8b878880-27e9-11ea-9770-a5ccffb72998.png)

**Comment by AnitaRyzo** [comment]
文字編輯器的提示視窗內容已改為中文，而在英文語系顯示英文
![image](https://user-images.githubusercontent.com/41721950/71572136-bbe86300-2b18-11ea-9827-a5968c61e3a6.png)
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
文字編輯器的提示視窗內容已改為中文，而在英文語系顯示英文。
![image](https://user-images.githubusercontent.com/49626114/71789128-b7b1cd80-3063-11ea-9c63-99537bd69dd2.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
文字編輯器的提示視窗內容已改為中文，而在英文語系顯示英文。
![image](https://user-images.githubusercontent.com/49626114/72033904-8c7ee680-32ce-11ea-86ef-a56fdb7989d7.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
