### ISSUE TITLE
【MongoDB】資料綁定的分類設定未能即時顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1791]
資料綁定的分類設定，預覽的畫面一直保持如下，直到切換上方功能列
![image](https://user-images.githubusercontent.com/41721950/71464942-25edc900-27f6-11ea-8a96-68614cb2ad02.png)
無論是文字或是任何設定都不會即時出現在預覽區，而圖片的「連結網址」自動跳「undefined」
![image](https://user-images.githubusercontent.com/41721950/71465200-e2e02580-27f6-11ea-8f23-7791a8a939ce.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
所有設定都會即時出現在預覽區，而圖片的「連結網址」也不會出現undefined
![image](https://user-images.githubusercontent.com/41721950/71714414-bc4e6a00-2e48-11ea-90a8-9a48d4cae525.png)
![image](https://user-images.githubusercontent.com/41721950/71714437-dc7e2900-2e48-11ea-94bb-f9bf8e1c8bd3.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
所有設定都會即時出現在預覽區，而圖片的「連結網址」也不會出現undefined。
![image](https://user-images.githubusercontent.com/49626114/71797912-0888ec80-308b-11ea-8ed4-164e308e420c.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
所有設定都會即時出現在預覽區，而圖片的「連結網址」也不會出現undefined。
![image](https://user-images.githubusercontent.com/49626114/72044114-ea6ef680-32ed-11ea-9a2f-b7669d46d43a.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
