### ISSUE TITLE
【MongoDB】同時複製貼上多個元件，卻不能一次移動多個元件

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1792]
在io環境，同時複製貼上多個元件，第一時間可以同時移動「貼上的所有元件」
![image](https://user-images.githubusercontent.com/41721950/71465871-bc22ee80-27f8-11ea-984c-271e3dcc181e.png)
但是在com環境，只能移動「其中一個貼上的元件」
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
同時複製貼上多個元件，可一次移動多個元件
![image](https://user-images.githubusercontent.com/41721950/71714211-e81d2000-2e47-11ea-9f89-7b3f067b09c0.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
同時複製貼上多個元件，可一次移動多個元件
![image](https://user-images.githubusercontent.com/49626114/71790599-3579d700-306c-11ea-8ef2-f1313f751d9d.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
同時複製貼上多個元件，可一次移動多個元件。
![image](https://user-images.githubusercontent.com/49626114/72033735-19757000-32ce-11ea-8408-029af0cb02c3.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
