### ISSUE TITLE
【MongoDB】臉書工具發佈後未顯示且出現錯誤訊息

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1793]
臉書工具發佈後未顯示任何內容且出現錯誤訊息(內嵌型和動作型皆有此問題)
![image](https://user-images.githubusercontent.com/49626114/71468876-681d0780-2802-11ea-9c31-94a446b7f11c.png)
備註：無論是動作型或內嵌型的臉書工具都有此狀況

**Comment by cocosu123** [comment]
臉書工具(動作型&內嵌型)發佈後已出現。
![image](https://user-images.githubusercontent.com/49626114/71714668-bc029e80-2e49-11ea-83a6-b59d651ef402.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by AnitaRyzo** [comment]
編輯區的樣貌
![image](https://user-images.githubusercontent.com/41721950/71792632-652cdd00-3074-11ea-8b2e-c6462a04fa56.png)
臉書工具(動作型&內嵌型)在uat、發佈後、專案與審核/發佈的預覽皆有出現
![image](https://user-images.githubusercontent.com/41721950/71793023-ecc71b80-3075-11ea-8203-e7dd9b67d686.png)
◎◎ 20200106確認以上正式環境內容 ◎◎

**Comment by cocosu123** [comment]
臉書工具已正常顯示。
![image](https://user-images.githubusercontent.com/49626114/72035647-71fb3c00-32d3-11ea-9629-0d4b0dff8c8e.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
