### ISSUE TITLE
【MongoDB】Banner的元件之編輯框皆未能即時縮放與預覽設定

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1794]
Banner的所有元件皆有此錯誤狀況
![image](https://user-images.githubusercontent.com/41721950/71470447-17f47400-2807-11ea-80b2-c1e41ca9c2f4.png)
問題一：畫布區的編輯框(綠色)未完整包覆元件(ex:裝飾圖案的編輯框線)
![image](https://user-images.githubusercontent.com/41721950/71470419-0ad78500-2807-11ea-8cfa-99a4a279b949.png)
問題二：設定的項目皆未即時顯示，必須切換畫布才會出現
→圖一與圖二的設定相同，只差在切換畫布
![image](https://user-images.githubusercontent.com/41721950/71470525-6dc91c00-2807-11ea-8f07-6bdbfa21809e.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
解決一：畫布區的編輯框(綠色)會完整包覆元件
解決二：設定的項目皆會即時顯示
◎◎ 20191231確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
1. 畫布區的編輯框(綠色)會完整包覆元件
2. 文字、圖示、裝飾圖案皆會即時顯示。
圖片延伸問題已寫issue #1822
 ◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
解一：畫布區的編輯框(綠色)會完整包覆元件
解二：文字、圖示、裝飾圖案皆會即時顯示，圖片要托移或編輯才會顯示
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
