### ISSUE TITLE
【MongoDB】表單「送出後執行動作」無法選擇頁面和提示

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1796]
在編輯頁已設定頁面2(橘框處)和提示(黃框處)，「送出後執行動作」選擇頁面或提示時，卻沒有頁面跟提示的內容可以選擇(如紅框處)。
![image](https://user-images.githubusercontent.com/49626114/71503633-fa7be480-28b0-11ea-9930-f2f4b48ce68b.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/71573068-f81dc280-2b1c-11ea-94c3-91a61543b947.png)
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
「送出後執行動作」已可選擇頁面及提示，且也都可以正常執行。
![image](https://user-images.githubusercontent.com/49626114/71793771-4846d880-3079-11ea-95be-5d332571d599.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
「送出後執行動作」已可選擇頁面及提示，且也都可以正常執行。
![image](https://user-images.githubusercontent.com/41721950/71950139-339d4880-3211-11ea-89a6-4b658d18aea4.png)
◎◎ 20200108確認以上測試環境內容in MongoDB◎◎
