### ISSUE TITLE
【問題】電子申請書檔案寄出頁的「上方文字」陰影失效

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1797]
電子申請書檔案寄出頁的「上方文字」設定陰影(黃框處)，但是畫面上卻未顯示(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/71506862-8bf15380-28bd-11ea-8196-4b65b38d1111.png)
且原本已勾選開啟陰影設定(如上圖黃框處)，離開提示編輯模式後再回到檔案寄出頁設定時，陰影的勾選設定會自動被取消(如下圖橘框處)。
![image](https://user-images.githubusercontent.com/49626114/71507016-05894180-28be-11ea-91cf-d899c42576af.png)

**Comment by AnitaRyzo** [comment]
「上方文字」設定陰影，畫布區會即時顯示
![image](https://user-images.githubusercontent.com/41721950/71573227-b7727900-2b1d-11ea-9c91-a7316609ab15.png)
◎◎ 20191230確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
電子申請書檔案寄出頁的「上方文字」設定陰影，畫布區會即時顯示。
![image](https://user-images.githubusercontent.com/49626114/71793409-aa9ed980-3077-11ea-80a8-abb7e0a0182d.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
電子申請書檔案寄出頁的「上方/下方文字」設定陰影，畫布區會即時顯示。
![image](https://user-images.githubusercontent.com/41721950/72042367-4f741d80-32e9-11ea-990d-6482eb532d0e.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
