### ISSUE TITLE
【MongoDB】圖片素材跟圖片庫不該出現資料綁定狀態

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1801]
已確認Banner的圖片素材跟圖片庫不該出現內容狀態
![image](https://user-images.githubusercontent.com/41721950/71568182-2640d980-2b00-11ea-84c1-480fbf32393a.png)
已確認專案的圖片素材跟圖片庫不該出現內容狀態
![image](https://user-images.githubusercontent.com/41721950/71571733-bdb12700-2b16-11ea-98bf-c54f603f6260.png)

以上問題請協助處理，感恩~

**Comment by cocosu123** [comment]
圖片元件跟圖片庫已沒有出現資料綁定的內容狀態(綠框處)。
![image](https://user-images.githubusercontent.com/49626114/71713527-0df4f580-2e45-11ea-82a1-83e79d38b312.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
圖片元件跟圖片庫已沒有出現資料綁定的內容狀態(橘框處)。
![image](https://user-images.githubusercontent.com/49626114/71793203-ceadeb00-3076-11ea-9df5-f9d526deba30.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
專案與Banner的圖片元件跟圖片庫已沒有出現資料綁定的下拉選項
![image](https://user-images.githubusercontent.com/41721950/72030384-cac2d880-32c3-11ea-83cf-a2c21d1ea9c3.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
