### ISSUE TITLE
【問題】互動遊戲無兌獎獎項，中獎紀錄頁的錯誤狀態

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1802]
當設定獎項未有一個是『開啟兌獎』
![image](https://user-images.githubusercontent.com/41721950/71569584-1da1d080-2b0b-11ea-9e5f-001537a914dd.png)
點擊狀態(提示)頁的「中獎紀錄」，畫布區內容是空白的，且也不會保留點擊在「中獎紀錄」(紅框)
![image](https://user-images.githubusercontent.com/41721950/71569632-740f0f00-2b0b-11ea-9554-6a5e383b3183.png)

console錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/71569606-4629ca80-2b0b-11ea-9abd-b98609742065.png)

**Comment by Gabe-Liu** [comment]
經過討論，會出現"無可兌換獎項"的字樣(發佈後不會出現)

**Comment by cocosu123** [comment]
互動遊戲無兌獎獎項的情況下，在中獎紀錄頁會顯示「無可兌換獎項」。
![image](https://user-images.githubusercontent.com/49626114/71713145-73e07d80-2e43-11ea-97ff-0e4f6191366d.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
互動遊戲無兌獎獎項的情況下，在中獎紀錄頁會顯示「無可兌換獎項」。
![image](https://user-images.githubusercontent.com/49626114/71792315-38c49100-3073-11ea-9f22-53acb47ee228.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by cocosu123** [comment]
互動遊戲無兌獎獎項的情況下，在中獎紀錄頁會顯示「無可兌換獎項」。
![image](https://user-images.githubusercontent.com/49626114/72044542-f3ac9300-32ee-11ea-812e-8d89db667414.png)
◎◎ 20200109確認以上測試環境內容MS SQL◎◎
