### ISSUE TITLE
【MongoDB】互動後台社群列表和中獎名單的「來源」和「社群ID」顯示的內容不同

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1803]
在互動後台的社群列表(黃框處)和中獎名單(紅框處)顯示的「來源」和「社群ID」內容不同。
![image](https://user-images.githubusercontent.com/49626114/71570256-209ec000-2b0f-11ea-882a-a893848c736a.png)

**Comment by ryuichl** [comment]
一個抽獎同個帳號出現兩次會有此狀況
目前已修正

**Comment by cocosu123** [comment]
目前在互動抽獎同個帳號出現兩次以上已不會有上述情況發生，中獎名單的「來源」和「社群ID」皆正常顯示。
![image](https://user-images.githubusercontent.com/49626114/71711802-9c657900-2e3d-11ea-9727-cb80c0272999.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
目前在互動抽獎同個帳號出現兩次以上已不會有上述情況發生，中獎名單的「來源」和「社群ID」皆正常顯示。
![image](https://user-images.githubusercontent.com/49626114/71790507-d1efa980-306b-11ea-9ab2-2742dbe04597.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
目前在互動抽獎同個帳號抽獎兩次以上，中獎名單的「來源」和「社群ID」皆正常顯示。
![image](https://user-images.githubusercontent.com/41721950/71960502-29d70d80-3230-11ea-9075-194b31aafdfe.png)
![image](https://user-images.githubusercontent.com/41721950/71960704-9f42de00-3230-11ea-9044-4788157f7409.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
