### ISSUE TITLE
【MongoDB】未開啟兌獎的銘謝惠顧獎項卻出現在互動後台的中獎名單中

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1804]
銘謝惠顧未開啟兌獎(黃框處)
![image](https://user-images.githubusercontent.com/49626114/71570539-9a837900-2b10-11ea-9dd7-b3628daea90e.png)
但是銘謝惠顧的獎項卻出現在互動後台的中獎名單中(紅框處)
![image](https://user-images.githubusercontent.com/49626114/71570611-1bdb0b80-2b11-11ea-8ca2-c5e4389042ed.png)

**Comment by cocosu123** [comment]
在互動後台的中獎名單和下載的檔案中僅會顯示有開啟兌獎的獎項，未開啟兌獎的銘謝惠顧獎項已不會出現。
![image](https://user-images.githubusercontent.com/49626114/71712988-aa69c880-2e42-11ea-9adf-bafc80e28074.png)
◎◎ 20200103確認以上測試環境內容in MongoDB◎◎

**Comment by cocosu123** [comment]
在互動後台的中獎名單和下載的檔案中僅會顯示有開啟兌獎的獎項，未開啟兌獎的銘謝惠顧獎項已不會出現。
![image](https://user-images.githubusercontent.com/49626114/71789850-593b1e00-3068-11ea-9d24-397a3a32b488.png)
◎◎ 20200106確認以上正式環境內容◎◎

**Comment by AnitaRyzo** [comment]
未開啟『兌獎』的銘謝惠顧獎項已不會出現。
![image](https://user-images.githubusercontent.com/41721950/71957921-e7aacd80-3229-11ea-9654-1726f17d24b3.png)
◎◎ 20200108確認以上測試環境內容MS SQL◎◎
