### ISSUE TITLE
【地圖有Bug】地圖設定的模式有蟲

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#183]
模式設定有蟲
<img width="1097" alt="2018-05-16 4 49 00" src="https://user-images.githubusercontent.com/37163894/40106806-53394c38-5929-11e8-9915-1bf45fc4447b.png">

**Comment by ryuichl** [comment]
看不懂
麻煩多點解釋
感恩

**Comment by liucwlewis** [comment]
我錯了，是不能選樣式

**Comment by Isabella-RYZO** [comment]
👌
