### ISSUE TITLE
【頁籤】右側選取樣式後，畫布沒有同步

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#184]
樣式選擇後，元件沒有同步變化
<img width="1047" alt="2018-05-16 5 01 19" src="https://user-images.githubusercontent.com/37163894/40107452-d607132e-592a-11e8-81cf-5e64ca25d6d5.png">

**Comment by ryuichl** [comment]
他有變化 只是顏色沒變你看不出來
#95

**Comment by ryzojudy** [comment]
我們錯了
