### ISSUE TITLE
【問題】文字框的定位點容易跳位

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#185]
<img width="433" alt="2018-05-16 5 24 31" src="https://user-images.githubusercontent.com/34876672/40108647-1da0cc36-592e-11e8-9ed7-072c61f7b816.png">
<img width="311" alt="2018-05-16 5 24 44" src="https://user-images.githubusercontent.com/34876672/40108648-1dca975a-592e-11e8-8796-728b03123f50.png">

此處點擊標題文字框容易跳位子
而且發佈之後跑版

**Comment by Isabella-Zheng** [comment]
本機測試已解決(reset css),待上線。
