### ISSUE TITLE
【問題】裝置&瀏覽器的相容性測試

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#187]
對 PC 及 Mobile 進行相容性測試

測試使用的專案:
https://sample-1.ryzoweba.io
https://sample-2.ryzoweba.io
https://sample-3.ryzoweba.io
https://sp4.ryzoweba.io
https://sp5.ryzoweba.io
https://mama.ryzoweba.io
https://summerevent.ryzoweba.io
https://lottery.ryzoweba.io

測試標的:
-------------------------------------------
PC Lenovo T470p - Windows 10 Home
Chrome 66
Firefox 60
IE 11
Opera 53
Edge 42
-------------------------------------------
Mac Pro - macOS Sierra 10.12.5
Safari 10.1.1
-------------------------------------------
IPhone 6s - IOS 11.3.1
Chrome 57
Firefox 11.1
Safari 11.3.1
Opera 16.0.9
FB Browser 171
LINE Browser  8.6.1
-------------------------------------------
Android 7
Chrome 66
Firefox 60
Opera 46
FB Browser 172
LINE Browser 8.6.1
Native Browser
-------------------------------------------

異常:
PC - IE 11 - 五個專案開啟之後都是畫面全黑
PC - Edge 42 - sample1 - 文字、按鈕與轉盤的樣式跑版
PC - Edge 42 - sample2 - 文字、轉盤部分樣式跑版
PC - Edge 42 - sample4 - 選單、轉盤部分樣式跑版，序號產生器的按鈕變成透明的(但可以觸發)
景遮罩消失
PC - Firefox 60 - sample5 - 文字跑版
IOS 11.3.1 - Opera 16 - sample 1&2&4 - 轉盤或序號產生器在登入驗證的時候會卡住, 無法驗證
Android 7 - FB & Line - sample1 - 文字、按鈕與轉盤的樣式跑版
Android 7 - FB & Line - sample2 -  文字、轉盤部分樣式跑版
Android 7 - FB & Line - sample4 -  選單、轉盤部分樣式跑版，序號產生器的按鈕變成透明的(但可以觸發)

Sample 5 - 
1.會出現 文字顏色異常、原本單行的文字被斷行，Popup 背景透明且文字顏色異常，按鈕邊框消失。
2. 在 IOS 或 MacOS 的 Safari 上 有個區塊輪播內的文字 "彩虹唇膏筆 1+1"(顏色為 hex 7374baff) 無法顯示(IPhone 或 PC 則可以顯示)，但另外有個問題是這段文字在原專案於編輯器內為單行文字，但複製過的專案則編輯器內會自動斷成兩行，而且實際在 IPhone 或 PC 上 顯示也是斷行後的文字。

另外，由於 Sample 3 裡面有用到特殊字元(\uf87f)，情況比較特殊，似乎僅在 Android 的 Firefox 內顯示為▮。
而在 IOS 上不顯示，在 PC 及 Android 的其他瀏覽器則是顯示為 或是⊠，WEBA 編輯器內則是顯示。
>>>
WEBA: 
PC: 
IOS: 不顯示
Android Firefox:  ▮
Android 其他: ⊠
>>>
Sample 3 補充: 
另外開了一個[專案](https://uf87f.ryzoweba.io)來測試這個特殊字元，發現只是不同裝置的瀏覽器對這個字元的顯示不同，應該不算是 BUG。

**Comment by Kyle30** [comment]
補充圖片:
PC - Edge 42 - sample1 - 文字、按鈕與轉盤的樣式跑版
![edge0](https://user-images.githubusercontent.com/11918396/40151897-1764a0a4-59b5-11e8-8fde-eede0f60a3c3.png)
![edge1](https://user-images.githubusercontent.com/11918396/40151898-1792d17c-59b5-11e8-9b5a-df8d90d181d1.png)
![edge2](https://user-images.githubusercontent.com/11918396/40151899-17bad3e8-59b5-11e8-9363-9fefc1f18a8d.png)
![edge3](https://user-images.githubusercontent.com/11918396/40151900-17ea33b8-59b5-11e8-81e8-5e76ed808cd5.png)
![edge4](https://user-images.githubusercontent.com/11918396/40151901-181388f8-59b5-11e8-8dd6-7761ca709a25.png)
![edge5](https://user-images.githubusercontent.com/11918396/40151902-183ce2b6-59b5-11e8-947d-a813d914de17.png)
![edge6](https://user-images.githubusercontent.com/11918396/40151903-1864d1ae-59b5-11e8-8bc3-dbc2ccf9cb2e.png)

**Comment by Kyle30** [comment]
補充圖片:
PC - Edge 42 - sample2 - 文字、轉盤部分樣式跑版
左邊: Edge 右邊: Chrome
![edge-sp2-0](https://user-images.githubusercontent.com/11918396/40152064-2b8c6dea-59b6-11e8-84d8-d6535ea4c8d6.png)
![edge-sp2-1](https://user-images.githubusercontent.com/11918396/40152065-2bb9fb66-59b6-11e8-9f57-fc6ee2126de6.png)
![edge-sp2-2](https://user-images.githubusercontent.com/11918396/40152066-2be4670c-59b6-11e8-82ff-ba60e0a38f9d.png)

**Comment by Kyle30** [comment]
補充圖片:
PC - Edge 42 - sample4 - 選單、轉盤部分樣式跑版，序號產生器的按鈕變成透明的(但可以觸發)
左邊: Edge 右邊: Chrome
![edge-sp4-0](https://user-images.githubusercontent.com/11918396/40152209-e0b1db56-59b6-11e8-86ef-2dcacda7716c.png)

**Comment by Kyle30** [comment]
補充圖片:
PC - IE 11 - 四個專案開啟之後都是畫面全黑
![ie11-sp1](https://user-images.githubusercontent.com/11918396/40152468-ef387d1e-59b7-11e8-98dc-4d530c984cbf.png)
![ie11-sp2](https://user-images.githubusercontent.com/11918396/40152469-ef66089c-59b7-11e8-83ec-545f90a37df3.png)
![ie11-sp3](https://user-images.githubusercontent.com/11918396/40152470-ef8e98de-59b7-11e8-9ef5-4e257b3f8e54.png)
![ie11-sp4](https://user-images.githubusercontent.com/11918396/40152471-efb8c2a8-59b7-11e8-8cb2-59c959e194bc.png)

**Comment by Gabe-Liu** [comment]
在strict模式中不可有屬性的多個定義 - 已修正
顏色部分，IE11不支援hex的8位表示法 #000000**00**， 預計全部更改為rgba呈現

**Comment by Kyle30** [comment]
補充圖片:
Sample 3 特殊字元
![weba-sp3](https://user-images.githubusercontent.com/11918396/40155267-4cf74176-59c5-11e8-8824-1843129ea270.png)
![pc-sp3](https://user-images.githubusercontent.com/11918396/40155268-4d1e4b72-59c5-11e8-8ee6-e91246a94df8.png)
![android-fb-sp3](https://user-images.githubusercontent.com/11918396/40155269-4d4d787a-59c5-11e8-8910-a05297a0ba70.jpg)
![android-line-sp3](https://user-images.githubusercontent.com/11918396/40155270-4d77d5fc-59c5-11e8-949f-75ab6a0af31c.jpg)
![android-chrome-sp3](https://user-images.githubusercontent.com/11918396/40155271-4da15dbe-59c5-11e8-9a24-0b3d2d7c3faf.jpg)
![iphone-firefox-sp3](https://user-images.githubusercontent.com/11918396/40155272-4dce295c-59c5-11e8-85e9-168657974322.jpg)
![android-firefox-sp3](https://user-images.githubusercontent.com/11918396/40155273-4df9bb08-59c5-11e8-91b9-46a894049379.jpg)

**Comment by Kyle30** [comment]
補充圖片:
Android 7 - FB & Line - sample1 - 文字、按鈕與轉盤的樣式跑版
![android-fb-sp1-1](https://user-images.githubusercontent.com/11918396/40155685-bb543ce4-59c7-11e8-9332-8b0ef3dc1c56.jpg)
![android-fb-sp1-2](https://user-images.githubusercontent.com/11918396/40155686-bb7dead0-59c7-11e8-9fc3-a01c75e44942.jpg)
![android-fb-sp1-3](https://user-images.githubusercontent.com/11918396/40155687-bba56cae-59c7-11e8-9858-a809a6a7150f.jpg)
![android-fb-sp1-4](https://user-images.githubusercontent.com/11918396/40155688-bbcf0aaa-59c7-11e8-992d-74a0631a2da5.jpg)
![android-fb-sp1-5](https://user-images.githubusercontent.com/11918396/40155690-bbfcd7e6-59c7-11e8-8217-a9463699e2db.jpg)
![android-fb-sp1-6](https://user-images.githubusercontent.com/11918396/40155691-bc2555ea-59c7-11e8-9e6d-efaaf55064eb.jpg)
![android-fb-sp1-7](https://user-images.githubusercontent.com/11918396/40155692-bc4ed1c2-59c7-11e8-9b6c-24192b22707a.jpg)
![android-line-sp1-1](https://user-images.githubusercontent.com/11918396/40155693-bc7886ac-59c7-11e8-9e3b-461121f82018.jpg)
![android-line-sp1-2](https://user-images.githubusercontent.com/11918396/40155694-bca30300-59c7-11e8-89a1-23d80d2da9c2.jpg)
![android-line-sp1-3](https://user-images.githubusercontent.com/11918396/40155695-bcc9bd7e-59c7-11e8-91ff-86f3016c5f3e.jpg)
![android-line-sp1-4](https://user-images.githubusercontent.com/11918396/40155696-bd159e74-59c7-11e8-912c-914b617067af.jpg)
![android-line-sp1-5](https://user-images.githubusercontent.com/11918396/40155697-bd40ada8-59c7-11e8-8b78-1f228605c237.jpg)
![android-line-sp1-6](https://user-images.githubusercontent.com/11918396/40155698-bd6aaef0-59c7-11e8-8f7a-6d769eb3a5f8.jpg)
![android-line-sp1-7](https://user-images.githubusercontent.com/11918396/40155699-bd932c90-59c7-11e8-9a95-ecc6850089a4.jpg)

**Comment by Kyle30** [comment]
補充圖片:
Android 7 - FB & Line - sample2 - 文字、轉盤部分樣式跑版
![android-fb-sp2-1](https://user-images.githubusercontent.com/11918396/40155745-f259f648-59c7-11e8-9a92-446f7643b564.jpg)
![android-fb-sp2-2](https://user-images.githubusercontent.com/11918396/40155747-f433a86a-59c7-11e8-9158-5093d6f69ecf.jpg)
![android-line-sp2-3](https://user-images.githubusercontent.com/11918396/40155749-f6726e9a-59c7-11e8-96b8-53c5aa897ad6.jpg)
![android-line-sp2-1](https://user-images.githubusercontent.com/11918396/40155769-0e83d2c6-59c8-11e8-940f-78cdc4efb959.jpg)
![android-line-sp2-2](https://user-images.githubusercontent.com/11918396/40155772-100db8f0-59c8-11e8-9685-4242c3aae170.jpg)
![android-line-sp2-3](https://user-images.githubusercontent.com/11918396/40155774-11153944-59c8-11e8-998e-fccb7c42e589.jpg)

**Comment by Kyle30** [comment]
補充圖片:
Android 7 - FB & Line - sample4 - 選單、轉盤部分樣式跑版，序號產生器的按鈕變成透明的(但可以觸發)
![android-fb-sp4](https://user-images.githubusercontent.com/11918396/40155821-4a542a30-59c8-11e8-84c7-3f00d89ecce4.jpg)
![android-line-sp4](https://user-images.githubusercontent.com/11918396/40155822-4b466336-59c8-11e8-9a36-8b5c2cbacc9f.jpg)

**Comment by Kyle30** [comment]
https://mama.ryzoweba.io 專案
在 IOS 上無法正常顯示
如圖
![iphone-safari-mama](https://user-images.githubusercontent.com/11918396/40290527-0c5002aa-5cf1-11e8-9ef9-c358bc3366cd.jpg)

**Comment by Kyle30** [comment]
https://lottery.ryzoweba.io/ 專案內
點擊按鈕 "立即加入" ( 嵌入的連結為: https://ec.nanshangeneral.com.tw/eCommerce/travel/regForm.jsp )
在多數的瀏覽器中會有 【重新導向次數過多】問題
![pc-edge-lottery-join-1](https://user-images.githubusercontent.com/11918396/40399446-0b82bc16-5e70-11e8-94b3-cc8585e67cc9.png)
![pc-edge-lottery-join-2](https://user-images.githubusercontent.com/11918396/40399447-0bb38a80-5e70-11e8-8fc8-837d463cb27b.png)
![pc-edge-lottery-join-3](https://user-images.githubusercontent.com/11918396/40399448-0bdb8616-5e70-11e8-94b7-7af90077a833.png)

**Comment by Kyle30** [comment]
https://lottery.ryzoweba.io/ 專案內
![default](https://user-images.githubusercontent.com/11918396/40407116-f0a9b126-5e95-11e8-9477-76c97db1560f.png)
這段文字區塊在
PC: Edge、IE 
IOS: 全部瀏覽器

僅會在"向右滑動"的動畫過程中顯示，當動畫完成後就消失了

**Comment by Kyle30** [comment]
https://subscribewow.ryzoweba.io 專案內
在 PC 上 使用 IE 11 填寫轉盤串接表單的資料時，畫面會跑版
**題目的編號會跟題目重疊**
![form](https://user-images.githubusercontent.com/11918396/40412006-adad9fa4-5ea4-11e8-89af-15079792f9ad.png)

**Comment by Gabe-Liu** [comment]
問題："重新導向次數過多"  暫無法重新呈現問題
問題："動畫消失" 修正
問題： "題目的編號會跟題目重疊" 修正

**Comment by Gabe-Liu** [comment]
在MAC上的文字寬度問題，還在繼續尋找解決辦法
