### ISSUE TITLE
【帳單版面編輯】廣告活動元件的輪播切換箭頭在預覽頁未顯示

### ISSUE THREAD

**Issue by cocosu123** [ryuichl/v3-report#1872]
廣告活動元件有設定輪播的切換箭頭(黃框處)，但預覽時沒有顯示出來(紅框處)。
![image](https://user-images.githubusercontent.com/49626114/72230953-a2084f00-35f3-11ea-89b2-194816813368.png)

**Comment by Gabe-Liu** [comment]
有存在著，只是因為是白色箭頭樣式，剛好又沒圖片或背景為白色，所以才看不出來

**Comment by cocosu123** [comment]
輪播的切換箭頭(黃框處)，在預覽時有顯示出來。
![image](https://user-images.githubusercontent.com/49626114/72400062-f42baa80-3782-11ea-8dae-de06406b6a33.png)
◎◎ 20200115確認以上測試環境內容MS SQL◎◎
