### ISSUE TITLE
【建議】表單題目之間的行距可以有「更小」的選擇

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#189]
目前的表單題目和選項可以設定行距
共有1~4共7個級距
但是最小的1行距還是滿大的
希望未來可以有「更小」的選擇
（0.1 0.5之類的）

感恩～

**Comment by ryuichl** [comment]
之後填ISSUE時希望可以加個圖
感恩

**Comment by wilmaftliu** [comment]
<img width="333" alt="2018-05-17 10 14 49" src="https://user-images.githubusercontent.com/34560641/40153195-27d45a28-59bb-11e8-9919-4a5d85774f4e.png">

**Comment by ryuichl** [comment]
你預期達到的效果
有其他已有的網站範例嗎?
@wilmaftliu

**Comment by ai015606220** [comment]
@wilmaftliu 你可能誤會行距了

這是行距1
![image 1](https://user-images.githubusercontent.com/10190722/40154939-bc82e286-59c3-11e8-820a-3128d5ddbf4d.jpg)

這是行距0.5
![image 2](https://user-images.githubusercontent.com/10190722/40154956-cc66d55e-59c3-11e8-85a0-8efcbd8d9ea6.jpg)

這是行距0.1
![image 3](https://user-images.githubusercontent.com/10190722/40154957-d070fa12-59c3-11e8-88bc-ad1c2a2e5fbd.jpg)

**Comment by wilmaftliu** [comment]
市面上的範例（題目之間的間距相對較近） 供參考
<img width="495" alt="2018-05-17 11 30 12" src="https://user-images.githubusercontent.com/34560641/40155335-c159a900-59c5-11e8-8c3f-99df74a5a474.png">

**Comment by wilmaftliu** [comment]
我們的題目目前最多一頁只能出現三題
題與題之間間距相對較寬
<img width="320" alt="2018-05-17 11 36 05" src="https://user-images.githubusercontent.com/34560641/40155491-9edd7428-59c6-11e8-82ea-6c109bd3b221.png">

**Comment by wilmaftliu** [comment]
補上花旗範例網址 https://www.citibank.com.tw/credit-cards/application/index.html?CardType=2&Media=319&icid=TWCCUTKZHMAINHTAB

**Comment by liucwlewis** [comment]
在頁面設定中的“頁面模式”與“進度條樣式”之間插入“題目間距”的設定，間距以像素為單位
![artboard](https://user-images.githubusercontent.com/37163894/42306856-299ab126-8063-11e8-974a-aa85084aeada.jpg)

**Comment by wilmaftliu** [comment]
請問這個後來有更新了嗎？
貌似最近一次的更新好像還沒有這個功能
希望知道目前進度 感恩

**Comment by eatinggg** [comment]
https://zpl.io/aw1OMNd

**Comment by AnitaYang2018** [comment]
“題目間距”的設定，以px為單位
![image](https://user-images.githubusercontent.com/41557924/45073481-11be1e00-b112-11e8-93b5-a5f8338152cc.png)
◎◎ 20180905確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/45477653-9c3af900-b774-11e8-829d-e5369971576d.png)
◎◎ 20180913確認以上測試環境內容 ◎◎
