### ISSUE TITLE
表單標題的對齊

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#190]
表單標題改變對齊方式的時候好像沒效果?
不確定是不是BUG

![image](https://user-images.githubusercontent.com/10150807/40152910-d2540cb6-59b9-11e8-9c44-902faa023a9a.png)

**Comment by ai015606220** [comment]
這邊我本來是使用text-align做排版，但後來改用flex所以對齊需要調整一下

**Comment by Isabella-RYZO** [comment]
👌
