### ISSUE TITLE
【帳單版面編輯】資料綁定的第一大類帶入的資料不完整

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#1901]
以下元件皆可串聯『資料綁定』的資料
![image](https://user-images.githubusercontent.com/41721950/72590215-30ecd280-3938-11ea-8551-8e7f15a2e14a.png)
預設的測試資料有九大類，但元件目前只帶入前四大類，似乎不足
![image](https://user-images.githubusercontent.com/41721950/72590317-62fe3480-3938-11ea-9692-4439ed917626.png)
備註：等大類皆顯示後，要研究第二大類以後的資料該如何選擇
以上問題請協助處理，感恩

**Comment by louis-lintingyou** [comment]
目前產品設計，資料綁定無法綁定陣列

**Comment by AnitaRyzo** [comment]
未來再測試圖片影片的資料綁定功能
