### ISSUE TITLE
【建議】幸運轉盤獎項新增的位置

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#191]
1.建議第一個獎項的位置可以固定在指針下方(現在是在3點鐘位置)

2.希望之後新增的獎項也可以有編號提示 例：獎品5,獎品6...
在設定多獎項獎品的時候會比較方便

謝謝～

![1526523079350](https://user-images.githubusercontent.com/34293268/40153187-13cfd796-59bb-11e8-8b73-a0b5094744a8.jpg)

**Comment by Samasianspock** [comment]
#483 同樣的建議
