### ISSUE TITLE
（急）【文字預設】預設標準字體，字體大小16px，不加粗，間距調寬一點

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#193]
點擊文字元件時，預設的字體太粗，希望預設標準字體字體大小16px，行距調整為1.5、字距為1、不加粗。

2018-05-17 教學回饋修正建議
https://docs.google.com/document/d/1eKI53Yk-_1UgcdvE332JR1xw9S4zP9uVIl5q5fysCnY/edit?usp=sharing

**Comment by liucwlewis** [comment]
希望預設標準字體字體大小16px，行距調整為1.5、字距為1、不加粗。

**Comment by ryuichl** [comment]
寬一點是指多少?

**Comment by liucwlewis** [comment]
行距調整為1.5、字距為1
