### ISSUE TITLE
 （急）【團隊管理】退出團隊按鈕在選取成員的狀態時應該要消失

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#194]
”退出團隊“按鈕在選取成員的狀態時應該要消失，不然使用者會以為所選取到的成員可以點擊”退出團隊“就被踢出。
![1526537480489](https://user-images.githubusercontent.com/37163894/40159529-4ec41968-59dc-11e8-99a0-816acca69458.jpg)

**Comment by ryuichl** [comment]
這操作感覺很怪
我覺得按鈕換個地方放是否好一點?
