### ISSUE TITLE
（急）【收縮區塊】無法直覺辨識是否能展開

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#195]
橘框位置應該放上圖示（箭頭、加號），讓使用者知道那個區塊可以被展開。
希望右側控制欄有開關可以切換展開、收合的狀態。
![1526537711233](https://user-images.githubusercontent.com/37163894/40159815-7d22acc4-59dd-11e8-8613-c9e025f0a29b.jpg)

**Comment by Gabe-Liu** [comment]
提供 箭頭、加號 圖示給使用者選擇
至於右側開關先暫時
