### ISSUE TITLE
（中）【選單架構】頁面時的名稱應該與頁面管理區的名稱一致

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#197]
橘框文字應該一致
![1526538697735](https://user-images.githubusercontent.com/37163894/40160195-11ab6d3a-59df-11e8-9f82-7c602b25f560.jpg)

**Comment by ryuichl** [comment]
#159

**Comment by ryuichl** [comment]
重複了 這個先關掉
