### ISSUE TITLE
（中）【圖片上傳優化】圖片上傳時，希望能有loading畫面

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#198]
同事說，有時候不知道圖片有沒有在上傳，都一片黑黑的，想要有loading畫面
橘框範圍
![1526538884481](https://user-images.githubusercontent.com/37163894/40160286-79005a7c-59df-11e8-910f-7bccee3eb733.jpg)

**Comment by ryzojudy** [comment]
畫布中的圖片位置會有loading動畫
不知這樣是否已經足夠了?
![image](https://user-images.githubusercontent.com/34263719/40636350-317bfc50-6331-11e8-9139-a11b76241db7.png)

**Comment by ryuichl** [comment]
背景圖上傳目前確實是沒有LOADING畫面

**Comment by Isabella-RYZO** [comment]
修改 圖片上傳時，右側圖片上傳欄出現 loading, 待上傳。
