### ISSUE TITLE
頁面編輯回主頁時的快捷鍵

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#20]
如果可以按左上角的LOGO回dashboard比按左下角HOME鍵更直覺

第一次使用時 一直狂按左上角回不去dashboard 找了2、3個人嘗試都以為是應該要按ＬＯＧＯ 
雖然後來在左下角找到了房子回dashboard 
但是相信大家被各種平台或網站教育下 直覺會覺得回到主頁應該要往左上角尋找更自然

供參考

**Comment by ryuichl** [comment]
已改
