### ISSUE TITLE
（中）【長頁面設定簡化】開啟長頁面時，直接僅出現高度數值

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#200]
開啟長頁面時，直接僅出現高度數值（在調整高度時，數值須同步呈現變化，比較有在調整的感覺）。開啟長頁面狀態時，畫布下方固定有延長按鈕
橘框內的資訊刪掉
![1526539333236](https://user-images.githubusercontent.com/37163894/40160526-824b7638-59e0-11e8-8a14-0b7e8c381268.jpg)

**Comment by Gabe-Liu** [comment]
待下次更新
