### ISSUE TITLE
（中）【轉盤元件優化】獎項輸入時，有提示文字告知兩個空白鍵是換行功能

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#201]
橘框位置，看是否加個備註在獎項名稱的後方
![1526539736326](https://user-images.githubusercontent.com/37163894/40160883-9afaf266-59e1-11e8-9b55-7c9cb8ae1f2c.jpg)

**Comment by ryzojudy** [comment]
麻煩出圖 @liucwlewis
