### ISSUE TITLE
（中）【轉盤元件優化】抽獎紀錄的圖示沒有fu

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#202]
等有空會找更直覺的圖示替換
![1526539993024](https://user-images.githubusercontent.com/37163894/40161102-487e343e-59e2-11e8-845c-afa38488ef1a.jpg)

**Comment by ryuichl** [comment]
我是覺得你只放圖不管誰都不會知道的

**Comment by weilyn** [comment]
![2018-05-18 9 44 22](https://user-images.githubusercontent.com/34327325/40211961-193b208a-5a80-11e8-9813-ca7de3f094df.png)

history的圖示建議
文字部分你們斟酌

**Comment by wilmaftliu** [comment]
或是可以直接用按鈕加上文字來處理？
![6a033e08720f49caa69152ec01b3ac01](https://user-images.githubusercontent.com/34560641/40212608-63da0144-5a83-11e8-8a0d-dddc48b92c96.jpg)

**Comment by ryuichl** [comment]
![image](https://user-images.githubusercontent.com/10150807/40212660-9f6c5dec-5a83-11e8-951a-9975952eeb01.png)
