### ISSUE TITLE
（中）【表單題目編輯】表單題目編輯，必須要按完成鈕才能編輯其他題目

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#206]
目前為可同時編輯多題。希望調整成，一題完成時必須按下完成才可編輯下一題
![1526541725445](https://user-images.githubusercontent.com/37163894/40162281-1491837a-59e6-11e8-9a35-02fd3987bcdb.jpg)

**Comment by ryuichl** [comment]
你在按別題的時候如果沒反應不會很怪嗎?
還是會出現甚麼提示?

**Comment by liucwlewis** [comment]
尚未點擊完成時，點其他的範圍會跳出這種提示框 
黃框內的文字改成“請先完成目前的題目設定”
<img width="721" alt="2018-05-17 3 34 55" src="https://user-images.githubusercontent.com/37163894/40162906-e4b875bc-59e7-11e8-97fb-54805a7ee646.png">

**Comment by Samasianspock** [comment]
目前希望編輯題目時必需要要點選“完成”鈕才可編輯其他題目，雖然同時編輯多題很方便，但為了避免使用者疏漏某些題目沒按”完成“，先限制一定要點選”完成“才可編輯其他題目，點選其他題目時跳出 @liucwlewis 提供的提示。
如果使用者沒有按完成就按”確認“和叉叉要直接關閉表單設計，跳出以下提示窗提醒使用者。
<img width="307" alt="2018-07-05 2 17 54" src="https://user-images.githubusercontent.com/37531593/42305952-c03d49da-805f-11e8-8ba8-e2b2364d1c20.png">
