### ISSUE TITLE
（中）【動畫設定優化】希望能針對全部的動畫進行循環

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#208]
希望兩個以上的動畫還是可以設定循環（全部的動畫）
![2018-05-17 3 40 59](https://user-images.githubusercontent.com/37163894/40163207-c895f462-59e8-11e8-91d3-cde576e4e90c.png)

**Comment by ryuichl** [comment]
#173

**Comment by AnitaRyzo** [comment]
單一元件可以在『動畫設定』開啟【動畫循環】，元件將依照動畫順序與效果執行循環
![image](https://user-images.githubusercontent.com/41721950/47007397-b6e50100-d16a-11e8-8cd7-51742dac72ba.png)
前提是動畫次數不能設定為『無限』
![image](https://user-images.githubusercontent.com/41721950/47007428-c6fce080-d16a-11e8-8d8a-31b48eda620c.png)
◎◎ 20181016確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
單一元件可以在『動畫設定』開啟【動畫循環】，元件將依照動畫順序與效果執行循環
![image](https://user-images.githubusercontent.com/41721950/47275495-9392d980-d5e2-11e8-882a-af0d18220de9.png)
◎◎ 20181016確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
單一元件可以在『動畫設定』開啟【動畫循環】，元件將依照動畫順序與效果執行循環
![image](https://user-images.githubusercontent.com/41721950/47275537-cd63e000-d5e2-11e8-9d27-a0116fa49a2d.png)
◎◎ 20181022確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
單一元件可以在『動畫設定』開啟【動畫循環】，元件將依照動畫順序與效果執行循環
![image](https://user-images.githubusercontent.com/41721950/47275633-8c200000-d5e3-11e8-9a6e-d3671aa9578c.png)
◎◎ 20181022確認以上正式環境內容 ◎◎
