### ISSUE TITLE
圖片拖拉時的外框

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#21]
目前的圖片是不論如何縮放 大小會改變 但是比例是不變的
如果是這樣的話 希望可以拿掉外框 直接用圖片本身的邊線當作外框就可以了
因為預設的外框（疑似是16:9的比例）
如果圖片是橫向 比例相近時 不會有感覺 

但如果圖片是直立式的 感覺多出來的外框就很明顯（參考下圖）
<img width="440" alt="2018-03-22 4 27 09" src="https://user-images.githubusercontent.com/34560641/37759280-17f40264-2dee-11e8-864f-42224b46bdf8.png">

在選擇其他元件時 
也會因為那張圖的外框太多而選到不該選的圖
（像是下面這張圖 因為直式的圖外框很大 導致選不到旁邊那張小黑圖）
<img width="489" alt="2018-03-22 4 28 32" src="https://user-images.githubusercontent.com/34560641/37759304-2b525bc6-2dee-11e8-8397-ca70619013fd.png">

不只是外觀問題 也可能影響使用者操作 建議外框能貼合圖片～～

**Comment by ryuichl** [comment]
暫不改善
