### ISSUE TITLE
（未來）【發佈設定優化】有太多細節要設定，希望能有更大的畫面呈現

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#212]
橘框為現在狀態，之後應該可調整為點擊“發佈設定”時，右側的設定欄會展開到綠色的框線範圍，將設定的資訊清楚排列、一目瞭然
![1526545273759](https://user-images.githubusercontent.com/37163894/40165467-a1acd9a0-59ee-11e8-9022-429b5d4cbd03.jpg)

**Comment by ai015606220** [comment]
那之後也需要請設計提供展開後的排版 @liucwlewis

**Comment by liucwlewis** [comment]
連結：https://zpl.io/2GQdB09
![default](https://user-images.githubusercontent.com/37163894/42255034-4b275f02-7f7c-11e8-9d16-91ba89e27de9.jpg)
