### ISSUE TITLE
（急）【選單優化】矩陣式選單預設的樣子有點像bug

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#217]
希望預設的間距能大一點
![2018-05-17 5 35 36](https://user-images.githubusercontent.com/37163894/40169513-bf252712-59f8-11e8-9c5f-bc59ab928ba4.png)

**Comment by ryzojudy** [comment]
矩陣式的預設希望改成
1. 置左對齊
2. 下間距為10px

根據老路轉述Gabe知道
