### ISSUE TITLE
【建議】文字元件可以選取部分範圍更改顏色

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#219]
建議文字元件可以選取部分範圍更改顏色 部分更改為粗體等等..
在應用上會更方便～～
如下圖～
謝謝

<img width="317" alt="2018-05-18 8 59 54" src="https://user-images.githubusercontent.com/34293268/40210841-e82d2f34-5a79-11e8-818f-15ea18423176.png">

**Comment by ryuichl** [comment]
這不可能做到
先關掉
