### ISSUE TITLE
(未來)【團隊管理】同階層可互看專案的權限

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#223]
新增一個可看同階層專案的權限
有利於未來協做時的操作

**Comment by ryuichl** [comment]
怎樣的協作?
@ryzojudy

**Comment by ryzojudy** [comment]
回覆：
不是跟協作有關係 比較像是資源流通的感覺
若在規模較小的公司 可能階層本身就沒有那麼明確
想要知道同階層的人有甚麼專案可以用(看有甚麼資源可使用)
有的話就就可以複製利用等

但這個還是等真的有企業提了再說

**Comment by ryuichl** [comment]
設定上就是不能看同階層的專案
不想分享給別人的概念
規模較小更不用考慮了
也不是目前的目標
