### ISSUE TITLE
【問題】矩陣式問題的選項跟回答對不上

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#224]
as title
![default](https://user-images.githubusercontent.com/11918396/40212708-f0359d60-5a83-11e8-9724-2515b0ab44b4.png)
![default](https://user-images.githubusercontent.com/11918396/40212710-f3f51b06-5a83-11e8-89a8-5ab53999e59c.png)

**Comment by ryuichl** [comment]
answer : {row-0: "直2", row-1: "直1", row-2: "直3"}

這裡的key會直接修正為行1.2.3嗎?
我下載那邊也要改一下
@ai015606220

**Comment by ai015606220** [comment]
不會耶，因為這個key不方便改
我是會多一個rowsList的欄位去做對照

**Comment by ryuichl** [comment]
恩 知道了 
我到時候再改吧

**Comment by Isabella-RYZO** [comment]
👌
