### ISSUE TITLE
【問題】表單回覆通知的日期欄位格式

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#225]
as title
![default](https://user-images.githubusercontent.com/11918396/40212923-47d68812-5a85-11e8-8e9e-ad7003926da0.png)
![2](https://user-images.githubusercontent.com/11918396/40212924-481ef142-5a85-11e8-97d6-cec401ee2d54.png)

**Comment by ryuichl** [comment]
已修正待上線
