### ISSUE TITLE
【轉盤】在打獎項名稱時 轉盤突然破裂?

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#226]
![image](https://user-images.githubusercontent.com/34263719/40213225-edf9328e-5a86-11e8-9dc7-542fd9177bc9.png)

**Comment by ryuichl** [comment]
有辦法重現嗎?

**Comment by ryzojudy** [comment]
我試試看

**Comment by ryzojudy** [comment]
無法

**Comment by ryuichl** [comment]
無法的話晚一點就先關掉囉
不然的話我們也測不出來

**Comment by ryzojudy** [comment]
恩恩 好喔 那 我就也不管繼續做下去囉?

**Comment by ryuichl** [comment]
@Gabe-Liu 
你看一下
不知道問題的話就把他關掉

**Comment by Gabe-Liu** [comment]
看起來應該是上傳的圖檔有問題，導致的破版
