### ISSUE TITLE
【問題】複製專案內的序號產生器異常

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#229]
某專案內有序號產生器,在複製該專案後, 重新啟用序號產生器並設定好表單且產出序號後
在使用時, 還是會出現"序號已取完"的狀況
![default](https://user-images.githubusercontent.com/11918396/40214019-223a0344-5a8b-11e8-8ed3-e8113f736da8.png)
![2](https://user-images.githubusercontent.com/11918396/40214020-242595e2-5a8b-11e8-91da-f99b7ce5f650.png)

**Comment by Kyle30** [comment]
每次開啟複製的專案, 序號機設定會呈現像是未產出序號的狀態
![4](https://user-images.githubusercontent.com/11918396/40214649-7e96de34-5a8e-11e8-88ec-cd3a45261660.png)
就算重新按下產出序號並儲存
![5](https://user-images.githubusercontent.com/11918396/40214677-b42ad028-5a8e-11e8-9c9b-2d5e9b83b156.png)
序號部分也還會是空的
![3](https://user-images.githubusercontent.com/11918396/40214681-b8ba1aea-5a8e-11e8-9995-7da9cac6f81f.png)

**Comment by ryzojudy** [comment]
補充
第一次編輯複製專案時 序號產生器無法產出序號 只可查看
第二次以後就如上述一樣 不管第幾次設計 都可以再重新產出序號

第一次
![image](https://user-images.githubusercontent.com/34263719/40214835-94544b20-5a8f-11e8-8e48-85733e13c15e.png)

第二次以後
![image](https://user-images.githubusercontent.com/34263719/40214866-bcfb6202-5a8f-11e8-99c5-de44a218dd83.png)

**Comment by ryzojudy** [comment]
在被複製的帳號中查看序號表單回覆
會出現原始帳號中的回覆
![image](https://user-images.githubusercontent.com/34263719/40214929-376c9ee8-5a90-11e8-987c-a9a62578bb39.png)

**Comment by Gabe-Liu** [comment]
看下次更新時有無修正

**Comment by Isabella-RYZO** [comment]
目前測試一切正常
