### ISSUE TITLE
【套版審核】套版審核的專案截圖都跑不出來

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#232]
![image](https://user-images.githubusercontent.com/34263719/40214420-2d27b9ac-5a8d-11e8-96d9-df758c0789c0.png)

**Comment by ryzojudy** [comment]
套版管理的截突也是

**Comment by ryuichl** [comment]
套版的截圖路徑需要修正
const src = `./f2e/src/assets/gcs/${req.user._id}/${req.body.site_id}`
const dest = `./f2e/src/assets/gcs/template/${template._id}`

**Comment by Isabella-RYZO** [comment]
👌
