### ISSUE TITLE
【問題】專案管理頁面重新載入會卡住

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#237]
as title
從不同頁面切換至專案管理頁面的時候，專案管理頁面都能正常載入。
但若是"已經"在專案管理頁，但又去點擊"專案管理頁面" ICON 的時候，會重新載入畫面但一直卡在 Loading 。
![site_loading](https://user-images.githubusercontent.com/11918396/40215838-986fd7aa-5a95-11e8-803d-d311a6736ade.png)

順帶一問，當我透過 https://ryzoweba.io/client/dashboard/site 進入專案管理頁面時。
Console 會出現以下錯誤
![site_error](https://user-images.githubusercontent.com/11918396/40215924-1847bbb4-5a96-11e8-93c4-94ad389e59f6.png)

跟權限內的 "site_publish" 有關聯嗎??
![authority](https://user-images.githubusercontent.com/11918396/40215968-494d99cc-5a96-11e8-8a41-0e57598ed92e.png)

**Comment by Gabe-Liu** [comment]
loading問題 - 我已修正
site_publish -  derek已修正

**Comment by Isabella-RYZO** [comment]
👌
