### ISSUE TITLE
【問題】框架圖層

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#238]
hi
A物件本來設定是在B框架物件以上

但預覽時就被框架物件B擋住了

**Comment by weilyn** [comment]
![2018-05-18 12 26 33](https://user-images.githubusercontent.com/34327325/40216054-bec67e26-5a96-11e8-9b6a-bc0592be0afe.png)
![2018-05-18 12 26 38](https://user-images.githubusercontent.com/34327325/40216055-beedb46e-5a96-11e8-9a09-c6d55a6b715e.png)


右上角zhuan dong dezhuan dong de h轉動的花

**Comment by Gabe-Liu** [comment]
@weilyn 是在你帳號下的專案嗎?

**Comment by Isabella-RYZO** [comment]
👌
