### ISSUE TITLE
新增動態的箭頭

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#242]
新增動態效果的箭頭好像長得怪怪的
(但還是可以點！)
如下圖～
謝謝～～

<img width="289" alt="2018-05-18 1 54 34" src="https://user-images.githubusercontent.com/34293268/40218261-151179aa-5aa3-11e8-96ce-3d914e837a50.png">

**Comment by ai015606220** [comment]
reset中缺少 -webkit-appearance: none;

**Comment by Isabella-RYZO** [comment]
👌
