### ISSUE TITLE
【建議】下拉選項圖示

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#243]
hi，
目前介面裡有下拉式的選項都會有兩種icon重疊出現

如圖
但事實上是不行點上下選調整參數的，只能從下拉選項中選擇

![2018-05-18 1 52 45](https://user-images.githubusercontent.com/34327325/40218222-ed858048-5aa2-11e8-9560-2f4f0b4e78b7.png)

**Comment by ryuichl** [comment]
#242
