### ISSUE TITLE
【問題】表單中的按鈕 後面墊了一塊東西？

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#245]
<img width="788" alt="2018-05-18 2 29 29" src="https://user-images.githubusercontent.com/34560641/40219447-fb5c06e2-5aa7-11e8-9e12-125e2103aabc.png">
如圖所示 
表單中的按鈕背後有個背後靈
旋轉後那塊墊背還是在原處
設定完邊框圓角後 背後靈還是方形的
煩請除靈 感謝～

<img width="780" alt="2018-05-18 2 31 19" src="https://user-images.githubusercontent.com/34560641/40219486-2b4567b8-5aa8-11e8-8f1e-3653246fbcf9.png">

**Comment by ryuichl** [comment]
#231
