### ISSUE TITLE
發佈項目

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#25]
發佈項目(時程等)
一樣可以在編輯區域可以設定
與發佈後台處的項目設定同步

**Comment by Gabe-Liu** [comment]
把structrue的內容拆到外面  
SEO
project-publish-setting

**Comment by Gabe-Liu** [comment]
如果拆到外面也必須要像是 structure 與 structure_prod 分成兩個狀態，並沒有比較方便，因此就保持原狀！
