### ISSUE TITLE
【優化】跨帳號表單查看回覆

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#256]
這個好像有一點跑板
正常應該是靠左邊一點 不會有這麼大的距離
![image](https://user-images.githubusercontent.com/34263719/40222085-ecfa3d7c-5ab0-11e8-883a-cc53e030b414.png)

另外因為不會下載勾選的回覆(一次就是下載全部)
所以希望也可以把勾選拿掉
不然就是需要能只下載勾選到的回覆

**Comment by ryuichl** [comment]
勾選是用在批量刪除

**Comment by ryzojudy** [comment]
不能刪除其他帳號表單的回覆啊?
這是在跨帳號查看其他人的表單回覆
