### ISSUE TITLE
【套版管理】新增主題，成功添加主題，但主題管理列表沒有顯示這個主題的標籤。

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#262]
**操作步驟：** 套版管理頁面，按下新增主題，輸入主題名稱，點選添加標籤，按下完成。
**結果：** 成功添加該主題，但主題標籤預覽沒有出現所屬標籤，開發者模式有以下錯誤。
> 例圖
![-](https://user-images.githubusercontent.com/20262208/40224280-4286ad32-5ab8-11e8-85d8-3c89050edab2.png)

**Comment by ai015606220** [comment]
我目前測試都是正常的，可能需要更多的測試資訊

**Comment by ryuichl** [comment]
我這邊測的情況是點新增主題選了標籤
按確定後
去點選剛新增的主題
下方的標籤會顯示灰色的 裡面沒有字
跑去別頁再回來就正常了
