### ISSUE TITLE
【套版管理】主題新增標籤後，加入新標籤，刪除新標籤，標籤列沒有該標籤了，但主題還有該標籤

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#264]
**操作步驟：** 在主題管理新增標籤，添加新增的'你看看你'標籤後，加入該主題，到標籤管理刪除'你看看你'標籤後，到剛剛的主題看，標籤列沒有'你看看你'標籤，但是主題標籤列還是有'你看看你'標籤

**疑問：** 被刪除後的標籤還會出現在主題裡面嗎???若是這樣，該主題也無法刪除或編輯'你看看你'標籤

按下重新整理後，被刪除的 '你看看你'標籤 不會出現在該主題裡了。
常理：應該當下就是刪除後的狀態。
> 例圖
![default](https://user-images.githubusercontent.com/20262208/40224957-55bbc606-5aba-11e8-9b14-5bdf470cb2da.png)

**Comment by ryuichl** [comment]
測了一下應該是前端資料沒更新

**Comment by Isabella-RYZO** [comment]
👌
