### ISSUE TITLE
【套版管理】管理套版，無法修改專案資料

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#267]
**操作步驟：** 套版管理頁面，按下專案的齒輪，修改套版名稱，按下完成。
**結果：** 沒有修改專案名稱，不曉得是什麼樣的格式錯誤。

> 例圖

![default](https://user-images.githubusercontent.com/20262208/40226947-b996c2ca-5abf-11e8-95be-4d6bef5bfa25.png)

**Comment by ryuichl** [comment]
我測試是可以正常改
不過原來版面上的名稱是要重整後才會更新就是

**Comment by Isabella-RYZO** [comment]
👌
