### ISSUE TITLE
【發布】設定完域名後出現「原本設定」？

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#269]
<img width="322" alt="2018-05-18 2 20 28" src="https://user-images.githubusercontent.com/34560641/40229120-ed56b4c0-5ac5-11e8-9c7e-cd7fb29e27ae.png">

剛輸入完域名後會出現綠色的字「可以使用」

但如果輸入完會出現「原本設定」
感覺是要作為和下一次設定時作區別
不過感覺好像沒有必要？ 還是可以改成其他比較好懂的用語？（個人建議可以刪掉「可以設定」）
供參考

**Comment by ryzojudy** [comment]
剛測試了一下
目前的狀況為
(第一次發佈)
顯示的字串為【可以使用】、【格式錯誤】、【域名已被使用】

(二次發布)
顯示的字串為【可以使用】、【格式錯誤】、【域名已被使用】、【原本設定】

不知道是否有解決問題?

**Comment by ryuichl** [comment]
先關掉
有新意見再打開
