### ISSUE TITLE
【問題】選擇頁籤裡的文字

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#270]
hi，我在頁面上有眾多文字放在頁籤裡，當我點選其中一個頁籤裡的文字時，其他文字都會一起被選擇到，但樣式不會跟著連動。

一起被選取到可能會讓人產生誤會
![2018-05-21 9 35 10](https://user-images.githubusercontent.com/34327325/40286669-197ab2ba-5cdb-11e8-87a7-0d74f3ff1f70.png)

**Comment by Gabe-Liu** [comment]
@weilyn  如果此專案之後要繼續使用，待下次更新時，需要把這些頁籤重新製作一次

**Comment by Isabella-RYZO** [comment]
👌
