### ISSUE TITLE
【問題】轉盤獎品圖片

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#273]
HI 轉盤獎品圖片在不知名情況會跑出自己的格子

![2018-05-21 9 37 53](https://user-images.githubusercontent.com/34327325/40286975-ff5dc5c8-5cdc-11e8-9a26-fa4c90ede843.png)

**Comment by Gabe-Liu** [comment]
後面的獎項的名稱與圖片，如果過長會覆蓋到上一個的，因此最後一個獎項(Nope ~ 嘴)會覆蓋到前一個與第一個。
