### ISSUE TITLE
【問題】套版分類區塊捲軸

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#275]
套版區塊捲軸卡住,無法看到完整內容
![1234](https://user-images.githubusercontent.com/34327325/40288843-d6898640-5ce7-11e8-92cd-c95d7eb6c812.PNG)

**Comment by ai015606220** [comment]
你的沒有出現滾軸嗎??

**Comment by ai015606220** [comment]
有空的時候方便我去看看你的畫面嗎

**Comment by Isabella-RYZO** [comment]
👌
