### ISSUE TITLE
【編輯區優化】編輯區域邊界線優化

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#280]
<img width="1433" alt="2018-05-21 15 10 00" src="https://user-images.githubusercontent.com/34700112/40294689-3bbda200-5d09-11e8-8589-8cee05eee1ed.png">
在編輯時，若是想把圖片填滿畫布區塊，有時會遮住邊界線，僅有在預覽時候能知道有沒有出血跑版，較不利於編輯時的排版。

**Comment by ryzojudy** [comment]
@liucwlewis

**Comment by liucwlewis** [comment]
當元件超過畫布範圍時，超出的範圍上方有一層深灰色的遮罩
<img width="941" alt="2018-06-01 2 07 03" src="https://user-images.githubusercontent.com/37163894/40824028-145eaf16-65a5-11e8-962d-9ef73fa6f91a.png">
