### ISSUE TITLE
bug!將元件固定成框架未套用至其他分頁

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#282]
<img width="1439" alt="2018-05-22 11 29 56" src="https://user-images.githubusercontent.com/34700112/40340792-ab8644fc-5db3-11e8-8449-32c1e9f06b9a.png">

<img width="1435" alt="2018-05-22 11 29 19" src="https://user-images.githubusercontent.com/34700112/40340793-abb00c92-5db3-11e8-9ee9-734e9b627bea.png">

<img width="384" alt="2018-05-22 11 30 11" src="https://user-images.githubusercontent.com/34700112/40340791-ab5d55d8-5db3-11e8-94ae-333e406ed19e.png">

如圖所示，最上面的LOGO區塊已設定成「框架」，卻無法顯示！
有時也會出現某元件有連動，另一個卻未有效果的情形發生！

**Comment by Gabe-Liu** [comment]
待下次更新前請先暫時停用框架

**Comment by Isabella-RYZO** [comment]
目前測試尚未發生此情況
