### ISSUE TITLE
【問題】頁面管理文字輸入

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#283]
hi
頁面管理區域，新增頁面要修改名稱時

發現無法連續輸入文字（拼音輸入法無法連續輸入，注音尚未測試）

**Comment by weilyn** [comment]
![2018-05-22 11 46 45](https://user-images.githubusercontent.com/34327325/40341179-34a25e18-5db6-11e8-9e5e-486e2528eb5c.png)

**Comment by wilmaftliu** [comment]
注音輸入法目前沒發現類似問題
<img width="273" alt="2018-06-07 2 34 00" src="https://user-images.githubusercontent.com/34560641/41082132-d736109c-6a5f-11e8-8777-db04238ae108.png">
