### ISSUE TITLE
【選單背景設定】選單設定為柵欄時，選單背景設定應該要消失

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#284]
選單為柵欄狀態時無法使用背景。所以在柵欄狀態時，要關閉背景設定的功能
![2018-05-22 11 54 02](https://user-images.githubusercontent.com/37163894/40341491-1d2cba56-5db8-11e8-847a-bb839df209be.png)

**Comment by Gabe-Liu** [comment]
待下次更新
