### ISSUE TITLE
【問題】圖片蓋在選單之上

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#285]
不知名原因，發生編輯過程中 圖片蓋在選單之上

但是預覽模式時正常顯示
![2018-05-22 12 13 49](https://user-images.githubusercontent.com/34327325/40341807-c457286a-5db9-11e8-9c2e-08b8d6e57f7f.png)

**Comment by ryuichl** [comment]
現在情況還在嗎?

**Comment by weilyn** [comment]
對 專案還開著

**Comment by Isabella-RYZO** [comment]
👌
