### ISSUE TITLE
[建議] 提示的離開方式

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#287]
目前離開提示製作的方式是在點一次喇叭
建議可以在右側加一個離開編輯模式
這樣會不會比較直覺?
![image](https://user-images.githubusercontent.com/10150807/40341915-5987c110-5dba-11e8-9e3d-dc18d5375116.png)

**Comment by ryzojudy** [comment]
麻煩出圖 @liucwlewis

**Comment by liucwlewis** [comment]
提示模式時，右側控制欄也會有“離開提示模式”的按鈕
<img width="1040" alt="2018-06-01 2 04 16" src="https://user-images.githubusercontent.com/37163894/40823908-b6343afa-65a4-11e8-8df1-80b478b9c4eb.png">
