### ISSUE TITLE
【問題】動畫進場效果

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#289]
HI
目前動畫進場效果是 先呈現出來，再開始進行動畫
 例如我設定光速進場，延遲0.8秒，他會在畫面停留0.8秒以後消失，然後才開始光速進場

這樣似乎有失進場動畫的本質，想了解是否規定是這樣，還是有可以調整之處

**Comment by ryuichl** [comment]
我自己試是他剛開始不會在畫面中
然後才光速進場耶

**Comment by weilyn** [comment]
哈囉哈囉 請問你那邊測試是正式發布環境嗎 還是預覽的狀態

**Comment by ryuichl** [comment]
我全試了都正常

**Comment by weilyn** [comment]
![2018-05-22 4 48 48](https://user-images.githubusercontent.com/34327325/40351885-0abfeece-5de0-11e8-892b-fb14ada10a16.png)
 可參閱此專案網址>申辦網址>5.完成

[https://childeduinsurance.ryzoweba.io/](https://childeduinsurance.ryzoweba.io/)

**Comment by Gabe-Liu** [comment]
目前發現是在幫群組添加動畫時，初始隱藏失效

**Comment by Isabella-RYZO** [comment]
👌
