### ISSUE TITLE
【建議】轉盤(或序號產生器)在尚未連結表單資料時的狀態提示

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#292]
當使用轉盤(或序號產生器)而未設定表單時
在瀏覽器上按下"填寫資料"則會出現這樣的畫面
![edge](https://user-images.githubusercontent.com/11918396/40401003-24537404-5e77-11e8-9bb6-02a8735c6e75.png)
![firefox](https://user-images.githubusercontent.com/11918396/40401004-247fb096-5e77-11e8-8316-468b7eb1db0e.png)
使用者可能沒有辦法很容易的聯想到，這是因為轉盤(或序號產生器)沒有設定表單資料而產生的問題。

**建議可以補上其他警告提示，或顯示出完整的"尚未建立表單"畫面。**
![weba](https://user-images.githubusercontent.com/11918396/40401116-98a608b2-5e77-11e8-9d87-291307ee44ca.png)

**Comment by ryzojudy** [comment]
已優化
