### ISSUE TITLE
【建議】按鈕關閉開啟連結後不要出現手的圖示

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#295]
<img width="373" alt="2018-05-23 14 02 46" src="https://user-images.githubusercontent.com/34700112/40406124-043ee6c4-5e92-11e8-9cb9-dcf1686b8e6e.png">

![s__7372811](https://user-images.githubusercontent.com/34700112/40406099-e83c7e78-5e91-11e8-8a40-02f55eb160dc.jpg)

如圖，按鈕關閉開啟連結後不要出現手的圖示

**Comment by ryuichl** [comment]
建議改用裝飾區塊
