### ISSUE TITLE
【內嵌程式碼bug】實際手機顯示與畫布狀態不同

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#304]
畫布畫面
<img width="638" alt="2018-05-24 11 35 10" src="https://user-images.githubusercontent.com/37163894/40463218-91c4529a-5f46-11e8-8645-984d46f14534.png">

實際畫面
![img_4884](https://user-images.githubusercontent.com/37163894/40463199-68fd8890-5f46-11e8-86a6-af72d117c0df.PNG)

**Comment by Isabella-Zheng** [comment]
【非 BUG】內嵌程式碼本身是一個iframe  然後 這個專案嵌入的也是個iframe (寬高是固定的)，所以如果你版你自己嵌入的iframe 寬高 都 100% 就可以符合了

**Comment by Isabella-RYZO** [comment]
👌
