### ISSUE TITLE
【套版管理】套版管理無法刪除無用的套版，希望能在完成鍵旁加一個刪除套版

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#306]
圖片支援
<img width="503" alt="2018-05-24 11 53 13" src="https://user-images.githubusercontent.com/37163894/40463673-1f56d446-5f49-11e8-9f37-c0eadae85e7e.png">

**Comment by ryuichl** [comment]
之前已經有做好刪除的API
你們看誰在把他補上去
@Gabe-Liu @ai015606220 
感恩

**Comment by ai015606220** [comment]
已完成, 等待上線
