### ISSUE TITLE
【排序】提示不能排序

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#308]
如題
目前提示新增後不能排序
<img width="236" alt="2018-05-24 12 11 53" src="https://user-images.githubusercontent.com/34560641/40464098-af1f8e68-5f4b-11e8-8ec2-a912a26383da.png">

希望之後新增完的提示可以在最下方 同時可以排序
<img width="312" alt="2018-05-24 12 11 45" src="https://user-images.githubusercontent.com/34560641/40464103-b36412e6-5f4b-11e8-9e97-57df7ad68846.png">

感恩

**Comment by ryzojudy** [comment]
麻煩出圖 @liucwlewis

**Comment by liucwlewis** [comment]
麻煩在每個提示選項前方加上移動的icon
<img width="945" alt="2018-06-01 1 55 45" src="https://user-images.githubusercontent.com/37163894/40823659-b4a7ca18-65a3-11e8-9b77-01de37974b70.png">
