### ISSUE TITLE
【帳號管理】icon更新了！！

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#310]
嗨～～
應觀眾要求～帳號管理的icon更新了！！
如下圖
<img width="289" alt="2018-05-24 4 53 19" src="https://user-images.githubusercontent.com/34293268/40475005-02ae13b6-5f73-11e8-8882-076ae08d2387.png">

路徑如下：
第三版icon > 01 dashboard > 00左側吧 > 02 帳號管理 

再請有權限的人幫我關掉issue#178～謝謝：）

**Comment by ai015606220** [comment]
#178
