### ISSUE TITLE
【問題】圖片選取框位置跑掉

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#314]
我是用分隔線所以會很細
然後他的選取框框就位移了（如圖）
而且會點選不太到 ヾ(;ﾟ;Д;ﾟ;)ﾉﾞ

<img width="263" alt="2018-05-25 10 32 07" src="https://user-images.githubusercontent.com/34876672/40523295-898b5076-6007-11e8-9ed6-04f1d0fb3590.png">
<img width="664" alt="2018-05-25 10 28 44" src="https://user-images.githubusercontent.com/34876672/40523297-8a7b793e-6007-11e8-9863-edc7dd297ddf.png">
<img width="238" alt="2018-05-25 10 28 24" src="https://user-images.githubusercontent.com/34876672/40523299-8b552314-6007-11e8-8691-404b08cfc6cd.png">

**Comment by ai015606220** [comment]
目前圖片很細的話會有這個問題
還在嘗試解決中
如果有這種需求建議先使用裝飾區塊的矩形

**Comment by ryzojessie** [comment]
好ㄛ ｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡

**Comment by Isabella-RYZO** [comment]
👌
