### ISSUE TITLE
【建議】選取的元件調整大小

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#315]
hi
頁面上有相互重疊的圖層

主要是我想要修改被壓在下層的裝飾圖示的尺寸
並且我已經點選到他了, 但是由於他的下緣被其他張圖片擋住,所以我無法選到他下緣的控制點

是不是能讓我優先編輯選取中的元件呢
![default](https://user-images.githubusercontent.com/34327325/40525562-5ea82b84-6013-11e8-8ac7-62ddad83e969.PNG)

**Comment by Samasianspock** [comment]
目前有兩種建議的做法：
一是將上層的元件隱藏，二是將上層的元件上鎖，就不會影響下方元件的操作。

需要麻煩工程優化的部分是，下方元件的控制鈕應該要出現，而不會被蓋住，雖然Weilyn的例子上方圖片元件是透明背景，但如果上方元件是不透明的，則下方選取到的元件控制點還是要顯示，方便操作，感謝！
(可以參考Illustrator的方式，如下圖)

<img width="552" alt="2018-06-28 9 49 38" src="https://user-images.githubusercontent.com/37531593/42008576-de802f90-7ab8-11e8-84b4-4ac312eddec6.png">
![img_3448](https://user-images.githubusercontent.com/37531593/42008578-e0e5ce98-7ab8-11e8-9575-e4e1514ca4c1.JPG)

**Comment by Gabe-Liu** [comment]
之後會修改為，被點選的元件浮在最上層

**Comment by weilyn** [comment]
hi，目前修改後的樣式已經相當不錯了，
不過這邊還是提供對照表供未來要更優化時做參考
主要是最下方兩種狀態，變成半透明可以讓圖層的先後順序更加明瞭
詳細請見附圖

![2018-07-10 3 10 31](https://user-images.githubusercontent.com/34327325/42494765-c6d50ab0-8453-11e8-9e51-e843a855e5d7.png)
以上抄襲自wix

**Comment by weilyn** [comment]
簡單來說，就是拖曳、縮放大小時再讓他附在最上層，並同時賦予半透明（90%之類的）的狀態。
而單純點選到的時候則不會浮現在最上方，也不會變半透明

如此就不會讓圖層的部分因為浮現在最上層的關係而不易調整
