### ISSUE TITLE
裝飾圖案小建議

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#316]
<img width="1436" alt="2018-05-25 15 04 33" src="https://user-images.githubusercontent.com/34700112/40530897-0972882a-602d-11e8-8fa9-072572e4ec9e.png">

1.調整至最小的高度還是很高，無法拿來作分隔線使用。
2.導圓角的圓無法調整，調整高度後，圓會變形不方便使用。

**Comment by ryuichl** [comment]
目前你可以用輸入數值的方式變更小

**Comment by ryuichl** [comment]
第2個的話目前無法做到

**Comment by brendatseng** [comment]
好歐感謝
