### ISSUE TITLE
【問題】元件刪除與回復步驟

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#318]
HI
剛剛在專案裡藉由右下角圖層的地方刪除元件

然後發現

不能回上一步

OMG

**Comment by Gabe-Liu** [comment]
目前發現在MAC上，刪除元件時不會觸發儲存上步驟，待下次更新

**Comment by Gabe-Liu** [comment]
需一台閒置的MAC，邊改修邊測試

**Comment by AnitaRyzo** [comment]
在MAC上，利用『圖層設定』或『Delete鍵』刪除元件時，皆觸發儲存上一步
◎◎ 20180910確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
在MAC上，利用『圖層設定』或『Delete鍵』刪除元件時，皆觸發儲存上一步
◎◎ 20180917確認以上測試環境內容 ◎◎
