### ISSUE TITLE
【問題】裝飾區塊切換電腦版時沒有跟著縮放

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#319]
裝飾區塊切換電腦版時沒有跟著縮放
第一張是手機版預覽圖 對照 第2.3張電腦版截圖

<img width="447" alt="2018-05-28 9 37 59" src="https://user-images.githubusercontent.com/34876672/40593433-23898102-625b-11e8-9162-5d098de45993.png">
<img width="1440" alt="2018-05-28 9 38 10" src="https://user-images.githubusercontent.com/34876672/40593434-23b5f868-625b-11e8-99a4-7b5bb9417e8b.png">
<img width="1440" alt="2018-05-28 9 38 15" src="https://user-images.githubusercontent.com/34876672/40593435-23de19f6-625b-11e8-9a45-6753d1a75d61.png">

**Comment by Isabella-Zheng** [comment]
已修正

**Comment by ryzojessie** [comment]
剛剛重新發佈過 但還是一樣ㄟ
（在你修正後發布ㄉ，在無痕視窗或safari都是一樣ㄉ狀況）

<img width="1440" alt="2018-05-28 9 52 38" src="https://user-images.githubusercontent.com/34876672/40593720-ee57f4ee-625c-11e8-8be7-b5ce6bac1fde.png">
<img width="1440" alt="2018-05-28 9 52 45" src="https://user-images.githubusercontent.com/34876672/40593721-ee83132c-625c-11e8-8bde-6cab084563c4.png">

**Comment by Isabella-Zheng** [comment]
抱歉 ~待上傳更新後功能才會回復正常。 XD

**Comment by Isabella-RYZO** [comment]
👌
