### ISSUE TITLE
【問題】關閉發布

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#322]
Hi
想要將已經發布的專案關閉發布

發現從 專案發佈>發布中>關閉專案icon>關閉發布

點擊之後專案好像沒有真的被關閉

又或是其實在其他途徑裡，再麻煩協助解答

![2018-05-28 12 23 06](https://user-images.githubusercontent.com/34327325/40597108-e7184f02-6271-11e8-919f-4e61c0f7f671.png)

**Comment by ryuichl** [comment]
網站網址多少?

**Comment by weilyn** [comment]
https://mama.ryzoweba.io/

但其實附圖一整排發布中的點擊關閉都沒反應

**Comment by ryuichl** [comment]
![image](https://user-images.githubusercontent.com/10150807/40597262-f139e328-6272-11e8-91e2-db1c6d94a901.png)

待修正

**Comment by Isabella-RYZO** [comment]
👌
