### ISSUE TITLE
【建議】「套版管理」中燈號辨別

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#323]
目前套版管理中分兩種燈號
無燈號：關閉的套版
綠燈：通過審核未發佈＋通過審核已發佈
（已與Judy確認過燈號類型）

希望可以增加一種燈號 方便辨識該專案是否有發布在線上，建議如下：
黃燈：通過審核未發佈
綠燈：通過審核已發佈

以方便套版管理者辨別狀態與管理套版，感恩

**Comment by liucwlewis** [comment]
套版的狀態分為三種，如圖：
<img width="851" alt="2018-06-01 12 09 05" src="https://user-images.githubusercontent.com/37163894/40820709-b13d5cb2-6594-11e8-9948-f1777ed0e15e.png">

**Comment by ai015606220** [comment]
已完成, 待日後上線
