### ISSUE TITLE
【問題】發佈設定與儲存

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#324]
HI
剛剛在專案裡做了編修後，在發佈設定輸入summer,並儲存+申請審核

發現點選發布以後沒有任何反饋，除此之外也沒有真的申請審核，

重新進入專案以後發現剛剛做的編修都遺失了

目前發現只有使用summer這個域名才會出現，
不知是否因為域名已經被使用過，但系統偵測都是顯示可以使用

**Comment by ryuichl** [comment]
已修正
