### ISSUE TITLE
【問題】專案管理區顯示

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#325]
專案管理區：
將未申請審核的專案>複製之後
發現新複製出來的專案會被直接標示為審核不通過。

![2018-05-28 3 54 57](https://user-images.githubusercontent.com/34327325/40603886-d8b41dc4-628f-11e8-9196-7afc06c84a99.png)

**Comment by ryuichl** [comment]
@Gabe-Liu @ai015606220 
這邊紅燈怎麼判斷的阿?

**Comment by ai015606220** [comment]
(project.apply_at < project.verify_at) && !project.verify

**Comment by ryuichl** [comment]
已修正
新複製的不會有這狀況
