### ISSUE TITLE
【建議】柵欄選單文字對齊

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#327]
使用柵欄式選單
當插入的圖片尺寸規格不同時 文字會高高低低
建議優先以文字整齊為標準

例如 上圖下文的時候向下對齊

上文下圖的時候向上對齊

![2018-05-28 4 45 18](https://user-images.githubusercontent.com/34327325/40606081-d30d8d36-6296-11e8-8b08-5d584fb4555f.png)

**Comment by Gabe-Liu** [comment]
建議上傳同尺寸圖片

**Comment by weilyn** [comment]
我們這邊可以上傳同尺寸的圖片 可是客戶使用時就不一定了

或是你們限制個比例之類的，因為目前上傳icon的部分也不能裁切比例，比較難抓準尺寸

但這個也不急啦

**Comment by liucwlewis** [comment]
連結：https://zpl.io/agv0XMQ
目前解決辦法僅能提供剪裁功能
<img width="766" alt="2018-07-06 3 22 09" src="https://user-images.githubusercontent.com/37163894/42365196-5ec36f6e-8130-11e8-86c9-188a3b07e5b3.png">

**Comment by Gabe-Liu** [comment]
添加裁切功能  提供使用者將圖示調整為同樣比例
