### ISSUE TITLE
【手機預覽】無法顯示預覽畫面

### ISSUE THREAD

**Issue by Isabella-RYZO** [ryuichl/v3-report#329]
> 操作步驟：
1. 選擇套版進入編輯
2. 沒有變更任何東西，直接按下儲存
3. 按預覽使用預覽連結(掃qrcode)

> 結果：

PC/手機，皆無法看到預覽畫面

**Comment by Gabe-Liu** [comment]
要先執行刷新時間

**Comment by Isabella-RYZO** [comment]
已刷新時間但是依舊無法觀看(log：預覽已結束)。

**Comment by ryuichl** [comment]
已修正
