### ISSUE TITLE
【表單管理】標單明細很多項(很多題目)，只能透過調整欄位寬度才能往後看到後面欄位的資訊

### ISSUE THREAD

**Issue by Isabella-RYZO** [ryuichl/v3-report#332]
上方資訊面板展開時，
表單明細過長，是否有左右滾動可以直接滾動到後面欄位觀看?
目前只能透過調整欄位寬度才能顯示後面欄位的資料。

![0530](https://user-images.githubusercontent.com/39641812/40702372-24051532-6414-11e8-85b7-58610ef61640.png)

**Comment by ryzojudy** [comment]
剛剛確認過
下方有拖拉霸
![image](https://user-images.githubusercontent.com/34263719/40818812-99197afc-658b-11e8-8efc-b4646b972032.png)

**Comment by ryuichl** [comment]
螢幕小的時候
或是前面凍結項目太多的時候
拖拉條會超小 很難使用

**Comment by Isabella-RYZO** [comment]
我這邊真的不能滾動左右~
還是說設計本來就是~~~~"""上方資訊面板展開時"""無法滾動左右。

**Comment by ryzojudy** [comment]
可以自己設定凍結項目嗎??

**Comment by ryuichl** [comment]
當初有設計成要凍結嗎?

**Comment by ryzojudy** [comment]
沒有設計凍結
但有希望可以隱藏欄位

**Comment by ryuichl** [comment]
可以把凍結去掉嗎?
@ai015606220

**Comment by ai015606220** [comment]
把凍結去掉是什麼??

**Comment by ai015606220** [comment]
已修正，待日後上線
