### ISSUE TITLE
【建議】社群追蹤與社群分享希望可以改成置中排列

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#336]
目前”社群追蹤“與”社群分享“新增至畫布上時是置左排列，
希望可以改成置中排列，方便做圖上的對齊與排版。
<img width="491" alt="2018-05-30 4 03 52" src="https://user-images.githubusercontent.com/37531593/40707412-33cadbbe-6423-11e8-83ce-95228b5af46c.png">

**Comment by Isabella-RYZO** [comment]
@Samasianspock 
倘若社群圖示2排的情況下也會置中，這樣可以嗎?
![default](https://user-images.githubusercontent.com/39641812/40762193-5211e0f4-64d2-11e8-9fb6-a546b2aede51.png)

**Comment by Samasianspock** [comment]
@Isabella-RYZO 我覺得這樣至少會比較方便，使用者可以自行決定是否再加入第二組元件去編排第二排的社群．

**Comment by Isabella-RYZO** [comment]
待上線
