### ISSUE TITLE
測試環境的url（電腦）點進去沒東西，（手機）掃碼QR觀看也沒東西！

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#338]
<img width="1436" alt="2018-05-31 14 12 39" src="https://user-images.githubusercontent.com/34700112/40764769-d8c3daa8-64dc-11e8-8a84-61ed3070ebed.png">

<img width="1440" alt="2018-05-31 14 14 13" src="https://user-images.githubusercontent.com/34700112/40764818-eba17a72-64dc-11e8-9835-0be7dd48e1aa.png">

測試環境的url（電腦）點進去沒東西，（手機）掃碼QR觀看也沒東西！

**Comment by ryuichl** [comment]
#329

**Comment by ryuichl** [comment]
已修正
