### ISSUE TITLE
Bug! 區塊輪播內的按鈕無法點擊

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#339]
<img width="1436" alt="2018-05-31 14 12 39" src="https://user-images.githubusercontent.com/34700112/40764867-10159e6a-64dd-11e8-9dc9-4b86adfbd89b.png">

區塊輪播內的按鈕【了解詳情】無法點擊

**Comment by ryuichl** [comment]
你是指預覽時按鈕沒反應?

**Comment by brendatseng** [comment]
對的 有設連結到頁面

**Comment by Gabe-Liu** [comment]
下方的圖層剛好蓋在按鈕上，要調整~
