### ISSUE TITLE
動畫問題

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#340]
<img width="800" alt="2018-05-31 14 58 48" src="https://user-images.githubusercontent.com/34700112/40766805-45b465e6-64e3-11e8-87f3-49f5b6f211d5.png">
<img width="865" alt="2018-05-31 14 58 53" src="https://user-images.githubusercontent.com/34700112/40766808-47390dcc-64e3-11e8-99d6-73763bbba41c.png">

如上圖，將區塊輪播內的區塊1、區塊2、區塊3設置不同的動畫，
但動畫出現的方式是畫面出來動畫就會出現了，
假若區塊輪播輪播到區塊二要再出現動畫時，
就需要設置動畫的【延遲時間】這部分是可以調整的嗎？
輪播到該區域再啟動該區塊的動畫～

**Comment by ryuichl** [comment]
暫時無法達成
未來不排除支援

**Comment by AnitaRyzo** [comment]
區塊輪播內的區塊1、區塊2、區塊3設置不同的動畫
待使用者切換區塊時，動畫才開始運作
◎◎ 20181015確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
區塊輪播內的區塊1、區塊2、區塊3設置不同的動畫
待使用者切換區塊時，動畫才開始運作
◎◎ 20181022確認以上正式環境內容 ◎◎
