### ISSUE TITLE
【問題】連結錨點

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#341]
使用圖片或按鈕連結錨點時，
選擇分頁的地方會重複出現頁面

這個專案只有兩個頁面

![2018-05-31 4 53 04](https://user-images.githubusercontent.com/34327325/40772857-b79aa3ae-64f3-11e8-8f7a-e66641188d83.png)

**Comment by Gabe-Liu** [comment]
應該已解決~
