### ISSUE TITLE
切換團隊的時候 畫面會重新LOAD

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#343]
![image](https://user-images.githubusercontent.com/10150807/40819610-8ef3a996-658e-11e8-9e51-765a3840ca8c.png)

如果切換團隊 畫面會跑回個人帳號

**Comment by ai015606220** [comment]
這個不算是bug, 
是因為目前我把權限的計算都放在最上層, 
所以才設計讓它切換團隊的時候會讓頁面資料刷新, 
如果覺得不妥會再思考如何修改

**Comment by ryuichl** [comment]
你再看看吧
理論上是要留在同一頁

**Comment by Gabe-Liu** [comment]
待下次更新
