### ISSUE TITLE
【問題】運行速度及小建議

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#344]
因為最近WEBA的運行速度不是很順暢，
像是設定表單的時候，要展開進階設定、開啟框線 這一類的都有明顯的停頓感
想確認是否因為網路問題，或是有其他可能性

此外目前右側的控制選項使用了大量的隱藏進階設定的元素，可能造成使用者操作上不便利

還想確認下方灰色的文字區域是否沒有開放設定顏色
![2018-06-01 11 25 49](https://user-images.githubusercontent.com/34327325/40819996-791cecca-6590-11e8-8514-eca5d27c172d.png)

**Comment by ai015606220** [comment]
速度方面應該有恢復正常,請你們再確認看看
這個文字顏色目前沒有辦法設定
