### ISSUE TITLE
[建議] 群組移動方式

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#345]
希望群組與群組內移動方式可以跟ppt一樣

感恩

**Comment by Samasianspock** [comment]
以下幾個針對群組的選取與移動的動作建議 

選取：點擊一次選取到群組，雙擊兩次才可選取到內部元件。
移動：點擊一次選取到整個群組，可移動整個群組。

＃目前的設定是點擊一次就能選到群組內的元件，要移動群組的話要點擊空隙處，因此有些小積木，特別是有堆疊元件的、元件設計的非常接近的積木 (如下圖)，會很難選取或不能用游標移動整個群組，以上建議，感謝。

<img width="200" alt="default" src="https://user-images.githubusercontent.com/37531593/42300862-021311ac-8045-11e8-9d2e-fd3a99732e0a.png">
