### ISSUE TITLE
社群分享和追蹤某些樣式會失效

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#347]
社群分享和追蹤選到某些樣式會怪怪的
圖示會消失

![image](https://user-images.githubusercontent.com/10150807/40837234-5fb72444-65cc-11e8-8514-fe9a5f8e370a.png)

**Comment by Isabella-RYZO** [comment]
總共11種樣式，目前我這邊看都沒問題。
請問是哪一個樣式會不見。感謝~

> 以下例圖

![0604](https://user-images.githubusercontent.com/39641812/40894078-94f241c0-67d9-11e8-9885-833e51a878d0.png)

**Comment by Isabella-RYZO** [comment]
目前修改：
1. 修正 右側 圖示樣式 選擇，部分圖式樣式無法呈現問題。
2. 移除 最少顯示 1 個社群 限制，同時調整 編輯區社群呈現 及 下拉選單 最小高度 css。 
3. 右側 下拉選擇社群樣式 滑鼠移入 css 調整。

待上線更新
