### ISSUE TITLE
[建議] 查看發佈中專案的 QRCODE

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#351]
目前查看QRCODE的方式是點選關閉專案後看到
感覺很怪
是否換個位置放還怎樣?

![image](https://user-images.githubusercontent.com/10150807/40895818-1cd4d1d4-67e4-11e8-92c2-d14766aac9e9.png)

**Comment by Gabe-Liu** [comment]
那要先請 @liucwlewis  @ryzojudy 他們討論一下，要改成怎樣的流程或畫面

**Comment by ryzojudy** [comment]
經過討論後
會調整查看時那個狀態的畫面呈現
QR code也會出現在那個畫面中
已經有跟gabe提過
lewis會再出圖

**Comment by liucwlewis** [comment]
@Gabe-Liu  
畫面位置： https://zpl.io/awrAj5M
