### ISSUE TITLE
上傳圖片編輯時看不到，卻在預覽時候出現！

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#352]
<img width="1439" alt="2018-06-04 11 37 05" src="https://user-images.githubusercontent.com/34700112/40897122-ac46c7d0-67eb-11e8-80ad-fc72e23093f7.png">
<img width="1440" alt="2018-06-04 11 36 58" src="https://user-images.githubusercontent.com/34700112/40897123-ac72405e-67eb-11e8-8cab-b9fa29ebec2b.png">
如圖所示，上傳一張圖片，在編輯時一直以為上傳失敗，因為都沒有東西，
卻在預覽時候出現了？！

**Comment by Isabella-RYZO** [comment]
@brendatseng 還可從現嗎? 剛剛我一直試，試不出來。☹️

**Comment by ai015606220** [comment]
@brendatseng 
這情況很常發生嗎? 
圖片沒出現時, 元件框(可調整大小的綠線框)的大小是跟圖片一樣大的嗎?
編輯頁重整之後圖片有出現嗎?

**Comment by brendatseng** [comment]
今天早上才出現的，
現在重新整理已解決，
圖片沒出現時，不會有元件框，就是什麼都沒有，讓人覺得沒有上傳成功。
