### ISSUE TITLE
表格文字樣式設定沒反應

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#353]
<img width="1432" alt="2018-06-04 16 32 59" src="https://user-images.githubusercontent.com/34700112/40907005-0d4e2c0c-6815-11e8-9136-93f7ca652257.png">
如圖，表格的文字樣式設定沒反應

<img width="426" alt="2018-06-04 16 34 08" src="https://user-images.githubusercontent.com/34700112/40907044-253d4b7c-6815-11e8-827b-d588f159df2f.png">
另外表格設定的表格內容建議，可以做一些說明，讓人知道可以直接拉他調大小，
不然找很久找不到～

**Comment by ai015606220** [comment]
@brendatseng 這是個bug, 在修好前如果你急著用的話, 可以先將  "開啟首欄首列"  開啟一次, 就會正常

**Comment by ai015606220** [comment]
bug已修正, 待日後上線
第二點有請 @ryzojudy

**Comment by brendatseng** [comment]
<img width="487" alt="2018-06-05 09 36 41" src="https://user-images.githubusercontent.com/34700112/40950130-ff03fa52-68a3-11e8-83fc-a14c3cb08180.png">
<img width="25" alt="2018-06-05 09 38 32" src="https://user-images.githubusercontent.com/34700112/40950173-3ec3e6a2-68a4-11e8-81a8-ecaeb29520cc.png">

再詢問一下，文字框的大小已足夠，有方法可以不要有上面的拖拉出現嗎？ 這是bug嗎？

**Comment by ai015606220** [comment]
對, 是bug, 我會再修正

**Comment by ryzojudy** [comment]
針對第二點
會在"使用統一尺寸"後面加一個問號的icon
鼠標移過去會出現氣泡窗告知使用者
在麻煩 @liucwlewis 出圖

**Comment by liucwlewis** [comment]
位置：https://zpl.io/am6llQr
<img width="957" alt="2018-06-06 11 37 40" src="https://user-images.githubusercontent.com/37163894/41015706-0a1c5d3c-697e-11e8-9f9c-052a8a6d2252.png">
