### ISSUE TITLE
【問題】臉書工具 內嵌型

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#354]
HI

請問臉書工具內嵌型的留言板，如果要使用的話有什麼特別需要注意的嗎

例如隱私權設定還是什麼之類的

因為目前無法使用

![2018-06-04 4 36 09](https://user-images.githubusercontent.com/34327325/40907187-a27308a2-6815-11e8-93a2-d510e15c9710.png)

**Comment by ryuichl** [comment]
那個是讓你內嵌某則留言
不是留言版
