### ISSUE TITLE
【建議】圖示功能

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#356]
目前圖示元件的搜尋，必須先找到指定的分類以後才能搜尋分類內的icon

建議改成搜尋的時候可以全域搜尋

另外，圖示的分類目前都是英文，建議可以翻譯成中文。
這部分是只要提供分類的中英文對照表就可以協助替換嗎？

謝謝

**Comment by ryuichl** [comment]
搜尋我們會再找時間做優化

分類的部份有中英對照的話可以協助替換

**Comment by wilmaftliu** [comment]
已完成分類中英翻譯 連結請見下方
https://docs.google.com/spreadsheets/d/1iUaYw2SYqc28zNDIFDnUNE5Buz6RcYl96P4ngnSL3o0/edit?usp=sharing

**Comment by Isabella-RYZO** [comment]
已將圖示分類中文化，並將搜尋設為全域搜尋，待上線
