### ISSUE TITLE
【建議】數值輸入不要限制至少預留一個值

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#361]
HI
三版在輸入數值的時候，無法全部刪除，重新鍵入數值
因此剛剛在表格裡想要用輸入數值的方式修改欄位數量時
出現了不受控制的情況
原本只是要輸入4*15

但因為以上的預設設定，以及不知名原因欄跟列會自己浮動數值
最後變成如下圖75欄不受控制的情況
並且系統會變得非常卡頓，無法修改
再麻煩協助調整、或是檢查是否有bug在其中

![2018-06-05 4 20 21](https://user-images.githubusercontent.com/34327325/40964132-e484f260-68dc-11e8-8fd2-90352c0423c2.png)

**Comment by ryuichl** [comment]
輸入數值
數字會亂跳

**Comment by ai015606220** [comment]
這邊目前輸入太大的數值的時候會有問題,
我需要改寫一下,
請先別輸入大數值
