### ISSUE TITLE
【下拉式選單呈現不一致】目前下拉式選單的顏色不一致

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#366]
改成這樣
<img width="494" alt="2018-06-06 9 33 56" src="https://user-images.githubusercontent.com/37163894/41011012-5413b9dc-696d-11e8-9833-ae0196d0fce3.png">
其他
<img width="310" alt="2018-06-06 9 33 41" src="https://user-images.githubusercontent.com/37163894/41011028-65e92e62-696d-11e8-9789-f797b3a6481d.png">
<img width="331" alt="2018-06-06 9 34 01" src="https://user-images.githubusercontent.com/37163894/41011030-681fd7d0-696d-11e8-907a-327f34c8c975.png">
<img width="431" alt="2018-06-06 9 34 06" src="https://user-images.githubusercontent.com/37163894/41011032-69747564-696d-11e8-817d-693d4c9d968f.png">

**Comment by ryuichl** [comment]
實作方式不同 
無法如你所願
感恩
