### ISSUE TITLE
[建議] 圖片剪裁

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#368]
圖片剪裁畫面再麻煩 @liucwlewis  設計一下
感恩

![image](https://user-images.githubusercontent.com/10150807/41012316-9423e9d8-6973-11e8-8e70-5ace4791f16a.png)

**Comment by wilmaftliu** [comment]
希望可以像二版一樣 有一個「恢復原圖」的按鈕
<img width="957" alt="2018-06-07 1 43 47" src="https://user-images.githubusercontent.com/34560641/41080384-d321b33c-6a58-11e8-9ecd-da696e747e99.png">

**Comment by liucwlewis** [comment]
位置：https://zpl.io/VxkMOlR
icon位置：https://drive.google.com/open?id=1Jvzj2GFWKzEp556kLsAgCaTMQdfpG5e-
![2018-06-08 2 51 02](https://user-images.githubusercontent.com/37163894/41143475-ffc2d5d2-6b2b-11e8-9749-760ec41fa7b8.png)

**Comment by ryuichl** [comment]
重設的按鈕按下去會怎樣阿?

**Comment by ai015606220** [comment]
已完成, 待日後上線

@ryuichl 目前我是讓他回復到最初的那張圖
