### ISSUE TITLE
[建議] 手機預覽說明

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#370]
目前手機預覽部分缺乏一些說明
1. 說明QRCODE功能為設計時的手機預覽
2. 手機預覽只能看到儲存後的結果
建議可以補上
感恩

![image](https://user-images.githubusercontent.com/10150807/41020391-48554cf0-6995-11e8-9287-5625442c95ae.png)

**Comment by ryzojudy** [comment]
那一串文字不夠明確嗎??

**Comment by ryuichl** [comment]
第二點我剛有看到了
但不太明顯
或許可以用紅字?

**Comment by liucwlewis** [comment]
1.說明QRCODE功能為設計時的手機預覽
->目前的QRCODE跟網址都是可以直接在手機或電腦上開啟，所以我覺得應該不用強調手機觀看這件事
2.手機預覽只能看到儲存後的結果
->目前文字中最後面補充的文字應該就能了解～～我覺得啦～～～～

**Comment by wilmaftliu** [comment]
如果沒有按重新整理 預覽的連結就是無效的
要是沒理解敘述文字 或是沒看到重新整理的圖示的使用者 會誤以為預覽壞惹ＱＡＱ
會有這樣的狀況是因為把在WEBA預覽和在瀏覽器預覽做在同一頁了

建議做法：
1. 每次按下眼睛去預覽時 如果做在同一頁 無法判斷用戶是要在WEBA內預覽還是在瀏覽器預覽
 ＱＲ和上面的連結就應該要可以自動更新成最新的（但這樣聽說工程就得要每次按那顆眼睛都要傳資料回去）

2. 點開眼睛時就是出現WEBA內的預覽 如果有需要在瀏覽器預覽 另外按鈕產出 不預設提供

以上 提供參考

2. 不主動產出手機預覽的QR和網址 如果

**Comment by liucwlewis** [comment]
位置：https://zpl.io/VK0WnDR
![default](https://user-images.githubusercontent.com/37163894/41082799-0e1c19d8-6a62-11e8-88ed-ca6930e425ae.jpg)

**Comment by liucwlewis** [comment]
位置：https://zpl.io/VK0WnDR
<img width="1279" alt="2018-06-07 5 12 48" src="https://user-images.githubusercontent.com/37163894/41090130-162409ce-6a76-11e8-9067-a57aec2e3c05.png">

**Comment by Gabe-Liu** [comment]
待下次更新
