### ISSUE TITLE
【建議】在畫布就可以上傳圖片

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#377]
![1528342295772](https://user-images.githubusercontent.com/34560641/41077363-cfea51ac-6a48-11e8-9916-794680bed2ae.jpg)
如果可以像在手冊上做的一樣 能在畫布中就能上傳圖片或輪播圖 覺得會直覺許多
![1528342385223](https://user-images.githubusercontent.com/34560641/41077386-ecef1418-6a48-11e8-9d69-fd68a1560175.jpg)
目前在三版上圖片上傳會有個圖 再去右邊上傳

**Comment by ryuichl** [comment]
未來會有簡易工具列
請期待我們的新功能
