### ISSUE TITLE
【建議】輪播區塊＆輪播圖的輪播點預設顏色

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#378]
輪播圖則是空白（下方和左右會有輪播方向鍵頭和白色輪播點，但是如果背景是原本的白色沒有設定的話其實看不出來裡面有東西）
建議可以把預設的輪播點點設定成黑色的
（輪播區塊亦同）
<img width="348" alt="2018-06-07 11 53 25" src="https://user-images.githubusercontent.com/34560641/41077489-71e69d8a-6a49-11e8-945a-047522ad2070.png">

**Comment by Gabe-Liu** [comment]
待上線
