### ISSUE TITLE
【問題】收縮區塊右側圖示無法點擊

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#380]
目前的收縮區塊右側有兩種圖示可以選（＋號和箭頭）
可是在預覽時發現，如果把游標移到右側的圖示上時，是不能點擊的（要點擊圖示以外的地方才有反應）
發布後手機上也是如此

感覺圖示就是會引導人去點 如果那塊不能點 會讓人以為收縮區塊沒有反應 希望可以讓整個標題區都能點擊

GABE欠我一次

**Comment by ai015606220** [comment]
已修正, 待上線
