### ISSUE TITLE
[bug] 預覽模式到期警示

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#381]
預覽到期的alert沒有寫字

![image](https://user-images.githubusercontent.com/10150807/41080730-5742cce0-6a5a-11e8-973c-7ec2234b3c96.png)

**Comment by ai015606220** [comment]
程式碼裡面看的確alert裡面是沒有值的, 請問有人能提供要放什麼字嗎?

**Comment by ryzojudy** [comment]
預覽時間已到期，請重新至預覽處生成連結

**Comment by ryuichl** [comment]
我們連結是固定的唷

**Comment by ryzojudy** [comment]
預覽時間已到期，請重新至預覽處刷新預覽有效時間
