### ISSUE TITLE
【帳號問題】註冊時說已有此用戶，但是要重寄認證信時又說無此用戶

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/v3-report#382]
和泰的帳號問題
Michelle.Lee@HOTAINS.COM.TW

上面這個帳號之前有註冊，但是找不到認證信，
所以想重寄認證信。

點選重寄時，說「無此用戶」，
但是回到註冊頁想重新註冊時，又說「已有此用戶」。

所以目前完全無法登入此帳號
QQQQQQ

**Comment by ryuichl** [comment]
重寄時請打小寫

**Comment by ryuichl** [comment]
這部分我們會再優化

**Comment by Grace-Tseng** [comment]
OK, 寄成功了，Thanks!!!

**Comment by ryuichl** [comment]
已修正待上線
