### ISSUE TITLE
小積木的icon是舊的

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#385]
<img width="67" alt="2018-06-07 3 49 44" src="https://user-images.githubusercontent.com/34293268/41085740-71e3e9b6-6a6a-11e8-9150-fb360a16be44.png">
嗨～
小積木的icon好像用到舊的了

下面這個才是新的～
<img width="675" alt="2018-06-07 3 50 23" src="https://user-images.githubusercontent.com/34293268/41085790-90885d98-6a6a-11e8-905c-d4a167a48e87.png">

路徑是
第三版icon>02 編輯區>** 05 左側吧>左側吧-小積木
謝謝～～

**Comment by ai015606220** [comment]
已修正, 待日後上線
