### ISSUE TITLE
【建議】元件分類

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#387]
目前元件已經高達24個 建議可以將元件分類（目前使用手冊上是分成4類）
方便快速找到需要的元件
<img width="476" alt="2018-06-07 3 59 27" src="https://user-images.githubusercontent.com/34560641/41086186-d8ebbdc2-6a6b-11e8-8f09-9a045ac8d060.png">

**Comment by liucwlewis** [comment]
位置：https://zpl.io/25ynZvW
<img width="1148" alt="2018-06-07 4 33 34" src="https://user-images.githubusercontent.com/37163894/41088027-f382b00a-6a70-11e8-9814-94b4914ee13a.png">

**Comment by wilmaftliu** [comment]
覺得可以分類 但是不要收縮起來 
不然要一個一個點開才能找到想要的元件

**Comment by wilmaftliu** [comment]
喔喔 好喔
