### ISSUE TITLE
【建議】希望右側編輯區可以完全收合起來

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#388]
希望右方的編輯區域可以往右收合
請見圖示

展開
<img width="614" alt="2018-06-07 4 19 48" src="https://user-images.githubusercontent.com/34560641/41087245-bdd698ce-6a6e-11e8-9603-258b857d9dda.png">

收合
<img width="617" alt="2018-06-07 4 20 17" src="https://user-images.githubusercontent.com/34560641/41087256-c5dd2fa6-6a6e-11e8-8e73-70828846bed5.png">

以上

感謝

**Comment by ryuichl** [comment]
收起來的用意是?

**Comment by wilmaftliu** [comment]
因為有時候提示設定的時候會被右側編輯區擋到
或是有些元件會先放在右邊 超出畫布 如果編輯區一直都在 不太方便

**Comment by ryzojudy** [comment]
目前實際狀況：
在較小螢幕(如13.3吋)編輯提示時
瀏覽器需要縮小到80%才不會被擋到

剛剛詢問了大家的意見
目前是覺得收不收影響不太大
但普遍都希望圖層區可以拉大
這邊先提供一個小彩蛋
希望可以先幫你解決這件煩惱事
我們的選單架構那一頁是可以移動的
可以利用那的小視窗來左右移動我們的編輯頁
![20180608_112455](https://user-images.githubusercontent.com/34263719/41137690-2677e0b8-6b0f-11e8-8818-10fcafd8aa50.gif)

**Comment by liucwlewis** [comment]
位置：https://zpl.io/25yn56r
icon連結：https://drive.google.com/open?id=0B7J75LWx4nupeUtlMXVuRURBTzQ
![2018-06-08 11 44 59](https://user-images.githubusercontent.com/37163894/41138062-62f1c6e2-6b11-11e8-9967-86a0468a1bf0.png)

**Comment by wilmaftliu** [comment]
@ryzojudy 選單視窗可以移動但是提示不能移動 ＱＡＱ

**Comment by ryzojudy** [comment]
你現在可以先暫時用選單把右邊的空間拉寬後 再點提示 這樣就不會擋到了~

**Comment by ai015606220** [comment]
已完成, 待日後上線
