### ISSUE TITLE
【建議】希望文字元件中可個別節選某段文字做不同設定

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/v3-report#392]
現行做法：
在同一個文字元件中的文字 只能同樣顏色、大小、字體、......等
一旦要做不同設定，就要再開新的文字元件，無法直接做標示 as V2。

希望做法：
在同一個文字元件中的文字 可個別節選某段文字做不同設定。

**Comment by ryuichl** [comment]
這牽扯到技術細節
基本上這版的設定就是這樣
無法再優化
