### ISSUE TITLE
【建議】透明度設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#394]
因為文字工具裡透明度設定是由左至右 透明至不透明。
另外一般使用者在使用時，東西越透明，通常數值會設定越小

所以建議此區設定為 “不透明度”一類說法
並且調整桿由左至右是透明>>>>不透明

![2018-06-08 10 32 14](https://user-images.githubusercontent.com/34327325/41136181-b066bb58-6b07-11e8-80e9-cf64cb0ac0d6.png)

**Comment by ryzojudy** [comment]
文字工具???

**Comment by ryuichl** [comment]
猜測是說這個

![image](https://user-images.githubusercontent.com/10150807/41136651-d2203a60-6b09-11e8-8f66-e72cfeb2147b.png)

**Comment by weilyn** [comment]
沒錯 就是roy的那個截圖，並且那個比較符合常態的使用邏輯

所以建議系統裡其他的透明度 像是圖片、背景之類的也可以參照這個方向性
不然就是要統一

**Comment by ryzojudy** [comment]
經過討論且參考了一下其他競品
統一都是使用不透明度的設定
因此希望改成下面這樣
不透明度 一開始的預設值就是100%
感謝~~
![image](https://user-images.githubusercontent.com/34263719/41137992-efc51926-6b10-11e8-99b0-d583ce9a5499.png)

**Comment by ai015606220** [comment]
已修改, 待日後上線
