### ISSUE TITLE
【問題】表單動畫

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#396]
HI
在表單上加入動畫 (淡入)
表單Loading完會直接呈現在畫面上，然後才運行動畫

沒有任何群組

**Comment by ryuichl** [comment]
我試了是他在LOADING時就開始在跑動畫
你可以試看看淡入拉長一點時間 5秒之類的

**Comment by weilyn** [comment]
剛剛再次確認發現情況還是有發生
此外這個物件的30分鐘預覽的動畫失效
附上參數及截圖
![2018-06-08 11 49 43](https://user-images.githubusercontent.com/34327325/41138293-edcb88e2-6b12-11e8-961b-c699098e08b5.png)


![untitled](https://user-images.githubusercontent.com/34327325/41138296-f0313258-6b12-11e8-8402-611202920975.gif)

**Comment by ryuichl** [comment]
備註
淡入有延遲時 
表單剛開始是出現的狀態

**Comment by ai015606220** [comment]
@weilyn 手機預覽的動畫我測試是沒問題的, 麻煩詳述你的情形以供測試

**Comment by weilyn** [comment]
https://ryzoweba.io/client/mobile-preview/5b18f6b02ee0391368f05dd4
目前中間表單的題目是設定延遲1.5秒以後才淡入進畫面
所以題目原本不應該直接出現在畫面上

不過在預覽中可以看到他LOADING黑色畫面結束後就直接停留在畫面上，
時間到了才重做一次淡入(因此閃了一下)

**Comment by ai015606220** [comment]
已修正, 待日後上線
