### ISSUE TITLE
【建議】專案管理的預覽專案

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#397]
HI
已經發布的專案
在專案管理區點選預覽時會出現QR跟網址

建議網址增加複製的icon （同系統地方的複製網址icon）

**Comment by weilyn** [comment]
![2018-06-08 11 48 12](https://user-images.githubusercontent.com/34327325/41138754-fbab8734-6b15-11e8-879f-c09505bbe570.png)

**Comment by ai015606220** [comment]
已完成, 待日後上線
