### ISSUE TITLE
限制in app browser的瀏覽

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#398]
之後預計支援的in app browser
只有line 和 facebook

為了避免用戶使用不知名的QR掃描器
增加判定用戶是否使用line 和 facebook 以外的 in app browser
是的話出現遮罩 引導用戶使用瀏覽器開啟

麻煩 @liucwlewis  設計畫面
感恩

**Comment by ryzojudy** [comment]
文字部份：
請使用LINE或Facebook打開連結
感謝~

**Comment by ryuichl** [comment]
我們會去偵測他是不是用
非LINE或FB的內置瀏覽器打開
是的話就放遮罩

**Comment by liucwlewis** [comment]
感覺在台灣微信的用戶也蠻多的，也會限制微信嗎？

**Comment by ryuichl** [comment]
恩 限制 目前暫不支援

**Comment by ryzojudy** [comment]
文字部分：
請使用手機內建瀏覽器開啟網頁
感謝~~

**Comment by Gabe-Liu** [comment]
待上線
