### ISSUE TITLE
【問題】表單設定 表單連結

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#400]
HI，剛剛在整理沒有用到的表單資料
發現很多連動到 undefined的專案
不知道是不是從已經被我刪除的專案殘留下來
目前帳號裡專案都有命名

![2018-06-08 4 16 53](https://user-images.githubusercontent.com/34327325/41147016-c3642120-6b37-11e8-926b-e01d1133cc1e.png)

**Comment by ai015606220** [comment]
已修正, 等待上線
