### ISSUE TITLE
【建議】圖層視窗 手動拉長高度 顯示更多元件圖層

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#401]
圖層視窗體驗優化建議：
由於目前圖層視窗的高度有限，畫布上一旦元件過多，要在茫茫圖層中找到特定元件，以目前設定的高度可能會造成搜尋上的困擾，有鑑於此建議可以增加拉高圖層視窗的功能，方便使用者選取圖層中的元件來設計頁面。
![default](https://user-images.githubusercontent.com/37531593/41147570-519e8ed4-6b39-11e8-80b0-9a9a469f45bc.jpg)

**Comment by Gabe-Liu** [comment]
給兩種比較好解決的方法，
1. 把原本預設的高度調高(現在圖層預設是折疊起來的，一開始不會展開
2. 把圖層放到別的地方，點擊才切換到圖層，如此可以讓它整排呈現出來。

**Comment by Samasianspock** [comment]
@Gabe-Liu
因為目前的圖層位置其實是方便使用者選擇以及管理元件位置，不太適合再另開頁籤(多一個切換步驟)，
還是希望能夠有自由調整高度的功能，讓使用者調整成最合適的高度去操作。
期待您的日後更新。

**Comment by ryuichl** [comment]
為何不能直接調高固定高度?
@Samasianspock

**Comment by Samasianspock** [comment]
@ryuichl 如果要再設定固定的高度也是可以 (高度直接設定到示意圖最右邊的狀態)，但每個人合適的高度可能都不同，圖層的多寡也不一定，所以還是認為能夠自由調整高度是最好的方法。

**Comment by ryuichl** [comment]
希望你理解的部分是
解法有快速和麻煩的選擇
如果你選擇快速可能等下就改好
麻煩的話可能是2個月
端看你的選擇

**Comment by Samasianspock** [comment]
了解，可以先用快速的方式先做，之後再慢慢優化。

**Comment by ryuichl** [comment]
請問要調整固定高度的話想調到多少?
@Samasianspock  @liucwlewis

**Comment by ryuichl** [comment]
如果是全展開
那跟多一個頁籤的意思是不是一樣?

**Comment by liucwlewis** [comment]
ummmm，我跟sam是覺得快速展開選取到要的元件就這樣，應該沒有重要到需要再開一個新的頁籤

**Comment by Gabe-Liu** [comment]
待下次更新
