### ISSUE TITLE
【問題】社群追蹤

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#402]
HI 社群追蹤第一個欄位可以讓我選擇要顯示哪些社群網站

不過在第三步要輸入網址的時候

無論我有沒有選擇到開啟他，都還是會顯示icon，只是不能輸入網址

不知道這件事能否整合，例如有輸入網址的才會顯示出來
或是有選到的才會在第三步顯示icon

![2018-06-08 4 39 12](https://user-images.githubusercontent.com/34327325/41148121-cd893a0c-6b3a-11e8-9a03-bc0e270a61a6.png)

**Comment by Isabella-RYZO** [comment]
待上線
