### ISSUE TITLE
【問題】裝飾圖案的預覽圖

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#403]
hi
裝飾圖案“圓形”在預覽圖裡會神奇的變形

但暫時不影響其他層面

![2018-06-08 5 20 09](https://user-images.githubusercontent.com/34327325/41150350-5e7ca3e6-6b40-11e8-8bcc-89341feca76f.png)
![2018-06-08 5 19 43](https://user-images.githubusercontent.com/34327325/41150351-5ea52be0-6b40-11e8-81ce-1c0e50fd0a3f.png)

**Comment by Gabe-Liu** [comment]
已解決
