### ISSUE TITLE
輪播區塊加裝飾圖案的bug

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#405]
<img width="1432" alt="2018-06-11 14 46 10" src="https://user-images.githubusercontent.com/34700112/41216271-35b2c9b6-6d86-11e8-9261-f5d63999dffe.png">
如圖，在輪播區塊，進入編輯區後，添加裝飾圖案，須先離開編輯區一次，才能看到添加的裝飾圖案。

**Comment by ryuichl** [comment]
我這邊測試沒這問題
待 @Gabe-Liu  深入確認

**Comment by Gabe-Liu** [comment]
我本機與線上測試沒有問題
