### ISSUE TITLE
【問題】裝飾區塊旋轉調整大小

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#406]
HI
裝飾區塊旋轉後

調整大小會亂飄

**Comment by ryuichl** [comment]
是甚麼形狀會有這種狀況?
我試沒有亂飄的感覺

**Comment by weilyn** [comment]
我剛剛使用方形 還有很像旗幟的的都有類似情況發生

**Comment by Isabella-RYZO** [comment]
我這邊測試的情況也正常

**Comment by ai015606220** [comment]
初步了解是因為旋轉的物件在調整尺寸時它的座標會需要用不同的計算方式,
https://stackoverflow.com/questions/25985630/changing-width-height-moves-rotated-element
會繼續研究如何調整
