### ISSUE TITLE
【問題】表單如果有「日期」、「時間」等有預設答案的問題，進度條數字會不準

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#407]
<img width="302" alt="2018-06-12 12 14 04" src="https://user-images.githubusercontent.com/34560641/41269805-1e858f26-6e3a-11e8-9588-ad6e86791df3.png">
表單裡如果有像是「日期」、「時間」這種有預設答案的問題
即使還沒開始填表 因為有預設今日日期和現在時間 所以進度條會判定為已填寫 
如果只有這兩題 進度條在一開始就會顯示100%（如附圖）

希望可以優化 讓進度條可以從零開始

**Comment by ai015606220** [comment]
已完成, 待日後上線
