### ISSUE TITLE
【問題】表單多題單頁時，不應該出現捲軸(scroll bar)

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#410]
如 Weilyn 的案例所示，表單在多題單頁形式預覽時不應該出現捲軸。
![2018-06-12 3 51 51](https://user-images.githubusercontent.com/37531593/41277728-99988900-6e5a-11e8-9bd9-c0ccbd90172e.png)

**Comment by ryuichl** [comment]
不好意思
圖片中看不太出來不應該的點是?

**Comment by weilyn** [comment]
這個表單是一次展開到底的，但是表單內部本身就有一個捲軸，跟長頁的捲軸會互相衝突

**Comment by ryuichl** [comment]
感覺是你的表單拉不夠長?

**Comment by weilyn** [comment]
![2018-06-12 4 10 20](https://user-images.githubusercontent.com/34327325/41277921-212f3d0a-6e5b-11e8-9d71-27aa35e723ac.png)

**Comment by ryuichl** [comment]
應該是因為雖然你看到他題目都出現
但是實際上還有一些高度
你拉長一點應該就沒有捲軸了吧?
