### ISSUE TITLE
[bug] 表單 單行文字填寫中文在後台會沒東西

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#411]
![image](https://user-images.githubusercontent.com/10150807/41279025-f520032c-6e5d-11e8-8033-631d23de20a2.png)
![image](https://user-images.githubusercontent.com/10150807/41279036-fae98012-6e5d-11e8-944a-1e675b8d32cd.png)

**Comment by ai015606220** [comment]
已修正, 待日後上線
