### ISSUE TITLE
【建議】QR code 產生器

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#415]
上傳圖片以後無法刪除
![2018-06-15 3 50 53](https://user-images.githubusercontent.com/34327325/41456745-003462d2-70b4-11e8-963d-46b5891eba95.png)

**Comment by Gabe-Liu** [comment]
切回顏色不就得了!

**Comment by weilyn** [comment]
1. 切回顏色圖片還在
2.顏色模式的商標圖也不能刪除

目前解就是關掉視窗重做一個～

**Comment by liucwlewis** [comment]
目前Gabe修改成左右排列，但上下排列看起來比較沒那麼擠
![artboard](https://user-images.githubusercontent.com/37163894/42301751-97d9940a-8049-11e8-94d5-322629574d71.jpg)
