### ISSUE TITLE
【問題】表單連結

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#416]
HI
在表單後台裡發現

我將A跟B專案原本串連的 表單1修改成表單2
但是在表單1的編輯裡，依然顯示跟A、B專案串連

<但表單2裡也有顯示與A、B專案串連

總之就是這部分顯示好像有異

![2018-06-15 4 15 21](https://user-images.githubusercontent.com/34327325/41457926-be7bebfe-70b7-11e8-8ab6-a31b37942842.png)

**Comment by ryuichl** [comment]
我們這邊會在找時間優化

**Comment by weilyn** [comment]
謝謝 不急

**Comment by ryuichl** [comment]
@ai015606220 
我已經新增一個API可以刪除表單和專案的連動在 v3development
這個issue你有空可以改一下

**Comment by ai015606220** [comment]
好的

**Comment by ai015606220** [comment]
已完成，待日後上線

**Comment by ai015606220** [comment]
目前刪除的時機是專案送出審核的時候
