### ISSUE TITLE
【問題】表單資料填寫

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#420]
請協助確認此專案表單無法正確發送
會出現表單回覆發生錯誤
https://webasurvey.ryzoweba.io/

![2018-06-19 12 27 02](https://user-images.githubusercontent.com/34327325/41576835-1ec26824-73bc-11e8-8d5d-426c71c36589.png)

**Comment by ryuichl** [comment]
已修復 請確認
感恩
