### ISSUE TITLE
【問題】圖片上傳後變成一條線

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#422]
<img width="999" alt="2018-06-20 2 19 11" src="https://user-images.githubusercontent.com/34560641/41640802-9ade8288-7495-11e8-83d3-2ba44fc873b7.png">
在圖片上傳後 圖片變成一條線 
游標滑上去會顯示「未選擇任何檔案」
<img width="321" alt="2018-06-20 2 24 37" src="https://user-images.githubusercontent.com/34560641/41640843-bf9d133c-7495-11e8-8687-6ca5b0dbf37c.png">
這時候的線條可以再稍微縮放 但是如果再點擊其他區域 線條就消失了
但是預覽時他又會出現完整圖片
<img width="387" alt="2018-06-20 2 25 58" src="https://user-images.githubusercontent.com/34560641/41640896-fa026090-7495-11e8-8d16-1ffa42bc17d3.png">

預覽回來圖片就又出現了

求抓鬼
感恩

**Comment by ryuichl** [comment]
應該是修掉了
有再發現的話請再提出
感恩
