### ISSUE TITLE
【建議】右側的編輯區的收縮按鈕 在點擊元件時會自動展開

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#423]
目前右側編輯區有可以把編輯曲收合起來的收縮按鈕（撒花）
不過如果收合起來後 如果把原件丟在右側畫布外
然後右側編輯區收合的狀態下點擊元件時
右邊本來收起來的編輯區就會認為你要進行元件的編輯而自動展開了
（但我只是要調整位置而已）

這樣變成每次要去右側做事情時 又要一直把編輯區收起來
感覺跟收合的需求相違背

希望可以不要自動展開 等到點開他的時候再展開就好
不然這樣收合的功能感覺沒有什麼意義 （因為隨便點到什麼他都會在展開）
又手動又自動感覺邏輯衝突 希望可以改成手動開關就好

歡迎討論 感恩

**Comment by Gabe-Liu** [comment]
剛好在修改相關的地方，就順便修改，待下次更新
