### ISSUE TITLE
【問題】做好轉盤選擇表單時滑不下去按確定

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#424]
<img width="1278" alt="2018-06-20 6 12 47" src="https://user-images.githubusercontent.com/34560641/41692639-e7c18520-7533-11e8-80c1-9291ac24aadd.png">
可能是螢幕比較小的關係？
我做好轉盤時要選擇表單的時候 會滑不下去 無法按到確定鍵
要把畫面縮放 比例縮小他才會出現
希望可以放上面一點
PS: 使用的是macbook 12"

**Comment by wilmaftliu** [comment]
<img width="1034" alt="2018-06-21 9 30 26" src="https://user-images.githubusercontent.com/34560641/41692989-d3ba0c9e-7535-11e8-9eb3-addfe4431a79.png">
選擇表單主題樣式時也有一樣的問題
無法下去按到下方的「儲存」按鈕

**Comment by ai015606220** [comment]
已修正，等待上線

**Comment by wilmaftliu** [comment]
感恩
