### ISSUE TITLE
【問題】表單左側圖示被壓扁

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#425]
<img width="779" alt="2018-06-21 9 33 42" src="https://user-images.githubusercontent.com/34560641/41693109-5edb4bd0-7536-11e8-8954-36ef88bec9a3.png">
如紅框處 左側的表單圖示和下方的「編輯」按鈕會被壓扁
甚至是空白的情況
（macbook 12")

**Comment by ai015606220** [comment]
修改完成，等待上線
