### ISSUE TITLE
表單題數少的時候 題目和送出按鈕之間會空下一段透明的區塊

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/v3-report#430]
<img width="346" alt="2018-06-21 15 50 16" src="https://user-images.githubusercontent.com/34263114/41705202-e33793dc-756a-11e8-8797-e2d084533cf7.png">

**Comment by ai015606220** [comment]
@Grace-Tseng 你可以把表單的高度縮短，因為有背景顏色的是題目而非表單本身

**Comment by ai015606220** [comment]
如果是轉盤的表單無法調整高度的話，建議使用單題多頁或是多新增幾題題目
因為一些原因，我無法在表單本身加背景顏色

**Comment by Grace-Tseng** [comment]
了解，已透過調整行距的方式解決。
