### ISSUE TITLE
【問題】分享圖預覽

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#433]
預覽中的FB樣式

據印象中應該是1200*628
目前的預覽格式不符合這個比例

![2018-06-21 4 38 17](https://user-images.githubusercontent.com/34327325/41707846-a986c85e-7571-11e8-82c3-c91225f19328.png)

**Comment by ryuichl** [comment]
![image](https://user-images.githubusercontent.com/10150807/41709256-53715958-7575-11e8-95e4-1e42bd5bc68e.png)

補充

**Comment by Gabe-Liu** [comment]
待下次更新
