### ISSUE TITLE
【問題】新增表單題目

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#435]
HI
大螢幕在新增表單題目時，如果題目數比較多的時候，很容易感應到表單右側題目的捲軸。
（但其實目前能夠一次顯示出全部的題型，且捲軸過長，其實下方都是空白的欄位）

在使用過程中很容易出現附件中的樣子：
想要新增題目，但是很多題目選項因為捲軸關係被滑到上方了，要再手動滾動下來
![2018-06-22 9 40 48](https://user-images.githubusercontent.com/34327325/41753578-d4e3fc44-7600-11e8-8f58-48fafd1df45f.png)

**Comment by ai015606220** [comment]
已修正，等待上線
