### ISSUE TITLE
【問題】專案發布的表單問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#436]
HI，
專案已經審核發布，後又在專案裡的表單進行修改，並儲存>發佈

經過重新審核，並更新專案後，發現無論是預覽或是實體網址部分，表單的修改都沒有成功被更新到
網址如下https://hearteasing.ryzoweba.io

![2018-06-22 9 49 00](https://user-images.githubusercontent.com/34327325/41753737-c6d8d8e4-7601-11e8-8189-9c815d2fd9f7.png)

**Comment by weilyn** [comment]
但是專案的名稱那些修改有被更新到

**Comment by ai015606220** [comment]
原因是題目修改後沒有點擊完成就關閉視窗，之後會在想如何優化提醒的部分
