### ISSUE TITLE
【問題】製作時的間距與發佈後的不符

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#437]
製作時看起來編輯區的距離是這樣的：（是上下兩個文字框）
<img width="951" alt="2018-06-22 12 05 49" src="https://user-images.githubusercontent.com/34560641/41757540-3ed6a890-7615-11e8-9dd0-e7746b4c6194.png">
在WEBA上預覽時手機版也是相同的文字間距
<img width="756" alt="2018-06-22 12 05 59" src="https://user-images.githubusercontent.com/34560641/41757566-6927f284-7615-11e8-9b5f-c7d53222b47f.png">

但是在電腦版上預覽時間距就被拉大了
<img width="1070" alt="2018-06-22 12 06 06" src="https://user-images.githubusercontent.com/34560641/41757574-7670e234-7615-11e8-8f11-5e46a02b691e.png">

實際發布後電腦版和手機版的都是被拉大的距離
<img width="1277" alt="2018-06-22 12 12 14" src="https://user-images.githubusercontent.com/34560641/41757588-908e19fc-7615-11e8-9399-3f57dc1692b0.png">

![s__50741256](https://user-images.githubusercontent.com/34560641/41757607-b30dd35a-7615-11e8-80e6-b802a4f8d047.jpg)

專案網址： https://thermosdemo.ryzoweba.io/

再麻煩協助確認是什麼原因 感謝

**Comment by ai015606220** [comment]
![image 2](https://user-images.githubusercontent.com/10190722/41757769-b9624b90-7616-11e8-9e03-762cfb9083af.png)

我看這個元件的高度設定的確是這麼高??

**Comment by wilmaftliu** [comment]
原來是縮放比例的問題 因為我製作時螢幕比例有縮小到90% 已解決 感謝
