### ISSUE TITLE
【電腦版】手機複製到電腦時沒有複製完全

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#439]
手機版為長頁面
電腦版也將幻燈片拉到同高
手機版全選圖層後複製到電腦版
只有最一開始建立的群組何一個圖示複製成功
其他的都沒有過來
另外單獨複製一個群組時
有的可以複製成功
有的不行

有點不太知道怎麼形容
如果看不懂的話歡迎來找我~~

**Comment by ryzojudy** [comment]
![20180625_115021](https://user-images.githubusercontent.com/34263719/41829653-97c6ca10-786e-11e8-807d-10af7af2f8a2.gif)

**Comment by Gabe-Liu** [comment]
發現是 頁籤、輪播區塊、收縮區塊的複製出現BUG所導致的，
待下次更新~
