### ISSUE TITLE
【電腦版】從手機版複製轉盤到電腦版時 應可以選取已建立的轉盤

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#440]
目前將轉盤從手機版複製到電腦版
轉盤會照原本設定複製
但是進入到電腦版時 需點選啟用（這是後就變成一個新的轉盤了）
（沒有啟用的話轉盤在電腦上就不能用）

應該要可以選擇手機版建立的那個轉盤 收集至同一個表單

目前作法是 在電腦版重新新增一個轉盤 然後再選擇做好的轉盤
希望用複製的方式也可以做到這樣的效果

以上

**Comment by Samasianspock** [comment]
嗨威瑪，Gabe說之後複製的轉盤也會有“選擇轉盤”的選項，就可以選擇之前設定好的轉盤表單以及轉盤樣式。
<img width="319" alt="2018-06-25 1 57 39" src="https://user-images.githubusercontent.com/37531593/41832935-da49ad5a-7880-11e8-8f10-5d63f1db6d51.png">

**Comment by Gabe-Liu** [comment]
待下次更新

**Comment by wilmaftliu** [comment]
太棒了 感恩各位 期待更新
