### ISSUE TITLE
【問題】新建轉盤，在“選擇轉盤”時下拉選單的選項有問題。

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#441]
@Gabe-Liu 
新建轉盤或者複製轉盤後，欲選取先前設定好的轉盤，下拉選單的預設應該是在“請選擇轉盤”
目前是預設選取到我先前設定的轉盤“new lottery test”，而確定按鈕無法點擊，應該是串錯了，感謝！
<img width="319" alt="2018-06-25 1 57 39" src="https://user-images.githubusercontent.com/37531593/41833125-a797b900-7881-11e8-97e5-dd9bcbb78672.png">
<img width="316" alt="2018-06-25 2 08 31" src="https://user-images.githubusercontent.com/37531593/41833128-a931ab4a-7881-11e8-89df-c1822fa5f67f.png">
<img width="317" alt="2018-06-25 2 08 38" src="https://user-images.githubusercontent.com/37531593/41833132-aa920aa2-7881-11e8-88b4-4e9cf615bfd3.png">

**Comment by Gabe-Liu** [comment]
待下次更新
