### ISSUE TITLE
【問題】桌機模式預覽

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#442]
HI，在桌機模式放了滿版的大圖，
預覽的時候發現兩邊是白色的邊
不知道這兩個白邊用意是什麼

如果是因為比例緣故所以露出的介面顏色應該是灰色

![2018-06-25 3 28 25](https://user-images.githubusercontent.com/34327325/41836236-b83c89f6-788c-11e8-91d5-37d97160001a.png)

**Comment by ryuichl** [comment]
已解答
