### ISSUE TITLE
【問題】臉書工具 動作型 語系

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#446]
HI
電腦系統是中文系統
WEBA第三版不能切換語系

不過臉書工具顯示都是英文
![2018-06-26 10 50 38](https://user-images.githubusercontent.com/34327325/41886446-f753ab18-792e-11e8-8b70-7778a8a86645.png)

**Comment by ryzojudy** [comment]
可是我顯示的昰中文ㄟ
會不會是你臉書自己本身或是瀏覽企設定的語言是英文呢??
![image](https://user-images.githubusercontent.com/34263719/41896089-49131458-7956-11e8-85cb-8e1109fb14d5.png)

**Comment by weilyn** [comment]
所以製作過程也會看臉書的語系囉

我的臉書是英文的沒錯
