### ISSUE TITLE
【問題】桌機模式選單顏色

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#451]
桌機模式>主選單樣式>選取狀態>選取選單顏色

在預覽模式中顏色失效，應該要呈現黃色

![2018-06-27 9 45 17](https://user-images.githubusercontent.com/34327325/41948387-1609eac0-79ef-11e8-82af-384a3136aee1.png)
![2018-06-27 9 45 46](https://user-images.githubusercontent.com/34327325/41948390-1c2e4fae-79ef-11e8-86c8-8d52d2c6b7b0.png)

**Comment by ryuichl** [comment]
問題重複了
這個先關掉
