### ISSUE TITLE
【bug】電腦版的編輯與預覽有跑掉

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/v3-report#453]
<img width="691" alt="2018-06-27 11 01 10" src="https://user-images.githubusercontent.com/34700112/41950652-913b008a-79f9-11e8-9397-0ccdf888333e.png">
<img width="458" alt="2018-06-27 11 00 59" src="https://user-images.githubusercontent.com/34700112/41950653-91775300-79f9-11e8-9b7a-7641260caed5.png">
如圖～～ 文字區塊那邊跑掉～～

**Comment by Gabe-Liu** [comment]
製作時瀏覽器要保持100%的縮放狀態
