### ISSUE TITLE
【建議】裝飾區塊

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#454]
希望裝飾區塊可以新增以下幾種形狀
讓整體使用層面可以更彈性

![2018-06-29 1 38 23](https://user-images.githubusercontent.com/34327325/42075097-dd955e04-7ba1-11e8-859d-d5fcd97afaff.png)

**Comment by liucwlewis** [comment]
＊原始的圖案也麻煩調整排列順序～～
SVG檔：https://drive.google.com/drive/folders/10jCd_3hB_DKCg6onpLIiZ49ENDL5qmhF?usp=sharing
位置：https://zpl.io/bJqAOZ3
<img width="417" alt="2018-07-05 4 52 49" src="https://user-images.githubusercontent.com/37163894/42312923-125595ba-8074-11e8-9cd3-fed6d41d5fbe.png">

**Comment by Gabe-Liu** [comment]
@liucwlewis 提供的svg的檔案名稱命名順序請照你所提供的圖 ，不然我都要重新命名
以及如果以後有更多的svg儘量不要重新排列，要的話，請把檔案都重新命名好，我再載來使用~

**Comment by Gabe-Liu** [comment]
待下次更新

**Comment by weilyn** [comment]
建議以後不要修改排列順序，或是有修改順序時麻煩告知
因為會影響過去已經有使用裝飾區塊的套版
@liucwlewis  @Gabe-Liu
