### ISSUE TITLE
【問題】互動元件表單問題

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#457]
剛才在測試互動元件流程的時候發現，若在互動元件建立後並且設定完成(包含樣式、獎項與表單)，到後台去刻意刪除該元件的表單，再回到編輯區時表單會因為抓不到資料而呈現loading的狀態，進入表單管理時同樣也是無資料。
我的例子是幸運轉盤
<img width="328" alt="2018-07-02 10 53 14" src="https://user-images.githubusercontent.com/37531593/42143129-26c8da10-7de6-11e8-8973-e6130ee3f7db.png">
<img width="344" alt="2018-07-02 10 45 00" src="https://user-images.githubusercontent.com/37531593/42143162-579b07e4-7de6-11e8-9e20-a81522053cfe.png">
<img width="1019" alt="2018-07-02 10 45 09" src="https://user-images.githubusercontent.com/37531593/42143167-5d27691e-7de6-11e8-9a6a-00c97797e559.png">

建議是不是可以在發現表單資料被刪除後，元件上顯示“請先執行該元件表單的設計”的狀態，要求使用者要重新建立或選擇既有表單，感謝！
如下圖
<img width="330" alt="2018-07-02 10 51 18" src="https://user-images.githubusercontent.com/37531593/42143171-644ac77c-7de6-11e8-87c2-51621096aafc.png">

**Comment by ai015606220** [comment]
已修改，待日後上線
