### ISSUE TITLE
表單 手勢評分 預設選項

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#458]
第一次進去時
沒有跑出預設選項
使用起來感覺有點神祕
可以研究一下有沒有改善空間

![image](https://user-images.githubusercontent.com/10150807/42148629-97f725a6-7e05-11e8-8851-10b60a9c16b0.png)
![image](https://user-images.githubusercontent.com/10150807/42148663-b899045a-7e05-11e8-966d-eb375d7a9ee1.png)

**Comment by ryzojudy** [comment]
目前討論出來的結論如下：
在那一條上面會出現刻度
應該會比現在更容易知道它是可以被拖拉到該刻度進行選擇的
樣式包也會出幾種在A樣式中只有刻度，B樣式中會顯示所有項目的文字
再麻煩 @liucwlewis 出畫面
感謝~~~

**Comment by liucwlewis** [comment]
保留選項的刻度。第一次開啟時，會直接選取到第一個選項（要有選取時的過程動畫）。
<img width="335" alt="2018-07-25 2 32 24" src="https://user-images.githubusercontent.com/37163894/43183432-b46e49de-9017-11e8-96e3-4bdcf94d59f3.png">

**Comment by wilmaftliu** [comment]
<img width="882" alt="2019-01-30 3 35 58" src="https://user-images.githubusercontent.com/34560641/51965532-cc293580-24a4-11e9-885c-921fac252c1f.png">
建議在設定題目時
可以出現預設選項
讓使用者知道做出來的題目會長怎樣

甚至可以先讓他們預覽題目（good to have)
