### ISSUE TITLE
【問題】桌機模式選單顯示問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#461]
桌機模式選單已經刪除，編輯頁面中亦沒有出現
但預覽和發佈就會跑出來

![2018-07-02 5 00 57](https://user-images.githubusercontent.com/34327325/42154943-9e672a6c-7e19-11e8-9f4f-2e0e7c591251.png)

![2018-07-02 5 01 55](https://user-images.githubusercontent.com/34327325/42154957-a7b7e9bc-7e19-11e8-86e7-de4f31e05339.png)

**Comment by Gabe-Liu** [comment]
已解決
