### ISSUE TITLE
【問題】選單圖片上傳問題

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#462]
在選單架構裡想要上傳圖片，但是選擇圖片檔案(jpg ,png)之後沒有任何反應，不知道是不是只有我有問題，麻煩幫忙檢查一下，感激～
<img width="585" alt="2018-07-03 10 00 44" src="https://user-images.githubusercontent.com/37531593/42194813-54ed91de-7ea8-11e8-810f-d0a2a4ef083f.png">

**Comment by Gabe-Liu** [comment]
已解決
