### ISSUE TITLE
表單的日期時間題

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#464]
嗨～
表單的日期時間題
選擇時間的地方現在是“請輸入日期“
但應該是顯示"請輸入**時間**"～～

**日期題**
<img width="320" alt="2018-07-03 12 09 24" src="https://user-images.githubusercontent.com/34293268/42198437-91268b44-7eba-11e8-8382-0f986919535b.png">

**時間題**
<img width="321" alt="2018-07-03 12 09 05" src="https://user-images.githubusercontent.com/34293268/42198445-9e5cb37e-7eba-11e8-8633-9394a9abcc58.png">

還有一個小建議
因為日期和時間都是用”選擇“的
但填答提示是『 請”輸入“日期 』
建議可以改成 『 請”選擇“日期 』
比較不會造成使用者的誤會
謝謝～

**Comment by ai015606220** [comment]
已修正，等待上線中
