### ISSUE TITLE
【問題】幸運轉盤設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#468]
幸運轉盤的設定有分登入前與登入後
當我切換到登入後，做一些修改（例如文字顏色 大小之類的）
點選預覽的眼睛按鈕，再關掉預覽，

設定會停留在登入後，但是畫面已經跳回去登入前的編輯畫面了
容易讓人產生誤會

![2018-07-04 11 54 47](https://user-images.githubusercontent.com/34327325/42256048-6e1f3fd4-7f81-11e8-98a3-a80954c9a5e4.png)

**Comment by Gabe-Liu** [comment]
待下次更新
