### ISSUE TITLE
【問題】幸運轉盤獎項超出範圍

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#472]
這個問題以前提過

目前發現有時候會被裁切隱藏
有時候會直接超出去到隔壁隔

以文字跟圖片都是，因為這部分好像不能調文字大小
所以想弄清楚一下規則

![2018-07-04 3 46 46](https://user-images.githubusercontent.com/34327325/42263886-dfdb1c0e-7fa1-11e8-9c5c-fd8af0c357f0.png)
![2018-07-04 3 47 10](https://user-images.githubusercontent.com/34327325/42263887-e0047478-7fa1-11e8-9378-84cfab412d17.png)

**Comment by Gabe-Liu** [comment]
後面的獎項名稱與圖片如果超出範圍會覆蓋到前一個獎項的，
因此最後一個獎項會蓋到前一個與第一個，
此情況無法避免，只能在製作時看到而做調整
