### ISSUE TITLE
【問題】表單無法填寫

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#474]
剛剛測試，只要有出現這種圓圈選項的都會造成表單無法填寫

像是手勢選答、多選題（話說為什麼多選題是這種圖案，我以為是正方形）

目前只有在預覽模式測試

![2018-07-04 4 12 51](https://user-images.githubusercontent.com/34327325/42265100-2201553c-7fa5-11e8-8971-cb45c8f30662.png)

**Comment by ryuichl** [comment]
#471
