### ISSUE TITLE
【問題】表單逾期文字

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#475]
hi
表單逾期文字我設定了
但是沒有吃到我設置的文字內容

![2018-07-04 4 30 07](https://user-images.githubusercontent.com/34327325/42266313-a5d172d6-7fa8-11e8-819e-ed32b78d63a4.png)
![2018-07-04 4 36 35](https://user-images.githubusercontent.com/34327325/42266317-a81c250e-7fa8-11e8-9680-725627f6634d.png)

**Comment by weilyn** [comment]
有儲存了

**Comment by ai015606220** [comment]
已修正, 待日後上線
