### ISSUE TITLE
【問題】收縮區塊

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#476]
進入編輯模式插入元件沒反應

但按眼睛預覽會出現

**Comment by weilyn** [comment]
沒事 原來是沒展開就進入編輯模式

**Comment by weilyn** [comment]
但是沒展開的情況下進入編輯模式
插入元件以後會出現不知名的的區塊 ，要離開編輯模式以後
點選展開 才能看到是什麼

![2018-07-04 5 07 19](https://user-images.githubusercontent.com/34327325/42267917-d71e14d0-7fac-11e8-9710-1a812e2b8800.png)

**Comment by Gabe-Liu** [comment]
待下次更新
