### ISSUE TITLE
【建議】進入編輯模式

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#479]
希望要進入編輯模式的所有元件
在我主動按離開編輯模式以前，都不要讓我離開這個頁面
會跳出視窗要求我按離開編輯模式，或是自動離開編輯模式

不然使用者沒有離開的情況下
換到其他幻燈片繼續設計
會哭倒在地

**Comment by Samasianspock** [comment]
目前進入編輯模式時，必需要點擊“離開編輯模式”才能選取其他元件。
對於選取其他幻燈片的問題，將會規劃一個提示窗，請使用者離開編輯模式後才能切換幻燈片。
感謝回饋！

**Comment by Gabe-Liu** [comment]
剛跟weilyn討論後，決定再切換幻燈片時，自動把編輯模式關閉-
待下次更新
