### ISSUE TITLE
【表單失效】轉盤抽獎完填表表單出不來

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#480]
如題
<img width="1276" alt="2018-07-04 9 19 59" src="https://user-images.githubusercontent.com/34560641/42279379-2aa20148-7fd0-11e8-941c-d77f05c40f62.png">
看起來表單一直在loading出不來

**Comment by wilmaftliu** [comment]
直接製作表單就可以正常填寫 單純使用表單原件是沒有問題的

7/5週四早上10:00需要到企業簡報 
情況緊急
再麻煩盡快修復 感恩

**Comment by Gabe-Liu** [comment]
已解決
