### ISSUE TITLE
【建議】編輯模式時的範圍顯示

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#482]
希望進入編輯模式時有虛線顯示編輯區範圍
我們有幾個需要進入編輯模式的元件，建議在進入編輯模式時，以虛線的外框永久顯示該元件的範圍。
如圖-1 (編輯模式的範圍)
<img width="320" alt="default" src="https://user-images.githubusercontent.com/37531593/42298063-577f697e-8036-11e8-8f5e-9bd95ff77c9d.png">
目前只有編輯模式開始添增元件時虛線才會若隱若現，之前曾經建議在編輯模式以外的區域增加黑色遮罩的視覺效果，但似乎過於複雜，希望以顯示虛線的方式讓使用者了解編輯的設計範圍，另外建議在編輯模式，編輯區以外不相干的元件能夠有一層半透明白色遮罩，不讓其他元件影響作圖，能夠專注在編輯區內。
如圖-2 (編輯區外的元件加半透明遮罩)
<img width="500" alt="-" src="https://user-images.githubusercontent.com/37531593/42298083-8449a9ce-8036-11e8-9038-00d3813f85cb.png">

**Comment by Gabe-Liu** [comment]
待下次更新
