### ISSUE TITLE
【建議】上傳圖片被限制時的提示

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#484]
![upload_img](https://user-images.githubusercontent.com/11918396/42301244-d026a896-8046-11e8-9d84-e2f68e5e645d.png)
雖然圖片上傳旁邊的提示"?" 有註明上傳限制，但如果能在上傳圖片超過容量限制或不符合檔案類型時，出現對應的提示訊息，應該會更加明確。( 目前是一直卡在 Loading )

**Comment by Samasianspock** [comment]
@Kyle30 
請問有沒有所有狀態的清單，比如檔案過大、檔案類型不支援，或者其他上傳失敗的原因之類的，好用來顯示在提視窗裡面，去年有詢問過。

**Comment by Kyle30** [comment]
@Samasianspock  主要就是1.檔案大小超過限制(目前是10MB) 2.副檔名不支援 這兩種需要提示。
其他上傳失敗的原因，比較難事先界定。
