### ISSUE TITLE
【問題】表格欄列顏色設定問題

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#485]
目前遇到的狀況是設定表格的奇數或偶數的欄列顏色，畫布上不會顯示新設定的顏色，但是如果去開啟再關閉“開啟首欄列”的開關，設定的顏色就會出現。
後來發現開啟首欄列後，設定顏色也不會顯示。
<img width="650" alt="default" src="https://user-images.githubusercontent.com/37531593/42357221-69582a86-8109-11e8-89d9-56418659dd37.png">
<img width="650" alt="2" src="https://user-images.githubusercontent.com/37531593/42357259-9a3ef724-8109-11e8-93ec-fc5485749d63.png">

**Comment by ai015606220** [comment]
已修正, 待日後上線
