### ISSUE TITLE
【問題】幸運轉盤抽獎問題-再玩一次

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#486]
幸運轉盤如果沒有抽到獎品會有“再玩一次”的按鈕，但是按下按鈕後沒有反應，只能按關閉紐關掉提示。help~

![default](https://user-images.githubusercontent.com/37531593/42364350-667ba652-812d-11e8-934f-cf1870ea3273.PNG)

**Comment by Gabe-Liu** [comment]
待下次更新
