### ISSUE TITLE
【建議】幸運轉盤登入後

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#490]
希望中間開始抽獎的部分可以手動換行 例如兩個空白鍵
不然依現在情況，如果轉盤縮小、又或是使用者想要縮小文字，就會出現比較不美觀的換行方式

![2018-07-10 3 32 05](https://user-images.githubusercontent.com/34327325/42495796-b11cf41e-8456-11e8-97a5-0d604c94f41a.png)

**Comment by Gabe-Liu** [comment]
待下次更新 ( 註： 之前的轉盤需要重新設定一下按鈕!

**Comment by weilyn** [comment]
修改並上線完成時，再麻煩告知

**Comment by Gabe-Liu** [comment]
@weilyn  已更新上去
