### ISSUE TITLE
【問題】裝飾區塊順序

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#491]
HI，因為裝飾區塊順序調整
所以影響了先前的樣板內的裝飾區塊顯示，不過這部分我們已經著手在手動調整

比較有問題的是，先前已經上架的小積木也有使用到裝飾區塊的元件
所以許多的積木都出現一些奇妙的現象

謝謝

**Comment by ryzojudy** [comment]
按照現在WEBA上的順序(由左到右)
![image](https://user-images.githubusercontent.com/34263719/42622627-619e5e7a-85f3-11e8-913c-bc1e1754fd6f.png)
![image](https://user-images.githubusercontent.com/34263719/42622633-66142cf0-85f3-11e8-981f-5fc9657d3ece.png)

triangle
right triangle
circle
rectangle
rounded rectangle
parallelogram
trapezoid
star
6 point star
8 point star
radial
pentagon
hexagon
octagon
decagon
book mark
house
heart
gear1
gear2
chat cloud
badge1
ribbon1
ribbon2
ribbon3
arrow
banner
