### ISSUE TITLE
【建議】提示裏的編輯模式

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#493]
HI
在提示裡插入區塊輪播或是頁簽這一類型的元件時
在編輯過程會出現兩個離開編輯模式
容易使使用者混淆

![2018-07-13 9 15 29](https://user-images.githubusercontent.com/34327325/42667350-95dea9d0-867d-11e8-8075-7d4987ee8a9c.png)

**Comment by Samasianspock** [comment]
我們會在文字上敘述的更清楚，更改成「離開提示編輯模式」「離開頁籤編輯模式」，在點選「離開提示編輯模式」的話就是直接離開提示頁面，感謝回饋！
