### ISSUE TITLE
【問題】刮刮樂表單

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#495]
建立表單的部分
出現的的是建立轉盤表單

![2018-07-13 10 51 46](https://user-images.githubusercontent.com/34327325/42670018-26e21036-868b-11e8-9bed-874c70f0f88b.png)

**Comment by ryuichl** [comment]
@ryzojudy  這部分再麻煩你把相關文字都優化一下
感恩

**Comment by weilyn** [comment]
另外 為什麼 九宮格的表單可以連結幸運轉盤、以及刮刮樂的轉盤
是本來就打算做在一起的嗎
因為序號機是不可以共用的

**Comment by ryuichl** [comment]
@weilyn 
新加的這些互動背後都是轉盤邏輯
所以是可以共用的

**Comment by AnitaRyzo** [comment]
九宮格、幸運轉盤、戳戳樂、搖獎機、轉蛋機、刮刮卡、抽紅包、幸運餅乾、抽獎禮盒皆已修改如下
![image](https://user-images.githubusercontent.com/41721950/43750957-6ed1329a-9a2d-11e8-842a-bb41be844f09.png)

另外要求的序號表單敘述已修改如下
![image](https://user-images.githubusercontent.com/41721950/43751555-f6587a6e-9a2f-11e8-986a-69488022c2c0.png)

請知悉~

**Comment by AnitaRyzo** [comment]
20180820確認正式環境如上
