### ISSUE TITLE
【建議】裝飾圖案

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#497]
希望選取到的選項可以被圈選起來
增加使用者操作回饋

![2018-07-13 2 04 06](https://user-images.githubusercontent.com/34327325/42675254-cae7bec8-86a5-11e8-8c8e-d76fcfb19cd1.png)

**Comment by Samasianspock** [comment]
可以依照下圖的設定，除了右側要對應到畫布上的圖案之外，在圖示元件時，也應該要顯示使用中的圖示的正確分類位置，比如說畫布上使用的是「對話框」圖示，右側應該顯示，在「通訊」分類裡面第一頁的「對話框」圖示。
對應的設定除了可以讓使用者了解目前選取的圖案外，若想更換同分類中的圖示也可以更快速的切換。
顏色設定：在未選取狀態時請用 #878A8C (灰色) 選取狀態時用 #FFFFFF (白色)
<img width="640" alt="default" src="https://user-images.githubusercontent.com/37531593/42740734-dcec1a3a-88dd-11e8-9b62-800634a504a4.png">
