### ISSUE TITLE
【問題】請問待發布的專案要如何直接下架

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#498]
如圖，想讓待發布的專案在不發布的情況下直接取消

![2018-07-13 3 57 09](https://user-images.githubusercontent.com/34327325/42679777-b4ec7ad6-86b5-11e8-90fe-b2af36294d1b.png)

**Comment by ryuichl** [comment]
再申請一次審核
會跑到審核區
但如果已發佈就沒辦法了

**Comment by weilyn** [comment]
HI
我嘗試了以下操作
專案申請審核 > 設定 審核不通過 > 發現這些專案仍然在待發布裡

**Comment by ai015606220** [comment]
這個專案有曾經通過審核?
