### ISSUE TITLE
【問題】專案發佈設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#499]
目前的域名欄位，只要有輸入過任何字元
清空後就會出現不能存檔的情況

希望這道域名檢查程序只用在申請發布的部分，存檔則不受影響

![2018-07-13 4 24 21](https://user-images.githubusercontent.com/34327325/42681178-8e180354-86b9-11e8-846e-798177dd061c.png)

**Comment by ryuichl** [comment]
目前新開專案有打發佈名後再清空就無法儲存
這部分可能需要改一下 @Gabe-Liu 

至於已經發佈過後是否可以再把發佈域名清空
請 @ryzojudy  想一下
感恩

**Comment by ryzojudy** [comment]
編輯區的「專案開啟」拿掉

未發佈過的專案：
專案儲存時域名可儲存空值，申請審核域名不可為空

發佈中專案和下線的專案：
維持原樣，域名處不可為空

**Comment by weilyn** [comment]
哈囉，這部分的修改可以跟“進行中專案/已創建專案”的規則一起檢視
基本上進行中專案的定義明確我這邊就沒有異議

**Comment by weilyn** [comment]
#434

**Comment by ryzojudy** [comment]
可是這樣在編擊區就能把專案下線也很奇怪吧~
理論上專案所有的發佈跟下線都只能在發佈後台那邊操作

**Comment by ryuichl** [comment]
沒有
發佈的人只負責發佈
他沒有要去決定專案要不要下線
