### ISSUE TITLE
【建議】審核區的排序

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#500]
HI 目前專案申請審核後，會出現在審核區，一旦審核通過就會散落在待發布、及發布中的分類裡

目前主要的排序方法是以專案的創建日期為依據，建議可以增加“最近修改”為依據的排序方式
對於審核者比較容易找到需要更新發布的項目，目前雖然有顯示橘色燈號，
但數量一多其實不明顯，容易忽略

![2018-07-13 3 57 09](https://user-images.githubusercontent.com/34327325/42681447-495cbdf8-86ba-11e8-871e-ab807e83ad6a.png)

**Comment by ryuichl** [comment]
我看了一下目前排序裡有一個最近更新
這個排序是否不符合你的需求?

**Comment by weilyn** [comment]
希望在 以下四個區塊也能有最近更新的排序選項

專案審核
專案發布
套版審核
套版管理

**Comment by Gabe-Liu** [comment]
和roy討論後，決定有"最近更新"選項的
專案發布 - 依據橘色燈號為優先排序
套版管理 - 依據送出審核時間排序
