### ISSUE TITLE
【建議】九宮格獎項圖片與文字顯示

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#501]
由於我們沒有讓使用者上傳獎項圖片時可以裁切，會直接呈現圖片的原始尺寸乍看之下會有點凌亂。
建議獎項圖片的格子用固定的尺寸，比如說方形，使用者上傳圖片之後自動符合方形的範圍，如此一來就算獎項文字有換行，圖片至少看起來會是整齊的。
<img width="310" alt="2018-07-13 5 40 17" src="https://user-images.githubusercontent.com/37531593/42685162-d75d2034-86c4-11e8-9ad0-ce233e89d0b1.png">
獎項圖片固定的樣式可以參考下圖
<img width="201" alt="2018-05-28 2 15 18" src="https://user-images.githubusercontent.com/37531593/42685243-0af37ed4-86c5-11e8-9b01-8311318f866c.png">

**Comment by weilyn** [comment]
跑版參考2

![2018-07-16 9 15 38](https://user-images.githubusercontent.com/34327325/42740348-d5c04f7e-88d8-11e8-8ef2-3dcd65a919eb.png)
