### ISSUE TITLE
【建議】權限管理的帳號階層

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#502]
hi，
**1.建議在權限管理的部分，帳號階層旁可以新增一個“?”**
說明權限大小的排序規則，例如0最大，諸如此類，以及影響的範圍
雖然我們可以口頭告知管理人員規則，但人是容易遺忘的動物

**2.建議剛加入團隊的人，預設階層設定為5（或是更小）**
雖然在被給予權限以前，無法查看他人的專案，
但是管理者不熟悉系統時，若是忽略了階層的設定就給予了權限，就有專案被低位階的人查看的風險

![2018-07-16 9 23 43](https://user-images.githubusercontent.com/34327325/42740492-befc3ecc-88da-11e8-85d2-d1a8927a0ec0.png)

**Comment by ryzojudy** [comment]
1.**建議在權限管理的部分，帳號階層旁可以新增一個“?”**
氣泡窗文字：
階層的大小將會影響該帳號的查看權限，數字越小階層越高，最高階為0階，無最低階限制。可以查看團隊中比自己低階帳號的專案、表單回覆等資訊

2.**建議剛加入團隊的人，預設階層設定為5（或是更小）**
是否麻煩大德調一下預設的階層呢?不管是誰 預設的階層都改為5

第一點的部分需要麻煩 @liucwlewis 出圖

**Comment by ryuichl** [comment]
第二點不太同意
如果今天階層已經到10
結果新進的卻是5

**Comment by Samasianspock** [comment]
那有沒有可能我們預設最低是五5 ，一旦使用者自己有設階層，我們就自動偵測使用者的最低階層為預設呢？
比如說使用者設定10，那之後他們邀請的新成員階層就自動設為10呢？

**Comment by ryuichl** [comment]
老實說
很麻煩

**Comment by ryzojudy** [comment]
那可以把預設值拿掉嗎??

**Comment by ryuichl** [comment]
可以

**Comment by ai015606220** [comment]
@ryzojudy 請問你指的預設值是邀請成員進入團隊時的輸入框?

**Comment by ryzojudy** [comment]
??有點看不懂
我是指 在指定這個帳號權限時的那個輸入框 兩個是一樣的嗎??
![image](https://user-images.githubusercontent.com/34263719/43384228-f46c2a32-940f-11e8-8167-ef00b0fe1e9f.png)

**Comment by ai015606220** [comment]
![q1](https://user-images.githubusercontent.com/10190722/43384421-9710cef0-9410-11e8-845a-678c11f7f4d3.png)
流程上，第一次設定階層的地方是在邀請成員入團時

**Comment by ryzojudy** [comment]
後續應該是邀請進團隊的那個人 
或是有設定權限的人才會進入的畫面吧??
而且因為權限的預設都是關閉的
所以我想一開始沒有設定層集應該是沒有影響的

**Comment by ryuichl** [comment]
剛開始沒預設我同意
因為你又說同意邀請後的後續設定也要空白
這是兩個不同情況

**Comment by ryzojudy** [comment]
我們現在的流程
A邀請B -> B同意邀請 -> A設定權限 -> B可以使用
應該是這樣吧??

**Comment by ryuichl** [comment]
是

**Comment by ryzojudy** [comment]
關於第2點

**Comment by ryzojudy** [comment]
設定階層旁邊的白色圈圈
也要放第1點的問號
