### ISSUE TITLE
【建議】權限不足提示

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#503]
在我沒有建立專案權限的情況下，
當我點選了套版總覽，一樣可以進入查看套版的樣式
但是當我點選“使用此套版”的選項，沒有任何反應

建議可以跳出提示告知因為沒有權限所以不能套用樣板

![2018-07-16 9 31 57](https://user-images.githubusercontent.com/34327325/42740549-9b4d9a06-88db-11e8-9a8f-8035973e66ba.png)

**Comment by Samasianspock** [comment]
也許可以呈現「您沒有使用此套版的權限」文字描述的提示窗，沒有其他權限時也用此類提示窗。
