### ISSUE TITLE
【問題】互動元件無法創建表單

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#507]
如題 
除了表單本人、序號產生器以外
幸運轉盤 刮刮樂 九宮格這幾個用幸運轉盤邏輯的元件都無法正常建新表單

**Comment by Gabe-Liu** [comment]
剛跟 @weilyn 確認，暫時無法重新呈現出錯誤的畫面

**Comment by weilyn** [comment]
![2018-07-16 11 05 07](https://user-images.githubusercontent.com/34327325/42741815-21a2f34c-88e8-11e8-8acb-2549a2707f48.png)

**Comment by weilyn** [comment]
選擇已經存在的互動元件>建立表單
