### ISSUE TITLE
【區塊輪播-編輯時】建議 有明確的編輯區塊

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#51]
> 進入編輯模式時的範圍是否明確一點
 
雖已進入區塊輪播編輯模式，但加入的元件不在區塊元件範圍內也可拖曳 ，拖曳到非區塊輪播範圍時是否有提醒或明顯限制。
極容易導致使用時以為沒有編輯到區塊輪播元件，而拖曳到區塊輪播外的元件也會不在區塊輪播元件範圍內。以下例圖：
![default](https://user-images.githubusercontent.com/20262208/39690453-bf8c78fc-520c-11e8-8f65-72e70efd9966.png)

**Comment by Gabe-Liu** [comment]
目前會讓使用者在編輯時，無法操作外面的元件，至於遮罩就撓了我吧
