### ISSUE TITLE
【建議】表單管理介面收縮方式建議

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#510]
目前的表單管理頁 上中下共有三個區塊
1. （上）：指定表單概覽
<img width="1205" alt="2018-07-17 1 43 46" src="https://user-images.githubusercontent.com/34560641/42798714-98a9df7a-89c7-11e8-9f71-407b05f2d2ec.png">

2. （中）：所有表單一覽
<img width="1183" alt="2018-07-17 1 43 53" src="https://user-images.githubusercontent.com/34560641/42798720-a1d22850-89c7-11e8-8ba8-149608224d27.png">

3. （下）：表單收集資料
<img width="1182" alt="2018-07-17 1 43 59" src="https://user-images.githubusercontent.com/34560641/42798722-a82a02a4-89c7-11e8-88ff-ec1c1396f3ff.png">

如果螢幕夠大1、2、3區塊會一起呈現
但因為螢幕小的人 
只能同時看到 1、2 或 1、3
<img width="1276" alt="2018-07-17 1 42 27" src="https://user-images.githubusercontent.com/34560641/42798744-bf548ddc-89c7-11e8-819e-39fa47eba657.png">

<img width="1271" alt="2018-07-17 1 42 34" src="https://user-images.githubusercontent.com/34560641/42798748-c62d8398-89c7-11e8-81d5-10a8ad2d59a1.png">

但其實有時後在找專案的時候 如果可以同時看到2、3 會更加方便（1比較少用到）
但目前小螢幕的人只能透過收合開關的按鈕來切換
不是很方便

希望可以在收合時像專案管理頁一樣 能把1的部分完全收起來 方便同時觀看2、 3（當然專案管理頁沒有像表單管理一樣有分三個區塊啦 但是在表單管理頁中感覺1不是最常用到的 固定在上方相對可惜了觀看區域）
<img width="1212" alt="2018-07-17 1 48 39" src="https://user-images.githubusercontent.com/34560641/42798836-2728d418-89c8-11e8-9bb9-9f2cc4b61fdb.png">

<img width="1200" alt="2018-07-17 1 48 44" src="https://user-images.githubusercontent.com/34560641/42798879-50b92eb8-89c8-11e8-84c4-a48d3cc9f541.png">

歡迎提供看法與討論 

感謝

**Comment by ryzojudy** [comment]
路易斯已提供新畫面
再麻煩參考互動後台的收合方式 感謝~~
https://app.zeplin.io/project/59a919a5cb287bce8478d1b4/screen/5b57e05037ba623e150c8dde

**Comment by AnitaRyzo** [comment]
1、2、3區塊同時呈現
![image](https://user-images.githubusercontent.com/41721950/43751809-07b8475c-9a31-11e8-9bd2-95a13d12699f.png)

同時觀看2、 3
![image](https://user-images.githubusercontent.com/41721950/43751801-fc9c00ac-9a30-11e8-8d2b-69b54d415fc6.png)
20180807確認如上，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/44320424-8c314180-a474-11e8-933c-c73284714adf.png)
20180820確認正式環境如上
