### ISSUE TITLE
【許願】希望互動功能（如轉盤序號）驗證後 可收取以驗證的社群資料

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#511]
目前WEBA的互動功能都有社群驗證 （fb/ g+)
其實系統應該有收集這些驗證帳號的資料
希望未來互動功能的後台
除了收集用戶填寫的表單資料以外
也有一個清單列表收集這些經過驗證的社群帳號（社群帳號、綁定email或ID?)

目前南山產物、台新銀行等潛在客戶 有提過類似的需求

**Comment by ryuichl** [comment]
done
