### ISSUE TITLE
【建議】離開網站提示

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#512]
目前在編輯頁面之中，如果點擊“按鈕”的“外連網址”，在沒有設定開新視窗的情況下，會出現提示視窗
![2018-07-18 11 16 12](https://user-images.githubusercontent.com/34327325/42857371-30bde770-8a7c-11e8-8026-79dd3d96b49b.png)

但是如果連結是做在圖片、或是其他物件加上連結的屬性並且沒有設定開新視窗，在預覽模式中點選，會直接跳轉頁面（離開編輯頁）
建議只要是會直接離開系統的都能加上提醒視窗(像是編輯頁裏的預覽、專案管理區的預覽)

![2018-07-18 11 14 57](https://user-images.githubusercontent.com/34327325/42857457-845d460a-8a7c-11e8-8944-4df2b2b6390f.png)

**Comment by wilmaftliu** [comment]
不知這個issue後來是？

**Comment by Gabe-Liu** [comment]
在編輯畫面的預覽時，裡面的外部連結被點擊時會出現離開提示，是因為怕使用者尚未儲存設計的內容。
而至於在其他頁面時，則完整的呈現出功能，所以使用者點擊外部連結就直接讓他連出去了。

**Comment by weilyn** [comment]
提供一個使用情境

使用者在挑選套版的過程中>
點選到了套版裡的套版連結>
畫面轉跳到連結網址>
使用者點選上一頁回到編輯器>
重新在眾多套版中找到該套版

目前套版的解決方案是鼓勵使用開啟新視窗來做連結
但無法根本解決上述的不便之處

**Comment by Gabe-Liu** [comment]
預計 "加入離開提示" 來解決此問題
