### ISSUE TITLE
【建議】表單 手勢選答 輔助提醒

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#514]
目前的手勢選答 如果選的是「多提單頁」
看起來會跟一般的單選題呈現方式一樣 如果有多個問題的話 要換成「單題多頁」的方式才會有方向鍵頭
希望在設定題目時可以特別提醒一下使用者 手勢題建議多題單頁（一題一頁）
<img width="852" alt="2018-07-18 12 17 47" src="https://user-images.githubusercontent.com/34560641/42859098-a1079d5c-8a84-11e8-8887-19b7d43c973e.png">
<img width="847" alt="2018-07-18 12 17 52" src="https://user-images.githubusercontent.com/34560641/42859099-a130597c-8a84-11e8-90a6-3d4297ac4c1c.png">

**Comment by ryzojudy** [comment]
提示文字：
效果僅適用於單題多頁樣式，選擇多題單頁時自動轉換為單選題效果

在麻煩 @Samasianspock 幫忙出圖 感謝

**Comment by Samasianspock** [comment]
討論完後的規劃：
我們希望在題目編輯時在手勢題型旁邊，以提示窗的形式加註一個輔助說明：「效果僅適用於單題多頁樣式，選擇多題單頁時自動轉換為單選題效果。」
請參閱示意圖，感激！
<img width="1132" alt="2018-07-30 11 12 53" src="https://user-images.githubusercontent.com/37531593/43375805-dd5d251a-93e9-11e8-92c0-0a03fd79da88.png">
<img width="528" alt="2018-07-30 11 13 03" src="https://user-images.githubusercontent.com/37531593/43375810-e40e58d4-93e9-11e8-82ae-f75f1b81772b.png">

**Comment by wilmaftliu** [comment]
我覺得可以

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/43753322-c505ddc8-9a37-11e8-883f-35fdc760bb8d.png)

20180807確認以上內容，請知悉~

**Comment by AnitaRyzo** [comment]
20180820確認正式環境如上
