### ISSUE TITLE
【問題】抽紅包 抽完後呈現

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#516]
目前抽紅包時 一開始會呈現多個紅包讓你抽
<img width="436" alt="2018-07-19 10 02 08" src="https://user-images.githubusercontent.com/34560641/42917137-e40bd418-8b3a-11e8-9d26-5509f026fc6d.png">

但是當抽完後 填寫完資料 如果要再抽一次的話 畫面還是會出現那一個紅包袋
<img width="405" alt="2018-07-19 10 01 12" src="https://user-images.githubusercontent.com/34560641/42917156-f6ae1d1a-8b3a-11e8-842d-4aba920067fd.png">

即使抽獎次數設定為多次 流程中還是只能抽一次
只有重新整理後，才能回到多個紅包的畫面

不知道能不能在抽獎次數設定為多次時， 當用戶抽完獎項，填完資料按X時，回到多個紅包的話面

**Comment by AnitaRyzo** [comment]
#1097 
抽獎次數設定為多次時，若按下按鈕『再玩一次』會回到原始多個紅包畫面；若按下X時，回到單一紅包畫面。
以上補充，感恩~
