### ISSUE TITLE
電腦版 圖片解析度

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#517]
之前因為只有手機版
圖片尺寸在程式端限制了最寬只能800px

現在因為多了電腦版
@ryzojudy 麻煩想一下怎麼因應
和界面上怎麼操作

感恩

**Comment by weilyn** [comment]
此外，目前上傳的照片因為壓縮，所以經過裁切後，即使點選重設，也會變成比原本小的照片，
我們已經回不去了～

**Comment by liucwlewis** [comment]
連結：https://zpl.io/VKlZ9lR
icon連結：https://drive.google.com/open?id=1ExtawkWhB2AJwNsS1us4gmjbPSv1VeGp
https://drive.google.com/open?id=1-3s1OG6KFpfM5SGt1tQhsxyrAxFHb0yw

**Comment by ryuichl** [comment]
是不是可以考慮直接在上傳圖片的下面讓他可以選擇是否不要壓縮
![image](https://user-images.githubusercontent.com/10150807/45341065-b685a300-b5cb-11e8-9911-5d57b275131b.png)
如果是點了上傳才選擇感覺有點麻煩
因為大部分都是要壓縮
@ryzojudy  @liucwlewis

**Comment by liucwlewis** [comment]
剛討論後調整成這樣～～～

<img width="277" alt="2018-09-11 3 51 48" src="https://user-images.githubusercontent.com/37163894/45346040-a6c18b00-b5da-11e8-93c4-cd58c43f665d.png">

網址：https://zpl.io/a3l57qN

**Comment by AnitaRyzo** [comment]
在上傳圖片時可以選擇兩種方式：一般上傳(原始尺寸) & 壓縮上傳
![image](https://user-images.githubusercontent.com/41721950/45478105-c345fa80-b775-11e8-8557-071e8a7cdde8.png)
壓縮且裁切後，點選『重設』，照片會回覆原始畫面
![image](https://user-images.githubusercontent.com/41721950/45478545-c7264c80-b776-11e8-870f-18773202c328.png)
◎◎ 20180913確認以上測試環境內容 ◎◎
