### ISSUE TITLE
【建議】互動元件獎項預設

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#518]
如同幸運轉盤元件，獎項設定裡已經預設四個獎項，為協助以及引導使用者設定獎項(他們可以更直接地發現可以上傳獎項圖片)，希望其他互動元件也可先預設一個獎項和圖片，如下圖。
<img width="907" alt="2018-07-20 3 37 04" src="https://user-images.githubusercontent.com/37531593/42989934-c95dcee2-8c33-11e8-8a67-b2de64a27cfb.png">
<img width="127" alt="2 2x" src="https://user-images.githubusercontent.com/37531593/42989967-e9f59676-8c33-11e8-99a9-99a78be4c17b.png">

也避免在沒有設定獎項時預覽刮刮卡看不到獎項的狀況。
除了轉盤與九宮格已經有特別的預設之外，其他抽獎元件希望都可以預設一個獎項。

**Comment by Samasianspock** [comment]
另外獎項名稱現在是顯示「雙擊編輯名稱」，建議放入右邊的括號裡面，預設一個「獎項一」之類的文字，不然畫布上會顯示「雙擊編輯名稱」會讓人誤會可以直接在畫布上編輯。
如下圖的第二張
<img width="600" alt="2018-07-20 4 23 08" src="https://user-images.githubusercontent.com/37531593/42992181-67c82176-8c3a-11e8-8db0-0b4dc22b5691.png">

**Comment by Gabe-Liu** [comment]
上次討論結果為，其他互動元件預設一個未兌獎的選項 至於圖片應該不需要預設一個
