### ISSUE TITLE
【問題】團隊顯示不完全

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#519]
目前我所在5個團隊中，
但是其中「業務部」這個團隊在上方下拉選單裡有，
但在下方團隊框框裡卻沒有
請大人明察（登出重整後還是一樣）
<img width="1119" alt="2018-07-20 4 15 26" src="https://user-images.githubusercontent.com/34560641/42991554-84d810d4-8c38-11e8-8189-bc6507966f0c.png">

**Comment by ai015606220** [comment]
我看最右邊是有滾軸出現了，往下滾應該就會出現

**Comment by wilmaftliu** [comment]
真的耶 果然在下方
不過感覺往下滾好像不是很直覺 如果團隊很多往下卻一次只能看一排好像視窗有點小
如果可以往右滾 不知道是不是比較順？

提供參考 感謝回答
