### ISSUE TITLE
【問題】刮刮卡 獎品圖後的背後靈

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#521]
如下圖 上傳完圖片後 在刮獎時 刮完出現圖片以外  還會有一個黑底白線條的圖片壓在背後

<img width="404" alt="2018-07-23 2 51 39" src="https://user-images.githubusercontent.com/34560641/43061472-19883276-8e88-11e8-8da9-a8e9f2bd59cd.png">
<img width="322" alt="2018-07-23 2 50 16" src="https://user-images.githubusercontent.com/34560641/43061479-1b520366-8e88-11e8-9439-abfb41cda18d.png">

編輯區的預覽 和發佈後 都有這東西

**Comment by ai015606220** [comment]
因為預設圖片的位置有變動，已調整待日後上線
