### ISSUE TITLE
【問題】無法建立序號

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#522]
加入序號機元件後 點選建立序號機 卻出現這個畫面
<img width="325" alt="2018-07-23 3 20 53" src="https://user-images.githubusercontent.com/34560641/43062669-307170de-8e8c-11e8-863b-a78703cd8077.png">
點選啟用序號機後 會顯示 「無權限」
<img width="325" alt="2018-07-23 3 22 29" src="https://user-images.githubusercontent.com/34560641/43062706-46b65a80-8e8c-11e8-99e5-e51c9b789e27.png">
求解求解

**Comment by Gabe-Liu** [comment]
待下次上線更正
