### ISSUE TITLE
【問題】刮刮樂獎品圖以及遮罩圖能否置中？

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#523]
1.刮刮樂獎品圖以及遮罩圖能否置中
很明顯藍色的獎品圖歪掉惹～～～
<img width="507" alt="2018-07-23 3 44 25" src="https://user-images.githubusercontent.com/34876672/43063907-f88ba6cc-8e8f-11e8-899a-f250c607ce23.png">

2.獎項設定那邊說空白格兩下就是換行，但是顯示出來沒有ㄛ
我有空兩格
<img width="331" alt="2018-07-23 3 46 50" src="https://user-images.githubusercontent.com/34876672/43063953-151d8c88-8e90-11e8-9036-463d6e5d12bd.png">

顯示這樣
<img width="484" alt="2018-07-23 3 46 05" src="https://user-images.githubusercontent.com/34876672/43063936-0a1a7f76-8e90-11e8-8ec1-d7a4241dbbba.png">

**Comment by Gabe-Liu** [comment]
文字換行部分 我已修正  待下次更新

**Comment by ai015606220** [comment]
@ryzojessie 可以請你提供這張上傳的圖嗎?
