### ISSUE TITLE
樣版總覽排序

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#529]
建議比較新的放上面

![image](https://user-images.githubusercontent.com/10150807/43116809-24861dbe-8f3c-11e8-8d39-404dfea6ed4e.png)

**Comment by ryzojudy** [comment]
同意~ @Samasianspock 你的意見呢?

**Comment by AnitaRyzo** [comment]
已確認越新的套版放在越前面
![image](https://user-images.githubusercontent.com/41721950/44322257-1383b280-a47f-11e8-8f06-64a37dc37deb.png)
20180820確認正式環境如上
