### ISSUE TITLE
【頁籤元件和收縮區塊元件】- 進入編輯時，console 報錯一直出現

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#53]
`新增頁籤元件或收縮區塊元件進入編輯時，有時候會有以下錯誤：`
如例圖：
![error](https://user-images.githubusercontent.com/20262208/39690838-07595c80-520e-11e8-93e2-31670965875c.png)

> PS.建議：

當【頁籤元件和收縮區塊元件】 內容很多的時候，會佔編輯版面很多的空間，是否可控制收放?

**Comment by Gabe-Liu** [comment]
暫時玩不出來
