### ISSUE TITLE
【建議】表單管理 回覆列表的搜尋功能 可加放大鏡圖示

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#531]
在表單管理中查看回覆列表時，各個欄位上有一個搜尋功能（圖示為三條槓），建議可以把圖示改成放大鏡，這樣可以更清楚的傳達此圖示的功能。
<img width="667" alt="default" src="https://user-images.githubusercontent.com/37531593/43123419-af3bce6c-8f56-11e8-955f-be2d2e9ff6b1.png">

**Comment by liucwlewis** [comment]
icon連結：https://drive.google.com/file/d/0B7J75LWx4nupcXBkMnMxR3g2RWM/view?usp=sharing

**Comment by AnitaRyzo** [comment]
各個欄位上的搜尋功能，圖示已改成放大鏡
![image](https://user-images.githubusercontent.com/41721950/44020161-93f39ce4-9f13-11e8-8282-8a1d77d8ee8a.png)

20180813確認以上測試環境的內容，請知悉~

**Comment by AnitaRyzo** [comment]
搜尋功能的圖示已改成放大鏡
20180820確認正式環境如上
