### ISSUE TITLE
【問題】輪播區塊

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#533]
三頁以上的輪播區塊
左右的<,>反應有點遲緩
例如已經跳到最後一頁了，>的圖案還是呈現可以點擊的的黑色，只是點了沒有反應
或是在第二頁的時候，其實還有第三頁，但是>呈現不能點擊的灰色，
要等待一下才會正確顯示

目前設定值是有開啟自動播放，不知是否有影響

![2018-07-25 9 39 45](https://user-images.githubusercontent.com/34327325/43174924-2cb4151e-8fef-11e8-8793-acf1dee222a2.png)

**Comment by Gabe-Liu** [comment]
發現如果輪播區塊裡的輪播圖沒有使用箭頭時，會導致影響到外層的輪播區塊  - 待下次修正
