### ISSUE TITLE
【建議】互動遊戲前的社群驗證可開關

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#535]
目前的互動功能因為避免多次領獎所以綁定社群帳號驗證
建議可以設定開關 如果使用者在辦活動時不在乎有人重複領獎/玩遊戲，也不需要收取社群個資時
可以將驗證的社群綁定關閉

**Comment by wilmaftliu** [comment]
像是亞太電信目前的活動
其實是希望透過互動（刮刮卡）可以吸引用戶進來玩遊戲 
抽出的獎項事實上是需要付費申辦來電答鈴才能擁有的優惠折扣
這時候抽中獎項的同時 客戶是需要付出一定成本的

這個活動的流程是：
客戶玩刮刮卡 抽中獎項 --> 填寫亞太門號 申請人名字電話生日後 --> 後續由東捷匯出Excel開通

所以如果他們亂用名字去重複領獎
沒有亞太門號 也一樣無法開通

所以這時候亞太端就會希望將活動進入門檻放低 讓大家都可以來玩 來抽獎


希望這個情境有幫助了解 ：Ｄ

**Comment by wilmaftliu** [comment]
補充活動連結 https://pop94.ittscrm.com.tw

**Comment by ryuichl** [comment]
所以一個人可以領100個答鈴?

**Comment by wilmaftliu** [comment]
可以在活動辦法裡說明「一人只能領取一組答鈴 如果重複申請也只視為一組 」這樣的資訊
有明確訂好遊戲規則就好

**Comment by ryuichl** [comment]
所以這個刮開可以抽到甚麼?
來電答鈴打8折?

**Comment by wilmaftliu** [comment]
提供7首排行榜最狂冠軍K歌每月自動更新

**Comment by ryuichl** [comment]
所以優惠折扣是?

**Comment by wilmaftliu** [comment]
買五送一？

**Comment by ryuichl** [comment]
妳是說我有6首來電答鈴
每次隨機播放?

**Comment by wilmaftliu** [comment]
不是 是買五個月的來電答鈴 送你第六個月的來電答鈴 每月都有七首隨機播放

**Comment by ryuichl** [comment]
所以只有一個獎項?

**Comment by wilmaftliu** [comment]
目前我們收到的獎項是這一個 其他的要再跟亞太確認 
說起來其實他是把優惠活動包進互動遊戲裡 並不完全是真的要送你東西

但希望去玩的人可以降低門檻 這樣去領取這樣的優惠的人就會更多

**Comment by ryuichl** [comment]
聽完還是不太同意
這樣根本就假優惠阿

**Comment by wilmaftliu** [comment]
我覺得我們不應該去限制使用者要怎麼使用這些元件
如果自由度越高 他們可以將這些元件做的變化就越多

同時我們去拜訪的許多企業 都會問到「可不可以將驗證拿掉？」的問題
凱基銀行 宏泰人壽 亞太電信 膳魔師 其實都有問過這樣的問題

我覺得這應該是可以讓客戶自行去決定的 如果這麼多企業都想要利用WEBA的元件功能做假優惠
因為他們在給客戶玩遊戲的時候都只是一種手段 那也是他們的選擇

**Comment by ryuichl** [comment]
我認為他們會問這樣的問題
是因為他們還不了解機制和背後原理

**Comment by wilmaftliu** [comment]
其實以亞太這個客戶來說 我們已經有將上述問題跟他們溝通過了 
現場在介紹時也清楚讓他們了解做這樣的驗證的目的
但是為了可以讓大部分的人可以先玩過留下資料 再來做篩選 以獲得大量的用戶名單 
他們認為在玩之前要加一個驗證機制 會大幅降低用戶來體驗這個遊戲的動力
所以才希望把這個機制拿掉

對他們來說
寧願有很多人進來玩 就算最後有重複名單再另外篩選掉
也不要因為有了這個機制 導致本來想玩的人卻都跳走了

還是有其他方式 可以先讓用戶玩遊戲、取得獎品，如果要領獎再來登入驗證資料？
有可能將順序調整嗎？

**Comment by ryuichl** [comment]
我覺得這已經牽扯到其他層面了
以這個例子來說
如果進到這網頁的人都可以拿到優惠
那刮刮樂這樣的方式是否真的好
還是其實有更好的方式

**Comment by wilmaftliu** [comment]
ＯＫ沒問題 感謝

**Comment by ryzojudy** [comment]
	於右側控制欄多一個【開啟社群驗證】的開關鈕
-	開啟：抽獎設置出現
-	關閉：抽獎設置消失，狀態提示頁【身份驗證】、【已達抽獎上限】、【中獎記錄】、【尚無抽獎記錄】這四頁無法設定

![image](https://user-images.githubusercontent.com/34263719/48173017-015a3780-e33d-11e8-83d5-aef07d84e8fa.png)

![image](https://user-images.githubusercontent.com/34263719/48173032-11721700-e33d-11e8-88a9-b9f576bfe9ea.png)
