### ISSUE TITLE
（東捷帳號）複製專案 發布後掉圖

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#536]
掉圖的專案網址：[https://pop94-2.ittscrm.com.tw](https://pop94-2.ittscrm.com.tw)
原專案網址：[https://pop94.ittscrm.com.tw](https://pop94.ittscrm.com.tw)

截圖如下
<img width="447" alt="2018-07-25 2 54 13" src="https://user-images.githubusercontent.com/34876672/43184361-e7cd68ca-901a-11e8-8c94-08312845dab2.png">
<img width="441" alt="2018-07-25 2 54 23" src="https://user-images.githubusercontent.com/34876672/43184362-e7fde982-901a-11e8-8aa3-c502d402ae68.png">

**Comment by weilyn** [comment]
剛剛重新發布仍然沒有正常顯示
再麻煩協助處理

>找jessie

**Comment by Kyle30** [comment]
處理中

**Comment by ryuichl** [comment]
done
