### ISSUE TITLE
【問題】搖獎機的球顏色

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#539]
搖獎機跳出來的球在"預覽"時會依照【設定獎項】內的【對應顏色】跳出相對應獎項的球，但是在瀏覽器上，是跟著背景變換。
![2](https://user-images.githubusercontent.com/41721950/43245991-da805c4a-90e2-11e8-82fd-6c1fad67bcff.jpg)

若【背景設定】內的【背景顏色】是單色且無上傳圖片，顯示與【背景顏色】同色的球。
![1](https://user-images.githubusercontent.com/41721950/43245976-d17e7f28-90e2-11e8-8f37-836f30158646.jpg)

若【背景設定】內的【圖片上傳】有照片時，顯示透明球。
![3](https://user-images.githubusercontent.com/41721950/43245986-d60e6116-90e2-11e8-8cc5-972615b4506b.jpg)

請協助確認球是否都該依照【設定獎項】內的【對應顏色】顯示呢? thx!

**Comment by Gabe-Liu** [comment]
待下次更新
