### ISSUE TITLE
【404 頁面-編輯時】- 有的設定是否需要?例如錨點、大轉盤、序號機等等...

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#54]
在設計 【404 頁面】時，404頁面設定錨點也無法連結到404頁面。建議在編輯 _404頁面_ 時 不能加入特定的某些元件，如大轉盤、序號機、錨點等元件。

**Comment by ryzojudy** [comment]
文字、圖片、按鈕、影片、地圖、圖示、社群追蹤、線段、小工具

**Comment by Isabella-Zheng** [comment]
圖示、社群追蹤、線段、小工具 之後有的功能會在追加上去 :+1:
