### ISSUE TITLE
【建議】分享示意可以完全顯示

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#541]
![image](https://user-images.githubusercontent.com/36216073/43300559-7ab97fd4-9192-11e8-8d59-78d6da0e0de5.png)
在進行預覽時，分享示意在Facebook的部分需要滑動才可以完全看完示意圖
建議可以減少上方手機預覽部分的文字，或更改它的排版方式
讓分享示意可以完全顯示，不需滑動即可看完他全部的樣貌

**Comment by wilmaftliu** [comment]
建議QR下方的文字可以縮減，或是位置移到QR右側。

**Comment by ryzojudy** [comment]
QR下方文字不建議再縮減
需要麻煩 @liucwlewis @Samasianspock 幫忙協助 畫面是否可以再優化
好讓分享圖能完全顯示
感謝~~

**Comment by liucwlewis** [comment]
位置：https://zpl.io/VK0WnDR
修正後，盡量增加了預覽的範圍，但還是無法避免使用者如果真的輸入大量文字時依然會被擋到的問題。
<img width="1091" alt="2018-08-06 2 56 36" src="https://user-images.githubusercontent.com/37163894/43701539-2abb7754-9989-11e8-8954-416df5f9454e.png">

**Comment by wilmaftliu** [comment]
不知道這個issue目前的進度是？ 
看起來UI已經改好 想知道工程的進度 感謝

**Comment by AnitaRyzo** [comment]
示意圖顯示如下
![image](https://user-images.githubusercontent.com/41721950/45478834-6e0ae880-b777-11e8-99ce-1143e76dc70c.png)
◎◎ 20180913確認以上測試環境內容 ◎◎
