### ISSUE TITLE
【問題】手機預覽部分跑版

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#542]
在縮放比例100%的狀況下，手機預覽的部分跑版，如下圖所示~
![image](https://user-images.githubusercontent.com/36216073/43301527-5760df7c-9198-11e8-95e6-b06cb6b79e78.png)

**Comment by AnitaRyzo** [comment]
『預覽』已無跑板
![image](https://user-images.githubusercontent.com/41721950/43752594-50bcbe30-9a34-11e8-994b-fed2df0c2e12.png)
20180807確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
20180820確認正式環境如上
