### ISSUE TITLE
【建議】表單後台 刪除凍結直欄功能 或是可以自定義凍結欄位

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#543]
因為凍結左側欄 導致右側觀看與往右滑動的區域變小
希望可以將這一欄刪除
或是開放可以編輯哪些欄目可以凍結
#332

**Comment by ai015606220** [comment]
@wilmaftliu 目前是互動元件的表單遇到這個問題嗎?

**Comment by AnitaRyzo** [comment]
黃色框線代表凍結的欄位，紅色框線為側拉式顯示資料
上圖為舊有凍結左側欄(互動原件)，凍結『選取資料』、『活動名稱』、『獎項or序號』、『已兌獎』四個欄位；下圖為改版後，僅凍結『選取資料』。
![image](https://user-images.githubusercontent.com/41721950/43761263-2dbf0384-9a57-11e8-8818-2b85a227434b.png)

20180807確認以上內容，請知悉~

**Comment by AnitaRyzo** [comment]
下圖為改版後，僅凍結『選取資料』
![image](https://user-images.githubusercontent.com/41721950/44322793-b76e5d80-a481-11e8-8e3d-e9419974c444.png)
20180820確認正式環境如上
