### ISSUE TITLE
【建議】表單後台 調整欄寬的小槓槓左右兩側的空間縮減

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#544]
現在調整欄寬的小直槓 拖曳後可以調整欄寬
可是這個方便的小胖子佔用了太多空間
導致很快選單標題就變「...」
希望可以幫他減肥 縮減左右兩側預留的空間
供參考
感謝
預祝減肥成功
<img width="136" alt="2018-07-27 2 52 40" src="https://user-images.githubusercontent.com/34560641/43306216-004daea8-91ad-11e8-9e22-6b141def0632.png">

**Comment by AnitaRyzo** [comment]
調整欄寬的小直槓已從24px剩下10px囉!
![image](https://user-images.githubusercontent.com/41721950/43753116-c9994e34-9a36-11e8-93a1-c52d5b8f6508.png)
20180807確認以上內容，請知悉~

**Comment by AnitaRyzo** [comment]
欄寬的小直槓已瘦身
![image](https://user-images.githubusercontent.com/41721950/44323140-2bf5cc00-a483-11e8-944d-99d66834fe85.png)
20180820確認正式環境如上
