### ISSUE TITLE
【問題】表單後台 點擊收縮區時 無法呈現下方清單內容

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#546]
原本表單後臺長這樣
<img width="1210" alt="2018-07-27 4 09 24" src="https://user-images.githubusercontent.com/34560641/43309482-7748b016-91b7-11e8-9d83-cb55e5aad2de.png">
當我點擊下方的收縮按鈕時 雖然表單框們被收起來了
但是下方的清單無法呈現 如下圖
<img width="1209" alt="2018-07-27 4 05 33" src="https://user-images.githubusercontent.com/34560641/43309444-639b2e7c-91b7-11e8-8cdb-6cf28762046f.png">
等了很久還是沒有出現ＱＡＱ

但是當我把收縮按鈕再次點擊的那個瞬間 下面的清單又一秒出現

請協助小螢幕族群 我知道預計會新增最上方也可以收縮的按鈕 不過如果縮起來後還是無法觀看 
可能還是要設法解決
感恩

**Comment by ryuichl** [comment]
我試了是正常的
你現在還是有這情況?

**Comment by wilmaftliu** [comment]
我現在還是有這個情況

**Comment by wilmaftliu** [comment]
@Gabe-Liu 有看過 他覺得這是bug

**Comment by wilmaftliu** [comment]
sorry 是 @ai015606220 看過

**Comment by ai015606220** [comment]
不是螢幕大小的問題，是上半部縮起來之後，表格那邊沒有重新計算高度

**Comment by AnitaRyzo** [comment]
左邊為測試環境，右邊為正式環境
正式環境在小框架時，容易無法出現清單資料(如右圖)
測試環境無論收縮按鈕如何配置，都會有資料
![image](https://user-images.githubusercontent.com/41721950/44127349-84cadb30-a06f-11e8-96d4-d55458f5d63f.png)

20180815確認以上測試環境的內容，請知悉~

**Comment by AnitaRyzo** [comment]
無論收縮按鈕如何配置，都會有資料
![image](https://user-images.githubusercontent.com/41721950/44323833-22219800-a486-11e8-87a1-fcc3d14e200d.png)

20180820確認以上正式環境內容!
