### ISSUE TITLE
【建議】獎項圖片建議制定固定尺寸

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#547]
在互動元件中，「恭喜中獎」以及「中獎紀錄」狀態由於圖片會因為大小不同而擠壓到其他內容，有些可能會被推出畫布範圍外，建議圖片尺寸固定，就不會有圖中的狀況發生，感謝！
<img width="1033" alt="2018-07-27 5 22 17" src="https://user-images.githubusercontent.com/37531593/43313783-a72d4222-91c3-11e8-8d4d-3eeefbdbd32f.png">

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
『恭喜中獎!』的指定尺寸是337x310
![image](https://user-images.githubusercontent.com/41721950/44325037-189a2f00-a48a-11e8-8c9c-7ee7b7b3e8c9.png)
『中獎紀錄』的指定尺寸是263x310
![image](https://user-images.githubusercontent.com/41721950/44325318-11275580-a48b-11e8-9d9c-75ca0936eaf3.png)
20180820確認以上正式環境內容!
