### ISSUE TITLE
【問題】圖片上傳

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#548]
出現錯誤提醒視窗以後

無法再次上傳

![2018-07-30 11 38 35](https://user-images.githubusercontent.com/34327325/43376400-30d68bac-93ed-11e8-83f2-aae1c8198c62.png)

![2018-07-30 11 38 19](https://user-images.githubusercontent.com/34327325/43376406-33f7e0a6-93ed-11e8-8871-a9087c9261dd.png)

**Comment by AnitaRyzo** [comment]
『支援格式大小不超過10MB』的提示訊息只會出現三秒，爾後就可重新選擇『上傳』或『刪除』。
a. 圖片與刮刮卡的設定版本
![image](https://user-images.githubusercontent.com/41721950/43762489-a12e2c3e-9a5a-11e8-95d7-1fe3325503f0.png)

b. 搖獎機、刮刮卡、轉蛋機、幸運餅乾、抽獎禮盒的版本
![image](https://user-images.githubusercontent.com/41721950/43761782-a4e5570a-9a58-11e8-9ee2-616d65f8562f.png)

c. 幸運轉盤、戳戳樂、九宮格、抽紅包的版本
![image](https://user-images.githubusercontent.com/41721950/43761818-be83ce26-9a58-11e8-83f5-0ba6060abd28.png)
20180807確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
『支援格式大小不超過10MB』的提示訊息只會出現三秒，爾後就可重新選擇『上傳』或『刪除』。
20180820確認以上正式環境內容!
