### ISSUE TITLE
【抽獎禮盒】的樣式預覽 & icon需要更換

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#549]
抽獎禮盒的樣式預覽沒有出現
<img width="956" alt="2018-07-30 11 42 13" src="https://user-images.githubusercontent.com/34293268/43376626-5c5192da-93ee-11e8-9283-96e1c10d1883.png">

還有現在的icon是舊的
新的長相是這樣
<img width="581" alt="2018-07-30 11 49 29" src="https://user-images.githubusercontent.com/34293268/43376666-a31f2d30-93ee-11e8-8810-4a5e04c896a9.png">

可以到這裡下載：https://drive.google.com/drive/u/2/folders/0B7J75LWx4nupdFVKMTBvT0JZRDA

-------------------------------------------------------------------------------------------------
同場加映

現在刮刮卡 & 抽獎禮盒的 icon顏色比其他元件深 
預設顏色應該是#afafaf 
還有hover的時候 顏色應該是白色 #ffffff 
以下圖片說明
<img width="176" alt="2018-07-30 11 42 29" src="https://user-images.githubusercontent.com/34293268/43376710-dfd21594-93ee-11e8-84c5-15f7dac8454b.png">
<img width="177" alt="2018-07-30 11 43 18" src="https://user-images.githubusercontent.com/34293268/43376719-e35656b2-93ee-11e8-96c1-b4151058109e.png">

再協助修改～感恩！

**Comment by AnitaRyzo** [comment]
抽獎禮盒的樣式預覽如下所示
![image](https://user-images.githubusercontent.com/41721950/43764039-eb2208a2-9a5e-11e8-81e3-0af0292eaf77.png)

PS: 刮刮卡 & 抽獎禮盒的 icon顏色尚未修改：預設顏色為#afafaf
20180807確認以上內容，請知悉~

**Comment by AnitaRyzo** [comment]
左邊為測試環境，右邊為正式環境
已確認刮刮卡 & 抽獎禮盒的 icon顏色與其他元件相同
![image](https://user-images.githubusercontent.com/41721950/44020782-9789956e-9f15-11e8-9395-c5f698aa5b74.png)

20180813確認以上測試環境的內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
抽獎禮盒的樣式已有樣式一
已確認刮刮卡 & 抽獎禮盒的 icon顏色與其他元件相同
![image](https://user-images.githubusercontent.com/41721950/44327062-2e125780-a490-11e8-8bf5-780f6cb4ed48.png)

20180820確認以上正式環境內容!
