### ISSUE TITLE
【問題】抽獎禮盒的獎項與圖示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#555]
※抽獎禮盒問題一：獎項覆蓋※

1. 先設定第一個抽獎禮盒(三個禮盒)
![image](https://user-images.githubusercontent.com/41721950/43439962-1ea31f00-94c8-11e8-80f9-564c3d0a8391.png)
1-1. 在瀏覽器執行後出現獎項如同設定
![image](https://user-images.githubusercontent.com/41721950/43440051-67736168-94c8-11e8-8d10-fffc29748f36.png)

2. 複製幻燈片，重新設定抽獎禮盒(六個禮盒)的獎項
![image](https://user-images.githubusercontent.com/41721950/43440114-a96d957a-94c8-11e8-8537-a6704a79d2ed.png)
2-1. 在瀏覽器執行後，獎項全部如同後設的禮盒
![image](https://user-images.githubusercontent.com/41721950/43440147-d2764d54-94c8-11e8-9037-66dc6bd33fc6.png)

※抽獎禮盒問題二：圖片顯示※
禮物盒在IE上會有鋸齒狀唷!
![image](https://user-images.githubusercontent.com/41721950/43440261-3bf5870e-94c9-11e8-8644-5fd92ef953af.png)

以上請協助確認，謝謝~

**Comment by ai015606220** [comment]
關於第二點，是由於透明背景的png在ie上會有格式支援上的問題

**Comment by ai015606220** [comment]
目前第一點由Gabe加上 '幻燈片複製同時清空互動元件id' 的功能

第二點因為直接換成svg檔在截圖時會有問題，採取做法為編輯頁使用png，預覽、正式頁面使用svg

**Comment by AnitaRyzo** [comment]
不論是在同一張幻燈片複製出多個『抽獎禮盒』，或是直接複製已有多個『抽獎禮盒』的幻燈片，畫布都會顯示『尚未建立抽獎禮盒』。

直接選互動原件的幸運餅乾
![image](https://user-images.githubusercontent.com/41721950/43815682-803f963a-9b03-11e8-8881-f82ed818e683.png)

"複製幻燈片"或"點選後複製"的幸運餅乾
若點選"啟用抽獎禮盒"，所有內部設定會與前一個禮盒相同，但後設定的獎項不會覆蓋前一個禮盒的。
![image](https://user-images.githubusercontent.com/41721950/43815637-421d67b0-9b03-11e8-80af-f4086fa9fa36.png)

已確認在手機版與電腦版瀏覽器(Chrome、Firefox、Opera、IE)上，圖示都不會有鋸齒狀的
![image](https://user-images.githubusercontent.com/41721950/43815420-2eaea3de-9b02-11e8-81f2-849ec74fd869.png)
20180808確認以上內容，請知悉~

**Comment by AnitaRyzo** [comment]
20180820確認以上正式環境內容!
