### ISSUE TITLE
【問題】在 IE執行會有差異的部分X6

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#556]
前提：右邊是IE畫面，左邊是其他瀏覽器

※刮刮樂：只要有做"切換幻燈片"的動作，雖然可以按下『開始』按鈕，但無法執行刮開。
http://uat-era.ryzoweba.io/

※選單：矩陣式選單顯示方式有差別
![image](https://user-images.githubusercontent.com/41721950/43443781-79fbd6d8-94d4-11e8-8bfc-7558f8bed919.png)

※地圖：無法顯示google地圖
![image](https://user-images.githubusercontent.com/41721950/43443743-59882da2-94d4-11e8-9ec8-011aa57e2a01.png)

※序號機：提示訊息被截斷
![image](https://user-images.githubusercontent.com/41721950/43443828-9491b422-94d4-11e8-948c-6792f68ac91e.png)

※九宮格：圖示與文字一起顯示時，整個格式會跑掉
![image](https://user-images.githubusercontent.com/41721950/43443856-b0714a40-94d4-11e8-9fb7-006fa88cf4c6.png)

※中獎訊息：中間圖案尺寸是626X626，畫面跑掉；最右邊尺寸是300X300，畫面在中間。
![image](https://user-images.githubusercontent.com/41721950/43443451-7bd2670c-94d3-11e8-9005-4ce8adf54988.png)

以上請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
地圖問題 已解決

**Comment by ai015606220** [comment]
https://github.com/philipwalton/flexbugs

**Comment by Gabe-Liu** [comment]
選單問題：ie11 不支援某屬性，因此改用別的屬性作替代

**Comment by Gabe-Liu** [comment]
九宮格問題 已解決

**Comment by Gabe-Liu** [comment]
序號機問題 已解決

**Comment by AnitaRyzo** [comment]
※選單：矩陣式選單顯示相同
![image](https://user-images.githubusercontent.com/41721950/43874853-8eb2c0f8-9bc0-11e8-9fad-8adffadc819c.png)

※地圖：可顯示google地圖
![image](https://user-images.githubusercontent.com/41721950/43874945-266812ae-9bc1-11e8-8335-fc9dcd6fef61.png)

※序號機：提示訊息可完整顯示
![image](https://user-images.githubusercontent.com/41721950/43875092-da4d93f2-9bc1-11e8-9416-f836eac1f1f7.png)

※九宮格：圖示與文字可完整顯示
![image](https://user-images.githubusercontent.com/41721950/43875151-05ec8a4a-9bc2-11e8-9c0b-7004584d16ab.png)

※中獎訊息：中間圖案尺寸是626X626，畫面位置相似。(已測試九個互動元件)
![image](https://user-images.githubusercontent.com/41721950/43875339-a3029e50-9bc2-11e8-8d1a-e97053045577.png)
※中獎訊息：中間圖案尺寸是300X300，畫面位置相似。(已測試九個互動元件)
![image](https://user-images.githubusercontent.com/41721950/43875464-1a560bcc-9bc3-11e8-92f1-1fc603ebcc05.png)

20180809確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
選單、地圖、序號機訊息、九宮格圖文、中獎訊息如下圖
![image](https://user-images.githubusercontent.com/41721950/44379356-24dcc580-a538-11e8-97ca-1880bb438283.png)

![image](https://user-images.githubusercontent.com/41721950/44379318-f232cd00-a537-11e8-800e-36ddd334fd74.png)

![image](https://user-images.githubusercontent.com/41721950/44379305-da5b4900-a537-11e8-913c-6a6afdfc3238.png)

![image](https://user-images.githubusercontent.com/41721950/44379217-79337580-a537-11e8-8474-bb7bf8bf3d27.png)
20180821確認以上正式環境內容!
