### ISSUE TITLE
互動元件登出按鈕流程與設定

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#557]
所有抽獎類的互動元件除序號機以外，編輯時皆在狀態頁「中獎紀錄」、「尚無抽獎紀錄」加入登出按鈕。(詳見圖三、圖四)
**抽獎登出流程：** 使用者參與抽獎活動時，點擊中獎紀錄圖示查看紀錄以及選擇登出按鈕「切換帳號」後跳轉至身份驗證(社群)登入頁面，讓使用者再次登入。
(詳見圖一)
![default](https://user-images.githubusercontent.com/37531593/43443625-ff31f0a4-94d3-11e8-891b-c39c6a56fd0e.jpg)

**規劃：** 將登出鈕結合在「中獎紀錄」中是在用戶的抽獎紀錄功能上附加一種帳號管理的意象。由於各大主流軟體介面的使用情境，通常會把用戶的帳號設定(登出或管理帳號)、紀錄以及其他狀態集中於一個圖示內(通常是「人像、 ⋯、≡」等圖示)，舉凡購物App、社群App、Youtube、IG、Pinterest等皆有相似設計，因此把登出鈕放入抽獎紀錄畫面中比較不會違背一般人的使用習慣。
(詳見圖二)
![default](https://user-images.githubusercontent.com/37531593/43443677-27b8d1a0-94d4-11e8-9cfc-5b625f057e2f.jpg)
**抽獎類互動元件**
**編輯區：** (圖三、圖四)
**顯示資訊：** 登出鈕預設為顯示狀態，使用者可以取消勾選隱藏登出按鈕。
按鈕設定新增頁籤「兌換」與「登出」。
「兌換」按鈕文字：填寫資料；「登出」按鈕文字：切換帳號。
![- 01-1](https://user-images.githubusercontent.com/37531593/43443765-67d67558-94d4-11e8-98f1-daaaa8f676de.jpg)
![- 01-2](https://user-images.githubusercontent.com/37531593/43443772-6e04592c-94d4-11e8-9a21-8f5d3180bfb7.jpg)

**序號機**
在「已兌換」狀態頁中加入登出按鈕，由於序號沒有抽獎紀錄，故將登出鈕放置於上一次取得兌換序號的畫面「已兌換」下方。
**序號登出流程：** 使用者取得序號與QR Code關閉提示窗，再次點擊序號機按鈕時，顯示上次的序號與QR Code ，此時出現登出鈕才允許使用者切換帳號。
(詳見圖一)
**序號機編輯區：** (詳見圖五)
顯示資訊：登出鈕預設為顯示狀態，使用者可以取消勾選隱藏登出按鈕。
「登出」按鈕文字：切換帳號。
![- 02](https://user-images.githubusercontent.com/37531593/43443843-a2607e9e-94d4-11e8-9b7e-3ed1b2d9229a.jpg)

**規劃：** 主要是希望使用者先取得序號後才能切換帳號。
登出按鈕的預設文字顯示「切換帳號」是希望使用者在心理上能再產生參加活動的欲望。

**Comment by ryuichl** [comment]
兩點問題
1. 目前設計的畫面 使用者無法知道目前的帳號 是否可將大頭貼和名字加進去畫面
2. 序號不能事前換帳號有點神秘

**Comment by Samasianspock** [comment]
之前我們有想過這種形式，在標題下方有一塊是有大頭貼與社群ID的樣子，在編輯區就再加上id 的文字設定。
<img width="341" alt="2018-07-31 5 07 11" src="https://user-images.githubusercontent.com/37531593/43449937-3aeee72c-94e4-11e8-8b2c-90b38615c8b8.png">
至於序號機目前還沒有好的解決方式，會再思考。

**Comment by ryuichl** [comment]
印象中目前這頁是無法滑動的
這樣可能會太多東西

**Comment by Samasianspock** [comment]
有兩種紀錄的狀態忘記補充：
1.中獎尚未填表狀態
2.完成填表的狀態
所以應該不會像上面那張過於擁擠得狀態，個別的間距也可再調整。
<img width="727" alt="2018-07-31 5 25 01" src="https://user-images.githubusercontent.com/37531593/43451091-b9378db2-94e6-11e8-99d7-af6c1196a3e2.png">

**Comment by ryuichl** [comment]
你們有初步定案後
我們再統一開會討論一次
感恩
