### ISSUE TITLE
【問題】手勢選答在不同"頁面設定"下有差異

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#559]
手勢選答在設定問題時，明確要求上下左右的選項
![image](https://user-images.githubusercontent.com/41721950/43447683-953d3e78-94de-11e8-8cf6-4a02775227a6.png)

但在『頁面設定』選擇『多題單頁』後，顯示方法只是排列
![image](https://user-images.githubusercontent.com/41721950/43447891-11b5b098-94df-11e8-83b1-30970a091c7d.png)

以上請協助確認，謝謝~

**Comment by ai015606220** [comment]
#514
