### ISSUE TITLE
【序號機 - 發佈後】答題完，換取序號成功畫面關閉後，畫面無法關閉完全

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#56]
不是經常發生，測試時只發生過一次。
> 如附圖：

![qrcode](https://user-images.githubusercontent.com/20262208/39691655-d83db75e-5210-11e8-8714-9d1a1d643eeb.png)

**Comment by Gabe-Liu** [comment]
暫時遇不到此情況
