### ISSUE TITLE
【提問】複製互動元件時的狀況

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#560]
複製幸運轉盤或九宮格的時候
樣式和表單資訊都需要重新設定
<img width="561" alt="2018-08-01 10 38 13" src="https://user-images.githubusercontent.com/34293268/43498444-90a7723e-9579-11e8-9331-5feb059cb348.png">

<img width="564" alt="2018-08-01 10 39 15" src="https://user-images.githubusercontent.com/34293268/43498451-96baf1f0-9579-11e8-9199-32e64036b529.png">

其他互動元件目前沒有這個情況
樣式和表單資訊都有保留
如下圖
<img width="557" alt="2018-08-01 10 40 04" src="https://user-images.githubusercontent.com/34293268/43498475-afa09300-9579-11e8-8bcb-703d73ccabab.png">

----------------------------------------------------------------------------------------------------

比較後可以看到
這兩類互動元件複製後的操作流程不太一樣
可能幸運轉盤還有九宮格可以設計的地方比較多
所以採取現在這種做法(可以選擇曾經做過的)
但如果今天只是想要複製前一個設計好的元件
就感覺操作流程有點卡(也很困惑)

同樣都是互動元件的話是不是統一比較好?(純屬疑問)
再麻煩解惑～感謝～～

**Comment by ai015606220** [comment]
#554

**Comment by ryuichl** [comment]
目前複製有一個已經問題
待修正後操作流程會統一
