### ISSUE TITLE
【問題】幸運餅乾顯示結果

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#561]
幸運餅乾在抽獎已經達到次數上限的情況下

關閉了提示視窗，再次點選幸運餅乾圖案，會抽出空白的紙條
好像應該要持續顯示已經達到次數上限

![2018-08-01 12 15 20](https://user-images.githubusercontent.com/34327325/43500880-2e5fc91c-9585-11e8-9da3-a42f9da542af.png)

**Comment by ai015606220** [comment]
#553
