### ISSUE TITLE
【問題】輪播圖調整順序

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#562]
放置在輪播區塊裡的輪播圖無法調整圖片順序

單獨使用的輪播圖則正常

![2018-08-01 12 23 43](https://user-images.githubusercontent.com/34327325/43500991-e8b7b11c-9585-11e8-9b28-b26ff7af36cc.png)

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
20180820確認以上正式環境內容!
