### ISSUE TITLE
【問題】抽獎禮盒 預覽圖

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#564]
不知道有沒有提過
新增抽獎禮盒時的樣式圖是空白的

![2018-08-01 4 10 32](https://user-images.githubusercontent.com/34327325/43509804-3eba8a9c-95a6-11e8-8c50-4eb8ceddd3e3.png)

**Comment by ai015606220** [comment]
#549

**Comment by ryuichl** [comment]
抓包 都不先爬文
