### ISSUE TITLE
【問題】收縮區塊狀態

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#565]
目前專案裡的收縮區塊，預設好像都是展開狀態

![2018-08-01 4 59 16](https://user-images.githubusercontent.com/34327325/43511977-6e697644-95ac-11e8-82ae-ec2777387684.png)

**Comment by Gabe-Liu** [comment]
目前的收縮區塊更改為按照"收縮狀態"做呈現，
並不會一直是縮合的狀態~

所以使用時要多加注意
