### ISSUE TITLE
專案發佈頁面的載入

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#567]
這頁真的每次進去都很慢
是否可以優化?
猜想是否因為有類似全部預覽圖都LOAD到才顯示的設定

![image](https://user-images.githubusercontent.com/10150807/43556404-3c97bd0c-9632-11e8-9616-758f69b12d0c.png)

**Comment by ai015606220** [comment]
![q](https://user-images.githubusercontent.com/10190722/43557436-2abed4b2-9637-11e8-84ee-1b57122b7b1a.png)

目前看起來專案數太多會造成取得的資料大的太多，預覽圖的load不會影響到載入的速度

**Comment by ryuichl** [comment]
那個api拿到後
會用到裡面的structure嗎?

**Comment by ai015606220** [comment]
有些地方有用到 structure_prod，structure沒有

structure_prod主要是用來判斷是否為 '[]' => 未發布過

**Comment by weilyn** [comment]
套版管理，可以設定標籤的那個頁面也很慢～
