### ISSUE TITLE
【問題】最近更新的排序依據

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#568]
hello
上次有在系統的各個專案欄位加上最近更新的排序方法了
只是目前使用上還是有一些問題
例如其實我剛剛編輯的是以下這個畫面的的專案
![2018-08-02 10 37 06](https://user-images.githubusercontent.com/34327325/43559512-e45cb5de-9640-11e8-8499-f8bfedf0c369.png)

但是當我選擇最近更新時，他反而跑到第30個了

![2018-08-02 10 38 05](https://user-images.githubusercontent.com/34327325/43559514-e6b9873a-9640-11e8-9892-760a33251ee5.png)

**Comment by Gabe-Liu** [comment]
@weilyn 專案管理的最近更新是依照"發佈時間"

**Comment by weilyn** [comment]
ok 了解

**Comment by ryzojudy** [comment]
收到~我來看看

**Comment by ryzojudy** [comment]
@Gabe-Liu 請問在專案管理這一邊的"最近更新"
有辦法改成是依據 最近編輯 的判斷方式嗎?

**Comment by ryuichl** [comment]
目前程式內是沒有這樣的設計
要的話等有空再加

**Comment by ryzojudy** [comment]
好喔 沒問題~
希望在 專案管理的最近更新是根據 最近編輯
在發佈管裡那邊的最近更新就還是根據 最近發佈

**Comment by wilmaftliu** [comment]
目前將舊的專案重新編輯並發佈更新後發現
即使將排序方式換成「最近更新」時
排序方式竟然是以「有更新過的專案」中，以「創建日期」整齊地排序
<img width="1277" alt="2018-08-27 10 03 50" src="https://user-images.githubusercontent.com/34560641/44664312-71973380-aa45-11e8-9dc4-2581b2c95456.png">
如果是以最近更新時間排序的話 專案標題上的創建日期應該會是亂的
所以這個排序方式仍然不是以「最近更新時間」排序

煩請查明
這樣的排序是否圖文不符

**Comment by AnitaRyzo** [comment]
5. 表單管理
![image](https://user-images.githubusercontent.com/41721950/45479436-140b2280-b779-11e8-8e9d-0c39a4afdccc.png)

6. 互動後台管理
![image](https://user-images.githubusercontent.com/41721950/45479675-b62b0a80-b779-11e8-822d-cfcbfe0a1255.png)
◎◎ 20180913確認以上測試環境內容 ◎◎
