### ISSUE TITLE
【問題】手機APP執行有異  x7

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#569]
手機瀏覽器的六款APP：
Chrome for ios 68.0、Firefox 12.2、Safari 10.3、Line 8.11、facebook 183.0、EDGE 42.3.6

1.『連結』有設定開啟新分頁，但執行時不是開新分頁
有此異常的APP：Line 8.11、facebook 183.0

2.『臉書工具(動作&嵌入)』完全未呈現
有此異常的APP：Firefox 12.2
![img_1190](https://user-images.githubusercontent.com/41721950/43560699-5ab0ec28-9646-11e8-8858-eb0cdebaff37.PNG)

3.『圖示』被點選沒變"被選取的顏色"，而是配合框線樣示出現灰色框
有此異常的APP：全部
![image](https://user-images.githubusercontent.com/41721950/43560628-047f3a62-9646-11e8-9449-e26540f49a38.png)
![image](https://user-images.githubusercontent.com/41721950/43560744-8e8b0bbe-9646-11e8-9a18-a1543983ec56.png)

4.『幸運轉盤』樣示2的中間箭頭不見了
有此異常的APP：全部
![img_1188](https://user-images.githubusercontent.com/41721950/43560586-cb37b9a0-9645-11e8-9e65-08cb04eaa29a.PNG)

![img_1189](https://user-images.githubusercontent.com/41721950/43560584-cade158a-9645-11e8-8ba5-2f6ded0be21b.PNG)

6.『轉蛋機』上方桶子的球不會滾動
有此異常的APP：全部

7.『刮刮卡』若有多個幻燈片，刮的時候容易就被換幻燈片了
有此異常的APP：全部

以上請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
1.『連結』有設定開啟新分頁，但執行時不是開新分頁 -  此問題為app內建瀏覽器的機制，沒法更改。

**Comment by Gabe-Liu** [comment]
問題.3 已解決

**Comment by Gabe-Liu** [comment]
問題4. 已解決

**Comment by Gabe-Liu** [comment]
問題6 已解決

**Comment by Gabe-Liu** [comment]
問題2. 手機版火狐有自動開啟追蹤保護，因此會看不到，如果要看到，要自行開啟

**Comment by Gabe-Liu** [comment]
問題7. 已解決

**Comment by AnitaRyzo** [comment]
2. Firefox 12.2的『臉書工具(動作&嵌入)』，要開起追蹤保護才會出現
![image](https://user-images.githubusercontent.com/41721950/43830118-2666f3d0-9b33-11e8-8eaf-1100f7a21f70.png)

3.『圖示』在APP上被點選，在APP中都會隨"被選取的顏色"變化
4.『幸運轉盤』樣示2的中間箭頭，在APP中都會出現了
6.『轉蛋機』上方桶子的球，在APP中都會滾動了
7.『刮刮卡』若有多個幻燈片，刮的時候容易就被換幻燈片了
解法：在刮刮卡的圖片尺寸內不會換頁

20180808確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
20180821確認以上正式環境內容!
