### ISSUE TITLE
【問題】轉蛋機不能設定獎品數量？

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#570]
為什麼轉蛋機不能設定獎品數量？

**Comment by wilmaftliu** [comment]
發現是預設獎項不能設定數量 因為預設是文字設定「銘謝惠顧」 所以兌換的開關被關起來了
建議預設獎項改成可以兌換的獎品 避免誤會

**Comment by wilmaftliu** [comment]
同意 那再麻煩在數量設定的旁邊加一個（？）提醒使用者要將兌獎功能開啟

**Comment by ryzojudy** [comment]
那就麻煩加提醒文字在獎品數量旁
文字：獎品數量在右上角兌獎開關開啟時才可設定
再麻煩 @eatinggg 出圖了~

**Comment by liucwlewis** [comment]
位置：https://zpl.io/VDzRRRw
任何情況下提示都會顯示
<img width="721" alt="2018-08-06 5 13 56" src="https://user-images.githubusercontent.com/37163894/43708073-21f97644-999c-11e8-990c-53674af04d27.png">

**Comment by AnitaRyzo** [comment]
提示訊息如下所示
![image](https://user-images.githubusercontent.com/41721950/46463403-64185a80-c7f6-11e8-8494-678899ac7c97.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
提示訊息如下所示
![image](https://user-images.githubusercontent.com/41721950/47278946-7c161980-d5ff-11e8-93cd-7a4e6d72b048.png)
◎◎ 20181022確認以上正式環境內容 ◎◎
