### ISSUE TITLE
【問題】手機無法執行Opera的app

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#571]
手機無法執行Opera的app，會出現以下提示訊息
![img_1191](https://user-images.githubusercontent.com/41721950/43562507-94693872-964f-11e8-9237-f8ad6b2b4464.PNG)

以上請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
原本用isInApp套件來判定瀏覽器是否內建在app裡，理論上opera應該要和chrome、firefox是要為false，但opera mini卻得到的是true，所以才會出現提示。
因此我打算用navigator.userAgent取值來判定是否為opera mini，但沒想到取的值裡，沒有跟opera名稱有關的可以用來做判定.....
![s__7733250](https://user-images.githubusercontent.com/9190672/43564298-beac3298-9658-11e8-875a-3f15968f8819.jpg)

再研究看看有什麼值可以獲取到opera mini

**Comment by ryuichl** [comment]
https://bitsofco.de/better-detection-and-analytics-for-opera-browsers/

**Comment by ryuichl** [comment]
決定先把OPERA MINI的支援取消
之後有需要再研究
