### ISSUE TITLE
【問題】數據分析

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#572]
以下兩個區塊出現重複的選項，並且總和超過100%

期間沒有重新發佈或編輯內容

![2018-08-02 2 26 33](https://user-images.githubusercontent.com/34327325/43566285-811f5cfe-9660-11e8-9862-b3ba2881b3b9.png)

**Comment by Gabe-Liu** [comment]
剛跟 @weilyn 檢查後，發現此情況沒再出現， 因此先關閉
