### ISSUE TITLE
【問題】在Edge執行有異 X2 

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#573]
1.『選單』矩陣式選單顯示方式有差別
![image](https://user-images.githubusercontent.com/41721950/43570356-adb970ae-966c-11e8-9bcb-6f59e2dc81f9.png)

2.『下拉式』沒有出現卷軸
![image](https://user-images.githubusercontent.com/41721950/43570361-b4052a34-966c-11e8-90ad-a2da30088b6d.png)

以上請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
問題1 已解決

**Comment by ai015606220** [comment]
問題2 已解決

**Comment by AnitaRyzo** [comment]
矩陣式選單顯示如下
![image](https://user-images.githubusercontent.com/41721950/43880775-5d8429e2-9bdc-11e8-8a36-7dc6275375ae.png)

『下拉式』已有卷軸
![image](https://user-images.githubusercontent.com/41721950/43880732-264d6e84-9bdc-11e8-9b1e-2ebeab367081.png)
20180809確認以上內容，請知悉~

**Comment by AnitaRyzo** [comment]
矩陣式選單顯示已正確，『下拉式』已有卷軸。
20180821確認以上正式環境內容!
