### ISSUE TITLE
【問題】序號機若選擇 選擇序號機 無法建立表單

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#575]
選擇 選擇序號機會出現下圖的樣子，而且無法儲存表單

![image](https://user-images.githubusercontent.com/36216073/43575578-c19c5e4e-9679-11e8-9619-53839483710c.png)

**Comment by ryuichl** [comment]
選擇序號機
選的是已經建立過的序號機
確實無法新建表單

至於無法儲存目前沒有測出類似狀況
可能需要更多使用流程細節

**Comment by AnitaRyzo** [comment]
建立序號機，產出序號，活動名稱First 
─ 不論是否完成建立新表單
─ 不論是否刪除 First的活動序號
─ 不論新增或是複製序號機
─ 不論是選擇 First的活動序號，或是產生新的活動序號
皆出現以下畫面
![image](https://user-images.githubusercontent.com/41721950/43818723-7a72153e-9b12-11e8-9fa7-ca6fe4c149ac.png)
20180808確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
20180820確認以上正式環境內容!
