### ISSUE TITLE
【建議】序號機執行程序

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#576]
目前序號機程序為
![image](https://user-images.githubusercontent.com/41721950/43620014-34d5f648-9703-11e8-88c5-e2d75df7dd1c.png)

表單顯示的內容如下，『活動名稱』、『序號』與『已兌換』的欄位會被空下。
![image](https://user-images.githubusercontent.com/41721950/43620043-5b03ba80-9703-11e8-8de3-2f7487fbcfb0.png)

※建議是否更改程序如下圖，不讓重複登入的使用者重複填寫表單
![image](https://user-images.githubusercontent.com/41721950/43620167-ef406d74-9703-11e8-8aaa-6bcd0fa934d6.png)

請協助處理，謝謝~

**Comment by ryuichl** [comment]
待登出流程實做後
會一併改善

**Comment by AnitaRyzo** [comment]
已確認按照綠色程序執行序號機
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已確認按照綠色程序執行序號機
◎◎ 20181123確認以上正式環境內容 ◎◎
