### ISSUE TITLE
【問題】內嵌程式碼與網頁在手機APP執行時的異常

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#577]
手機瀏覽器的六款APP：
Chrome for ios 68.0、Firefox 12.2、Safari 10.3、Line 8.11、facebook 183.0、EDGE 42.3.6

內嵌程式碼在手機的六款APP執行時，沒有下拉式表單，故資料會被截掉 。
![image](https://user-images.githubusercontent.com/41721950/43621233-efe1665c-9708-11e8-99ff-1c477b3d72ed.png)

內嵌網頁在手機的Safari 10.3、Line 8.11執行時，版面會跑掉
![image](https://user-images.githubusercontent.com/41721950/43621303-391c5cc8-9709-11e8-99d7-a8ea3aca08aa.png)

以上請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
內嵌程式碼j問題 - 已解決

內嵌網頁問題 - 跑版問題解決，但在IOS上有另一個問題，當滑動時，不時會跳回內嵌網頁的最上面
