### ISSUE TITLE
【問題】抽獎寶箱出現錯誤代碼

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#578]
專案預覽都還正常會顯示，也可以抽獎
發布後都不行，出現錯誤代碼，小熊也沒有跑出來

<img width="456" alt="2018-08-03 12 16 55" src="https://user-images.githubusercontent.com/34876672/43624023-56bcc4e4-9717-11e8-997f-9eacc6b143ec.png">
<img width="454" alt="2018-08-03 12 17 05" src="https://user-images.githubusercontent.com/34876672/43624024-583e7164-9717-11e8-94a7-709831ab9c23.png">

**Comment by AnitaRyzo** [comment]
是否在『編輯名稱』沒有資料呢??
![image](https://user-images.githubusercontent.com/41721950/43624249-b8176374-9718-11e8-834d-dc7fed61c93a.png)

**Comment by ryuichl** [comment]
看了後台你有一次獎項沒名字
目前設定是一定要有名字
之後會加驗證

**Comment by ryzojessie** [comment]
哦哦 好 所以全部都要有名字就對了
好ㄛ 感謝 我試試看

**Comment by ryzojessie** [comment]
有ㄛ～～～ 恢復正常了～～～～～謝謝～～～～～～～～～

**Comment by AnitaRyzo** [comment]
【九個互動元件】的獎項名稱
若完全不輸入字元，會跳回設定前的資料，至少要輸入一個字元(空格也可以)
紅色圖框是輸入的資料，黃色圖框是顯示的資料
![image](https://user-images.githubusercontent.com/41721950/43819814-dd5a6332-9b16-11e8-93e5-b93738e63911.png)

20180808確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
【九個互動元件】的獎項名稱皆確定至少要有空格，否則會跳回原字串
20180821確認以上正式環境內容!
