### ISSUE TITLE
【問題】序號機的提示頁“活動時效”的活動時效設定，主題命名修正

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#579]
序號機的提示頁“活動時效”的活動時效設定，兩個標題“抽獎尚未開放”、“抽獎已結束”的“抽獎”改為“活動”
![2018-08-03 4 19 05](https://user-images.githubusercontent.com/37163894/43632579-26d66cea-9739-11e8-929e-9971bbf450f9.png)

**Comment by AnitaRyzo** [comment]
序號機的提示頁“活動時效”已修正如下
![image](https://user-images.githubusercontent.com/41721950/43820858-fc71f282-9b19-11e8-849e-6f67daf32b0f.png)

其餘互動元件(幸運轉盤、九宮格、戳戳樂、搖獎機、刮刮樂、轉蛋機、抽紅包、幸運餅乾)未變動如下
![image](https://user-images.githubusercontent.com/41721950/43820939-3e64bc4c-9b1a-11e8-96c8-98abf3bdbae9.png)
20180808確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
20180821確認以上正式環境內容是相同的!
