### ISSUE TITLE
進入專案編輯時，會有頁面編輯區閃現一下

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#58]
> 如附圖

![default](https://user-images.githubusercontent.com/20262208/39691846-858af7dc-5211-11e8-9139-80b4cce3b96c.png)

閃現完後即進入編輯畫面。

**Comment by ryuichl** [comment]
試了一下
有按儲存後就會有這狀況發生
大概是因為截圖沒清掉的關係?

**Comment by Gabe-Liu** [comment]
有增加loading畫面，等放至線上後看有無改善
