### ISSUE TITLE
【問題】帳號管理

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#580]
可能跑板了

![default](https://user-images.githubusercontent.com/34327325/43692307-6950ecea-9959-11e8-90db-74d73ffe952d.PNG)

**Comment by ryuichl** [comment]
可能跟團隊數目有關吧
待專人確認

**Comment by wilmaftliu** [comment]
<img width="1208" alt="2018-08-07 1 33 23" src="https://user-images.githubusercontent.com/34560641/43756287-7f63837e-9a46-11e8-8a60-aa7228650dad.png">
團隊太多時無法團隊太多時無法往下滑 或是左右滑 超出來的團隊會在畫面外 要把比例調小才會出現

**Comment by wilmaftliu** [comment]
<img width="1279" alt="2018-08-08 2 05 21" src="https://user-images.githubusercontent.com/34560641/43819155-5f9dedf8-9b14-11e8-8df5-3e7c1dcdbb6e.png">
跑版問題依舊存在 請問大概什麼時候會好呢？ 明天8/9及下週一8/13將有兩場大型簡報 請協助盡快修正 感謝

**Comment by wilmaftliu** [comment]
@Gabe-Liu

**Comment by AnitaRyzo** [comment]
左側標題跑版：已修改，如紅色框線
團隊超出頁面：已增加，如綠色框線的側拉式捲軸
→ 新增問題1：最後一個團隊只能顯示一半的名稱，如黃色框線
→ 新增問題2：頁面標示的字樣重疊，如藍色框線
![image](https://user-images.githubusercontent.com/41721950/43822572-12896f96-9b1f-11e8-89ed-6357e0e34835.png)
20180808確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
正式環境顯示內容如下
左側標題如紅色框線，已正常顯示
團隊超出頁面如綠色框線，已增加側拉式捲軸
頁面標示的字樣如藍色框線，已完整顯示
![image](https://user-images.githubusercontent.com/41721950/44374892-50a18080-a523-11e8-9918-ea67106bdbdf.png)
最後一個團隊可利用側拉式捲軸完整顯示
20180821確認以上正式環境內容!
