### ISSUE TITLE
【問題】帳號管理-團隊管理按鈕跑版

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#581]
<img width="530" alt="2018-08-06 11 29 34" src="https://user-images.githubusercontent.com/34560641/43695620-4a09b70a-996c-11e8-9dc5-6696b2d09104.png">
帳號管理裡面的「團隊管理」按鈕跑版 變成直式
如果按「個人帳號」又會變正常
但是按回「團隊管理」就又變窄了

**Comment by ryuichl** [comment]
#580
