### ISSUE TITLE
【疑問】輪播圖的『輪播設定』中的『背景顏色』

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#582]
『輪播圖』的『輪播設定』中有一個『背景顏色』的標題，可是沒有可編輯的設定
![default](https://user-images.githubusercontent.com/41721950/43696830-7e22f99c-9972-11e8-8f9a-c2479ff568a6.jpg)

請協助確認唷，謝謝~

**Comment by AnitaRyzo** [comment]
已無『背景顏色』的設定標題
![image](https://user-images.githubusercontent.com/41721950/43823077-88888564-9b20-11e8-9f7c-3ea6f58d08a2.png)
20180808確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
輪播圖已無『背景顏色』的設定標題
20180821確認以上正式環境內容!
