### ISSUE TITLE
【問題】抽獎禮盒是否該被隱藏呢?

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#583]
在頁籤編輯頁面中，抽獎禮盒沒有被隱藏，但也無法新增至畫布區
![image](https://user-images.githubusercontent.com/41721950/43703085-4ee3b33a-998e-11e8-960d-60ddaeb49d4d.png)

![image](https://user-images.githubusercontent.com/41721950/43702063-1cc6005e-998b-11e8-9dc5-a241fd1ec971.png)
請協助確認是否該被隱藏呢?? 謝謝~

**Comment by AnitaRyzo** [comment]
在『頁籤』與『輪播區塊』與『收縮區塊』的編輯頁面中，抽獎禮盒沒有被隱藏也不能使用
![image](https://user-images.githubusercontent.com/41721950/43823307-3df1daf4-9b21-11e8-8a78-0c29f72a3ca6.png)
![image](https://user-images.githubusercontent.com/41721950/43823363-64af6882-9b21-11e8-8c08-0090f667b00b.png)
![image](https://user-images.githubusercontent.com/41721950/43823439-9d08ceda-9b21-11e8-80b0-323dcac02dcb.png)
抽獎禮盒一直亮著
![image](https://user-images.githubusercontent.com/41721950/43823317-44889812-9b21-11e8-9529-4b9791efab9c.png)
請協助確認，謝謝

**Comment by AnitaRyzo** [comment]
在『頁籤』與『輪播區塊』的『收縮區塊』的編輯頁面中，抽獎禮盒已被隱藏
20180814確認以上測試環境的內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
在『頁籤』與『輪播區塊』的『收縮區塊』的編輯頁面中，抽獎禮盒已被隱藏
20180821確認以上正式環境內容!
