### ISSUE TITLE
【問題】序號機的序號組合設定按鈕顏色太深

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#585]
橘色框區域，顏色更改為＃6C6C6C

![1533543759302](https://user-images.githubusercontent.com/37163894/43705647-b16fb812-9995-11e8-849f-d315f6dd8b29.jpg)

**Comment by AnitaRyzo** [comment]
左邊為虛擬環境(修改後)
![image](https://user-images.githubusercontent.com/41721950/44015954-8c4e2bf2-9f05-11e8-8599-05185db8275e.png)
20180813確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
正式環境已如下顯示
![image](https://user-images.githubusercontent.com/41721950/44375636-471a1780-a527-11e8-9e89-a4745ab4c6d7.png)
20180821確認以上正式環境內容!
