### ISSUE TITLE
【疑問】『下載數據』的錯誤訊息

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#587]
【團隊管理】中【帳號編輯】裡面的【跨帳號功能】
裡面第一個【專案相關】的【下載數據】
不管是開啟或關閉【下載數據】的權限，『下載數據』的按鈕都是存在的，但是會出現以下錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/43749954-be1c1072-9a28-11e8-84fd-0d0fc137df5d.png)

● 關閉【下載數據】的權限時，有兩種款式的錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/43749990-f04fbf08-9a28-11e8-8e57-ece5c5c78f84.png)

● 開啟【下載數據】的權限時的錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/43750048-312072e8-9a29-11e8-9cdb-bf3e39eb69f9.png)

結論是都不能下載數據
以上請協助確認內容，謝謝~

**Comment by ryuichl** [comment]
後端已修正
前端 @Gabe-Liu  協助

**Comment by AnitaRyzo** [comment]
開啟【下載數據】的權限，『下載數據』的按鈕是存在的
![image](https://user-images.githubusercontent.com/41721950/44016141-60195d08-9f06-11e8-9c8a-c9ea7a34bea8.png)

關閉【下載數據】的權限，『下載數據』的按鈕是不存在的
![image](https://user-images.githubusercontent.com/41721950/44016202-b5642e3c-9f06-11e8-9510-db34d7e55ed3.png)

20180813確認以上測試環境的內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/44376025-2d79cf80-a529-11e8-9f21-5db96e285e13.png)

![image](https://user-images.githubusercontent.com/41721950/44376153-b55fd980-a529-11e8-8dc8-e148ee3935f1.png)
20180821確認以上正式環境內容!
