### ISSUE TITLE
【套版總覽】跑板

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#588]
【套版總覽】跑板如下
有設立兩個新的套版，但只看得到其中一個的一半畫面
![image](https://user-images.githubusercontent.com/41721950/43753850-5be87df2-9a3a-11e8-9ee0-c2d247ad83fd.png)
請協助處理，謝謝~

**Comment by AnitaRyzo** [comment]
已確認套版可以完整顯示

![image](https://user-images.githubusercontent.com/41721950/44016867-172465cc-9f09-11e8-9c00-7177da615b0f.png)
20180813確認以上測試環境的內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
套版樣式可完整呈現
![image](https://user-images.githubusercontent.com/41721950/44376230-20a9ab80-a52a-11e8-8f7c-ea870bbea3cc.png)
20180821確認以上正式環境內容!
