### ISSUE TITLE
【問題】提示狀態設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#589]
互動元件的提示狀態設定

當互動元件不是在畫面最上方時，
我點選畫面上的互動元件，並點選右側的提示狀態設定
畫布會偏離

![2018-08-07 1 44 16](https://user-images.githubusercontent.com/34327325/43756694-6447119e-9a48-11e8-9709-0947db069031.png)

**Comment by AnitaRyzo** [comment]
左邊為測試環境，右邊為正式環境
測試環境下，畫布內容不會自動跳動
![image](https://user-images.githubusercontent.com/41721950/44022435-252160a6-9f1a-11e8-9a77-73d8557e1696.png)
20180813確認以上測試環境的內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
當互動元件不是在畫面最上方時，點選右側的提示狀態設定，畫布內容不會自動跳動
![image](https://user-images.githubusercontent.com/41721950/44376475-5bf8aa00-a52b-11e8-9c54-0bfafd9cbede.png)
20180821確認以上正式環境內容!
