### ISSUE TITLE
【問題】權限無法設定

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#590]
我的帳號可以開團隊
但是開完團隊 邀請人進來後
只能設定層級 不能設定團隊成員功能權限
這是正常的嗎？
<img width="1054" alt="2018-08-07 4 52 13" src="https://user-images.githubusercontent.com/34560641/43765393-6cd08376-9a62-11e8-8653-165de2ac9c4e.png">

**Comment by ryuichl** [comment]
這是兩個不同權限
可以開團隊不代表你可以設定權限

**Comment by ryzojudy** [comment]
- 專案編輯 (建立、編輯、複製、刪除未發佈、刪除以發佈、變更已上線小工具、變更已上線序號、變更已上線轉盤)
- 專案數據 (查看、下載)
- 表單編輯 (建立、編輯、複製、刪除、變更已上線表單)
- 表單回覆 (查看、下載、刪除)
- 專案審核 (查看資格)
- 專案發佈 (發佈上線)
- 團隊管理 (邀請成員/帳號管理)
以上的 都是可以開關

全域權限(建立團隊、權限設定)

目前 套版的部分都沒有設定

**Comment by wilmaftliu** [comment]
@ryzojudy 我確認過 目前的使用手冊上好像沒有全域權限的功能設定說明
雖然到時候安裝 也許只會有幾個人能使用這些功能
希望這些細節或邏輯也能更新至使用手冊上 感謝

**Comment by ryzojudy** [comment]
好 等下次手冊更新時 會一併補上 到時再把issue關閉

**Comment by wilmaftliu** [comment]
感恩～～
