### ISSUE TITLE
【建議】邀請團隊成員時 建議將使用者名單順序倒過來

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#591]
建議可以將新註冊的成員 放在上面 邀請時比較方便
由而下分別是：
目前：舊--> 新
建議：新--> 舊
<img width="1003" alt="2018-08-07 4 54 57" src="https://user-images.githubusercontent.com/34560641/43766157-53582c80-9a64-11e8-98e8-ad8e93c60fcc.png">

**Comment by ai015606220** [comment]
目前這支api (`/api/weba/v3/auth/team/${teamId}/team_invite`)
所取得的資料並沒有帳號的create_at之類的屬性
![q](https://user-images.githubusercontent.com/10190722/44066883-6310fa58-9fa5-11e8-8217-28ef2da8f42b.png)

如果要進行這項改動
需要麻煩 @ryuichl 提供這個屬性

**Comment by ryuichl** [comment]
這支API是用來撈已送出邀請的列表耶
應該不是這個API吧?
@ai015606220

**Comment by ai015606220** [comment]
@ryuichl 抱歉打錯了
是/api/weba/v3/auth/user這一支

**Comment by ryuichl** [comment]
幫你加上去了
在GABE的分支
@ai015606220

**Comment by ai015606220** [comment]
好的感謝!!

**Comment by AnitaRyzo** [comment]
已將越晚註冊的成員放在越前面，方便使用者選取
![image](https://user-images.githubusercontent.com/41721950/46591042-8b1ea700-caea-11e8-9eb0-5dfbedadc018.png)
◎◎ 20181008確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
最新註冊的成員放在越前面，示意圖如下
![image](https://user-images.githubusercontent.com/41721950/47278986-cbf4e080-d5ff-11e8-941e-e23ae5b32f1b.png)
◎◎ 20181022確認以上正式環境內容 ◎◎
