### ISSUE TITLE
【問題】互動元件進入各提示頁時，右下角的“元件複製鈕”應該關閉

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#593]
畫布區右下角的複製鈕
![2018-08-08 10 29 00](https://user-images.githubusercontent.com/37163894/43812942-3cd6a332-9af6-11e8-8ba6-9878647f28c5.png)

**Comment by AnitaRyzo** [comment]
左邊為測試環境，右邊為正式環境
測試環境下，進入各提示頁時，右下角的“元件複製鈕”已關閉
![image](https://user-images.githubusercontent.com/41721950/44023382-c285a04e-9f1c-11e8-9013-1a8998c82054.png)

20180813確認以上測試環境的內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
已確認九個互動元件在各提示頁時，右下角的“元件複製鈕”已關閉
20180821確認以上正式環境內容!
