### ISSUE TITLE
【問題】團隊管理 踢出團隊後還是出現在複製專案清單

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#595]
<img width="921" alt="2018-08-08 2 02 41" src="https://user-images.githubusercontent.com/34560641/43819008-d163fe60-9b13-11e8-8edd-db1074aab5ea.png">
在團隊中要將專案複製給團隊中另一成員時 發現已經被踢出團隊的帳號 還是出現在複製目的地的帳號清單中（WEBA訓練帳戶）
但是事實上 在這團隊中 WEBA訓練帳戶早就已經被踢掉了
<img width="1279" alt="2018-08-08 2 05 21" src="https://user-images.githubusercontent.com/34560641/43819095-1cac8928-9b14-11e8-8df6-60a733a9d4db.png">
請協助查明真相 確認是否可以徹底將帳戶從團隊中刪除

感恩

**Comment by ryuichl** [comment]
已上到測試環境待測試

**Comment by AnitaRyzo** [comment]
選擇『刪除選取的團員』
![image](https://user-images.githubusercontent.com/41721950/44082886-18cf1fca-9fe5-11e8-9aa0-ec9c5027f08c.png)
網頁務必先做『重新整理』後，團隊就會顯示正確人數
複製專案時，就不會有被刪除的成員選項
![image](https://user-images.githubusercontent.com/41721950/44082909-348b846a-9fe5-11e8-9dfb-c392b58d1092.png)

20180814確認以上測試環境的內容，請知悉~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/44377363-ff978980-a52e-11e8-8643-cacfc02ef1ed.png)
網頁執行『重新整理』後，團隊就會顯示正確人數；複製專案時，就不會有被刪除的成員選項
![image](https://user-images.githubusercontent.com/41721950/44377394-1807a400-a52f-11e8-83a3-13a28af060b2.png)
20180821確認以上正式環境內容!
