### ISSUE TITLE
【網站修改】SHOWCASE網站資訊修改

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#596]
下方footer請協助修改電話及地址

電話  02 2547 5011
地址  台北市松山區復興北路191號7樓之2

![2018-08-08 3 19 26](https://user-images.githubusercontent.com/34327325/43822683-678eb992-9b1f-11e8-99d1-aa134efdeee8.png)

**Comment by AnitaRyzo** [comment]
有12個套版做修改，但是以下三個尚須修改
1. 玩酷快閃活動 2018/08/02 (捷運站有點太遠...)
![image](https://user-images.githubusercontent.com/41721950/44079037-a24dd7f6-9fda-11e8-88ab-72fa4eb16e4a.png)
2. 旅行平安保險 2018/06/01 (電話地址沒有改到)
![image](https://user-images.githubusercontent.com/41721950/44079106-cf5ea220-9fda-11e8-83bc-3fa13ed6f077.png)
3. 貴賓下午茶卷 2018/5/30 (地圖沒有改到)
![image](https://user-images.githubusercontent.com/41721950/44079290-39e1fd68-9fdb-11e8-9cae-95730ff24fd1.png)
20180814確認以上正式環境的內容，請知悉~

**Comment by weilyn** [comment]
以上三個專案修改完成
感謝提醒

**Comment by AnitaRyzo** [comment]
以上三個專案已確認修改
20180821確認以上正式環境內容!
