### ISSUE TITLE
【建議】積木功能裡的預設資訊

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#597]
附圖的兩個積木樣式，請協助更改為新版的地址、電話

![2018-08-08 4 36 35](https://user-images.githubusercontent.com/34327325/43826219-64b0b0ea-9b29-11e8-950d-a3e8871485c0.png)

**Comment by AnitaRyzo** [comment]
積木的頁尾主題已更改如下
![image](https://user-images.githubusercontent.com/41721950/44070010-15c4626c-9fb4-11e8-9b1c-3fdd281a8139.png)

※ 但積木中尚有三個分類有寫到地址，請確認是否要一起更改呢?? ※ 

大圖Banner主打活動
![image](https://user-images.githubusercontent.com/41721950/44070029-311b7e1a-9fb4-11e8-888b-e0d322d97791.png)

商品分類
![image](https://user-images.githubusercontent.com/41721950/44070058-4f3788a8-9fb4-11e8-8bcf-4eaedd914ab2.png)

門市資訊
![image](https://user-images.githubusercontent.com/41721950/44070085-6f5f54e4-9fb4-11e8-82f2-0b1e2225744d.png)

20180814確認以上測試環境的內容，請知悉~

**Comment by Gabe-Liu** [comment]
上方兩個積木已更新

**Comment by AnitaRyzo** [comment]
確認積木的頁尾主題已更新，其餘主題未變動
20180821確認以上正式環境內容!
