### ISSUE TITLE
【問題】表單的資料量暴增

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#598]
硬體：舊款Andriod手機
瀏覽器：FireFox 61.0
舊手機執行程式較慢，填寫表單的等待時間較長，等待程式執行的期間沒有多餘的操作；
但後台的表單內容，同一筆資料卻顯示超過二十筆以上...
![image](https://user-images.githubusercontent.com/41721950/43828665-b946116c-9b2f-11e8-89b4-77f2c3465add.png)
請協助確認內容，謝謝~

**Comment by ryuichl** [comment]
太久先關掉
有一樣問題再提出
