### ISSUE TITLE
【問題】區塊輪播背景

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#599]
區塊輪播背景顏色修改以後，只有第一頁有作用

其他都是空白的

之前有口頭提過，但隔有點久還沒修復，在此正式提出

**Comment by ryuichl** [comment]
最近都確實都沒有做更新
未來不會頻繁的更新檔案
都會先放到我們的測試環境測完後
才會再做更新

有重大BUG或是特殊需求的話
會另外處理

供你參考

**Comment by AnitaRyzo** [comment]
左邊為測試環境，右邊為正式環境
第一頁區塊輪播
![image](https://user-images.githubusercontent.com/41721950/43883478-d37f6d60-9be5-11e8-807a-73c8f1d662a4.png)
第二頁區塊輪播
![image](https://user-images.githubusercontent.com/41721950/43883509-f0dc7146-9be5-11e8-9187-5e02ae0bf1ba.png)
20180809確認以上內容，請知悉~

**Comment by Gabe-Liu** [comment]
已確認

**Comment by AnitaRyzo** [comment]
已確認區塊輪播的背景會如設定
20180821確認以上正式環境內容!
