### ISSUE TITLE
【動畫】幻燈片上太多元件時

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#602]
幻燈片上太多元件
導致預覽時動畫的設定都跑不出來～
發佈後也有一樣的問題ＱＱ

附上網址
https://hamigua.ryzoweba.io

救命！！

**Comment by Gabe-Liu** [comment]
目前幻燈片出現時，是把該幻燈片所有的元件都初始化，因此當元件多時，會卡卡的。
改善後，只有出現在畫面中位置的元件才會初始化，因此當畫面滑動時，元件要出現時才顯示其內容，希望能有效改善。

**Comment by AnitaRyzo** [comment]
在編輯區將每張幻燈片設定60個動畫圖片，並複製成5張幻燈片
![image](https://user-images.githubusercontent.com/41721950/45086198-35469000-b135-11e8-83da-471ef33e1843.png)
在瀏覽器看到的動畫執行速度，比在編輯區快一點點

◎◎ 20180905確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
在編輯區將每張幻燈片設定60個動畫圖片，並複製成5張幻燈片
![image](https://user-images.githubusercontent.com/41721950/45524874-292c9380-b803-11e8-8ee5-31460d493b3e.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
