### ISSUE TITLE
【問題】畫面無法完整顯示

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#603]
在解析度1366*768的情況下

專案管理下方的 編輯 複製 數據 那些選項，即使卷軸到最下方也無法顯示出來

必須將上方的資訊欄收合

![default](https://user-images.githubusercontent.com/34327325/44128912-247875c2-a078-11e8-8ff3-e21bf5e0360f.PNG)

**Comment by Gabe-Liu** [comment]
待更新後再確認一次
