### ISSUE TITLE
【問題】連接互動元件

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#605]
前提：在建立互動元件時，先『選擇連接的互動元件』
![image](https://user-images.githubusercontent.com/41721950/44138455-9929d8e2-a0a6-11e8-8d7c-17115ca6356f.png)

第一組：九宮格、戳戳樂、轉蛋機
當活動名稱相同，『獎項設定』與『抽獎設置』會同步；
若活動名稱不同，『獎項設定』與『抽獎設置』會不同步。
![image](https://user-images.githubusercontent.com/41721950/44138488-b401873c-a0a6-11e8-814b-9bd122f7db9d.png) 

第二組：轉盤、搖獎機
活動名稱不同，有連接的互動元件會同時更名，故『獎項設定』與『抽獎設置』會同步；
但轉盤的『樣式選擇』會互相牽連，轉盤配置會亂七八糟。
![image](https://user-images.githubusercontent.com/41721950/44138515-ca209710-a0a6-11e8-9e43-3f1b7c3d7a4b.png)

第三組：刮刮卡、抽紅包、幸運餅乾、抽獎禮盒
將最原始的互動元件設定命名為【A】，選擇連接的『活動名稱』【A】，卻沒有帶入任何【A】的設定資料，自行輸入『獎項設定』與『抽獎設置』後，卻發現所有資料是跟著A變動。
![image](https://user-images.githubusercontent.com/41721950/44138543-de46ec80-a0a6-11e8-99a1-18bbcb1d8b07.png)

※ 建議：『表單名稱』與『活動名稱』是否要設主鍵?
請協助確認正確的執行程序，謝謝~

**Comment by Gabe-Liu** [comment]
目前測試 第三組確實有問題 待修正

**Comment by AnitaRyzo** [comment]
第一組：九宮格、戳戳樂、轉蛋機 → 切換頁面才會同步
第二組：搖獎機、轉盤(顏色配置待修正) → 正確步驟就是所有連接的資料同步
第三組：刮刮卡、抽紅包、幸運餅乾、抽獎禮盒 (測試環境尚未有資料)

**Comment by AnitaRyzo** [comment]
建立互動元件時，『選擇連接的互動元件』
![image](https://user-images.githubusercontent.com/41721950/45131694-b8f98e80-b1c0-11e8-8b84-4cf28154fd7d.png)
連接後，『設定獎項』與『活動抽獎設定』會一併複製並連動
![image](https://user-images.githubusercontent.com/41721950/45131956-b9def000-b1c1-11e8-8e0e-e1aceaed0aee.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/45528196-d9a19400-b811-11e8-93c9-0dd13f9ad923.png)
互動元件三種建立方式
![image](https://user-images.githubusercontent.com/41721950/45528258-0e155000-b812-11e8-99e2-f76c3f6e0cb5.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
