### ISSUE TITLE
【問題】動畫效果不會顯示名稱

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#606]
新增元件動畫效果時，動畫效果名稱沒有顯示，
![image](https://user-images.githubusercontent.com/36216073/44139623-2e9115d2-a0aa-11e8-8e3f-eb8776a00f03.png)
再麻煩協助確認，謝謝~

**Comment by ryuichl** [comment]
測試無發現此問題
希望提供更詳細流程
感恩

**Comment by wendykuo** [comment]
剛剛清除紀錄後發現已經沒有問題了
感謝~

**Comment by ryuichl** [comment]
有再發現問題歡迎隨時提出
