### ISSUE TITLE
【問題】互動元件

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#607]
目前互動元件裡

1.幸運轉盤和九宮格的預設獎品是開啟兌換的，其他互動元件都是關閉兌換的，
想確認是否刻意這樣設置

2.抽獎禮盒的預覽圖是黑的（以前提過），以及只有禮盒沒有預設任何獎品
![2018-08-15 5 27 30](https://user-images.githubusercontent.com/34327325/44141710-81caa6b8-a0b0-11e8-9ffa-7b74088d75e7.png)

**Comment by Gabe-Liu** [comment]
問題1 確實是設定為這樣的模式
問題2 待下次更新時會修正

**Comment by AnitaRyzo** [comment]
問題二
抽獎禮盒的預覽圖
![image](https://user-images.githubusercontent.com/41721950/45132426-7d13f880-b1c3-11e8-9c2b-6f9b3cf08c19.png)
禮盒已預設『銘謝惠顧』關閉兌換的獎項
![image](https://user-images.githubusercontent.com/41721950/45132445-9157f580-b1c3-11e8-853a-6b1c75e46dd2.png)
◎◎ 20180905確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
禮盒已預設『銘謝惠顧』關閉兌換的獎項
預設『銘謝惠顧』：戳戳樂、搖獎機、轉蛋機、刮刮樂、抽紅包、幸運餅乾、抽獎禮盒
![image](https://user-images.githubusercontent.com/41721950/45528526-3a7d9c00-b813-11e8-9958-fcca6576debe.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
