### ISSUE TITLE
【問題】選單架構設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#608]
在開啟選單架構設定視窗的情況下，編輯互動元件的提示頁面，

提示頁面的選項會被蓋在後面，只能把選單頁面移開，但卻不能關閉

必須先離開提示編輯頁面以後，才能將選單架構頁面關閉

![2018-08-15 5 30 18](https://user-images.githubusercontent.com/34327325/44141984-4c671e4c-a0b1-11e8-9c16-737a9084e959.png)

**Comment by AnitaRyzo** [comment]
在開啟『選單架構』設定視窗的情況下，
![image](https://user-images.githubusercontent.com/41721950/45132741-aa14db00-b1c4-11e8-9fa3-8f0b8e2bc490.png)
開啟互動元件的『各狀態(提示)頁』，『選單架構』設定會被隱藏
![image](https://user-images.githubusercontent.com/41721950/45132767-c3b62280-b1c4-11e8-9022-bafe61ea67d7.png)
◎◎ 20180905確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
在開啟『選單架構』設定視窗的情況下，
![image](https://user-images.githubusercontent.com/41721950/45528738-3ef68480-b814-11e8-8301-46636e92d083.png)
開啟互動元件的『各狀態(提示)頁』，『選單架構』設定會被隱藏
![image](https://user-images.githubusercontent.com/41721950/45528721-1b333e80-b814-11e8-9486-3cfde8999d2f.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
