### ISSUE TITLE
【建議】複製的頁面

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#609]
建議複製的頁面新增在原本的頁面下方

![2018-08-15 5 34 35](https://user-images.githubusercontent.com/34327325/44142081-b0154b1c-a0b1-11e8-8215-01775ecd6232.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/45132921-5656c180-b1c5-11e8-8290-e2b825eda96f.png)
◎◎ 20180905確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/45397982-feacd000-b674-11e8-8537-446cbd1b2b05.png)
◎◎ 20180912確認以上測試環境內容 ◎◎
