### ISSUE TITLE
【建議】希望可以看到更新項目

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#612]
因為目前更新頻率步調放緩 內部測試過後再更新感覺系統也相對穩定
不過因為久久更新一次 會想知道自己提出的issue是否有被更新 或是更新後是否有改善
所以希望之後可以在某處？Github or email? 知道更新時間的通知＋更新項目
感謝

**Comment by ryuichl** [comment]
自行看之前提的ISSUE
相關狀況會寫在上面

**Comment by wilmaftliu** [comment]
所以有標記 [wait-for-prod]的都是會更新上去的嗎？
還是會有一個項目清單列下這次的更新項目？

**Comment by wilmaftliu** [comment]
了解
請麻煩協助說明各種標籤的意義
包含"wait-for-prod" "close" "on-check" 等等代表的issue階段
感恩

**Comment by ryuichl** [comment]
1. ISSUE提出後
2. 根據情況標籤bug或是ui ux
3. 工程人員修正後會標上waiting for test
4. 修正項目更新到測試環境上
5. 工程人員測試OK 標上 waiting for prod
6. 測試人員測試OK 拿掉 waiting for test
7. 修正項目更新到正式環境
8. 工程人員測試OK 在issue下面留言告知
9. 測試人員測試OK issue close
