### ISSUE TITLE
【問題】時間的搜尋功能

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#615]
表單設定題目是『時間』類型
![image](https://user-images.githubusercontent.com/41721950/44322656-e6380400-a480-11e8-9882-2aa5d0a0b942.png)

但在表單做搜尋功能的時候，卻只能選擇年月日，無法搜尋...
![image](https://user-images.githubusercontent.com/41721950/44322636-ce608000-a480-11e8-8191-0ae5bf06913e.png)

以上問題請協助確認，謝謝~

**Comment by ai015606220** [comment]
功能已新增，待日後更新至測試站

**Comment by AnitaRyzo** [comment]
時間的搜尋如下
![image](https://user-images.githubusercontent.com/41721950/45138004-8316d300-b1dd-11e8-9f61-081e1ce2bb52.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/45535934-90157100-b832-11e8-879c-d836e342a212.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
