### ISSUE TITLE
【問題】表單縮放後拖曳跑位問題

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#616]
九宮格製作後設計了一個表單
設定成一題一頁後
將表單的提示長度縮短後
一拖拉表單提示頁 表單就跑到下面去
請見下方GIF說明
![1534748441375](https://user-images.githubusercontent.com/34560641/44325019-0ddf9a00-a48a-11e8-866c-fa66f74e7649.gif)

**Comment by ryuichl** [comment]
拉長頁面後
會出現上述問題
