### ISSUE TITLE
【問題】表單無法正常縮放

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#617]
經過縮放後表單的控制點跑版，無法正常縮放表單
![1534748875202](https://user-images.githubusercontent.com/36216073/44325366-374cf580-a48b-11e8-81f4-4f5cd00212f5.gif)
再麻煩協助確認，謝謝

**Comment by ryuichl** [comment]
我嘗試後正常
待專家確認

**Comment by AnitaRyzo** [comment]
表單的控制點位置正確，可以正常縮放表單
![image](https://user-images.githubusercontent.com/41721950/45139057-24ebef00-b1e1-11e8-8048-669e9c5eeb87.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
表單的控制點位置正確，可以正常縮放表單
![image](https://user-images.githubusercontent.com/41721950/45540055-108d9f00-b83e-11e8-9f92-a90dce679028.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
