### ISSUE TITLE
【問題】 測試結果

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#618]
互動元件內關閉兌換的獎項(銘謝惠顧)，
在測試結果裡，顯示的文字是原本的文字，而不是銘謝惠顧
![2018-08-20 3 57 31](https://user-images.githubusercontent.com/34327325/44327720-0a501100-a492-11e8-9c4b-cda39cdec72d.png)

![2018-08-20 3 57 18](https://user-images.githubusercontent.com/34327325/44327724-0cb26b00-a492-11e8-9039-7956d485d881.png)

**Comment by ryuichl** [comment]
就算不是獎品
也是你打甚麼字就出現甚麼阿
不會自己變成銘謝惠顧

**Comment by weilyn** [comment]
因為關閉兌換的選項，在抽獎的時候會自動顯示成銘謝惠顧
所以感覺兩邊顯示的文字不太統一

**Comment by Samasianspock** [comment]
當初的設想「銘謝惠顧」是兌換開關「關閉」時的預設名稱，使用者可以再自行更改，最後顯示的是使用者自己命名的名稱，如果沒有更改就是預設的「銘謝惠顧」囉。

**Comment by ryuichl** [comment]
其實測試就是測試機率是否正確設定
跟是不是獎品沒關係
