### ISSUE TITLE
【建議】提示背景預設顏色可以深一點

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#622]
提示背景預設顏色可以深一點
大約可以是 黑色 不透明度 0.8

以下是預設的提示 前後內容會打架～
<img width="425" alt="2018-08-21 11 59 01" src="https://user-images.githubusercontent.com/34876672/44380341-586e1e80-a53d-11e8-8a49-217f27719a49.png">

**Comment by AnitaRyzo** [comment]
提示背景預設顏色
左邊是正式環境，右邊是測試環境已加深提示背景顏色
![image](https://user-images.githubusercontent.com/41721950/45139605-e6573400-b1e2-11e8-8d52-10bd028fd367.png)
建議反白提示字樣才能看得更清楚
![image](https://user-images.githubusercontent.com/41721950/45140067-4f8b7700-b1e4-11e8-8ce2-97e99eb894ac.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
提示背景預設顏色較深，適合反白文字
綠色框線中是黑色文字
![image](https://user-images.githubusercontent.com/41721950/45540619-7af30f00-b83f-11e8-9263-4ee1796b5629.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
