### ISSUE TITLE
【問題】按鈕選取顏色

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#624]
按鈕選取顏色在區塊輪播裡失效
![2018-08-21 1 57 37](https://user-images.githubusercontent.com/34327325/44383175-637b7b80-a54a-11e8-99d1-8779fdb86bb6.png)

**Comment by AnitaRyzo** [comment]
輪播區塊的編輯模式下的按鈕設定
![image](https://user-images.githubusercontent.com/41721950/45143090-cdec1700-b1ec-11e8-993c-76fc7aa1f19e.png)
瀏覽器執行畫面如下
![image](https://user-images.githubusercontent.com/41721950/45143007-954c3d80-b1ec-11e8-82cd-d2feb8f0f59a.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
輪播區塊的按鈕設定，已可在瀏覽器正確執行
![image](https://user-images.githubusercontent.com/41721950/45542809-7fbac180-b845-11e8-8236-935f4202b942.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
