### ISSUE TITLE
【問題】多個頁籤相互影響

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#626]
頁面上的多個頁籤會相互影響
點選一個物件,全部的頁籤的會起一起被圈選起來

![12344](https://user-images.githubusercontent.com/34327325/44384887-447fe800-a550-11e8-9245-f73660f24cff.PNG)

**Comment by Gabe-Liu** [comment]
這是早期時的BUG，這專案在很早前製作所以受到影響，如果要此專案正常運作，需要重新製作頁籤元件，再重新上架即可。
