### ISSUE TITLE
【問題】表單題目的英數會被截斷

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#627]
表單的題目類型有12種，而表單的標題、副標題與題目皆無限制字數
問題一：中文會自動換行，但英文跟數字會直接卡掉
副標題、單選、複選、矩陣式、手勢選答、手勢評分
![image](https://user-images.githubusercontent.com/41721950/44388909-fec91c80-a55b-11e8-9f16-064a752bff93.png)

問題二：矩陣式的英數版，格式會跑掉，無法選答
![image](https://user-images.githubusercontent.com/41721950/44389611-e1954d80-a55d-11e8-9808-55f6812f52a1.png)
以上問題請協助確認，謝謝~

**Comment by ai015606220** [comment]
已修正，待日後更新至測試站

**Comment by AnitaRyzo** [comment]
一、中文、英文與數字皆會自動換行
![image](https://user-images.githubusercontent.com/41721950/45083677-0a593d80-b12f-11e8-87b0-618d46144c49.png)

二、矩陣式
左邊是瀏覽器，右邊是『表單管理』的預覽，在預覽畫面的選項是空白
![image](https://user-images.githubusercontent.com/41721950/45083812-4c827f00-b12f-11e8-82f9-a4183f8cddbd.png)
◎◎ 20180905確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
一、中文、英文與數字在手勢選答皆會自動換行
![image](https://user-images.githubusercontent.com/41721950/45603146-9f2b3780-ba5b-11e8-9827-778f7e9bb402.png)

二、矩陣式
左邊是『預覽』，右邊是瀏覽器；英文與數字在最後一行時(黃框)，字會被卡掉
![image](https://user-images.githubusercontent.com/41721950/45603022-38594e80-ba5a-11e8-95ac-d5b21ae73c3a.png)
![image](https://user-images.githubusercontent.com/41721950/45603062-af8ee280-ba5a-11e8-8b13-8cebf18e125c.png)
中文的則會完整顯示
![image](https://user-images.githubusercontent.com/41721950/45603093-1e6c3b80-ba5b-11e8-9c9d-4fd0989b18e0.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
