### ISSUE TITLE
專案發佈-網址判斷有問題

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#63]
輸入已經存在的網址時
還是告知說可以用
接著點擊發佈鈕 就一直轉轉轉

**Comment by ryzojudy** [comment]
圖片被擋住看不出來 輸入的是test.ryzoweba.io(是derek在demo時用的網址)

![image](https://user-images.githubusercontent.com/34263719/39733139-c2300c6c-52a3-11e8-91e7-32fddaa4ea2c.png)

**Comment by Gabe-Liu** [comment]
暫時測不出來此問題
