### ISSUE TITLE
手機預覽未呈現電腦版設計版面

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#632]
as title

**Comment by AnitaRyzo** [comment]
在UAT環境下的『預覽』
若在『電腦版』的畫布有設計，利用此連結在電腦開啟時，會出現電腦版的畫面
![image](https://user-images.githubusercontent.com/41721950/45144637-46ed6d80-b1f1-11e8-823e-e40a6897194a.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
畫布環境的『預覽』
![image](https://user-images.githubusercontent.com/41721950/45726188-de3ec180-bbf0-11e8-98bd-7495c01e9a59.png)
專案審核的UAT環境下『預覽』
![image](https://user-images.githubusercontent.com/41721950/45726039-2c9f9080-bbf0-11e8-997b-4425b15a7a61.png)
若在『電腦版』的畫布有設計，利用此連結在電腦開啟時，會出現電腦版的畫面
◎◎ 20180919確認以上測試環境內容 ◎◎
