### ISSUE TITLE
【問題】表單題目設定右下方按紐超出畫面

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#633]
題目類型在最下方的按鈕會被切到
<img width="890" alt="2018-08-21 4 48 37" src="https://user-images.githubusercontent.com/34560641/44500681-6b5b2d00-a6bc-11e8-89ff-04fd73542027.png">

設定跳題的時候也是
<img width="890" alt="2018-08-21 4 28 24" src="https://user-images.githubusercontent.com/34560641/44500687-74e49500-a6bc-11e8-827e-89f53bf8552c.png">

螢幕比例是100%的 沒有縮放 煩請確認

**Comment by AnitaRyzo** [comment]
題目類型在最下方的按鈕
![image](https://user-images.githubusercontent.com/41721950/45145106-72248c80-b1f2-11e8-9d5b-5c8b78c8268a.png)
跳題在最下方的按鈕
![image](https://user-images.githubusercontent.com/41721950/45145557-7d2bec80-b1f3-11e8-82a6-5129a2509f65.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
題目類型在最下方的按鈕
![image](https://user-images.githubusercontent.com/41721950/45605104-fdace180-ba6c-11e8-94ff-5b9a62ad6016.png)
跳題在最下方的按鈕
![image](https://user-images.githubusercontent.com/41721950/45605139-30ef7080-ba6d-11e8-9517-7171f6188357.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
