### ISSUE TITLE
【問題】團隊管理中的團隊橫向拖曳

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#634]
<img width="1064" alt="2018-08-23 10 16 33" src="https://user-images.githubusercontent.com/34560641/44500965-b88bce80-a6bd-11e8-8fd7-0b9f19ddaa82.png">
新的團隊橫向切換方式 不是用滾輪滑動的方式 而是用抓取畫面後拖曳
因為沒有任何提示方式 如果不知道這樣功能的可能不知道如何使用

希望可以改善UX 感謝

**Comment by AnitaRyzo** [comment]
團隊橫向切換方式如下圖所示
![image](https://user-images.githubusercontent.com/41721950/45146003-89647980-b1f4-11e8-8228-6721ff10465e.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
團隊橫向切換是依靠『切換箭頭』+最底下的『側拉式選單』顯示完整團隊
![image](https://user-images.githubusercontent.com/41721950/45605310-c2131700-ba6e-11e8-83f6-f491a4340961.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
