### ISSUE TITLE
【問題】收縮區塊裡的地圖

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#635]
收縮區塊裡插入兩個地圖
兩個地圖會連動,不能單獨設定

![default](https://user-images.githubusercontent.com/34327325/44512396-f8b67580-a6ec-11e8-9b0b-bd7c9fc6c5ae.PNG)

**Comment by AnitaRyzo** [comment]
畫布顯示的地址可以單獨設定，但『地圖設定』顯示的地址卻是後者
![image](https://user-images.githubusercontent.com/41721950/44516560-fa396b00-a6f7-11e8-9f0a-12223d73f4ef.png)

**Comment by AnitaRyzo** [comment]
地址已可單獨設定並正確顯示地址
![image](https://user-images.githubusercontent.com/41721950/45146502-96ce3380-b1f5-11e8-841a-7075a9464961.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
地址已可單獨設定並正確顯示地址
![image](https://user-images.githubusercontent.com/41721950/45605445-9e040580-ba6f-11e8-9503-cd2af05236ae.png)

![image](https://user-images.githubusercontent.com/41721950/45605476-c855c300-ba6f-11e8-9082-04a4e4e178b3.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
