### ISSUE TITLE
【問題】中英文選擇中文字體，會出現方框

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#636]
前提：從WORD複製『有項目符號』的字串，將字串貼入『文字』元件中
『文字設定』中，中文字體有五種可以設定
![image](https://user-images.githubusercontent.com/41721950/44510326-f81ae080-a6e6-11e8-9622-4f2e4e99e884.png)
除了『正黑體』之外的四個字型
在EDGE與IE11的瀏覽器，中文與英文若最後有『空格』，就會顯示方框
![image](https://user-images.githubusercontent.com/41721950/44511933-9741d700-a6eb-11e8-86cc-6080281d563e.png)
以上疑問請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
使用特殊的中文字時，IE對於文字元件裡的換行標籤 <br/>會出現口的情況，而當把<br/>的字體預設成none時，就不會再出現口。

**Comment by AnitaRyzo** [comment]
即使是不同的字型，空格已不再出現
![image](https://user-images.githubusercontent.com/41721950/45147736-37bdee00-b1f8-11e8-9810-b28cde98e432.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
即使是不同的字型，空格已不再出現

另紀錄以下狀況，
若客戶直接將word中，使用『項目符號』的文字直接貼上，會出現以下狀況，無可避免。
![image](https://user-images.githubusercontent.com/41721950/45609063-db28c180-ba88-11e8-9e86-c9cf747e1b96.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
