### ISSUE TITLE
修改密碼成功後

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#638]
![image](https://user-images.githubusercontent.com/10150807/44562029-269dc780-a78a-11e8-9046-10c1b7684969.png)

目前修改成功後
沒有明顯回饋
建議加一點回饋

**Comment by AnitaRyzo** [comment]
密碼修改後的提示訊息如下
![image](https://user-images.githubusercontent.com/41721950/45607420-f5f63880-ba7e-11e8-8709-a56051156749.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
