### ISSUE TITLE
表單設計畫面

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#639]
![image](https://user-images.githubusercontent.com/10150807/44562810-e50f1b80-a78d-11e8-9ad5-5c974a9d960d.png)

表單右方的上下箭頭失效
一題一頁的左右換題也失效

![image](https://user-images.githubusercontent.com/10150807/44562870-1f78b880-a78e-11e8-9f96-f36edf406088.png)

我這個表單是選擇舊有的
在多題和一題的來回切換
右上角題目會無限往後增加(我這個表單只有三題)

**Comment by AnitaRyzo** [comment]
一題一頁的左右換題，題數正確顯示
![image](https://user-images.githubusercontent.com/41721950/45149049-45c13e00-b1fb-11e8-9fea-0fa0b5a76d29.png)

表單右方的上下箭頭可以操作，只是有時候整題的框架會跳離畫布
![image](https://user-images.githubusercontent.com/41721950/45149003-2fb37d80-b1fb-11e8-97b1-45a74644b2c2.png)
◎◎ 20180906確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
一題一頁的左右換題，題數正確顯示
![image](https://user-images.githubusercontent.com/41721950/45607577-f6db9a00-ba7f-11e8-8472-bf0d74677491.png)
表單右方的上下箭頭可以正確操作
![image](https://user-images.githubusercontent.com/41721950/45607627-48842480-ba80-11e8-958a-a5bd0226726a.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
