### ISSUE TITLE
小積木預覽

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#640]
![image](https://user-images.githubusercontent.com/10150807/44569421-df74fe00-a7ac-11e8-89be-71c10a88b3a6.png)
![image](https://user-images.githubusercontent.com/10150807/44569464-03384400-a7ad-11e8-8125-42adbb546b55.png)

有些小積木預覽時會出錯
然後有些裡面內容有點空
感覺不太正常?

**Comment by ai015606220** [comment]
這不是BUG，是因為收縮區塊的預設值是"關閉"
![image 1](https://user-images.githubusercontent.com/10190722/45193359-2d473700-b280-11e8-9da8-10086a5a5b40.png)
請問這個部份是要調整的嗎? @ryzojudy

**Comment by ryzojudy** [comment]
我覺得預設還是維持關閉的狀態
避免有人沒有注意到這是收縮區塊
若要改善的話
可以在有收縮區塊的小積木加上特別的標記
這部分需要跟 @Samasianspock 討論一下

**Comment by AnitaRyzo** [comment]
積木目前沒有出現錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/46387579-ed963280-c6f9-11e8-81c0-84e7fdbe30d1.png)
◎◎ 20181003確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
積木目前沒有出現錯誤訊息
![image](https://user-images.githubusercontent.com/41721950/47279061-d1065f80-d600-11e8-919d-9115431425ee.png)
◎◎ 20181022確認以上正式環境內容 ◎◎
