### ISSUE TITLE
【疑問】文字連結的提示線是否該存在?

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#641]
在『文字』元件中加入「限定輸入網址」的連結
![image](https://user-images.githubusercontent.com/41721950/44651392-db024c80-aa1b-11e8-8b58-57f8cbe1602f.png)

在『編輯區』與『預覽』時，文字顯示如下
![image](https://user-images.githubusercontent.com/41721950/44651326-9e365580-aa1b-11e8-8cbb-97656cfac3aa.png)
但在電腦與手機版本的瀏覽器，都會出現紫色的下底線
![image](https://user-images.githubusercontent.com/41721950/44651843-f883e600-aa1c-11e8-8807-7e8a74b83b42.png)
不論字串是甚麼顏色，下底線都是紫色，無法修改顏色；
若有存在的必要，是否可以照著字串顏色呢?

以上疑問請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
下次會移除

**Comment by AnitaRyzo** [comment]
字串底線已移除
![image](https://user-images.githubusercontent.com/41721950/45193844-c7a87a00-b282-11e8-946a-9df62abf76e7.png)
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
有連結的『文字』已無字串底線
![image](https://user-images.githubusercontent.com/41721950/45531852-3a39cc80-b824-11e8-9af6-cb9545c75991.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
