### ISSUE TITLE
【問題】表單中題目無法拖拉

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#642]
<img width="886" alt="2018-08-27 9 14 35" src="https://user-images.githubusercontent.com/34560641/44662010-0b0f1700-aa3f-11e8-876b-4403c117f05d.png">

當題目設定比較多時 想要將指定的題目拖拉至想要的位置 點擊拖拉的圖示卻沒有反應

**Comment by AnitaRyzo** [comment]
題目拖拉的敏感度變高
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
修改程式邏輯，故無畫面
提高題目拖拉的敏感度
◎◎ 20180914確認以上測試環境內容 ◎◎
