### ISSUE TITLE
【建議】表單中題目拖拉方式

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#643]
題目編輯完 想要更換題目位置時 目前只能拖拉到畫面中的位置 無法藉由拉到最下方或最上方一口氣跳到要放置的位置 有點不方便 一次只能拖曳一個位置 如果題目比較多 要拉到最下方就要拉很久
建議可以有拉到頂部或底部 就能一次咻咻咻滑到多題之上或之下的拖拉方式

**Comment by ryzojudy** [comment]
如果在那個綠色的上移下移旁邊多加 【移到最上層】和【移到最下層】這兩個按紐呢?
![image](https://user-images.githubusercontent.com/34263719/46402767-43d39780-c733-11e8-834f-9ad7a1e4ccea.png)

**Comment by wilmaftliu** [comment]
我覺得可以

**Comment by ryzojudy** [comment]
@liucwlewis 那就麻煩你了~
