### ISSUE TITLE
【問題】表單（一題一頁時）標題說明題型中 標題和部分文字會被吃掉

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#644]
表單中 標題說明題型 如果說明內容比較長的時候 一題一頁會出現「標題」和「上半部文字」被吃掉的情況

多題一頁時（正常：包含標題「個人資料保護法告知事項」和上半段文字「南山產物...」）
![1535376867263](https://user-images.githubusercontent.com/34560641/44662920-ac976800-aa41-11e8-9a68-5862db558e9b.gif)

一題一頁時（異常：標題「個人資料保護法告知事項」消失，上半部文字消失上半部文字消失，變成從「料，僅會在...」開始）
![1535376978539](https://user-images.githubusercontent.com/34560641/44662991-d6508f00-aa41-11e8-81c7-4d5a351b3198.gif)

提供參考
再麻煩協助修正 
感恩～

by抓蟲不只是說說 為了寫一休還製作GIF的認真瑪

**Comment by AnitaRyzo** [comment]
一題一頁的題目顯示方是
左邊為正式環境，右邊是測試環境；在測試環境已可完整顯示。
![image](https://user-images.githubusercontent.com/41721950/45194979-1e648280-b288-11e8-83a2-06b7eb4253fb.png)
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
一題一頁的題目顯示方式
左邊為正式環境，右邊是測試環境；在測試環境已可完整顯示。
![image](https://user-images.githubusercontent.com/41721950/45529405-95b18d80-b817-11e8-9712-628031232d0a.png)
◎◎ 20180914確認以上測試環境內容 ◎◎
