### ISSUE TITLE
【建議】介面文字修改

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#645]
![2018-08-28 9 45 18](https://user-images.githubusercontent.com/34327325/44695723-2281ea80-aaa7-11e8-8e0a-373c843c0054.png)

抽獎“紀“錄

名詞為紀
動詞為記

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/45209725-42dc5100-b2c0-11e8-9d5a-722e7f3d922d.png)
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
◎◎ 20180917確認以上測試環境內容 ◎◎
