### ISSUE TITLE
【問題】手勢選答、手勢評分

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#647]
手勢選答的感應區域貌似有點小，一定要在文字區域滑動才感應得到
![img_5944](https://user-images.githubusercontent.com/34327325/44697771-db4c2780-aaaf-11e8-89d4-268ea6fa7f52.PNG)

手勢評分在手機safari上，無法使用拖曳方式控制滑桿，只能用點擊的方式
![img_5945](https://user-images.githubusercontent.com/34327325/44697806-0c2c5c80-aab0-11e8-8e7d-fcbe7558ae49.PNG)

**Comment by ai015606220** [comment]
1. 是的墓前就是這麼大
2. 嘗試解決中

**Comment by AnitaYang2018** [comment]
手勢評分在手機瀏覽器上，可使用拖曳方式控制滑桿或是點擊
![958lp-kommv](https://user-images.githubusercontent.com/41557924/45074693-0e796100-b117-11e8-9c85-148bd213f23b.gif)
◎◎ 20180905確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
手勢評分在手機與電腦瀏覽器上，可使用拖曳方式控制滑桿或是點擊
◎◎ 20180917確認以上測試環境內容 ◎◎
