### ISSUE TITLE
【疑問】文字與表格在字串對齊的平均顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#648]
字串在『文字』與『表格』有四種對齊方式：靠左、置中、靠右、平均
![image](https://user-images.githubusercontent.com/41721950/44696683-1dbf3580-aaab-11e8-847f-6fc0c4d63e1c.png)

文字篇：『平均』的前提是編輯區的大小與字串數量相近
與右邊的瀏覽器相同顯示(平均=靠左)的有六個：電腦(EDGE、IE、FIREFOX)、手機(FIREFOX、FB、OPERA)
![image](https://user-images.githubusercontent.com/41721950/44699065-11d87100-aab5-11e8-9dd3-c82f4e3ec629.png)

表格篇：
所有瀏覽器顯示都是平均=靠左，與編輯區的大小無關
![image](https://user-images.githubusercontent.com/41721950/44699140-64b22880-aab5-11e8-83dd-a2874c5480f8.png)

以上疑問請協助確認，謝謝~

**Comment by ai015606220** [comment]
看不太懂這個問題

**Comment by AnitaRyzo** [comment]
若此對齊方式與WORD功能相同，那會覺得字元應該要在同一列平均分配間距。
![image](https://user-images.githubusercontent.com/41721950/44702688-35a4b280-aac7-11e8-9c87-a483d32b407b.png)

在文字元件中，按了同一個『平均』功能，在不同瀏覽器卻兩種顯示方法
在表格中，按了『平均』功能，卻與『靠左』顯示的相同

**Comment by ai015606220** [comment]
左右對齊的意思是與其他行的文字做比較

置左對齊
![left](https://user-images.githubusercontent.com/10190722/44703386-0a6f9280-aaca-11e8-93fe-b91f8747d096.png)

左右對齊
![justify](https://user-images.githubusercontent.com/10190722/44703398-19eedb80-aaca-11e8-8186-4f36c271d7a8.png)

**Comment by ai015606220** [comment]
文字篇的瀏覽器顯示差異是因為
那三行並非自然斷行 (因為使用了enter直接斷行)
並非全部的瀏覽器都依然會將這些斷句對齊
(這部分網頁排版觀念比較難解釋，需要口頭解釋可以找我)

結論是這問題比較無解

**Comment by AnitaRyzo** [comment]
已讓『文字』自然斷行，瀏覽器依然分為兩種顯示唷!

文字篇：第一段設『靠左對齊』，第二段設『左右對齊』
互相比較之後可知，有四個瀏覽器在這兩種樣式設定下，顯示的文字寬度是相同的(紅線)
『左右對齊=靠左對齊』的有四個：電腦(EDGE、IE、FIREFOX)、手機(FIREFOX)
![image](https://user-images.githubusercontent.com/41721950/44708468-d3a17880-aad9-11e8-9e74-d14bfcd484eb.png)

表單篇：『左右對齊』的功能僅適用在會自動斷行的中文；
由下圖比較之後得知，有三個瀏覽器顯示的文字寬度是不同的(紅線+黃線空格)
『左右對齊=靠左對齊』的是電腦版的EDGE、IE、FIREFOX
![image](https://user-images.githubusercontent.com/41721950/44710357-8247b800-aade-11e8-8f28-ea86e40fc0e5.png)
以上請協助確認是否有解，謝謝~

**Comment by ai015606220** [comment]
文字元件在EDGE、IE、FIREFOX 需再微調一些設定

**Comment by AnitaRyzo** [comment]
由左至右分別是EDGE、IE、FIREFOX 在測試環境的畫面中，左右對齊<>靠左對齊
![image](https://user-images.githubusercontent.com/41721950/45196325-4f47b600-b28e-11e8-91e4-460796a0420e.png)
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
在測試環境的環境中，電腦版的『文字』與『表格』明顯可知左右對齊<>靠左對齊
但在手機版本的Edge、FB、Safari、Firefox中，『文字』的『左右對齊<>靠左對齊』較不明顯
![image](https://user-images.githubusercontent.com/41721950/45661305-868c5180-bb2f-11e8-9dc1-e0de8b68dfe9.png)
◎◎ 20180918確認以上測試環境內容 ◎◎
