### ISSUE TITLE
【問題】表單可建立不可編輯時的異常

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#652]
當『帳號管理』的權限只開啟『表單編輯』的『建立』，無『編輯』的權限
![image](https://user-images.githubusercontent.com/41721950/44763072-1a47af00-ab7c-11e8-9a8d-f450ca89cd94.png)
表單可以依正常程序建立並編輯題目，按下『關閉視窗』，會出現以下提示訊息
![image](https://user-images.githubusercontent.com/41721950/44762858-1c5d3e00-ab7b-11e8-9bfe-aafa3364ca19.png)
按下『確定』鈕幾次，就會建立幾次新表單。
![image](https://user-images.githubusercontent.com/41721950/44763675-e15d0980-ab7e-11e8-95ed-38f532edb262.png)
![image](https://user-images.githubusercontent.com/41721950/44763204-b4a7f280-ab7c-11e8-8677-2d6c83876a4f.png)
以上疑問請協助處理，謝謝~

**Comment by ryuichl** [comment]
表單建立的過程
會同時建立後又編輯
所以當沒有編輯權限時
建立會無法正常完成

**Comment by AnitaRyzo** [comment]
當『帳號管理』的權限只開啟『表單編輯』的『建立』，無『編輯』的權限
就只能編輯表單名稱，故只有兩個步驟
![image](https://user-images.githubusercontent.com/41721950/45612689-6197d000-ba96-11e8-8881-39aca9d6070e.png)
有『表單編輯』的『建立』與『編輯』的權限，就會有三個步驟
![image](https://user-images.githubusercontent.com/41721950/45612768-9efc5d80-ba96-11e8-8b30-95315f6797ae.png)

◎◎ 20180917確認以上測試環境內容 ◎◎
