### ISSUE TITLE
【問題】『變更已上線序號』的權限影響新增序號機

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#653]
關閉『變更已上線序號』的權限
![image](https://user-images.githubusercontent.com/41721950/44764787-02742900-ab84-11e8-901b-703d7d4dad50.png)
當此專案輸入『域名』並按下『儲存』後，若再建立序號機，會出現以下錯誤訊息
1. 建立序號機
![image](https://user-images.githubusercontent.com/41721950/44767707-8a146480-ab91-11e8-91b3-26d6e43532ee.png)
1-1. 活動名稱、序號組合設定、產出序號都可以正常操作；但不能按『確認』
![image](https://user-images.githubusercontent.com/41721950/44767763-c1831100-ab91-11e8-8029-f568de2fde9d.png)

2. 選擇序號機
![image](https://user-images.githubusercontent.com/41721950/44767866-158df580-ab92-11e8-89b7-940d43f2123a.png)
以上疑問請協助確認，謝謝~

**Comment by ryuichl** [comment]
抽獎可能有一樣狀況
感恩

**Comment by AnitaRyzo** [comment]
關閉『變更已上線轉盤』的權限
九個互動元件皆在專案輸入『域名』並按下『儲存』後

1. 【建立新元件】時，在『設定獎項』時，會如下出現『權限不足』的按鈕
![image](https://user-images.githubusercontent.com/41721950/44775095-5c3a1a80-aba7-11e8-8585-faadec39df21.png)
但在刮刮樂中卻顯示『儲存』的按鈕，雖然不能執行；請確認是否要一致
![image](https://user-images.githubusercontent.com/41721950/44775570-8809d000-aba8-11e8-9f47-3b8818eb406b.png)

2. 【選擇元件】時，無法連接舊有的元件(與序號機相同問題)
![image](https://user-images.githubusercontent.com/41721950/44775324-f0a47d00-aba7-11e8-9978-4ad8bb77b468.png)
以上疑問請協助確認，謝謝~

**Comment by AnitaYang2018** [comment]
輸入『域名』並按下『儲存』後，若再建立序號機，就只能如下『選擇序號機』
![image](https://user-images.githubusercontent.com/41557924/45068568-a288ff80-b0fa-11e8-82c6-663d43123ad3.png)
選擇專案中已建立過的『活動名稱』
![image](https://user-images.githubusercontent.com/41557924/45068534-7a010580-b0fa-11e8-811b-abf9647168b9.png)
序號機也可以按下『確認』，並設定表單
![image](https://user-images.githubusercontent.com/41557924/45068610-d95f1580-b0fa-11e8-8a00-6d0ca3a8928b.png)

◎◎ 20180905確認以上測試環境內容 ◎◎ 
『變更已上線轉盤』權限的九個互動元件，尚有需要修改的地方

**Comment by AnitaRyzo** [comment]
『設定獎項』時，會如下出現『權限不足』的按鈕提示
![image](https://user-images.githubusercontent.com/41721950/45198485-6213b800-b299-11e8-9c7a-ec3e2ee411d9.png)
【選擇元件】時，戳戳樂可以順利連接舊有的元件
![image](https://user-images.githubusercontent.com/41721950/45198555-aef78e80-b299-11e8-86de-a62703bad056.png)
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
關閉『變更已上線序號』與『變更已上線抽獎』的權限
![image](https://user-images.githubusercontent.com/41721950/45658552-3d81d080-bb22-11e8-9962-f38c70d23262.png)
只能『選擇序號機』與『選擇互動元件』，選擇專案中已建立過的『活動名稱』；但禁止執行表單連結
![image](https://user-images.githubusercontent.com/41721950/45613279-5e054880-ba98-11e8-980e-86bfb39c4076.png)
『變更已上線轉盤』權限的九個互動元件，在『設定獎項』時，會出現『權限不足』的按鈕提示
![image](https://user-images.githubusercontent.com/41721950/45613399-c3593980-ba98-11e8-8678-1ca4450b0183.png)
◎◎ 20180918確認以上測試環境內容 ◎◎
