### ISSUE TITLE
新增專案下載功能

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#654]
https://zpl.io/2GOW7v4

畫面設計已經好了

for Kyle

**Comment by AnitaRyzo** [comment]
對自己的帳號進行『下載專案』
![image](https://user-images.githubusercontent.com/41721950/45613524-437f9f00-ba99-11e8-9f02-44f2a45a398e.png)
『下載專案』→解壓縮→資料夾內輸入cmd→view-server執行→表單與互動元件不能使用
◎◎ 20180917確認以上測試環境內容 ◎◎
