### ISSUE TITLE
【問題】『變更已上線內嵌程式碼』的權限影響

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#655]
關閉『變更已上線內嵌程式碼』的權限
![image](https://user-images.githubusercontent.com/41721950/44776612-11ba9d00-abab-11e8-99b7-e43b8aa65926.png)
一、原始同時存在『放大』『確定』的按鈕
![image](https://user-images.githubusercontent.com/41721950/44776732-5cd4b000-abab-11e8-9c67-62b88057e1a3.png)
二、當此專案輸入『域名』並按下『儲存』後，只剩下『放大』的按鈕
![image](https://user-images.githubusercontent.com/41721950/44776676-40d10e80-abab-11e8-833f-0434deaffdaf.png)
三、此時再新建『內嵌程式碼』的新元件B，輸入程式碼按下『確定』的按鈕，就立刻只剩下『放大』的按鈕，無法再進行修改。明明完全沒有按儲存...
以上疑問請協助確認，謝謝~

**Comment by ryuichl** [comment]
目前變更已上線序號 抽獎 小工具的敘述可能要更改一下

目前機制如下
假設使用者沒有變更已上線XXX的權限
當這個專案已經設定發佈域名 便認定此專案已上線
在已上線的情況下
使用者不得新增或變更XXX

**Comment by AnitaYang2018** [comment]
測試環境中，關閉『變更已上線內嵌程式碼』的權限
嵌入程式碼的位置已無『確定』的按鈕
![image](https://user-images.githubusercontent.com/41557924/45066649-e62b3b80-b0f1-11e8-9d31-26be4935e8a8.png)
建議是否直接讓『內嵌程式碼』，像『九宮格』一樣無法被選擇
![image](https://user-images.githubusercontent.com/41557924/45066618-ceec4e00-b0f1-11e8-852b-d96a9d236827.png)
![image](https://user-images.githubusercontent.com/41557924/45066781-8d0fd780-b0f2-11e8-8264-5f8c873be99b.png)

◎◎ 0905確認此測試畫面 ◎◎
