### ISSUE TITLE
【問題】臉書工具無法顯示在手機瀏覽器

### ISSUE THREAD

**Issue by AnitaYang2018** [ryuichl/v3-report#659]
臉書工具(內嵌型) 的『 影片』
在手機瀏覽時不存在：FB、Line、safari、Edge、chrome、Opera
![image](https://user-images.githubusercontent.com/41557924/44896269-39843f00-ad2a-11e8-8d8a-5df3d9dc12a8.png)

臉書工具(動作型)的 『 讚、分享、留言』
在手機瀏覽時不存在：Firefox
![image](https://user-images.githubusercontent.com/41557924/44896549-29209400-ad2b-11e8-9d60-da0aa41bb860.png)

題外話：同樣的『臉書工具』畫面，在電腦版Chrome執行的解析度很低
![image](https://user-images.githubusercontent.com/41557924/44897457-59b5fd00-ad2e-11e8-8be1-03b8e55dd0de.png)

以上疑問請協助確認，謝謝~

**Comment by Gabe-Liu** [comment]
問題1 .2已解決
電腦版Chrome執行的解析度很低的問題部分：
我是使用css的 transform: scale把臉書元件給放大，為了讓元件間的距離、大小等維持比例，但在chrome觀看時，會有模糊的情況發生，目前還尚未找到解決方法  :(

**Comment by AnitaRyzo** [comment]
臉書工具(內嵌型) 的『 影片』，無法在手機瀏覽器顯示完整貼文
建議添加提醒如下
![image](https://user-images.githubusercontent.com/41721950/45207519-bd09d700-b2ba-11e8-83e2-0464610a9831.png)
臉書工具(動作型)的 『 讚、分享、留言』，要Firefox先打開追蹤保護
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
臉書工具(內嵌型) 的『 影片』，已添加提醒如下
![image](https://user-images.githubusercontent.com/41721950/45614897-922f3800-ba9d-11e8-9b9b-b74f635feef3.png)
小備註：電腦版Chrome執行的解析度很低，目前尚未找到解決方法
◎◎ 20180917確認以上測試環境內容 ◎◎
