### ISSUE TITLE
【許願】條件式元件套餐

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#660]
之前和國泰世華銀行接洽時，了解到企業在對既有客戶進行行銷活動時，
除了WEBA目前這種「先抽獎、再填表」以獲取客戶名單的行銷流程，尚有另一種用法，
透過「先達成某些條件、再給好處」的方式，以協助企業分析客戶身份、製造網路聲量或建立品牌形象。
範例參考：
(1) 預測電競冠軍抽獎：完成電競相關知識問答（表單填寫）、預測完冠軍隊伍即可線上抽出小獎品。
(2)卡友分享貼文抽獎：分享到社群網頁（點擊分享按鈕）、完成卡友登錄（跳轉登陸頁）後，會在事後抽出大獎。

這種條件式的行銷手法，其實使用到的元件都是WEBA可以做出來的，但目前在WEBA上這些元件是無法互相溝通的，只能透過「線性排列」讓客戶依序看到這些元件，但事實上，目前還沒有辦法做到「做完A，才出現B」的效果（即使透過事件，也無法將這些元件拆解）。

所以在此許下願望，希望未來可以出現像是「條件式元件套餐」的功能，示意請見下方：
<img width="642" alt="2018-08-31 4 16 01" src="https://user-images.githubusercontent.com/34560641/44901174-3c3a6080-ad39-11e8-866a-e1af786dddfe.png">

**Comment by ryuichl** [comment]
排程中
先關掉
