### ISSUE TITLE
【問題】互動元件設定過的獎品數量會跑掉

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#661]
如題
例如
有時候設定30 儲存之後 下次再點進去專案裡面看有時候會變成29或28

**Comment by ryuichl** [comment]
你這個專案是否發佈過?
或是有進行uat測試

獎品被抽掉數量會減少

**Comment by AnitaYang2018** [comment]
![image](https://user-images.githubusercontent.com/41557924/44964837-16919f00-af65-11e8-9535-172edeed496e.png)

第一組：九宮格、戳戳樂、轉蛋機、轉盤、搖獎機
申請審核並在瀏覽器執行之後，『設定獎項』的數量會依照執行次數遞減，後台有執行並顯示→正常程序

第二組：刮刮卡、抽紅包、幸運餅乾、抽獎禮盒
申請審核並在瀏覽器執行之後，『設定獎項』的數量會依照執行次數遞減，後台有執行但不會顯示→錯誤程序

#605 修改issue時，Gabe已同時修改第二組的錯誤程序

**Comment by ryzojessie** [comment]
啊
對厚 我的不好 我忘記發布後抽獎獎品數量會減少
對 專案都是發佈過後的 我抱歉 my bad 那這個我沒有疑問了
謝謝～
