### ISSUE TITLE
【問題】小積木預覽時的下方應該是實心的色塊，目前僅有框線的顏色，如果下方有其他元件會融再一起

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#662]
如圖
<img width="549" alt="2018-09-03 9 57 47" src="https://user-images.githubusercontent.com/37163894/44963873-0925e600-af60-11e8-8a44-cce557adc4d9.png">

**Comment by AnitaRyzo** [comment]
小積木預覽時，畫布是實心的色塊
◎◎ 20180917確認以上測試環境內容 ◎◎
