### ISSUE TITLE
【問題】選擇現有互動元件

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#663]
HI
互動元件都有一個選擇XXXX(現有互動元件)的選項
這次在修改過往專案時發現，
選擇了過去已經創建過的互動元件，大部分資訊都沒有被保留，而且每個元件的情況不一
（專案內曾經創建過一個一樣性質，並且資料完整的互動元件，但是後來刪除了。）

轉蛋機、九宮格：獎項名稱、獎項照片被保留，活動名稱遺失
搖獎機、戳戳樂：獎項名稱數量被保留，圖片、活動名稱遺失
其餘互動元件：無論獎項名稱、獎項照片、活動名稱都遺失

如果資料都沒有保留的話，就感覺不需要選擇已創建過的互動元件了，因為都等同重新做起

**Comment by Gabe-Liu** [comment]
此issue應該已經解決了，只是一直尚未更新上去

**Comment by AnitaRyzo** [comment]
#605
