### ISSUE TITLE
【問題】專案管理排序專案的『最近更新』有誤

### ISSUE THREAD

**Issue by AnitaYang2018** [ryuichl/v3-report#664]
專案管理排序專案的方式有三種：創建日期、最近更新、按名稱排序
![image](https://user-images.githubusercontent.com/41557924/45007349-f8dd3c00-b02f-11e8-8c43-f308d95304da.png)

『創建日期』由新到舊的日期排序
![image](https://user-images.githubusercontent.com/41557924/45007480-7bfe9200-b030-11e8-90a7-4243653f4843.png)
但『最近更新』卻照著『創建日期』排序，非越晚更新的越靠左。
![image](https://user-images.githubusercontent.com/41557924/45007537-d26bd080-b030-11e8-9adc-35031ec39ec3.png)
以上疑問請協助確認，謝謝~

**Comment by ryuichl** [comment]
#568

**Comment by AnitaRyzo** [comment]
『最近更新』已按照儲存的時序排列(越左邊越新)
![image](https://user-images.githubusercontent.com/41721950/45204982-7a90cc00-b2b3-11e8-9ded-76644a9f8384.png)
『創建日期』已依照創立時間排序(越左邊越新)
![image](https://user-images.githubusercontent.com/41721950/45205031-97c59a80-b2b3-11e8-80a4-13f4c26d6049.png)
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『最近更新』已按照儲存的時序排列(越左邊越新)
![image](https://user-images.githubusercontent.com/41721950/45615893-695c7200-baa0-11e8-8d20-bcb74c2fe26e.png)
『創建日期』已依照創立時間排序(越左邊越新)
![image](https://user-images.githubusercontent.com/41721950/45615914-7711f780-baa0-11e8-9b1b-2a8ca1b60c18.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
