### ISSUE TITLE
【問題】專案排程時間的設定有誤

### ISSUE THREAD

**Issue by AnitaYang2018** [ryuichl/v3-report#665]
『專案管理』編輯『發佈設定』中的排程時間，如下設定《下午3:00》
![image](https://user-images.githubusercontent.com/41557924/45014542-7a919180-b051-11e8-94fb-d783a991deb0.png)
儲存離開後，再次進入專案，時間會變成《上午3:00》
![image](https://user-images.githubusercontent.com/41557924/45014383-efb09700-b050-11e8-860e-311db3daed10.png)

與此連動的是在『專案發佈』的『專案開啟時間設定』；如下設定《下午3:00》
![image](https://user-images.githubusercontent.com/41557924/45014469-3c946d80-b051-11e8-8424-89fa3dc5db37.png)
再次進入專案，時間是正確的《下午3:00》
![image](https://user-images.githubusercontent.com/41557924/45014248-77e26c80-b050-11e8-93ef-828e00e263fb.png)
以上疑問請協助確認，謝謝~

**Comment by AnitaRyzo** [comment]
『專案管理』的時間設定，時間已可正確顯示
![image](https://user-images.githubusercontent.com/41721950/45204575-3fda6400-b2b2-11e8-9289-9340683c6907.png)
也可連動『審核發佈管理』的時間設定
![image](https://user-images.githubusercontent.com/41721950/45204601-541e6100-b2b2-11e8-9cbd-c1b0dbf358ef.png)
◎◎ 20180907確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『專案管理』的時間設定，時間已可正確顯示
![image](https://user-images.githubusercontent.com/41721950/45616097-07e8d300-baa1-11e8-9387-e52a6d96489b.png)
也可連動『審核發佈管理』的時間設定
![image](https://user-images.githubusercontent.com/41721950/45616078-fa334d80-baa0-11e8-8076-98a7702c5c5c.png)
◎◎ 20180917確認以上測試環境內容 ◎◎
