### ISSUE TITLE
【建議】『被刪除表單的互動元件』是否能與『建立新的互動元件』有相同提示訊息

### ISSUE THREAD

**Issue by AnitaYang2018** [ryuichl/v3-report#666]
建立新的互動元件時，若尚未設立表單，會出現以下提示訊息
![image](https://user-images.githubusercontent.com/41557924/45021180-79696000-b063-11e8-8e08-01cf23206ac2.png)
瀏覽器執行的畫面如下
![image](https://user-images.githubusercontent.com/41557924/45021542-66a35b00-b064-11e8-9104-36eafc219b25.png)

※※※ 但若從『表單管理』刪除互動元件連結的表單 ※※※
互動元件會正常執行，但中獎後的『填寫資料』會不斷LOADING，無法執行
![image](https://user-images.githubusercontent.com/41557924/45020876-b6812280-b062-11e8-8a1a-6971455c2607.png)
而在編輯頁面裡，無任何提示告知此互動元件尚未連結表單
![image](https://user-images.githubusercontent.com/41557924/45021192-7e2e1400-b063-11e8-9e89-d5fe91f478da.png)
請確認『被刪除表單的互動元件』是否能與『建立新的互動元件』有相同提示訊息，謝謝~

**Comment by ai015606220** [comment]
無法加上類似的提醒，因為刪除表單的時候並不會去影響(改動)到各專案內的表單元件設定

目前的處理是讓表單不會一直顯示loading
![image 1](https://user-images.githubusercontent.com/10190722/45146619-d72db180-b1f5-11e8-9828-7d69cc9ecd7f.png)

**Comment by AnitaRyzo** [comment]
在UAT環境與發佈中的環境，若表單已被刪除，皆會出現如下畫面
![image](https://user-images.githubusercontent.com/41721950/46462519-3cc08e00-c7f4-11e8-8e60-4173de611554.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
在UAT環境與發佈中的瀏覽器，若表單已被刪除，皆會出現如左圖的『無此表單』
在編輯環境的表單資料顯示如右圖的『尚未建立任何表單』
![image](https://user-images.githubusercontent.com/41721950/47279937-796af280-d606-11e8-940f-cc4125e244fa.png)
◎◎ 20181022確認以上正式環境內容 ◎◎
