### ISSUE TITLE
【建議】希望可以增加「隱私權政策」核取方塊的題型

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#670]
目前的表單沒有類似的做法 
希望可以新增有「單項目核取方塊」的題型 下面提供兩種參考圖

第一種：跳出提示頁（裡面包含隱私權等細節）
![image](https://user-images.githubusercontent.com/34560641/45204427-c3478580-b2b1-11e8-9183-f02ae1c8da16.png)

第二種：文字含有連結，將隱私權政策細項設定「開新分頁」（跳轉到另一個網頁）或點開後跳出「提示頁」
![image](https://user-images.githubusercontent.com/34560641/45204446-d5292880-b2b1-11e8-8c87-043008eed2ae.png)

第三種：收縮區塊
![hhje6my5j1orbfgc4okd0d1zezlqtwwnlnaa_ptqgv4](https://user-images.githubusercontent.com/34560641/45204533-1ae5f100-b2b2-11e8-9767-ce4e4ce28de2.jpeg)

提供參考

**Comment by wilmaftliu** [comment]
@ryzojudy ＯＫ沒問提感謝

**Comment by liucwlewis** [comment]
<img width="1000" alt="2019-01-03 11 16 49" src="https://user-images.githubusercontent.com/37163894/50622558-158b7100-0f49-11e9-9a33-8b4e715c4daf.png">

連結：https://zpl.io/29oKYve
