### ISSUE TITLE
【問題】專案審核與團隊的關係

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#671]
目前看起來專案審核區是會將各團隊申請的審核項目分開顯示
也就是A團隊申請的審核,當我切換到B團隊時,是看不到審核項目的
但是如果專案是由"自己"製作的，就會不分團隊，全部顯示在審核及發布區
![dfbg](https://user-images.githubusercontent.com/34327325/45272707-71854200-b4e1-11e8-9a27-63a527e3174c.PNG)

想請問
1.如果我今天在A團隊製作了專案1，然後我切換到B團隊進行審核發布，此專案會算在A團隊還是B團隊的發布
2.目前這樣的設計是否會造成使用者的混淆? 例如以為資料重複了，就將之直接刪除

**Comment by ryuichl** [comment]
專案沒有屬於任何團隊
只會跟著個人
如果你看不到
可能是你誤會了甚麼不然就是BUG

**Comment by weilyn** [comment]
ok
了解規則及設計初衷了

謝謝
