### ISSUE TITLE
【問題】元件旋轉

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#672]
HI近日在操作weba時，發現有一些元件不能使用旋轉功能
想知道為什麼會如此設計，有什麼考量的點嗎(2版的時候，這些功能都是通用的)

元件包含
輪播區塊
收縮區塊
頁籤

有機會讓這些元件也可以旋轉嗎

**Comment by ryuichl** [comment]
太久先關掉
有一樣問題再提出
