### ISSUE TITLE
【建議】團隊邀請

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#676]
目前團隊邀請的部分，如果有不小心邀請到的人必須等他加入以後才能再將她踢出

無法直接取消邀請

建議增加這個選項

通常是在使用者帳號旁就有個X 可以直接刪掉該筆

**Comment by AnitaRyzo** [comment]
使用者帳號旁就有個X，可以直接刪掉該筆
![image](https://user-images.githubusercontent.com/41721950/45678785-c07a4980-bb69-11e8-95f2-7c008f702608.png)
◎◎ 20180918確認以上測試環境內容 ◎◎
