### ISSUE TITLE
【問題】套版管理

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#677]
大家好
小弟最近發現套版管理的頁面有嚴重的延遲感

![2018-09-12 5 00 20](https://user-images.githubusercontent.com/34327325/45414202-70087500-b6ad-11e8-993a-0bf0c7448a75.png)

**Comment by ryuichl** [comment]
補充說明
修改套版的標籤會很lag

**Comment by ryuichl** [comment]
剛發現進套版管理
會一次送出多筆請求撈出全部樣版資料
還有送出很多多餘的請求
這邊應該可以優化一下
![image](https://user-images.githubusercontent.com/10150807/45464791-c07ee180-b744-11e8-8b85-e1c3cb7ef5a2.png)
