### ISSUE TITLE
【建議】套版總覽防呆

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#678]
hi，因為從套版新增專案時，如果網路延遲而多點了幾下，會因此產生大量的該套版專案
剛剛查看來上操作課的使用者帳號裡也出現了大量的相同專案

希望未來可以設定一些機制，例如固定只能送出一次，或是多少秒以內只計算一次
諸如此類

![2018-09-13 2 19 09](https://user-images.githubusercontent.com/34327325/45470500-8f140f00-b760-11e8-8dbb-057656ff0f08.png)

**Comment by AnitaRyzo** [comment]
從套版新增專案，會先跳『執行圖示』，即使有網路延遲也無法繼續新增【使用此套版】
![image](https://user-images.githubusercontent.com/41721950/46389595-6c449d00-c705-11e8-9497-78d0140764c7.png)

**Comment by AnitaRyzo** [comment]
從套版新增專案，會跳『執行圖示』
![image](https://user-images.githubusercontent.com/41721950/47281433-b4bcef80-d60d-11e8-8093-9bc8f6a33a88.png)
◎◎ 20181022確認以上正式環境內容 ◎◎
