### ISSUE TITLE
【問題】查看表單

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#679]
上次有提到查看表單的問題，大概是在說沒有查看表單的選項

前些日子在設定權限時發現，
目前在團隊權限裡的“查看表單”這個權限的啟用狀況，
會影響我能不能看到“表單管理”這個欄位

也就是，只要我沒有開啟查看表單，那麼複製表單、查看回覆、下載回覆，這三個選項都沒辦法使用
查看專案也是一樣的情形

![2018-09-13 2 34 14](https://user-images.githubusercontent.com/34327325/45471326-575a9680-b763-11e8-9016-f3b9f3a75316.png)

![2018-09-13 2 34 06](https://user-images.githubusercontent.com/34327325/45471328-59bcf080-b763-11e8-87ac-ddcfbed6e1b1.png)

可能是因為現在後三個選項都必須是在我能夠查看表單、專案的情況下才可以使用，
但是設定權限的時候，他們卻被放在同一個層級裡進行設定，所以有點不是很合理

可能要設定成外層的“專案查看”、“表單管理”是可以看到表單跟專案的殼，至於能看到內容與否則是由底下的子選項來控制

**Comment by ryzojudy** [comment]
不知道可不可變成
只要勾選後面四個子項的任一個項目
就會顯示入口?
![image](https://user-images.githubusercontent.com/34263719/45526133-870faa00-b808-11e8-8a38-ce5017859364.png)

如果沒有查看的權限的話
在專案的地方就是變成鼠標移上去
變成紅框 同時文字呈現：沒有查看專案權限

**Comment by ryuichl** [comment]
麻煩'幫忙出畫面
感恩
@liucwlewis

**Comment by ai015606220** [comment]
能請教一下，查看表單的定義嗎? 
因為比較不確定的是，這樣改會變成，即使沒有查看表單的權限，也能得知目標使用者的'所擁有的表單清單'
確認一下是這個意思嗎??

**Comment by ryzojudy** [comment]
To Derek
對的 專案那邊也是一樣

**Comment by ai015606220** [comment]
好的

**Comment by ryzojudy** [comment]
@liucwlewis 
另外也需要麻煩把外面那兩欄的文字分別改為
"專案相關"和"表單相關"
![image](https://user-images.githubusercontent.com/34263719/45526890-abb95100-b80b-11e8-8cea-490a7e47e8f9.png)

感謝!!

**Comment by ai015606220** [comment]
OK

**Comment by liucwlewis** [comment]
如圖
<img width="542" alt="2018-09-14 2 04 07" src="https://user-images.githubusercontent.com/37163894/45532558-1e83f580-b827-11e8-82ba-aaf18dbac6fd.png">
位置：https://zpl.io/29yLmrW

**Comment by AnitaRyzo** [comment]
查看、複製、下載的功能，只要左邊黃框中有任一項開啟，右邊專案相關就會成立；綠框與表單相關亦同。
![image](https://user-images.githubusercontent.com/41721950/46392389-cb111300-c713-11e8-87f9-87eff8172564.png)

查看專案權限(藍框有權，紅框無權)
![image](https://user-images.githubusercontent.com/41721950/46389925-99924a80-c707-11e8-85bb-d2765877a7e7.png)
複製專案(黃框)與查看數據(紅框)
![image](https://user-images.githubusercontent.com/41721950/46393345-5b9d2280-c717-11e8-8a28-444972b1e52b.png)
表單相關權限
![image](https://user-images.githubusercontent.com/41721950/46393273-07923e00-c717-11e8-856b-b509f097fdb1.png)
查看回覆(綠框)與下載回覆(黃框)，【下載回覆】的前提是一定要有【查看回覆】的權限
![image](https://user-images.githubusercontent.com/41721950/46393664-baaf6700-c718-11e8-8937-4511f960c730.png)
![image](https://user-images.githubusercontent.com/41721950/46393570-5f7d7480-c718-11e8-8cc1-63d63473a0a7.png)
◎◎ 20181003確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『跨帳號功能』的所有權限
![image](https://user-images.githubusercontent.com/41721950/47330579-56dee500-d6ab-11e8-938e-5b07c78a2012.png)
查看專案權限(藍框有權限，紅框無權限)
![image](https://user-images.githubusercontent.com/41721950/47329664-2ea1b700-d6a8-11e8-954c-1f4c1c4677b3.png)
表單相關權限
![image](https://user-images.githubusercontent.com/41721950/47330079-8ab90b00-d6a9-11e8-8346-a439e73fef6f.png)
查看表單(藍框)、查看回覆(黃框)與下載回覆(綠框)，【下載回覆】的前提是一定要有【查看回覆】的權限
![image](https://user-images.githubusercontent.com/41721950/47330284-3d896900-d6aa-11e8-8c9d-157903eac24a.png)
◎◎ 20181023確認以上正式環境內容 ◎◎
