### ISSUE TITLE
【建議】QR code產生器中 自行輸入網址產出QR的UIUX

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#681]
目前的QRcode產生器 可以輸入網址的地方不太明顯 希望可以再輸入框加入「請輸入網址」的文字
<img width="1218" alt="2018-09-13 4 42 58" src="https://user-images.githubusercontent.com/34560641/45479011-e70a4000-b777-11e8-8248-3ff4ba473e0b.png">

另外 輸入網址後 要產出QR 但是卻沒有按鈕可以按 按enter也沒有反應
發現是要按右下角「複製連結」的按鈕 才會產出新的QR 這個流程有點令人疑惑
<img width="316" alt="2018-09-13 5 11 01" src="https://user-images.githubusercontent.com/34560641/45479145-42d4c900-b778-11e8-8daf-4d4ade0f069d.png">

建議另外新增按鈕/修改圖示/或游標移到按鈕上的提示文字加入「產出QR」

**Comment by eatinggg** [comment]
修改後的流程如下圖～
<img width="746" alt="2018-12-10 11 11 56" src="https://user-images.githubusercontent.com/34293268/49709007-3673e580-fc6d-11e8-9040-c2fb6abf6cd7.png">



@liucwlewis 確認沒問題後會上傳到zeplin

一併附上『產生QR』及『下載QR』的icon連結：
https://drive.google.com/drive/u/1/folders/1UaY1y3kVGuMZq695jpJLFsInXS_7-qy0

**Comment by liucwlewis** [comment]
已上傳
Zeplin連結：https://zpl.io/VOWM0X1
