### ISSUE TITLE
【建議】團隊管理可修改名稱、可排序＋UI調整

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#682]
<img width="189" alt="2018-09-13 5 47 27" src="https://user-images.githubusercontent.com/34560641/45481068-29824b80-b77d-11e8-8fca-aa2f376ce826.png">
建議將系統「確認在右邊」的邏輯一致 將「接受」團隊邀請的按鈕放右邊

建議團隊名稱可以修改

團隊順序可排序

**Comment by ryzojudy** [comment]
擁有團隊管理權限的人可以更改團隊名稱
其他畫面上變動的部分要麻煩 @liucwlewis 出圖了
感謝~

**Comment by liucwlewis** [comment]
如圖
<img width="811" alt="2018-09-14 2 02 09" src="https://user-images.githubusercontent.com/37163894/45532485-d1078880-b826-11e8-9924-5239e98308fc.png">

位置：https://zpl.io/29yLmrW

**Comment by ai015606220** [comment]
按鈕位置、修改團隊名稱
這兩項已完成，
自訂排序這項功能比較麻煩，還在設計中
