### ISSUE TITLE
【測試環境】圖片的濾鏡設定無法在IE顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#683]
圖片使用濾鏡設定
![image](https://user-images.githubusercontent.com/41721950/45525422-6f82f200-b805-11e8-9add-50e4e512b900.png)
左邊為正常顯示濾鏡設定後的顏色，右邊為IE顯示圖片原色
![image](https://user-images.githubusercontent.com/41721950/45525435-7dd10e00-b805-11e8-860e-779d5d4b33de.png)
以上問題請協助處理，謝謝~

**Comment by Gabe-Liu** [comment]
目前IE瀏覽器無法支援濾鏡效果

**Comment by Gabe-Liu** [comment]
加入提醒標語

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/45676528-86f30f80-bb64-11e8-91a1-6438dc104ac9.png)
◎◎ 20180918確認以上測試環境內容 ◎◎
