### ISSUE TITLE
【問題】社群分享設定在瀏覽器執行有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#684]
『社群分享設定』如下
![image](https://user-images.githubusercontent.com/41721950/45610765-b1bf6400-ba8f-11e8-9080-9046873349a5.png)

※FACEBOOK 皆可執行，GOOGLE+只有網址
![image](https://user-images.githubusercontent.com/41721950/45609458-aae22280-ba8a-11e8-9bfe-9dde1b769a62.png)

※LINE ：在IE執行時沒有顯示圖案、社群分享標題與摘要
![image](https://user-images.githubusercontent.com/41721950/45610977-71141a80-ba90-11e8-8ae0-819bd56ee004.png)

※Twitter ：所有瀏覽器皆同畫面
![image](https://user-images.githubusercontent.com/41721950/45611012-956ff700-ba90-11e8-9bf2-596426b0a9db.png)

※Linkedin ：只有在IE執行有誤
![image](https://user-images.githubusercontent.com/41721950/45611044-b1739880-ba90-11e8-8a8d-8328d44d389e.png)

※Pinterest ：電腦版只有在IE執行有誤，手機版只有顯示框，無圖案無描述
![image](https://user-images.githubusercontent.com/41721950/45611110-d8ca6580-ba90-11e8-9402-de64be4abd1e.png)

以上疑問請協助處理，謝謝~

**Comment by Gabe-Liu** [comment]
twitter的分享meta要另外設定：
<meta name="twitter:title" content="Top 10 Things Ever">
<meta name="twitter:description" content="Up than 200 characters.">
<meta name="twitter:image" content="http://placekitten.com/250/250">
<meta name="twitter:domain" content="YourDomain.com">

**Comment by ryuichl** [comment]
twitter 修改 OK
再麻煩 @AnitaRyzo  幫忙測試

**Comment by Gabe-Liu** [comment]
剛再次確認，Linkedin 和 pinterest的分享連結已經更新與我們的不一樣，但在IE以外的瀏覽器會自動導到新的連結。 會再修正分享的連結。
google+還在尋找問題

**Comment by Gabe-Liu** [comment]
google+ 已解決

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/46518405-89fd3800-c8a6-11e8-92ae-810c6871b115.png)
twitter登入推文之後，頁面會自動關閉
pinterst無法執行：電腦版IE瀏覽器與手機版瀏覽器(Chrome、Safari、Firefox、FB、Line、Edge、Opera)
◎◎ 20181005確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
twitter登入推文之後
![image](https://user-images.githubusercontent.com/41721950/46590019-9a99f200-cae2-11e8-92fc-c82ff3133fbb.png)
pinterst已可正常執行
圖片上傳的部分，每個瀏覽器都需要不同的更新時間才能跟得上正確的圖片
◎◎ 20181008確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
※※※ 社群分享僅能在『發佈後環境』中執行 ※※※
『社群分享設定』如下
![image](https://user-images.githubusercontent.com/41721950/47328374-7f62e100-d6a3-11e8-8358-487cd6435c12.png)
FACEBOOK 皆可執行，GOOGLE+登入後重整網址即可
![image](https://user-images.githubusercontent.com/41721950/47328668-758dad80-d6a4-11e8-8d41-0b7ab426c2d7.png)
LINE皆可執行，PINTEREST僅能抓出網頁中有的圖片
![image](https://user-images.githubusercontent.com/41721950/47328774-f2208c00-d6a4-11e8-838f-e155a44f315d.png)
TWITTER與LinkedIn在所有瀏覽器皆同畫面
![image](https://user-images.githubusercontent.com/41721950/47328918-622f1200-d6a5-11e8-8158-cae55f59464a.png)
當社群分享社定的文字或圖片更新時，在每個瀏覽器都需要不同的更新時間才能跟得上正確的圖片
◎◎ 20181023確認以上正式環境內容 ◎◎
