### ISSUE TITLE
【問題】專案數據

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#685]
專案在未申請審核以前,會出現暫無數據的文字

但只要申請審核(尚未通過審核),點選數據就會無限LOADING

**Comment by Gabe-Liu** [comment]
待測試站更新至正式站時，再試試看

**Comment by AnitaRyzo** [comment]
不管是【專案審核】未通過，或是【套版審核】未通過，Loading三秒左右會顯示『暫無數據』
![image](https://user-images.githubusercontent.com/41721950/46394486-d6683c80-c71b-11e8-93a1-c4e3a102082b.png)
![image](https://user-images.githubusercontent.com/41721950/46394572-19c2ab00-c71c-11e8-954c-21e1df3fa9f0.png)
◎◎ 20181003確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
不管是【專案管理】未通過，或是【套版申請】未通過，Loading三秒左右會顯示『暫無數據』
橘點：審核中　　　　　　　　　　　　　紅點：審核未通過
![image](https://user-images.githubusercontent.com/41721950/47332635-7594aa00-d6b2-11e8-9feb-a5a501a44f74.png)
◎◎ 20181023確認以上正式環境內容 ◎◎
