### ISSUE TITLE
【問題】圖片上傳

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#697]
上傳圖片的過程中
如果還沒上傳好，我就新增一個新的圖片元件
圖片會直接被上傳到新的圖片元件裡
舊的則是持續loading

![2018-09-27 5 09 17](https://user-images.githubusercontent.com/34327325/46135575-1b9df180-c278-11e8-9452-4d1e1112ecc8.png)

**Comment by AnitaRyzo** [comment]
上傳圖片的過程時，若尚未上傳完成就新增新的圖片元件，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/46452048-41714c00-c7cc-11e8-8172-95818c0a1a54.png)

上傳第一張圖片的同時，同時上傳第二張圖片，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/46451978-d9226a80-c7cb-11e8-95bd-1743ad9406ac.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
上傳圖片的過程時，若尚未上傳完成前，新增新的圖片元件，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/47344318-c6b89400-d6da-11e8-83a7-25dba5476013.png)
同時上傳圖片與輪播圖，圖片也不會互相影響
![image](https://user-images.githubusercontent.com/41721950/47344066-25314280-d6da-11e8-87a4-bea44e174916.png)
◎◎ 20181023確認以上正式環境內容 ◎◎
