### ISSUE TITLE
【問題/建議】提示中若有連結至頁面錨點 提示本身是不是可以自動關閉？

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#700]
如題
提示中若有連結至頁面錨點 提示本身是不是可以自動關閉？
可參考此專案

[https://ins.ryzoweba.io](https://ins.ryzoweba.io)

**Comment by ryzojessie** [comment]
[https://www.fubon.com/insurance/b2c/campaign/lottery/index.html#](https://www.fubon.com/insurance/b2c/campaign/lottery/index.html#)
亦可以參考此網頁的「活動辦法」提示

**Comment by ryzojudy** [comment]
如果可以的話
是否就是只要點擊提示內任何帶有連結的元件 提示就直接關閉?

**Comment by ryuichl** [comment]
如果連結是另開分頁是否就不會想要直接關掉

**Comment by ryzojudy** [comment]
剛剛跟gabe確認了一下
改成
跟頁面相關的(錨點、換頁等) 就直接點擊後關閉

其他的就都照舊~~
連結的部分
(另開分頁不需要關 直接換畫面就也不用管關不關的問題)
電話跟電子郵件 也是另開的
提示連提示 也會直接關閉舊的提示

**Comment by AnitaRyzo** [comment]
頁面相關的(錨點、換頁等) 直接點擊後，會自動關閉提示頁
外部網頁、電話、電子郵件會另開分頁，提示頁之間可以關舊提示頁，更換新提示頁
![image](https://user-images.githubusercontent.com/41721950/46458380-257ba380-c7e8-11e8-8605-b8f71fe4f748.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
頁面相關的(錨點、換頁等) 直接點擊後，會自動關閉提示頁
外部網頁、電話、電子郵件會另開分頁，提示頁之間可以關舊提示頁，更換新提示頁
![image](https://user-images.githubusercontent.com/41721950/47349924-3fbde880-d6e7-11e8-8739-b97aaa3f37ce.png)
◎◎ 20181023確認以上正式環境內容 ◎◎
