### ISSUE TITLE
【問題】輪播圖切換圓點

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#701]
放置在提示裡的輪播圖，
切換圓點選項為開啟，在編輯模式中沒問題，
但預覽的時候不會顯示圓點樣式

![2018-10-01 5 24 43](https://user-images.githubusercontent.com/34327325/46280686-21107a00-c59f-11e8-9a51-75be0cea18b6.png)

**Comment by AnitaRyzo** [comment]
預覽畫面已依照【輪播區塊設定】執行
![image](https://user-images.githubusercontent.com/41721950/46459351-3843a780-c7eb-11e8-9def-2019e7e12731.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
預覽畫面已依照【輪播區塊設定】執行
![image](https://user-images.githubusercontent.com/41721950/47350792-43526f00-d6e9-11e8-8504-0963eac5a811.png)
◎◎ 20181023確認以上正式環境內容 ◎◎
