### ISSUE TITLE
【問題】專案預覽圖

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#702]
原先的預覽圖可以經由重新整理後，重新抓取
但是剛剛發現重新整理後沒有反應，依然維持原先舊的預覽圖

除了影響專案管理外，套版的截圖可能也會一併受影響，再麻煩協助處理

**Comment by ryuichl** [comment]
現在有快取機制
你沒辦法透過重整看到新的
要看到新的你可以嘗試清除快取

**Comment by weilyn** [comment]
無痕視窗確認OK


如果我看到的畫面是A，無痕視窗是B
那專案如果申請套版的時候，套版會顯示我當前看到的A預覽圖，還是最新的B預覽圖呢？
使用者觀看會有影響嗎

**Comment by ryuichl** [comment]
會是最新的
你看到A是因為瀏覽器先把圖片存在你的電腦
但是後台的圖片已經是B
所以當申請樣版後截圖會是最新的B

**Comment by weilyn** [comment]
好 那就沒問題了 謝謝
