### ISSUE TITLE
[測試環境] 表單換頁動畫

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#703]
![image](https://user-images.githubusercontent.com/10150807/46388320-f6890300-c6fd-11e8-8a5a-72f596792e18.png)

有兩個翻轉效果
感覺是沒翻好?

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/46459770-6aa1d480-c7ec-11e8-8fe8-e4b7f85d2e89.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/47351449-911ba700-d6ea-11e8-96f2-8ef366308204.png)
◎◎ 20181023確認以上正式環境內容 ◎◎
