### ISSUE TITLE
【問題】邀請多位成員加入群組時，前面的選取處已勾選卻沒真的加入成員

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#704]
在邀請多位成員加入團隊時，第一位成員已勾選後，點到空白處(此時勾選仍然存在)，選擇第二位成員並按送出邀請後，發現只有第二位成員被邀請加入團隊。
再麻煩協助確認，謝謝~

**Comment by wendykuo** [comment]
剛剛討論了之後，覺得按下shift或ctrl沒有這麼直覺，一般使用者比較不會在這裡使用到，建議加入使用者時點任何地方都是確定勾選的~

**Comment by ai015606220** [comment]
目前改成，只有點選取框(勾勾)才會選取，點其他格子不會有反應，ctrl和shift的功能還是有保留

**Comment by wendykuo** [comment]
好的，那就依這個方式進行，謝謝~

不過希望前面的選取框有點小，怕選取時不好選，希望可以讓它長大一點，拜託~

**Comment by ai015606220** [comment]
我有想到解決方法了，待日後上線

**Comment by AnitaRyzo** [comment]
連續點選的方法
舊有的：要按紅框處才能連續點選，或是按下shift或ctrl再點選
更新後：黃框任一處點選皆可連續點選
PS: 但若按『專案相關、表單相關、帳號編輯』的位置，會連結到相關頁面；返回此頁面時，點選的編號仍是被選取的。
![image](https://user-images.githubusercontent.com/41721950/46461968-ad66ab00-c7f2-11e8-8b84-6237f74c68cf.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
黃框任一處點選皆可連續點選
若按『專案相關、表單相關、帳號編輯』的位置，會連結到相關頁面；返回此頁面時，點選的編號仍是被選取的。
![image](https://user-images.githubusercontent.com/41721950/47399593-cb795880-d76b-11e8-9b2b-cd6aaeb80137.png)
◎◎ 20181024確認以上正式環境內容 ◎◎
