### ISSUE TITLE
【問題】下拉式選單的選項數量限制取消

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#705]
下拉式選項目前最多只能填10個選項，希望選項不要有數量限制

**Comment by ai015606220** [comment]
@ryzojudy 忘記當初是規格書要求還是我自己加上的，目前下拉選項最多是10個，請問你覺得需要上修嗎? 需要上修到多少?

**Comment by ai015606220** [comment]
已修改，等待上測試站，不過得提醒一下，如果使用者真的新增了非常多的選項，也許會有些效能上的疑慮

**Comment by AnitaRyzo** [comment]
下拉選項的項目數量原為10項(左圖)，後更改無限制(右圖)
![image](https://user-images.githubusercontent.com/41721950/46460303-1992e000-c7ee-11e8-9cc2-f4a9946be6e9.png)
◎◎ 20181004確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
下拉選項的項目數量更改為無限制，如下圖
![image](https://user-images.githubusercontent.com/41721950/47400325-44c67a80-d76f-11e8-9bff-e4625c9af7ae.png)
◎◎ 20181024確認以上正式環境內容 ◎◎
