### ISSUE TITLE
【建議】希望表單送出後 可以跳轉到指定畫面

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#708]
目前的表單送出後
會有短暫的回覆區塊 一下就消失了
希望可以跳轉到指定的畫面
讓填表流程的結尾可以導向到指定目的地
（目前折衷做法是利用按鈕吸引用戶點擊後 以錨點或連結另外連接 但仍須使用者自行選擇性點擊 無法流暢顯示想要指定的結果）

使用場景
ex1. 填表參加抽獎 --> 跳轉到中獎公布網址/頁面 or 查看其他注意事項
ex2. 購物後/申辦後滿意度調查 --> 填完出現「感謝填寫」，並跳轉到其他相關推薦產品/服務

以上 歡迎增加其他場景or提出討論

**Comment by ryzojudy** [comment]
	於表單元件的右側控制欄「按鈕設定」中，多「連結設定」
	連結設定：以勾選的方式決定
-	不可新增多個連結
-	可選擇的連結項目為-連結、頁面、提示

沒有問題的話 一樣請 @liucwlewis 協助出圖

**Comment by ryuichl** [comment]
建議做成自由一點
不用侷限在連結
call to action可以有很多種
可能是轉連到某個地方 可能是關掉提示頁 可能甚麼都不做
未來甚至做成填完表單可以多玩一次抽獎

**Comment by ryzojudy** [comment]
	於表單元件的右側控制欄「按鈕設定」中，多「送出後執行動作」的區域設定
	送出後執行動作：以勾選的方式選擇動作，根據勾選的項目出現該動作的項目設定
-	預設(感謝填表的跳出視窗)
-	連結設定
	連結項目：連結、頁面、提示
	不可新增多個連結
-	關閉提示頁
-	抽獎限制次數新增
	抽獎次數：單位-次/天
	每人每天最多抽中：單位-次
	每人最多抽中：單位-次
*與互動元件抽獎設置相同
-	未來若有其他需要可在新增


改成這樣的話呢?

**Comment by ryuichl** [comment]
OK
不過跟抽獎連動的部分先不做 呵

**Comment by ryzojudy** [comment]
好的 那就麻煩 @liucwlewis 協助畫面的部分了

**Comment by liucwlewis** [comment]
這四個issue的畫面都有關連，所以畫再一起一次說明
#707 ：
進度條新增開關
<img width="460" alt="2018-12-12 11 31 15" src="https://user-images.githubusercontent.com/37163894/49845382-74097780-fe01-11e8-9ac1-a398c852417e.png">
#708 ：
新增送出後執行動作的設定
<img width="1233" alt="2018-12-12 11 32 19" src="https://user-images.githubusercontent.com/37163894/49845433-ab782400-fe01-11e8-96a7-aca99c4be47b.png">
#838：
新增“色彩參考”，之後會提供不同的顏色組合。原本直接顯示的色彩設定都藏在進階設定中。
“選擇主題樣式包”將顏色部分拿掉，有重新規劃樣式
<img width="217" alt="2018-12-12 11 30 13" src="https://user-images.githubusercontent.com/37163894/49845363-56d4a900-fe01-11e8-89a1-1c42a2ff34e5.png">
<img width="784" alt="2018-12-12 11 57 56" src="https://user-images.githubusercontent.com/37163894/49846228-3c9cca00-fe05-11e8-988e-3786d2adeb72.png">
#861 :
介面微調，直接參考圖片
<img width="227" alt="2018-12-12 11 32 44" src="https://user-images.githubusercontent.com/37163894/49845555-1c1f4080-fe02-11e8-96ca-2317b7e2eca4.png">

確切的設定直接看Zeplin內容
連結：https://zpl.io/andOARx

**Comment by wilmaftliu** [comment]
現在表單填寫送出後可以跳轉了
但是互動填表後還是不可以跳轉 希望互動型也可以
