### ISSUE TITLE
【建議】裝飾區塊元件尺寸

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#714]
裝飾區塊元件尺寸目前最小單位為10px
但是因為目前系統沒有線段類型的元件，
所以只能用裝飾區塊來設計

目前10以下要手動輸入數值，並且如果過程有手動調整尺寸，小於10px的數值會跳回10px

希望可以開放至1px
或是推出線段類型的元件

**Comment by Gabe-Liu** [comment]
可開放調整至1px，
至於線段元件待未來開發。

**Comment by AnitaRyzo** [comment]
裝飾區塊元件尺寸用滑鼠直接拉放的尺寸
由原先最小10px減少至1px
![image](https://user-images.githubusercontent.com/41721950/47056878-edfdf580-d1f0-11e8-8e1e-3ec093406594.png)

◎◎ 20181017確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
裝飾區塊元件的寬與高，使用滑鼠直接拉放的最小尺寸為1px
![image](https://user-images.githubusercontent.com/41721950/47404699-e73b2980-d780-11e8-825e-4e3cdef64778.png)
◎◎ 20181024確認以上正式環境內容 ◎◎
