### ISSUE TITLE
【問題】輪播圖圓點

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#716]
輪播圖上傳大量照片時，
在編輯模式中只呈現6個
但是在預覽模式中會全部出來

建議無論圖片多少張，一次都只顯示5-6個點

![2018-10-08 4 50 25](https://user-images.githubusercontent.com/34327325/46599704-9a1d4d80-cb1a-11e8-81b6-ad7d66751050.png)

![2018-10-08 4 50 37](https://user-images.githubusercontent.com/34327325/46599710-9d183e00-cb1a-11e8-9b22-0cebcbae18ce.png)

![2018-10-08 4 53 02](https://user-images.githubusercontent.com/34327325/46599721-a6090f80-cb1a-11e8-83ac-40fb4a0c2cb4.png)

**Comment by ryuichl** [comment]
點點是可以拿來切換的
所以只秀6個點並不現實
建議你把點點關掉

**Comment by weilyn** [comment]
我在網路上碰過許多很多張圖片的輪播圖，當我看到第六張的時候，他的第六個點會變成第七張圖片；看到第七張時，第六個點會變成第八張圖片，以此類推，底下的點其實是有在滾動的

此外，目前關閉圓點以後，預覽模式仍然會顯示圓點

**Comment by AnitaRyzo** [comment]
只有【切換箭頭】或只有【切換原點】皆可正常顯示
![image](https://user-images.githubusercontent.com/41721950/46845429-0dbaa580-ce0e-11e8-880c-0a46ba08e02a.png)
◎◎ 20181012確認以上測試環境內容 ◎◎

**Comment by ryzojudy** [comment]
我覺得顯示固定的輪播點不錯
想請教 @Gabe-Liu 
如果今天輪播圖的寬度較窄
是不是也會出現輪播點出現第二列的情形發生??
(假設我固定顯示5個 但實際寬度只能容納3個時)
還是可以根據輪播元件的寬度系統自動決定顯示的數量點呢??

**Comment by ryzojudy** [comment]
比如 接近兩邊的邊距幾px就不會有數量點出現 這種設定方式?

**Comment by ryzojudy** [comment]
剛剛已經跟gabe確認過
不能根據元件的大小 自動顯示多少個輪播點
最大的輪播點數量可以設定到五個
如果元件的寬度太窄 也是會有到第二排的狀況
以上
如果 @weilyn 沒有問題的話
就麻煩 @Gabe-Liu 將輪播點顯示的最大數量改為5個

**Comment by AnitaRyzo** [comment]
只有【切換箭頭】或只有【切換原點】皆可正常顯示
◎◎ 20181123確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
圓點數量為動態的，前後圖片只顯示三個點，中間圖片會顯示五個點
只有【切換箭頭】或只有【切換原點】皆可正常顯示，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/49206270-770d6c80-f3ec-11e8-99d8-564584fe50b6.png)
◎◎ 20181129確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
輪播圖的圓點數量是動態的，前後圖片只顯示三個點，中間圖片會顯示五個點
只有【切換箭頭】或只有【切換原點】皆可正常顯示，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/51231383-51d5bd00-199e-11e9-9691-4822ca7a11bd.png)
◎◎ 20190116確認以上正式環境內容 ◎◎
