### ISSUE TITLE
【問題】團隊名稱過長

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#717]
團隊管理區的團隊名稱過長造成跑版

目前WEBA裡可能沒有這個機制，但通常如果因為字數太長而被收合為....時，當游標移過去可能會出現完整名稱的氣泡窗，因為使用者可能還是會需要知道完整的名稱

有些情景大家會在名稱前加入一些前綴詞

例如景宜業務部-XXX專案
景宜業務部-ZZZZ專案

這種時候很容易出現字數超過的情況，但如果只顯示前面幾個字是沒有辦法讓人分辨出差異的
供你們參考

**Comment by weilyn** [comment]
![2018-10-08 5 44 15](https://user-images.githubusercontent.com/34327325/46602295-53335600-cb22-11e8-9bd9-90d104c15ada.png)

**Comment by weilyn** [comment]
不然就是要直接限制團隊名字長度

**Comment by AnitaRyzo** [comment]
團隊名稱過長將顯示『...』
![image](https://user-images.githubusercontent.com/41721950/46775670-c57e8300-cd3a-11e8-8bb8-93688434c7e8.png)
◎◎ 20181011確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
團隊名稱過長將顯示『...』
![image](https://user-images.githubusercontent.com/41721950/47405032-49e0f500-d782-11e8-8462-467f821bb044.png)
◎◎ 20181024確認以上正式環境內容 ◎◎
