### ISSUE TITLE
【建議】希望WEBA專案管理中的專案 可以分類並置入資料夾中

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#719]
參考Google drive
希望可以讓用戶主動將專案分類
並放在不同的資料夾中（可命名、修改名稱、刪除）
方便專案數量增加時可以進行管理

**Comment by ryzojudy** [comment]
這件事之前就有安排囉

**Comment by liucwlewis** [comment]
位置：https://zpl.io/bPXrm0y
![default](https://user-images.githubusercontent.com/37163894/49926343-4f42fc00-fef6-11e8-8f14-5d2d07cac88f.jpg)
