### ISSUE TITLE
【問題】已下架套版燈號

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#720]
hi
如圖，已下架套版仍然呈現綠色燈，並標示發布中

![2018-10-09 2 12 34](https://user-images.githubusercontent.com/34327325/46649963-88e14900-cbcd-11e8-8c13-f8ccfadb3f03.png)

右邊的套版在10.8自動下架了，但燈號顯示發布中
在套版選擇區裡確認，已經不會顯示在套版選項之中

**Comment by AnitaRyzo** [comment]
若套版已下架不會出現燈號(如右圖的紅框)
![image](https://user-images.githubusercontent.com/41721950/46775851-9e748100-cd3b-11e8-8c04-8d327bfbec6d.png)
◎◎ 20181011確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
發佈開啟時間內以綠燈表示(如綠框)，時間之外無燈號(如紅框)
![image](https://user-images.githubusercontent.com/41721950/46776129-d203db00-cd3c-11e8-8879-d02668183549.png)

同場疑問：
套版管理顯示的開啟時間設定是否可以即時更新??
目前的狀況是要切到別的頁面再回來，時間才會跳制定的時間
![image](https://user-images.githubusercontent.com/41721950/46776246-59e9e500-cd3d-11e8-9380-ddd9d32fa28e.png)

◎◎ 20181011確認以上測試環境內容 ◎◎

**Comment by ai015606220** [comment]
同場疑問已完成

**Comment by AnitaRyzo** [comment]
發佈開啟時間內以綠燈表示(如綠框)，時間之外無燈號(如紅框)
![image](https://user-images.githubusercontent.com/41721950/47409070-3ccd0180-d794-11e8-9161-fe8fdbf8806b.png)

套版管理的時間設定，在關掉對話視窗的同時，同步更新套版上顯示的時間
![image](https://user-images.githubusercontent.com/41721950/47409249-c250b180-d794-11e8-8806-6b6cf6c18dfb.png)
