### ISSUE TITLE
【請求修改】新版中文WEBA驗證信文案

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#726]
請將驗證信相關訊息改成下列文字與排版：

寄件人：WEBA
主旨：請驗證您的電子郵件地址

內文：
![default](https://user-images.githubusercontent.com/34560641/46787433-26717f80-cd6a-11e8-8c33-84ba53f8958c.png)

再麻煩 @ryzojudy 協助修改文案
文字檔請 無法被tag的平民百姓紀緯補充 感恩

**Comment by weilyn** [comment]
文字在此

https://docs.google.com/document/d/1fa_K2_UOXXF1z0TjBjajEfjQKlX3W4mXwFkkd85Zv4w/edit?usp=sharing

**Comment by ryzojudy** [comment]
@liucwlewis

**Comment by ryzojudy** [comment]
請幫忙協助將文字改成：

最後步驟！

請點擊下方按鈕，以驗證您的電子信箱，我們將完成開通您的 WEBA 帳號。


驗證您的電子信箱

如果點擊按鈕後無法開啟連結，
請複製以下連結並貼到新瀏覽器視窗中：

https://ryzoweba.io/client/signin/verify/5bbac19b9a625b703c7b7fdb

若您從未註冊過WEBA帳號，很可能有人意外輸入您的電子郵件地址，請直接忽略此訊息。

WEBA 團隊敬上  https://ryzo.io


此信件由系統自動寄發，請勿直接回覆。


關於畫面部分 請 @liucwlewis  幫忙協助看是否有需要再修正的部分

**Comment by ryzojudy** [comment]
之前有出過一次
![image](https://user-images.githubusercontent.com/34263719/46790131-c5997580-cd70-11e8-8063-af526d3402d9.png)

裡面的文字改成下方內容：
感謝您註冊成為WEBA會員！ 

為啟動您的會員帳號，
請點擊以下按鈕連結：

驗證您的電子信箱

如果點擊按鈕後無法開啟連結，
請複製以下連結並貼到新瀏覽器視窗中：

https://ryzoweba.io/client/signin/verify/5bbac19b9a625b703c7b7fdb

若您從未註冊過WEBA帳號，很可能有人意外輸入您的電子郵件地址，請直接忽略此訊息。

WEBA 團隊敬上 https://ryzo.io
此信件由系統自動寄發，請勿直接回覆。


不知道這樣的話 @wilmaftliu  @weilyn  可不可以接受呢?

**Comment by ryuichl** [comment]
這要改的話
重設密碼信
順便看一下
感恩 @ryzojudy

**Comment by ryzojudy** [comment]
![image](https://user-images.githubusercontent.com/34263719/46792219-743fb500-cd75-11e8-9708-b32d5b1dd612.png)

文字修改如下：

您好，您最近針對WEBA的帳號申請更改密碼，
請點擊以下按鈕連結：

修改密碼

如果點擊按鈕後無法開啟連結，
請複製以下連結並貼到新瀏覽器視窗中：
https://ryzoweba.io/client/signin/reset-password/dbd3902c5161a5697081577f8ddcefd704a0548c
若您從未申請修改密碼，請直接忽略此訊息。

WEBA 團隊敬上 https://ryzo.io
此信件由系統自動寄發，請勿直接回覆。

**Comment by ryzojudy** [comment]
@liucwlewis 
要麻煩你調一下畫面~
把下方的按鈕移到上面
另外新增聯結

**Comment by ryzojudy** [comment]
驗證信
主旨：請驗證您的電子郵件地址

修改密碼
主旨：WEBA帳號密碼修改

**Comment by AnitaRyzo** [comment]
驗證信
主旨：請驗證您的WEBA帳號
![image](https://user-images.githubusercontent.com/41721950/47075021-31c32000-d22e-11e8-9a22-7f708da62369.png)

修改密碼
主旨：重設您的WEBA密碼
![image](https://user-images.githubusercontent.com/41721950/47075422-1dcbee00-d22f-11e8-8b3f-01c40a8a9b8e.png)
◎◎ 20181017確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
驗證信
![image](https://user-images.githubusercontent.com/41721950/47279016-1d9d6b00-d600-11e8-93a2-8bbc69441450.png)
修改密碼
![image](https://user-images.githubusercontent.com/41721950/47279021-3148d180-d600-11e8-81a0-25e218acb71d.png)
◎◎ 20181022確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
驗證信
![image](https://user-images.githubusercontent.com/41721950/47279016-1d9d6b00-d600-11e8-93a2-8bbc69441450.png)
修改密碼
![image](https://user-images.githubusercontent.com/41721950/47279021-3148d180-d600-11e8-81a0-25e218acb71d.png)
◎◎ 20181022確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
業務要求如下紅框文字也要置中，請協助處理，感恩~
![image](https://user-images.githubusercontent.com/41721950/47280827-cea90300-d60a-11e8-8c53-585b586832da.png)

**Comment by AnitaRyzo** [comment]
可否將紅框內的字與其他文字相同配置的置中呢??
![image](https://user-images.githubusercontent.com/41721950/47283423-f6ea2f00-d615-11e8-8089-0f27ce51cf5f.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
這個置底會影響到全部的信
所以我覺得保持現狀就好

**Comment by weilyn** [comment]
OK， 昨天跟wilma討論過覺得維持現狀也沒關係
