### ISSUE TITLE
【問題】日期題型增加時間後，帶入後台資料有誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#727]
日期的題型可以增加時間選項
![image](https://user-images.githubusercontent.com/41721950/46789968-663b6580-cd70-11e8-9dd0-b220cc7320fb.png)
但在執行時，填寫問卷的人看到的答案與後台不同
若先擇取日期(黃框)，時間會由系統帶入，更改問卷內的時間也不會帶入後台；
若先擇取時間(綠框)，日期會由系統帶入，更改問卷內的日期也不會帶入後台。
![image](https://user-images.githubusercontent.com/41721950/46789857-24122400-cd70-11e8-9fa8-c710fd85b610.png)

附屬疑問：矩陣題型與其他題目的間距是否有點大呢??
![image](https://user-images.githubusercontent.com/41721950/46786094-6fbfd000-cd66-11e8-9613-c71521cf30bf.png)
以上問題請協助處理，感恩~

**Comment by ai015606220** [comment]
日期時間問題已解決，附屬疑問已修正但尚未上測試站

**Comment by AnitaRyzo** [comment]
日期題型的答案，已依照設定寫入後台
![image](https://user-images.githubusercontent.com/41721950/46937231-4fa84d80-d093-11e8-8425-03d872c35afe.png)
矩陣題型的題目間距已修改如下
![image](https://user-images.githubusercontent.com/41721950/46937185-238ccc80-d093-11e8-90eb-1c253c8677f1.png)
◎◎ 20181015確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
日期題型的答案，已依照設定寫入後台
![image](https://user-images.githubusercontent.com/41721950/47415407-eff22680-d7a5-11e8-8f8b-88bcdc773ba5.png)
矩陣題型的題目間距已修改如下
![image](https://user-images.githubusercontent.com/41721950/47415825-f503a580-d7a6-11e8-8899-1b8aa1cbfdca.png)
◎◎ 20181024確認以上正式環境內容 ◎◎
