### ISSUE TITLE
【頁面管理】希望建立頁面時，順道建立一個幻燈片在下方

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#73]
希望建立頁面時，順道建立一個幻燈片在下方

<img width="416" alt="2018-05-08 11 43 26" src="https://user-images.githubusercontent.com/37163894/39736919-1e222bac-52b5-11e8-9ebf-342dfac76727.png">

**Comment by Gabe-Liu** [comment]
待下次更新
