### ISSUE TITLE
【建議】編輯狀態與預覽狀態的裝置切換位置一致

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#732]
希望能與編輯狀態一致，固定置於頂部做切換，避免電腦版畫面太雜時，找不到切換位置。
![2018-10-19 9 56 54](https://user-images.githubusercontent.com/37163894/47193456-92b13c00-d385-11e8-9671-172a8d92c35c.png)
![2018-10-19 9 57 05](https://user-images.githubusercontent.com/37163894/47193459-93e26900-d385-11e8-8876-1044f830a98d.png)

**Comment by ryuichl** [comment]
看不是很懂耶
可以解釋簡單一點嗎 
感恩

**Comment by liucwlewis** [comment]
預覽畫面我想這樣改
<img width="872" alt="2018-10-19 12 04 54" src="https://user-images.githubusercontent.com/37163894/47197223-5b4b8b00-d397-11e8-9f18-546ea625eb6b.png">

**Comment by AnitaRyzo** [comment]
預覽時切換『手機版』與『電腦版』的位置如綠框
![image](https://user-images.githubusercontent.com/41721950/51231648-30c19c00-199f-11e9-8fb6-bd010b1eb1bb.png)
◎◎ 20190116確認以上正式環境內容 ◎◎
