### ISSUE TITLE
【問題】群組物件在框架會有bug

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#734]
原先有群組的物件在框架上沒有正確執行：**電腦版上有正常跟著頁面滾動 但手機上看卻沒有**
後來測試將群組解散之後 物件在無論電腦版或手機上看皆有正確跟著頁面滑動

ps.已經跟gabe說過溜～

參考此專案 [https://bean.ryzoweba.io](https://bean.ryzoweba.io)（已經修改完成）

**Comment by AnitaRyzo** [comment]
已測試手機版本Chrome、Firefox、Safari、Edge、FB、Line
群組後皆有正確跟著頁面滑動
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已測試手機版本，物件群組後皆有正確跟著頁面滑動
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已測試手機版本，物件群組後皆有正確跟著頁面滑動
◎◎ 20181123確認以上正式環境內容 ◎◎
