### ISSUE TITLE
【測試環境】表單的英文提示訊息在瀏覽器顯示錯誤

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#735]
英文語系測試，左邊為手機與電腦版的【瀏覽器】，右邊為【預覽】
在【瀏覽器】皆顯示中文，在【預覽】與【編輯頁面】皆顯示英文
![image](https://user-images.githubusercontent.com/41721950/47210592-f0fe0f00-d3c5-11e8-9e87-9940306bd8b9.png)
單選題、複選題、線性評分、手勢選答 
![image](https://user-images.githubusercontent.com/41721950/47210213-ed1dbd00-d3c4-11e8-9623-7423f6f9b402.png)
日期題有設定為"必填題"，但是未填不會有提示訊息
![image](https://user-images.githubusercontent.com/41721950/47210250-0e7ea900-d3c5-11e8-898a-fcfd0b000cdd.png)
PS: 提示訊息在不同題目類型寫的不同，以此三種題目作代表
以上問題請協助處理，感恩~

**Comment by Gabe-Liu** [comment]
發布後的表單內容主要是根據瀏覽器的語系，因此你要把瀏覽器語系設定改成英文的試試~

**Comment by AnitaRyzo** [comment]
進度條與時間提示皆改英文語系
![image](https://user-images.githubusercontent.com/41721950/47974848-69631080-e0e6-11e8-8cc2-5a3e178671b2.png)
But! 日期題型設定為必選題，未填資料卻無紅字提示訊息
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
進度條、時間提示與紅字提示訊息皆正確顯示
![image](https://user-images.githubusercontent.com/41721950/50578824-ea861c00-0e79-11e9-9b11-0df46d38fdc7.png)
◎◎ 20190102確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
語系控制有兩種方法
A. 修改瀏覽器設定：Chrome、OPERA、FIREFOX、
B. 修改控制台設定：Edge、Safari
IE不管設定控制台與瀏覽器的語言皆無法呈現英文
進度條、時間提示與紅字提示訊息皆正確顯示
◎◎ 20190116確認以上正式環境內容 ◎◎
