### ISSUE TITLE
【問題】下載專案中發現系統內元件

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#738]
（紀緯github疑似被停權 Wilma代PO）

美好的早晨，大家好

李組長今早使用了下載專案的功能，發現大小動輒3XMB，發現案情並不單純
打開資料夾，發現把小積木裡的素材圖，介面icon，全都下載下來了

還請工程部的大人們協助查明真相
![2018-10-22 9 49 02](https://user-images.githubusercontent.com/34560641/47275334-fdaa7f00-d5e0-11e8-9e1c-928c1196d75d.png)
![2018-10-22 9 49 34](https://user-images.githubusercontent.com/34560641/47275335-000cd900-d5e1-11e8-8782-bed86acaf509.png)
![2018-10-22 9 49 22](https://user-images.githubusercontent.com/34560641/47275337-026f3300-d5e1-11e8-8d28-9fc1c41b9bc6.png)

**Comment by ryuichl** [comment]
done
