### ISSUE TITLE
【提示頁最終樣】提示頁的最終樣貌，詳細內容於圖內

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#74]
提示頁的最終樣貌，詳細內容於圖內

zeplin連結：https://zpl.io/aMmgyDR

<img width="1277" alt="2018-05-08 11 48 48" src="https://user-images.githubusercontent.com/37163894/39737073-ced25332-52b5-11e8-8e91-c19e8fcdb5ed.png">

**Comment by Isabella-RYZO** [comment]
目前提示已改成最新版
