### ISSUE TITLE
【問題】表單元件出現謎之線條

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#743]
表單元件出現謎之線條
如圖

用電腦瀏覽器預覽WEBA專案
![2018-10-22 11 10 53](https://user-images.githubusercontent.com/34327325/47328091-36f6f380-d6a2-11e8-9de1-89e7362e8a39.png)

**Comment by AnitaRyzo** [comment]
表單元件已乾乾淨淨
![image](https://user-images.githubusercontent.com/41721950/49359239-8bb17380-f710-11e8-9541-60a7b0df8269.png)
◎◎ 20181203確認以上正式環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
目前表單沒有多餘的線條
◎◎ 20190116確認以上正式環境內容 ◎◎
