### ISSUE TITLE
【建議】跨帳號表單的小提醒

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#744]
跨帳號功能的小圖示如黃框處，是否能有小提醒告訴使用者可以對表單執行不同功能?
![image](https://user-images.githubusercontent.com/41721950/47332330-85f85500-d6b1-11e8-95c8-d9cfe5b09095.png)
![image](https://user-images.githubusercontent.com/41721950/47332359-9e686f80-d6b1-11e8-9fce-8ebb98378eaf.png)
以上建議請參考，謝謝~

**Comment by ryzojudy** [comment]
氣泡窗文字：查看表單
![image](https://user-images.githubusercontent.com/34263719/47405291-777a6e00-d783-11e8-948b-08d0c4b91f9a.png)

氣泡窗文字：查看表單回覆
![Uploading image.png…]()

**Comment by ai015606220** [comment]
Duplicate of #768
