### ISSUE TITLE
【建議】跨帳號查看表單增加專案已刪除文字

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#745]
目前跨帳號查看表單，如果原始專案已經刪除了，會出現空白的欄位，
希望有機會的話，可以多個文字標註，例如“原專案已經刪除”

![2018-10-23 11 07 22](https://user-images.githubusercontent.com/34327325/47333046-12a41280-d6b4-11e8-92c9-4d25e9e63d96.png)

**Comment by ryzojudy** [comment]
文字內容的部分就照weilyn的建議修改即可
內容：原專案已刪除
再麻煩了~感謝

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/58676286-46ea5a80-838a-11e9-9f99-ff1d00f6595b.png)
![image](https://user-images.githubusercontent.com/41721950/58676294-4f429580-838a-11e9-90cd-f98d76cce35f.png)
◎◎ 20190531確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/60633815-01b0c100-9e3f-11e9-8bf1-fa63e183bd0b.png)
![image](https://user-images.githubusercontent.com/41721950/60633798-f2ca0e80-9e3e-11e9-9516-24a3ebe0e18d.png)
◎◎ 20190704確認以上正式環境內容 ◎◎
