### ISSUE TITLE
【審核發佈管理】將審核部分挪出來，詳細內容於圖內

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#75]
將審核部分挪出來，詳細內容於圖內
zeplin連結：https://zpl.io/25y8jmr

![-](https://user-images.githubusercontent.com/37163894/39737233-a9093b88-52b6-11e8-99b2-94c22b260409.jpg)

**Comment by ryuichl** [comment]
發佈後可以有QR秀出來嗎
像2版那樣?

**Comment by liucwlewis** [comment]
會有，大概會像是這樣，點擊預覽後附在一旁
<img width="934" alt="2018-05-08 2 48 18" src="https://user-images.githubusercontent.com/37163894/39742138-f1342004-52ce-11e8-905a-0674465cc19c.png">

**Comment by ryuichl** [comment]
這是審核的部分
放行過後會有嗎?

**Comment by ai015606220** [comment]
#43

**Comment by liucwlewis** [comment]
會有的
