### ISSUE TITLE
【問題】套版審核備註欄位跑版

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#752]
畫面1: 新增第三個評論時就有點異樣，第四個評論無法顯示
![2018-10-30 11 48 55](https://user-images.githubusercontent.com/34327325/47694771-041ca480-dc3a-11e8-8f30-5ff93497e538.png)

畫面2:卷軸已經到底，內容還沒到底
![2018-10-30 11 49 05](https://user-images.githubusercontent.com/34327325/47694793-18f93800-dc3a-11e8-9c7b-6263e7150049.png)

**Comment by AnitaRyzo** [comment]
套版審核備註欄位已增加下拉式捲軸(黃框)，可以往下擴增
新問題點：英文與數字標題被卡掉(紅框)
![image](https://user-images.githubusercontent.com/41721950/47975647-a7156880-e0e9-11e8-9408-9d3c46c566cf.png)
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
套版審核備註欄位已增加下拉式捲軸(黃框)，可以往下擴增;英文與數字標題會自動斷行。
![image](https://user-images.githubusercontent.com/41721950/48613105-c81d6980-e9c5-11e8-8529-f960bbaa0169.png)
◎◎ 20181116確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
套版審核備註欄位已增加下拉式捲軸(黃框)，可以往下擴增;英文與數字標題會自動斷行。
![image](https://user-images.githubusercontent.com/41721950/48818272-7ab64900-ed85-11e8-8290-0eb174988a07.png)
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
套版審核備註欄位有下拉式捲軸；英文與數字標題會自動斷行。
◎◎ 20181123確認以上正式環境內容 ◎◎
