### ISSUE TITLE
【問題】showcase的套版網址裡的表單失效

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#754]
從showcase網站進入套版的網址，發現串連的表單消失

回到專案裡檢查發現表單正常顯示，且表單本體也沒有做修改或刪除

再請協助確認情況

提供相關的專案網址，但基本上是有表單的都出現此情況：
https://template-weba039.ryzoweba.io/

![2018-10-30 1 56 58](https://user-images.githubusercontent.com/34327325/47698882-fe2fbf00-dc4b-11e8-9a27-92bff868f635.png)

編輯器
![2018-10-30 1 57 15](https://user-images.githubusercontent.com/34327325/47698901-0b4cae00-dc4c-11e8-98e8-d71ed19dfb7c.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/47976303-c5c92e80-e0ec-11e8-8b7e-7b65d6570bce.png)
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
套版的表單皆已出現
◎◎ 20181123確認以上正式環境內容 ◎◎
