### ISSUE TITLE
【問題】專案的『GA數據』資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#755]
分頁分析中『連結分析』的資料，帶入『分頁』與『五個元件』
WEBA中五個元件有連結：文字(僅網頁)、圖片、圖示、按鈕、社群追蹤(僅網頁)。
僅測試連結中的：網頁連結、頁面、提示
![image](https://user-images.githubusercontent.com/41721950/47705952-f3ccef80-dc62-11e8-9f63-0c11d61e60fb.png)

1.連結顯示【undefined】(黃框)，按下開啟連結的【開啟】會到『https://ryzoweba.io/client/』
![image](https://user-images.githubusercontent.com/41721950/47705681-3c37dd80-dc62-11e8-881b-cf8a268d7372.png)
2. 『頁面連結』對按鈕的計數是獨立的，而圖片與圖示的計數是累加的；對『所在頁面』的描述也不同。
![image](https://user-images.githubusercontent.com/41721950/47705639-1ad6f180-dc62-11e8-8878-1d2fb9dcf83f.png)

3-1.『社群分享』的【按鈕文字】，編輯區無法編輯，能否從程式中直接將社群名稱寫入此欄位?
3-2.能否讓『所在頁面』與『總點擊次數』這兩欄做篩選或是排序?
![image](https://user-images.githubusercontent.com/41721950/47692526-fb73a080-dc30-11e8-8e65-a964dbedeed2.png)

4.GA資料並不是每次都會帶入『根目錄/』
![image](https://user-images.githubusercontent.com/41721950/47692378-5eb10300-dc30-11e8-8ab4-7e371cd5331d.png)

5.『基礎數據』的資料與『分頁分析』的資料數據有出入
![image](https://user-images.githubusercontent.com/41721950/47692066-7dfb6080-dc2f-11e8-8872-0fd297ea0e9e.png)

6. 資料多的時候，有些『頁面、提示連結』的資料不會被寫入
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
1. 暫時不知道問題點
2. 之後有連結的元件都需要有自己的id 這樣不會因為文字和連結一樣而混在一起
3. 要再加預設文字進去圖示
4. 暫時不知道問題點
5. bug 計算錯誤
![image](https://user-images.githubusercontent.com/10150807/47761289-c4fe5a00-dcf2-11e8-92a2-d0a425694dd8.png)
計算上把同頁面不同query string的加總了 所以會有問題
新版的從源頭就去掉query string 可能之後也不用另外計算

@Gabe-Liu  @ai015606220

**Comment by ryuichl** [comment]
先關掉這個issue
會先解掉已知問題
待新版界面出來再看有沒有新的問題
