### ISSUE TITLE
【問題】 圖片無法上傳！！！！！！！！！

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#756]
情境如下：（此事件在10/30約晚上5:45開始至10/31上午9:30，問題持續存在，網頁重整過非常多次，也用無痕視窗開啟都沒有用，圖片幾乎都是壓縮至2MB以下的jpg檔案）

專案裡我要設定多個相似的提示頁面，因此做完第一個提示頁面後，會利用「複製」的方式做第二第三個以此類推。當我在做第二提示頁面時，需要更換圖片，**但是圖片就是一直無法上傳一直在loading**， 更詭異的是，當我再回到第一個提示頁面時，會發現**原先應該要更換在第二提示頁面的圖片替換掉原本第一個提示頁面相對位置的圖片**！！！！！！！！！

**Comment by AnitaRyzo** [comment]
提示頁面中的【輪播圖】元件也有類似狀況
在『複製的提示頁面』刪除圖片後會一直顯示LOADING，增加圖片也不會顯示
若在『複製的提示頁面』增加圖片，圖片會被放到『被複製的提示頁面』
請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
提示頁的圖片已可獨立上傳，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/47891161-fe6acd00-de8c-11e8-9fb1-e81e01073244.png)
![image](https://user-images.githubusercontent.com/41721950/47891239-599cbf80-de8d-11e8-9189-e1a9e29b768b.png)

提示頁的輪播圖已可獨立上傳，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/47891020-72f13c00-de8c-11e8-9e52-446106d7d3ca.png)
![image](https://user-images.githubusercontent.com/41721950/47891048-8e5c4700-de8c-11e8-81cb-f6bb921b20fa.png)
◎◎ 20181102確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
提示頁的圖片與輪播圖已可獨立上傳，不會互相影響
![image](https://user-images.githubusercontent.com/41721950/48821911-1b146980-ed96-11e8-8af8-2a89b21ec8d9.png)
![image](https://user-images.githubusercontent.com/41721950/48821934-2bc4df80-ed96-11e8-8ab2-c3aec5de778d.png)
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
提示頁與輪播圖的圖片可獨立上傳，不會互相影響
◎◎ 20181123確認以上正式環境內容 ◎◎
