### ISSUE TITLE
【問題】表單設定的信箱與儲存

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#758]
表單設定頁面曾經在 #675表單回覆的指定信箱，信箱設為唯一值
![image](https://user-images.githubusercontent.com/41721950/47769294-5f23c980-dd16-11e8-9254-9c214a75e49b.png)
1. 現在操作卻變成『重複的值』才能輸入，新的信箱按enter會被刪除，按＋號沒有反應。
→ 但不管輸入幾次信箱，其實系統都只傳送一封信，如同#675設定。
2. 當『表單設定』與『題目編輯』切換時，輸入的資料會被自動刪除；
→ 要避免資料被刪除的方法，是操作每一個頁籤就要儲存一次，儲存之後視窗就會自動被關閉，使用者要再重複開啟操作視窗。

**Comment by AnitaRyzo** [comment]
信箱可輸入不同信箱，且會阻擋相同的信箱。
『表單設定』與『題目編輯』切換時，輸入的資料會被自動儲存。
![image](https://user-images.githubusercontent.com/41721950/47976795-4721c080-e0ef-11e8-876c-f8fe1f104190.png)

◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by weilyn** [comment]
想確認一下，表單寄送至指定信箱的功能是否已經在測試環境中修正完成

**Comment by ryuichl** [comment]
已修正
上線時間的話 這禮拜看看
可能禮拜四

**Comment by AnitaRyzo** [comment]
信箱可輸入不同信箱，且會阻擋相同的信箱。
![image](https://user-images.githubusercontent.com/41721950/48822489-34b6b080-ed98-11e8-89d0-7c64b270721d.png)
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『表單設定』與『題目編輯』的編輯頁切換時，輸入的資料會被自動儲存。
信箱可輸入不同信箱，且會阻擋相同的信箱。
◎◎ 20181123確認以上正式環境內容 ◎◎
