### ISSUE TITLE
【建議】表單的下拉選單文字提示

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#759]
目前下拉選單的選項提醒文字為：新增選項
其他提型的新增選項提醒文字為：新增選項(輸入非現有選項之文字)
不知道是否下拉選單的提醒文字也跟其他的改成一樣呢?
有測試過下拉選單也無法有相同文字的選項

圖片參上
下拉：
![image](https://user-images.githubusercontent.com/34263719/47775607-1296b900-dd2b-11e8-83b9-4dccbf5cd951.png)

單選：
![image](https://user-images.githubusercontent.com/34263719/47775614-188c9a00-dd2b-11e8-8cc3-59276e72595e.png)

**Comment by ryzojudy** [comment]
如果覺得可以改
希望英文語系的部分也同步變動~
感謝

**Comment by Samasianspock** [comment]
已確認「下拉式」的新增項目用語與其他題目名稱一致。
