### ISSUE TITLE
團隊管理-無法顯示團隊中的帳號清單，切換團隊會跳回個人帳號

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#76]
無法顯示團隊中的帳號清單
當切換團隊的時候 就會跳回個人帳號的分頁
![image](https://user-images.githubusercontent.com/34263719/39737283-dd7e7f04-52b6-11e8-95f9-8f8398475c5e.png)

**Comment by ai015606220** [comment]
#79

**Comment by ai015606220** [comment]
prod打包時發生的套件問題，暫時用非prod打包，後續繼續找解決方法

**Comment by ai015606220** [comment]
套件版本升級後已解決
angular-devkit/build-angular: 0.6.1
angular/cli: 6.0.1
