### ISSUE TITLE
【問題】東捷後台 數據無法下載

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#762]
<img width="154" alt="2018-11-01 2 20 28" src="https://user-images.githubusercontent.com/34560641/47835973-5cda7180-dde1-11e8-82cf-37ecc4c07917.png">

東捷系統中的數據後台 目前無法下載數據
點擊「下載數據」按鈕時，會跳出上述網頁畫面
煩請查明原因 感謝

**Comment by Kyle30** [comment]
可以提供我帳號嗎?!

**Comment by Kyle30** [comment]
Done

**Comment by ryuichl** [comment]
在正式環境已修復的bug
因為東捷還是舊版本 所以造成此問題
目前已單獨修復此bug
