### ISSUE TITLE
【問題】錨點沒有滑到準確的位置

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#764]
此專案的錨點皆不準確
無論是手機版、電腦版 預覽或發佈
[https://east.ryzoweba.io](https://east.ryzoweba.io)

**Comment by AnitaRyzo** [comment]
錨點是因為編輯區百分比的變動而不準確，已確定手機版、電腦版皆可準確定位
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已確定手機版、電腦版皆可準確定位錨點
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已確定手機版、電腦版皆可準確定位錨點
◎◎ 20181123確認以上正式環境內容 ◎◎
