### ISSUE TITLE
【問題】文字連結

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#765]
WEBA裡的文字，如果開啟了連結，但是沒有設定連結，會跳轉到編輯器的登入畫面

不知到有沒有辦法自動將這類型“設定不完全”的連結變成沒作用，或是有其他解決方案

連結到編輯器入口感覺不是一個好選擇

![2018-11-01 5 05 06](https://user-images.githubusercontent.com/34327325/47842657-4ee41b00-ddf8-11e8-8410-6ef9b70d73a8.png)

**Comment by AnitaRyzo** [comment]
“設定不完全”=不會有反應
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
“設定不完全”=不會有反應
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
“設定不完全”=不會有反應
◎◎ 20181123確認以上正式環境內容 ◎◎
