### ISSUE TITLE
【問題】表格沒有按比例放大 

### ISSUE THREAD

**Issue by ryzojessie** [ryuichl/v3-report#766]
上圖為專案裡的表格大小，下圖為發佈後的電腦版表格
＊圓圈圈跑版的比較嚴重

<img width="314" alt="2018-11-01 5 12 58" src="https://user-images.githubusercontent.com/34876672/47843120-9ae38f80-ddf9-11e8-96e8-fb14a9b0ceed.png">

<img width="434" alt="2018-11-01 5 13 36" src="https://user-images.githubusercontent.com/34876672/47843124-9cad5300-ddf9-11e8-9711-6064a3cd51d9.png">

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/47977724-b221c600-e0f4-11e8-96e4-2d03782863cb.png)
左邊編輯區與右邊瀏覽器的比較，表格與圓圈位置未出現跑版狀況
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/48824795-603d9900-eda0-11e8-8b85-a841a0c3ecd5.png)
左邊編輯區與右邊瀏覽器的表格與圓圈位置未出現跑版狀況
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/48930962-b8a2a100-ef2e-11e8-8b15-56f0f57deb07.png)
左邊編輯區與右邊瀏覽器的表格與圓圈位置未出現跑版狀況
◎◎ 20181123確認以上正式環境內容 ◎◎
