### ISSUE TITLE
【問題】提示裡的群組問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#767]
在提示裡分別 新增圖片及文字
並將其群組

群組後無法使用滑鼠同時移動群組物件，要使用鍵盤才可以

且在圖層裡選擇群組時，畫布裡的物件不會被圈選起來

![2018-11-02 11 30 15](https://user-images.githubusercontent.com/34327325/47892457-bf3f7a80-de92-11e8-9363-54a83dbdea1b.png)

**Comment by weilyn** [comment]
好像一般頁面裡也有機會出現這個問題

**Comment by AnitaRyzo** [comment]
外圍為虛線的時候，可以利用滑鼠同時移動群組物件
![image](https://user-images.githubusercontent.com/41721950/48825239-c4149180-eda1-11e8-8cc8-c46ffb97a69e.png)
在圖層設定選擇群組時，畫布裡的物件外圍是實線，可以利用鍵盤方向鍵移動群組物件
![image](https://user-images.githubusercontent.com/41721950/48825600-ccb99780-eda2-11e8-8f2d-d9e07ac45f57.png)
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
外圍為虛線的時候，可以利用滑鼠同時移動群組物件
在圖層設定選擇群組時，畫布裡的物件外圍是實線，可以利用鍵盤方向鍵移動群組物件
◎◎ 20181123確認以上正式環境內容 ◎◎
