### ISSUE TITLE
【建議】跨帳號 查看表單 圖示修改

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#768]
<img width="686" alt="2018-11-02 11 53 36" src="https://user-images.githubusercontent.com/34560641/47893076-1135cf80-de96-11e8-9800-6e0a8d81ea5f.png">
目前跨帳號的查看表單中 建議在跨帳號複製時 右下角的按鈕可以出現氣泡窗 
<br/>
讓使用者滑鼠在按鈕上時 可以知道這個按鈕的用途
<br/>
<br/>
另外 純查看表單和純查看表單回覆的圖示 希望可以更明確 建議：
<br/>
<br/>
- 純查看表單：改成「眼睛」圖示
<br/>
- 純查看表單回覆：改成「表單右上角有眼睛」圖示
<br/>
<br/>
提供參考 目前的圖示看起來比較像是 「進入」和「回信」的感覺
歡迎討論

**Comment by liucwlewis** [comment]
由於兩種狀態不會同時出現，就統一使用「眼睛icon」（跟專案管理的預覽同一個icon）
觸碰時會跳出氣泡窗，分別內容是：1.查看表單 2.查看回覆

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51017144-e068c980-15ad-11e9-8595-c762d1a80f2c.png)
◎◎ 20190111確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
與上述相同
![image](https://user-images.githubusercontent.com/41721950/51236028-062a1000-19ac-11e9-9713-76c2fb6013aa.png)
◎◎ 20190116確認以上正式環境內容 ◎◎
