### ISSUE TITLE
【建議】權限管理Wording統一與修改

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#769]
建議將權限管理中：

「專案管理」和「表單管理」的名詞使用的與後台名稱一致
原本在左側控制欄的名稱分別是「專案管理」和「表單管理」
<img width="170" alt="2018-11-02 12 05 57" src="https://user-images.githubusercontent.com/34560641/47893443-f49a9700-de97-11e8-91ee-ae9c883cdb32.png"><img width="177" alt="2018-11-02 12 06 01" src="https://user-images.githubusercontent.com/34560641/47893450-f95f4b00-de97-11e8-8e38-a5e0c43079f8.png">
在權限管理裡面卻變成了「專案設計」和「表單系統」
建議做以下修改
<img width="885" alt="2018-11-02 12 01 40" src="https://user-images.githubusercontent.com/34560641/47893418-db91e600-de97-11e8-8d6f-5f3e5cfb70a0.png">
並將跨帳號的部分也以相同規則說明
<img width="879" alt="2018-11-02 12 01 48" src="https://user-images.githubusercontent.com/34560641/47893483-20b61800-de98-11e8-9b71-2fc73925a0a6.png">

同時跨帳號的名稱修改後 在跨帳號的檢視後台的相對應位置（上方橫列中）一起做相對應修改
<img width="1035" alt="2018-11-02 12 06 16" src="https://user-images.githubusercontent.com/34560641/47893517-42af9a80-de98-11e8-9170-09373f9603f1.png">

希望能統一各個功能的名詞與圖示 避免用戶混淆
以上建議 歡迎討論

**Comment by leonlin6** [comment]
麻煩文字修改內容也請@ryzojudy 確認是否與wilma提出的一致
修改後畫面應如下
![002](https://user-images.githubusercontent.com/29088297/55946038-81832100-5c7e-11e9-9d08-395066030df6.jpg)
![001](https://user-images.githubusercontent.com/29088297/55946039-81832100-5c7e-11e9-9f38-fbf4fbae4bc6.jpg)

**Comment by ryzojudy** [comment]
如果改成下列的狀況
不知道可不可以呢?

專案設計(個人帳號) -> 專案管理(個人帳號)
表單系統(個人帳號) -> 表單管理(個人帳號)

跨帳號功能：
專案相關 -> 專案管理
表單相關 -> 表單管理

(跨帳號檢視後台的對應位置)
專案相關 -> 跨帳號專案管理
表單相關 -> 跨帳號表單管理

這邊關於改成「跨帳號專案管理」還是想調整為「專案管理」的原因
是因為他本來就已經在「跨帳號管理」的這個大架構下了，如果再加上【跨帳號】感覺有點累綴
另外還是把【個人帳號】用括號的方式加在後面，是覺得這樣看起來會比較清楚知道是在處理專案的還是表單的東西

以上要麻煩 @wilmaftliu 幫我確認了~感謝

**Comment by wilmaftliu** [comment]
同意 最後修改項目如下：
<img width="896" alt="螢幕快照 2019-05-08 上午10 14 11" src="https://user-images.githubusercontent.com/34560641/57344627-89998800-717a-11e9-9dcf-8b14640569a7.png">

<img width="892" alt="螢幕快照 2019-05-08 上午10 14 19" src="https://user-images.githubusercontent.com/34560641/57344640-8e5e3c00-717a-11e9-99df-7606e8de48c2.png">

![跨帳號後台](https://user-images.githubusercontent.com/34560641/57344648-99b16780-717a-11e9-976e-181cc342763f.jpg)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57830300-44adcb00-77e4-11e9-93a5-bf4c0d570f38.png)
![image](https://user-images.githubusercontent.com/41721950/57830092-99047b00-77e3-11e9-9448-6ad6c5149961.png)
◎◎ 20190516確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已確認如上黃框修改
◎◎ 20190704確認以上正式環境內容 ◎◎
