### ISSUE TITLE
【問題】跨頁複製

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#770]
在提示裡可以開啟跨頁複製的選項，也可以選取物件

但是無法確實複製到其他頁面裡

**Comment by Gabe-Liu** [comment]
提示目前是無法跨頁複製，會隱藏起來。

**Comment by AnitaRyzo** [comment]
提示頁的複製已隱藏
![image](https://user-images.githubusercontent.com/41721950/47980264-d2a44d00-e101-11e8-8848-ec71acfdd587.png)
◎◎ 20181105確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
提示頁沒有【複製】按鈕
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
提示頁沒有【複製】按鈕
◎◎ 20181123確認以上正式環境內容 ◎◎
