### ISSUE TITLE
【建議】互動模組的系統各狀態提示頁可個別編輯背景＋可上傳圖片

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#771]
Suggestion from Joe:

建議互動元件以QR兌換贈品時，或是登入社群時的驗證頁面中，可以更改預設的半透明灰色背景圖，
或是可以另外上傳圖片。
<img width="376" alt="2018-11-02 3 47 35" src="https://user-images.githubusercontent.com/34560641/47900098-a8128400-deb6-11e8-9293-b476131eeb0d.png">

目前可編輯區域只有「標題」、「說明文」以及「序號」的樣式設定
<img width="833" alt="2018-11-02 3 45 03" src="https://user-images.githubusercontent.com/34560641/47900025-6da8e700-deb6-11e8-9aae-3c7bfa54b012.png">

希望能讓客戶在要使用QR兌換時的畫面可以讓使用者插入圖/背景，放置活動KV或企業CI。

以上 歡迎討論

**Comment by weilyn** [comment]
目前是可以更換背景圖片，或是遮罩的透明度，但是是一次修改全部的提示狀態
