### ISSUE TITLE
【建議】套版管理-新增刪除套版警告提示窗

### ISSUE THREAD

**Issue by Samasianspock** [ryuichl/v3-report#772]
有鑒於有 L同仁在套版管理設定時誤觸刪除按鈕，造成套版原作者的困擾，因此必須增加一道防護措施（警告提示窗），讓使用者再次確認是否刪除以避免類似意外再次發生，而日後也將整理及確認後臺所有的重要設定在變更時有相同的確認變更提示窗。
![alert issue](https://user-images.githubusercontent.com/37531593/47901170-27ee1d80-deba-11e8-950e-3453a1226cd9.jpg)

**Comment by AnitaRyzo** [comment]
確認【套版管理】有『刪除提示對話框』
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
確認【套版管理】有『刪除提示對話框』
◎◎ 20181123確認以上正式環境內容 ◎◎
