### ISSUE TITLE
【建議】抽獎型元件 設定密碼後QR需手動開啟

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#774]
建議在抽獎型元件設定兌換密碼後
<img width="819" alt="2018-11-05 12 15 49" src="https://user-images.githubusercontent.com/34560641/47977716-a504d700-e0f4-11e8-865a-de620468e6a3.png">

在各狀態提示頁中，中獎紀錄裡的「QR Code」可以連動變成開啟 （目前需要自己手動打開才會出現QR）
不需要手動打開 否則操作上不直覺
<img width="824" alt="2018-11-05 12 13 29" src="https://user-images.githubusercontent.com/34560641/47977766-ea290900-e0f4-11e8-9dc5-179616c1af93.png">
目前預設QR都是關閉的 會讓使用者容易忽略 請協助改善

**Comment by eatinggg** [comment]
已修改
抽獎型元件設定兌換密碼後，QR Code 預設更改為開啟
再麻煩 @Gabe-Liu 協助修改～感謝～

<img width="582" alt="2018-11-27 12 14 02" src="https://user-images.githubusercontent.com/34293268/49058200-f3ae1880-f23d-11e8-8d3e-df976b822849.png">

**Comment by ryuichl** [comment]
是否該考慮最常使用的情況
如果最常使用的情況不是開啟QR
這樣可能反而增加困擾

還是其實目前場景大部分都要開啟QR?

**Comment by Samasianspock** [comment]
我們的「中獎紀錄」以及序號的「已兌換」提示頁是類似市面上的電子票卷，常見的形式通常都有包含QR Code或條碼。在預設狀態時主動顯示，使用者若不需要的話就會自行在介面上尋找關閉顯示的設定，而且如果有QR Code的話，工作人員在兌換時也會比較方便，所以比較建議預設都顯示。

![market_implementation](https://user-images.githubusercontent.com/37531593/49212623-7204e900-f3fd-11e8-95c6-9388167e8e3d.jpg)

**Comment by ryuichl** [comment]
感覺沒有理解我的提問
我的重點是常用的場景是哪一種
對我自己來說
常見的場景是
抽獎後直接寄送獎品並不用到店面兌獎
在這個前提下每次製作還要去關掉會增加困擾

那如果說如果其實大部分場景是
要去線下兌獎
那我就同意要預設打開
