### ISSUE TITLE
【問題】發布中專案預覽無法顯示，受帳號權限影響

### ISSUE THREAD

**Issue by jamesyeh327** [ryuichl/v3-report#775]
發布中製作的專案全部預覽顯示不出來，好像只有我的電腦有這種問題，cookie等也清理過了，需要協助~!!

![1](https://user-images.githubusercontent.com/44761381/47977797-0d53b880-e0f5-11e8-9b98-694ded13fa88.png)

**Comment by AnitaRyzo** [comment]
當『帳號管理』權限如下時，就無法觀看專案
![image](https://user-images.githubusercontent.com/41721950/47982570-2d8e7200-e10b-11e8-90cc-4abc495ff608.png)
建議是否在此權限下，依然可以看到自己編輯的專案? 感恩~

**Comment by ryuichl** [comment]
看自己的部分我會從後台處理
跨帳號的部分再麻煩你們處理
@Gabe-Liu  @ai015606220 
感恩

**Comment by AnitaRyzo** [comment]
當『帳號管理』權限如上所要求
自己專案的預覽可以完整呈現
![image](https://user-images.githubusercontent.com/41721950/48335377-7d83b080-e698-11e8-8818-37881c90e054.png)
他人專案的預覽只有出現QR CODE
![image](https://user-images.githubusercontent.com/41721950/48335621-44980b80-e699-11e8-87bc-2624fe8c3bd2.png)
◎◎ 20181112確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
自己專案的預覽可以完整呈現
![image](https://user-images.githubusercontent.com/41721950/48826636-ced12580-eda5-11e8-8ce2-0f357b345201.png)

他人專案的預覽只有出現QR CODE
![image](https://user-images.githubusercontent.com/41721950/48826610-bd881900-eda5-11e8-9074-35ad76720a33.png)


◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
當『帳號管理』權限如上所要求
自己專案的預覽可以完整呈現，他人專案的預覽只有出現QR CODE
◎◎ 20181123確認以上正式環境內容 ◎◎
