### ISSUE TITLE
【問題】編輯區顯示的日期與設定的日期不同

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#778]
問題一：未從編輯區跳出，時間會一直回到原先設定；但其實設定的時間有被儲存。
step1. 在專案中設定時間如下紅框，結束時間是【12/1】；按下【儲存】。
![image](https://user-images.githubusercontent.com/41721950/48121965-50f32180-e2b1-11e8-938f-fcb248979d38.png)
step2. 在專案中切換任何頁面皆可，再次回到設定頁會發現時間回到設定前的【11/7】
![image](https://user-images.githubusercontent.com/41721950/48121973-56506c00-e2b1-11e8-8350-310ca1f8adeb.png)
step3-1. 另開分頁，『專案管理』進入此專案，專案結束時間是【12/1】
![image](https://user-images.githubusercontent.com/41721950/48122021-7aac4880-e2b1-11e8-8cb8-cf07192c098f.png)
step3-2. 『專案發佈』進入此專案，專案結束時間是【12/1】
![image](https://user-images.githubusercontent.com/41721950/48122096-9d3e6180-e2b1-11e8-9d0f-bfd094aea907.png)

問題二：中文的日期格式是【年月日】，英文的日期格式是【月日年】；日期格式是否可以統一?
![image](https://user-images.githubusercontent.com/41721950/48122254-1473f580-e2b2-11e8-894e-b3903c43a44c.png)

題外話一：在英文語系中表單管理的名稱會被卡掉
![image](https://user-images.githubusercontent.com/41721950/48122473-99f7a580-e2b2-11e8-80f3-26a31ec38163.png)
題外話二：如下的提示訊息，不管在哪個語系都顯示的都相同
![image](https://user-images.githubusercontent.com/41721950/48122721-30c46200-e2b3-11e8-9a5a-9b9d39c5d2d4.png)

**Comment by ryuichl** [comment]
問題二感覺是因為國外習慣的格式就是那樣?

**Comment by AnitaRyzo** [comment]
因為在【表單管理】與【互動後台管理】的英文介面顯示的日期格式是【年月日】，所以多問一句
國外習慣的日期格式確實是【月日年】，謝謝~
![image](https://user-images.githubusercontent.com/41721950/48175187-f657d500-e345-11e8-9f25-4d6fa577ecc7.png)

**Comment by Gabe-Liu** [comment]
問題二，可能要等英文語系的文字修改好後看情況而定~

**Comment by Gabe-Liu** [comment]
時間問題修改 - 
英文語系一律顯示 月日年
其他語系一律顯示 年月日
