### ISSUE TITLE
【問題】輪播圖設定標題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#779]
輪播圖設定區域的標題是輪播區塊
可能造成與輪播區塊元件的混淆

<img width="314" alt="2018-11-08 11 10 34" src="https://user-images.githubusercontent.com/34327325/48175441-08864300-e347-11e8-8b77-65f1116cb9d7.png">

**Comment by AnitaRyzo** [comment]
已將標題更改為『輪播圖設定』
![image](https://user-images.githubusercontent.com/41721950/48335845-e1f33f80-e699-11e8-9ce6-f01a02b2b8ed.png)
◎◎ 20181112確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
標題已正確顯示『輪播圖設定』&『輪播區塊設定』
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
標題已正確顯示『輪播圖設定』&『輪播區塊設定』
◎◎ 20181123確認以上正式環境內容 ◎◎
