### ISSUE TITLE
【權限優化】顯示個人權限流程，詳細內容於圖內

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#78]
顯示個人權限流程，詳細內容於圖內
Zeplin連結:https://zpl.io/2Gm0rNj
<img width="1044" alt="2018-05-08 11 59 12" src="https://user-images.githubusercontent.com/37163894/39737383-55c22e20-52b7-11e8-82d4-c122ab2c8253.png">

**Comment by ai015606220** [comment]
#27
