### ISSUE TITLE
【問題】表單 回覆寄至指定信箱 無法新增

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#780]
嗨，表單寄送至指定信箱的功能
經客戶反應發現無法新增信箱位址

請協助排除問題

<img width="478" alt="2018-11-08 1 55 39" src="https://user-images.githubusercontent.com/34327325/48180344-24e1aa00-e35e-11e8-8a32-002b99367f45.png">

**Comment by ryuichl** [comment]
#758
