### ISSUE TITLE
【建議】切換團隊

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#785]
在團隊管理時，點選下方的團隊要查看團隊名單，頁面會整個跳轉，

當我的團隊很多的情況下，**必須靠圓點來進行切換團隊，
但是只要點選以後，就會跳回到第一個圓點** 紅框處
變成如果我需要快速查看團隊時，就會多做很多次類似的動作
希望圓點的位置可以記憶

團隊管理這個區塊其實主要用來邀請成員或是調整權限
中間專案區域也不是跟著團隊在計算，應該不需要全部一起重新出現
所以也可以考慮只替換下半部的團隊內資訊(黃框處)，專案數、還有團隊名稱列表都不需要再重載

<img width="1440" alt="2018-11-09 1 58 01" src="https://user-images.githubusercontent.com/34327325/48245979-8b32ff00-e428-11e8-8d9f-ec4021f00805.png">

**Comment by Samasianspock** [comment]
希望紅框處的切換點可以停留在所選的團隊位置，切換團隊時只有黃色框處會變更內容，如果允許的話團隊切換的方式希望能用 #857 的方式快速切換，感謝！

**Comment by wilmaftliu** [comment]
建議可以像PPT裡面一樣，可以有一長條的列表，
也可以有像矩陣式一樣一次列出所有團隊的畫面

一般列表
<img width="1271" alt="2019-01-30 2 55 52" src="https://user-images.githubusercontent.com/34560641/51963633-32ab5500-249f-11e9-8019-4aeb9c94322f.png">

矩陣列表
<img width="1279" alt="2019-01-30 2 55 58" src="https://user-images.githubusercontent.com/34560641/51963641-3939cc80-249f-11e9-8d5f-17670abbeab9.png">
