### ISSUE TITLE
【表單】表單回覆出不來

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#79]
應該要有2筆回覆
但沒有反應
早一點的時候還很正常

![image](https://user-images.githubusercontent.com/34263719/39737969-ef9c0e14-52ba-11e8-8a0b-55fee162da53.png)

**Comment by ai015606220** [comment]
套件的bug
https://github.com/ag-grid/ag-grid-angular/issues/212

**Comment by ai015606220** [comment]
套件版本升級後已解決
@angular-devkit/build-angular: 0.6.1
@angular/cli: 6.0.1
