### ISSUE TITLE
【問題】互動後台   序號產生器顯示

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#791]
hi，以下專案已經刪除了，但由於互動後台的資料還在，故提出相關問題

據我所知序號產生器最多產生10000筆，不過在畫面中，顯示了10001

<img width="1341" alt="2018-11-09 5 35 25" src="https://user-images.githubusercontent.com/34327325/48254873-1a024480-e446-11e8-8fb9-785f3ed0826f.png">

**Comment by AnitaRyzo** [comment]
使用者創立了10000筆，而後台的『總數量』是未兌換+未領取+已兌換
未兌換=5
未領取=9995
已兌換=1
故出現總數量=10001
→ 不知後台是否有甚麼特殊狀況??
![image](https://user-images.githubusercontent.com/41721950/48333550-d5b7b400-e692-11e8-8167-9d306631c024.png)

增加的問題：在大螢幕可輸入的數字限制是『9999999』，而在Mac小螢幕的數字限制是『100』
![image](https://user-images.githubusercontent.com/41721950/48333882-def55080-e693-11e8-8ff2-f03c080a0223.png)
以上補充請協助處理，感恩~
