### ISSUE TITLE
【問題】序號產生的密碼問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#795]
目前序號產生器如果沒有產生序號或是沒有設定密碼，都可以正常發佈專案
但是以密碼來說，目前其實一定要密碼才能兌換
所以如果沒有設定密碼的話，掃描QR code，就會怎麼輸入都不正確
，看來其實密碼是必要條件，是否強制規定要設定

另外客戶反應，希望可以有關閉密碼的機制，不知道在未來有沒有可能實行，可以再討論看看

然後，英文手機系統的使用者，兌換按鈕微跑版
![img_0138](https://user-images.githubusercontent.com/34327325/48329083-06dbb880-e682-11e8-9417-5b06ff326595.PNG)

**Comment by AnitaRyzo** [comment]
關閉密碼的機制請@ryzojudy 再做後續評估。

英文版除了【兌換】鈕跑版+出現中文﹝測試﹞
若兌換時『密碼輸入失敗』或是『已兌換過』，則出現紅色驚嘆號而無任何字樣(中間)；
將畫面重新整理之後，出現最右邊的狀況
![image](https://user-images.githubusercontent.com/41721950/48333472-82456600-e692-11e8-9474-12c3d9a16aa9.png)
簡體中文版也請協助一併處理，感恩~

**Comment by AnitaRyzo** [comment]
英文版兌換介面如下
![image](https://user-images.githubusercontent.com/41721950/48681811-b8796d00-ebdf-11e8-80d3-89e0f5044824.png)
簡體中文版兌換介面如下
![image](https://user-images.githubusercontent.com/41721950/48681807-b1eaf580-ebdf-11e8-916b-d69476929317.png)
◎◎ 20181119確認以上測試環境內容 ◎◎

**Comment by ryzojudy** [comment]
@weilyn 想問一下 客戶那邊為甚麼會想關閉密碼呢?

**Comment by weilyn** [comment]
您好，如同有些客戶會期望關閉社群驗證的原因類似，主要都是希望讓流程順暢，減少步驟。
社群驗證的理由是讓客戶做最少事，用最簡易的方法，增加活動受眾的廣度。

至於關閉密碼則是因為，密碼使用的場景通常是在線下活動，
如果使用者來換贈品還要工作人員逐一輸入密碼，人員太忙碌了，因為還有很多事情要做
一個無償性質的QR Code兌換，客戶如果真的想要獎品，就應該到現場再進行掃描，
而不該在其他地方自行掃描使用，場面上也有這類型的兌換券案例，一定要到現場點選或掃描才有效
(像是LINE上發放的優惠券 一手私藏紅茶)
會提出增加關閉的選項，就是希望增加一個更彈性的選擇

目前發現很多客戶，比起獎品被兌換完，或是安全機制，有時候更在意流程的流暢度及活動的熱鬧度

**Comment by ryzojudy** [comment]
好喔 了解

**Comment by ryzojudy** [comment]
那麻煩 @Gabe-Liu 幫我在紅框處放一個開關鈕
預設為開啟
開啟狀態時 需設定密碼才可以儲存
另外 如果可以的話 其他互動元件也是一樣的狀況
感謝~
![image](https://user-images.githubusercontent.com/34263719/48813930-da0b5d80-ed73-11e8-95de-70784dfaac4c.png)

**Comment by AnitaRyzo** [comment]
英文版與簡體中文版兌換鈕已在正確位置
![image](https://user-images.githubusercontent.com/41721950/48817602-32495c00-ed82-11e8-9eee-f90569cfd622.png)
延伸題：當【活動名稱】有做任何修改，兌換頁面就不會顯示活動名稱了(如紅框)
◎◎ 20181121確認以上測試環境內容 ◎◎
