### ISSUE TITLE
【建議】臉書工具 內嵌型文字

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#796]
內嵌型右側的頁籤資訊
應該統一使用官方用語

留言>>>訊息

<img width="918" alt="2018-11-13 11 46 45" src="https://user-images.githubusercontent.com/34327325/48389830-1fa7a500-e73a-11e8-9df0-420d14aa5040.png">

**Comment by AnitaRyzo** [comment]
已改為『訊息』
![image](https://user-images.githubusercontent.com/41721950/48613765-94dbda00-e9c7-11e8-8b56-ef0258673269.png)
◎◎ 20181116確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已是『訊息』
◎◎ 20181121確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
臉書工具(內嵌型)的頁籤資訊已改為『訊息』
◎◎ 20181123確認以上正式環境內容 ◎◎

#824 臉書工具(內嵌型)與臉書工具(工具型)的類型是要更改為『留言』
