### ISSUE TITLE
【建議】臉書工作動作型 留言

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#797]
目前該元件的設定區塊裡可以設定網址，
所以我應該可以理解為這是可以指定某特定一則貼文的留言板

日前接觸一些客戶，會用到這個功能多半是希望可以將社群和活動網站做串連
因此希望兩邊的回文可以同步
**意即FACEBOOK上留言的內容，在WEBA的內嵌留言板中也可以顯示(留言鏡像)**，
特別是在活動剛開跑，還沒有人開始留言參與活動的時候

上網查到相關做法，認為應該可行，提供網址在文章最後
https://free.com.tw/facebook-comments-mirroring/

<img width="325" alt="2018-11-13 12 00 14" src="https://user-images.githubusercontent.com/34327325/48390341-6e563e80-e73c-11e8-9dbb-d4f36258c5d8.png">

**Comment by ryuichl** [comment]
https://km.nicetypo.com/doc/a38b4b883a1fb2401d3c6cb4ed98709c
這功能看起來已經跟我們說再見了
