### ISSUE TITLE
【問題】選單架構設定 的名稱

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#798]
#103 
先前有類似的問題，當時表示因為自訂可以自己設定名稱，所以不連動。
隨著未來使用者可能增多，以及這段時間累積下來的使用經驗

發覺即使是想要使用自訂選單架構的人，在新增的時候也會期待編輯頁左側的名稱可以同步過來，
不需要連動，只要第一次新增進來的時候是使用左側的名字

例如頁面、例如錨點，都可以去抓使用者設定的名字當成預設的名稱
接著使用者可以再依需求去做修改

否則，目前的自訂選單架構的使用者體驗不是很流暢

圖片中，我在同一頁面下的不同幻燈片中個別插入了錨點
當我在自訂中將這些錨點連續加入以後，就無法分辨他們
變成使用者要新增一個頁面或選單，就立即開始修改名稱，是不利於連續操作的

<img width="235" alt="2018-11-13 3 46 39" src="https://user-images.githubusercontent.com/34327325/48398536-fb5cc000-e75b-11e8-9a29-3f516f49b0d2.png">

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51223503-f9da8e80-197c-11e9-92da-a92fb7a8c6f9.png)
◎◎ 20190116確認以上正式環境內容 ◎◎
