### ISSUE TITLE
【問題】表單顏色 設定差異化

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#799]
此問題以前提出過一次，再次提出

目前表單有兩種樣式，其中 表單顏色 的欄位只有主題1可以使用
主題0是無法修改表單顏色的，
那麼既然無法修改，該欄位就應該被隱藏起來

像是互動元件裡的幸運轉盤，樣式三也因為可以設定的項目比較少，所以隱藏了一些欄位
希望表單這裡也可以比照辦理
<img width="311" alt="2018-11-13 3 54 31" src="https://user-images.githubusercontent.com/34327325/48398989-54792380-e75d-11e8-9e0d-d064348a93c7.png">

**Comment by eatinggg** [comment]
調整後如下圖～
@liucwlewis   說之後會和其他的修改一起上線：Ｄ

<img width="598" alt="2018-11-22 5 45 18" src="https://user-images.githubusercontent.com/34293268/48894846-aff29200-ee7e-11e8-9fd0-b1f67d082cde.png">

**Comment by AnitaRyzo** [comment]
主題0已隱藏『表單顏色』
![image](https://user-images.githubusercontent.com/41721950/49274268-c4541180-f4b2-11e8-954e-955112eebc03.png)
◎◎ 20181130確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『theme-0』已隱藏『表單顏色』，『theme-1』顯示『表單顏色』。
◎◎ 20190116確認以上正式環境內容 ◎◎
