### ISSUE TITLE
【問題】發佈排程設定

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#800]
確認一下，
這裡的專案開啟跟底下的開啟時間有沒有什麼連動關聯性
因為目前的專案開啟是關閉的情況下，下方的排程還是可以設定

我的理解為下：
專案開啟：專案發佈時，是否是開啟狀態
發佈時間：想要上線發佈的時間

所以如果我希望專案發佈後，不要立刻上線，必須要將 專案開啟OFF，並且排程時間ON
如果我希望專案發佈後即刻上線，只需要將專案開啟ON，排程時間OFF
專案開啟OFF，排程時間OFF，表示發佈後，專案沒上線，而且我也還沒想好什麼時候要上線 (那幹嘛要發佈)

專案開啟ON，發佈時間ON，？？？

再麻煩協助釐清解答

<img width="316" alt="2018-11-13 5 19 08" src="https://user-images.githubusercontent.com/34327325/48403628-4c26e580-e769-11e8-97d7-a759e0b931a5.png">

**Comment by ryuichl** [comment]
兩道鎖

第一道鎖是專案開啟
有開啟才能看

第二道鎖時間設定
有開啟的話在時間內才能看

**Comment by weilyn** [comment]
所以如果第二道鎖開啟的情況下， 依然要第一道鎖開啟，才能觀看

如果是這樣的話，第一道鎖關閉的情況下，第二道鎖是不是應該保留設定值，但是反灰，禁止修改

**Comment by ryuichl** [comment]
第一道和第二道沒關係阿?
為何要反灰?

**Comment by weilyn** [comment]
因為即使我設定了固定時間內可以看，只要第一道沒開不就是不能觀看嗎

**Comment by ryuichl** [comment]
我是覺得沒啥關係
交給 @ryzojudy  @Samasianspock 
來想

**Comment by ryzojudy** [comment]
跟sam討論完後
可以修改如下：
專案開啟為關閉狀態時，下方的排程設定將消失
專案開起為開啟狀態時，下方的排程設定出現
(跟背景設定，開啟長頁面那邊一樣)
開啟狀態時，下方的排程設定預設為"未勾選"

感謝~~

**Comment by eatinggg** [comment]
修改完如下圖
等 @liucwlewis 統整之後會上傳到zeplin~~

<img width="613" alt="2018-12-07 10 45 12" src="https://user-images.githubusercontent.com/34293268/49624666-4d1c0180-fa0d-11e8-9776-ce6ea23b0e3f.png">

**Comment by liucwlewis** [comment]
Zeplin連結：https://zpl.io/2GQdB09

**Comment by AnitaRyzo** [comment]
發佈排程設定如下
![image](https://user-images.githubusercontent.com/41721950/50679370-1ce07680-103e-11e9-8adf-77224c114732.png)
◎◎ 20190104確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51239606-cc113c00-19b4-11e9-864f-e1c930547ea3.png)
◎◎ 20190116確認以上正式環境內容 ◎◎
