### ISSUE TITLE
編輯區有些 icon 還沒換成新的

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#81]
頁面管理&元件選單
<img width="66" alt="2018-05-09 9 15 00" src="https://user-images.githubusercontent.com/34293268/39792843-3f9ac986-5375-11e8-9869-95dfe3af251e.png">

頁面管理底下的 頁面(前面小小的那個)
<img width="171" alt="2018-05-09 10 33 22" src="https://user-images.githubusercontent.com/34293268/39792844-40b8171a-5375-11e8-83c0-05bb1fe273b1.png">

右側控制欄的 元件設定&專案設定
<img width="49" alt="2018-05-09 10 33 15" src="https://user-images.githubusercontent.com/34293268/39792847-4297df98-5375-11e8-956a-0df187aa8364.png">

dashboard 左側吧新增 發佈審核的icon(放在雲端了)

<img width="696" alt="2018-05-09 10 45 14" src="https://user-images.githubusercontent.com/34293268/39793018-12f45f7c-5376-11e8-906e-3f69177aef65.png">

**Comment by Isabella-Zheng** [comment]
dashboard 左側吧新增 發佈審核的icon 目前尚未有此功能，故未置放。 其餘反應之圖示皆已調整確認完畢
