### ISSUE TITLE
【優化】新增Line入口

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#811]
＊註冊頁面另外有調整中間色塊、文字的相對位置跟LOGO的位置，再麻煩留意一下～
新增Line入口-登入頁面（註冊模式）：https://zpl.io/bLxy8xQ
![line -](https://user-images.githubusercontent.com/37163894/48591479-10656900-e97f-11e8-94c8-58bf2df2cfa0.jpg)

新增Line入口-登入頁面（登入模式）：https://zpl.io/2jPzLXr
![line -](https://user-images.githubusercontent.com/37163894/48591492-18bda400-e97f-11e8-964d-f09b36faef43.jpg)

新增Line入口-個人帳號：https://zpl.io/aXk0Zkx
![line -](https://user-images.githubusercontent.com/37163894/48591502-1f4c1b80-e97f-11e8-8065-165a91089063.jpg)

**Comment by ryuichl** [comment]
還有抽獎登入的部分唷
提醒一下
感恩

**Comment by liucwlewis** [comment]
來囉～
在互動元件的提示中「身份驗證」新增Line的選項，如果要看Zeplin畫面的話，已經新增到全部的互動元件內容中
![line -](https://user-images.githubusercontent.com/37163894/48876613-e1953a00-ee39-11e8-816e-bf5ff5a646f0.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51239716-109cd780-19b5-11e9-8b60-d6add90a1add.png)
◎◎ 20190116確認以上正式環境內容 ◎◎
