### ISSUE TITLE
【問題】套版管理中 點擊套版右下方齒輪時提示頁超出畫面

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#812]
<img width="1277" alt="2018-11-16 5 38 16" src="https://user-images.githubusercontent.com/34560641/48613420-9f49a400-e9c6-11e8-8de6-d4c87166781f.png">
如圖
提示框超出畫面 會出現在齒輪右側

**Comment by AnitaRyzo** [comment]
點擊套版右下方齒輪時提示頁不超出畫面
![image](https://user-images.githubusercontent.com/41721950/49206591-7aedbe80-f3ed-11e8-8347-9520294e98fa.png)
◎◎ 20181129確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
點擊套版右下方齒輪時提示頁不超出畫面
◎◎ 20190116確認以上正式環境內容 ◎◎
