### ISSUE TITLE
【測試環境】互動後台管理與編輯區的顯示的獎項數量不符合

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#814]
step1. 設立『互動元件』的獎項、活動名稱與表單後儲存；跳出此專案。
![image](https://user-images.githubusercontent.com/41721950/48688301-8cbaaf00-ec00-11e8-8abf-24d18455cb12.png)
step2. 進入專案並複製互動元件後，連接方式選擇【啟用互動元件】
![image](https://user-images.githubusercontent.com/41721950/48688914-21bea780-ec03-11e8-8f58-df52ffc37da3.png)
【設定獎項】的地方有獎項
![image](https://user-images.githubusercontent.com/41721950/48689101-ee304d00-ec03-11e8-913e-10f424058829.png)
但在【互動後台管理】的頁面卻顯示【0/0】
![image](https://user-images.githubusercontent.com/41721950/48689267-9ba36080-ec04-11e8-808b-da4ee8f2db7f.png)
【0/0】的狀況有時候出現在『被複製的元件』有時候出現在『複製的元件』
已上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
因為mssql和mongodb實作上的不同
造成這個問題

解決方法是
複製後的抽獎
在啟用時
如果獎項的部分已經自己的id時
要先跑迴圈把id刪掉
@Gabe-Liu

**Comment by AnitaRyzo** [comment]
【互動後台管理】的數量已不會歸零
◎◎ 20181127確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
【啟用互動元件】後，【互動後台管理】的數量不會歸零
◎◎ 20190116確認以上正式環境內容 ◎◎
