### ISSUE TITLE
【建議】隱藏圖層選擇

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#817]
你好，使用上有一些小建議

已經從圖層隱藏的元件，如果使用滑鼠從畫布圈選範圍後，還是會被圈選到，
只有用圈選的方式才可以選擇到，直接點擊的方式無效

建議隱藏的圖層即使使用圈選也不要被圈選到，就讓他老實地待著

<img width="524" alt="2018-11-21 10 27 58" src="https://user-images.githubusercontent.com/34327325/48815113-37091280-ed78-11e8-89ac-c8bdf39e9452.png">

**Comment by AnitaRyzo** [comment]
即使是選取整個畫布，隱藏的元件在「圖層設定」仍是未選取
![image](https://user-images.githubusercontent.com/41721950/51289651-fb1ec080-1a3b-11e9-86db-040665289324.png)
◎◎ 20190117確認以上正式環境內容 ◎◎
