### ISSUE TITLE
【建議】裝飾區塊樣式

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#818]
希望裝飾區塊可以新增以下幾種形狀
讓整體使用層面可以更彈性

<img width="1031" alt="2018-11-21 2 42 09" src="https://user-images.githubusercontent.com/34293268/48823470-ed322380-ed9b-11e8-89f5-2a526be59d20.png">

SVG檔案位址：https://drive.google.com/drive/u/1/folders/1FwDmeIMHt2yvpAxOQKzAwXnS6wkBQjYL

**Comment by AnitaRyzo** [comment]
裝飾圖案已新增至正式環境
◎◎ 20190117確認以上正式環境內容 ◎◎
