### ISSUE TITLE
【問題】介面上收縮區塊的箭頭方向

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#819]
進入套版總覽後的下一層
目的類型、產業類型...等等收縮區塊的箭頭方向錯了

目前展開
圖1
<img width="151" alt="2018-11-16 10 33 10" src="https://user-images.githubusercontent.com/34293268/48824219-98dc7300-ed9e-11e8-96d9-acd7935a12cb.png">

目前收合
圖2
<img width="151" alt="2018-11-16 10 34 02" src="https://user-images.githubusercontent.com/34293268/48824231-a3970800-ed9e-11e8-9296-60ac984c19df.png">

收合時箭頭應該向右 如下
圖3
<img width="485" alt="2018-11-21 2 49 51" src="https://user-images.githubusercontent.com/34293268/48824251-b7426e80-ed9e-11e8-9db1-6b44e458ed53.png">

小問題再協助修改～感恩的心～～

**Comment by AnitaRyzo** [comment]
收合時箭頭已向右 
![image](https://user-images.githubusercontent.com/41721950/49209011-45000880-f3f4-11e8-92c0-7c39664d73d9.png)
◎◎ 20181129確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51289804-96b03100-1a3c-11e9-8535-4e01443204d4.png)
◎◎ 20190117確認以上正式環境內容 ◎◎
