### ISSUE TITLE
【小希望】頁籤

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#82]
希望新增頁籤元件時預設是兩個頁籤

目前：
![image](https://user-images.githubusercontent.com/34263719/39793457-2b0b3764-5378-11e8-8d58-ee5e7cdc523f.png)

希望：
![image](https://user-images.githubusercontent.com/34263719/39793462-31898c4e-5378-11e8-8159-b170cebff379.png)

**Comment by Isabella-Zheng** [comment]
處理完成
