### ISSUE TITLE
【問題】專案儲存及申請審核

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#821]
專案如果使用了相同的域名會被檢查出有重複的域名，
但是如果這時候我直接按儲存，就會變成顯示“原本設定”，
但是不能申請審核，會提示要先儲存。

猜測可能域名重複的情況下是不能儲存的，但是這邊的提示有誤，讓使用者以為其實已經被儲存了
但如果域名重複就不能儲存的話，可能會造成使用者誤以為有儲存，而造成下一次進入的資料流失

可能也需要提示 先修改域名後再次儲存，或是直接儲存，但是清空使用者這一次修改的域名設定

<img width="327" alt="2018-11-22 2 25 00" src="https://user-images.githubusercontent.com/34327325/48885474-66487e00-ee63-11e8-87db-3407584921b1.png">
<img width="319" alt="2018-11-22 2 24 48" src="https://user-images.githubusercontent.com/34327325/48885475-66e11480-ee63-11e8-9308-6a22166d447f.png">

**Comment by ryuichl** [comment]
#816
