### ISSUE TITLE
【建議】套版主題分類的編輯設定與視窗關閉

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#822]
在『審核發佈管理』介面設定套版的『主題』分類
![image](https://user-images.githubusercontent.com/41721950/48888741-9fd2b680-ee6e-11e8-86a8-b2f1f88e0beb.png)
當第一個按下【AAA】主題的編輯頁面，就只有綠框組可以開啟編輯頁面(黑底)；若想要讓黃框組可以編輯，就要重新整理頁面。
問題一：是否可以按下主題就可以編輯?
![image](https://user-images.githubusercontent.com/41721950/48889521-238da280-ee71-11e8-8315-f773a461516b.png)
在自訂的主題(紅圈)之間切換，編輯頁面會自動關閉；但預設的主題(藍框)或是新增主題就不會自動關閉。
問題二：是否可以在主題切換時，就自動關閉編輯頁面?
![image](https://user-images.githubusercontent.com/41721950/48889990-87fd3180-ee72-11e8-8750-02d718c2dacb.png)
以上建議請參考，感恩~

**Comment by Samasianspock** [comment]
問題一：是否可以按下主題就可以編輯?
一但點擊主題的設定時，必須點擊【齒輪】設定圖示才可開啟設定氣泡窗，需點擊【關閉】或【儲存設定】才可關閉目前的設定氣泡窗。需關閉氣泡窗後才能設定下一個主題。未關閉氣泡窗的狀態下，無法點擊【全部套版】、【未上傳套版】。

問題二：是否可以在主題切換時，就自動關閉編輯頁面?
兩者功能無法同時進行設定，必須確實關閉【關閉】或【儲存設定】設定的視窗才可以進行其他主題的設定，就不會出現【全部套版】、【未上傳套版】設定依然存在的情況。

以上為主題操作的設定，感謝！

**Comment by Gabe-Liu** [comment]
目前修改成
點擊齒輪呼叫出設定區後，必須要點X或者點擊設定區外觸發關閉，才可操作下個動作

**Comment by AnitaRyzo** [comment]
已確認以下操作
點擊齒輪呼叫出設定區後，必須要點X或者點擊設定區外觸發關閉，才可操作下個動作
◎◎ 20190411確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
點擊齒輪呼叫出設定區後，必須要點X或者點擊設定區外觸發關閉，才可操作下個動作
![image](https://user-images.githubusercontent.com/41721950/56258011-a48b5600-6100-11e9-8cca-05a19d465732.png)
◎◎ 20190417確認以上正式環境內容 ◎◎
