### ISSUE TITLE
【問題】當序號產生器重複登入帳號，會無法兌獎

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#823]
重複使用同一個帳號登入序號產生器，會出現『您已經索取過序號』
![image](https://user-images.githubusercontent.com/41721950/48927689-f691cc00-ef12-11e8-98af-5ccf5e851e9a.png)
當出現『您已經索取過序號』的提示訊息，【互動後台管理】的獎項雖然是在【未兌換】區
![image](https://user-images.githubusercontent.com/41721950/48927704-2214b680-ef13-11e8-8a98-b87687870929.png)
但【兌換密碼】的頁面不會顯示『活動名稱』並出現『無此序號』的提示訊息
![image](https://user-images.githubusercontent.com/41721950/48927744-b0893800-ef13-11e8-8f2c-6af48c838156.png)
延伸：當【活動名稱】有做任何修改，兌換頁面也不會顯示活動名稱(如紅框)
![image](https://user-images.githubusercontent.com/41721950/48927863-a0258d00-ef14-11e8-90c2-bf64cd62480b.png)
以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
序號id取值錯誤
![image](https://user-images.githubusercontent.com/10150807/48928394-63a86000-ef19-11e8-8b06-04270c0999fd.png)
要使用_serial_number._id
@Gabe-Liu

**Comment by AnitaRyzo** [comment]
即使出現『您已經索取過序號』，還是可以正常兌獎
![image](https://user-images.githubusercontent.com/41721950/48991114-79619380-f16c-11e8-874d-bff935b5014b.png)
當【活動名稱】有做任何修改，兌換頁面也會顯示活動名稱(如紅框)
![image](https://user-images.githubusercontent.com/41721950/48991160-b037a980-f16c-11e8-935a-eef50affab25.png)
◎◎ 20181126確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
【序號機】兌獎已可正確執行，【活動名稱】也會即時更新
![image](https://user-images.githubusercontent.com/41721950/51291182-44254380-1a41-11e9-8c0d-cfd75d3283b8.png)
◎◎ 20190117確認以上正式環境內容 ◎◎
