### ISSUE TITLE
【建議】跨帳號複製 按鈕位置與wording不一致

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#829]
目前跨帳號複製中 
複製專案時，點選完複製到的目的地帳號後，下方出現的是：
[關閉][確認]
<img width="1030" alt="2018-11-26 11 52 09" src="https://user-images.githubusercontent.com/34560641/48992335-2c80bb80-f172-11e8-98aa-39c81af54994.png">

但是跨帳號複製表單時，卻是：
[確認][返回]
而且上方也顯示「專案複製」應該要改為「表單複製」
<img width="1034" alt="2018-11-26 11 51 50" src="https://user-images.githubusercontent.com/34560641/48992393-72d61a80-f172-11e8-97f9-9a48a0dbd067.png">

建議調整跨帳號複製表單的按鈕位置 應改為與複製專案時一樣（左關閉右確認）
並將跨帳號複製表單的標題修正

以上

**Comment by AnitaRyzo** [comment]
左關閉右確認且標題修改為『表單複製』
![image](https://user-images.githubusercontent.com/41721950/48999806-af197300-f192-11e8-8a57-47a0fbe5e6c8.png)
◎◎ 20181126確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
左關閉右確認且標題修改為『表單複製』
![image](https://user-images.githubusercontent.com/41721950/55947618-682fa400-5c81-11e9-9d08-675ee387dcb1.png)
◎◎ 20190411確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
左關閉右確認且標題修改為『表單複製』
◎◎ 20190417確認以上正式環境內容 ◎◎
