### ISSUE TITLE
【建議】社群帳號登入

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#830]
許多人手機裡都有安裝FB這類型的APP
但是不一定有使用手機瀏覽器登入
因此玩互動元件的時候，需要再輸入一次帳號密碼(但很難記住)
間接影響參與意願

不知道能不能如下圖方式來做APP登入連動
![img_0311](https://user-images.githubusercontent.com/34327325/48998120-70cd8500-f18d-11e8-8d85-0f58763c445c.PNG)

**Comment by ryuichl** [comment]
就我目前所看到的資訊
基本上是不可能的
要達到圖中所示要元生APP才可以
網頁無法達成

**Comment by weilyn** [comment]
OK沒問題
我了解意思了
感恩

順便問一下，未來預計會開放的社群驗證方式大概有哪些種類
又大概會在什麼時候上線呢
