### ISSUE TITLE
【建議】表單工具的樣式選擇

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#838]
目前表單的樣式表裡有兩個主題可以選擇
不過使用者在操作上可能不是這麼的理解，所以變成大家做出來的表單都是
白底、黑字、綠線

之前有提出一個選配色的概念，這次附上圖片做參考
這個情境是他會給很多不同的色票，主要是可以看到色系
實際套用時，不一定會用到色票裡的全部顏色，但是可以讓使用者有底，
知道大概套用了什麼類型的顏色，接下來才做套用

我覺得像是表單或是一些比較深入型的樣式設定可以，使用者在第一時間不會去調這麼多細項
是不是有可能變成外層選擇色票，如果要做自訂化調整時，才跳出視窗做顏色對應的修改
同時這個網站y有個功能，就是使用者可以新增自己的色票，但這部分可能我們還不會去做。

<img width="1025" alt="2018-11-29 11 56 59" src="https://user-images.githubusercontent.com/34327325/49198720-84682e00-f3cf-11e8-95af-2d6abb199e0e.png">

**Comment by weilyn** [comment]
類似這樣子的結構

<img width="917" alt="1" src="https://user-images.githubusercontent.com/34327325/49198986-be85ff80-f3d0-11e8-9db9-93cf206b43aa.png">
![2](https://user-images.githubusercontent.com/34327325/49198988-be85ff80-f3d0-11e8-9ea8-c8fb7076f9cb.jpg)

**Comment by eatinggg** [comment]
已完成介面圖，等 @liucwlewis 修改完成後，會跟表單優化的其他項目一起放到zeplin上～

**Comment by liucwlewis** [comment]
這四個issue的畫面都有關連，所以畫再一起一次說明
#707 ：
進度條新增開關
<img width="460" alt="2018-12-12 11 31 15" src="https://user-images.githubusercontent.com/37163894/49845382-74097780-fe01-11e8-9ac1-a398c852417e.png">
#708 ：
新增送出後執行動作的設定
<img width="1233" alt="2018-12-12 11 32 19" src="https://user-images.githubusercontent.com/37163894/49845433-ab782400-fe01-11e8-96a7-aca99c4be47b.png">
#838：
新增“色彩參考”，之後會提供不同的顏色組合。原本直接顯示的色彩設定都藏在進階設定中。
“選擇主題樣式包”將顏色部分拿掉，有重新規劃樣式
<img width="217" alt="2018-12-12 11 30 13" src="https://user-images.githubusercontent.com/37163894/49845363-56d4a900-fe01-11e8-89a1-1c42a2ff34e5.png">
<img width="824" alt="2018-12-12 11 29 17" src="https://user-images.githubusercontent.com/37163894/49845335-31e03600-fe01-11e8-9aa7-f15a50f9f3e9.png">
#861 :
介面微調，直接參考圖片
<img width="227" alt="2018-12-12 11 32 44" src="https://user-images.githubusercontent.com/37163894/49845555-1c1f4080-fe02-11e8-96ca-2317b7e2eca4.png">

確切的設定直接看Zeplin內容
連結：https://zpl.io/andOARx

**Comment by weilyn** [comment]
重新打開
