### ISSUE TITLE
【問題】SHOWCASE網址無法顯示 403

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#847]
<img width="960" alt="2018-12-03 11 09 25" src="https://user-images.githubusercontent.com/34560641/49350906-edabb200-f6eb-11e8-896e-a1a1d606e9de.png">
如標題
網址如下：
https://template-showcase.ryzoweba.io/
煩請協助查明

**Comment by ryuichl** [comment]
可以用了
上次更新動到一點東西

**Comment by wilmaftliu** [comment]
tks
