### ISSUE TITLE
小問題～按鈕的邊緣有時候會消失～

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#85]
mac畫面縮放80%以下的時候 
儲存按鈕的邊緣會消失

<img width="543" alt="2018-05-09 12 08 23" src="https://user-images.githubusercontent.com/34293268/39795285-c5e3a088-5381-11e8-804c-a242ea19c150.png">

**Comment by Gabe-Liu** [comment]
看似是因為使用特殊的漸層色邊框，在縮小時會發生此情況~
如果要改就是拿掉漸層色邊框~
