### ISSUE TITLE
【問題】序號機寄至指定信箱，最後一筆資料未完整

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#851]
在表單設定的地方，開啟『回覆寄至指定信箱』的功能
![image](https://user-images.githubusercontent.com/41721950/49417497-e9999600-f7b8-11e8-9455-878e1fe9c3d2.png)
設定『累積到第三筆』的時候發送郵件，結果寄出的郵件『第三筆』的資料不完整
![image](https://user-images.githubusercontent.com/41721950/49418613-0daba600-f7be-11e8-8487-ecd50862c3c3.png)
一般表單與抽獎類型沒有這個問題
請協助處理以上問題，感恩~

**Comment by ryuichl** [comment]
因為序號流程是先填表再取序號
所以在寄信時還沒有取到序號會造成這種狀況

會把序號的部分改成有完整資料的才計入累積筆數

**Comment by AnitaRyzo** [comment]
若設定的是累積第N筆寄送郵件，郵件將會在第N+1筆時寄出
![image](https://user-images.githubusercontent.com/41721950/49429767-537b6500-f7e4-11e8-8f6a-b0053df61aad.png)
◎◎ 20181204確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
若設定的是累積第N筆寄送郵件，郵件將會在第N+1筆時寄出(綠框)
![image](https://user-images.githubusercontent.com/41721950/51363752-7a7fc300-1b14-11e9-99e6-d19f23207ab3.png)
◎◎ 20190118確認以上正式環境內容 ◎◎
