### ISSUE TITLE
[測試環境] 序號的社群希望預設全開

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#852]
![image](https://user-images.githubusercontent.com/10150807/49418994-cfaf8180-f7bf-11e8-8947-c23426c2b4dc.png)

line預設沒打開
希望能打開
感恩

**Comment by AnitaRyzo** [comment]
所有互動預設皆已將社群開啟
![image](https://user-images.githubusercontent.com/41721950/50581861-96d6fb00-0e98-11e9-9d33-3a8f5a655018.png)
◎◎ 20190102確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
所有互動預設皆已將三項社群皆開啟
◎◎ 20190117確認以上正式環境內容 ◎◎
