### ISSUE TITLE
[測試環境] 小積木無法使用

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#854]
![image](https://user-images.githubusercontent.com/10150807/49488647-78261a00-f882-11e8-9f04-28990c62b820.png)

點小積木沒反應
附上錯誤訊息

**Comment by AnitaRyzo** [comment]
小積木未出現任何錯誤訊息，可正常顯示
◎◎ 20190102確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
小積木未出現任何錯誤訊息，可正常顯示
◎◎ 20190117確認以上正式環境內容 ◎◎
