### ISSUE TITLE
【問題】互動元件各狀態提示頁的圖示選擇

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#856]
<img width="1030" alt="2018-12-05 12 11 23" src="https://user-images.githubusercontent.com/34293268/49489653-0e5c3f00-f887-11e8-8815-d5e73fb538f9.png">

互動元件>各狀態提示頁>右側控制欄

圖示選擇無法操作
煩請協助解惑～謝謝～

**Comment by AnitaRyzo** [comment]
#820 已在測試環境修正
.2 狀態提示頁的身分認證設定，【圖示選擇】的下拉式選單
![image](https://user-images.githubusercontent.com/41721950/49493174-ff30bd80-f895-11e8-878d-9f993df9991a.png)
請知悉~

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51307613-1d83fe80-1a7b-11e9-90a1-2a7a41f245f8.png)
◎◎ 20190117確認以上正式環境內容 ◎◎
