### ISSUE TITLE
【建議】系統裡的橫向捲軸優化

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#857]
HI，系統裡有部分區域使用了橫向捲軸
像是團隊管理、字體的設定
目前是設定一次切換一格
在團隊數量多的情況下，切換較慢
不知道能否變成類似以下網頁的橫向捲軸的切換方式

等於不會卡在定點，但是直接點選圓圈也能跳轉到指定的位置
https://2018floraexpo.tw/

**Comment by Samasianspock** [comment]
這是一個好的建議，若能使用觸控板快速滑動查看更多內容，同樣的設計也希望能套用在「套版管理」的主題分類區，這就麻煩工程的夥伴評估，感恩！

**Comment by AnitaRyzo** [comment]
系統目前直接點選圓圈，能跳轉到指定的位置
團隊管理
![image](https://user-images.githubusercontent.com/41721950/59658352-f66e5c00-91d5-11e9-9073-7d593593da44.png)
套版管理
![image](https://user-images.githubusercontent.com/41721950/59658496-5e24a700-91d6-11e9-93f2-086f902bd512.png)
數據後台
![image](https://user-images.githubusercontent.com/41721950/59658469-49481380-91d6-11e9-9c27-07dd604dbb14.png)
◎◎ 20190618確認以上正式環境內容 ◎◎
