### ISSUE TITLE
【測試環境】專案網址發佈於社群，數據後台會是空白資料

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#858]
若直接將專案網址貼入社群(FB、LINE、TWITTER、LinkedIn)發佈，不從瀏覽器開啟專案網址!
![image](https://user-images.githubusercontent.com/41721950/49497620-cd265800-f8a3-11e8-9bf3-180c70d42cc6.png)
【數據後台】的資料顯示欄位為空白
![image](https://user-images.githubusercontent.com/41721950/49497941-8be27800-f8a4-11e8-8bbe-ff5cba67f84d.png)
錯誤訊息如下
![image](https://user-images.githubusercontent.com/41721950/49496417-db26a980-f8a0-11e8-820e-74bd6023de0e.png)
以上錯誤訊息請協助處理，感恩~

若專案尚無使用者在瀏覽器的資料，會出現以下提示訊息
![image](https://user-images.githubusercontent.com/41721950/49497891-6eada980-f8a4-11e8-9e3f-0f850fb9636f.png)

**Comment by Gabe-Liu** [comment]
無法重現，暫時先放著

**Comment by ryuichl** [comment]
太久先關掉
有一樣問題再提出
