### ISSUE TITLE
【發佈後台】發佈更新開啟時間時錯誤

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#86]
發佈專案後，一開始沒設到發佈時間。點擊開啟發佈時間時，無法開啟更動發佈時間，並有以下錯誤：

> 例圖

![default](https://user-images.githubusercontent.com/20262208/39797652-beab25da-538f-11e8-952e-401354f045d3.png)

**Comment by ai015606220** [comment]
prod打包時發生的套件問題，暫時用非prod打包，後續繼續找解決方法

https://bit.ly/2K9q5rW

**Comment by ai015606220** [comment]
已解決
更新
@angular/cdk 至6.0.1
ng-pick-datetime至6.0.1
