### ISSUE TITLE
【問題】表單跳題後可以直接跳到結束

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#863]
![s__55459846](https://user-images.githubusercontent.com/36216073/49632881-4653b580-fa32-11e8-926e-b4610b15680a.jpg)

和上面的圖片一樣，其實男生的題目在第三題就結束了，目前的狀況沒辦法直接送出表單，仍然要先去第四題，但其實第四題並不需要讓男生看到，surveycake的作法是可以直接跳轉到結束頁，希望 @ryzojudy 可以幫忙想一下，謝謝~

**Comment by wilmaftliu** [comment]
希望的路徑是：
男生：1-2-3-5
女生：1-2-4-5
但因為題目是線性的，即使男生不需要看到第4題，第3題打完後，還是會先出現第4題。
不知道在跳題流程中，是否可以把第3、4題設為隱藏提，只有當回答完2後才會出現，
避免讓應該被跳過的題目因為線性流程的關係仍然被顯示出來。
