### ISSUE TITLE
【問題】提示頁面裡的電腦版設定應該隱藏

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#864]
在提示的編輯中，背景設定裡面的電腦版開關應該隱藏，
因為並不是直接切換到電腦版的提示，也不是直接開啟電腦版的提示

<img width="1364" alt="2018-12-07 3 41 42" src="https://user-images.githubusercontent.com/34327325/49634202-f7f4e580-fa36-11e8-96a5-262ca06af8ff.png">

**Comment by AnitaRyzo** [comment]
提示的編輯頁可以設定的內容如下
![image](https://user-images.githubusercontent.com/41721950/50584334-e671f280-0ea9-11e9-92eb-98c520f25073.png)
◎◎ 20190102確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已移除『電腦版設定』
在手機版設立的提示，只能在手機版連結；在電腦版設立的提示，只能在電腦版連結。
![image](https://user-images.githubusercontent.com/41721950/51308451-1958e080-1a7d-11e9-91f0-a27059285bff.png)
◎◎ 20190117確認以上正式環境內容 ◎◎
