### ISSUE TITLE
【問題】序號產生器提示頁面文字修改

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#866]
序號產生器的提示頁面右側文字“獎項已抽完“
但序號產生器應用不只是獎品，所以應該需要修改

<img width="915" alt="2018-12-07 5 41 03" src="https://user-images.githubusercontent.com/34327325/49640617-03e9a300-fa49-11e8-98a6-a957696263e8.png">

他的提示名稱目前也是獎項已抽完，應該要一併處理

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51309320-14952c00-1a7f-11e9-9d2d-792df807101d.png)
◎◎ 20190117確認以上正式環境內容 ◎◎
