### ISSUE TITLE
【問題】套版主題設定的搜尋標籤指向錯誤

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#868]
在套版管理>套版主題設定裡進行新的主題新增
使用點選的方式將標籤收錄沒問題
但如果使用搜尋的方式，搜尋結果雖然正確，點選取以後都會變成“電子名片“

例如我搜尋”翻頁式”，出現的結果也是翻頁式的選項，但是選擇它的時候會變成“電子名片”

<img width="553" alt="2018-12-10 4 03 41" src="https://user-images.githubusercontent.com/34327325/49718573-7bac0d80-fc95-11e8-933d-24effd81b65b.png">

**Comment by AnitaRyzo** [comment]
左邊為搜尋狀況，右邊為全部標籤
選擇了【11】跳出AB，選擇了【111】會跳出BA；似乎是因為鎖住了全部標籤的所在位置...!?
![image](https://user-images.githubusercontent.com/41721950/49724642-bec1ad00-fca4-11e8-8152-5ff1b6d97b1e.png)
以上意見僅供參考~

**Comment by AnitaRyzo** [comment]
已顯示正確標籤
![image](https://user-images.githubusercontent.com/41721950/50671354-53050280-100c-11e9-8946-9ef05bdc6d21.png)
◎◎ 20190104確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
已可帶入正確標籤
![image](https://user-images.githubusercontent.com/41721950/51365248-50310400-1b1a-11e9-9d14-86d6a0dbde1f.png)
◎◎ 20190118確認以上正式環境內容 ◎◎
