### ISSUE TITLE
【問題】刮刮樂在電腦上無法刮開會直接跳出獎品且沒有恭喜中獎頁 & 編輯恭喜中獎頁不會出現獎項名

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#870]
如同上面所提到的，使用電腦開啟時，登入後點擊開始，完全不需要刮獎品圖案就會直接出現，而且也不會跳出恭喜中獎的頁面

![20181211_104646](https://user-images.githubusercontent.com/36216073/49775425-27576b00-fd33-11e8-8caf-4c502e3ec018.gif)
網址如下：https://testlottery1211.ryzoweba.io

另外還有碰到一個問題，
在編輯的時候，進入編輯恭喜中獎頁，如果只選擇顯示「獎項名稱」，離開編輯區後，再次進入編輯區時不會看到獎項名稱出現

離開前
![image](https://user-images.githubusercontent.com/36216073/49775757-28d56300-fd34-11e8-83b3-f5a357d283d1.png)

離開後再進入
![image](https://user-images.githubusercontent.com/36216073/49775762-34288e80-fd34-11e8-86a5-14fe1ef74388.png)

以上兩個問題再麻煩協助確認，謝謝~

**Comment by ryuichl** [comment]
請問使用的瀏覽器和版本?
我剛測試可以正常刮
感恩

**Comment by wendykuo** [comment]
我是使用 chrome 版本是70

**Comment by AnitaRyzo** [comment]
1.刮刮樂的遮罩圖片、背景圖片、獎項圖片皆為.png檔，獎項設置超過40項；已可執行
![image](https://user-images.githubusercontent.com/41721950/55777799-a1c2ac80-5ad3-11e9-9603-c74abf7b823f.png)

X2.進入狀態提示頁時，若第一個就點選『恭喜中獎』，看不到獎項名稱；
但若先點選『中獎紀錄』，再點選『恭喜中獎』就看得到獎項名稱。
第二個問題請協助解決，感恩~
