### ISSUE TITLE
【問題】表單在預覽狀態時被刪除

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#871]
1. 在預覽狀態時進行填寫表單後
<img width="1280" alt="2018-12-11 1 54 44" src="https://user-images.githubusercontent.com/34293268/49781148-9ee5c400-fd4c-11e8-87aa-bfdc7c5009c1.png">

2. 將第一題的答案刪除 想重新輸入
<img width="1278" alt="2018-12-11 1 54 55" src="https://user-images.githubusercontent.com/34293268/49781176-b4f38480-fd4c-11e8-865e-7982f6304d18.png">

3. 取消選取後再按一次delete，結果表單就被刪除了
<img width="1280" alt="2018-12-11 1 55 02" src="https://user-images.githubusercontent.com/34293268/49781194-c0df4680-fd4c-11e8-97ad-345ebf255c97.png">

4. 在編輯區也找不到原本設計好的表單，只能按上一步把表單救回來～
<img width="1280" alt="2018-12-11 1 55 12" src="https://user-images.githubusercontent.com/34293268/49781239-e9674080-fd4c-11e8-97a0-bd2adea8e3e5.png">

不確定是什麼原因，造成表單在預覽狀態時被刪除，
再麻煩協助解惑～感恩～

**Comment by AnitaRyzo** [comment]
不管表單是甚麼題型，只要在題目空白處按下DELETE，表單都會被刪除
![image](https://user-images.githubusercontent.com/41721950/49784439-49171900-fd58-11e8-8090-267b01b3d0be.png)
以上請參考，感恩~

**Comment by AnitaRyzo** [comment]
表單在預覽狀態已不會被刪除
◎◎ 20190104確認以上測試環境內容 ◎◎
