### ISSUE TITLE
【建議】序號產生器按鈕換行

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#877]
hi
目前按鈕、互動元件都可以設定換行
唯獨序號產生器的按鈕不行，可能需要調整一下

此外我覺得使用者想要修改序號產生器的按鈕文字的機率大於其他抽獎互動元件

但目前按鈕設定都是藏起來，放在進階設定裡的，有沒有可能把序號產生器的按鈕文字選項抓出來放？

<img width="600" alt="2018-12-13 5 12 13" src="https://user-images.githubusercontent.com/34327325/49928273-cda19d00-fefa-11e8-9f6d-35443a578584.png">

**Comment by Samasianspock** [comment]
這邊會建議序號機的按鈕文字也可以和一般/互動元件按鈕一樣能換行，至於進階設定中的各種設定有哪些適合放到外面基本設定，之後會把所有互動元件的設定都做一次評估和整理，再上傳至zeplin，感恩～

**Comment by AnitaRyzo** [comment]
序號產生器按鈕文字選項已可編輯換行
![image](https://user-images.githubusercontent.com/41721950/50678463-be18fe00-1039-11e9-8dd1-e139a60e4ba4.png)
◎◎ 20190104確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
序號產生器按鈕文字選項已可編輯換行
◎◎ 20190118確認以上正式環境內容 ◎◎
