### ISSUE TITLE
【錯字】內嵌程式碼右側控制欄應顯示「內嵌程式碼」

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/v3-report#878]
內嵌程式碼 右側控制欄的地方
應該是顯示「內嵌程式碼」
現在跟內嵌網頁一樣顯示的都是內嵌網頁
現在狀況如下：

內嵌程式碼
![image](https://user-images.githubusercontent.com/34263719/49977341-eeacd100-ff80-11e8-8b77-85779d8f675e.png)

內嵌網頁(無誤)
![image](https://user-images.githubusercontent.com/34263719/49977347-f5d3df00-ff80-11e8-907c-4bd40a17ed4f.png)

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51367623-6fce2980-1b26-11e9-9bd0-6f822560d155.png)
◎◎ 20190118確認以上正式環境內容 ◎◎
