### ISSUE TITLE
【社群分享設定-發佈後】未顯示已設定之資訊

### ISSUE THREAD

**Issue by Isabella-Zheng** [ryuichl/v3-report#88]
Line / Facebook 社群分享 有設定 標題、描述、圖片 皆未顯示

> 社群分享預覽圖 (正確)

![default](https://user-images.githubusercontent.com/20262208/39797782-475fb238-5390-11e8-9639-9943cc10fa31.png)

> Line 例圖 (錯誤)

![default](https://user-images.githubusercontent.com/20262208/39797809-66f92228-5390-11e8-93a0-7a41b94826b7.png)

**Comment by ryuichl** [comment]
已修正
