### ISSUE TITLE
google plus 樣式更改

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#884]
因為google plus 即將關閉服務
所以需要將google相關登入樣式做修改
不能再用紅色

![image](https://user-images.githubusercontent.com/10150807/50327121-ad8c6200-0528-11e9-9b5f-de1237ef4bac.png)

再麻煩幫忙設計
感恩
https://developers.google.com/+/mobile/android/api-deprecation

**Comment by liucwlewis** [comment]
連結：
1.（註冊模式） https://zpl.io/andkN6O
2.（登入模式） https://zpl.io/2ZjDyqX
3.（個人帳號） https://zpl.io/aXk0Zkx
4.（身份驗證） https://zpl.io/bzAwGKl
icon https://drive.google.com/drive/u/1/folders/1uCuPE8bGOq-u0b2Y2uTWhrgWzJJG_wSm

**Comment by AnitaRyzo** [comment]
（註冊模式）（登入模式）（個人帳號）已修改
![image](https://user-images.githubusercontent.com/41721950/50751278-16434080-1284-11e9-9f7a-b293e22e061d.png)
而（身份驗證）尚未更新
![image](https://user-images.githubusercontent.com/41721950/50751346-5acedc00-1284-11e9-921c-f3a6f0f7d5bd.png)
◎◎ 20190107確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
（身份驗證）已更新
![image](https://user-images.githubusercontent.com/41721950/51023862-f03ed880-15c2-11e9-863e-12d83ae17708.png)
◎◎ 20190111確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51219881-da883500-196d-11e9-857d-c54b060374ae.png)
◎◎ 20190116確認以上正式環境內容 ◎◎
