### ISSUE TITLE
【測試環境】重複使用域名，數據後台會自動將原專案資料帶回

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#885]
域名雖是唯一值，但刪除專案後再使用相同域名，GA後台就會把原專案資料帶回。
範例：12/5 設立域名為【INTER】的專案
![image](https://user-images.githubusercontent.com/41721950/50327413-f98bd680-0529-11e9-94e2-8b0472c84ab0.png)
12/21將之刪除後，重新創立相同域名的【INTER】專案
尚未執行就可以在『數據後台』看到系統已將12/5的同名專案資料帶入了。
![image](https://user-images.githubusercontent.com/41721950/50330428-1dedb000-0536-11e9-8b3c-fd0642d0aef5.png)

建議：連結元件括號中顯示的代號是相同的，會分成兩個項目計數是因為名稱有所更動
請問相同的連結元件代號是否可以合併計算呢?
![image](https://user-images.githubusercontent.com/41721950/50329874-ef6ed580-0533-11e9-82a5-fd019f6670b4.png)

以上問題與建議請參考，感恩~

**Comment by ryuichl** [comment]
@Gabe-Liu  偷懶被抓包

**Comment by ryuichl** [comment]
對建議的想法
有可能用戶改名是為了做類似AB測試
所以我覺得不合併可能會更好
畢竟合起來就不知道個別成效

**Comment by AnitaRyzo** [comment]
step1.在2019/1/4 設立域名為【INTER】的專案
step2.刪除【INTER】專案
step3.再次於2019/1/4 設立域名為【INTER】
→數據後台的資料仍會帶入，已確認同日的資料帶入問題目前無解。
◎◎ 20190104確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
不同的建立日期，數據後台的資料不會帶入。
◎◎ 20190118確認以上正式環境內容 ◎◎
