### ISSUE TITLE
【問題】跨帳號查看專案出現的畫面

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#886]
因為是客戶的專案，尚不知目前專案發佈情形
但猜測應該是發佈後，又有申請審核，因為正式網址目前依然可以使用的
提供一下兩張圖，可能有跑版、或是其他問題存在

<img width="592" alt="2018-12-22 2 09 19" src="https://user-images.githubusercontent.com/34327325/50371333-8e0e3b80-05f3-11e9-9991-6b5d8e6f5a72.png">
<img width="590" alt="2018-12-22 2 09 11" src="https://user-images.githubusercontent.com/34327325/50371334-8ea6d200-05f3-11e9-9dc4-896e76f327c3.png">

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51368405-34355e80-1b2a-11e9-9ebe-5d7188f6c6d6.png)
◎◎ 20190118確認以上正式環境內容 ◎◎
