### ISSUE TITLE
【問題】臉書工具內嵌型尺寸調整

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#888]
目前臉書工具嵌入型的“嵌入粉絲團”以及“嵌入貼文”這兩項
尺寸都是固定的

嵌入粉絲團是寬度尺寸固定在254px(若小於這個尺寸會直接被裁切)
嵌入貼文是寬度尺寸固定在337px(文字會隨寬度調整，照片不會，重點是預設尺寸就已經超過編輯器了)

看到這個網頁裡面提到“調適型寬度”，不知道是否適用於WEBA
https://developers.facebook.com/docs/plugins/page-plugin
而嵌入FACEBOOK的貼文、粉絲團時，在facebook develpoers裡好像是可以指定寬度跟高度的
所以如果調適型如果真的不能達成的話，這部份尺寸設定可能必須要進入WEBA裡
知道這類工具有最大跟最小尺寸的限制，不過目前是沒有這個彈性讓使用者決定大小

之前好像有提到社群工具可以做一次整體的優化檢視排程

<img width="324" alt="2018-12-24 9 54 25" src="https://user-images.githubusercontent.com/34327325/50389276-5b835080-0763-11e9-9c1c-c98acda96723.png">
嵌入貼文

<img width="322" alt="2018-12-24 9 51 27" src="https://user-images.githubusercontent.com/34327325/50389279-64742200-0763-11e9-89ac-9baaceb92aee.png">
嵌入粉絲團

**Comment by weilyn** [comment]
附註 粉絲團在編輯器中縮放不會跟著縮放大小，
但是預覽時會調整大小
可能是快取的問題吧？

**Comment by AnitaRyzo** [comment]
臉書工具(內嵌型)已可自由調整尺寸，滾軸可協助完整呈現內文
![image](https://user-images.githubusercontent.com/41721950/59661144-b9599800-91dc-11e9-84d5-765b5895c3ba.png)
◎◎ 20190618確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
臉書工具(內嵌型)已可自由調整尺寸，滾軸可協助完整呈現內文
![image](https://user-images.githubusercontent.com/41721950/60503839-0e280300-9cf3-11e9-827e-a4ea92ee64cb.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
