### ISSUE TITLE
【問題】按鈕點擊後，連結的頁面全白

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/v3-report#889]
客戶反映自己電腦版的部分，有一個按鈕點擊過去後甚麼都沒有顯示
活動網址：https://btschool0117.ryzoweba.io
點擊「立即報名」後甚麼都看不到，如下圖
![image](https://user-images.githubusercontent.com/36216073/50390227-7d82d000-076f-11e9-8ef1-756b12b61848.png)
網址就會變成是 https://btschool0117.ryzoweba.io/404
再麻煩盡快確認，謝謝~

客戶反映自己的專案文字會失蹤，剛剛複製他的專案過來時，一度有遇到這個狀況，但現在又不一定，如過可以確認的話再麻煩協助確認，感謝~
![image](https://user-images.githubusercontent.com/36216073/50390084-7ce93a00-076d-11e9-84e3-49c4b1588f70.png)

**Comment by ryuichl** [comment]
他按鈕看起來沒設定任何連結
請問他在後台設定連去哪裡?

另外文字失蹤是怎樣的操作會失蹤
怎樣叫失蹤?
希望可以講更詳細一點

**Comment by wendykuo** [comment]
後台的也是連到他設定的頁面
![image](https://user-images.githubusercontent.com/36216073/50390384-b15ef500-0771-11e9-86ea-f38fc290d1e9.png)

發佈的部分是有時候剛進去看到文字1秒後就不見了
後台的部分也是換到頁面後出現1秒文字消失，但是點擊文字剛剛存在的位置仍然有文字的存在，顏色上也不是白色
![image](https://user-images.githubusercontent.com/36216073/50390438-46fa8480-0772-11e9-85a4-4e272480bbc2.png)
