### ISSUE TITLE
【建議】發佈後的網頁預載動畫

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#897]
看過很多H5網站，或是以下這類型的網站
因為動畫、圖片多，所以會優先進行預載以後才顯示網頁
(至少先預載好1個頁面的內容)，因為有動畫圖案了，可以讓人感覺等待的時間沒這麼長
<img width="133" alt="2018-12-26 9 54 20" src="https://user-images.githubusercontent.com/34327325/50428663-6b7e6a00-08f4-11e9-8bff-f3328654d7a6.png">

目前WEBA生成的網頁，經常圖片還沒讀取玩，動畫就結束了
導致設計者的許多巧思都不被人看見
建議可以增加類似這樣子的元素
用loading可能不太好，最好是一些可以分散注意力的動畫，
但在各場景都很通用的選項(或是要讓使用者從幾個預設的選擇)

https://www.esunbank.com.tw/event/credit/picard/index.html?

**Comment by eatinggg** [comment]
經過一番討論～附上最後決定參考動畫

https://codepen.io/artboardartisan/pen/VLzKVN

<img width="739" alt="2019-01-09 3 58 44" src="https://user-images.githubusercontent.com/34293268/50885036-8c33dd00-1427-11e9-8859-5bf7e02f99fd.png">

**Comment by AnitaRyzo** [comment]
「預覽」「UAT環境」「發佈後環境」都會出現預載動畫
![image](https://user-images.githubusercontent.com/41721950/51372220-6ac5a600-1b37-11e9-898a-0c85156945ff.png)
◎◎ 20190118確認以上正式環境內容 ◎◎
