### ISSUE TITLE
【問題】抽獎設置的抽獎次數未判斷抽獎日期

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#899]
前提：有抽就有獎項，有獎項就立刻回填表單
在抽獎設置時的抽獎上限達標時，對應顯示的提示訊息如連結的右邊
此抽獎配置宣告每人**每天可抽獎一次，中獎一次**，最多中獎十次。
![image](https://user-images.githubusercontent.com/41721950/50462199-9e8d3000-09be-11e9-94e2-79580ef430f6.png)

由表單回填的資料可知，12/26有抽獎1次/天且每人每天最多抽中1次
![image](https://user-images.githubusercontent.com/41721950/50462266-0c395c00-09bf-11e9-821f-dcb6ba6800be.png)
但12/27要再次抽獎時，卻出現以下的提示訊息
![image](https://user-images.githubusercontent.com/41721950/50462313-689c7b80-09bf-11e9-9d2f-dc9d2e17727b.png)
目前已知錯誤是**抽獎次數未判斷抽獎日期**
因為不管距離第一次抽獎幾天後，此互動元件都跳相同的提示訊息。
以上問題請協助處理，感恩~

**Comment by weilyn** [comment]
+1
一樣的問題
<img width="312" alt="2018-12-27 10 31 28" src="https://user-images.githubusercontent.com/34327325/50462840-e31aca80-09c2-11e9-9764-b12f91efc039.png">
<img width="323" alt="2018-12-27 10 31 57" src="https://user-images.githubusercontent.com/34327325/50462841-e31aca80-09c2-11e9-820a-083d421f609d.png">
<img width="434" alt="2018-12-27 10 33 24" src="https://user-images.githubusercontent.com/34327325/50462842-e3b36100-09c2-11e9-9a2c-5a66b968fc15.png">

**Comment by AnitaRyzo** [comment]
已可每日一抽
![image](https://user-images.githubusercontent.com/41721950/50499307-a8c53200-0a83-11e9-8e21-0889d603b308.png)
◎◎ 20181228確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
每人每日可抽一次
![image](https://user-images.githubusercontent.com/41721950/51372463-5afa9180-1b38-11e9-899a-5987c1ca122f.png)
◎◎ 20190118確認以上正式環境內容 ◎◎
