### ISSUE TITLE
【問題】表單複製時，最後步驟的提示框按鈕擺放錯誤

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#902]
![2019-01-03 11 48 11](https://user-images.githubusercontent.com/37163894/50623151-06f38880-0f4e-11e9-997c-d855209faa28.png)

當跨帳號複製表單時，執行到最後步驟要點擊目標帳號時，跳出的提示框下方的按鈕應該為「左邊是“上一步”右邊是“完成”」，同時整個提示框應該直接關閉。

**Comment by ai015606220** [comment]
我覺得 '返回' 好像比 '上一步'  適合耶

**Comment by AnitaRyzo** [comment]
跨帳號複製表單的按鈕內容已修改如下
![image](https://user-images.githubusercontent.com/41721950/50682308-62ef0780-1049-11e9-9559-27e3deb3ee39.png)
◎◎ 20190104確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51420457-15d46f00-1bcd-11e9-8bb5-83172a8c01c0.png)
◎◎ 20190119確認以上正式環境內容 ◎◎
