### ISSUE TITLE
【問題】跨帳號查看表單時，一旦點擊表單時就無法取消選取狀態

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#903]
目前狀態為：一旦點擊表單時，就強制必須選取一個表單。
希望這部分的選取再重複點擊時能夠取消選取
![2019-01-03 12 00 49](https://user-images.githubusercontent.com/37163894/50623309-4d95b280-0f4f-11e9-9568-787675308f9e.png)

**Comment by ai015606220** [comment]
但他本來就必須選取一個表單, 不然無法進行複製
請問讓他取消的用意是?

**Comment by Samasianspock** [comment]
其實是希望不需要強制使用者一定要點擊叉叉圖示關閉視窗，才能取消選取以及複製表單的整個動作，希望保留一點操作上的自由。
所以這裡建議：
在沒有選擇任何一個表單的情況下，下方的「複製表單」按鈕就無法使用，

另外也希望在「專案複製」的時候也能夠有相同的機制，因為現在專案複製，若沒有選擇目標帳號時還是可以點擊「確認」，點擊完後就會一直loading。

以上建議，感謝！

**Comment by AnitaRyzo** [comment]
目前可以選取0個以上的表單
◎◎ 20190104確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
目前可以選取0個以上的表單
◎◎ 20190119確認以上正式環境內容 ◎◎
