### ISSUE TITLE
【問題+建議】資料綁定的文字元件資料顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#907]
一、文字換行
![image](https://user-images.githubusercontent.com/41721950/50758676-d426f880-129d-11e9-9e4b-8f8e62b1a15f.png)
※※『分類行銷內容』文案庫內容設定如下
![image](https://user-images.githubusercontent.com/41721950/50758683-d8ebac80-129d-11e9-9ee0-1fba47f46ad4.png)
 『分類行銷內容』可以選擇【對應文案庫】or【自行輸入】
A【對應文案庫】：直接選擇文案庫名稱，不管是手動換行or自動換行都正確執行
B-1.【自行輸入】：直接輸入內容(編輯區無法換行)+手動換行
→設定的換行變成只有空白
![image](https://user-images.githubusercontent.com/41721950/50756270-92df1a80-1296-11e9-8824-9923e0e394c6.png)
B-2.【自行輸入】：直接輸入內容(編輯區無法換行)+自動換行
→依照設定換行並且有自動換行
 
※※『個人化內容』excel資料設定兩行文字：
![image](https://user-images.githubusercontent.com/41721950/50758518-5c58ce00-129d-11e9-9f42-0de7922b838a.png)
『個人化內容』可以選擇【對應文案庫】or【顯示資料】
C.【對應文案庫】：文案庫標題與指定欄位同名稱(excel的欄位資料若換行就無法對應)，不管是手動換行or自動換行都正確執行
D-1.【顯示資料】：顯示指定欄位內容+手動換行
→未依照指定位置換行
![image](https://user-images.githubusercontent.com/41721950/50757873-8b6e4000-129b-11e9-94aa-1d8e5cb45203.png)
D-2.【顯示資料】：顯示指定欄位內容+自動換行
→設定的換行變成_x000d_
![image](https://user-images.githubusercontent.com/41721950/50759375-d12d0780-129f-11e9-9ce7-d84f9b22fb73.png)

二、文字量(建議)
因『文案庫』的資料量可以很大，一個『文字元件』可以同時設定『分類行銷內容』與『個人化內容』；
是否可以在『文字元件』固定尺寸的前提下，在**資料量大的時候顯示下拉式捲軸**呢??
以上問題與建議請協助確認並處理，感恩~

**Comment by Gabe-Liu** [comment]
建議的部分要和 @ryzojudy 討論過後再做決定

**Comment by AnitaRyzo** [comment]
B-1.【自行輸入】：直接輸入內容(編輯區無法換行)+手動換行，已正確執行。
![image](https://user-images.githubusercontent.com/41721950/50821106-4c0e2500-1369-11e9-914a-9e35f65ec1d6.png)
D-1.【顯示資料】：顯示指定欄位內容+手動換行，已正確執行。
![image](https://user-images.githubusercontent.com/41721950/50821397-0b62db80-136a-11e9-85bb-a76833f10aa0.png)
D-2.【顯示資料】：顯示指定欄位內容+自動換行，已正確執行。
![image](https://user-images.githubusercontent.com/41721950/50821753-f89cd680-136a-11e9-87f4-28eacdff3657.png)
◎◎ 20190108確認以上測試環境內容 ◎◎

**Comment by ryzojudy** [comment]
針對建議的部分
不知道是否可以在外面的畫布區 外觀尺寸的地方
加一個【固定尺寸】的勾選選項呢?
  非勾選狀態：現行的自動偵測文字內容增加元件高度
  勾選狀態：高度就會固定 當文字內容較多時自動出現卷軸
預設是非勾選狀態

**Comment by AnitaRyzo** [comment]
B-1.【自行輸入】：直接輸入內容(編輯區無法換行)+手動換行，已正確執行。
![image](https://user-images.githubusercontent.com/41721950/51421799-efb7ca80-1bde-11e9-948c-e889d4039ccf.png)
D-1.【顯示資料】：顯示指定欄位內容+手動換行，已正確執行。
![image](https://user-images.githubusercontent.com/41721950/51421817-6f459980-1bdf-11e9-826b-e34af9d03931.png)
D-2.【顯示資料】：顯示指定欄位內容+自動換行，已正確執行。
![image](https://user-images.githubusercontent.com/41721950/51421832-acaa2700-1bdf-11e9-81e3-ad8cca5124b2.png)
◎◎ 20190119確認以上正式環境內容 ◎◎
@ryzojudy 的建議答覆將在#959 執行，請知悉~
