### ISSUE TITLE
【測試環境】資料綁定之輪播圖的照片無法顯示

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#910]
『個人化+輪播圖』可以選擇【對應圖片庫】or【(檔案內的)連結網址】，資料必須存在『上傳檔案』中。
『分類行銷+輪播圖』可以選擇【對應圖片庫】or【自行輸入(連結網址)】
1. 當『輪播圖』在『頁面管理』**未上傳任何圖片**，在『資料綁定』頁面時...
→可以無限增加【+新增替換內容】
→ 不管怎麼操作都無法顯示任何一張圖片
![image](https://user-images.githubusercontent.com/41721950/50804057-55769d80-1327-11e9-96f2-94abb440c385.png)

2. 當『輪播圖』在『頁面管理』**上傳一張圖片**，在『資料綁定』頁面時...
2-1. 『個人化+輪播圖』的【對應圖片庫】無法顯示圖片；【連結網址】可以正確執行。
![image](https://user-images.githubusercontent.com/41721950/50804497-24976800-1329-11e9-9b00-50b1bddf5867.png)
2-2. 『分類行銷+輪播圖』的【對應圖片庫】無法帶入照片；【自行輸入(連結網址)】可以正確執行。
![image](https://user-images.githubusercontent.com/41721950/50804708-3c232080-132a-11e9-84b0-b8ccce5f46a5.png)

3. 當『輪播圖』在『頁面管理』**上傳一張以上圖片**，在『資料綁定』頁面時...
→不管從下拉式選單選擇哪一個圖片，預覽圖只會出現"第一張照片"
![image](https://user-images.githubusercontent.com/41721950/50805506-b012f800-132d-11e9-8e63-6e928848cbd1.png)
PS:【+新增替換內容】會與『頁面管理』上傳的圖片數量相同
![image](https://user-images.githubusercontent.com/41721950/50805451-675b3f00-132d-11e9-8a09-3d89f51860fe.png)
以上問題請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
1.當『輪播圖』在『頁面管理』未上傳任何圖片，在『資料綁定』頁面時直接無法操作
![image](https://user-images.githubusercontent.com/41721950/50822654-326edc80-136d-11e9-8194-68e07277009d.png)
2.當『輪播圖』在『頁面管理』上傳一張圖片，在『資料綁定』的【對應圖片庫】已可執行
![image](https://user-images.githubusercontent.com/41721950/50823141-3c450f80-136e-11e9-80f9-2170a5358e1c.png)
3.當『輪播圖』在『頁面管理』上傳一張以上圖片的預覽圖片仍有錯誤!!
◎◎ 20190108確認以上測試環境內容 ◎◎

**Comment by ryzojudy** [comment]
目前問號內的文字：
支援格式為JPG、PNG、GIF，且大小不可超過10MB
請協助更改為：
。支援格式為JPG、PNG、GIF，且大小不可超過10MB
。若欲進行資料綁定設定，請先上傳預計圖片張數

感謝~

**Comment by AnitaRyzo** [comment]
1.當『輪播圖』在『頁面管理』未上傳任何圖片
→ 小小建議：若欲進行資料綁定設定，請先(至頁面管理)上傳預計圖片張數
→ 提示使用者關於「設定的位置」算是小小的防呆，請 @ryzojudy 參考一下~
![image](https://user-images.githubusercontent.com/41721950/51024380-609a2980-15c4-11e9-8878-a0248faddf64.png)
2&3.當『輪播圖』在『頁面管理』上傳一張或以上的圖片，在『資料綁定』的【對應圖片庫】已可執行
◎◎ 20190111確認以上測試環境內容 ◎◎
