### ISSUE TITLE
【問題】轉蛋機獎品名稱換行失效

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#914]
轉蛋機的獎品使用2個空格想要換行
但是在預覽之中發現仍然在同一行

<img width="601" alt="2019-01-08 3 50 04" src="https://user-images.githubusercontent.com/34327325/50816955-309d1d00-135d-11e9-96be-b62b2582cde6.png">
<img width="352" alt="2019-01-08 3 49 49" src="https://user-images.githubusercontent.com/34327325/50816961-3430a400-135d-11e9-949c-9edc6e019dc5.png">

**Comment by AnitaRyzo** [comment]
所有互動元件在『恭喜中獎』與『中獎紀錄』的頁面中，皆未遵循【雙空格換行】的指示。
『測試結果』頁面也未遵循
![image](https://user-images.githubusercontent.com/41721950/50869301-53c3dd00-13ee-11e9-8081-bff199f5ea1d.png)
以上補充請協助處理，感恩~

**Comment by AnitaRyzo** [comment]
所有互動元件在「預覽」「UAT環境」「發佈後環境」的『恭喜中獎』與『中獎紀錄』的頁面中，皆遵循【雙空格換行】的指示。
◎◎ 20190118確認以上正式環境內容 ◎◎
