### ISSUE TITLE
【建議】審核發布後台中 UAT命名 建議修改

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#915]
目前的專案審核發布後台中，
其中UAT的網址前綴（ex. uat-xxx.ryzoweba.io) 和介面中的的標題，
建議改掉「UAT」這種說法，避免和系統安裝時的UAT混淆。

suggestion from Joe, better name to be discussed.

**Comment by ryuichl** [comment]
#836

**Comment by ryuichl** [comment]
重複了先關掉
