### ISSUE TITLE
【測試環境】資料綁定的匯出資料

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#917]
<img width="433" alt="2019-01-10 10 38 09" src="https://user-images.githubusercontent.com/34327325/50942921-475e8380-14c5-11e9-8cc3-35291223c2cd.png">

<img width="800" alt="2019-01-10 10 43 21" src="https://user-images.githubusercontent.com/34327325/50942928-4fb6be80-14c5-11e9-8f86-63fcc4b6fa45.png">

這個功能目前會直接跳轉WEBA編輯器
會中斷使用者操作體驗
(沒發布的情況下)
但因為沒發布的情況下就已經可以點選這個按鈕了，
如果我剛好編輯了資料綁定裡的分類、資料綁定編輯，
那麼一旦跳出去資料就會消失，雖然weba會問是否恢復專案內容，
但實則這部分資料不會被回復，因此可能需要做調整

**Comment by ryuichl** [comment]
建議調整成未發佈不給下載

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51020497-b0272800-15b9-11e9-9953-e9bb99e1aa43.png)
◎◎ 20190111確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
專案發佈後才會出現『匯出資料』
若一直在專案中，就要重整頁面才會出現『匯出資料』
◎◎ 20190119確認以上正式環境內容 ◎◎
