### ISSUE TITLE
【測試環境】資料綁定編輯的選擇元件 效果不明顯

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#918]
<img width="705" alt="2019-01-10 10 52 26" src="https://user-images.githubusercontent.com/34327325/50943107-07e46700-14c6-11e9-8163-0489b2288baa.png">

以上區塊選擇區塊因為只能從圖層列表裡選擇，因此在預覽畫面裡需要更明顯的使用者回饋
例如：
點選到元件，**自動跳轉**到那個元件的位置，顯示**更明顯的框**(目前的很容易被忽略)

**Comment by AnitaRyzo** [comment]
已降低透明度並加粗框架
![image](https://user-images.githubusercontent.com/41721950/51019695-e3b48300-15b6-11e9-9c6d-0146372ab0e5.png)
◎◎ 20190111確認以上測試環境內容 ◎◎

**Comment by weilyn** [comment]
不好意思請問一下
所以跳到該元件的位置這種做法目前是沒有機會做到的是嗎

**Comment by AnitaRyzo** [comment]
現在只能『長頁面』的時候跳到元件的位置，『跳不同頁面的元件』的部分待研究。
請稍後，感恩~

**Comment by weilyn** [comment]
可是不同頁面的元件不是本來就是分開顯示嗎
所以可以視為很多個長頁面？？

因為資料綁定的使用路徑不是我自己點選頁面或幻燈片以後，才在元件列表裡選擇元件嗎

**Comment by AnitaRyzo** [comment]
『跳不同頁面的元件』會自動切換頁面並以綠粗框線表示
![image](https://user-images.githubusercontent.com/41721950/51422871-8db49080-1bf1-11e9-9135-0f7bf1e85094.png)
◎◎ 20190119確認以上正式環境內容 ◎◎
