### ISSUE TITLE
[建議] 輪播圖改善

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#92]
1.新增預設輪播圖
2.右側圖片排序很難知道看出是哪一張圖片 很難排出自己要的順序

![image](https://user-images.githubusercontent.com/10150807/39801821-01010e04-539f-11e8-9060-2f67a6c93ff9.png)

**Comment by liucwlewis** [comment]
連結：https://zpl.io/aB5DoOA
除了預覽優化之外，，新增了圖片預覽、單一圖片剪裁及跳出提示。提示部分讓使用者能快速在大圖狀態進行排列，同時可進行裁切（可以在評估要不要做）。
![default](https://user-images.githubusercontent.com/37163894/42301528-4da7aef4-8048-11e8-9c75-2968dc873164.png)

**Comment by liucwlewis** [comment]
十字移動圖示：https://drive.google.com/file/d/1HI5NM5FbPZ8BjGnZpbnrS23pvcd-Mbfy/view?usp=sharing
裁切圖示：https://drive.google.com/file/d/15VLUQkPtBFg5m7GEsIAiL-pmHVxWCjIE/view?usp=sharing
