### ISSUE TITLE
【測試環境】資料綁定>分類切換設定的重置按鈕 reset

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#921]
目前WEBA裡面有幾種元件都是可以選擇樣式的，像是表單、抽獎元件
但這些都僅能做小幅度的顏色調整

目前在使用分類切換設定的設計功能
因為大小、位置都是用數字來設定，對使用者來說其實並不友善
他們對於尺寸300px/50px是多少也非常沒概念，更別說XY軸了
再加上這個區域的可調性其實是非常大的，這也表示做失敗的機會也很大
如圖，我隨意嘗試設定這些數值以後，樣式2已經變得看不出原形了，但我實在是調不回去
就算先切換回樣式1，再切換回來樣式2，這個失敗的作品還被保留著
建議可以增加重置的按鈕，讓使用者可以重新做人

<img width="1289" alt="2019-01-10 11 36 24" src="https://user-images.githubusercontent.com/34327325/50944781-bf7c7780-14cc-11e9-9faf-ae55bb5d46cd.png">

題外話，資料綁定裡的預覽畫面很常顯示不完全
如上圖，下方的柵欄式選單樣式就跟設定的不同，以下附上原本的選單示意圖
<img width="1430" alt="2019-01-09 5 22 23" src="https://user-images.githubusercontent.com/34327325/50944817-e6d34480-14cc-11e9-9b58-c1ec3fbf42ee.png">

**Comment by liucwlewis** [comment]
圖片支援：
<img width="801" alt="2019-01-18 5 38 30" src="https://user-images.githubusercontent.com/37163894/51378796-ebd96900-1b48-11e9-9aa1-c34f5a7afd8f.png">


連結：https://zpl.io/a3qPyeQ

**Comment by liucwlewis** [comment]
分類切換設定新增「重設」按鈕在選單狀態右側，點擊後有提示框最後確認是否執行
![2019-01-19 2 16 54](https://user-images.githubusercontent.com/37163894/51423088-f7826980-1bf4-11e9-808d-eaace855e0c4.png)

連結：https://zpl.io/bz1L31M

**Comment by leonlin6** [comment]
與Sam確認後，調整以下兩點地方
1. 點選重設按鈕跳出的提示視窗介面調整樣式，以符合與其他跳出視窗風格統一 
ex. 名單檔案的刪除檔案按鈕->跳出視窗
![image](https://user-images.githubusercontent.com/29088297/56886082-b83fa080-6aa0-11e9-9479-3a972a54c3bc.png)

![image](https://user-images.githubusercontent.com/29088297/56885900-45362a00-6aa0-11e9-846f-80ae56cd10ab.png)

2.  重設按鈕依照「選單狀態[關閉/展開]」的tab選擇出現/消失，選單狀態:展開 的重設按鈕功能設計待以後討論後再決定要不要做。
![image](https://user-images.githubusercontent.com/29088297/56886028-95ad8780-6aa0-11e9-9fca-b574721be640.png)
![image](https://user-images.githubusercontent.com/29088297/56886042-a100b300-6aa0-11e9-9b1a-7d94b7908f01.png)

**Comment by AnitaRyzo** [comment]
按下『重設』按鈕，會回到初始設定
![image](https://user-images.githubusercontent.com/41721950/57835838-04554980-77f2-11e9-9d68-64a44badb894.png)
◎◎ 20190516確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
改變顏色及位置
![921-1](https://user-images.githubusercontent.com/49626114/60077244-2381b800-975c-11e9-9178-e3853efa5957.png)
按下『重設』按鈕，會回到初始設定
![921-2](https://user-images.githubusercontent.com/49626114/60077245-2381b800-975c-11e9-9b1e-20a17b0c3a33.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
