### ISSUE TITLE
【測試環境】在資料綁定中點選申請審核，不會跳轉

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#927]
專案在沒有設定網址、相關資訊的情況下
在資料綁定的編輯頁面點選申請審核
看起來很像送出審核了，其實好像沒有？？
因為網址還沒設定，但是也不會得到任何錯誤提示

<img width="1440" alt="2019-01-10 4 56 59" src="https://user-images.githubusercontent.com/34327325/50957361-04b69e80-14f9-11e9-95bf-84ae5236e7cf.png">

**Comment by AnitaRyzo** [comment]
【申請審核】現有方法為二
1.若在『頁面管理』頁面編輯的任何一處按下【申請審核】，會立刻跳至『發佈設定』頁面
![image](https://user-images.githubusercontent.com/41721950/50960137-9d501d00-14ff-11e9-988e-cac2d20ee4d1.png)
2.在『預覽』頁面時，無法按下【申請審核】。
建議：若已設定域名，在『資料綁定』頁面的【申請審核】開啟；若未設定就跳至『發佈設定』頁面。
以上建議僅供參考，感恩~

**Comment by liucwlewis** [comment]
1. 點擊「申請審核」圖示
![螢幕快照 2019-05-09 上午10 49 14](https://user-images.githubusercontent.com/37163894/57423835-26762700-7248-11e9-9997-1e154739afc3.png)

2. 跳出確認氣泡窗同時跳轉至發佈設定畫面，點擊確認後提出申請。
![螢幕快照 2019-05-09 上午10 49 21](https://user-images.githubusercontent.com/37163894/57423838-2d9d3500-7248-11e9-9dd3-ed93ad607367.png)

3. 若域名未設定/設定有誤，則無法點擊氣泡窗的「確認」按鈕
![螢幕快照 2019-05-09 上午10 49 29](https://user-images.githubusercontent.com/37163894/57423843-31c95280-7248-11e9-96ca-30d102939335.png)

連結：https://zpl.io/bA7MwYo

**Comment by leonlin6** [comment]
已改成「氣泡窗」方式。

**Comment by leonlin6** [comment]
此issue與 「#1383【問題】資料綁定中，點選儲存或發佈的回饋 」 一同修改完內容。

**Comment by AnitaRyzo** [comment]
資料綁定中點選『儲存』或『發佈』後，會跳至『發佈設定』頁
![image](https://user-images.githubusercontent.com/41721950/60777459-1fdf2f80-a165-11e9-8361-1246f1fe1afb.png)
◎◎ 20190708確認以上正式環境內容 ◎◎
