### ISSUE TITLE
【測試環境】資料綁定在的頁面選單設定遺失

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#928]
在製作資料綁定的時候，經常會發現專案選單上的顏色、圖片消失的情況
有時候重新整理又會出現

剛剛發佈一個專案，在編輯器中選單正常
但是發佈後的一般網頁也正常
但是分類網頁就顯示有些問題
如以下
一般網頁：https://testweiwei.ryzoweba.com
分類網頁：https://testweiwei.ryzoweba.com?did=nOcctZZHyE

<img width="1440" alt="2019-01-10 5 03 10" src="https://user-images.githubusercontent.com/34327325/50957695-e3a27d80-14f9-11e9-8054-6503e5565bdd.png">

**Comment by AnitaRyzo** [comment]
討論後的小結論
每次要【+新增分類】時，都從『頁面管理』將「自動」「自訂」的選單架構帶入。
![image](https://user-images.githubusercontent.com/41721950/51008078-2d847580-1585-11e9-88f5-33f085416c2e.png)
PS:『資料綁定』「自訂」的選單架構為每個分類獨立存在，故不會影響『頁面管理』的「自訂」。
請參考以上補充，感恩~

**Comment by AnitaRyzo** [comment]
每次要【+新增分類】時，都從『頁面管理』將「自動」「自訂」的選單架構帶入。
已設立的分類只有「自動」的選單架構會更新。
◎◎ 20190111確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
每次要【+新增分類】時，都從『頁面管理』帶入「自動」「自訂」的現有選單架構。
已設立的分類只有「自動」的選單架構會更新。
◎◎ 20190116確認以上正式環境內容 ◎◎
