### ISSUE TITLE
【測試環境】樞紐分析欄位疑問

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#932]
目前樞紐分析應該是參考GA的設置再做強化(變成雙向)
其中GA的定義中，
<img width="689" alt="2019-01-10 5 36 36" src="https://user-images.githubusercontent.com/34327325/50960208-ca9ccb00-14ff-11e9-826d-fc72c03935ea.png">
Dimension 維度：左側直欄屬性文字
Metrics 指標：位上方橫列，呈現個別維度的數值

基本上指標就是指標，好像不應該變成“值項目”，或是其實有這種說法？但我不確定
另外直欄跟橫欄的項目其實就是直欄維度跟橫欄維度

整體來說，幫使用者把維度跟指標的項目區分很好
但加上樞紐以後的表達方式可能要再確認一下
<img width="330" alt="2019-01-10 5 42 27" src="https://user-images.githubusercontent.com/34327325/50960236-de483180-14ff-11e9-87f9-d68f906cb7ab.png">

**Comment by ryuichl** [comment]
ga可以使用樞紐
在他裡面較資料透視
你可以研究一下
基本上他不是直觀的拿維度和指標來作表格

**Comment by weilyn** [comment]
那名字中文的部分可以先處理一下嗎

**Comment by weilyn** [comment]
哈囉
關於昨天提到的資料透視問題，依據我的理解得出結果如下(與原本大致相同)：
資料透視主要就是將維度放置於X跟Y軸，並且可以同時觀看次要維度的數值
在資料透視裡，直欄可以有主要維度+1個次要維度
橫欄可以有1個資料透視維度
在其之下才是顯示數值的指標

如果替換到WEBA的資料綁定的話，因為我們本身就已經將維度跟指標做劃分
所以下方應該可以變成
直欄項目/橫欄項目---->直欄維度/橫欄維度
值項目---->分析指標(諸如此類)

會建議這樣修改是因為以下理由
1.直欄項目跟橫欄項目裡只能放置上方的“維度選項”，指標是不能存在在這裡的。修正名字可以讓使用者知道那兩個欄位就是只能放置進維度，而不會想把指標放進去，

2.指標因為本來就是為了呈現維度的數值，所以維持上方指標的名詞，或是可以把上下區域合併，但是讓使用者可以調整順序。因為目前在我看來，指標的區塊如果上方用勾選，同時可以讓使用者可以拖曳調整順序的話，似乎也不用分成兩個欄位？這部分還是依UX規劃為主

<img width="1168" alt="2019-01-11 9 56 56" src="https://user-images.githubusercontent.com/34327325/51011043-da64ef80-1591-11e9-8df9-fe9d6b9bf8de.png">

另外建議下方兩個欄位中加入類似以下ICON，讓人知道是可以跨欄移動的
以及，如果其中一欄(橫向)沒有加入項目的話，就無法按確認
除了現有的防呆外，建議有氣泡窗告知要加入比較項目
<img width="208" alt="2019-01-11 11 15 48" src="https://user-images.githubusercontent.com/34327325/51011196-8f97a780-1592-11e9-9b48-1cd3aecb090f.png">

以上如果有理解錯誤再麻煩告知指教

**Comment by ryzojudy** [comment]
如果是直接以GA的狀況來進行調整的話
那是不是改成這樣比較符合他們GA的使用狀況??

直欄項目：維度項目
橫列項目：主要依據
值項目：分析指標

不知道這樣 大家有沒有別的想法呢??

**Comment by weilyn** [comment]
維度項目跟依據裡面的內容是共通的
但是名詞卻不一樣，不知道會不會讓使用者不易理解
並且WEBA裡可以新增一個以上的依據，因此可以一次比較多個維度，多個依據

**Comment by ryzojudy** [comment]
Anita建議：
可以利用顏色去區分上面的兩大類項目與下面三個區域之間的關係
