### ISSUE TITLE
【測試環境】網站數據的顯示更多

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#933]
同樣資料筆數的情況下
**其實不需要展開就可以看到全部內容**
**以及有些可以展開，有些無法展開**
**數值的位置有些是平行，有些在下一列 規則是什麼？**

以上三個問題
<img width="1343" alt="2019-01-10 5 23 42" src="https://user-images.githubusercontent.com/34327325/50960462-69c1c280-1500-11e9-93d2-5b8acd9b527b.png">

**Comment by ryuichl** [comment]
不展開的情況下他會顯示固定數量
超過才會看的出差異
