### ISSUE TITLE
【測試環境】數據後台台灣地圖變形

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#936]
台灣地圖壓窄了

![2019-01-11 2 00 33](https://user-images.githubusercontent.com/34327325/51016011-94b42100-15a9-11e9-8b34-01934188ce48.png)

**Comment by ai015606220** [comment]
這是因為我目前使用的GeoJSON所繪製出來的台灣就是這麼瘦, 會再尋找更適合的設定檔

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51163245-048d1900-18d4-11e9-84f4-511b0775e1aa.png)
◎◎ 20190115確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51423285-c86df700-1bf8-11e9-9fe6-f285976ba228.png)
◎◎ 20190119確認以上正式環境內容 ◎◎
