### ISSUE TITLE
【測試環境】網站數據細項查看的縮放情況問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#938]
目前網站數據裡的細項，似乎有可以讓人使用滑鼠滾輪來進行縮放
以下這種線段圖形在縮放後會進入一個完全沒出現任何線段的狀態，
水平無法拖曳

![2019-01-11 2 01 31](https://user-images.githubusercontent.com/34327325/51016326-e4471c80-15aa-11e9-866d-fb92c5589501.png)
![2019-01-11 1 59 20](https://user-images.githubusercontent.com/34327325/51016328-e6a97680-15aa-11e9-8ac0-1184a1acf3b6.png)

**Comment by ai015606220** [comment]
因為你縮放到座標只剩一天, 你如果滑鼠移過去, 會有座標點出現

水平可以拖曳, 只是當你縮得這麼小的時候, 他的判定範圍會變大, 所以你拖曳的幅度也要變大才會觸發
