### ISSUE TITLE
【測試環境】數據細項建議加上橫向滾軸

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#939]
目前數據細項經過縮放後，可以使用滑鼠拖曳方式來查看其他內容
但是當放到最大的時候，就會變得很不容易拖曳
建議可以同時開放 拖曳手勢與下方的橫向捲軸

![2019-01-11 2 13 58](https://user-images.githubusercontent.com/34327325/51016484-7bac6f80-15ab-11e9-9769-502e629da525.png)
![2019-01-11 2 14 17](https://user-images.githubusercontent.com/34327325/51016488-7d763300-15ab-11e9-8879-4213e7bdfff7.png)

**Comment by ai015606220** [comment]
當初我有試著研究過這點
但這個要求有點牴觸這項套件的架構
所以可能暫時無法修改
