### ISSUE TITLE
【測試環境】數據後台的發布時間/結束時間

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#940]
數據後台上方有個發佈時間與結束時間，發佈沒問題，自然是我最後一次將網站上線的時間
那結束時間呢？
因為專案本身並沒有開啟專案排程的功能

![2019-01-11 2 37 09](https://user-images.githubusercontent.com/34327325/51017350-c2e82f80-15ae-11e9-9d89-561d74427c39.png)
而且因為預設開始與結束時間可能是創專案的日期
所以使用者可能看到會以為他的專案下線了

**Comment by Samasianspock** [comment]
情境一：專案發佈設定 專案開啟「啟動」開啟時間設定「未勾選」時，不顯示結束時間。
情境二：專案發佈設定 專案開啟「關閉」開啟時間設定「勾選啟動」有設定時間，要顯示結束時間。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51153468-4bb2e400-18ab-11e9-811e-cb0f1fbc9092.png)
◎◎ 20190115確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/51423325-6792ee80-1bf9-11e9-8de9-eeace54eb1a9.png)
◎◎ 20190119確認以上正式環境內容 ◎◎

**Comment by liucwlewis** [comment]
在專案部分新增圓點協助辨識專案的狀態，分為兩種：1.上線中（綠色） 2.已下線（紅色）。有部份希望能調整，在尚無設定結束時間時，時間位置顯示「尚無設定」
<img width="1261" alt="2019-01-19 3 43 26" src="https://user-images.githubusercontent.com/37163894/51423856-03742880-1c01-11e9-9e6f-eb5f88536cff.png">

位置：https://zpl.io/aREN8wn
