### ISSUE TITLE
【問題】選單架構在頁面間切換與名稱的正確性

### ISSUE THREAD

**Issue by AnitaRyzo** [ryuichl/v3-report#942]
由選單架構示意圖可知，『頁面B』的第二層為『電話』與『C錨點』
![image](https://user-images.githubusercontent.com/41721950/51094069-b5b48600-17e4-11e9-8c9c-0de49cc4be44.png)
選擇『C錨點』應維持在『頁面B』的選單架構；但由下圖可知已切換到『頁面C』。
![image](https://user-images.githubusercontent.com/41721950/51094115-34112800-17e5-11e9-9fe5-1956aa6febf5.png)

以上問題請協助處理，感恩~

**Comment by ryuichl** [comment]
C錨點本來就在頁面C 感覺切換到頁面C是正常的吧?

**Comment by AnitaRyzo** [comment]
選單架構『頁面』的第二層不管怎麼切換都會在原有的『頁面』
◎◎ 20190115確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
選單架構『頁面』的第二層不管怎麼切換都會在原有的『頁面』
◎◎ 20190116確認以上正式環境內容 ◎◎
