### ISSUE TITLE
數據分析的離開率

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#945]
![image](https://user-images.githubusercontent.com/10150807/51163258-0f47ae00-18d4-11e9-8935-67d350d8fdcc.png)

目前在網站數據內是有離開率這個數值
但根據ga對離開率解釋
https://support.google.com/analytics/answer/2525491?hl=zh-Hant&ref_topic=6156780

是否離開率這個數值比較適用於分頁上?
感覺不應該在全站數據也呈現

**Comment by ryzojudy** [comment]
這邊跟sam的討論後 覺得可以拿掉

**Comment by AnitaRyzo** [comment]
數據後台的『網站數據』已移除『離開率』
![image](https://user-images.githubusercontent.com/41721950/57830445-b9810500-77e4-11e9-95a3-1a38f8af3f1a.png)
數據後台的『分頁』保留『離開率』
![image](https://user-images.githubusercontent.com/41721950/57831467-cbb07280-77e7-11e9-8dfc-8826d094a26b.png)
但**在『樞紐設定』的非分頁仍可以選擇『離開率』**
@ryzojudy 請協助確認此處的離開率要如何顯示?? 感恩
![image](https://user-images.githubusercontent.com/41721950/57831234-24cbd680-77e7-11e9-9bde-c8abed285cdf.png)
◎◎ 20190516確認以上測試環境內容 ◎◎

**Comment by ryzojudy** [comment]
跟sam討論完後
在專案的離開率顯示時，顯示【NA】
感謝~~

**Comment by leonlin6** [comment]
於『樞紐設定』頁面規則：
若未選取Dimension 「分頁」，有選取Metrics「離開率」，則顯示N/A
若有選取Dimension 「分頁」，有選取Metrics「離開率」，則正常顯示數值。

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/59591125-0b88b380-9120-11e9-87f8-e1e152a4bd34.png)
◎◎ 20190617確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
數據後台的『網站數據』已移除『離開率』，『分頁』保留『離開率』
『樞紐設定』有「分頁」才有「離開率」資料
![image](https://user-images.githubusercontent.com/41721950/60502226-fa2ed200-9cef-11e9-9013-7742ba481341.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
