### ISSUE TITLE
【問題】專案產出的 QR CODE 不易掃描

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#946]
測試過 iphone最新系統情況下，內建/line/第三方 皆無法正確掃描
但是掃其他軟體產生的QR CODE則沒問題
可能是產出的條碼太複雜

再麻煩協助測試

<img width="710" alt="2019-01-15 3 38 02" src="https://user-images.githubusercontent.com/34327325/51165620-ca277a00-18db-11e9-92c4-7294fa2cd641.png">

**Comment by ai015606220** [comment]
初步會先讓周圍留白的區域變寬、降低QR code的複雜度
再後續觀察成效

**Comment by AnitaRyzo** [comment]
目前可順利掃描QR code
◎◎ 20190119確認以上正式環境內容 ◎◎
