### ISSUE TITLE
【問題】表單預設文字設定不一致

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#948]
單行文字和多行文字的預設文字顏色不一致
但這個是使用者無法自行修改的項目
如果可以讓使用者自己修改顏色就更好了，
或是會自己偵測 深色背景>白色，淺色背景>黑灰色
諸如此類

<img width="423" alt="2019-01-15 5 23 53" src="https://user-images.githubusercontent.com/34327325/51171015-c0f1d980-18ea-11e9-9eeb-86de8a0b059d.png">
<img width="345" alt="2019-01-15 5 23 49" src="https://user-images.githubusercontent.com/34327325/51171016-c0f1d980-18ea-11e9-842d-1b953db9213e.png">

**Comment by AnitaRyzo** [comment]
單行文字和多行文字的預設文字顏色已一致
![image](https://user-images.githubusercontent.com/41721950/51374689-bdef2700-1b3e-11e9-80c0-9cc857555e21.png)
暫無偵測顏色的功能
◎◎ 20190118確認以上正式環境內容 ◎◎
