### ISSUE TITLE
[建議] 頁籤樣式選擇

### ISSUE THREAD

**Issue by ryuichl** [ryuichl/v3-report#95]
目前給的頁籤樣式
切換時並沒有同時變換成如示意中的顏色
導致看起來沒有太大差異

![image](https://user-images.githubusercontent.com/10150807/39803722-73d36b98-53a4-11e8-9ab0-fd77e59d15cd.png)

**Comment by AnitaRyzo** [comment]
頁籤樣式與頁籤顏色選擇後，畫布中的頁籤會同步變化
![image](https://user-images.githubusercontent.com/41721950/45272018-51538400-b4dd-11e8-9385-bbad2c2b8d9f.png)
