### ISSUE TITLE
【建議】編輯區左列的選單可以加入氣泡窗

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#951]
如WEBA管理頁面中
滑鼠碰到左側控制欄 會有氣泡窗滑出 讓用戶知道點進去是什麼項目的編輯
<img width="204" alt="2019-01-17 10 40 28" src="https://user-images.githubusercontent.com/34560641/51292070-7dab7e00-1a44-11e9-8905-74fb5c80efa4.png">
建議在編輯區中 左側也可以有類似的氣泡窗 當滑鼠游標滑到左側控制欄時
也可以出現這些項目代表的意思
<img width="248" alt="2019-01-17 10 40 18" src="https://user-images.githubusercontent.com/34560641/51298215-b8baab00-1a5e-11e9-9ca4-d6bb72377d97.png">

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55044653-20503080-5076-11e9-8127-e541c54e8770.png)
◎◎ 20190327確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
如上已有氣泡窗
◎◎ 20190408確認以上正式環境內容 ◎◎
