### ISSUE TITLE
【問題】個人化後的網址後參數 LINE電腦版無法帶有連結

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#952]
目前的個人化網址 因為在域名後面帶有後綴
在LINE電腦版中 後面的網址不會被帶入連結
導致開啟時只會開啟沒有個人化參數的網址 如下圖所示
<img width="358" alt="2019-01-17 2 08 12" src="https://user-images.githubusercontent.com/34560641/51298907-7d6dab80-1a61-11e9-8419-7f519f434e76.png">

目前作法是可以在網址後面加一個斜線「/」
LINE電腦版就會判定為網址 一起把後面的參數加入連結中
<img width="359" alt="2019-01-17 2 08 20" src="https://user-images.githubusercontent.com/34560641/51298947-95ddc600-1a61-11e9-958e-a3a3213b4c84.png">

敬請協助改善 感謝

**Comment by AnitaRyzo** [comment]
LINE電腦版已可帶入連結
![image](https://user-images.githubusercontent.com/41721950/51423425-dde42080-1bfa-11e9-8376-a505acf8e4e0.png)
附註：在FB也會自動帶連結
![image](https://user-images.githubusercontent.com/41721950/51423411-9a89b200-1bfa-11e9-90cf-504a4302d8b2.png)
◎◎ 20190119確認以上正式環境內容 ◎◎
