### ISSUE TITLE
【問題】寄送至指定信箱出現神秘編碼

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#955]
如下圖，
主要是使用者自己輸入的中文字會變成神秘編碼
原文字為 
1.17 測試結果表單

<img width="842" alt="2019-01-18 10 43 37" src="https://user-images.githubusercontent.com/34327325/51362335-1823c400-1b0e-11e9-9c84-b39874dcd8bf.png">

**Comment by AnitaRyzo** [comment]
已更改為中文顯示
![image](https://user-images.githubusercontent.com/41721950/51423767-dffcae00-1bff-11e9-8f82-089a4b15f122.png)
◎◎ 20190119確認以上正式環境內容 ◎◎
