### ISSUE TITLE
【建議】表單選項中要有一題可以點選「其他」並可以輸入答案

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#958]
如題

**Comment by Samasianspock** [comment]
已經完成設計了，目前加入其他選項的表單題目有「單選題型」「複選題型」「下拉式題型」，在線上申請書也有特定的題目會有其他選項的功能，可以期待日後線上申請書上線時使用。
![issue 958](https://user-images.githubusercontent.com/37531593/51449541-74355500-1d67-11e9-8e49-0a347dde9e68.jpg)

**Comment by liucwlewis** [comment]
連結：https://zpl.io/adN4Pzn
包含了其他的相關建議，
issue修改需求書連結：https://docs.google.com/document/d/1zXzxaLeDraQZRp0cfz9-3TmXNzCFfwtt1J62svbpQiI/edit
