### ISSUE TITLE
【問題】資料綁定-個人化圖片預覽時無法顯示

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#968]
資料綁定編輯 
個人化圖片設定(截圖中的金牌圖)
名次欄位對應圖片庫
<img width="1280" alt="2019-01-21 5 30 23" src="https://user-images.githubusercontent.com/34293268/51465459-ed9e6900-1da2-11e9-9af9-5cd4b3af1dcb.png">
<img width="1280" alt="2019-01-21 5 30 53" src="https://user-images.githubusercontent.com/34293268/51465487-fc851b80-1da2-11e9-8917-5a406144c379.png">

編輯時可以看見顯示對應的圖片
<img width="1279" alt="2019-01-21 5 30 41" src="https://user-images.githubusercontent.com/34293268/51465533-0c046480-1da3-11e9-9b0d-dcd0aa2ac4c7.png">

但預覽時看不見(紅框框處)
請協助解惑～～感恩的心～～～～

<img width="1280" alt="2019-01-21 5 31 12" src="https://user-images.githubusercontent.com/34293268/51465555-145c9f80-1da3-11e9-89e0-a82f78e249e1.png">

**Comment by ryuichl** [comment]
@AnitaRyzo  @Gabe-Liu  @ai015606220

**Comment by AnitaRyzo** [comment]
個人化內容-編輯區的狀況
![image](https://user-images.githubusercontent.com/41721950/52831469-be63e900-310f-11e9-998d-e309dc4821d4.png)
個人化內容-預覽與瀏覽器執行
![image](https://user-images.githubusercontent.com/41721950/52831859-3252c100-3111-11e9-83ec-161c15cfaadd.png)
◎◎ 20190215確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55463753-46547280-562c-11e9-92a2-4ff7a45e031c.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
