### ISSUE TITLE
【問題】點擊資料綁定編輯時上方選項會跑版

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#972]
不知道是不是13吋的問題，再麻煩了～
![1548129073127](https://user-images.githubusercontent.com/37163894/51511405-250d2400-1e3c-11e9-8293-981505aa821c.jpg)

**Comment by AnitaRyzo** [comment]
目前發現只有選擇『資料綁定編輯』頁時，會自動縮小成如上畫面
以上補充請參考，感恩~

**Comment by AnitaRyzo** [comment]
『資料綁定編輯』頁已不會縮小
◎◎ 20190215確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
『資料綁定編輯』頁已不會縮小
![image](https://user-images.githubusercontent.com/41721950/55462655-d0e7a280-5629-11e9-995f-eae35637bb4e.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
