### ISSUE TITLE
【建議】資料綁定編輯中，“分類行銷內容”中的設定項目想改名稱

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#973]
“設定項目”改為“選擇變動項目”
<img width="649" alt="2019-01-22 12 03 27" src="https://user-images.githubusercontent.com/37163894/51511874-09a31880-1e3e-11e9-9773-68617651bb66.png">

跳出的提示框標題也改為“變動項目選擇”
<img width="647" alt="2019-01-22 12 03 33" src="https://user-images.githubusercontent.com/37163894/51511879-10ca2680-1e3e-11e9-901e-aff26d712e96.png">

連結：https://zpl.io/bz1Zg6z

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57992775-94440d80-7ae8-11e9-9422-1dde5270fb7b.png)
◎◎ 20190520確認以上測試環境內容 ◎◎

**Comment by cocosu123** [comment]
![973](https://user-images.githubusercontent.com/49626114/60076870-3a73da80-975b-11e9-920d-d8c777391820.png)
◎◎ 20190625確認以上正式環境內容 ◎◎
