### ISSUE TITLE
【問題】手勢評分拖拉軸有些沒有顏色

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/v3-report#977]
![s__56655875](https://user-images.githubusercontent.com/34560641/51578048-16377780-1ef7-11e9-9f54-9fdf1089377c.jpg)
如題
拖拖拉後的軸顏色部分
有些評分後 還是灰色
請明察

**Comment by ai015606220** [comment]
會出現這種情況的原因是
當第一次操作時, 直接從右側灰白的bar點擊並拖拉
經過測試只有手機操作有這種問題
且這是所使用的套件 Angular material 本身就有的問題
後續會想辦法有沒有辦法避免類似的操作
