### ISSUE TITLE
【問題】資料綁定的圖片庫選取

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#980]
資料綁定裡的圖片庫
圖片左上角有選取的圓圈
但是不能點選
是不是還沒做到這個功能
或是有特殊的使用方法
<img width="1281" alt="2019-01-23 10 44 40" src="https://user-images.githubusercontent.com/34327325/51579499-230a9a00-1efc-11e9-8add-19bc67d6f12c.png">

**Comment by AnitaRyzo** [comment]
圖片左上角選取的圓圈，目前是點選如下圖填滿綠色的部分隨意一處才會開啟勾選
![image](https://user-images.githubusercontent.com/41721950/51579768-1dfa1a80-1efd-11e9-8104-db9616e356d3.png)
請參考~

**Comment by weilyn** [comment]
可是排除圓圈那個點似乎不是很合理吧
精準點選的人反而無法使用

**Comment by AnitaRyzo** [comment]
除了黃框內的三項功能，整張圖片隨處點擊都可以選取圖片
![image](https://user-images.githubusercontent.com/41721950/52833738-40a4db00-3119-11e9-996b-9f1e3d5b9bf3.png)
◎◎ 20190215確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
除了黃框內的三項功能，整張圖片隨處點擊都可以選取圖片
![image](https://user-images.githubusercontent.com/41721950/55464442-bca5a480-562d-11e9-97e3-9c5adb6000c1.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
