### ISSUE TITLE
[表單問題反應]表單題目過長時，其台顯示會超出畫面，建議可以有換行功能

### ISSUE THREAD

**Issue by katrinaliu** [ryuichl/v3-report#981]
如題，建議表單編排有換行功能!以方便編輯。

**Comment by AnitaRyzo** [comment]
表單題目過長已會自動換行
![image](https://user-images.githubusercontent.com/41721950/59650723-9e296100-91b9-11e9-9bd8-ccd6140f4dbf.png)
◎◎ 20190618確認以上正式環境內容 ◎◎
