### ISSUE TITLE
【建議】資料綁定>資料綁定編輯標題雙擊修改

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#982]
建議資料綁定>資料綁定編輯的標題可以雙擊修改
與互動元件、或是WEBA其他地方的操作維持一貫的流程

<img width="805" alt="2019-01-23 10 48 03" src="https://user-images.githubusercontent.com/34327325/51584920-59ebaa80-1f12-11e9-8f02-dc6eee22a6a8.png">

**Comment by AnitaRyzo** [comment]
雙擊修改名稱
![image](https://user-images.githubusercontent.com/41721950/54891778-a1c68800-4ee9-11e9-9eb8-fcdf2e11e007.png)
◎◎ 20190325確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
資料綁定編輯標題皆可雙擊修改
◎◎ 20190403確認以上正式環境內容 ◎◎
