### ISSUE TITLE
【問題】跨帳號查詢表單欄位資料遺失

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#985]
跨帳號查詢表單
專案的名稱欄位資料空白
(專案沒有刪除)
<img width="1230" alt="2019-01-23 3 07 00" src="https://user-images.githubusercontent.com/34327325/51589129-0d5b9b80-1f21-11e9-8eee-8cba5a716367.png">

**Comment by ai015606220** [comment]
這裡疏忽了
已修改成跨帳號取得站點

但如果他的專案已被刪除的話
表單回覆裡的專案欄位也會變成空白的

**Comment by AnitaRyzo** [comment]
『表單回覆』皆可看到專案名稱
![image](https://user-images.githubusercontent.com/41721950/52702726-b5600400-2fb7-11e9-89ec-be6cdc300b63.png)
◎◎ 20190213確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/55705740-16351700-5a12-11e9-9e4e-8e7a069bc07f.png)
◎◎ 20190408確認以上正式環境內容 ◎◎
