### ISSUE TITLE
【問題】當資料庫使用MSSQL時，資料綁定頁面異常

### ISSUE THREAD

**Issue by Kyle30** [ryuichl/v3-report#986]
如題，每個站點在**"初次"**點擊資料綁定頁面時，應該要新增一筆資料綁定相關數據 ( POST /site/:site_id/databinding )
但在使用 mssql 作為資料庫時，不會送出這個請求

使用 mongodb 是正常，如下面兩張圖
![image](https://user-images.githubusercontent.com/11918396/51593436-1eaaa500-1f2d-11e9-9850-d5daa959c0c3.png)
![image](https://user-images.githubusercontent.com/11918396/51593478-36822900-1f2d-11e9-9006-afb40e2bc563.png)

而使用 mssql ，不會觸發該 API ， 如下圖所示
![image](https://user-images.githubusercontent.com/11918396/51593148-5f55ee80-1f2c-11e9-8d67-f9d8fa7d00b7.png)

**Comment by ryuichl** [comment]
已解
先關掉
