### ISSUE TITLE
【問題】裁切圖片的提示框尺寸需調整

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#987]
資料綁定編輯
圖片庫內裁切圖片的提示框
小螢幕使用者(我QQ) 的標題會被擋住
無法取消裁切動作
<img width="1280" alt="2019-01-24 11 10 11" src="https://user-images.githubusercontent.com/34293268/51652021-17d17000-1fc9-11e9-8807-23f315e697df.png">

需縮小至90%時標題才會出現
<img width="1280" alt="2019-01-24 11 10 37" src="https://user-images.githubusercontent.com/34293268/51652124-7991da00-1fc9-11e9-9b04-12f77986906e.png">

**Comment by AnitaRyzo** [comment]
已將比例縮小
![image](https://user-images.githubusercontent.com/41721950/52697888-5b5a4100-2fad-11e9-984f-34dc304610a7.png)
◎◎ 20190213確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
圖片剪裁的最小比例![image](https://user-images.githubusercontent.com/41721950/55467035-00e77380-5633-11e9-8f62-4ffc62335e3a.png)
◎◎ 20190403確認以上正式環境內容 ◎◎
