### ISSUE TITLE
【建議】表單的題目下方線段刪除及表單填答體驗優化

### ISSUE THREAD

**Issue by weilyn** [ryuichl/v3-report#988]
看過賓客現場填寫後
發現有為數不少的賓客在填寫時會點擊題目下的線段想要填寫，
但實際答案的填寫線段在下一欄，
建議可以將題目下的線段刪除，讓每一題就只有一條線

詳細修改需求請參閱下方留言

<img width="208" alt="2019-01-24 11 57 48" src="https://user-images.githubusercontent.com/34327325/51653737-c1b3fb00-1fcf-11e9-982a-b4f49e82b6ea.png">

**Comment by Samasianspock** [comment]
目前的題目底線會固定出現，主要是區隔題目與副標題，建議可以讓底線在有設定副標題時才會出現。

**Comment by weilyn** [comment]
補充：
觀察到user喜歡點擊圖片中黃色區域來填寫表單
原因不排除有以下
1.題目下有一條線讓人想點擊輸入文字
2.使用者可能很容易直覺認為點題目就可以填寫
3.同一個題目裡，題目與作答區距離太遠，跟下一題的間距曖昧不清

我個人在這邊針對第三點提出一個想法，表單中的題目間距選項只影響題目跟題目之間的距離，不影響題目與答案的距離，並且題目跟答案的距離可以稍近一點
其餘部分請UX與產品考慮過後與我討論

<img width="429" alt="螢幕快照 2019-04-19 下午2 03 20" src="https://user-images.githubusercontent.com/34327325/56409649-a265fa80-62ac-11e9-8e81-5d52dcb519cd.png">

**Comment by AnitaRyzo** [comment]
![image](https://user-images.githubusercontent.com/41721950/57993869-601f1b80-7aed-11e9-885e-5b69a6174776.png)
◎◎ 20190520確認以上測試環境內容 ◎◎

**Comment by weilyn** [comment]
請問988的需求修改是依照最新版本的需求修改建議書修改的嗎？

<img width="254" alt="螢幕快照 2019-05-20 上午10 57 11" src="https://user-images.githubusercontent.com/34327325/57994091-1b47b480-7aee-11e9-9898-c801dd15c6a7.png">
<img width="442" alt="螢幕快照 2019-05-20 上午10 57 37" src="https://user-images.githubusercontent.com/34327325/57994092-1b47b480-7aee-11e9-9cf9-6ae14646f413.png">

**Comment by ryuichl** [comment]
尚未修改

**Comment by AnitaRyzo** [comment]
測試環境(左圖)與正式環境(右圖)對照，完成進度如下：
1.刪除題目下方的線段，只有填答的區域有線段(如黃框)
2.調整題目內與題目間的預設間距(如綠框)
題目間距0px
![image](https://user-images.githubusercontent.com/41721950/58847197-ae6b1780-86b4-11e9-8af0-f982c718e5c4.png)
題目間距100px
![image](https://user-images.githubusercontent.com/41721950/58847485-b9727780-86b5-11e9-8f55-826bdac30e59.png)

X『工程不建議』將題目點擊感應區範圍擴大
◎◎ 20190604確認以上測試環境內容 ◎◎

**Comment by AnitaRyzo** [comment]
1.只有填答的區域有線段
2.調整題目內與題目間的預設間距
![image](https://user-images.githubusercontent.com/41721950/60503251-e84e2e80-9cf1-11e9-8b97-98951afed8e7.png)
◎◎ 20190702確認以上正式環境內容 ◎◎
