### ISSUE TITLE
【表單-題目編輯】希望點選題目的標題時就可直接進入編輯狀態

### ISSUE THREAD

**Issue by liucwlewis** [ryuichl/v3-report#99]
希望點選題目的標題時就可直接進入編輯狀態
<img width="1128" alt="2018-05-09 5 42 08" src="https://user-images.githubusercontent.com/37163894/39808002-5f375e2c-53b0-11e8-86ab-e97939c712a1.png">

**Comment by ryuichl** [comment]
可以雙擊進入編輯

**Comment by liucwlewis** [comment]
好的
