### ISSUE TITLE
【問題】背景設定的顏色無法貼上色碼

### ISSUE THREAD

**Issue by eatinggg** [ryuichl/v3-report#995]
背景設定裡的「**背景顏色**」、「**背景顏色(液版)**」
無法貼上八位數的色碼 #f9a995ff
只能從色票中選取顏色、調整

圖一
貼上八位數色碼後無反應
<img width="1280" alt="2019-01-28 12 23 13" src="https://user-images.githubusercontent.com/34293268/51816762-1a063800-2303-11e9-849a-c984e3c621a9.png">

圖二
直接選取色票可更改顏色
<img width="1280" alt="2019-01-28 12 23 23" src="https://user-images.githubusercontent.com/34293268/51816767-1ecaec00-2303-11e9-9365-a22491810687.png">

圖三
貼上六位數色碼可改變顏色
<img width="1280" alt="2019-01-28 1 48 30" src="https://user-images.githubusercontent.com/34293268/51816867-7b2e0b80-2303-11e9-8d44-c4aa77bfdb28.png">

**Comment by ai015606220** [comment]
這是因為這裡不能設定透明度 (不能做設定的理由可能要請問 @Gabe-Liu)
所以色碼只有6碼

**Comment by Gabe-Liu** [comment]
因為在換幻燈片動畫時，如果是有透明度的背景，可能會看到後面上一個或下一個的幻燈片
